In [1]:
import pandas as pd

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option("display.max_colwidth", None)

In [2]:
df = pd.read_csv(r'/home/user/Downloads/DataHut_CH_Lidl_PriceExtractions_20260814.CSV', low_memory=False, sep='|')

In [3]:
mask = (
    df["product_unique_key"].astype(str)
    !=
    (df["unique_id"].astype(str) + "P")
)

issues = df.loc[mask, ["unique_id", "product_unique_key", "pdp_url"]].copy()
issues["row_no"] = issues.index + 2

issues = issues[["row_no", "pdp_url", "unique_id", "product_unique_key"]]

issues

KeyError: 'product_unique_key'

In [3]:
df.isnull().sum()

unique_id                   0
competitor_name             0
extraction_date             0
product_name                0
grammage_quantity           0
grammage_unit               0
regular_price               0
selling_price               0
price_valid_from         3044
price_per_unit            432
percentage_discount      3315
promotion_price          3313
promotion_valid_from     3044
promotion_valid_upto     3366
promotion_description    2980
currency                    0
breadcrumb                  0
pdp_url                     0
region                   3620
pack_size                3620
site_shown_uom            432
dtype: int64

In [4]:
import pandas as pd

text_cols = df.select_dtypes(include="object").columns

issues = {}

for col in text_cols:
    mask = (
        df[col]
        .fillna("")
        .astype(str)
        .str.contains(r"(?<!\\)\|", regex=True)
    )

    if mask.any():
        temp = df.loc[mask, ["pdp_url", col]].copy()
        temp.insert(0, "row_no", temp.index)  # DataFrame row number
        issues[col] = temp

# Print results
if issues:
    print("Columns containing unescaped '|':\n")

    for col, data in issues.items():
        print(f"\n=== {col} ({len(data)} rows) ===")
        print(data.to_string(index=False))
else:
    print("No unescaped '|' found.")

No unescaped '|' found.

In [5]:
import pandas as pd

escape_pattern = r'[\n\r\t\b\f\v]'

issues = []

for col in df.select_dtypes(include="object").columns:
    mask = df[col].fillna("").astype(str).str.contains(
        escape_pattern,
        regex=True,
        na=False
    )

    if mask.any():
        temp = df.loc[mask, [col]].copy()
        temp.insert(0, "row_no", temp.index + 2)
        temp["column"] = col
        temp["issue_value"] = temp[col]

        if "pdp_url" in df.columns:
            temp["pdp_url"] = df.loc[mask, "pdp_url"]

        issues.append(
            temp[["row_no", "pdp_url", "column", "issue_value"]]
        )

if issues:
    result = pd.concat(issues, ignore_index=True)

    print("=== Escape Character Issues ===")
    print(result.to_string(index=False))
    print(f"\nTotal issues: {len(result)}")
else:
    print("No escape characters found.")

No escape characters found.

In [5]:
import pandas as pd

text_cols = df.select_dtypes(include="object").columns

issues = {}

for col in text_cols:
    # Match | not preceded by a backslash
    mask = (
        df[col]
        .fillna("")
        .astype(str)
        .str.contains(r"(?<!\\)\|", regex=True)
    )

    if mask.any():
        issues[col] = df.loc[mask, ["unique_id", col]]

# Print results
if issues:
    print("Columns containing unescaped '|':\n")
    for col, data in issues.items():
        print(f"\n=== {col} ({len(data)} rows) ===")
        print(data.to_string(index=False))
else:
    print("No unescaped '|' found.")

No unescaped '|' found.

In [7]:
df.shape

(3620, 21)

In [13]:
empty_cols = df.columns[df.isna().all()].tolist()
empty_cols

['price_valid_from',
 'percentage_discount',
 'promotion_valid_from',
 'promotion_valid_upto',
 'region',
 'pack_size']

In [8]:
req_cols = """unique_id,competitor_name,extraction_date,product_name,grammage_quantity,grammage_unit,regular_price,selling_price,price_valid_from,price_per_unit,percentage_discount,promotion_price,promotion_valid_from,promotion_valid_upto,promotion_description,currency,breadcrumb,pdp_url,region,pack_size,
site_shown_uom"""

req_cols = [c.strip() for c in req_cols.split(",") if c.strip()]

missing = [c for c in req_cols if c not in df.columns]
extra = [c for c in df.columns if c not in req_cols]

print("Requirement columns" \
":", len(req_cols))
print("File columns:", len(df.columns))
print("Missing:", missing)
print("Extra:", extra)
print("Order matches:", req_cols == list(df.columns))

Requirement columns: 21
File columns: 21
Missing: []
Extra: []
Order matches: True

In [9]:
df.competitor_name.value_counts()

competitor_name
lidl    3620
Name: count, dtype: int64

In [10]:
# Empty columns as per requirement
req_empty = """ """

req_empty = [c.strip() for c in req_empty.split(",") if c.strip()]

# Empty columns in the file
file_empty = df.columns[df.isna().all()].tolist()

# Compare
missing_empty = [c for c in req_empty if c not in file_empty]
unexpected_empty = [c for c in file_empty if c not in req_empty]
matching_empty = [c for c in req_empty if c in file_empty]

print("Requirement empty columns :", len(req_empty))
print("File empty columns        :", len(file_empty))
print("Matching                 :", len(matching_empty))
print("Expected empty but not empty:", missing_empty)
print("Unexpected empty columns     :", unexpected_empty)

Requirement empty columns : 0
File empty columns        : 2
Matching                 : 0
Expected empty but not empty: []
Unexpected empty columns     : ['region', 'pack_size']

In [12]:
df.isnull().sum()

unique_id                    0
competitor_name              0
extraction_date              0
product_name                 0
grammage_quantity            0
grammage_unit                0
regular_price               19
selling_price               19
price_valid_from         41191
price_per_unit           16995
percentage_discount      41191
promotion_price          38938
promotion_valid_from     41191
promotion_valid_upto     41191
promotion_description    38938
currency                     0
breadcrumb                   0
pdp_url                      0
region                   41191
pack_size                41191
site_shown_uom               0
dtype: int64

In [11]:
df.nunique()

unique_id                3620
competitor_name             1
extraction_date             1
product_name             3207
grammage_quantity         396
grammage_unit               5
regular_price             348
selling_price             378
price_valid_from            7
price_per_unit           1012
percentage_discount        32
promotion_price           122
promotion_valid_from        7
promotion_valid_upto        6
promotion_description      67
currency                    1
breadcrumb               3005
pdp_url                  3620
region                      0
pack_size                   0
site_shown_uom            716
dtype: int64

In [19]:
df.competitor_product_key.value_counts()

AttributeError: 'DataFrame' object has no attribute 'competitor_product_key'

In [12]:
df.unique_id.duplicated().sum()

np.int64(0)

In [13]:
df.instock.value_counts()

AttributeError: 'DataFrame' object has no attribute 'instock'

In [14]:
df.grammage_unit.value_counts()

grammage_unit
g        2047
stück     714
l         398
ml        352
kg        109
Name: count, dtype: int64

In [15]:
df.competitor_name.value_counts()

competitor_name
lidl    3620
Name: count, dtype: int64

In [16]:
pattern = r'^[^>]+( > [^>]+)*$'

# Invalid breadcrumbs
invalid = df[
    df["breadcrumb"].isna() |
    (df["breadcrumb"].str.strip() == "") |
    (~df["breadcrumb"].str.fullmatch(pattern, na=False))
]

print(f"Total invalid breadcrumbs: {len(invalid)}")

if not invalid.empty:
    print(invalid[["breadcrumb"]])

Total invalid breadcrumbs: 0

In [17]:
df.currency.value_counts()

currency
Swiss franc    3620
Name: count, dtype: int64

In [18]:
import pandas as pd
import re

price_columns = [
    "grammage_quantity",
    "regular_price",
    "selling_price",
    "price_was",
    "promotion_price",
    "percentage_discount",
    "price_per_unit",
    "multi_buy_items_price_total",
    "multibuy_items_pricesingle"
]

for col in price_columns:

    if col not in df.columns:
        continue

    s = df[col].fillna("").astype(str).str.strip()

    # Extract only numeric-looking part
    # This allows values such as:
    # KG. za 3.58 €
    # KG. za 0.9 €
    number = s.str.extract(r"(\d[\d.,]*)", expand=False).fillna("")

    # --------------------------------------------------
    # 1. MULTIPLE DECIMAL POINTS
    # --------------------------------------------------
    multiple_decimal = number.str.count(r"\.") > 1

    # --------------------------------------------------
    # 2. COMMA USED INSTEAD OF DECIMAL POINT
    # --------------------------------------------------
    comma_decimal = number.str.contains(
        r",",
        regex=True,
        na=False
    )

    # --------------------------------------------------
    # 3. EXACTLY 2 DECIMAL PLACES
    # ONLY regular_price and selling_price
    # --------------------------------------------------
    two_decimal_issue = pd.Series(False, index=df.index)

    if col in ["regular_price", "selling_price"]:
        two_decimal_issue = (
            (s != "") &
            (~s.str.fullmatch(r"\d+\.\d{2}", na=False))
        )

    print(f"\n{'='*15} {col} {'='*15}")

    if multiple_decimal.any():
        print(f"Multiple decimal points: {multiple_decimal.sum()}")
        print(
            df.loc[multiple_decimal, [col]]
            .head(10)
            .to_string(index=False)
        )

    if comma_decimal.any():
        print(f"Comma used instead of dot: {comma_decimal.sum()}")
        print(
            df.loc[comma_decimal, [col]]
            .head(10)
            .to_string(index=False)
        )

    if two_decimal_issue.any():
        print(f"Not in 2-decimal format: {two_decimal_issue.sum()}")
        print(
            df.loc[two_decimal_issue, [col]]
            .head(10)
            .to_string(index=False)
        )

=============== grammage_quantity ===============

=============== regular_price ===============
Not in 2-decimal format: 58
 regular_price
           2.6
           3.3
           8.5
          16.0
          10.0
          24.0
           2.7
          26.5
           8.5
           0.1

=============== selling_price ===============
Not in 2-decimal format: 61
 selling_price
           2.6
           3.3
          16.0
          10.0
          24.0
           2.7
           3.0
           2.2
           0.1
           7.8

=============== promotion_price ===============

=============== percentage_discount ===============

=============== price_per_unit ===============

In [19]:
import pandas as pd

price_columns = [
    "grammage_quantity",
    "regular_price",
    "selling_price",
    "price_was",
    "promotion_price",
    "percentage_discount",
    "price_per_unit",
    "multi_buy_items_price_total",
    "multibuy_items_pricesingle"
]

for col in price_columns:
    if col not in df.columns:
        continue

    s = df[col].fillna("").astype(str)

    issues = {
        "Zero values": pd.to_numeric(s, errors="coerce") == 0,
        "Negative values": pd.to_numeric(s, errors="coerce") < 0,
        "Multiple decimal points": s.str.count(r"\.") > 1,
        "More than 2 decimal places": s.str.contains(r"\.\d{3,}$", regex=True),
        "Non-numeric values": (~s.str.match(r"^-?\d+(\.\d+)?$", na=False)) & (s != ""),
        "Leading/Trailing whitespace": s != s.str.strip(),
    }

    print(f"\n{'='*15} {col} {'='*15}")

    for issue, mask in issues.items():
        if mask.any():
            print(f"{issue}: {mask.sum()}")
            print(df.loc[mask, [col]].head(5).to_string(index=False))

=============== grammage_quantity ===============
More than 2 decimal places: 8
grammage_quantity
          6x0.275
            1.491
            1.491
            1.125
            1.125
Non-numeric values: 314
grammage_quantity
            6x0.5
            12x60
            8x100
            4x0.5
            4x100

=============== regular_price ===============

=============== selling_price ===============

=============== promotion_price ===============

=============== percentage_discount ===============

=============== price_per_unit ===============
Non-numeric values: 3188
 price_per_unit
    pro 1 stück
    pro 1 stück
       pro 1 kg
 1Kg = 3.50 CHF
100g = 1.50 CHF

In [20]:
mask = (
    df["price_valid_from"].notna() &
    df["promotion_valid_from"].notna() &
    (df["price_valid_from"] != df["promotion_valid_from"])
)

issues = df.loc[
    mask,
    ["pdp_url", "price_valid_from", "promotion_valid_from"]
].copy()

issues["row_no"] = issues.index + 2

issues[["row_no", "pdp_url", "price_valid_from", "promotion_valid_from"]]

Empty DataFrame
Columns: [row_no, pdp_url, price_valid_from, promotion_valid_from]
Index: []

In [21]:
import re

col = "regular_price"

# More than one decimal point in the numeric part
invalid = df[
    df[col]
    .fillna("")
    .astype(str)
    .str.contains(r'\d+\.\d+\.', regex=True)
]

print(f"Rows with multiple decimal points: {len(invalid)}")
print(invalid[[col]])

Rows with multiple decimal points: 0
Empty DataFrame
Columns: [regular_price]
Index: []

In [22]:
import re

url_pattern = re.compile(
    r"^https?://[^\s/$.?#].[^\s]*$",
    re.IGNORECASE
)

invalid_urls = df[
    
    df["pdp_url"].isna() |
    ~df["pdp_url"].astype(str).str.match(url_pattern)
]

print(f"Invalid URLs: {len(invalid_urls)}")
print(invalid_urls[[ "pdp_url"]])

Invalid URLs: 0
Empty DataFrame
Columns: [pdp_url]
Index: []

In [23]:
df.loc[df["pdp_url"].str.contains(r"\s", regex=True, na=False),
       ["pdp_url"]]

Empty DataFrame
Columns: [pdp_url]
Index: []

In [24]:
import pandas as pd

# Promotion description has a value containing %
promo_mask = (
    df["promotion_description"].fillna("").astype(str).str.contains("%", na=False)
)

# Percentage discount is empty
discount_empty = (
    df["percentage_discount"].isna() |
    df["percentage_discount"].astype(str).str.strip().eq("")
)

# Both conditions
mask = promo_mask & discount_empty

issues = df.loc[
    mask,
    ["promotion_description", "percentage_discount", "pdp_url"]
].copy()

# Row number (assuming header is row 1)
issues["row_no"] = issues.index + 2

# Arrange columns
issues = issues[
    ["row_no", "pdp_url", "promotion_description", "percentage_discount"]
]

print(issues.to_string(index=False))

Empty DataFrame
Columns: [row_no, pdp_url, promotion_description, percentage_discount]
Index: []

In [27]:
df.grammage_quantity.value_counts()

grammage_quantity
1           14874
0.75         2233
500          1927
100          1878
250          1621
200          1341
150           953
0.5           928
400           856
0.7           809
20            677
300           650
330           575
50            571
350           398
125           364
75            360
180           296
80            288
10            274
1.5           248
40            236
60            235
450           225
70            219
2             205
30            203
120           198
3             194
600           180
90            175
750           169
25            164
220           145
240           143
4             140
190           131
160           129
175           128
375           126
140           125
360           115
800           112
110           109
5             101
6             100
16             99
130            96
8              95
340            92
35             91
85             88
18             88
225            87
45             77
12             74
320            70
230            69
210            68
280            67
170            66
55             64
185            63
270            62
480            60
135            59
95             59
42             58
700            58
36             54
15             53
650            50
24             46
65             45
260            43
420            42
460            41
550            40
1.02           39
670            39
440            38
0.8            36
9              36
380            35
1000           35
22             32
64             32
900            31
38             31
1.2            31
680            31
7              31
390            30
275            30
56             30
370            30
32             29
105            28
115            28
0.6            27
290            26
28             26
195            26
14             25
2 x 50         25
21             23
235            23
46             23
1.4            22
138            21
0.9            21
48             21
165            21
310            21
23             21
560            20
72             20
285            19
68             19
76             19
19             19
2.04           18
325            18
465            17
54             17
26             17
473            16
112            16
520            16
43             15
17             15
510            15
580            15
77             14
470            14
1.1            14
145            13
540            13
39             13
44             13
0.825          12
1.0            12
530            12
215            12
425            12
11             12
1.25           12
720            12
0.2            12
126            12
355            12
4.8            11
34             11
96             11
269            11
192            11
47             11
66             11
1.98           11
284            10
155            10
37             10
212             9
92              9
430             9
227             9
0.72            9
950             9
33              9
3.4             9
31              9
52              9
228             9
114             8
49              8
154             8
27              8
1.8             8
74              8
57              8
204             8
111             8
205             8
102             8
455             8
168             8
144             8
880             7
132             7
5000            7
62              7
84              7
1.3             7
2.5             7
415             7
660             7
108             7
166             7
365             7
625             7
0.65            7
255             7
3 x 50          7
182             6
29              6
71              6
113             6
136             6
59              6
410             6
67              6
435             6
128             6
820             6
106             6
224             6
1.75            6
4.5             6
0.25            6
121             6
94              5
53              5
2.1             5
432             5
1.65            5
0.1             5
1200            5
4.700           5
218             5
98              5
385             5
226             5
69              5
352             5
78              5
0.3             5
405             5
850             5
87              5
0.525           5
288             5
1.35            5
1.009           5
960             5
123             5
3.5             5
2x 200          4
3000            4
61              4
2 x 250         4
177             4
345             4
2.9             4
30 x 9          4
15 x 9          4
315             4
86              4
567             4
245             4
2000            4
0.52            4
1.55            4
146             4
3x37            4
640             4
89              4
129             4
3x1             4
176             4
505             4
0.35            4
2.8             4
265             4
157             4
665             4
41              4
73              4
7.5             4
2x50            4
63              4
413             4
148             4
163             4
116             4
475             4
88              4
83              4
187             4
51              3
231             3
414             3
223             3
0.88            3
780             3
58              3
156             3
219             3
99              3
103             3
590             3
4x2             3
162             3
272             3
186             3
0.95            3
0.625           3
336             3
1.24            3
2x9             3
3x16            3
3 x 80          3
5 x 48          3
0.85            3
2 x 20          3
104             3
3 x 100         3
13              3
1500            3
675             3
2.4             3
8.2             3
2 x 269         3
1.7             3
312             3
30 x 10         3
152             3
198             3
0.27            3
222             3
361             3
495             3
395             3
825             2
6x50            2
252             2
0.036           2
2.2             2
232             2
327             2
364             2
980             2
256             2
311             2
107             2
247             2
3x5             2
133             2
2x2             2
281             2
1.200           2
137             2
6 x 10          2
335             2
3 x 1           2
565             2
2x105           2
4.3             2
3x8             2
427             2
81              2
2 x 70          2
3.74            2
1.6             2
0.51            2
5x200           2
366             2
575             2
4.250           2
0.66            2
6.8             2
12 x 52         2
24 x 9          2
4.500           2
282             2
2 x 90          2
184             2
172             2
451             2
2.0             2
840             2
169             2
807             2
585             2
1.125           2
97              2
485             2
268             2
4.800           2
2 x 1000        2
690             2
259             2
119             2
3x7             2
149             2
0.545           2
5x8             2
2x24            2
576             2
5x52            2
1.50            2
6x12            2
490             2
468             2
1.9             2
24 x 10         2
15 x 10         2
3x11            2
0.54            2
3.2             2
423             1
533             1
436             1
79              1
0.84            1
143             1
173             1
141             1
2x100           1
253             1
1.025           1
151             1
197             1
0.77            1
234             1
3170            1
242             1
342             1
411             1
434             1
0.567           1
3.6             1
324             1
276             1
4 x 50          1
6.5             1
728             1
216             1
117             1
2 x 100         1
5.500           1
10 x 6          1
24x10           1
887             1
3x48            1
3x56            1
907             1
4.2             1
9.4             1
0.013           1
329             1
1.980           1
1700            1
0.250           1
3 x 6           1
2.3             1
118             1
568             1
6.75            1
297             1
371             1
1.32            1
0.111           1
3x20            1
4.36            1
93              1
20 x 9          1
3 x 150         1
35-40           1
188             1
372             1
0.50            1
3 x 60          1
0.74            1
0.500           1
0.730           1
3.700           1
9 x 5           1
0.40            1
2x12            1
4.4             1
0.62            1
12x1.75         1
202             1
437             1
386             1
159             1
2.15            1
0.73            1
0.03            1
3x12            1
3.835           1
0.070           1
41 x 6          1
0.106           1
2x400           1
2 x 105         1
890             1
147             1
409             1
248             1
2 x 8.2         1
55x1            1
1.12            1
42 x 10         1
1.08            1
15 x 3          1
50-70           1
12.5            1
318             1
100x100         1
18.5            1
2 x 400         1
620             1
3 x 44          1
0.585           1
445             1
398             1
2500            1
139             1
183             1
0.94            1
0.45            1
36 x 9          1
8.8             1
305             1
570             1
349             1
985             1
433             1
760             1
4330            1
482             1
492             1
454             1
6x190           1
610             1
17-30           1
2 x 42          1
208             1
0.20            1
2.25            1
2 x 56          1
439             1
5 x 10          1
206             1
387             1
830             1
0.075           1
3 x 1.12        1
2.13            1
1.78            1
75 x 3          1
452             1
5 x 0.45        1
3 x 0.94        1
2x1000          1
264             1
975             1
0.4             1
1.46            1
3x100           1
712             1
507             1
3x10            1
4.25            1
308             1
3.0             1
0.648           1
161             1
710             1
1.01            1
322             1
382             1
0.725           1
535             1
532             1
0.330           1
4.9             1
3 x 1.5         1
4 x 18.5        1
0.604           1
251             1
273             1
3 x 10          1
0.125           1
8.4             1
0.06            1
221             1
13.2            1
376             1
2 x 0.75        1
525             1
6x110           1
0.055           1
142             1
537             1
2x 850          1
0.100           1
4x0.75          1
214             1
178             1
2x17            1
122             1
2x250           1
2.970           1
5.61            1
1250            1
1x12            1
438             1
3x45            1
353             1
487             1
0.55            1
193             1
6x2             1
348             1
412             1
82              1
0.565           1
6450            1
378             1
127             1
0.15            1
171             1
812             1
0.58            1
164             1
534             1
243             1
167             1
Name: count, dtype: int64

In [25]:
mask = (
    df["promotion_valid_from"].notna()
    & df["promotion_valid_from"].astype(str).str.strip().ne("")
    & (
        df["price_valid_from"].isna()
        | df["price_valid_from"].astype(str).str.strip().eq("")
    )
)

issues = df.loc[
    mask,
    
    [ "pdp_url", "promotion_valid_from", "price_valid_from"]
].copy()

issues["row_no"] = issues.index + 2

issues = issues[
    ["row_no",  "pdp_url", "promotion_valid_from", "price_valid_from"]
]

print(issues.to_string(index=False))

Empty DataFrame
Columns: [row_no, pdp_url, promotion_valid_from, price_valid_from]
Index: []

In [26]:
invalid_urls = invalid_urls["pdp_url"].unique()

print("Unique invalid URLs:", len(invalid_urls))
for url in invalid_urls:
    print(repr(url))

Unique invalid URLs: 0

In [31]:
import numpy as np

invalid_urls = np.unique(invalid_urls)

print("Unique invalid URLs:", len(invalid_urls))
for url in invalid_urls:
    print(url)  # Or your specific loop logic

Unique invalid URLs: 0

In [32]:
issues = df[
    df["product_name"].astype(str).str.startswith("Denner", na=False)
    & (df["brand"].fillna("").str.strip() != "Denner")
]

issues[["product_name", "brand", "pdp_url"]]

KeyError: 'brand'

In [33]:
df.instock.value_counts()

AttributeError: 'DataFrame' object has no attribute 'instock'

In [27]:
import re

image_cols = [c for c in df.columns if c.startswith("image_url_")]

# Basic image URL pattern
pattern = re.compile(
    r"^https?://[^\s]+\.(jpg|jpeg|png|webp|gif|bmp|avif)(\?.*)?$",
    re.IGNORECASE
)

for col in image_cols:
    invalid = df[
        df[col].notna() &
        (df[col].astype(str).str.strip() != "") &
        ~df[col].astype(str).str.match(pattern)
    ]

    print(f"\n{col}: {len(invalid)} invalid URLs")

    if not invalid.empty:
        print(invalid[["unique_id", col]].head())

In [28]:
(
    df.groupby(['store_addressline2', 'unique_id'])
      .size()
      .reset_index(name='count')
      .query('count > 1')
      .sort_values(['store_addressline2', 'count'], ascending=[True, False])
)

KeyError: 'store_addressline2'

In [29]:
df.extraction_date.value_counts()

extraction_date
2026-08-14    3620
Name: count, dtype: int64

In [30]:
import re

pattern = re.compile(r"^https?://[^\s]+$", re.IGNORECASE)

for col in image_cols:
    invalid = df[
        df[col].notna() &
        (df[col].astype(str).str.strip() != "") &
        ~df[col].astype(str).str.match(pattern)
    ]

    print(f"{col}: {len(invalid)} invalid URLs")

In [31]:
price_cols = [
    "regular_price",
    "selling_price",
   
   
   
]

# Keep only columns that exist in the file
price_cols = [c for c in price_cols if c in df.columns]

# Rows where at least one price column is empty
empty_price_rows = df[df[price_cols].replace("", pd.NA).isna().any(axis=1)]

print(f"Rows with empty price fields: {len(empty_price_rows)}")
display(empty_price_rows[["unique_id","pdp_url", "promotion_description","product_name"] + price_cols])

Rows with empty price fields: 0

Empty DataFrame
Columns: [unique_id, pdp_url, promotion_description, product_name, regular_price, selling_price]
Index: []

In [32]:
import pandas as pd

# Treat empty strings as missing values
promo_price = df["promotion_price"].replace("", pd.NA)
promo_desc = df["promotion_description"].replace("", pd.NA)

# 1. Promotion price present but promotion description missing
price_no_desc = df[
    promo_price.notna() & promo_desc.isna()
]

# 2. Promotion description present but promotion price missing
desc_no_price = df[
    promo_desc.notna() & promo_price.isna()
]

print("Promotion price present but description missing:", len(price_no_desc))
display(price_no_desc[["unique_id", "product_name", "promotion_price","pdp_url", "promotion_description"]])

print("\nPromotion description present but price missing:", len(desc_no_price))
display(desc_no_price[["unique_id", "product_name", "promotion_price", "pdp_url","promotion_description"]])

Promotion price present but description missing: 0

Empty DataFrame
Columns: [unique_id, product_name, promotion_price, pdp_url, promotion_description]
Index: []

Promotion description present but price missing: 333

,unique_id,product_name,promotion_price,pdp_url,promotion_description
34,5114255,Chicken Wings nature,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21941/s/chicken-wings-nature-5114255/category/54/,Aktion
35,1801686,Frisco Extrême Cornets Soft Core,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21940/s/frisco-extreme-cornets-soft-core-1801686/category/54/,Aktion
38,1009870,Glace Erdbeer Crisp XXL,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21939/s/glace-erdbeer-crisp-xxl-1009870/category/54/,Aktion
42,1021254,Lager Bier XXL,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21938/s/lager-bier-xxl-1021254/category/54/,Aktion
43,1017455,Babyfeuchttücher 99% Wasser XXL,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21937/s/babyfeuchttuecher-99-wasser-xxl-1017455/category/54/,Aktion
44,153647,Mini Mix Mandel Vollmilch,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21936/s/mini-mix-mandel-vollmilch-0153647/category/54/,Aktion
45,218173,Hummus XXL,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21934/s/hummus-xxl-0218173/category/54/,Aktion
46,215443,Skyr Natur 0.2% XXL,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21932/s/skyr-natur-0-2-xxl-0215443/category/54/,Aktion
47,1018612,ASC XXL Riesencrevetten,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21931/s/asc-xxl-riesencrevetten-1018612/category/54/,Aktion
48,5719125,Blütenhonig XXL,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21935/s/bluetenhonig-xxl-5719125/category/54/,Aktion
49,5110229,Tessiner Grillwurst XXL,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21928/s/tessiner-grillwurst-xxl-5110229/category/54/,Aktion
50,1801481,Milka Choco Snack,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21930/s/milka-choco-snack-1801481/category/54/,Aktion
51,5112315,Kalbshamburger,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21929/s/kalbshamburger-5112315/category/54/,Aktion
52,146618,Spaghetti XXL,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21933/s/spaghetti-xxl-0146618/category/54/,Aktion
53,1801599,Dr. Oetker Pizza Casa di Mama Diavola,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21927/s/dr-oetker-pizza-casa-di-mama-diavola-1801599/category/54/,Aktion
56,6000964,Getrocknete Steinpilze Spezial,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21919/s/getrocknete-steinpilze-spezial-6000964/category/54/,Aktion
57,1801332,Gran Pavesi Cracker Non Salati,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21918/s/gran-pavesi-cracker-non-salati-1801332/category/54/,Aktion
58,1801331,Gran Pavesi Cracker Salati,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21917/s/gran-pavesi-cracker-salati-1801331/category/54/,Aktion
64,6000194,Gewürzspray,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21916/s/gewuerzspray-6000194/category/54/,Aktion
65,1801625,Dr. Oetker Pizza Casa di Mama Speciale,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21915/s/dr-oetker-pizza-casa-di-mama-speciale-1801625/category/54/,Aktion
66,1801600,Dr. Oetker Pizza Casa di Mama Margherita,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21914/s/dr-oetker-pizza-casa-di-mama-margherita-1801600/category/54/,Aktion
68,1017554,Aperitif Passionsf Alkoholfrei,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21912/s/aperitif-passionsf-alkoholfrei-1017554/category/54/,Aktion
70,175721,DdS Syrah Terre Siciliane,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21913/s/dds-syrah-terre-siciliane-0175721/category/54/,Aktion
125,1801641,Calanda Peach Zero 0.0%,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21675/s/calanda-peach-zero-0-0--1801641/category/54/,Aktion
164,6015535,Nudeln al bronzo IGP,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21585/s/nudeln-al-bronzo-igp-6015535/category/54/,Aktion
165,106463,Pastasaucen,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21586/s/pastasaucen-0106463/category/54/,Aktion
166,1018934,Croissants mit Cremefüllung,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21580/s/croissants-mit-cremefuellung-1018934/category/54/,Aktion
167,1801533,Pampers Windeln Baby Dry,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21573/s/pampers-windeln-baby-dry-1801533/category/54/,Aktion
168,1801528,Pampers Windeln Baby Dry,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21571/s/pampers-windeln-baby-dry-1801528/category/54/,Aktion
169,1801530,Pampers Windeln Baby Dry,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21572/s/pampers-windeln-baby-dry-1801530/category/54/,Aktion
178,1801403,Plenty Haushaltspapier,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21530/s/plenty-haushaltspapier-1801403/category/54/,Aktion
184,5907,Schweinsgeschnetzeltes,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21502/s/schweinsgeschnetzeltes-0005907/category/54/,Aktion
208,5109810,Ramseier Apfelschorle,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21472/s/ramseier-apfelschorle-5109810/category/54/,6+0 gratis
209,1801457,Felix Katzennassnahrung,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21471/s/felix-katzennassnahrung-1801457/category/54/,Aktion
210,1801453,Felix Katzennassnahrung,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21467/s/felix-katzennassnahrung-1801453/category/54/,Aktion
255,1014749,Limoncello Alkoholfrei,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21309/s/limoncello-alkoholfrei-1014749/category/54/,Aktion
257,6005495,Star Granragù Fertigsosse,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21304/s/star-granragu-fertigsosse-6005495/category/54/,Aktion
258,6003836,Star Granragù Fertigsosse,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21302/s/star-granragu-fertigsosse-6003836/category/54/,Aktion
259,6001613,Star Granragù Fertigsosse,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21303/s/star-granragu-fertigsosse-6001613/category/54/,Aktion
337,1801525,Pampers Windeln Baby Dry,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21149/s/pampers-windeln-baby-dry-1801525/category/54/,Aktion
338,1801527,Pampers Windeln Baby Dry,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21148/s/pampers-windeln-baby-dry-1801527/category/54/,Aktion
339,1801526,Pampers Windeln Baby Dry,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21146/s/pampers-windeln-baby-dry-1801526/category/54/,Aktion
340,1801529,Pampers Windeln Baby Dry,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21145/s/pampers-windeln-baby-dry-1801529/category/54/,Aktion
341,1801532,Pampers Windeln Baby Dry,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21147/s/pampers-windeln-baby-dry-1801532/category/54/,Aktion
343,1801531,Pampers Windeln Baby Dry,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21144/s/pampers-windeln-baby-dry-1801531/category/54/,Aktion
392,5114057,Tesori d'Oriente Weichspüler,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20966/s/tesori-d-oriente-weichspueler-5114057/category/54/,Aktion
394,5114056,Tesori d'Oriente Weichspüler,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20964/s/tesori-d-oriente-weichspueler-5114056/category/54/,Aktion
396,5114058,Tesori d'Oriente Weichspüler,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20965/s/tesori-d-oriente-weichspueler-5114058/category/54/,Aktion
434,1801340,Barilla Penne Rigate,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20824/s/barilla-penne-rigate-1801340/category/54/,Aktion
436,1801337,Barilla Spaghettini,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20821/s/barilla-spaghettini-1801337/category/54/,Aktion
437,1801338,Barilla Spaghettoni,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20823/s/barilla-spaghettoni-1801338/category/54/,Aktion
438,1801339,Barilla Spaghetti,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20822/s/barilla-spaghetti-1801339/category/54/,Aktion
440,1801336,Barilla Bavette,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20820/s/barilla-bavette-1801336/category/54/,Aktion
447,1801321,Ritter Sport diverse Sorten,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20787/s/ritter-sport-diverse-sorten-1801321/category/54/,Aktion
455,5112416,Knoblauchwurst,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20763/s/knoblauchwurst-5112416/category/54/,Aktion
465,5105686,Schweinsplätzli vom Stotzen,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20876/s/schweinsplaetzli-vom-stotzen-5105686/category/54/,Aktion
538,210584,Kaffeekapseln XXL,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20514/s/kaffeekapseln-xxl-0210584/category/54/,Aktion
547,122318,Getrocknete Cranberries XXL,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20490/s/getrocknete-cranberries-xxl-0122318/category/54/,Aktion
549,144795,MSC Alaska Seelachsfilet XXL,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20489/s/msc-alaska-seelachsfilet-xxl-0144795/category/54/,Aktion
623,212112,Steinofenpizza Vier Käse XXL,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20105/s/steinofenpizza-vier-kaese-xxl-0212112/category/54/,Aktion
624,5722187,Hafer-Drink Barista XXL,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20096/s/hafer-drink-barista-xxl-5722187/category/54/,Aktion
625,117024,Kartoffelspalten XXL,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20102/s/kartoffelspalten-xxl-0117024/category/54/,Aktion
626,134430,Milk-Choc-Bits Nougat Bits XXL,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20095/s/milk-choc-bits-nougat-bits-xxl-0134430/category/54/,Aktion
627,6006657,Parmigiano Reggiano DOP XXL,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20093/s/parmigiano-reggiano-dop-xxl-6006657/category/54/,Aktion
628,122308,Soft Cake Orange XXL,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20094/s/soft-cake-orange-xxl-0122308/category/54/,Aktion
629,147311,Blätterteiggebäck XXL,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20092/s/blaetterteiggebaeck-xxl-0147311/category/54/,Aktion
644,70916,Kaffeegetränk XXL,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20063/s/kaffeegetraenk-xxl-0070916/category/54/,Aktion
645,146683,Lasagne XXL,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20060/s/lasagne-xxl-0146683/category/54/,Aktion
646,5012221,L.Casei Active Drink XXL,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20061/s/l-casei-active-drink-xxl-5012221/category/54/,Aktion
648,1801233,Cailler Tafelschokolade 3er,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20051/s/cailler-tafelschokolade-3er-1801233/category/54/,Aktion
649,1801232,Cailler Tafelschokolade 3er,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20050/s/cailler-tafelschokolade-3er-1801232/category/54/,Aktion
650,5701753,Schokobrötchen XXL,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20040/s/schokobroetchen-xxl-5701753/category/54/,Aktion
651,1801234,Cailler Tafelschokolade 3er,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20052/s/cailler-tafelschokolade-3er-1801234/category/54/,Aktion
652,174614,High Protein Drink XXL,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20062/s/high-protein-drink-xxl-0174614/category/54/,Aktion
653,200862,Salami-Sticks XXL,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20038/s/salami-sticks-xxl-0200862/category/54/,Aktion
655,117021,Steinofenpizza Salami XXL,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20036/s/steinofenpizza-salami-xxl-0117021/category/54/,Aktion
656,5113226,Le Gruyère Surchoix XXL,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20035/s/le-gruyere-surchoix-xxl-5113226/category/54/,Aktion
658,6003923,Grissini,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20020/s/grissini-6003923/category/54/,Aktion
659,6015480,"Glace mit Ricotta, Honig und Schoko",NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20021/s/glace-mit-ricotta-honig-und-schoko-6015480/category/54/,Aktion
670,122418,Dessert,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20001/s/dessert-0122418/category/54/,Aktion
671,144953,Mini Mozzarella,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20000/s/mini-mozzarella-0144953/category/54/,Aktion
674,5112414,Cervelas-Ring,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/19982/s/cervelas-ring-5112414/category/54/,Aktion
675,200479,Heinz Mayonnaise Top Down,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/19993/s/heinz-mayonnaise-top-down-0200479/category/54/,Aktion
676,200458,Heinz Ketchup Top Up,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/19969/s/heinz-ketchup-top-up-0200458/category/54/,Aktion
688,5113602,Feldschlösschen Bier Original,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/19935/s/feldschloesschen-bier-original-5113602/category/54/,Aktion
708,156458,Chicken Nuggets XXL,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/19839/s/chicken-nuggets-xxl-0156458/category/54/,Aktion
713,158053,Oliven XXL,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/19800/s/oliven-xxl-0158053/category/54/,Aktion
714,144632,Delikatess Krustenschinken,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/19793/s/delikatess-krustenschinken-0144632/category/54/,Aktion
715,145062,Schoko-Crisp XXL,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/19794/s/schoko-crisp-xxl-0145062/category/54/,Aktion
731,1801101,Cornetto mini Classico / Caramel,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/19828/s/cornetto-mini-classico-caramel-1801101/category/54/,Aktion
758,5111894,Eat Real Chips Hummus Tomate & Basilikum,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/19745/s/eat-real-chips-hummus-tomate-basilikum-5111894/category/54/,Aktion
759,5111896,Eat Real Quinoa Chips Sour Cream,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/19744/s/eat-real-quinoa-chips-sour-cream-5111896/category/54/,Aktion
760,5111895,Eat Real Linsenchips Meersalz,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/19743/s/eat-real-linsenchips-meersalz-5111895/category/54/,Aktion
766,1800867,Frisco Extrême Cornets,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/19670/s/frisco-extreme-cornets-1800867/category/54/,Aktion
788,226271,Chiccosi,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/19636/s/chiccosi-0226271/category/54/,Aktion
792,109317,Passierte Tomaten,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/19628/s/passierte-tomaten-0109317/category/54/,Aktion
798,202579,Flaureo Prosecco Spumante,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/19596/s/flaureo-prosecco-spumante-0202579/category/54/,Aktion
800,1800928,Gillette Venus Comfortglide Ersatzklingen,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/19576/s/gillette-venus-comfortglide-ersatzklingen-1800928/category/54/,Aktion
801,1800927,Gillette Venus Comfortglide Rasierer,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/19575/s/gillette-venus-comfortglide-rasierer-1800927/category/54/,Aktion
803,210583,Kaffeekapseln XXL,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/19506/s/kaffeekapseln-xxl-0210583/category/54/,Aktion
807,211067,Jumbo Neo Rolle XXL,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/19505/s/jumbo-neo-rolle-xxl-0211067/category/54/,Aktion
816,163106,Frischei Waffeln XXL,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/19479/s/frischei-waffeln-xxl-0163106/category/54/,Aktion
818,174949,Picco Pizzi XXL,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/19478/s/picco-pizzi-xxl-0174949/category/54/,Aktion
819,148719,Mortadella XXL,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/19474/s/mortadella-xxl-0148719/category/54/,Aktion
840,222694,"Sachertorte Brownie,Cheesecake",NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/19427/s/sachertorte-brownie-cheesecake-0222694/category/54/,Aktion
846,25765,Pizza,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/19590/s/pizza-0025765/category/54/,Aktion
912,6000271,Pesto,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/19073/s/pesto-6000271/category/54/,Aktion
923,1800078,Magnum Double Sunlover,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/19006/s/magnum-double-sunlover-1800078/category/54/,Aktion
940,6597,Lammgigot,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/18907/s/lammgigot-0006597/category/54/,Aktion
951,1800915,Head&Shoulders Anti-Schuppen Shampoo,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/18882/s/head-shoulders-anti-schuppen-shampoo-1800915/category/54/,Aktion
957,117427,Gratinkäse XXL,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/18843/s/gratinkaese-xxl-0117427/category/54/,Aktion
974,116971,Salami Veronese,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/18693/s/salami-veronese-0116971/category/54/,Aktion
975,138667,Dessert Spezialitäten,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/18702/s/dessert-spezialitaeten-0138667/category/54/,Aktion
1008,173558,High Protein Fruchtquark XXL,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/18328/s/high-protein-fruchtquark-xxl-0173558/category/54/,Aktion
1011,25383,Mozzarella XXL,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/18325/s/mozzarella-xxl-0025383/category/54/,Aktion
1019,176390,Ganzes Lachsfilet mit Haut,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/18235/s/ganzes-lachsfilet-mit-haut-0176390/category/54/,Aktion
1021,1800689,Perwoll Flüssigwaschmittel Blütenrausch Duo,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/18179/s/perwoll-fluessigwaschmittel-bluetenrausch-duo-1800689/category/54/,Aktion
1032,115054,Ferrero Raffaello,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/18159/s/ferrero-raffaello-0115054/category/54/,Aktion
1036,1800059,Jacobs Kaffeekapseln,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/18090/s/jacobs-kaffeekapseln-1800059/category/54/,Aktion
1040,7443,Jacobs Kaffee Kapseln Espresso 10 Intens,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/18089/s/jacobs-kaffee-kapseln-espresso-10-intens-0007443/category/54/,Aktion
1041,7442,Jacobs Kaffee Kapseln,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/18088/s/jacobs-kaffee-kapseln-0007442/category/54/,Aktion
1042,7440,Jacobs Kaffee Kapseln,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/18087/s/jacobs-kaffee-kapseln-0007440/category/54/,Aktion
1066,128665,Salatkäse XXL,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/18310/s/salatkaese-xxl-0128665/category/54/,Aktion
1070,6596,Rindshuft am Stück,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/17882/s/rindshuft-am-stueck-0006596/category/54/,Aktion
1089,1800214,Gillette Mach 3 Sport Ersatzklingen,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/17851/s/gillette-mach-3-sport-ersatzklingen-1800214/category/54/,Aktion
1090,1800216,Gillette Venus Start Ersatzklingen,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/17849/s/gillette-venus-start-ersatzklingen-1800216/category/54/,Aktion
1091,1800215,Gillette Fusion Sport Ersatzklingen,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/17850/s/gillette-fusion-sport-ersatzklingen-1800215/category/54/,Aktion
1092,7367,Gillette Fusion Sport Starterset,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/17848/s/gillette-fusion-sport-starterset-0007367/category/54/,Aktion
1093,1800213,Gillette Venus Smooth Handstück,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/17847/s/gillette-venus-smooth-handstueck-1800213/category/54/,Aktion
1094,1800212,Gillette Mach 3 Sport Handstück,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/17846/s/gillette-mach-3-sport-handstueck-1800212/category/54/,Aktion

In [40]:
df.breadcrumb.value_counts()

breadcrumb
SPAR Website > Produktwelt > Haushalt > Textilien > Wäsche & Strumpfwaren > Wäsche Damen                                                              1381
SPAR Website > Produktwelt > Haushalt > Freizeit & Saisonen > Dekoration > Saisonale Dekoration                                                       1028
SPAR Website > Produktwelt > Getränke > Alkoholische Getränke > Weine > Weißweine                                                                      885
SPAR Website > Produktwelt > Getränke > Alkoholische Getränke > Weine > Rotweine                                                                       827
SPAR Website > Produktwelt > Haushalt > Textilien > Wäsche & Strumpfwaren > Strumpfwaren                                                               768
SPAR Website > Produktwelt > Haushalt > Freizeit & Saisonen > Dekoration > Kerzen & Raumduft                                                           742
SPAR Website > Produktwelt > Lebensmittel > Beilagen, Essig, Öl & Gewürze > Gewürze, Salz & Kräuter > Gewürze & Gewürzöle                              701
SPAR Website > Produktwelt > Lebensmittel > Süßes & Salziges > Süßes > Schokolade & Pralinen                                                           645
SPAR Website > Produktwelt > Lebensmittel > Schnelle Küche & To Go > Fertiggerichte > Fertigmahlzeiten                                                 609
SPAR Website > Produktwelt > Haushalt > Spielen, Lernen, Büro & Unterhaltung > Papier, Büro & Schreibwaren > Schreiben, Malen & Zeichnen               561
SPAR Website > Produktwelt > Lebensmittel > Brot & Gebäck > Brot > Brot ungeschnitten                                                                  551
SPAR Website > Produktwelt > Lebensmittel > Beilagen, Essig, Öl & Gewürze > Saucen, Pesto & Sugo > Ketchup, Senf & Co                                  493
SPAR Website > Produktwelt > Lebensmittel > Brot & Gebäck > Feinbackwaren & Süßes > Ungekühlte Konditoreiware                                          491
SPAR Website > Produktwelt > Getränke > Alkoholische Getränke > Bier > Traditionelles Bier                                                             455
SPAR Website > Produktwelt > Haushalt > Spielen, Lernen, Büro & Unterhaltung > Spielware > Baukästen                                                   453
SPAR Website > Produktwelt > Haushalt > Küche > Küchenhelfer & Menagen > Küchen Hilfsgeräte                                                            452
SPAR Website > Produktwelt > Haushalt > Küche > Tischkultur > Servietten & Co                                                                          433
SPAR Website > Produktwelt > Lebensmittel > Beilagen, Essig, Öl & Gewürze > Beilagen > Nudeln & Teigwaren                                              391
SPAR Website > Produktwelt > Drogerie & Beauty > Tierbedarf > Tierfutter > Katze                                                                       330
SPAR Website > Produktwelt > Haushalt > Spielen, Lernen, Büro & Unterhaltung > Spielware > Sonstige Spielwaren                                         323
SPAR Website > Produktwelt > Getränke > Alkoholische Getränke > Spirituosen > Liköre                                                                   310
SPAR Website > Produktwelt > Lebensmittel > Backen & Frühstück > Frühstück > Müsli & Cerealien                                                         297
SPAR Website > Produktwelt > Getränke > Alkoholfreie Getränke > Softdrinks & Säfte > Limonaden & Cola                                                  295
SPAR Website > Produktwelt > Lebensmittel > Süßes & Salziges > Süßes > Waffeln, Kekse & Co.                                                            286
SPAR Website > Produktwelt > Lebensmittel > Milchprodukte & Alternativen > Käse, Streichkäse & Frischkäse > Schnittkäse                                284
SPAR Website > Produktwelt > Haushalt > Textilien > Wäsche & Strumpfwaren > Wäsche Herren                                                              275
SPAR Website > Produktwelt > Lebensmittel > Schnelle Küche & To Go > Eingelegtes Gemüse & Konserven > Sauergemüse & Salate                             274
SPAR Website > Produktwelt > Lebensmittel > Milchprodukte & Alternativen > Joghurt & Topfen > Fruchtjoghurt                                            272
SPAR Website > Produktwelt > Getränke > Alkoholfreie Getränke > Softdrinks & Säfte > Fruchtsäfte & Nektare                                             265
SPAR Website > Produktwelt > Haushalt > Spielen, Lernen, Büro & Unterhaltung > Papier, Büro & Schreibwaren > Schreib- & Zeichenpapiere                 262
SPAR Website > Produktwelt > Getränke > Alkoholische Getränke > Spirituosen > Schnäpse & Brände                                                        253
SPAR Website > Produktwelt > Haushalt > Haushalt & Wohnen > Elektrische Haushaltsgeräte > Elektro Großgeräte                                           253
SPAR Website > Produktwelt > Lebensmittel > Schnelle Küche & To Go > Eingelegtes Gemüse & Konserven > Gemüse eingelegt                                 251
SPAR Website > Produktwelt > Lebensmittel > Milchprodukte & Alternativen > Käse, Streichkäse & Frischkäse > Frischkäse                                 250
SPAR Website > Produktwelt > Haushalt > Küche > Backutensilien > Backzubehör                                                                           234
SPAR Website > Produktwelt > Lebensmittel > Tiefkühlprodukte > Speiseeis & Eiswürfel > Familienpackungen, Torten & Desserts                            229
SPAR Website > Produktwelt > Drogerie & Beauty > Körper & Gesicht > Baden & Duschen > Duschgels & Co.                                                  228
SPAR Website > Produktwelt > Getränke > Alkoholische Getränke > Spirituosen > Whisk(e)y & Bourbon                                                      224
SPAR Website > Produktwelt > Lebensmittel > Süßes & Salziges > Süßes > Riegel                                                                          223
SPAR Website > Produktwelt > Lebensmittel > Backen & Frühstück > Backen > Mehl, Grieß & Co.                                                            222
SPAR Website > Produktwelt > Lebensmittel > Süßes & Salziges > Salziges > Chips, Snips & Co.                                                           221
SPAR Website > Produktwelt > Drogerie & Beauty > Tierbedarf > Tierfutter > Hund                                                                        217
SPAR Website > Produktwelt > Lebensmittel > Wurst, Fleisch, Eier & Fisch > Wurst & Selchwaren > Schinken & Rohwurst                                    216
SPAR Website > Produktwelt > Lebensmittel > Wurst, Fleisch, Eier & Fisch > Frischfleisch > Rind & Kalb                                                 213
SPAR Website > Produktwelt > Drogerie & Beauty > Körper & Gesicht > Hautpflege > Gesichtspflege                                                        213
SPAR Website > Produktwelt > Lebensmittel > Backen & Frühstück > Backen > Backzutaten & Tortendeko                                                     213
SPAR Website > Produktwelt > Drogerie & Beauty > Haarpflege > Shampoo > Trockenes & geschädigtes Haar                                                  209
SPAR Website > Produktwelt > Lebensmittel > Schnelle Küche & To Go > Fertiggerichte > Basis- & Fixgerichte                                             209
SPAR Website > Produktwelt > Lebensmittel > Wurst, Fleisch, Eier & Fisch > Wurst & Selchwaren > Aufschnitt, Knacker & Würstel                          209
SPAR Website > Produktwelt > Lebensmittel > Beilagen, Essig, Öl & Gewürze > Saucen, Pesto & Sugo > Pesto, Sugo & Saucen                                207
SPAR Website > Produktwelt > Getränke > Kaffee, Tee & Kakao > Kaffee > Kaffeekapseln & Kaffeepads                                                      199
SPAR Website > Produktwelt > Haushalt > Küche > Tischkultur > Glaswaren & Vasen                                                                        193
SPAR Website > Produktwelt > Haushalt > Haushalt & Wohnen > Wäschewaschen, Trocknen & Bügeln > Waschmittel                                             190
SPAR Website > Produktwelt > Lebensmittel > Backen & Frühstück > Frühstück > Marmelade, Konfitüre                                                      188
SPAR Website > Produktwelt > Haushalt > Freizeit & Saisonen > Pflanzen & Garten > Garten Zubehör                                                       186
SPAR Website > Produktwelt > Lebensmittel > Süßes & Salziges > Süßes > Zuckerl & Kaugummi                                                              184
SPAR Website > Produktwelt > Lebensmittel > Wurst, Fleisch, Eier & Fisch > Wurst & Selchwaren > Salami & Hartwurst                                     183
SPAR Website > Produktwelt > Haushalt > Küche > Kochen > Kochgeschirr Pfannen                                                                          171
SPAR Website > Produktwelt > Lebensmittel > Schnelle Küche & To Go > Aufstriche & Pasteten > Aufstriche                                                171
SPAR Website > Produktwelt > Haushalt > Freizeit & Saisonen > Reisegepäck, Taschen, Brillen & Accessoires > Trolleys, Taschen, Rucksäcke & Zubehör     170
SPAR Website > Produktwelt > Lebensmittel > Milchprodukte & Alternativen > Käse, Streichkäse & Frischkäse > Hartkäse                                   169
SPAR Website > Produktwelt > Drogerie & Beauty > Gesundheit > Nahrungsergänzung > Protein & Sportnahrung                                               167
SPAR Website > Produktwelt > Getränke > Kaffee, Tee & Kakao > Kaffee > Kaffeebohnen                                                                    167
SPAR Website > Produktwelt > Haushalt > Haushalt & Wohnen > Heimtextilien > Frottierware & Bademäntel                                                  165
SPAR Website > Produktwelt > Lebensmittel > Süßes & Salziges > Salziges > Knabbergebäck                                                                159
SPAR Website > Produktwelt > Haushalt > Küche > Trink & Isolierflaschen > Trinkflaschen                                                                159
SPAR Website > Produktwelt > Lebensmittel > Milchprodukte & Alternativen > Käse, Streichkäse & Frischkäse > Weichkäse                                  157
SPAR Website > Produktwelt > Haushalt > Spielen, Lernen, Büro & Unterhaltung > Spielware > Spiele & Puzzle                                             157
SPAR Website > Produktwelt > Lebensmittel > Schnelle Küche & To Go > Dosenfische & -meeresfrüchte > Dosenfische                                        156
SPAR Website > Produktwelt > Lebensmittel > Wurst, Fleisch, Eier & Fisch > Fisch & Meeresfrüchte > Kaviar, Räucherfisch & Spezialitäten                154
SPAR Website > Produktwelt > Haushalt > Spielen, Lernen, Büro & Unterhaltung > Unterhaltungselektronik > TV, Audio & Abspielgeräte                     152
SPAR Website > Produktwelt > Lebensmittel > Brot & Gebäck > Gebäck > Korn- & Vollkorngebäck                                                            152
SPAR Website > Produktwelt > Drogerie & Beauty > Gesundheit > Nahrungsergänzung > Vitamine & Mineralien                                                152
SPAR Website > Produktwelt > Haushalt > Haushalt & Wohnen > Putzen & Putzutensilien > Geschirrreiniger                                                 149
SPAR Website > Produktwelt > Lebensmittel > Milchprodukte & Alternativen > Milch & Milchgetränke > Milchmischgetränke                                  149
SPAR Website > Produktwelt > Lebensmittel > Backen & Frühstück > Frühstück > Honig & Sirup                                                             148
SPAR Website > Produktwelt > Getränke > Kaffee, Tee & Kakao > Tee > Kräutertee                                                                         148
SPAR Website > Produktwelt > Lebensmittel > Tiefkühlprodukte > Speiseeis & Eiswürfel > Portionspackungen                                               147
SPAR Website > Produktwelt > Lebensmittel > Süßes & Salziges > Salziges > Nüsse & Kerne                                                                147
SPAR Website > Produktwelt > Drogerie & Beauty > Körper & Gesicht > Deodorants > Deo Spray                                                             146
SPAR Website > Produktwelt > Haushalt > Spielen, Lernen, Büro & Unterhaltung > Kommunikation > Telefonie                                               144
SPAR Website > Produktwelt > Lebensmittel > Schnelle Küche & To Go > Fertiggerichte > Suppen & Einlagen                                                142
SPAR Website > Produktwelt > Getränke > Alkoholfreie Getränke > Softdrinks & Säfte > Sirupe & Konzentrate                                              140
SPAR Website > Produktwelt > Drogerie & Beauty > Zahnpflege > Handzahnbürsten > Handzahnbürsten für Erwachsene                                         138
SPAR Website > Produktwelt > Lebensmittel > Süßes & Salziges > Süßes > Fruchtgummi & Fruchtspeck                                                       138
SPAR Website > Produktwelt > Lebensmittel > Babynahrung > Babykost > Desserts & Snacks                                                                 137
SPAR Website > Produktwelt > Haushalt > Haushalt & Wohnen > Aufbewahren und Ordnen > Eimer & Co                                                        137
SPAR Website > Produktwelt > Haushalt > Haushalt & Wohnen > Nähen und Zubehör > Nähzubehör                                                             136
SPAR Website > Produktwelt > Drogerie & Beauty > Körper & Gesicht > Hautpflege > Bodylotion & Hautcreme                                                136
SPAR Website > Produktwelt > Getränke > Alkoholische Getränke > Spirituosen > Rum                                                                      135
SPAR Website > Produktwelt > Lebensmittel > Beilagen, Essig, Öl & Gewürze > Essig & Öl > Speiseöl                                                      133
SPAR Website > Produktwelt > Haushalt > Haushalt & Wohnen > Putzen & Putzutensilien > Lufterfrischer                                                   133
SPAR Website > Produktwelt > Drogerie & Beauty > Körper & Gesicht > Baden & Duschen > Seifen                                                           132
SPAR Website > Produktwelt > Haushalt > Küche > Backutensilien > Backformen                                                                            132
SPAR Website > Produktwelt > Haushalt > Küche > Küchenhelfer & Menagen > Küchenmesser & Zubehör                                                        132
SPAR Website > Produktwelt > Lebensmittel > Backen & Frühstück > Backen > Nüsse, Kerne & Trockenfrüchte                                                132
SPAR Website > Produktwelt > Getränke > Alkoholische Getränke > Spirituosen > Gin                                                                      129
SPAR Website > Produktwelt > Lebensmittel > Milchprodukte & Alternativen > Alternative Produkte > Milchprodukte Alternativen auf sonstiger Basis       128
SPAR Website > Produktwelt > Haushalt > Küche > Einkochen > Gläser & Flaschen                                                                          127
SPAR Website > Produktwelt > Lebensmittel > Milchprodukte & Alternativen > Käse, Streichkäse & Frischkäse > Käse Stücke & Scheiben                     127
SPAR Website > Produktwelt > Haushalt > Haushalt & Wohnen > Putzen & Putzutensilien > Haushaltsreiniger Generalisten                                   126
SPAR Website > Produktwelt > Drogerie & Beauty > Zahnpflege > Zahnpasta > Zahnpasta für Erwachsene                                                     124
SPAR Website > Produktwelt > Haushalt > Haushalt & Wohnen > Elektrische Haushaltsgeräte > Küchenmaschinen                                              123
SPAR Website > Produktwelt > Getränke > Kaffee, Tee & Kakao > Tee > Früchtetee                                                                         122
SPAR Website > Produktwelt > Haushalt > Freizeit & Saisonen > Grillen & Zubehör > Brennstoffe & Zubehör                                                122
SPAR Website > Produktwelt > Getränke > Alkoholfreie Getränke > Softdrinks & Säfte > Eistee & Teegetränke                                              122
SPAR Website > Produktwelt > Lebensmittel > Beilagen, Essig, Öl & Gewürze > Beilagen > Reis & Hülsenfrüchte                                            121
SPAR Website > Produktwelt > Haushalt > Küche > Tischkultur > Porzellan & Keramik                                                                      118
SPAR Website > Produktwelt > Haushalt > Spielen, Lernen, Büro & Unterhaltung > Papier, Büro & Schreibwaren > Basteln & Kleben                          117
SPAR Website > Produktwelt > Lebensmittel > Babynahrung > Babykost > Baby Glaskost                                                                     114
SPAR Website > Produktwelt > Drogerie & Beauty > Körper & Gesicht > Baden & Duschen > Badezusätze                                                      114
SPAR Website > Produktwelt > Haushalt > Haushalt & Wohnen > Elektrische Haushaltsgeräte > Mikrowelle, Kleinküche & Co                                  114
SPAR Website > Produktwelt > Haushalt > Haushalt & Wohnen > Putzen & Putzutensilien > Haushaltstücher & Schwämme                                       113
SPAR Website > Produktwelt > Lebensmittel > Wurst, Fleisch, Eier & Fisch > Frischfleisch > Huhn & Pute                                                 111
SPAR Website > Produktwelt > Lebensmittel > Beilagen, Essig, Öl & Gewürze > Gewürze, Salz & Kräuter > Speisesalz                                       108
SPAR Website > Produktwelt > Lebensmittel > Milchprodukte & Alternativen > Pudding & gekühlte Desserts > Gekühlte Desserts                             108
SPAR Website > Produktwelt > Haushalt > Haushalt & Wohnen > Elektrische Haushaltsgeräte > Staubsauger & Zubehör                                        107
SPAR Website > Produktwelt > Lebensmittel > Tiefkühlprodukte > Gemüse, Obst & Kräuter > TK Gemüse & Pilze                                              107
SPAR Website > Produktwelt > Haushalt > Freizeit & Saisonen > Partyzubehör und Schenken > Partyzubehör                                                 104
SPAR Website > Produktwelt > Haushalt > Küche > Lebensmittel Aufbewahrung > Aufbewahrung Dosen                                                         103
SPAR Website > Produktwelt > Haushalt > Küche > Kochen > Kochgeschirr Töpfe                                                                            102
SPAR Website > Produktwelt > Lebensmittel > Schnelle Küche & To Go > Fertiggerichte > TK Traditionelle Fertiggerichte, Saucen & Suppen                 102
SPAR Website > Produktwelt > Getränke > Alkoholische Getränke > Schaumwein > Sekt                                                                      101
SPAR Website > Produktwelt > Drogerie & Beauty > Körper & Gesicht > Sonnenschutz & Insektenschutz > Sonnencreme & Sprays                                98
SPAR Website > Produktwelt > Getränke > Alkoholfreie Getränke > Softdrinks & Säfte > Smoothies & gekühlte Säfte                                         98
SPAR Website > Produktwelt > Haushalt > Spielen, Lernen, Büro & Unterhaltung > Spielware > Fahrzeuge & Modellbau                                        98
SPAR Website > Produktwelt > Lebensmittel > Milchprodukte & Alternativen > Joghurt & Topfen > Naturjoghurt                                              98
SPAR Website > Produktwelt > Getränke > Alkoholische Getränke > Weine > Roséweine                                                                       97

In [33]:
invalid = df[df["breadcrumb"].str.contains("…", na=False)]

print(f"Rows with truncated breadcrumbs: {len(invalid)}")
display(invalid[["unique_id", "breadcrumb"]])

Rows with truncated breadcrumbs: 0

Empty DataFrame
Columns: [unique_id, breadcrumb]
Index: []

In [34]:
result = df[
    df["selling_price"].isna() & df["regular_price"].isna()

text_cols = df.select_dtypes(include="object").columns

issues = {}

for col in text_cols:
    # Match | not preceded by a backslash
    mask = (
        df[col]
        .fillna("")
        .astype(str)
        .str.contains(r"(?<!\\)\|", regex=True)
    )

    if mask.any():
        issues[col] = df.loc[mask, ["unique_id", col]]

# Print results
if issues:
    print("Columns containing unescaped '|':\n")
    for col, data in issues.items():
        print(f"\n=== {col} ({len(data)} rows) ===")
        print(data.to_string(index=False))
else:
    print("No unescaped '|' found.")
]

print(result)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (3466212421.py, line 2)

In [35]:
import pandas as pd

# Text columns only
text_cols = df.select_dtypes(include="object").columns

invalid_chars = [ "\n", "\r", "\t"]

issues = {}

for col in text_cols:
    mask = df[col].fillna("").astype(str).str.contains(r"[\n\r\t]", regex=True)
    if mask.any():
        issues[col] = df.loc[mask, ["unique_id", col]]

# Summary
if issues:
    print("Columns containing \\n, \\r or \\t:\n")
    for col, data in issues.items():
        print(f"{col}: {len(data)} rows")
else:
    print("No \\n, \\r or \\t found.")

No \n, \r or \t found.

In [36]:
import pandas as pd

text_cols = df.select_dtypes(include="object").columns

results = []

for col in text_cols:
    mask = df[col].fillna("").astype(str).str.contains(r"[\n\r\t]", regex=True)

    for idx, value in df.loc[mask, col].items():
        results.append({
            "row_no": idx + 2,      # Excel row number
            "unique_id": df.at[idx, "unique_id"],
            "pdp_url": df.at[idx, "pdp_url"],
            "column": col,
            "issue_value": value
        })

issues_df = pd.DataFrame(results)

issues_df

Empty DataFrame
Columns: []
Index: []

In [37]:
columns = ["product_description", "special_information", "manufacturer_address"]

for col in columns:
    rows = df[
        df[col]
        .fillna("")
        .astype(str)
        .str.contains("|", regex=False, na=False)
    ]

    print(f"\n=== {col}: {len(rows)} rows ===")

    if not rows.empty:
        display(rows[["unique_id", "pdp_url", col]])

KeyError: 'product_description'

In [46]:
import pandas as pd
import re




df["dimensions"] = df["dimensions"].fillna("").str.strip()

pattern = re.compile(
    r'^\d+(\.\d+)?(\s*[a-zA-Z]+)?\s*[xX×]\s*'
    r'\d+(\.\d+)?(\s*[a-zA-Z]+)?\s*[xX×]\s*'
    r'\d+(\.\d+)?(\s*[a-zA-Z]+)?$'
)

invalid = df[
    (df["dimensions"] != "") &
    (~df["dimensions"].str.match(pattern))
]

print(f"Invalid values: {len(invalid)}")
print(invalid[["unique_id", "product_name", "dimensions"]])

KeyError: 'dimensions'

In [38]:
import pandas as pd

issues = []

for col in df.columns:
    if df[col].dtype == "object":
        mask = df[col].fillna("").astype(str).str.contains(
            r'^\s+|\s+$|\t|\n|\r| {2,}',
            regex=True,
            na=False
        )

        if mask.any():
            temp = df.loc[mask, [col]].copy()
            temp["row_no"] = temp.index + 2
            temp["column"] = col
            issues.append(temp[["row_no", "column", col]])

if issues:
    result = pd.concat(issues, ignore_index=True)
    print(result)
else:
    print("No unwanted whitespace found.")

   row_no        column                               product_name  \
0    3539  product_name  Mini Pizza Pancetta, Provola und  Zwiebel
1    3539    breadcrumb                                        NaN

                                                          breadcrumb
0                                                                NaN
1  Sortiment > Sortiment > Mini Pizza Pancetta, Provola und  Zwiebel

In [48]:

# Replace empty strings with NA
df = df.replace(r'^\s*$', pd.NA, regex=True)

# Filter Fleisch & Fisch
ff = df[df["producthierarchy_level1"] == "Fleisch & Fisch"]

# Subcategories that should have price_per_unit
ppu_subcats = ["Fleisch & Geflügel", "Frischfisch & Schalentiere"]

# Missing price_per_unit
invalid_ppu = ff[
    ff["producthierarchy_level2"].isin(ppu_subcats) &
    ff["price_per_unit"].isna()
]

print("Missing price_per_unit:")
print(invalid_ppu[["unique_id","product_name","producthierarchy_level2","price_per_unit"]])

KeyError: 'producthierarchy_level1'

In [39]:
date_columns = [
    "promotion_valid_upto",
    "promotion_valid_from",
    "price_valid_from"
]

for col in date_columns:
    print("\nColumn:", col)
    print(df[col].value_counts(dropna=False))

Column: promotion_valid_upto
promotion_valid_upto
NaN          3366
19.8.2026     131
26.8.2026      87
15.8.2026      20
22.8.2026      11
29.8.2026       4
19.9.2026       1
Name: count, dtype: int64

Column: promotion_valid_from
promotion_valid_from
NaN          3044
13.8.2026     424
20.8.2026      48
24.8.2026      43
17.8.2026      41
10.8.2026      15
6.8.2026        4
15.8.2025       1
Name: count, dtype: int64

Column: price_valid_from
price_valid_from
NaN          3044
13.8.2026     424
20.8.2026      48
24.8.2026      43
17.8.2026      41
10.8.2026      15
6.8.2026        4
15.8.2025       1
Name: count, dtype: int64

In [40]:
invalid_discount = df[
    df["percentage_discount"]
    .astype(str)
    .str.contains(r"[%\-]", regex=True, na=False)
]

print("Invalid percentage_discount values:")
print(invalid_discount[["unique_id", "product_name", "percentage_discount"]])

print("\nCount:", len(invalid_discount))

Invalid percentage_discount values:
Empty DataFrame
Columns: [unique_id, product_name, percentage_discount]
Index: []

Count: 0

In [41]:
s = df['percentage_discount']

mask = (
    s.notna() &
    s.astype(str).str.strip().ne("") &
    ~s.astype(str).str.fullmatch(r'\d+', na=False)
)

issues = df.loc[
    mask,
    ['pdp_url', 'percentage_discount']
].copy()

issues['row_no'] = issues.index + 2

issues = issues[['row_no', 'pdp_url', 'percentage_discount']]

print(issues.to_string(index=False))
print(f"\nTotal issues: {len(issues)}")

 row_no                                                                                                                               pdp_url  percentage_discount
      7                         https://sortiment.lidl.ch/de/catalog/product/view/id/14079/s/montepulciano-d-abruzzo-doc-0151217/category/54/                 20.0
     20                         https://sortiment.lidl.ch/de/catalog/product/view/id/14499/s/prosecco-valdobbiadene-docg-0149516/category/54/                 20.0
     32                                     https://sortiment.lidl.ch/de/catalog/product/view/id/13318/s/buendnerfleisch-5107879/category/54/                 20.0
     81                      https://sortiment.lidl.ch/de/catalog/product/view/id/16188/s/terra-natura-baguette-rustique-5111837/category/54/                 16.0
     93                                               https://sortiment.lidl.ch/de/catalog/product/view/id/21793/s/gyoza-0145799/category/54/                 20.0
    143                           https://sortiment.lidl.ch/de/catalog/product/view/id/21632/s/freesecco-sparkling-white-1009461/category/54/                 20.0
    157                                               https://sortiment.lidl.ch/de/catalog/product/view/id/21614/s/pizza-0204675/category/54/                 20.0
    190                    https://sortiment.lidl.ch/de/catalog/product/view/id/21497/s/flaureo-prosecco-doc-millesimato-0173657/category/54/                 20.0
    191                           https://sortiment.lidl.ch/de/catalog/product/view/id/21496/s/viura-airen-valdepe-as-do-0036724/category/54/                 20.0
    197                                   https://sortiment.lidl.ch/de/catalog/product/view/id/21495/s/weisswein-trocken-0029589/category/54/                 20.0
    280                           https://sortiment.lidl.ch/de/catalog/product/view/id/21277/s/cheetos-xl-cheese-paprika-5114225/category/54/                 35.0
    284                                https://sortiment.lidl.ch/de/catalog/product/view/id/21273/s/hugo-frizzante-mango-0130418/category/54/                 20.0
    338                               https://sortiment.lidl.ch/de/catalog/product/view/id/21168/s/bio-bianco-puglia-igt-1012022/category/54/                 20.0
    389                                   https://sortiment.lidl.ch/de/catalog/product/view/id/21048/s/chardonnay-italia-0224748/category/54/                 20.0
    466                          https://sortiment.lidl.ch/de/catalog/product/view/id/20705/s/pizzateig-mit-tomatensauce-1006127/category/54/                 20.0
    505                                https://sortiment.lidl.ch/de/catalog/product/view/id/20603/s/bio-rosso-puglia-igt-1001282/category/54/                 20.0
    548                               https://sortiment.lidl.ch/de/catalog/product/view/id/20501/s/mauler-cordon-or-brut-5114001/category/54/                 20.0
    602                            https://sortiment.lidl.ch/de/catalog/product/view/id/20212/s/emmi-caffe-latte-balance-0190748/category/54/                 28.0
    637                                       https://sortiment.lidl.ch/de/catalog/product/view/id/20073/s/pastagerichte-0183613/category/54/                 12.0
    645                    https://sortiment.lidl.ch/de/catalog/product/view/id/20044/s/calanda-radler-mango-spritz-0-0--5113623/category/54/                 30.0
    666                               https://sortiment.lidl.ch/de/catalog/product/view/id/20008/s/kleinflaschen-italien-0211049/category/54/                 20.0
    685                                     https://sortiment.lidl.ch/de/catalog/product/view/id/19947/s/syrah-pays-d-oc-0228949/category/54/                 20.0
    688                                   https://sortiment.lidl.ch/de/catalog/product/view/id/19926/s/rioja-crianza-doc-0031965/category/54/                 20.0
    727                                        https://sortiment.lidl.ch/de/catalog/product/view/id/19788/s/sekt-trocken-0152675/category/54/                 20.0
    766    https://sortiment.lidl.ch/de/catalog/product/view/id/19701/s/vigne-vecchie-leggenda-primitivo-di-manduria-dop-5109548/category/54/                 20.0
    767                                          https://sortiment.lidl.ch/de/catalog/product/view/id/19700/s/syrah-rose-0099010/category/54/                 20.0
    810                      https://sortiment.lidl.ch/de/catalog/product/view/id/19504/s/cave-alianca-casal-mendes-rose-5108508/category/54/                 38.0
    814                  https://sortiment.lidl.ch/de/catalog/product/view/id/19499/s/faustino-i-gran-reserva-rioja-doca-5103124/category/54/                 20.0
    815                https://sortiment.lidl.ch/de/catalog/product/view/id/19501/s/pata-negra-toro-do-tempranillo-roble-5107188/category/54/                 20.0
    839                          https://sortiment.lidl.ch/de/catalog/product/view/id/19431/s/krustenschinken-hauchduenn-5113359/category/54/                 17.0
    853                                     https://sortiment.lidl.ch/de/catalog/product/view/id/19396/s/bitterol-sprizz-0176615/category/54/                 20.0
    890                                   https://sortiment.lidl.ch/de/catalog/product/view/id/19161/s/mediterranee-rose-0203655/category/54/                 20.0
    892 https://sortiment.lidl.ch/de/catalog/product/view/id/19141/s/feudi-di-san-marzano-sessantanni-primitivo-manduria-5105972/category/54/                 20.0
    912                                       https://sortiment.lidl.ch/de/catalog/product/view/id/19087/s/poulet-delice-5113318/category/54/                  9.0
    913                                           https://sortiment.lidl.ch/de/catalog/product/view/id/19074/s/croissant-6002908/category/54/                 25.0
    980                             https://sortiment.lidl.ch/de/catalog/product/view/id/18688/s/johannisberg-valais-aoc-5113273/category/54/                 20.0
   1002                                  https://sortiment.lidl.ch/de/catalog/product/view/id/18891/s/high-protein-drink-0216192/category/54/                 20.0
   1011                                        https://sortiment.lidl.ch/de/catalog/product/view/id/18350/s/mate-classic-5112704/category/54/                 40.0
   1048                                    https://sortiment.lidl.ch/de/catalog/product/view/id/18070/s/granatapfelkerne-5113185/category/54/                 14.0
   1073            https://sortiment.lidl.ch/de/catalog/product/view/id/17886/s/cantine-cellaro-due-lune-terre-siciliane-5106288/category/54/                 20.0
   1106                       https://sortiment.lidl.ch/de/catalog/product/view/id/17755/s/tempo-toilettenpapier-classic-1800483/category/54/                 43.0
   1107                               https://sortiment.lidl.ch/de/catalog/product/view/id/17754/s/tempo-toilettenpapier-1800482/category/54/                 50.0
   1188                                   https://sortiment.lidl.ch/de/catalog/product/view/id/17093/s/san-benedetto-the-5107610/category/54/                 16.0
   1192                                            https://sortiment.lidl.ch/de/catalog/product/view/id/17073/s/cornetti-6000214/category/54/                 25.0
   1193                                            https://sortiment.lidl.ch/de/catalog/product/view/id/17072/s/cornetti-6000213/category/54/                 25.0
   1197                                  https://sortiment.lidl.ch/de/catalog/product/view/id/17064/s/nduja-aus-spilinga-6015028/category/54/                 20.0
   1214              https://sortiment.lidl.ch/de/catalog/product/view/id/16975/s/muerbeteigkekse-mit-milch-und-reismehl-6008309/category/54/                 25.0
   1221                              https://sortiment.lidl.ch/de/catalog/product/view/id/16963/s/tartufo-coppa-cappucci-0077845/category/54/                 20.0
   1242                           https://sortiment.lidl.ch/de/catalog/product/view/id/16892/s/miesmuscheln-tomatensauce-6000047/category/54/                 23.0
   1244                                           https://sortiment.lidl.ch/de/catalog/product/view/id/16890/s/salsiccia-0176289/category/54/                 20.0
   1268                       https://sortiment.lidl.ch/de/catalog/product/view/id/16793/s/dolcezze-quotidiane-croissant-6009678/category/54/                 20.0
   1272       https://sortiment.lidl.ch/de/catalog/product/view/id/16758/s/feldschloesschen-panache-pfirsich-alkoholfrei-5112520/category/54/                 25.0
   1279                      https://sortiment.lidl.ch/de/catalog/product/view/id/16605/s/calanda-radler-grapefruit-0-0--5112745/category/54/                 30.0
   1280                          https://sortiment.lidl.ch/de/catalog/product/view/id/16603/s/freixenet-rose-alkoholfrei-5112831/category/54/                 20.0
   1281                         https://sortiment.lidl.ch/de/catalog/product/view/id/16604/s/freixenet-alkoholfrei-weiss-5112830/category/54/                 20.0
   1282                            https://sortiment.lidl.ch/de/catalog/product/view/id/16597/s/san-pellegrino-sanbitter-0003819/category/54/                 30.0
   1283                  https://sortiment.lidl.ch/de/catalog/product/view/id/16579/s/le-petit-marseillais-duschgel-trio-1800137/category/54/                 42.0
   1314                                https://sortiment.lidl.ch/de/catalog/product/view/id/16525/s/primitivo-puglia-igt-0201266/category/54/                 20.0
   1316                                         https://sortiment.lidl.ch/de/catalog/product/view/id/16507/s/tempranillo-0115461/category/54/                 20.0
   1330                                      https://sortiment.lidl.ch/de/catalog/product/view/id/16482/s/zinfandel-rose-0206816/category/54/                 20.0
   1354                    https://sortiment.lidl.ch/de/catalog/product/view/id/16431/s/pata-negra-valdepe-as-reserva-do-5110693/category/54/                 20.0
   1355                       https://sortiment.lidl.ch/de/catalog/product/view/id/16432/s/uno-primitivo-di-manduria-doc-5112701/category/54/                 20.0
   1400                                           https://sortiment.lidl.ch/de/catalog/product/view/id/16343/s/piu-secco-0206227/category/54/                 20.0
   1430                   https://sortiment.lidl.ch/de/catalog/product/view/id/16270/s/weingut-mueller-gruener-veltliner-5008143/category/54/                 20.0
   1455                                               https://sortiment.lidl.ch/de/catalog/product/view/id/16233/s/glace-0021461/category/54/                 31.0
   1474                                         https://sortiment.lidl.ch/de/catalog/product/view/id/16208/s/pane-maggia-0205406/category/54/                 33.0
   1481                            https://sortiment.lidl.ch/de/catalog/product/view/id/16194/s/faustino-vii-tempranillo-5105311/category/54/                 20.0
   1519                                    https://sortiment.lidl.ch/de/catalog/product/view/id/16118/s/bio-prosecco-doc-0172440/category/54/                 20.0
   1551                           https://sortiment.lidl.ch/de/catalog/product/view/id/16038/s/findus-plaetzli-bolognese-5106364/category/54/                 33.0
   1555                                 https://sortiment.lidl.ch/de/catalog/product/view/id/16022/s/instant-kaffee-gold-0162590/category/54/                 18.0
   1557                     https://sortiment.lidl.ch/de/catalog/product/view/id/16019/s/corte-alle-mura-chianti-riserva-0024692/category/54/                 20.0
   1562                                      https://sortiment.lidl.ch/de/catalog/product/view/id/16011/s/schweinsragout-5110566/category/54/                 15.0
   1568                                      https://sortiment.lidl.ch/de/catalog/product/view/id/15999/s/cottage-cheese-5100168/category/54/                 26.0
   1571                                        https://sortiment.lidl.ch/de/catalog/product/view/id/15993/s/shiraz-paarl-0133553/category/54/                 20.0
   1581                                   https://sortiment.lidl.ch/de/catalog/product/view/id/15979/s/davoser-bergkaese-5102771/category/54/                 25.0
   1584                                       https://sortiment.lidl.ch/de/catalog/product/view/id/15975/s/bardolino-doc-0188106/category/54/                 20.0
   1589                              https://sortiment.lidl.ch/de/catalog/product/view/id/15963/s/bio-chasselas-vaudoise-5110452/category/54/                 20.0
   1591                            https://sortiment.lidl.ch/de/catalog/product/view/id/15965/s/kleinflaschen-wallis-aoc-5111279/category/54/                 20.0
   1620            https://sortiment.lidl.ch/de/catalog/product/view/id/15941/s/fortezza-dei-colli-chianti-classico-docg-0188420/category/54/                 20.0
   1623                                https://sortiment.lidl.ch/de/catalog/product/view/id/15903/s/primitivo-puglia-dop-0151636/category/54/                 20.0
   1624                                         https://sortiment.lidl.ch/de/catalog/product/view/id/15902/s/mateus-rose-5103714/category/54/                 20.0
   1642                             https://sortiment.lidl.ch/de/catalog/product/view/id/15860/s/susumaniello-puglia-igp-0168195/category/54/                 20.0
   1702   https://sortiment.lidl.ch/de/catalog/product/view/id/15719/s/feldschloesschen-bier-alkoholfrei-zitrone-panache-5109473/category/54/                 24.0
   1734                                            https://sortiment.lidl.ch/de/catalog/product/view/id/15673/s/pinotage-0034515/category/54/                 20.0
   1736                                  https://sortiment.lidl.ch/de/catalog/product/view/id/15635/s/chenin-blanc-paarl-0133796/category/54/                 20.0
   1742                                 https://sortiment.lidl.ch/de/catalog/product/view/id/15627/s/luna-malbec-premium-0132656/category/54/                 20.0
   1823                                     https://sortiment.lidl.ch/de/catalog/product/view/id/15330/s/tempranillo-dop-0036258/category/54/                 20.0
   1827                             https://sortiment.lidl.ch/de/catalog/product/view/id/15302/s/chateauneuf-du-pape-aop-0178850/category/54/                 20.0
   1829                                   https://sortiment.lidl.ch/de/catalog/product/view/id/15285/s/prosecco-doc-rose-0160262/category/54/                 20.0
   1862                            https://sortiment.lidl.ch/de/catalog/product/view/id/15203/s/camembert-zum-grillieren-7708355/category/54/                 25.0
   1905           https://sortiment.lidl.ch/de/catalog/product/view/id/14799/s/fantini-farnese-edizione-cinque-autoctoni-5105391/category/54/                 20.0
   1906                              https://sortiment.lidl.ch/de/catalog/product/view/id/14801/s/freixenet-carta-nevada-0007533/category/54/                 20.0
   1915                                               https://sortiment.lidl.ch/de/catalog/product/view/id/14776/s/coppa-0161607/category/54/                 20.0
   1931                      https://sortiment.lidl.ch/de/catalog/product/view/id/14748/s/gran-selone-premium-collection-0163947/category/54/                 20.0
   1991                                      https://sortiment.lidl.ch/de/catalog/product/view/id/14495/s/zweigelt-cuvee-5008172/category/54/                 20.0
   1992                                    https://sortiment.lidl.ch/de/catalog/product/view/id/14492/s/nero-d-avola-dop-0128628/category/54/                 20.0
   1993                                          https://sortiment.lidl.ch/de/catalog/product/view/id/14491/s/chardonnay-0034496/category/54/                 20.0
   1998                                      https://sortiment.lidl.ch/de/catalog/product/view/id/14490/s/kochwein-weiss-5108639/category/54/                 20.0
   2050                                        https://sortiment.lidl.ch/de/catalog/product/view/id/14286/s/mini-burrata-6012305/category/54/                 20.0
   2079                                            https://sortiment.lidl.ch/de/catalog/product/view/id/14201/s/rosewein-0029511/category/54/                 20.0
   2085                                        https://sortiment.lidl.ch/de/catalog/product/view/id/14165/s/sekt-trocken-0152671/category/54/                 20.0
   2089                           https://sortiment.lidl.ch/de/catalog/product/view/id/14156/s/primitivo-di-manduria-doc-0038537/category/54/                 20.0
   2097                                      https://sortiment.lidl.ch/de/catalog/product/view/id/14115/s/hugo-frizzante-0137653/category/54/                 20.0
   2122                                        https://sortiment.lidl.ch/de/catalog/product/view/id/14067/s/bordeaux-aop-0026937/category/54/                 20.0
   2158                               https://sortiment.lidl.ch/de/catalog/product/view/id/13876/s/fackelspiess-gefuellt-0006013/category/54/                 22.0
   2204                                     https://sortiment.lidl.ch/de/catalog/product/view/id/13718/s/findus-plaetzli-0001867/category/54/                 22.0
   2210                          https://sortiment.lidl.ch/de/catalog/product/view/id/13703/s/mont-sur-rolle-la-cote-aoc-0001008/category/54/                 20.0
   2211                             https://sortiment.lidl.ch/de/catalog/product/view/id/13702/s/pinot-noir-salgesch-aoc-0002326/category/54/                 20.0
   2213                          https://sortiment.lidl.ch/de/catalog/product/view/id/13701/s/dole-blanche-du-valais-aoc-0001017/category/54/                 20.0
   2220                                             https://sortiment.lidl.ch/de/catalog/product/view/id/13690/s/orangen-0080135/category/54/                 28.0
   2224                                       https://sortiment.lidl.ch/de/catalog/product/view/id/13680/s/malvoisie-aoc-0001015/category/54/                 20.0
   2227                                 https://sortiment.lidl.ch/de/catalog/product/view/id/13678/s/champagner-aop-brut-0098985/category/54/                 20.0
   2228                                        https://sortiment.lidl.ch/de/catalog/product/view/id/13675/s/prosecco-doc-0127982/category/54/                 20.0
   2229                              https://sortiment.lidl.ch/de/catalog/product/view/id/13672/s/moscato-spumante-dolce-0028100/category/54/                 20.0
   2230                            https://sortiment.lidl.ch/de/catalog/product/view/id/13669/s/rimuss-party-alkoholfrei-0002870/category/54/                 20.0
   2231                                      https://sortiment.lidl.ch/de/catalog/product/view/id/13668/s/moliere-litchi-0001890/category/54/                 20.0
   2232                                https://sortiment.lidl.ch/de/catalog/product/view/id/13674/s/prosecco-treviso-doc-0048641/category/54/                 20.0
   2241                       https://sortiment.lidl.ch/de/catalog/product/view/id/13649/s/naturjoghurt-griechischer-art-0006714/category/54/                 23.0
   2244                                   https://sortiment.lidl.ch/de/catalog/product/view/id/13647/s/petite-arvine-aoc-0001006/category/54/                 20.0
   2245                       https://sortiment.lidl.ch/de/catalog/product/view/id/13644/s/barbera-d-asti-superiore-docg-0120906/category/54/                 20.0
   2246                               https://sortiment.lidl.ch/de/catalog/product/view/id/13645/s/fendant-du-valais-aoc-0001003/category/54/                 20.0

In [51]:
invalid = df[
    df["promotion_description"].notna() &
    (
        df["promotion_valid_from"].isna() |
        df["promotion_valid_upto"].isna()
    )
]

print(f"Rows with promotion description but missing promotion dates: {len(invalid)}")

display(
    invalid[
        [
            "unique_id",
            "product_name",
            "promotion_description",
            "promotion_valid_from",
            "promotion_valid_upto",
            "pdp_url"
        ]
    ]
)

Rows with promotion description but missing promotion dates: 519

,unique_id,product_name,promotion_description,promotion_valid_from,promotion_valid_upto,pdp_url
5,151217,Montepulciano d'Abruzzo DOC,-20%,13.8.2026,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/14079/s/montepulciano-d-abruzzo-doc-0151217/category/54/
18,149516,Prosecco Valdobbiadene DOCG,-20%,13.8.2026,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/14499/s/prosecco-valdobbiadene-docg-0149516/category/54/
30,5107879,Bündnerfleisch,-20%,13.8.2026,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/13318/s/buendnerfleisch-5107879/category/54/
34,5114255,Chicken Wings nature,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21941/s/chicken-wings-nature-5114255/category/54/
35,1801686,Frisco Extrême Cornets Soft Core,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21940/s/frisco-extreme-cornets-soft-core-1801686/category/54/
38,1009870,Glace Erdbeer Crisp XXL,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21939/s/glace-erdbeer-crisp-xxl-1009870/category/54/
42,1021254,Lager Bier XXL,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21938/s/lager-bier-xxl-1021254/category/54/
43,1017455,Babyfeuchttücher 99% Wasser XXL,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21937/s/babyfeuchttuecher-99-wasser-xxl-1017455/category/54/
44,153647,Mini Mix Mandel Vollmilch,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21936/s/mini-mix-mandel-vollmilch-0153647/category/54/
45,218173,Hummus XXL,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21934/s/hummus-xxl-0218173/category/54/
46,215443,Skyr Natur 0.2% XXL,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21932/s/skyr-natur-0-2-xxl-0215443/category/54/
47,1018612,ASC XXL Riesencrevetten,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21931/s/asc-xxl-riesencrevetten-1018612/category/54/
48,5719125,Blütenhonig XXL,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21935/s/bluetenhonig-xxl-5719125/category/54/
49,5110229,Tessiner Grillwurst XXL,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21928/s/tessiner-grillwurst-xxl-5110229/category/54/
50,1801481,Milka Choco Snack,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21930/s/milka-choco-snack-1801481/category/54/
51,5112315,Kalbshamburger,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21929/s/kalbshamburger-5112315/category/54/
52,146618,Spaghetti XXL,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21933/s/spaghetti-xxl-0146618/category/54/
53,1801599,Dr. Oetker Pizza Casa di Mama Diavola,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21927/s/dr-oetker-pizza-casa-di-mama-diavola-1801599/category/54/
56,6000964,Getrocknete Steinpilze Spezial,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21919/s/getrocknete-steinpilze-spezial-6000964/category/54/
57,1801332,Gran Pavesi Cracker Non Salati,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21918/s/gran-pavesi-cracker-non-salati-1801332/category/54/
58,1801331,Gran Pavesi Cracker Salati,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21917/s/gran-pavesi-cracker-salati-1801331/category/54/
64,6000194,Gewürzspray,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21916/s/gewuerzspray-6000194/category/54/
65,1801625,Dr. Oetker Pizza Casa di Mama Speciale,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21915/s/dr-oetker-pizza-casa-di-mama-speciale-1801625/category/54/
66,1801600,Dr. Oetker Pizza Casa di Mama Margherita,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21914/s/dr-oetker-pizza-casa-di-mama-margherita-1801600/category/54/
68,1017554,Aperitif Passionsf Alkoholfrei,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21912/s/aperitif-passionsf-alkoholfrei-1017554/category/54/
70,175721,DdS Syrah Terre Siciliane,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21913/s/dds-syrah-terre-siciliane-0175721/category/54/
79,5111837,Terra Natura Baguette Rustique,-16%,13.8.2026,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/16188/s/terra-natura-baguette-rustique-5111837/category/54/
91,145799,Gyoza,-20%,13.8.2026,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21793/s/gyoza-0145799/category/54/
125,1801641,Calanda Peach Zero 0.0%,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21675/s/calanda-peach-zero-0-0--1801641/category/54/
141,1009461,FreeSecco Sparkling White,-20%,6.8.2026,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21632/s/freesecco-sparkling-white-1009461/category/54/
155,204675,Pizza,-20%,13.8.2026,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21614/s/pizza-0204675/category/54/
164,6015535,Nudeln al bronzo IGP,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21585/s/nudeln-al-bronzo-igp-6015535/category/54/
165,106463,Pastasaucen,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21586/s/pastasaucen-0106463/category/54/
166,1018934,Croissants mit Cremefüllung,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21580/s/croissants-mit-cremefuellung-1018934/category/54/
167,1801533,Pampers Windeln Baby Dry,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21573/s/pampers-windeln-baby-dry-1801533/category/54/
168,1801528,Pampers Windeln Baby Dry,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21571/s/pampers-windeln-baby-dry-1801528/category/54/
169,1801530,Pampers Windeln Baby Dry,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21572/s/pampers-windeln-baby-dry-1801530/category/54/
178,1801403,Plenty Haushaltspapier,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21530/s/plenty-haushaltspapier-1801403/category/54/
184,5907,Schweinsgeschnetzeltes,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21502/s/schweinsgeschnetzeltes-0005907/category/54/
188,173657,Flaureo Prosecco DOC Millesimato,-20%,13.8.2026,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21497/s/flaureo-prosecco-doc-millesimato-0173657/category/54/
189,36724,Viura/Aíren Valdepeñas DO,-20%,13.8.2026,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21496/s/viura-airen-valdepe-as-do-0036724/category/54/
195,29589,Weisswein trocken,-20%,13.8.2026,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21495/s/weisswein-trocken-0029589/category/54/
208,5109810,Ramseier Apfelschorle,6+0 gratis,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21472/s/ramseier-apfelschorle-5109810/category/54/
209,1801457,Felix Katzennassnahrung,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21471/s/felix-katzennassnahrung-1801457/category/54/
210,1801453,Felix Katzennassnahrung,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21467/s/felix-katzennassnahrung-1801453/category/54/
255,1014749,Limoncello Alkoholfrei,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21309/s/limoncello-alkoholfrei-1014749/category/54/
257,6005495,Star Granragù Fertigsosse,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21304/s/star-granragu-fertigsosse-6005495/category/54/
258,6003836,Star Granragù Fertigsosse,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21302/s/star-granragu-fertigsosse-6003836/category/54/
259,6001613,Star Granragù Fertigsosse,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21303/s/star-granragu-fertigsosse-6001613/category/54/
278,5114225,Cheetos XL Cheese & Paprika,-35%,13.8.2026,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21277/s/cheetos-xl-cheese-paprika-5114225/category/54/
282,130418,Hugo Frizzante Mango,-20%,13.8.2026,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21273/s/hugo-frizzante-mango-0130418/category/54/
336,1012022,Bio Bianco Puglia IGT,-20%,13.8.2026,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21168/s/bio-bianco-puglia-igt-1012022/category/54/
337,1801525,Pampers Windeln Baby Dry,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21149/s/pampers-windeln-baby-dry-1801525/category/54/
338,1801527,Pampers Windeln Baby Dry,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21148/s/pampers-windeln-baby-dry-1801527/category/54/
339,1801526,Pampers Windeln Baby Dry,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21146/s/pampers-windeln-baby-dry-1801526/category/54/
340,1801529,Pampers Windeln Baby Dry,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21145/s/pampers-windeln-baby-dry-1801529/category/54/
341,1801532,Pampers Windeln Baby Dry,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21147/s/pampers-windeln-baby-dry-1801532/category/54/
343,1801531,Pampers Windeln Baby Dry,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21144/s/pampers-windeln-baby-dry-1801531/category/54/
387,224748,Chardonnay Italia,-20%,13.8.2026,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/21048/s/chardonnay-italia-0224748/category/54/
392,5114057,Tesori d'Oriente Weichspüler,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20966/s/tesori-d-oriente-weichspueler-5114057/category/54/
394,5114056,Tesori d'Oriente Weichspüler,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20964/s/tesori-d-oriente-weichspueler-5114056/category/54/
396,5114058,Tesori d'Oriente Weichspüler,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20965/s/tesori-d-oriente-weichspueler-5114058/category/54/
434,1801340,Barilla Penne Rigate,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20824/s/barilla-penne-rigate-1801340/category/54/
436,1801337,Barilla Spaghettini,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20821/s/barilla-spaghettini-1801337/category/54/
437,1801338,Barilla Spaghettoni,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20823/s/barilla-spaghettoni-1801338/category/54/
438,1801339,Barilla Spaghetti,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20822/s/barilla-spaghetti-1801339/category/54/
440,1801336,Barilla Bavette,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20820/s/barilla-bavette-1801336/category/54/
447,1801321,Ritter Sport diverse Sorten,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20787/s/ritter-sport-diverse-sorten-1801321/category/54/
455,5112416,Knoblauchwurst,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20763/s/knoblauchwurst-5112416/category/54/
464,1006127,Pizzateig mit Tomatensauce,-20%,13.8.2026,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20705/s/pizzateig-mit-tomatensauce-1006127/category/54/
465,5105686,Schweinsplätzli vom Stotzen,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20876/s/schweinsplaetzli-vom-stotzen-5105686/category/54/
503,1001282,Bio Rosso Puglia IGT,-20%,13.8.2026,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20603/s/bio-rosso-puglia-igt-1001282/category/54/
538,210584,Kaffeekapseln XXL,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20514/s/kaffeekapseln-xxl-0210584/category/54/
546,5114001,Mauler Cordon Or Brut,-20%,13.8.2026,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20501/s/mauler-cordon-or-brut-5114001/category/54/
547,122318,Getrocknete Cranberries XXL,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20490/s/getrocknete-cranberries-xxl-0122318/category/54/
549,144795,MSC Alaska Seelachsfilet XXL,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20489/s/msc-alaska-seelachsfilet-xxl-0144795/category/54/
600,190748,Emmi Caffè Latte Balance,-28%,13.8.2026,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20212/s/emmi-caffe-latte-balance-0190748/category/54/
623,212112,Steinofenpizza Vier Käse XXL,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20105/s/steinofenpizza-vier-kaese-xxl-0212112/category/54/
624,5722187,Hafer-Drink Barista XXL,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20096/s/hafer-drink-barista-xxl-5722187/category/54/
625,117024,Kartoffelspalten XXL,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20102/s/kartoffelspalten-xxl-0117024/category/54/
626,134430,Milk-Choc-Bits Nougat Bits XXL,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20095/s/milk-choc-bits-nougat-bits-xxl-0134430/category/54/
627,6006657,Parmigiano Reggiano DOP XXL,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20093/s/parmigiano-reggiano-dop-xxl-6006657/category/54/
628,122308,Soft Cake Orange XXL,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20094/s/soft-cake-orange-xxl-0122308/category/54/
629,147311,Blätterteiggebäck XXL,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20092/s/blaetterteiggebaeck-xxl-0147311/category/54/
635,183613,Pastagerichte,-12%,13.8.2026,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20073/s/pastagerichte-0183613/category/54/
643,5113623,Calanda Radler Mango Spritz 0.0%,-30%,15.8.2025,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20044/s/calanda-radler-mango-spritz-0-0--5113623/category/54/
644,70916,Kaffeegetränk XXL,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20063/s/kaffeegetraenk-xxl-0070916/category/54/
645,146683,Lasagne XXL,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20060/s/lasagne-xxl-0146683/category/54/
646,5012221,L.Casei Active Drink XXL,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20061/s/l-casei-active-drink-xxl-5012221/category/54/
648,1801233,Cailler Tafelschokolade 3er,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20051/s/cailler-tafelschokolade-3er-1801233/category/54/
649,1801232,Cailler Tafelschokolade 3er,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20050/s/cailler-tafelschokolade-3er-1801232/category/54/
650,5701753,Schokobrötchen XXL,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20040/s/schokobroetchen-xxl-5701753/category/54/
651,1801234,Cailler Tafelschokolade 3er,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20052/s/cailler-tafelschokolade-3er-1801234/category/54/
652,174614,High Protein Drink XXL,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20062/s/high-protein-drink-xxl-0174614/category/54/
653,200862,Salami-Sticks XXL,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20038/s/salami-sticks-xxl-0200862/category/54/
655,117021,Steinofenpizza Salami XXL,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20036/s/steinofenpizza-salami-xxl-0117021/category/54/
656,5113226,Le Gruyère Surchoix XXL,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20035/s/le-gruyere-surchoix-xxl-5113226/category/54/
658,6003923,Grissini,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20020/s/grissini-6003923/category/54/
659,6015480,"Glace mit Ricotta, Honig und Schoko",Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20021/s/glace-mit-ricotta-honig-und-schoko-6015480/category/54/
664,211049,Kleinflaschen Italien,-20%,13.8.2026,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20008/s/kleinflaschen-italien-0211049/category/54/
670,122418,Dessert,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20001/s/dessert-0122418/category/54/
671,144953,Mini Mozzarella,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/20000/s/mini-mozzarella-0144953/category/54/
674,5112414,Cervelas-Ring,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/19982/s/cervelas-ring-5112414/category/54/
675,200479,Heinz Mayonnaise Top Down,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/19993/s/heinz-mayonnaise-top-down-0200479/category/54/
676,200458,Heinz Ketchup Top Up,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/19969/s/heinz-ketchup-top-up-0200458/category/54/
683,228949,Syrah Pays d'Oc,-20%,13.8.2026,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/19947/s/syrah-pays-d-oc-0228949/category/54/
686,31965,Rioja Crianza DOC,-20%,6.8.2026,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/19926/s/rioja-crianza-doc-0031965/category/54/
688,5113602,Feldschlösschen Bier Original,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/19935/s/feldschloesschen-bier-original-5113602/category/54/
708,156458,Chicken Nuggets XXL,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/19839/s/chicken-nuggets-xxl-0156458/category/54/
713,158053,Oliven XXL,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/19800/s/oliven-xxl-0158053/category/54/
714,144632,Delikatess Krustenschinken,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/19793/s/delikatess-krustenschinken-0144632/category/54/
715,145062,Schoko-Crisp XXL,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/19794/s/schoko-crisp-xxl-0145062/category/54/
725,152675,Sekt trocken,-20%,13.8.2026,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/19788/s/sekt-trocken-0152675/category/54/
731,1801101,Cornetto mini Classico / Caramel,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/19828/s/cornetto-mini-classico-caramel-1801101/category/54/
758,5111894,Eat Real Chips Hummus Tomate & Basilikum,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/19745/s/eat-real-chips-hummus-tomate-basilikum-5111894/category/54/
759,5111896,Eat Real Quinoa Chips Sour Cream,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/19744/s/eat-real-quinoa-chips-sour-cream-5111896/category/54/
760,5111895,Eat Real Linsenchips Meersalz,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/19743/s/eat-real-linsenchips-meersalz-5111895/category/54/
764,5109548,Vigne Vecchie Leggenda Primitivo di Manduria DOP,-20%,13.8.2026,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/19701/s/vigne-vecchie-leggenda-primitivo-di-manduria-dop-5109548/category/54/
765,99010,Syrah Rosé,-20%,13.8.2026,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/19700/s/syrah-rose-0099010/category/54/
766,1800867,Frisco Extrême Cornets,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/19670/s/frisco-extreme-cornets-1800867/category/54/
788,226271,Chiccosi,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/19636/s/chiccosi-0226271/category/54/
792,109317,Passierte Tomaten,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/19628/s/passierte-tomaten-0109317/category/54/
798,202579,Flaureo Prosecco Spumante,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/19596/s/flaureo-prosecco-spumante-0202579/category/54/
800,1800928,Gillette Venus Comfortglide Ersatzklingen,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/19576/s/gillette-venus-comfortglide-ersatzklingen-1800928/category/54/
801,1800927,Gillette Venus Comfortglide Rasierer,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/19575/s/gillette-venus-comfortglide-rasierer-1800927/category/54/
803,210583,Kaffeekapseln XXL,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/19506/s/kaffeekapseln-xxl-0210583/category/54/
807,211067,Jumbo Neo Rolle XXL,Aktion,NaN,NaN,https://sortiment.lidl.ch/de/catalog/product/view/id/19505/s/jumbo-neo-rolle-xxl-0211067/category/54/

In [50]:
import pandas as pd
import numpy as np
import re

issues = []

valid_units = {
    "g","kg","ml","l","stuck","stk","btl","wg","pcs","pc","piece","ea"
}

for i, row in df.iterrows():

    url = str(row.get("pdp_url",""))

    # unique_id
    if pd.isna(row["unique_id"]) or str(row["unique_id"]).strip()=="":
        issues.append([i+1,url,"unique_id","Missing unique_id"])

    # product_name
    if pd.isna(row["product_name"]) or str(row["product_name"]).strip()=="":
        issues.append([i+1,url,"product_name","Missing product_name"])

    # selling_price
    if pd.isna(row["selling_price"]):
        issues.append([i+1,url,"selling_price","Missing selling_price"])

    # regular price < selling price
    if pd.notna(row["regular_price"]) and pd.notna(row["selling_price"]):
        if float(row["selling_price"]) > float(row["regular_price"]):
            issues.append([i+1,url,"price","selling_price greater than regular_price"])

    # promotion price
    if pd.notna(row["promotion_price"]) and pd.notna(row["selling_price"]):
        if float(row["promotion_price"]) > float(row["selling_price"]):
            issues.append([i+1,url,"promotion_price","promotion_price greater than selling_price"])

    # promotion description
    if pd.notna(row["promotion_price"]) and (
        pd.isna(row["promotion_description"]) or
        str(row["promotion_description"]).strip()==""
    ):
        issues.append([i+1,url,"promotion_description",
                       "promotion_price present but promotion_description empty"])

    # grammage quantity
    if pd.isna(row["grammage_quantity"]):
        issues.append([i+1,url,"grammage_quantity","Missing grammage_quantity"])

    # grammage unit
    if pd.isna(row["grammage_unit"]) or str(row["grammage_unit"]).strip()=="":
        issues.append([i+1,url,"grammage_unit","Missing grammage_unit"])
    elif str(row["grammage_unit"]).lower() not in valid_units:
        issues.append([i+1,url,"grammage_unit","Unknown grammage_unit"])

    # price_per_unit
    if pd.isna(row["price_per_unit"]) or str(row["price_per_unit"]).strip()=="":
        issues.append([i+1,url,"price_per_unit","Missing price_per_unit"])

    # currency
    if str(row["currency"]).strip().upper()!="EUR":
        issues.append([i+1,url,"currency","Unexpected currency"])

    # breadcrumb
    if pd.isna(row["breadcrumb"]) or str(row["breadcrumb"]).strip()=="":
        issues.append([i+1,url,"breadcrumb","Empty breadcrumb"])

    # pack_size
    if pd.isna(row["pack_size"]) or str(row["pack_size"]).strip()=="":
        issues.append([i+1,url,"pack_size","Empty pack_size"])

    # site_shown_uom
    if pd.isna(row["site_shown_uom"]) or str(row["site_shown_uom"]).strip()=="":
        issues.append([i+1,url,"site_shown_uom","Empty site_shown_uom"])

    # URL validation
    if not re.match(r"^https?://", url):
        issues.append([i+1,url,"pdp_url","Invalid URL"])

# duplicate unique_id
dup = df[df["unique_id"].duplicated(keep=False)]

for i,row in dup.iterrows():
    issues.append([
        i+1,
        row["pdp_url"],
        "unique_id",
        "Duplicate unique_id"
    ])

issues_df = pd.DataFrame(
    issues,
    columns=["row_no","pdp_url","column","issue"]
)

print("Total Issues:", len(issues_df))
display(issues_df)

Total Issues: 8818

      row_no  \
0          1
1          1
2          1
3          2
4          2
5          2
6          3
7          3
8          4
9          4
10         5
11         5
12         6
13         6
14         7
15         7
16         7
17         8
18         8
19         9
20         9
21        10
22        10
23        11
24        11
25        12
26        12
27        13
28        13
29        14
30        14
31        15
32        15
33        16
34        16
35        17
36        17
37        18
38        18
39        19
40        19
41        20
42        20
43        21
44        21
45        22
46        22
47        23
48        23
49        23
50        24
51        24
52        25
53        25
54        26
55        26
56        27
57        27
58        28
59        28
60        29
61        29
62        30
63        30
64        31
65        31
66        32
67        32
68        33
69        33
70        34
71        34
72        35
73        35
74        36
75        36
76        37
77        37
78        38
79        38
80        39
81        39
82        40
83        40
84        41
85        41
86        42
87        42
88        42
89        43
90        43
91        44
92        44
93        44
94        45
95        45
96        46
97        46
98        47
99        47
100       48
101       48
102       49
103       49
104       50
105       50
106       51
107       51
108       52
109       52
110       53
111       53
112       54
113       54
114       55
115       55
116       55
117       56
118       56
119       56
120       57
121       57
122       58
123       58
124       59
125       59
126       60
127       60
128       61
129       61
130       62
131       62
132       63
133       63
134       64
135       64
136       65
137       65
138       66
139       66
140       67
141       67
142       68
143       68
144       68
145       69
146       69
147       70
148       70
149       70
150       71
151       71
152       72
153       72
154       72
155       73
156       73
157       73
158       74
159       74
160       74
161       75
162       75
163       76
164       76
165       76
166       77
167       77
168       78
169       78
170       79
171       79
172       80
173       80
174       81
175       81
176       82
177       82
178       83
179       83
180       84
181       84
182       85
183       85
184       86
185       86
186       87
187       87
188       88
189       88
190       89
191       89
192       90
193       90
194       91
195       91
196       92
197       92
198       93
199       93
200       93
201       94
202       94
203       95
204       95
205       96
206       96
207       97
208       97
209       98
210       98
211       99
212       99
213      100
214      100
215      101
216      101
217      102
218      102
219      103
220      103
221      104
222      104
223      105
224      105
225      106
226      106
227      107
228      107
229      108
230      108
231      109
232      109
233      110
234      110
235      111
236      111
237      111
238      112
239      112
240      113
241      113
242      113
243      114
244      114
245      115
246      115
247      116
248      116
249      117
250      117
251      118
252      118
253      119
254      119
255      120
256      120
257      121
258      121
259      122
260      122
261      123
262      123
263      124
264      124
265      125
266      125
267      126
268      126
269      127
270      127
271      127
272      128
273      128
274      129
275      129
276      130
277      130
278      131
279      131
280      132
281      132
282      133
283      133
284      134
285      134
286      135
287      135
288      136
289      136
290      137
291      137
292      138
293      138
294      139
295      139
296      140
297      140
298      141
299      141
300      142
301      142
302      143
303      143
304      144
305      144
306      145
307      145
308      146
309      146
310      147
311      147
312      148
313      148
314      149
315      149
316      150
317      150
318      151
319      151
320      152
321      152
322      153
323      153
324      154
325      154
326      155
327      155
328      156
329      156
330      157
331      157
332      158
333      158
334      159
335      159
336      160
337      160
338      161
339      161
340      162
341      162
342      163
343      163
344      164
345      164
346      165
347      165
348      166
349      166
350      167
351      167
352      168
353      168
354      168
355      169
356      169
357      169
358      170
359      170
360      170
361      171
362      171
363      172
364      172
365      173
366      173
367      174
368      174
369      175
370      175
371      175
372      176
373      176
374      176
375      177
376      177
377      178
378      178
379      179
380      179
381      179
382      180
383      180
384      181
385      181
386      182
387      182
388      183
389      183
390      184
391      184
392      185
393      185
394      186
395      186
396      187
397      187
398      188
399      188
400      189
401      189
402      190
403      190
404      191
405      191
406      192
407      192
408      193
409      193
410      194
411      194
412      195
413      195
414      196
415      196
416      197
417      197
418      198
419      198
420      199
421      199
422      200
423      200
424      201
425      201
426      202
427      202
428      203
429      203
430      204
431      204
432      205
433      205
434      206
435      206
436      207
437      207
438      208
439      208
440      209
441      209
442      210
443      210
444      211
445      211
446      212
447      212
448      213
449      213
450      213
451      214
452      214
453      215
454      215
455      216
456      216
457      217
458      217
459      218
460      218
461      219
462      219
463      220
464      220
465      221
466      221
467      222
468      222
469      223
470      223
471      224
472      224
473      225
474      225
475      226
476      226
477      227
478      227
479      228
480      228
481      229
482      229
483      230
484      230
485      231
486      231
487      232
488      232
489      233
490      233
491      233
492      234
493      234
494      235
495      235
496      236
497      236
498      237
499      237
500      238
501      238
502      239
503      239
504      240
505      240
506      241
507      241
508      241
509      242
510      242
511      243
512      243
513      243
514      244
515      244
516      244
517      245
518      245
519      246
520      246
521      246
522      247
523      247
524      248
525      248
526      248
527      249
528      249
529      250
530      250
531      250
532      251
533      251
534      252
535      252
536      253
537      253
538      254
539      254
540      255
541      255
542      256
543      256
544      257
545      257
546      258
547      258
548      259
549      259
550      260
551      260
552      261
553      261
554      262
555      262
556      262
557      263
558      263
559      264
560      264
561      265
562      265
563      266
564      266
565      267
566      267
567      268
568      268
569      269
570      269
571      270
572      270
573      271
574      271
575      272
576      272
577      273
578      273
579      274
580      274
581      275
582      275
583      276
584      276
585      277
586      277
587      278
588      278
589      279
590      279
591      280
592      280
593      281
594      281
595      282
596      282
597      283
598      283
599      284
600      284
601      285
602      285
603      286
604      286
605      287
606      287
607      288
608      288
609      289
610      289
611      290
612      290
613      291
614      291
615      292
616      292
617      293
618      293
619      294
620      294
621      295
622      295
623      296
624      296
625      297
626      297
627      298
628      298
629      299
630      299
631      300
632      300
633      301
634      301
635      302
636      302
637      303
638      303
639      304
640      304
641      305
642      305
643      306
644      306
645      307
646      307
647      308
648      308
649      309
650      309
651      310
652      310
653      311
654      311
655      312
656      312
657      313
658      313
659      314
660      314
661      315
662      315
663      316
664      316
665      317
666      317
667      318
668      318
669      319
670      319
671      320
672      320
673      321
674      321
675      322
676      322
677      323
678      323
679      324
680      324
681      325
682      325
683      326
684      326
685      327
686      327
687      328
688      328
689      329
690      329
691      330
692      330
693      331
694      331
695      331
696      332
697      332
698      333
699      333
700      334
701      334
702      335
703      335
704      336
705      336
706      337
707      337
708      338
709      338
710      338
711      339
712      339
713      339
714      340
715      340
716      340
717      341
718      341
719      341
720      342
721      342
722      342
723      343
724      343
725      344
726      344
727      344
728      345
729      345
730      346
731      346
732      347
733      347
734      348
735      348
736      349
737      349
738      350
739      350
740      351
741      351
742      352
743      352
744      352
745      353
746      353
747      354
748      354
749      355
750      355
751      356
752      356
753      357
754      357
755      358
756      358
757      358
758      359
759      359
760      360
761      360
762      361
763      361
764      362
765      362
766      363
767      363
768      364
769      364
770      365
771      365
772      366
773      366
774      367
775      367
776      368
777      368
778      368
779      369
780      369
781      369
782      370
783      370
784      370
785      371
786      371
787      371
788      372
789      372
790      372
791      373
792      373
793      374
794      374
795      375
796      375
797      376
798      376
799      377
800      377
801      378
802      378
803      379
804      379
805      380
806      380
807      381
808      381
809      382
810      382
811      383
812      383
813      384
814      384
815      384
816      385
817      385
818      386
819      386
820      387
821      387
822      387
823      388
824      388
825      389
826      389
827      389
828      390
829      390
830      391
831      391
832      392
833      392
834      393
835      393
836      394
837      394
838      395
839      395
840      396
841      396
842      397
843      397
844      398
845      398
846      399
847      399
848      400
849      400
850      401
851      401
852      402
853      402
854      403
855      403
856      404
857      404
858      405
859      405
860      406
861      406
862      407
863      407
864      408
865      408
866      409
867      409
868      410
869      410
870      411
871      411
872      412
873      412
874      413
875      413
876      414
877      414
878      415
879      415
880      416
881      416
882      417
883      417
884      417
885      418
886      418
887      419
888      419
889      419
890      420
891      420
892      421
893      421
894      422
895      422
896      423
897      423
898      423
899      424
900      424
901      424
902      425
903      425
904      426
905      426
906      427
907      427
908      428
909      428
910      429
911      429
912      430
913      430
914      431
915      431
916      431
917      432
918      432
919      433
920      433
921      434
922      434
923      435
924      435
925      436
926      436
927      436
928      437
929      437
930      438
931      438
932      439
933      439
934      440
935      440
936      441
937      441
938      442
939      442
940      442
941      443
942      443
943      443
944      444
945      444
946      445
947      445
948      446
949      446
950      447
951      447
952      448
953      448
954      449
955      449
956      450
957      450
958      450
959      451
960      451
961      452
962      452
963      453
964      453
965      454
966      454
967      455
968      455
969      456
970      456
971      457
972      457
973      458
974      458
975      459
976      459
977      460
978      460
979      461
980      461
981      462
982      462
983      463
984      463
985      464
986      464
987      465
988      465
989      466
990      466
991      467
992      467
993      468
994      468
995      469
996      469
997      470
998      470
999      471
1000     471
1001     472
1002     472
1003     473
1004     473
1005     474
1006     474
1007     475
1008     475
1009     476
1010     476
1011     477
1012     477
1013     478
1014     478
1015     478
1016     479
1017     479
1018     480
1019     480
1020     481
1021     481
1022     482
1023     482
1024     483
1025     483
1026     484
1027     484
1028     485
1029     485
1030     486
1031     486
1032     487
1033     487
1034     488
1035     488
1036     489
1037     489
1038     490
1039     490
1040     491
1041     491
1042     492
1043     492
1044     493
1045     493
1046     494
1047     494
1048     495
1049     495
1050     496
1051     496
1052     497
1053     497
1054     498
1055     498
1056     498
1057     499
1058     499
1059     500
1060     500
1061     501
1062     501
1063     502
1064     502
1065     503
1066     503
1067     504
1068     504
1069     505
1070     505
1071     506
1072     506
1073     507
1074     507
1075     508
1076     508
1077     508
1078     509
1079     509
1080     510
1081     510
1082     511
1083     511
1084     512
1085     512
1086     513
1087     513
1088     514
1089     514
1090     515
1091     515
1092     516
1093     516
1094     517
1095     517
1096     518
1097     518
1098     518
1099     519
1100     519
1101     520
1102     520
1103     521
1104     521
1105     522
1106     522
1107     523
1108     523
1109     524
1110     524
1111     525
1112     525
1113     526
1114     526
1115     527
1116     527
1117     528
1118     528
1119     529
1120     529
1121     530
1122     530
1123     531
1124     531
1125     532
1126     532
1127     533
1128     533
1129     534
1130     534
1131     535
1132     535
1133     536
1134     536
1135     537
1136     537
1137     538
1138     538
1139     539
1140     539
1141     540
1142     540
1143     541
1144     541
1145     542
1146     542
1147     543
1148     543
1149     544
1150     544
1151     545
1152     545
1153     546
1154     546
1155     547
1156     547
1157     548
1158     548
1159     549
1160     549
1161     550
1162     550
1163     551
1164     551
1165     552
1166     552
1167     553
1168     553
1169     554
1170     554
1171     555
1172     555
1173     556
1174     556
1175     557
1176     557
1177     557
1178     558
1179     558
1180     559
1181     559
1182     560
1183     560
1184     561
1185     561
1186     562
1187     562
1188     563
1189     563
1190     564
1191     564
1192     564
1193     565
1194     565
1195     566
1196     566
1197     567
1198     567
1199     568
1200     568
1201     569
1202     569
1203     570
1204     570
1205     571
1206     571
1207     572
1208     572
1209     573
1210     573
1211     574
1212     574
1213     575
1214     575
1215     576
1216     576
1217     577
1218     577
1219     578
1220     578
1221     579
1222     579
1223     580
1224     580
1225     581
1226     581
1227     582
1228     582
1229     583
1230     583
1231     584
1232     584
1233     585
1234     585
1235     586
1236     586
1237     587
1238     587
1239     588
1240     588
1241     588
1242     589
1243     589
1244     590
1245     590
1246     591
1247     591
1248     592
1249     592
1250     593
1251     593
1252     594
1253     594
1254     595
1255     595
1256     596
1257     596
1258     597
1259     597
1260     598
1261     598
1262     599
1263     599
1264     600
1265     600
1266     601
1267     601
1268     602
1269     602
1270     603
1271     603
1272     604
1273     604
1274     605
1275     605
1276     606
1277     606
1278     607
1279     607
1280     608
1281     608
1282     609
1283     609
1284     610
1285     610
1286     611
1287     611
1288     612
1289     612
1290     613
1291     613
1292     614
1293     614
1294     615
1295     615
1296     615
1297     616
1298     616
1299     617
1300     617
1301     618
1302     618
1303     619
1304     619
1305     619
1306     620
1307     620
1308     621
1309     621
1310     622
1311     622
1312     623
1313     623
1314     624
1315     624
1316     625
1317     625
1318     626
1319     626
1320     627
1321     627
1322     628
1323     628
1324     629
1325     629
1326     630
1327     630
1328     631
1329     631
1330     632
1331     632
1332     632
1333     633
1334     633
1335     633
1336     634
1337     634
1338     635
1339     635
1340     636
1341     636
1342     637
1343     637
1344     638
1345     638
1346     639
1347     639
1348     639
1349     640
1350     640
1351     641
1352     641
1353     642
1354     642
1355     643
1356     643
1357     644
1358     644
1359     645
1360     645
1361     646
1362     646
1363     647
1364     647
1365     648
1366     648
1367     649
1368     649
1369     650
1370     650
1371     651
1372     651
1373     652
1374     652
1375     653
1376     653
1377     654
1378     654
1379     655
1380     655
1381     656
1382     656
1383     657
1384     657
1385     658
1386     658
1387     659
1388     659
1389     660
1390     660
1391     661
1392     661
1393     662
1394     662
1395     663
1396     663
1397     664
1398     664
1399     665
1400     665
1401     666
1402     666
1403     667
1404     667
1405     668
1406     668
1407     669
1408     669
1409     670
1410     670
1411     671
1412     671
1413     672
1414     672
1415     673
1416     673
1417     674
1418     674
1419     675
1420     675
1421     676
1422     676
1423     677
1424     677
1425     678
1426     678
1427     679
1428     679
1429     680
1430     680
1431     681
1432     681
1433     682
1434     682
1435     683
1436     683
1437     684
1438     684
1439     685
1440     685
1441     686
1442     686
1443     687
1444     687
1445     688
1446     688
1447     689
1448     689
1449     690
1450     690
1451     691
1452     691
1453     692
1454     692
1455     693
1456     693
1457     694
1458     694
1459     695
1460     695
1461     696
1462     696
1463     697
1464     697
1465     698
1466     698
1467     699
1468     699
1469     700
1470     700
1471     701
1472     701
1473     701
1474     702
1475     702
1476     703
1477     703
1478     704
1479     704
1480     704
1481     705
1482     705
1483     706
1484     706
1485     707
1486     707
1487     708
1488     708
1489     709
1490     709
1491     710
1492     710
1493     711
1494     711
1495     712
1496     712
1497     713
1498     713
1499     714
1500     714
1501     715
1502     715
1503     716
1504     716
1505     717
1506     717
1507     718
1508     718
1509     719
1510     719
1511     719
1512     720
1513     720
1514     721
1515     721
1516     722
1517     722
1518     723
1519     723
1520     724
1521     724
1522     725
1523     725
1524     726
1525     726
1526     727
1527     727
1528     728
1529     728
1530     729
1531     729
1532     730
1533     730
1534     731
1535     731
1536     732

In [54]:
mask = (
    df["regular_price"].notna() &
    df["price_was"].notna() &
    (pd.to_numeric(df["regular_price"], errors="coerce") !=
     pd.to_numeric(df["price_was"], errors="coerce"))
)

issues = df.loc[mask, ["pdp_url", "regular_price", "price_was"]].copy()
issues["row_no"] = issues.index + 2

issues = issues[["row_no", "pdp_url", "regular_price", "price_was"]]

issues

KeyError: 'price_was'

In [55]:
mask = (
    df["unique_id"].astype(str).fillna("") + "P"
    !=
    df["product_unique_key"].astype(str).fillna("")
)

issues = df.loc[mask, ["unique_id", "product_unique_key", "pdp_url"]].copy()
issues["row_no"] = issues.index + 2

issues = issues[["row_no", "pdp_url", "unique_id", "product_unique_key"]]

issues

KeyError: 'product_unique_key'

In [56]:
import pandas as pd

# Normalize for case-insensitive comparison
df["site_shown_uom"] = df["site_shown_uom"].fillna("").astype(str)
df["grammage_unit"] = df["grammage_unit"].fillna("").astype(str)
df["grammage_quantity"] = df["grammage_quantity"].fillna("").astype(str)

# -----------------------------
# Rule 1: Teebeutel / Beutel -> btl
# -----------------------------
btl_keywords = [
    "Teebeutel Packung",
    "Teebeutel",
    "Beutel",
    "Btl",
    "Teebeutel Karton",
    "Teebeutel Paket",
    "Packung Beutel"
]

btl_invalid = df[
    df["site_shown_uom"].str.contains("|".join(btl_keywords), case=False, regex=True)
    &
    (df["grammage_unit"].str.lower() != "btl")
]

print(f"BTL unit mismatches: {len(btl_invalid)}")
display(btl_invalid[[
    "unique_id",
    "product_name",
    "site_shown_uom",
    "grammage_quantity",
    "grammage_unit"
]])

# -----------------------------
# Rule 2: Portion Packung / ANW -> stuck
# -----------------------------
stuck_keywords = [
    "Portion Packung",
    "ANW"
]

stuck_invalid = df[
    df["site_shown_uom"].str.contains("|".join(stuck_keywords), case=False, regex=True)
    &
    (df["grammage_unit"].str.lower() != "stuck")
]

print(f"STUCK unit mismatches: {len(stuck_invalid)}")
display(stuck_invalid[[
    "unique_id",
    "product_name",
    "site_shown_uom",
    "grammage_quantity",
    "grammage_unit"
]])

# -----------------------------
# Rule 3: wg / Waschgänge -> wg
# -----------------------------
wg_keywords = [
    "wg",
    "Waschgänge"
]

wg_invalid = df[
    df["site_shown_uom"].str.contains("|".join(wg_keywords), case=False, regex=True)
    &
    (df["grammage_unit"].str.lower() != "wg")
]

print(f"WG unit mismatches: {len(wg_invalid)}")
display(wg_invalid[[
    "unique_id",
    "product_name",
    "site_shown_uom",
    "grammage_quantity",
    "grammage_unit",
    "pdp_url"
]])

BTL unit mismatches: 160

,unique_id,product_name,site_shown_uom,grammage_quantity,grammage_unit
112,2020003506550,SPAR Müllbeutel mit Duft 30l 20 Stk.,SPAR Müllbeutel mit Duft 30l 20 Stk.,30,l
117,2020003507151,SPAR Öko Müllbeutel 150l 8 Stk.,SPAR Öko Müllbeutel 150l 8 Stk.,150,l
119,2020003471797,SPAR Biomüllbeutel 120l 5 Stk.,SPAR Biomüllbeutel 120l 5 Stk.,120,l
217,2020003471179,SPAR Biomüllbeutel 30l 8 Stk.,SPAR Biomüllbeutel 30l 8 Stk.,30,l
230,2020004008084,SPAR Gefrierbeutel 6l,SPAR Gefrierbeutel 6l,6,l
262,2020004008060,SPAR Gefrierbeutel 1l,SPAR Gefrierbeutel 1l,1,l
263,2020005369887,SPAR Müllbeutel Fixierband,SPAR Müllbeutel Fixierband,1,stück
266,2020006225847,SPAR Müllbeutel Tragegriff 50L,SPAR Müllbeutel Tragegriff 50L,50,l
272,2020003506536,SPAR Müllbeutel mit Duft 20l 20 Stk.,SPAR Müllbeutel mit Duft 20l 20 Stk.,20,l
284,2020006225908,SPAR Müllbeutel Recycling mit Tragegriff 20L,SPAR Müllbeutel Recycling mit Tragegriff 20L,20,l
487,2020003506598,SPAR Bio Kompostbeutel 10l 10 Stk.,SPAR Bio Kompostbeutel 10l 10 Stk.,10,l
490,2020003471780,SPAR Biomüllbeutel 10l 10 Stk.,SPAR Biomüllbeutel 10l 10 Stk.,10,l
502,2020003506697,SPAR Öko Müllbeutel mit Zugband 35l 20 Stk.,SPAR Öko Müllbeutel mit Zugband 35l 20 Stk.,35,l
507,2020003506437,SPAR Schwerlast Müllbeutel offen 110l 10 Stk.,SPAR Schwerlast Müllbeutel offen 110l 10 Stk.,110,l
509,2020004627872,SPAR Butterbrot-Beutel 80 Stück,SPAR Butterbrot-Beutel 80 Stück,80,stück
526,2020003912603,SPAR Gefrierbeutel 15 x 3 l,SPAR Gefrierbeutel 15 x 3 l,15 x 3,l
533,2020003506512,SPAR Müllbeutel Antigeruch 10l 40 Stk.,SPAR Müllbeutel Antigeruch 10l 40 Stk.,10,l
538,2020003506581,SPAR Müllbeutel mit Duft 60l 25 Stk.,SPAR Müllbeutel mit Duft 60l 25 Stk.,60,l
617,2020004946829,SPAR Biomüllbeutel mit Zugband 15L 8 Stk.,SPAR Biomüllbeutel mit Zugband 15L 8 Stk.,15,l
630,2020006225885,SPAR Müllbeutel mit Zugband extra lang 50-70L,SPAR Müllbeutel mit Zugband extra lang 50-70L,50-70,l
754,2020003506413,SPAR Müllbeutel offen 25l 40 Stk.,SPAR Müllbeutel offen 25l 40 Stk.,25,l
756,2020003912627,SPAR Gefrierbeutel 10 x 6 l,SPAR Gefrierbeutel 10 x 6 l,10 x 6,l
758,2020006225915,SPAR Müllbeutel Recycling mit Tragegriff 35L,SPAR Müllbeutel Recycling mit Tragegriff 35L,35,l
761,2020003506451,SPAR Müllbeutel mit Griff 10l 80 Stk.,SPAR Müllbeutel mit Griff 10l 80 Stk.,10,l
764,2020003507120,SPAR Öko Müllbeutel mit Zugband 120l 10 Stk.,SPAR Öko Müllbeutel mit Zugband 120l 10 Stk.,120,l
834,2020003506499,SPAR Müllbeutel mit Zugband extra breit 25l 30 Stk.,SPAR Müllbeutel mit Zugband extra breit 25l 30 Stk.,25,l
838,2020003506475,SPAR Müllbeutel mit Zugband 45l 20 Stk.,SPAR Müllbeutel mit Zugband 45l 20 Stk.,45,l
847,2020004629203,SPAR Spritzbeutel 31 cm 1 Adapter und 4 Tüllen,SPAR Spritzbeutel 31 cm 1 Adapter und 4 Tüllen,1,stück
871,2020003506635,SPAR Öko Müllbeutel mit Zugband 20l 25 Stk.,SPAR Öko Müllbeutel mit Zugband 20l 25 Stk.,20,l
889,2020006225861,SPAR Müllbeutel mit Zugband extra lang 35-40L,SPAR Müllbeutel mit Zugband extra lang 35-40L,35-40,l
897,2020005369931,SPAR Müllbeutel Fixierband,SPAR Müllbeutel Fixierband,1,stück
928,2020004008077,SPAR Gefrierbeutel 3l,SPAR Gefrierbeutel 3l,3,l
945,2020003912580,SPAR Gefrierbeutel Zip 20x1,SPAR Gefrierbeutel Zip 20x1,1,stück
1121,2020003506505,SPAR Müllbeutel mit Zugband extra breit 35l 25 Stk.,SPAR Müllbeutel mit Zugband extra breit 35l 25 Stk.,35,l
1136,2020003904530,SPAR Eiswürfelbeutel 12x9,SPAR Eiswürfelbeutel 12x9,1,stück
1145,2020003506468,SPAR Müllbeutel mit Zugband 35l 30 Stk.,SPAR Müllbeutel mit Zugband 35l 30 Stk.,35,l
1148,2020003507090,SPAR Öko Müllbeutel mit Zugband 60l 15 Stk.,SPAR Öko Müllbeutel mit Zugband 60l 15 Stk.,60,l
1149,2020003506482,SPAR Müllbeutel mit Zugband 70l 20 Stk.,SPAR Müllbeutel mit Zugband 70l 20 Stk.,70,l
1287,2020004350077,S-BUDGET Gefrierbeutel,S-BUDGET Gefrierbeutel,1,stück
1311,2020004627926,S-BUDGET Jausen-Beutel 120 Stück,S-BUDGET Jausen-Beutel 120 Stück,120,stück
1381,2020003912566,S-BUDGET Gefrierbeutel 41 x 6 l,S-BUDGET Gefrierbeutel 41 x 6 l,41 x 6,l
1383,2020003506284,S-BUDGET Müllbeutel mit Griff 25l 50 Stk.,S-BUDGET Müllbeutel mit Griff 25l 50 Stk.,25,l
1743,2020004578143,S-BUDGET Gefrierbeutel 75 x 3 l,S-BUDGET Gefrierbeutel 75 x 3 l,75 x 3,l
2001,2020003506406,S-BUDGET Müllbeutel mit Zugband 60l 20 Stk.,S-BUDGET Müllbeutel mit Zugband 60l 20 Stk.,60,l
2160,2020003506352,S-BUDGET Müllbeutel mit Zugband 30l 35 Stk.,S-BUDGET Müllbeutel mit Zugband 30l 35 Stk.,30,l
5007,2020001803521,SIMPEX BASIC Vakuum Beutel 55 x 90 cm 3 Stück,SIMPEX BASIC Vakuum Beutel 55 x 90 cm 3 Stück,3,stück
5731,2020002879266,SIMPEX BASIC Vakuumiergerät inkl. 5 Vakuumier-Beutel,SIMPEX BASIC Vakuumiergerät inkl. 5 Vakuumier-Beutel,1,stück
5940,2020001801657,SIMPEX BASIC Vakuum Beutel 73 x 130 cm 2 Stück,SIMPEX BASIC Vakuum Beutel 73 x 130 cm 2 Stück,2,stück
6958,2020002517069,SIMPEX BASIC Beutelstaubsauger Compact,SIMPEX BASIC Beutelstaubsauger Compact,1,stück
7966,6638887,Swirl Müllbeutel mit Fixierband 35 Liter 10 Stück,Swirl Müllbeutel mit Fixierband 35 Liter 10 Stück,35,l
8002,2020004972194,Siemens Beutelstaubsauger Z 3.0,Siemens Beutelstaubsauger Z 3.0,1,stück
8402,4083641,Toppits Jausenbeutel 18x25cm 45 Stück,Toppits Jausenbeutel 18x25cm 45 Stück,45,stück
9282,2020002964146,Swirl Staubsaugerbeutel S67/4,Swirl Staubsaugerbeutel S67/4,1,stück
9367,2020002243302,Toppits Eiskugelbeutel 10 Stück,Toppits Eiskugelbeutel 10 Stück,10,stück
9513,6707552,Swirl Staubsaugerbeutel Y 50 4 Stück,Swirl Staubsaugerbeutel Y 50 4 Stück,4,stück
9691,2020003815201,Swirl Müllbeutel mit Zugband 60 Liter,Swirl Müllbeutel mit Zugband 60 Liter,60,l
9837,2020003813498,Swirl Müllbeutel Anti Geruch 35 Liter,Swirl Müllbeutel Anti Geruch 35 Liter,35,l
10429,2020000700814,Swirl Bio Müllbeutel 35 Liter 6 Stück,Swirl Bio Müllbeutel 35 Liter 6 Stück,35,l
11749,2020004148568,Swirl Öko Müllbeutel mit Zugband 35 Liter 12 Stück,Swirl Öko Müllbeutel mit Zugband 35 Liter 12 Stück,35,l
12279,2020002692599,Kuwopa Oster Textilbeutel Hase,Kuwopa Oster Textilbeutel Hase,1,stück
12402,2020006309462,Severin Beutelstaubsauger BC 7047,Severin Beutelstaubsauger BC 7047,1,stück
12838,8067555,Swirl Staubsaugerbeutel R36 4 Stück,Swirl Staubsaugerbeutel R36 4 Stück,4,stück
13078,2020003760822,Kuwopa Ostereier im Beutel,Kuwopa Ostereier im Beutel,1,stück
13374,4693840,Toppits Spritzbeutel 10 Stück,Toppits Spritzbeutel 10 Stück,10,stück
13419,7271205,Swirl Staubsaugerbeutel Y30/4 Y30 4 Stück,Swirl Staubsaugerbeutel Y30/4 Y30 4 Stück,4,stück
13423,2020003815188,Swirl Müllbeutel mit Zugband 20 Liter,Swirl Müllbeutel mit Zugband 20 Liter,20,l
13427,2101200,Swirl Duft Müllbeutel Hochkant 20 Liter 12 Stück,Swirl Duft Müllbeutel Hochkant 20 Liter 12 Stück,20,l
13546,2020006137089,Undercover Schuhbeutel Lilo & Stitch,Undercover Schuhbeutel Lilo & Stitch,1,stück
13790,2778495,Swirl Bio-Müllbeutel 10 Liter 10 Stück,Swirl Bio-Müllbeutel 10 Liter 10 Stück,10,l
13903,2020003224034,Kuwopa Oster Stoffbeutel Hase,Kuwopa Oster Stoffbeutel Hase,1,stück
13904,6664749,Swirl Staubsaugerbeutel PH86/99 4 Stück,Swirl Staubsaugerbeutel PH86/99 4 Stück,4,stück
14636,2020005894983,Bosch Beutelstaubsauger Serie 2,Bosch Beutelstaubsauger Serie 2,1,stück
14802,4550433,Samarin Brausepulver 18 Portionsbeutel,Samarin Brausepulver 18 Portionsbeutel,1,stück
15794,2020003815010,Swirl Duft Müllbeutel 35 Liter,Swirl Duft Müllbeutel 35 Liter,35,l
16316,2020000926900,Swirl Staubbeutel R39,Swirl Staubbeutel R39,1,stück
18210,6661595,Swirl Staubsaugerbeutel M50 4 Stück,Swirl Staubsaugerbeutel M50 4 Stück,4,stück
18469,6661786,Swirl Staubsaugerbeutel Y101 4 Stück,Swirl Staubsaugerbeutel Y101 4 Stück,4,stück
18480,2020006114080,Kuwopa Stoffbeutel Hase sortiert,Kuwopa Stoffbeutel Hase sortiert,1,stück
18732,2020005415294,Siemens Staubsauger mit Beutel Z 7.0,Siemens Staubsauger mit Beutel Z 7.0,1,stück
19274,2020005934177,Swirl Staubsaugerbeutel S62 4 Stück,Swirl Staubsaugerbeutel S62 4 Stück,4,stück
19490,2148540,Toppits Gefrierbeutel 6 Liter 20 Stück,Toppits Gefrierbeutel 6 Liter 20 Stück,6,l
19507,2020003011641,Podravka Vegeta Würzmischung mit Gemüse im Beutel 150g,Podravka Vegeta Würzmischung mit Gemüse im Beutel 150g,150,g
19823,7899546,Swirl Duft Müllbeutel mit Zugband 10 Liter 14 Stück,Swirl Duft Müllbeutel mit Zugband 10 Liter 14 Stück,10,l
19913,2020003813276,Swirl Müllbeutel Anti Geruch 20 Liter,Swirl Müllbeutel Anti Geruch 20 Liter,20,l
20269,2020004009890,Rowenta Beutelsauger Power RO3953EA,Rowenta Beutelsauger Power RO3953EA,1,stück
20282,1290400,Swirl Bio Müllbeutel 10 Liter 8 Stück,Swirl Bio Müllbeutel 10 Liter 8 Stück,10,l
20373,6661489,Swirl Staubsaugerbeutel M49 4 Stück,Swirl Staubsaugerbeutel M49 4 Stück,4,stück
20466,2020006136860,Undercover Schuhbeutel bluey,Undercover Schuhbeutel bluey,1,stück
21115,1060454,Swirl Bio-Müllbeutel 20 Liter 6 Stück,Swirl Bio-Müllbeutel 20 Liter 6 Stück,20,l
21413,5675760,Kuwopa Kunststoff Eier im Beutel,Kuwopa Kunststoff Eier im Beutel,1,stück
21603,2020006118255,Wildplastic Müllbeutel 35L,Wildplastic Müllbeutel 35L,35,l
21779,2020006165105,Beko Toplader Waschmaschine BTL1WFP10724AT 7kg,Beko Toplader Waschmaschine BTL1WFP10724AT 7kg,7,kg
22661,2020006184120,"HAO HAO Instant Noodles Beutel Shrimp, Chili, Lime 78g","HAO HAO Instant Noodles Beutel Shrimp, Chili, Lime 78g",78,g
22950,2020004277121,Toppits Frühstücksbeutel mit Powerklemme 55x1L,Toppits Frühstücksbeutel mit Powerklemme 55x1L,55x1,l
23448,2317250,Swirl Bio-Müllbeutel 10 Liter 8 Stück,Swirl Bio-Müllbeutel 10 Liter 8 Stück,10,l
23532,6661687,Swirl Staubsaugerbeutel S 67 4 Stück,Swirl Staubsaugerbeutel S 67 4 Stück,4,stück
23611,2020006078030,Swirl Staubsaugerbeutel M60 4 Stück,Swirl Staubsaugerbeutel M60 4 Stück,4,stück
23830,2020001693436,Swirl Staubsaugerbeutel M50/4,Swirl Staubsaugerbeutel M50/4,1,stück
24718,6661465,Swirl Staubsaugerbeutel M40/M50 4 Stück,Swirl Staubsaugerbeutel M40/M50 4 Stück,4,stück
24843,2020003815218,Swirl Müllbeutel mit Tragegriff 20 Liter,Swirl Müllbeutel mit Tragegriff 20 Liter,20,l
25372,2020005525771,Kuwopa Stoffbeutel Hase mit Ohren,Kuwopa Stoffbeutel Hase mit Ohren,1,stück
25655,2020004669162,Swirl Müllbeutel mit Zugband 35 Liter 11 Stück,Swirl Müllbeutel mit Zugband 35 Liter 11 Stück,35,l
25778,2020005723986,"Birkmann BreadBuddies Brotbeutel 38 x 45 cm, 100 % Baumwolle","Birkmann BreadBuddies Brotbeutel 38 x 45 cm, 100 % Baumwolle",1,stück
25811,2020002225544,Defrost Auftausalz im Beutel 5kg,Defrost Auftausalz im Beutel 5kg,5,kg
25902,6664718,Swirl Staubsaugerbeutel N73/4 N73 4 Stück,Swirl Staubsaugerbeutel N73/4 N73 4 Stück,4,stück
26371,2020006118293,Wildplastic Müllbeutel 60 L,Wildplastic Müllbeutel 60 L,60,l
26394,2020003815232,Swirl Müllbeutel mit Tragegriff 35 Liter,Swirl Müllbeutel mit Tragegriff 35 Liter,35,l
26421,2020000596585,Swirl Staubsaugerbeutel N74/4,Swirl Staubsaugerbeutel N74/4,1,stück
26512,2020004148599,Swirl Öko Müllbeutel mit Zugband 60 Liter 8 Stück,Swirl Öko Müllbeutel mit Zugband 60 Liter 8 Stück,60,l
27070,2020002964160,Swirl Staubsaugerbeutel PH86/4,Swirl Staubsaugerbeutel PH86/4,1,stück
27178,2020003274923,Toppits ÖKO Gefrierbeutel 3L,Toppits ÖKO Gefrierbeutel 3L,3,l
27385,2148458,Toppits Gefrierbeutel 3 Liter 35 Stück,Toppits Gefrierbeutel 3 Liter 35 Stück,3,l
27472,2020005990661,Swirl Staubsaugerbeutel Y 45 Mit 1 Fiiter,Swirl Staubsaugerbeutel Y 45 Mit 1 Fiiter,1,stück
27611,5405398,Swirl Müllbeutel mit Zugband 35 Liter 25 Stück,Swirl Müllbeutel mit Zugband 35 Liter 25 Stück,35,l
27960,2765655,Dr. Beckmann Mitwaschbeutel Super weiß 2 Stück,Dr. Beckmann Mitwaschbeutel Super weiß 2 Stück,2,stück
28144,6661649,Swirl Staubsaugerbeutel S62 4 Stück,Swirl Staubsaugerbeutel S62 4 Stück,4,stück
28685,2020006118187,Wildplastic Müllbeutel 25 L,Wildplastic Müllbeutel 25 L,25,l
29606,2020005859739,PartyXPeople Kakerlaken im Beutel 50 Stück,PartyXPeople Kakerlaken im Beutel 50 Stück,50,stück
29680,2020000952527,Swirl Staubsaugerbeutel Y12 4 Stück,Swirl Staubsaugerbeutel Y12 4 Stück,4,stück
29716,2020003733734,GEJO Lavendel - blütenbeutel,GEJO Lavendel - blütenbeutel,1,stück
29723,6676612,Swirl Staubsaugerbeutel A06/4 A06 4 Stück,Swirl Staubsaugerbeutel A06/4 A06 4 Stück,4,stück
30134,2020005867956,Beast Müllbeutel 120L extra stark 10 Stück,Beast Müllbeutel 120L extra stark 10 Stück,120,l
30811,6452933,Kuwopa Kunsteier im Beutel,Kuwopa Kunsteier im Beutel,1,stück
31124,2020004901682,Dr. Oetker Spritzbeutel-Set 2 Tüllen Profi,Dr. Oetker Spritzbeutel-Set 2 Tüllen Profi,1,stück
31238,2020003776281,Miele Beutelstaubsauger Complete C3 Powerline,Miele Beutelstaubsauger Complete C3 Powerline,1,stück
31264,2020004669179,Swirl Müllbeutel mit Zugband 60 Liter 8 Stück,Swirl Müllbeutel mit Zugband 60 Liter 8 Stück,60,l
31412,2020001905027,Schlaraffenland Dekoration Zimtstangen im Beutel klein,Schlaraffenland Dekoration Zimtstangen im Beutel klein,1,stück
31753,2020004148506,Swirl Öko Müllbeutel mit Zugband 20 Liter 18 Stück,Swirl Öko Müllbeutel mit Zugband 20 Liter 18 Stück,20,l
31926,2020003345647,Philips Beutelstaubsauger FC8240/09 Power Go,Philips Beutelstaubsauger FC8240/09 Power Go,1,stück
32408,2020003814938,Swirl Duft Müllbeutel 20 Liter,Swirl Duft Müllbeutel 20 Liter,20,l
32489,6676971,Swirl Staubsaugerbeutel Y05 4 Stück,Swirl Staubsaugerbeutel Y05 4 Stück,4,stück
32511,2020000432456,Toppits Gefrierbeutel 3 Liter Safeloc,Toppits Gefrierbeutel 3 Liter Safeloc,3,l
32782,2020001905010,Schlaraffenland Deko Arnis im Beutel,Schlaraffenland Deko Arnis im Beutel,1,stück
32852,2020005867949,Beast Müllbeutel 60L extra stark 10 Stück,Beast Müllbeutel 60L extra stark 10 Stück,60,l
33626,2020003814853,Swirl Müllbeutel mit Fixierband 20 Liter,Swirl Müllbeutel mit Fixierband 20 Liter,20,l
33815,2020005867918,Beast Müllbeutel 35L mit Zugband 10 Stück,Beast Müllbeutel 35L mit Zugband 10 Stück,35,l
34657,2020004964304,Swirl Staubsaugerbeutel M40 Neutralize Air,Swirl Staubsaugerbeutel M40 Neutralize Air,1,stück
34666,2020006136914,Undercover Schuhbeutel Minnie Mouse,Undercover Schuhbeutel Minnie Mouse,1,stück
34782,2020001905041,Schlaraffenland Zimtstangen im Beutel Groß 25cm 75g,Schlaraffenland Zimtstangen im Beutel Groß 25cm 75g,75,g
35875,2020004669148,Swirl Müllbeutel mit Zugband 20 Liter 15 Stück,Swirl Müllbeutel mit Zugband 20 Liter 15 Stück,20,l
36104,6664619,Swirl Staubsaugerbeutel A07 4 Stück,Swirl Staubsaugerbeutel A07 4 Stück,4,stück
36161,2147567,Toppits Gefrierbeutel 1 Liter 35 Stück,Toppits Gefrierbeutel 1 Liter 35 Stück,1,l
36167,5080571,Swirl Anti Calc Bio Entkalker Pulver Anti Kalk Beutel 2 x 20g,Swirl Anti Calc Bio Entkalker Pulver Anti Kalk Beutel 2 x 20g,2 x 20,g
36231,2020002964184,Swirl Staubsaugerbeutel A07/4,Swirl Staubsaugerbeutel A07/4,1,stück
36240,2020003815195,Swirl Müllbeutel mit Zugband 35 Liter,Swirl Müllbeutel mit Zugband 35 Liter,35,l
36531,2389493,"Toppits Gefrierbeutel Set 1l, 3l, 6l 3er Vorteilspack","Toppits Gefrierbeutel Set 1l, 3l, 6l 3er Vorteilspack",6,l
36742,2020005997172,Silva Homeline Beutelstaubsauger BS 8000,Silva Homeline Beutelstaubsauger BS 8000,1,stück
36963,1228601,Swirl Staubsaugerbeutel S73 4 Stück,Swirl Staubsaugerbeutel S73 4 Stück,4,stück
37152,2020003814914,Swirl Duft-Müllbeutel 10 Liter,Swirl Duft-Müllbeutel 10 Liter,10,l
37163,2020006137126,Undercover Schuhbeutel Super Mario,Undercover Schuhbeutel Super Mario,1,stück
37245,2020005687585,Miele Staubsaugerbeutel HyClean Pure TU,Miele Staubsaugerbeutel HyClean Pure TU,1,stück
37392,2020006152877,Philips Beutelstaubsauger XD1142/10,Philips Beutelstaubsauger XD1142/10,1,stück
37628,2020003648243,Trisa Beutellosssauger Clean Angel T6324,Trisa Beutellosssauger Clean Angel T6324,1,stück
37800,8209283,Swirl Müllbeutel mit Fixierband 20 Liter 20 Stück,Swirl Müllbeutel mit Fixierband 20 Liter 20 Stück,20,l
38332,2020000904502,Kuwopa Osterhase mit Beutel,Kuwopa Osterhase mit Beutel,1,stück
38579,2020003813528,Swirl Müllbeutel Anti Geruch 60 L,Swirl Müllbeutel Anti Geruch 60 L,60,l
38789,2020003650611,Kuwopa Plüschhase mit Beutel,Kuwopa Plüschhase mit Beutel,1,stück
38849,2020005341661,Swirl Müllbeutel Winterzauber 35 L Spicy-Orange,Swirl Müllbeutel Winterzauber 35 L Spicy-Orange,35,l
38899,1833829,Swirl Staubsaugerbeutel M52 4 Stück,Swirl Staubsaugerbeutel M52 4 Stück,4,stück
39194,2020005448896,Grundig Beutelstaubsauger VCC3851,Grundig Beutelstaubsauger VCC3851,1,stück

STUCK unit mismatches: 1

,unique_id,product_name,site_shown_uom,grammage_quantity,grammage_unit
15134,2020002299026,Syoss Cool Blonds Haarcoloration 10-55 Platinum Blond 1 Anwendung,Syoss Cool Blonds Haarcoloration 10-55 Platinum Blond 1 Anwendung,1,stück

WG unit mismatches: 10

,unique_id,product_name,site_shown_uom,grammage_quantity,grammage_unit,pdp_url
7461,2020005400351,Siemens Waschmaschine WG44G2Z22 9kg,Siemens Waschmaschine WG44G2Z22 9kg,9,kg,https://www.spar.at/produktwelt/siemens-waschmaschine-9kg-p2020005400351
14399,2020006269643,Gorenje Waschmaschine WG2PS74AP2/AT,Gorenje Waschmaschine WG2PS74AP2/AT,1,stück,https://www.spar.at/produktwelt/gorenje-waschmaschine-wg2ps74ap2-at-p2020006269643
24253,2020005407312,Bosch Waschmaschine WGE0241H 7 kg,Bosch Waschmaschine WGE0241H 7 kg,7,kg,https://www.spar.at/produktwelt/bosch-waschmaschine-wge0241h-7-kg-p2020005407312
30356,2020006269452,Gorenje Waschmaschine WG474A2P1,Gorenje Waschmaschine WG474A2P1,1,stück,https://www.spar.at/produktwelt/gorenje-waschmaschine-wg474a2p1-p2020006269452
31588,2020005906921,Siemens Waschmaschine iQ500 WG44G2ZEM,Siemens Waschmaschine iQ500 WG44G2ZEM,1,stück,https://www.spar.at/produktwelt/siemens-waschmaschine-iq500-wg44g2zem-p2020005906921
33141,2020005032477,Gorenje Waschmaschine WGPNEI14A2DTS 10 kg,Gorenje Waschmaschine WGPNEI14A2DTS 10 kg,10,kg,https://www.spar.at/produktwelt/gorenje-waschmaschine-wgpnei14a2dts-10-kg-p2020005032477
35395,2020006269674,Gorenje Waschmaschine WG2PS84A3P2/AT,Gorenje Waschmaschine WG2PS84A3P2/AT,1,stück,https://www.spar.at/produktwelt/gorenje-waschmaschine-wg2ps84a3p2-at-p2020006269674
35661,2020005680852,Siemens Waschmaschine WG46B2071 iQ700 9 kg,Siemens Waschmaschine WG46B2071 iQ700 9 kg,9,kg,https://www.spar.at/produktwelt/siemens-waschmaschine-wg46b2071-iq700-p2020005680852
35950,2020005677111,Siemens Waschmaschine WG44G2F 9 kg,Siemens Waschmaschine WG44G2F 9 kg,9,kg,https://www.spar.at/produktwelt/siemens-waschmaschine-wg44g2f-p2020005677111
38770,2020004680020,Siemens Waschmaschine WG44B20X40 9 kg,Siemens Waschmaschine WG44B20X40 9 kg,9,kg,https://www.spar.at/produktwelt/siemens-waschmaschine-wg44b20x40-p2020004680020

In [56]:
import pandas as pd

price_cols = ["regular_price", "selling_price"]

for col in price_cols:
    # Ignore missing values
    mask = (
        df[col].notna() &
        (~df[col].astype(float).round(2).eq(df[col].astype(float)))
    )

    invalid = df.loc[mask, ["unique_id", "product_name", col]]

    print(f"\n{col}: {len(invalid)} values not in 2-decimal format")
    display(invalid)

regular_price: 0 values not in 2-decimal format

Empty DataFrame
Columns: [unique_id, product_name, regular_price]
Index: []

selling_price: 0 values not in 2-decimal format

Empty DataFrame
Columns: [unique_id, product_name, selling_price]
Index: []

In [57]:
import pandas as pd

# Match both old and new site keywords
promo_mask = (
    df["promotion_description"]
    .fillna("")
    .astype(str)
    .str.contains(r"Trajno znižano|Znižano", case=False, na=False)
)

# Empty promotion price
promo_price_empty = (
    df["promotion_price"].isna()
    | df["promotion_price"].astype(str).str.strip().eq("")
)

# Check where promotion price is NOT empty
promo_price_issue = promo_mask & ~promo_price_empty

# Get all matching records
issues = df.loc[
    promo_mask,
    [
        "unique_id",
        "pdp_url",
        "promotion_description",
        "regular_price",
        "selling_price",
        "promotion_price"
    ]
].copy()

issues["row_no"] = issues.index + 2

# Add issue remarks
def check_issue(row):
    remarks = []

    if pd.notna(row["promotion_price"]) and str(row["promotion_price"]).strip() != "":
        remarks.append("promotion_price should be empty")

    if row["regular_price"] != row["selling_price"]:
        remarks.append("regular_price and selling_price are not equal")

    return "; ".join(remarks)

issues["issue"] = issues.apply(check_issue, axis=1)

# Show only violations
issues = issues[issues["issue"] != ""]

issues = issues[
    [
        "row_no",
        "unique_id",
        "pdp_url",
        "promotion_description",
        "regular_price",
        "selling_price",
        "promotion_price",
        "issue"
    ]
]

print(issues.to_string(index=False))

Empty DataFrame
Columns: [row_no, unique_id, pdp_url, promotion_description, regular_price, selling_price, promotion_price, issue]
Index: []

In [58]:
import re
import pandas as pd

# Normalize grammage_unit
df["grammage_unit_norm"] = df["grammage_unit"].fillna("").str.lower().str.strip()

# Extract quantity from site_shown_uom
df["site_qty"] = (
    df["site_shown_uom"]
      .str.extract(r"(\d+(?:[.,]\d+)?)", expand=False)
      .str.replace(",", ".", regex=False)
)

df["site_qty"] = pd.to_numeric(df["site_qty"], errors="coerce")

# ---------- Rule 1 : Beutel / Btl ----------
btl_pattern = (
    r"Teebeutel Packung|Teebeutel Karton|Teebeutel Paket|"
    r"Packung Beutel|Teebeutel|Beutel|Btl"
)

btl_issue = df[
    df["site_shown_uom"].fillna("").str.contains(btl_pattern, case=False, regex=True)
    &
    (
        (df["grammage_unit_norm"] != "btl") |
        (df["grammage_quantity"] != df["site_qty"])
    )
]

# ---------- Rule 2 : Portion Packung / ANW ----------
stuck_pattern = r"Portion Packung|ANW"

stuck_issue = df[
    df["site_shown_uom"].fillna("").str.contains(stuck_pattern, case=False, regex=True)
    &
    (
        (df["grammage_unit_norm"] != "stuck") |
        (df["grammage_quantity"] != df["site_qty"])
    )
]

# ---------- Rule 3 : Waschgang / Waschgänge / wg ----------
wg_pattern = r"\bwg\b|Waschgänge|Waschgang"

wg_issue = df[
    df["site_shown_uom"].fillna("").str.contains(wg_pattern, case=False, regex=True)
    &
    (
        (df["grammage_unit_norm"] != "wg") |
        (df["grammage_quantity"] != df["site_qty"])
    )
]

print("Btl issues:", len(btl_issue))
print("Stuck issues:", len(stuck_issue))
print("WG issues:", len(wg_issue))

Btl issues: 1162
Stuck issues: 0
WG issues: 83

In [59]:
import pandas as pd

text_cols = df.select_dtypes(include="object").columns

results = []

for col in text_cols:
    mask = df[col].fillna("").astype(str).str.contains(r" {2,}", regex=True)

    for idx, value in df.loc[mask, col].items():
        results.append({
            "row_no": idx + 2,
            "pdp_url": df.at[idx, "pdp_url"],
            "column": col,
            "issue_value": repr(value)
        })

issues_df = pd.DataFrame(results)
issues_df

Empty DataFrame
Columns: []
Index: []

In [60]:
btl_issue[
    [
        "unique_id",
        "product_name",
        "site_shown_uom",
        "grammage_quantity",
        "grammage_unit",
        "site_qty"
    ]
].head(20)

,unique_id,product_name,site_shown_uom,grammage_quantity,grammage_unit,site_qty
11,00-101513,Toppits Gefrierbeutel 6 Liter 20 Beutel Packung,20 Beutel Packung,1,stück,20.0
12,00-101511,Toppits Gefrierbeutel 1L 40 Beutel Packung,40 Beutel Packung,1,stück,40.0
48,00-116129,Kinder Schokobons 200 g Beutel,200 g Beutel,200,g,200.0
62,00-103992,Vegeta Würzmischung 1 kg Beutel,1 kg Beutel,1,kg,1.0
68,00-11697,Teekanne Früchtetee 20 Teebeutel Packung,20 Teebeutel Packung,20,btl,20.0
92,00-11080,Knorr Basis für Faschiertes 1 Packung Beutel,1 Packung Beutel,1,btl,1.0
98,00-129148,Teekanne Fixbutte 40 Teebeutel Paket,40 Teebeutel Paket,40,btl,40.0
99,00-129163,Teekanne Fixminze 40 Teebeutel Paket,40 Teebeutel Paket,40,btl,40.0
100,00-129189,Teekanne Fixmille 40 Teebeutel Packung,40 Teebeutel Packung,40,btl,40.0
104,00-133728,Twinings English Breakfast 50 Teebeutel Packung,50 Teebeutel Packung,50,btl,50.0
107,00-133710,Twinings Earl Grey 50 Teebeutel Packung,50 Teebeutel Packung,50,btl,50.0
129,00-1404,Ricola Schweizer Kräuterbonbon 75 g Beutel,75 g Beutel,75,g,75.0
135,00-141657,Ricola Salbei zuckerfrei 75 g Beutel,75 g Beutel,75,g,75.0
147,00-14270,Gloria Watte 200 g Beutel,200 g Beutel,200,g,200.0
170,00-144516,Ricola Zitronenmelisse zuckerfrei 75 g Beutel,75 g Beutel,75,g,75.0
198,00-17772,nimm2 Vitaminbonbons 240 g Beutel,240 g Beutel,240,g,240.0
211,00-17942,MAGGI Fix für Chili con Carne 1 Packung Beutel,1 Packung Beutel,1,btl,1.0
214,00-179846,Kotányi Pfeffer Schwarz Ganz 70 g Beutel,70 g Beutel,70,g,70.0
260,00-184150,Knorr Spätzle 200 g Beutel,200 g Beutel,200,g,200.0
291,00-20029,Samarin 36 Beutel Packung Medizinprodukt,36 Beutel Packung Medizinprodukt,1,stück,36.0

In [61]:
wrong_unit_wg = wg_issue[
    wg_issue["grammage_unit_norm"] != "wg"
]

wrong_qty_wg = wg_issue[
    (wg_issue["grammage_unit_norm"] == "wg") &
    (wg_issue["grammage_quantity"] != wg_issue["site_qty"])
]

print("WG - Wrong unit:", len(wrong_unit_wg))
print("WG - Wrong quantity:", len(wrong_qty_wg))

WG - Wrong unit: 79
WG - Wrong quantity: 4

In [62]:
wrong_unit_wg[
    [
        "unique_id",
        "product_name",
        "site_shown_uom",
        "grammage_quantity",
        "grammage_unit",
        "pdp_url"
    ]
]

,unique_id,product_name,site_shown_uom,grammage_quantity,grammage_unit,pdp_url
2096,00-393820,Persil Gel Color Activ 100 Waschgang Flasche,100 Waschgang Flasche,1,stück,https://shop.Billa.at/produkte/persil-gel-color-activ-00393820
3530,00-451977,bi good Lavendel Vollwaschmittel Beutel 25 Waschgang Beutel,25 Waschgang Beutel,1,stück,https://shop.Billa.at/produkte/bi-good-lavendel-vollwaschmittel-beutel-00451977
3533,00-451972,bi good Apfelblüte Colorwaschmittel Beutel 25 Waschgang Beutel,25 Waschgang Beutel,1,stück,https://shop.Billa.at/produkte/bi-good-apfelbluete-colorwaschmittel-beutel-00451972
3655,00-465128,Sagrotan Hygienespüler 20 Waschgang Flasche,20 Waschgang Flasche,1,stück,https://shop.Billa.at/produkte/sagrotan-hygienespueler-00465128
3814,00-471467,Lenor Weichspüler Goldene Orchidee 38 Waschgang Flasche,38 Waschgang Flasche,1,stück,https://shop.Billa.at/produkte/lenor-weichspueler-goldene-orchidee-00471467
4021,00-482549,Weißer Riese Trio Caps Orchidee 40 Waschgang Karton,40 Waschgang Karton,1,stück,https://shop.Billa.at/produkte/weisser-riese-trio-caps-orchidee-00482549
4022,00-482548,Weißer Riese Trio Caps Lotus 40 Waschgang Karton,40 Waschgang Karton,1,stück,https://shop.Billa.at/produkte/weisser-riese-trio-caps-lotus-00482548
4848,00-572851,Dr. Beckmann Magic Leaves Universal 25 Waschgang Stück,25 Waschgang Stück,1,stück,https://shop.Billa.at/produkte/dr-beckmann-magic-leaves-universal-00572851
4885,00-575505,Clever Weichspüler Pfirsich 60 Waschgang Flasche,60 Waschgang Flasche,1,stück,https://shop.Billa.at/produkte/clever-weichspueler-pfirsich-00575505
4890,00-575545,Clever Weichspüler Frische Quelle 60 Waschgang Flasche,60 Waschgang Flasche,1,stück,https://shop.Billa.at/produkte/clever-weichspueler-frische-quelle-00575545
5133,00-596229,Ariel Allin1 Pods Universal 22WL 22 Waschgang Karton,22 Waschgang Karton,1,stück,https://shop.Billa.at/produkte/ariel-allin1-pods-universal-22wl-00596229
5143,00-596227,Ariel Allin1 Pods Color 22WL 22 Waschgang Karton,22 Waschgang Karton,1,stück,https://shop.Billa.at/produkte/ariel-allin1-pods-color-22wl-00596227
5941,00-692622,Weißer Riese Riesenfrisch 45 Waschgang Packung,45 Waschgang Packung,1,stück,https://shop.Billa.at/produkte/weisser-riese-riesenfrisch-00692622
6108,00-701512,Frosch Waschpulver Sensitiv Aloe Vera 22 Waschgang Karton,22 Waschgang Karton,1,stück,https://shop.Billa.at/produkte/frosch-waschpulver-sensitiv-aloe-vera-00701512
6111,00-701510,Frosch Waschpulver Citrus 22 Waschgang Karton,22 Waschgang Karton,1,stück,https://shop.Billa.at/produkte/frosch-waschpulver-citrus-00701510
6451,00-716918,Persil Pulver Universal 28 Waschgang Packung,28 Waschgang Packung,1,stück,https://shop.Billa.at/produkte/persil-pulver-universal-00716918
6452,00-716917,Persil Pulver Frische von Silan 28 Waschgang Packung,28 Waschgang Packung,1,stück,https://shop.Billa.at/produkte/persil-pulver-frische-von-silan-00716917
6457,00-717011,Coral Flüssig Waschmittel Color 25 Waschgang Flasche,25 Waschgang Flasche,1,stück,https://shop.Billa.at/produkte/coral-fluessig-waschmittel-color-00717011
6466,00-717004,Coral Waschmittel Flüssig Wolle und Seide 25 Waschgang Flasche,25 Waschgang Flasche,1,stück,https://shop.Billa.at/produkte/coral-waschmittel-fluessig-wolle-und-seide-00717004
6753,00-723297,Persil Megapearls Universal 23 Waschgang Packung,23 Waschgang Packung,1,stück,https://shop.Billa.at/produkte/persil-megapearls-universal-00723297
6760,00-723301,Persil Megapearls Color 23 Waschgang Packung,23 Waschgang Packung,1,stück,https://shop.Billa.at/produkte/persil-megapearls-color-00723301
6766,00-723302,Persil Megapearls Universal 23 Waschgang Packung,23 Waschgang Packung,1,stück,https://shop.Billa.at/produkte/persil-megapearls-universal-00723302
6784,00-723327,Fewa Renew & Blütenrausch 20 Waschgang Flasche,20 Waschgang Flasche,1,stück,https://shop.Billa.at/produkte/fewa-renew-und-bluetenrausch-00723327
6785,00-723329,Fewa Renew Black 20 Waschgang Flasche,20 Waschgang Flasche,1,stück,https://shop.Billa.at/produkte/fewa-renew-black-00723329
6786,00-723335,Fewa Renew Color 20 Waschgang Flasche,20 Waschgang Flasche,1,stück,https://shop.Billa.at/produkte/fewa-renew-color-00723335
6787,00-723362,Silan Weichspüler Classic Fresh Sky 50 Waschgang Flasche,50 Waschgang Flasche,1,stück,https://shop.Billa.at/produkte/silan-weichspueler-classic-fresh-sky-00723362
6788,00-723358,Silan Wild Rose 50 WG 50 Waschgang Flasche,50 Waschgang Flasche,1,stück,https://shop.Billa.at/produkte/silan-wild-rose-50-wg-00723358
6789,00-723338,Fewa Renew Wolle 20 Waschgang Flasche,20 Waschgang Flasche,1,stück,https://shop.Billa.at/produkte/fewa-renew-wolle-00723338
6790,00-723337,Fewa Sport & Active 20 Waschgang Flasche,20 Waschgang Flasche,1,stück,https://shop.Billa.at/produkte/fewa-sport-und-active-00723337
6791,00-723361,Silan Sensitiv 50 WG 50 Waschgang Flasche,50 Waschgang Flasche,1,stück,https://shop.Billa.at/produkte/silan-sensitiv-50-wg-00723361
6792,00-723363,Silan Aromatherapie Magnolie 46 WG 46 Waschgang Flasche,46 Waschgang Flasche,1,stück,https://shop.Billa.at/produkte/silan-aromatherapie-magnolie-46-wg-00723363
6793,00-723365,Silan Aromatherapie Rose 46 WG 46 Waschgang Flasche,46 Waschgang Flasche,1,stück,https://shop.Billa.at/produkte/silan-aromatherapie-rose-46-wg-00723365
6794,00-723366,Silan Aromatherapie Malediven 46 WG 46 Waschgang Flasche,46 Waschgang Flasche,1,stück,https://shop.Billa.at/produkte/silan-aromatherapie-malediven-46-wg-00723366
6795,00-723368,Silan Aromatherapie Frangipani 46 WG 46 Waschgang Flasche,46 Waschgang Flasche,1,stück,https://shop.Billa.at/produkte/silan-aromatherapie-frangipani-46-wg-00723368
6796,00-723367,Silan Aromatherapie Dschungel 46 WG 46 Waschgang Flasche,46 Waschgang Flasche,1,stück,https://shop.Billa.at/produkte/silan-aromatherapie-dschungel-46-wg-00723367
6797,00-723372,Silan Sensitiv Derma Care 46 Waschgang Flasche,46 Waschgang Flasche,1,stück,https://shop.Billa.at/produkte/silan-sensitiv-derma-care-00723372
6798,00-723379,Silan Aromatherapie Lotus 46 WG 46 Waschgang Flasche,46 Waschgang Flasche,1,stück,https://shop.Billa.at/produkte/silan-aromatherapie-lotus-46-wg-00723379
6799,00-723369,Silan Fresh Control Cool Fresh 46 WG 46 Waschgang Flasche,46 Waschgang Flasche,1,stück,https://shop.Billa.at/produkte/silan-fresh-control-cool-fresh-46-wg-00723369
6800,00-723371,Silan Naturals Ylang- Ylang & Süßgras 46 Waschgang Flasche,46 Waschgang Flasche,1,stück,https://shop.Billa.at/produkte/silan-naturals-ylang-ylang-und-suessgras-00723371
7253,00-733441,Cleanly Waschstreifen Universal und Color 32 Waschgang Packung,32 Waschgang Packung,1,stück,https://shop.Billa.at/produkte/cleanly-waschstreifen-universal-und-color-00733441
7478,00-738463,Fewa Waschmittel Wolle 55 Waschgang Flasche,55 Waschgang Flasche,1,stück,https://shop.Billa.at/produkte/fewa-waschmittel-wolle-00738463
7486,00-739237,Somat XXl Pulver 125 Waschgang Packung,125 Waschgang Packung,1,stück,https://shop.Billa.at/produkte/somat-xxl-pulver-00739237
7527,00-740480,Fewa Waschmittel Renew Black 55 Waschgang Flasche,55 Waschgang Flasche,1,stück,https://shop.Billa.at/produkte/fewa-waschmittel-renew-black-00740480
7535,00-740605,Omo Flüssig Aktiv 40 Waschgang Flasche,40 Waschgang Flasche,1,stück,https://shop.Billa.at/produkte/omo-fluessig-aktiv-00740605
7546,00-741246,Omo Flüssig Color 40 Waschgang Flasche,40 Waschgang Flasche,1,stück,https://shop.Billa.at/produkte/omo-fluessig-color-00741246
8595,00-768547,Ariel Waschmittel Flüssig Universal 25 Waschgang Flasche,25 Waschgang Flasche,1,stück,https://shop.Billa.at/produkte/ariel-waschmittel-fluessig-universal-00768547
8597,00-768550,Ariel Waschmittel Flüssig Color 25 Waschgang Flasche,25 Waschgang Flasche,1,stück,https://shop.Billa.at/produkte/ariel-waschmittel-fluessig-color-00768550
8598,00-768559,Ariel Waschmittel Flüssig Febreze 25 Waschgang Flasche,25 Waschgang Flasche,1,stück,https://shop.Billa.at/produkte/ariel-waschmittel-fluessig-febreze-00768559
8599,00-768567,Ariel Color Waschmittel Pulver 23 Waschgang Packung,23 Waschgang Packung,1,stück,https://shop.Billa.at/produkte/ariel-color-waschmittel-pulver-00768567
8601,00-768606,Lenor Weichspüler Sensitiv 42 Waschgang Flasche,42 Waschgang Flasche,1,stück,https://shop.Billa.at/produkte/lenor-weichspueler-sensitiv-00768606
8602,00-768590,Lenor Weichspüler Aprilfrisch 42 Waschgang Flasche,42 Waschgang Flasche,1,stück,https://shop.Billa.at/produkte/lenor-weichspueler-aprilfrisch-00768590
8605,00-768656,Lenor Weichspüler Goldene Orchidee 42 Waschgang Flasche,42 Waschgang Flasche,1,stück,https://shop.Billa.at/produkte/lenor-weichspueler-goldene-orchidee-00768656
8640,00-768565,Ariel Universal Waschmittel Pulver 23 Waschgang Packung,23 Waschgang Packung,1,stück,https://shop.Billa.at/produkte/ariel-universal-waschmittel-pulver-00768565
9079,00-771098,Ariel All in One Color Waschmittelpods 19 Waschgang Karton,19 Waschgang Karton,1,stück,https://shop.Billa.at/produkte/ariel-all-in-one-color-waschmittelpods-00771098
9082,00-771109,Lenor Universal Waschmittelpods Aprilfrisch 19 Waschgang Karton,19 Waschgang Karton,1,stück,https://shop.Billa.at/produkte/lenor-universal-waschmittelpods-aprilfrisch-00771109
9083,00-771113,Lenor Color Waschmittelpods Blütentraum 19 Waschgang Karton,19 Waschgang Karton,1,stück,https://shop.Billa.at/produkte/lenor-color-waschmittelpods-bluetentraum-00771113
9102,00-770885,Ariel All in One Waschmittelpods 19 Waschgang Flasche,19 Waschgang Flasche,1,stück,https://shop.Billa.at/produkte/ariel-all-in-one-waschmittelpods-00770885
9103,00-770912,Ariel Waschmittel Frische Baumwollblüte Flüssig 25 Waschgang Flasche,25 Waschgang Flasche,1,stück,https://shop.Billa.at/produkte/ariel-waschmittel-frische-baumwollbluete-fluessig-00770912
9131,00-771634,Lenor Universal Waschmittelpods Orangeblüte & Pfirsich 19 Waschgang Karton,19 Waschgang Karton,1,stück,https://shop.Billa.at/produkte/lenor-universal-waschmittelpods-orangebluete-und-pfirsich-00771634
9238,00-773719,Lenor Waschmittel Flüssig Blütentraum 25 Waschgang Flasche,25 Waschgang Flasche,1,stück,https://shop.Billa.at/produkte/lenor-waschmittel-fluessig-bluetentraum-00773719
9239,00-773721,Lenor Sensitiv Waschmittel Flüssig 25 Waschgang Flasche,25 Waschgang Flasche,1,stück,https://shop.Billa.at/produkte/lenor-sensitiv-waschmittel-fluessig-00773721
9257,00-773221,Clever Waschmittel Universal Pulver 85 Waschgang Karton,85 Waschgang Karton,1,stück,https://shop.Billa.at/produkte/clever-waschmittel-universal-pulver-00773221
9498,00-772746,Frosch Waschmittel Universal 22 Waschgang Beutel,22 Waschgang Beutel,1,stück,https://shop.Billa.at/produkte/frosch-waschmittel-universal-00772746
10499,00-867796,Clever Spezialwaschmittel Flüssig Black 41 Waschgang Flasche,41 Waschgang Flasche,1,stück,https://shop.Billa.at/produkte/clever-spezialwaschmittel-fluessig-black-00867796
10502,00-867795,Clever Spezialwaschmittel Flüssig Seide & Wolle 41 Waschgang Flasche,41 Waschgang Flasche,1,stück,https://shop.Billa.at/produkte/clever-spezialwaschmittel-fluessig-seide-und-wolle-00867795
10509,00-867784,Clever Spezialwaschmittel Flüssig Color 41 Waschgang Flasche,41 Waschgang Flasche,1,stück,https://shop.Billa.at/produkte/clever-spezialwaschmittel-fluessig-color-00867784
10537,00-867752,Clever Vollwaschmittel Flüssig 40 Waschgang Flasche,40 Waschgang Flasche,1,stück,https://shop.Billa.at/produkte/clever-vollwaschmittel-fluessig-00867752
10538,00-867759,Clever Colorwaschmittel Flüssig 40 Waschgang Flasche,40 Waschgang Flasche,1,stück,https://shop.Billa.at/produkte/clever-colorwaschmittel-fluessig-00867759
10649,00-870278,BI HOME Waschmittel Flüssig Color 30 Waschgang Flasche,30 Waschgang Flasche,1,stück,https://shop.Billa.at/produkte/bi-home-waschmittel-fluessig-color-00870278
10652,00-870298,BI HOME Waschmittel Flüssig Sensitiv 30 Waschgang Flasche,30 Waschgang Flasche,1,stück,https://shop.Billa.at/produkte/bi-home-waschmittel-fluessig-sensitiv-00870298
10653,00-870299,BI HOME Vollwaschmittel Flüssig Universal 30 Waschgang Flasche,30 Waschgang Flasche,1,stück,https://shop.Billa.at/produkte/bi-home-vollwaschmittel-fluessig-universal-00870299
10720,00-871697,Lenor Weichspüler Frisches Erwachen 42 Waschgang Flasche,42 Waschgang Flasche,1,stück,https://shop.Billa.at/produkte/lenor-weichspueler-frisches-erwachen-00871697
11614,00-900024,Frosch Baumwollblüte Weichspüler 30 Waschgang Flasche,30 Waschgang Flasche,1,stück,https://shop.Billa.at/produkte/frosch-baumwollbluete-weichspueler-00900024
11935,00-930289,Omo Active Pulver 35 Waschgang Stück,35 Waschgang Stück,1,stück,https://shop.Billa.at/produkte/omo-active-pulver-00930289
12015,00-936953,Ariel All in One Color Waschmitttelpods 30 Waschgang Karton,30 Waschgang Karton,1,stück,https://shop.Billa.at/produkte/ariel-all-in-one-color-waschmitttelpods-00936953
12016,00-936952,Ariel All in One Universal Waschmittelpods 30 Waschgang Karton,30 Waschgang Karton,1,stück,https://shop.Billa.at/produkte/ariel-all-in-one-universal-waschmittelpods-00936952
12023,00-938340,Weißer Riese Color Gel 50 Waschgang Flasche,50 Waschgang Flasche,1,stück,https://shop.Billa.at/produkte/weisser-riese-color-gel-00938340
12027,00-938360,Weißer Riese Universal Gel 50 Waschgang Flasche,50 Waschgang Flasche,1,stück,https://shop.Billa.at/produkte/weisser-riese-universal-gel-00938360
12162,00-962788,Dixan Extra Frische Gel 30 Waschgang Flasche,30 Waschgang Flasche,1,stück,https://shop.Billa.at/produkte/dixan-extra-frische-gel-00962788

In [63]:
# JO PREIS price structure
jo_mask = df['promotion_description'].fillna('').astype(str).str.contains(
    r'JO PREIS',
    case=False,
    na=False
)

issues = df.loc[
    jo_mask & (
        df['regular_price'].isna() |
        df['selling_price'].isna() |
        df['price_per_unit'].isna()
    ),
    [
        'pdp_url',
        'promotion_description',
        'regular_price',
        'selling_price',
        'price_per_unit'
    ]
].copy()

issues['row_no'] = issues.index + 2

issues = issues[
    ['row_no', 'pdp_url', 'promotion_description',
     'regular_price', 'selling_price', 'price_per_unit']
]

print(f"JO PREIS issues: {len(issues)}")
print(issues.to_string(index=False))

JO PREIS issues: 0
Empty DataFrame
Columns: [row_no, pdp_url, promotion_description, regular_price, selling_price, price_per_unit]
Index: []

In [64]:
text_cols = df.select_dtypes(include="object").columns

leading_trailing = {}

for col in text_cols:
    mask = (
        df[col].fillna("").astype(str)
        != df[col].fillna("").astype(str).str.strip()
    )
    if mask.any():
        leading_trailing[col] = df.loc[mask, col]

print(leading_trailing.keys())

dict_keys(['organictype'])

In [65]:
multiple_spaces = {}

for col in text_cols:
    mask = df[col].fillna("").str.contains(r"\s{2,}", regex=True)
    if mask.any():
        multiple_spaces[col] = df.loc[mask, col]

print(multiple_spaces.keys())

dict_keys([])

In [66]:
special_space = {}

for col in text_cols:
    mask = df[col].fillna("").str.contains(r"[\t\r\n]", regex=True)
    if mask.any():
        special_space[col] = df.loc[mask, col]

print(special_space.keys())

dict_keys([])

In [67]:
special_space

{}

In [6]:
issues = []

for col in text_cols:
    mask = (
        (df[col].fillna("") != df[col].fillna("").str.strip()) |
        df[col].fillna("").str.contains(r"\s{2,}", regex=True) |
        df[col].fillna("").str.contains(r"[\t\r\n]", regex=True) |
        df[col].fillna("").str.contains("\u00A0", regex=False)
    )

    if mask.any():
        tmp = df.loc[mask, ["unique_id", col]].copy()
        tmp["column"] = col
        issues.append(tmp)

issues = pd.concat(issues, ignore_index=True)

issues.head()

NameError: name 'text_cols' is not defined

In [49]:
import pandas as pd

# Convert to datetime for proper date comparison
price_date = pd.to_datetime(df["price_valid_from"], errors="coerce")
promo_date = pd.to_datetime(df["promotion_valid_from"], errors="coerce")

# Find rows where both have values but are different
mask = (
    price_date.notna()
    & promo_date.notna()
    & (price_date != promo_date)
)

issues = df.loc[
    mask,
    ["unique_id", "pdp_url", "price_valid_from", "promotion_valid_from"]
].copy()

issues["row_no"] = issues.index + 2

issues = issues[
    ["row_no", "unique_id", "pdp_url",
     "price_valid_from", "promotion_valid_from"]
]

print(issues.to_string(index=False))
print(f"\nTotal issues: {len(issues)}")

Empty DataFrame
Columns: [row_no, unique_id, pdp_url, price_valid_from, promotion_valid_from]
Index: []

Total issues: 0

/tmp/ipykernel_24657/158468668.py:4: UserWarning: Parsing dates in %d.%m.%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  price_date = pd.to_datetime(df["price_valid_from"], errors="coerce")
/tmp/ipykernel_24657/158468668.py:5: UserWarning: Parsing dates in %d.%m.%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  promo_date = pd.to_datetime(df["promotion_valid_from"], errors="coerce")

In [8]:
import pandas as pd

# Convert price columns to numeric
cols = ["regular_price", "selling_price", "promotion_price", "price_per_unit"]
df[cols] = df[cols].apply(pd.to_numeric, errors="coerce")

invalid = df[
    # Mehrweg product
    (
        df["product_name"].fillna("").str.contains("Mehrweg", case=False) |
        df["breadcrumb"].fillna("").str.contains("Mehrweg", case=False)
    )
    &
    # Has AKTION promotion
    df["promotion_description"].fillna("").str.contains("AKTION", case=False)
    &
    # Rule violation
    (
        df["regular_price"].notna() |
        (df["selling_price"] != df["price_per_unit"]) |
        (df["promotion_price"] != df["price_per_unit"])
    )
]

print("Invalid rows:", len(invalid))

invalid[
    [
        "unique_id",
        "product_name",
        "regular_price",
        "selling_price",
        "promotion_price",
        "price_per_unit",
        "promotion_description",
        "pdp_url",
    ]
]

Invalid rows: 0

Empty DataFrame
Columns: [unique_id, product_name, regular_price, selling_price, promotion_price, price_per_unit, promotion_description, pdp_url]
Index: []

In [9]:
import pandas as pd

# 1. Identify which IDs are duplicated
duplicate_ids = df[df.duplicated(subset=['unique_id'], keep=False)]

# 2. Count occurrences of each duplicate ID
duplicate_counts = df['unique_id'].value_counts()
duplicate_counts = duplicate_counts[duplicate_counts > 1]

In [10]:
duplicate_ids

Empty DataFrame
Columns: [unique_id, competitor_name, extraction_date, product_name, grammage_quantity, grammage_unit, regular_price, selling_price, price_valid_from, price_per_unit, percentage_discount, promotion_price, promotion_valid_from, promotion_valid_upto, promotion_description, currency, breadcrumb, pdp_url, region, pack_size, site_shown_uom]
Index: []

In [11]:
df[df.regular_price.isna()]

,unique_id,competitor_name,extraction_date,product_name,grammage_quantity,grammage_unit,regular_price,selling_price,price_valid_from,price_per_unit,percentage_discount,promotion_price,promotion_valid_from,promotion_valid_upto,promotion_description,currency,breadcrumb,pdp_url,region,pack_size,site_shown_uom
322,00-21841,billa,2026-08-14,Gösser Märzen 500 ml,500,ml,NaN,1.06,NaN,NaN,NaN,1.06,NaN,NaN,AKTION,EUR,Alle Kategorien > Getränke > Bier > Flaschenbier,https://shop.billa.at/produkte/goesser-maerzen-0021841,NaN,NaN,500 ml
331,00-21982,billa,2026-08-14,Stiegl Goldbräu 500 ml,500,ml,NaN,0.99,NaN,NaN,NaN,0.99,NaN,NaN,AKTION,EUR,Alle Kategorien > Getränke > Bier > Flaschenbier,https://shop.billa.at/produkte/stiegl-goldbraeu-0021982,NaN,NaN,500 ml
1046,00-30036,billa,2026-08-14,Gösser Märzen 6er 500 ml,500,ml,NaN,1.06,NaN,NaN,NaN,1.06,NaN,NaN,AKTION,EUR,Alle Kategorien > Getränke > Bier > Flaschenbier,https://shop.billa.at/produkte/goesser-maerzen-6er-0030036,NaN,NaN,500 ml
1281,00-317777,billa,2026-08-14,Alnatura Tomatensauce Basilikum 350 g Glas,350,g,NaN,1.49,NaN,NaN,NaN,1.49,NaN,NaN,AKTION,EUR,"Alle Kategorien > Vorratsschrank > Tomatenprodukte, Sugo & Pesto > Sugo",https://shop.billa.at/produkte/alnatura-tomatensauce-basilikum-00317777,NaN,NaN,350 g Glas
1803,00-377843,billa,2026-08-14,Stiegl Hell 500 ml,500,ml,NaN,0.99,NaN,NaN,NaN,0.99,NaN,NaN,AKTION,EUR,Alle Kategorien > Getränke > Bier > Flaschenbier,https://shop.billa.at/produkte/stiegl-hell-00377843,NaN,NaN,500 ml
1908,00-381753,billa,2026-08-14,Lindt Lindor Kugeln Dark 500 g Packung,500,g,NaN,9.99,NaN,NaN,NaN,9.99,NaN,NaN,AKTION,EUR,Alle Kategorien > Vorratsschrank > Süßes & Salziges > Süßes > Süße Spezialitäten,https://shop.billa.at/produkte/lindt-lindor-kugeln-dark-00381753,NaN,NaN,500 g Packung
2525,00-411889,billa,2026-08-14,Stiegl Goldbräu 6er 500 ml,500,ml,NaN,0.99,NaN,NaN,NaN,0.99,NaN,NaN,AKTION,EUR,Alle Kategorien > Getränke > Bier > Flaschenbier,https://shop.billa.at/produkte/stiegl-goldbraeu-6er-00411889,NaN,NaN,500 ml
4167,00-504120,billa,2026-08-14,"Stiegl Paracelsus Bio Zwickl 6x0,5l 500 ml",500,ml,NaN,1.19,NaN,NaN,NaN,1.19,NaN,NaN,AKTION,EUR,Alle Kategorien > Getränke > Bier > Flaschenbier,https://shop.billa.at/produkte/stiegl-paracelsus-bio-zwickl-6x05l-00504120,NaN,NaN,500 ml
4715,00-573700,billa,2026-08-14,BILLA Apfelsaft 1 Liter,1,l,NaN,1.59,NaN,NaN,NaN,1.59,NaN,NaN,AKTION,EUR,Alle Kategorien > Getränke > Alkoholfreie Getränke > Frucht- & Gemüsesäfte,https://shop.billa.at/produkte/billa-apfelsaft-00573700,NaN,NaN,1 Liter
5729,00-678591,billa,2026-08-14,Alnatura Tomate Kräutersauce 350 g Glas,350,g,NaN,1.49,NaN,NaN,NaN,1.49,NaN,NaN,AKTION,EUR,Alle Kategorien > Rein Pflanzlich > Vorratsschrank > Tomatenprodukte & Pesto,https://shop.billa.at/produkte/alnatura-tomate-kraeutersauce-00678591,NaN,NaN,350 g Glas
5775,00-685017,billa,2026-08-14,"Stiegl Weisse 6x0,5l 500 ml",500,ml,NaN,1.19,NaN,NaN,NaN,1.19,NaN,NaN,AKTION,EUR,Alle Kategorien > Getränke > Bier > Flaschenbier,https://shop.billa.at/produkte/stiegl-weisse-6x05l-00685017,NaN,NaN,500 ml
6289,00-716803,billa,2026-08-14,BILLA Eistee Erdbeer-Melone 20 Teebeutel Schachtel,20,btl,NaN,0.50,NaN,NaN,NaN,0.50,NaN,NaN,AKTION,EUR,Alle Kategorien > Getränke > Alkoholfreie Getränke > Eistee,https://shop.billa.at/produkte/billa-eistee-erdbeermelone-00716803,NaN,NaN,20 Teebeutel Schachtel
6406,00-719242,billa,2026-08-14,BILLA Traubensaft 1 Liter,1,l,NaN,1.59,NaN,NaN,NaN,1.59,NaN,NaN,AKTION,EUR,Alle Kategorien > Getränke > Alkoholfreie Getränke > Frucht- & Gemüsesäfte,https://shop.billa.at/produkte/billa-traubensaft-00719242,NaN,NaN,1 Liter
7020,00-731768,billa,2026-08-14,Pfanner Orangennektar 60% 1 Liter,1,l,NaN,1.99,NaN,NaN,NaN,1.99,NaN,NaN,AKTION,EUR,Alle Kategorien > Getränke > Alkoholfreie Getränke > Frucht- & Gemüsesäfte,https://shop.billa.at/produkte/pfanner-orangennektar-60-00731768,NaN,NaN,1 Liter
7454,00-742626,billa,2026-08-14,Manner Eiswaffeln 75 g Packung,75,g,NaN,0.89,NaN,NaN,NaN,0.89,NaN,NaN,AKTION,EUR,Alle Kategorien > Vorratsschrank > Süßes & Salziges > Schnitten & Waffeln > Waffeln,https://shop.billa.at/produkte/manner-eiswaffeln-00742626,NaN,NaN,75 g Packung
8076,00-757326,billa,2026-08-14,Lindt Lindor Kugeln Lieblingsmix 500 g Stück,500,g,NaN,9.99,NaN,NaN,NaN,9.99,NaN,NaN,AKTION,EUR,Alle Kategorien > Vorratsschrank > Süßes & Salziges > Süßes > Süße Spezialitäten,https://shop.billa.at/produkte/lindt-lindor-kugeln-lieblingsmix-00757326,NaN,NaN,500 g Stück
9101,00-774161,billa,2026-08-14,"Stiegl Alkoholfrei 6x0,5l 500 ml",500,ml,NaN,1.19,NaN,NaN,NaN,1.19,NaN,NaN,AKTION,EUR,Alle Kategorien > Getränke > Bier > Alkoholfreies Bier,https://shop.billa.at/produkte/stiegl-alkoholfrei-6x05l-00774161,NaN,NaN,500 ml
9977,00-852604,billa,2026-08-14,Nivea Visage Augencreme Anti Falten mit Q10 15 ml Tube,15,ml,NaN,16.49,NaN,NaN,NaN,16.49,NaN,NaN,AKTION,EUR,Alle Kategorien > Drogerie & Kosmetik > Körperpflege & Reinigung > Gesichts- & Lippenpflege > Gesichtspflege und Reinigung,https://shop.billa.at/produkte/nivea-visage-augencreme-anti-falten-mit-q10-00852604,NaN,NaN,15 ml Tube
10215,00-867403,billa,2026-08-14,Pfanner Fifty-Fifty Mehrfruchtsaft 1 Liter,1,l,NaN,1.99,NaN,NaN,NaN,1.99,NaN,NaN,AKTION,EUR,Alle Kategorien > Getränke > Alkoholfreie Getränke > Frucht- & Gemüsesäfte,https://shop.billa.at/produkte/pfanner-fiftyfifty-mehrfruchtsaft-00867403,NaN,NaN,1 Liter
10431,00-871627,billa,2026-08-14,Lindt Lindor Kugeln Tiramisu 500 g Karton,500,g,NaN,9.99,NaN,NaN,NaN,9.99,NaN,NaN,AKTION,EUR,Alle Kategorien > Vorratsschrank > Süßes & Salziges > Süßes > Süße Spezialitäten,https://shop.billa.at/produkte/lindt-lindor-kugeln-tiramisu-00871627,NaN,NaN,500 g Karton
11321,00-898387,billa,2026-08-14,HOLY Iced Tea 3er Box Ananas 21 g Karton,21,g,NaN,3.49,NaN,NaN,NaN,3.49,NaN,NaN,AKTION,EUR,Alle Kategorien > Getränke > Alkoholfreie Getränke > Eistee,https://shop.billa.at/produkte/holy-iced-tea-3er-box-ananas-00898387,NaN,NaN,21 g Karton
11322,00-897896,billa,2026-08-14,Gösser Soda Zitron Radler 500 ml,500,ml,NaN,0.99,NaN,NaN,NaN,0.99,NaN,NaN,AKTION,EUR,Alle Kategorien > Getränke > Radler & Cider > Radler,https://shop.billa.at/produkte/goesser-soda-zitron-radler-00897896,NaN,NaN,500 ml
11333,00-898388,billa,2026-08-14,HOLY Iced Tea 3er Box Sternfrucht 21 g Karton,21,g,NaN,3.49,NaN,NaN,NaN,3.49,NaN,NaN,AKTION,EUR,Alle Kategorien > Getränke > Alkoholfreie Getränke > Eistee,https://shop.billa.at/produkte/holy-iced-tea-3er-box-sternfrucht-00898388,NaN,NaN,21 g Karton
11424,00-904695,billa,2026-08-14,Nivea Vital Teint Optimal Nachtpflege Soja 50 ml Tiegel,50,ml,NaN,19.49,NaN,NaN,NaN,19.49,NaN,NaN,AKTION,EUR,Alle Kategorien > Drogerie & Kosmetik > Körperpflege & Reinigung > Gesichts- & Lippenpflege > Gesichtspflege und Reinigung,https://shop.billa.at/produkte/nivea-vital-teint-optimal-nachtpflege-soja-00904695,NaN,NaN,50 ml Tiegel
11426,00-904698,billa,2026-08-14,Nivea Vital Teint Optimal Tagespflege Soja 50 ml Tiegel,50,ml,NaN,18.99,NaN,NaN,NaN,18.99,NaN,NaN,AKTION,EUR,Alle Kategorien > Drogerie & Kosmetik > Körperpflege & Reinigung > Gesichts- & Lippenpflege > Gesichtspflege und Reinigung,https://shop.billa.at/produkte/nivea-vital-teint-optimal-tagespflege-soja-00904698,NaN,NaN,50 ml Tiegel

In [12]:
df.grammage_unit.value_counts()

grammage_unit
g        7252
l        2079
ml       1179
stück    1158
kg        410
btl       220
wg          4
Name: count, dtype: int64

In [13]:
df.store_addressline1.value_counts()

AttributeError: 'DataFrame' object has no attribute 'store_addressline1'

In [14]:
duplicates = df[
    df.duplicated(subset=["store_addressline1", "unique_id"], keep=False)
].sort_values(["store_addressline1", "unique_id"])

print("Duplicate unique_id within stores:", len(duplicates))

display(duplicates[["store_addressline1", "unique_id"]])

KeyError: Index(['store_addressline1'], dtype='object')

In [15]:
df.dtypes

unique_id                 object
competitor_name           object
extraction_date           object
product_name              object
grammage_quantity         object
grammage_unit             object
regular_price            float64
selling_price            float64
price_valid_from         float64
price_per_unit           float64
percentage_discount      float64
promotion_price          float64
promotion_valid_from     float64
promotion_valid_upto     float64
promotion_description     object
currency                  object
breadcrumb                object
pdp_url                   object
region                   float64
pack_size                float64
site_shown_uom            object
dtype: object

In [16]:
issues = df[
    df["grammage_quantity"].astype(str).str.count(r"\d+\s*x") > 1
][["grammage_quantity", "pdp_url"]].reset_index(names="row_no")

issues

Empty DataFrame
Columns: [row_no, grammage_quantity, pdp_url]
Index: []

In [17]:
wine = df[
    df["producthierarchy_level1"].astype(str).str.contains("wein|wine", case=False, na=False)
]

issues = wine[
    wine["site_shown_uom"].astype(str).str.contains(r"\b[2-9]\d*\s*x\b", regex=True, na=False)
][["site_shown_uom", "regular_price", "selling_price", "pdp_url"]]

issues.reset_index(names="row_no")

KeyError: 'producthierarchy_level1'

In [48]:
import pandas as pd

issues = []

for idx, row in df.iterrows():

    rp = str(row.get("regular_price", "")).strip()
    sp = str(row.get("selling_price", "")).strip()
    pp = str(row.get("promotion_price", "")).strip()
    pdesc = str(row.get("promotion_description", "")).strip()

    # Ignore NaN represented as string
    if rp.lower() == "nan": rp = ""
    if sp.lower() == "nan": sp = ""
    if pp.lower() == "nan": pp = ""
    if pdesc.lower() == "nan": pdesc = ""

    remarks = []

    # Rule 1: Regular price contains comma
    if "," in rp:
        remarks.append("Regular price contains comma (,) instead of dot (.)")

    # Rule 2: Regular price missing
    if rp == "" and sp != "":
        remarks.append("Regular price missing (should be assigned from selling price)")

    # Rule 3: Promotion description missing but prices exist
    if pdesc == "" and rp != "" and sp != "":
        if pp != sp:
            remarks.append("Promotion description missing - promotion_price should equal selling_price")

    # Rule 4: Aktion products with all prices (reference only)
    if "aktion" in pdesc.lower():
        if rp == "":
            remarks.append("Aktion product with missing regular price (requires previous iteration data)")
        elif pp == "":
            remarks.append("Aktion product missing promotion_price")

    if remarks:
        issues.append({
            "row_no": idx + 1,
            "profile_url": row.get("profile_url", ""),
            "regular_price": rp,
            "selling_price": sp,
            "promotion_price": pp,
            "promotion_description": pdesc,
            "issue": " | ".join(remarks)
        })

issues_df = pd.DataFrame(issues)

print(f"Total issues found: {len(issues_df)}")
display(issues_df)

Total issues found: 3272

      row_no profile_url regular_price selling_price promotion_price  \
0          1                      2.79          2.79
1          2                      2.79          2.79
2          3                      1.95          1.95
3          4                      1.75          1.75
4          5                      2.99          2.99
5          7                      3.79          3.79
6          8                      3.99          3.99
7          9                      3.89          3.89
8         10                      2.49          2.49
9         11                      2.49          2.49
10        12                      3.99          3.99
11        13                      3.65          3.65
12        14                      3.95          3.95
13        15                      2.69          2.69
14        16                      2.69          2.69
15        17                      2.69          2.69
16        18                      1.29          1.29
17        20                      3.69          3.69
18        21                      1.99          1.99
19        22                      0.59          0.59
20        23                      2.49          2.49
21        24                     11.69         11.69
22        25                      0.95          0.95
23        26                      1.69          1.69
24        27                      4.49          4.49
25        28                      4.79          4.79
26        29                      1.99          1.99
27        30                      3.99          3.99
28        32                      2.75          2.75
29        33                      9.99          9.99
30        34                      0.69          0.69
31        35                     14.99         14.99
32        36                      7.65          7.65
33        37                      3.99          3.99
34        38                      5.69          5.69
35        39                      3.69          3.69
36        40                      1.99          1.99
37        41                      1.99          1.99
38        42                      2.29          2.29
39        43                      1.77          1.77
40        44                      8.99          8.99
41        45                      4.49          4.49
42        46                      1.95          1.95
43        47                      2.99          2.99
44        48                     11.99         11.99
45        49                      4.99          4.99
46        50                      4.99          4.99
47        51                      2.25          2.25
48        52                      5.99          5.99
49        53                      1.19          1.19
50        54                      4.89          4.89
51        55                      3.29          3.29
52        56                      5.99          5.99
53        57                      1.99          1.99
54        58                      3.49          3.49
55        59                      3.49          3.49
56        60                      8.99          8.99
57        61                      3.49          3.49
58        62                      2.85          2.85
59        63                      4.99          4.99
60        64                      0.99          0.99
61        65                      1.49          1.49
62        66                      4.89          4.89
63        67                      4.89          4.89
64        68                      1.29          1.29
65        69                      3.49          3.49
66        70                      3.49          3.49
67        71                      5.99          5.99
68        72                      2.69          2.69
69        73                      0.52          0.52
70        74                      1.89          1.89
71        75                      1.39          1.39
72        76                      1.49          1.49
73        77                      0.69          0.69
74        78                      1.99          1.99
75        79                      4.79          4.79
76        81                      1.49          1.49
77        82                      9.49          9.49
78        83                      1.49          1.49
79        84                      0.49          0.49
80        85                      5.28          5.28
81        86                      1.49          1.49
82        87                      4.49          4.49
83        88                      1.29          1.29
84        89                      1.95          1.95
85        90                      0.59          0.59
86        91                      3.29          3.29
87        93                      0.99          0.99
88        94                      3.99          3.99
89        95                      4.99          4.99
90        96                      3.49          3.49
91        97                      1.49          1.49
92        98                      0.59          0.59
93        99                      0.79          0.79
94       100                      3.65          3.65
95       101                      2.99          2.99
96       102                      3.39          3.39
97       103                      2.59          2.59
98       104                      1.99          1.99
99       105                      1.99          1.99
100      106                      2.49          2.49
101      107                      1.79          1.79
102      108                      4.99          4.99
103      109                      3.29          3.29
104      110                      3.49          3.49
105      111                      1.99          1.99
106      112                      1.99          1.99
107      113                     10.71         10.71
108      114                      4.99          4.99
109      115                      1.69          1.69
110      116                      0.69          0.69
111      117                      1.59          1.59
112      118                      2.19          2.19
113      119                      0.54          0.54
114      120                      0.44          0.44
115      121                      1.69          1.69
116      122                      0.69          0.69
117      123                      4.49          4.49
118      124                      1.85          1.85
119      125                      3.99          3.99
120      126                      5.95          5.95
121      127                      3.39          3.39
122      128                      6.55          6.55
123      129                      2.99          2.99
124      130                      2.99          2.99
125      131                      1.99          1.99
126      132                      4.99          4.99
127      133                      3.99          3.99
128      134                      5.99          5.99
129      135                      3.49          3.49
130      136                      2.95          2.95
131      137                      3.29          3.29
132      138                      3.99          3.99
133      139                      0.69          0.69
134      140                      5.69          5.69
135      141                      1.39          1.39
136      143                      2.99          2.99
137      144                      1.75          1.75
138      145                      1.99          1.99
139      146                      3.59          3.59
140      147                      2.99          2.99
141      148                      4.99          4.99
142      149                      3.39          3.39
143      150                      1.49          1.49
144      151                      2.49          2.49
145      152                      1.25          1.25
146      153                      1.25          1.25
147      154                      3.59          3.59
148      155                      5.99          5.99
149      157                      5.99          5.99
150      158                      4.99          4.99
151      159                      1.75          1.75
152      160                      2.98          2.98
153      161                      2.98          2.98
154      162                      2.95          2.95
155      163                      2.95          2.95
156      164                      2.99          2.99
157      165                      1.99          1.99
158      166                      1.29          1.29
159      167                      1.99          1.99
160      168                     24.99         24.99
161      169                     24.99         24.99
162      170                     24.99         24.99
163      171                      1.59          1.59
164      172                      2.95          2.95
165      173                      2.99          2.99
166      174                      1.75          1.75
167      175                     22.39         22.39
168      176                      2.19          2.19
169      177                      4.49          4.49
170      178                      5.29          5.29
171      179                     13.95         13.95
172      180                     16.69         16.69
173      181                      2.99          2.99
174      182                      2.49          2.49
175      183                      2.49          2.49
176      184                      2.79          2.79
177      185                      9.49          9.49
178      186                      9.59          9.59
179      187                      1.59          1.59
180      188                      0.99          0.99
181      191                       2.6           2.6
182      192                      2.99          2.99
183      193                      4.79          4.79
184      194                      1.59          1.59
185      195                      4.25          4.25
186      197                      1.85          1.85
187      198                      0.85          0.85
188      199                      3.95          3.95
189      200                      2.29          2.29
190      201                      2.99          2.99
191      202                      0.89          0.89
192      203                      3.29          3.29
193      204                      1.99          1.99
194      205                      2.49          2.49
195      206                      0.59          0.59
196      207                      1.89          1.89
197      208                      1.99          1.99
198      210                     14.89         14.89
199      211                     19.95         19.95
200      212                      0.79          0.79
201      213                      4.78          4.78
202      214                      4.95          4.95
203      215                      2.49          2.49
204      216                      5.95          5.95
205      217                      9.95          9.95
206      218                      1.59          1.59
207      219                      1.39          1.39
208      220                      2.89          2.89
209      221                      4.49          4.49
210      222                      2.95          2.95
211      223                      0.99          0.99
212      224                      2.95          2.95
213      225                      2.95          2.95
214      226                      4.85          4.85
215      227                      2.95          2.95
216      228                      1.59          1.59
217      229                      1.99          1.99
218      230                      5.69          5.69
219      231                      5.95          5.95
220      232                      2.95          2.95
221      233                      2.29          2.29
222      234                      1.99          1.99
223      235                      2.99          2.99
224      236                      1.69          1.69
225      237                      1.24          1.24
226      238                      0.99          0.99
227      239                      3.99          3.99
228      240                      2.99          2.99
229      241                      2.95          2.95
230      242                      2.99          2.99
231      243                      3.25          3.25
232      244                      2.95          2.95
233      245                      0.79          0.79
234      246                      1.29          1.29
235      247                      5.49          5.49
236      248                      7.49          7.49
237      249                      9.95          9.95
238      250                      1.99          1.99
239      251                      2.79          2.79
240      252                      2.25          2.25
241      253                      1.59          1.59
242      254                      1.95          1.95
243      255                      4.95          4.95
244      256                      2.59          2.59
245      257                      4.69          4.69
246      258                      3.99          3.99
247      259                      3.99          3.99
248      260                      3.99          3.99
249      261                      4.39          4.39
250      262                      8.39          8.39
251      263                      4.49          4.49
252      264                      4.95          4.95
253      265                      5.99          5.99
254      266                      3.99          3.99
255      267                      1.49          1.49
256      268                      2.49          2.49
257      269                      3.99          3.99
258      270                      1.25          1.25
259      271                      4.99          4.99
260      272                      1.69          1.69
261      273                      3.79          3.79
262      274                      2.79          2.79
263      275                      3.49          3.49
264      276                      2.99          2.99
265      277                      3.49          3.49
266      278                      4.99          4.99
267      280                      0.99          0.99
268      281                      1.69          1.69
269      282                      5.49          5.49
270      284                      4.95          4.95
271      285                      1.99          1.99
272      286                      3.29          3.29
273      287                      0.69          0.69
274      288                      1.79          1.79
275      289                      1.49          1.49
276      290                      1.99          1.99
277      291                      1.99          1.99
278      292                      3.99          3.99
279      293                      2.79          2.79
280      294                      3.39          3.39
281      295                      1.79          1.79
282      296                      3.29          3.29
283      297                      2.39          2.39
284      298                      1.99          1.99
285      299                      2.69          2.69
286      300                      2.39          2.39
287      301                      3.19          3.19
288      302                      3.39          3.39
289      303                      3.39          3.39
290      304                      4.49          4.49
291      305                      3.99          3.99
292      306                      1.49          1.49
293      307                      3.69          3.69
294      308                      2.89          2.89
295      309                      1.99          1.99
296      310                      9.99          9.99
297      311                      2.49          2.49
298      312                      2.49          2.49
299      313                      3.95          3.95
300      314                      3.19          3.19
301      315                      1.35          1.35
302      316                      3.99          3.99
303      317                      1.95          1.95
304      318                      5.49          5.49
305      319                      1.99          1.99
306      320                      2.69          2.69
307      321                      1.69          1.69
308      322                      0.89          0.89
309      323                      0.99          0.99
310      324                      0.69          0.69
311      325                      0.29          0.29
312      326                      0.79          0.79
313      327                      0.99          0.99
314      328                      3.49          3.49
315      329                      7.49          7.49
316      330                      1.25          1.25
317      331                      6.69          6.69
318      332                      3.99          3.99
319      333                      3.85          3.85
320      334                      0.99          0.99
321      335                      1.79          1.79
322      336                      1.09          1.09
323      338                     24.99         24.99
324      339                     24.99         24.99
325      340                     24.99         24.99
326      341                     24.99         24.99
327      342                     24.99         24.99
328      343                      3.75          3.75
329      344                     24.99         24.99
330      345                      1.25          1.25
331      346                      1.95          1.95
332      347                      4.99          4.99
333      348                      2.85          2.85
334      349                      3.29          3.29
335      350                      2.95          2.95
336      351                      1.95          1.95
337      352                      8.49          8.49
338      353                      1.65          1.65
339      354                      5.99          5.99
340      355                      1.65          1.65
341      356                      4.99          4.99
342      357                      7.29          7.29
343      358                      8.89          8.89
344      359                      3.29          3.29
345      360                      2.49          2.49
346      361                      2.99          2.99
347      362                      2.99          2.99
348      363                      3.79          3.79
349      364                      0.85          0.85
350      365                      3.99          3.99
351      366                      3.89          3.89
352      367                      1.49          1.49
353      368                      3.99          3.99
354      369                      2.69          2.69
355      370                      2.99          2.99
356      371                      2.49          2.49
357      372                      2.49          2.49
358      373                      3.65          3.65
359      374                      2.25          2.25
360      375                      4.59          4.59
361      376                      1.09          1.09
362      377                     10.99         10.99
363      378                      1.85          1.85
364      379                     10.99         10.99
365      380                      2.47          2.47
366      381                      2.25          2.25
367      382                      1.69          1.69
368      383                      0.85          0.85
369      384                      3.95          3.95
370      385                     14.99         14.99
371      386                      8.49          8.49
372      387                      1.69          1.69
373      389                      0.79          0.79
374      390                      5.99          5.99
375      391                      5.55          5.55

In [19]:
df.unique_id.duplicated().sum()

np.int64(0)

In [47]:
mask = (
    df['selling_price'].eq(df['regular_price']) &
    df['selling_price'].eq(df['promotion_price'])
)

issues = df.loc[mask, ['pdp_url', 'selling_price', 'regular_price', "promotion_description", 'promotion_price']].copy()
issues['row_no'] = issues.index + 2

issues[['row_no', 'pdp_url', 'selling_price', 'regular_price', "promotion_description", 'promotion_price']]

Empty DataFrame
Columns: [row_no, pdp_url, selling_price, regular_price, promotion_description, promotion_price]
Index: []

In [46]:
# Find Mehrweg products that are not yogurt
# and have missing price_per_unit

mehrweg_mask = (
    df['promotion_description']
    .fillna('')
    .astype(str)
    .str.contains('Mehrweg', case=False, na=False)
)

# Exclude yogurt products
not_yogurt_mask = ~df['product_name'].fillna('').astype(str).str.contains(
    'yogurt|joghurt|yoghurt',
    case=False,
    na=False
)

# price_per_unit is missing / empty
price_per_unit_missing = (
    df['price_per_unit'].isna() |
    df['price_per_unit'].astype(str).str.strip().eq('')
)

mask = mehrweg_mask & not_yogurt_mask & price_per_unit_missing

issues = df.loc[
    mask,
    ['pdp_url', 'product_name', 'promotion_description', 'price_per_unit']
].copy()

# Excel row number
issues['row_no'] = issues.index + 2

issues = issues[
    ['row_no', 'pdp_url', 'product_name',
     'promotion_description', 'price_per_unit']
]

print(f"Total Mehrweg issues: {len(issues)}")
print(issues.to_string(index=False))

Total Mehrweg issues: 0
Empty DataFrame
Columns: [row_no, pdp_url, product_name, promotion_description, price_per_unit]
Index: []

In [45]:
# Check if selling_price or promotion_price is greater than regular_price

regular_price = pd.to_numeric(df['regular_price'], errors='coerce')
selling_price = pd.to_numeric(df['selling_price'], errors='coerce')
promotion_price = pd.to_numeric(df['promotion_price'], errors='coerce')

mask = (
    regular_price.notna() &
    (
        (selling_price.notna() & (selling_price > regular_price)) |
        (promotion_price.notna() & (promotion_price > regular_price))
    )
)

issues = df.loc[
    mask,
    ['pdp_url', 'promotion_description',
     'regular_price', 'selling_price', 'promotion_price']
].copy()

# Excel row number
issues['row_no'] = issues.index + 2

issues = issues[
    ['row_no', 'pdp_url', 'promotion_description',
     'regular_price', 'selling_price', 'promotion_price']
]

print(f"Total issues: {len(issues)}")
print(issues.to_string(index=False))

Total issues: 0
Empty DataFrame
Columns: [row_no, pdp_url, promotion_description, regular_price, selling_price, promotion_price]
Index: []

In [44]:
mask = (
    df["regular_price"].notna() &
    df["price_was"].notna() &
    (pd.to_numeric(df["regular_price"], errors="coerce") ==
     pd.to_numeric(df["price_was"], errors="coerce"))
)

issues = df.loc[mask, ["pdp_url", "regular_price", "price_was"]].copy()
issues["row_no"] = issues.index + 2

issues = issues[["row_no", "pdp_url", "regular_price", "price_was"]]

issues

KeyError: 'price_was'

In [61]:
df.organictype.value_counts()

organictype
Non-Organic    15183
Organic         1630
Name: count, dtype: int64

In [60]:
for i, ch in enumerate(url):
    if ch == " ":
        print(i, "Normal space")
    elif ch == "\xa0":
        print(i, "NBSP")

NameError: name 'url' is not defined

In [26]:
issues = df[
    df["product_unique_key"].astype(str) != (df["unique_id"].astype(str) + "P")
][["unique_id", "product_unique_key", "pdp_url"]].reset_index(names="row_no")

issues

KeyError: 'product_unique_key'

In [27]:
invalid_urls = [u.replace(" ", "\xa0") for u in invalid_urls]

issues = df[df["pdp_url"].isin(invalid_urls)][
    ["unique_id", "pdp_url"]
].reset_index(names="row_no")

issues

NameError: name 'invalid_urls' is not defined

In [28]:
df[df['site_shown_uom'] == ""]

Empty DataFrame
Columns: [unique_id, competitor_name, extraction_date, product_name, grammage_quantity, grammage_unit, regular_price, selling_price, price_valid_from, price_per_unit, percentage_discount, promotion_price, promotion_valid_from, promotion_valid_upto, promotion_description, currency, breadcrumb, pdp_url, region, pack_size, site_shown_uom]
Index: []

In [29]:
df.dtypes

unique_id                 object
competitor_name           object
extraction_date           object
product_name              object
grammage_quantity         object
grammage_unit             object
regular_price            float64
selling_price            float64
price_valid_from         float64
price_per_unit           float64
percentage_discount      float64
promotion_price          float64
promotion_valid_from     float64
promotion_valid_upto     float64
promotion_description     object
currency                  object
breadcrumb                object
pdp_url                   object
region                   float64
pack_size                float64
site_shown_uom            object
dtype: object

In [30]:
df.grammage_quantity.value_counts()

grammage_quantity
1        1528
500       784
250       754
200       589
100       585
0.75      531
400       493
150       419
300       320
0.5       279
0.7       256
125       215
0.33      172
180       145
330       142
1 000     135
50        134
20        133
1.5       132
350       124
75        118
750       117
450       117
80        107
0.25      106
160       100
190        98
120        95
2          88
175        86
800        86
600        84
360        78
220        76
70         75
60         73
90         73
140        72
40         69
130        62
10         58
340        55
0.2        53
30         52
700        52
240        51
85         50
225        46
110        45
25         42
3          41
280        40
270        40
170        39
320        37
375        37
95         37
230        36
650        35
45         33
210        33
4          31
460        29
185        29
370        28
670        28
18         28
55         27
15         26
550        26
6          25
420        24
1 020      22
8          22
65         22
35         22
135        21
12         21
195        20
24         20
235        20
56         20
440        19
480        18
680        18
115        18
105        17
380        17
165        16
275        16
5          16
260        15
16         14
0.375      14
21         14
325        13
465        13
64         13
390        12
825        12
14         11
0.9        11
57         11
84         10
32         10
36         10
0.3        10
415        10
310        10
580         9
28          9
52          9
51          9
63          9
44          9
290         9
42          9
410         8
900         8
475         8
168         8
430         8
355         8
1.25        8
112         8
540         8
54          8
104         8
0.275       7
2 040       7
530         7
285         7
1 200       7
17          7
22          7
0.6         7
1.4         7
138         7
62          7
46          7
171         6
48          6
205         6
132         6
39          6
68          6
560         6
47          6
0.8         6
2.5         6
26          6
425         6
218.4       6
192         5
850         5
166         5
435         5
111         5
128         5
144         5
204         5
405         5
427         4
38          4
570         4
407         4
23          4
0.24        4
126         4
0.4         4
326         4
53          4
156         4
1 240       4
720         4
76          4
472         4
43          4
470         4
0.355       4
108         4
520         4
1.35        4
72          4
59          4
0.08        4
950         3
114         3
1 400       3
7.5         3
2.8         3
525         3
625         3
71          3
136         3
227         3
172         3
365         3
0.65        3
690         3
1 550       3
79          3
0.85        3
485         3
256         3
27          3
41          3
288         3
0.44        3
9           3
17.4        3
228         3
123         3
1.9         3
840         3
148         3
315         3
78          3
66          3
0.1         3
255         3
226         3
295         3
265         3
565         3
77          3
345         3
245         3
0.048       3
0.04        2
119         2
455         2
1 650       2
640         2
0.265       2
67.19       2
176         2
0.235       2
231         2
675         2
1.98        2
364         2
585         2
178         2
0.525       2
237         2
94          2
352         2
152         2
336         2
335         2
182         2
710         2
0.42        2
157         2
61          2
29          2
567         2
146         2
37          2
495         2
145         2
780         2
19          2
363         2
236         2
96          2
215         2
0.15        2
184         2
1.2         2
87          2
620         2
264         2
188         2
121         2
162         2
31          2
385         2
74          2
0.35        2
124         2
154         2
660         2
113         2
970         2
11          2
0.36        2
2 500       2
23.5        2
0.06        2
93          2
102         2
372         2
960         2
510         2
269         2
99          2
83          2
0.45        2
880         2
0.34        1
0.473       1
252         1
174         1
532         1
534         1
22.5        1
195.5       1
4.9         1
107         1
183.2       1
186.4       1
92          1
182.5       1
9.6         1
31.5        1
1 080       1
3.96        1
7           1
157.5       1
368         1
1 500       1
305         1
117         1
276         1
4.5         1
268         1
216         1
1 300       1
88          1
1 396       1
134         1
378         1
327         1
412.5       1
5.02        1
187         1
740         1
69          1
147         1
118         1
169         1
473         1
201         1
464         1
217         1
387         1
243         1
344         1
13          1
2.15        1
610         1
630         1
376         1
0.28        1
282         1
398         1
770         1
187.5       1
312         1
86          1
1 150       1
267         1
1 600       1
91          1
487         1
492         1
709         1
181         1
167         1
163         1
153         1
705         1
58          1
648         1
62.5        1
2.6         1
820         1
1.8         1
1 050       1
526         1
154.8       1
129         1
211.5       1
528         1
186         1
711         1
438         1
261         1
392         1
489         1
18.2        1
1 780       1
890         1
284         1
193         1
432         1
309         1
273         1
0.588       1
133         1
371         1
247         1
424         1
482         1
102.5       1
87.5        1
99.9        1
4.8         1
145.6       1
109         1
0.18        1
211         1
222         1
333         1
141.7       1
73          1
272         1
728         1
212         1
920         1
163.8       1
1.32        1
172.5       1
324         1
Name: count, dtype: int64

In [31]:
import pandas as pd
import re

issues = []

# Check all text/object columns
text_cols = df.select_dtypes(include="object").columns

for col in text_cols:
    s = df[col].fillna("").astype(str)

    # 1. Value ending with comma
    mask_comma = s.str.rstrip().str.endswith(",")

    if mask_comma.any():
        temp = df.loc[mask_comma, [col]].copy()
        temp["row_no"] = temp.index + 2
        temp["column"] = col
        temp["issue"] = "Value ends with comma (,)"
        temp["issue_value"] = temp[col]

        # Add PDP URL if available
        if "pdp_url" in df.columns:
            temp["URL"] = df.loc[mask_comma, "pdp_url"]

        issues.append(
            temp[["row_no", "URL", "column", "issue_value", "issue"]]
        )

    # 2. Leading/trailing whitespace
    mask_space = s.ne(s.str.strip()) & s.ne("")

    if mask_space.any():
        temp = df.loc[mask_space, [col]].copy()
        temp["row_no"] = temp.index + 2
        temp["column"] = col
        temp["issue"] = "Leading/trailing whitespace"
        temp["issue_value"] = temp[col]

        if "pdp_url" in df.columns:
            temp["URL"] = df.loc[mask_space, "pdp_url"]

        issues.append(
            temp[["row_no", "URL", "column", "issue_value", "issue"]]
        )

# Combine results
if issues:
    result = pd.concat(issues, ignore_index=True)

    print(result.to_string(index=False))
else:
    print("No issues found.")

No issues found.

In [32]:
price_cols = ['regular_price', 'selling_price']

for col in price_cols:
    # Convert to string and check exactly 2 decimal places
    mask = (
        df[col].notna() &
        ~df[col].astype(str).str.match(r'^\d+\.\d{2}$')
    )

    if mask.any():
        print(f"\n=== {col} - Invalid 2 Decimal Format ===")
        print(df.loc[mask, ['pdp_url', col]].to_string(index=False))
        print(f"Total issues: {mask.sum()}")
    else:
        print(f"{col}: All values are in 2 decimal format.")

=== regular_price - Invalid 2 Decimal Format ===
                                                                                          pdp_url  regular_price
                                     https://shop.billa.at/produkte/hennessy-very-special-0011379           47.9
                        https://shop.billa.at/produkte/rauch-weizenmehl-extra-fuer-kuchen-0015865            1.8
                                        https://shop.billa.at/produkte/oelz-mehrkorntoast-0014336            3.8
                                https://shop.billa.at/produkte/stangl-fadennudeln-mit-ei-00196840            3.8
                                 https://shop.billa.at/produkte/stangl-bandnudeln-mit-ei-00196865            3.8
                                   https://shop.billa.at/produkte/stangl-fleckerl-mit-ei-00196873            3.8
                                   https://shop.billa.at/produkte/stangl-spiralen-mit-ei-00196881            3.8
                                  https://shop.billa.at/produkte/stangl-hoernchen-mit-ei-00196899            3.8
                                       https://shop.billa.at/produkte/clever-selchroller-00200090            0.9
                                  https://shop.billa.at/produkte/courvoisier-vsop-cognac-00201384           45.9
                                    https://shop.billa.at/produkte/courvoisier-vs-cognac-00201376           34.9
                                            https://shop.billa.at/produkte/zipfer-maerzen-0021910            1.4
                   https://shop.billa.at/produkte/party-breze-raeucherlachssinfonie-baby-00253569           39.9
                                    https://shop.billa.at/produkte/roastbeef-geschnitten-00256586           59.9
                                https://shop.billa.at/produkte/breze-kaesevariation-baby-00253612           22.9
                               https://shop.billa.at/produkte/partybreze-dolce-vita-baby-00253643           34.9
                         https://shop.billa.at/produkte/aberlour-single-malt-whisky-12yo-00255242           58.9
                      https://shop.billa.at/produkte/party-breze-schinkenkaese-duo-sesam-00271280           42.9
                                   https://shop.billa.at/produkte/danke-bauer-haussalami-00271803           17.9
                      https://shop.billa.at/produkte/party-breze-schinkenkaese-duo-lauge-00272497           44.9
                       https://shop.billa.at/produkte/party-breze-schinkenkaese-duo-baby-00272501           22.9
                                 https://shop.billa.at/produkte/reisetbauer-axberg-vodka-00278748           36.9
                                 https://shop.billa.at/produkte/hofstaedter-beinschinken-00280517            1.5
                       https://shop.billa.at/produkte/diplomatico-reserva-exclusiva-12yo-00284644           51.9
                          https://shop.billa.at/produkte/chivas-regal-18yo-scotch-whisky-00290304           68.9
     https://shop.billa.at/produkte/chivas-regal-royal-salute-21yo-blended-scotch-whisky-00290305          179.9
                          https://shop.billa.at/produkte/ron-zacapa-centenario-23-solera-00290313           59.9
                                        https://shop.billa.at/produkte/yutaka-sushi-reis-00291889            3.8
                   https://shop.billa.at/produkte/ben-und-jerrys-chocolate-fudge-brownie-00296744            3.0
                                 https://shop.billa.at/produkte/sesambreze-knusperstelze-00299667           42.9
                                https://shop.billa.at/produkte/laugenbreze-knusperstelze-00299669           46.9
                                      https://shop.billa.at/produkte/martell-cognac-vsop-00303150           47.9
                                 https://shop.billa.at/produkte/president-meersalzbutter-00309098            3.8
             https://shop.billa.at/produkte/the-glenlivet-single-malt-scotch-whisky-12yo-00312977           39.9
                    https://shop.billa.at/produkte/chivas-regal-xv-blended-scotch-whisky-00313122           49.9
                      https://shop.billa.at/produkte/formil-laktosefreie-haltbarmilch-15-00315379            1.8
                                          https://shop.billa.at/produkte/mehrkornweckerl-00316402            0.6
                                                https://shop.billa.at/produkte/beerenmix-00310265           21.9
                               https://shop.billa.at/produkte/alnatura-vollkorn-farfalle-00317448            1.7
                           https://shop.billa.at/produkte/clever-eier-aus-bodenhaltung-m-00312736            3.8
                                    https://shop.billa.at/produkte/alnatura-risotto-reis-00317649            3.8
             https://shop.billa.at/produkte/the-glenlivet-founders-reserve-scotch-whisky-00320208           35.9
                                   https://shop.billa.at/produkte/gin-mare-mediterranean-00323898           46.9
                          https://shop.billa.at/produkte/barcelo-imperial-ron-dominicano-00324955           39.9
                      https://shop.billa.at/produkte/ja-natuerlich-bio-spitzpaprika-bunt-00339602            3.8
                                      https://shop.billa.at/produkte/voeslauer-prickelnd-00344561            1.9
                        https://shop.billa.at/produkte/hofstaedter-selchschopf-essfertig-00346096            1.0
                                      https://shop.billa.at/produkte/clever-zwiebel-gelb-00346427            1.7
                           https://shop.billa.at/produkte/finis-feinstes-ruckzuck-griess-00349818            1.8
                             https://shop.billa.at/produkte/gourmet-glas-die-kaesemacher-00349582           15.5
                                            https://shop.billa.at/produkte/berger-knacker-0035040            1.5
                            https://shop.billa.at/produkte/remy-martin-1738-accord-royal-00352975           69.9
                                              https://shop.billa.at/produkte/2b-hemp-gin-00353644           46.9
                                  https://shop.billa.at/produkte/silvia-heinrich-terra-o-00370571           39.9
                             https://shop.billa.at/produkte/just-taste-edamame-spaghetti-00389050            3.8
                 https://shop.billa.at/produkte/just-taste-lila-suesskartoffel-fettucine-00389033            3.8
                               https://shop.billa.at/produkte/mediterrane-feinkostplatte-00390181           32.9
                           https://shop.billa.at/produkte/vegetarische-jourgebaeckplatte-00397688           54.9
                   https://shop.billa.at/produkte/vegetarische-baguette-broetchen-platte-00397691           45.9
                                https://shop.billa.at/produkte/deftige-jour-semmelplatte-00397693           54.9
                                 https://shop.billa.at/produkte/da-komm-ich-her-eissalat-00400428            1.7
                                   https://shop.billa.at/produkte/formil-haltbarmilch-35-00400480            0.9
                                   https://shop.billa.at/produkte/formil-haltbarmilch-05-00400484            0.9
                                       https://shop.billa.at/produkte/bumbu-the-original-00402465           39.9
                         https://shop.billa.at/produkte/da-komm-ich-her-snack-radieschen-00410232            1.7
                        https://shop.billa.at/produkte/da-komm-ich-her-paprika-tricolore-00410646            3.8
                           https://shop.billa.at/produkte/ja-natuerlich-bio-austernpilze-00410667            3.8
                                https://shop.billa.at/produkte/da-komm-ich-her-melanzani-00410633            1.7
                                https://shop.billa.at/produkte/sinnack-mehrkornbroetchen-00410950            1.7
                                      https://shop.billa.at/produkte/eskimo-calippo-cola-00413434            1.5
               https://shop.billa.at/produkte/glenfiddich-12yo-single-malt-scotch-whisky-00415604           55.9
                                          https://shop.billa.at/produkte/recheis-lasagne-00418953            1.7
                                      https://shop.billa.at/produkte/markowitsch-redmont-00421222           21.9
                                https://shop.billa.at/produkte/recheis-familie-hoernchen-00422246            3.8
                             https://shop.billa.at/produkte/iglo-blattspinat-zwutschgerl-00424163            3.8
                            https://shop.billa.at/produkte/glanzer-gold-weizenmehl-glatt-00418255            1.7
                       https://shop.billa.at/produkte/oelz-muehlviertler-weizenmischbrot-00427149            3.7
                                    https://shop.billa.at/produkte/sinnack-unsere-besten-00427178            1.7
                       https://shop.billa.at/produkte/eskimo-cremissimo-eiskaffee-becher-00427981            2.3
                 https://shop.billa.at/produkte/eskimo-cremissimo-erdbeer-vanille-becher-00428250            2.3
                                https://shop.billa.at/produkte/murelli-cola-mix-limonade-00429353            1.9
                                  https://shop.billa.at/produkte/reschundfrisch-backofen-00431390          149.9
                                https://shop.billa.at/produkte/noem-fasten-milch-09-fett-00431900            1.7
                               https://shop.billa.at/produkte/noem-guten-morgen-milch-18-00432809            1.7
                             https://shop.billa.at/produkte/baby-breze-vegetarisch-sesam-00434941           22.9
                      https://shop.billa.at/produkte/wurzelbrot-rein-pflanzlich-gefuellt-00435015           18.9
                         https://shop.billa.at/produkte/eskimo-cornetto-kingcone-vanilla-00440645            2.9
                              https://shop.billa.at/produkte/noem-lfree-halbfettmilch-18-00441099            1.7
                              https://shop.billa.at/produkte/da-komm-ich-her-zwiebel-rot-00444016            1.7
                           https://shop.billa.at/produkte/goelles-ron-johan-old-plum-rum-00447361           44.9
                         https://shop.billa.at/produkte/nestle-pirulo-kaktus-for-friends-00448110            2.9
                                      https://shop.billa.at/produkte/noem-rahmjoghurt-10-00453897            1.7
                   https://shop.billa.at/produkte/arnautovic-premium-london-dry-gin-no-7-00455356           36.9
                     https://shop.billa.at/produkte/schnitzer-sesam-schnitten-glutenfrei-00464409            3.8
                                https://shop.billa.at/produkte/eskimo-magnum-billionaire-00465507            2.9
                            https://shop.billa.at/produkte/ja-natuerlich-bio-vogerlsalat-00475740            1.7
                                        https://shop.billa.at/produkte/jourgebaeckplatte-00478373           54.9
                                   https://shop.billa.at/produkte/mumm-grand-cordon-rose-00482101           69.9
                             https://shop.billa.at/produkte/mumm-grand-cordon-champagner-00482129           49.9
                                          https://shop.billa.at/produkte/dinkelbrot-hell-00508961            3.8
                                        https://shop.billa.at/produkte/putengenussplatte-00514783           16.9
                                           https://shop.billa.at/produkte/schinkenplatte-00514794           19.9
               https://shop.billa.at/produkte/wurst-schinken-kaese-aus-oesterreich-klein-00514800           17.9
               https://shop.billa.at/produkte/wurst-schinken-kaese-aus-oesterreich-gross-00514806           34.9
                                      https://shop.billa.at/produkte/wurstschinkenplatte-00514816           34.9
                                           https://shop.billa.at/produkte/heurigenplatte-00514823           34.9
                                       https://shop.billa.at/produkte/grosse-kaeseplatte-00514829           32.9
                                           https://shop.billa.at/produkte/festtagsplatte-00514828           39.9
                                       https://shop.billa.at/produkte/kleine-kaeseplatte-00514832           14.9
                                    https://shop.billa.at/produkte/exquisite-kaeseplatte-00514842           39.9
                             https://shop.billa.at/produkte/oesterreichische-kaeseplatte-00514849           19.9
                                        https://shop.billa.at/produkte/fischdelikatessen-00514856           29.9
                                               https://shop.billa.at/produkte/obstplatte-00519204           18.9
                                https://shop.billa.at/produkte/laugenbreze-putenquintett-00520400           44.9
                                  https://shop.billa.at/produkte/sandwichbroetchenplatte-00520397           24.9
                                 https://shop.billa.at/produkte/sesambreze-putenquintett-00520401           42.9
                                 https://shop.billa.at/produkte/baby-breze-putenquintett-00520402           22.9
                           https://shop.billa.at/produkte/ja-natuerlich-seeforellenfilet-00527191           64.9
                            https://shop.billa.at/produkte/gobelsburg-riesling-urgestein-00537082           14.9
                                        https://shop.billa.at/produkte/clubmate-original-00550609            3.5
                              https://shop.billa.at/produkte/recheis-familie-fadennudeln-00564088            3.8
                                 https://shop.billa.at/produkte/oelz-landbrot-100-dinkel-00566804            3.8
                                      https://shop.billa.at/produkte/fior-london-dry-gin-00574479           39.9
                                  https://shop.billa.at/produkte/rauch-mehl-doppelgriffig-0054006            1.8
                             https://shop.billa.at/produkte/herzerl-platte-feinschmecker-00540576           11.9
                       https://shop.billa.at/produkte/ja-natuerlich-bio-spitzpaprika-rot-00579260            1.7
                                https://shop.billa.at/produkte/ja-natuerlich-bachforelle-00581678           48.9
                                  https://shop.billa.at/produkte/dubioza-pflaumenschnaps-00584708           29.9
                                 https://shop.billa.at/produkte/maksuzija-quittenschnaps-00584712           36.9
                                 https://shop.billa.at/produkte/roe-und-co-irish-whiskey-00586970           39.9
                             https://shop.billa.at/produkte/redbreast-irish-whiskey-12yo-00587045           55.9
                                https://shop.billa.at/produkte/noem-waldviertel-milch-35-00608239            1.7
                                         https://shop.billa.at/produkte/schmankerlplatte-00608969           24.9
                                https://shop.billa.at/produkte/nonino-grappa-millesimata-00609404           34.9
                                     https://shop.billa.at/produkte/reisetbauer-blue-gin-00614971           39.9
                               https://shop.billa.at/produkte/ricard-pastis-de-marseille-00619468           24.9
                     https://shop.billa.at/produkte/klassische-baguette-broetchen-platte-00622052           46.9
                           https://shop.billa.at/produkte/miraval-rose-cotes-de-provence-00622254           23.9
                                             https://shop.billa.at/produkte/canapeplatte-00622563           56.9
                                          https://shop.billa.at/produkte/makronen-platte-00624516           24.0
                                       https://shop.billa.at/produkte/kuchenplatte-klein-00624522           16.0
                              https://shop.billa.at/produkte/jack-daniels-gentleman-jack-00624794           38.9
                                https://shop.billa.at/produkte/kuchenpeter-semmelwuerfel-00633142            1.7
                                  https://shop.billa.at/produkte/weninger-veratina-cuvee-00634025           21.9
                                          https://shop.billa.at/produkte/belvedere-vodka-00635256           43.9
                                            https://shop.billa.at/produkte/hendricks-gin-00636234           47.9
                                 https://shop.billa.at/produkte/glenkinchie-12-years-old-00638518           44.9
                 https://shop.billa.at/produkte/ja-natuerlich-saiblingsfilet-geraeuchert-00643205            7.6
                        https://shop.billa.at/produkte/die-leichte-muh-fruehstuecksmilch-00641676            1.8
    https://shop.billa.at/produkte/antipastimix-gefuellt-mit-frischkaese-die-kaesemacher-00655028           12.5
                                   https://shop.billa.at/produkte/recheis-familie-dralli-00655416            3.8
                              https://shop.billa.at/produkte/partybreze-dolce-vita-sesam-00651354           52.9
                               https://shop.billa.at/produkte/breze-kaesevariation-sesam-00651358           42.9
                https://shop.billa.at/produkte/ja-natuerlich-vollmilch-laenger-frisch-35-00651606            1.8
                     https://shop.billa.at/produkte/sinnack-unsere-besten-mit-roggenmehl-00660710            1.7
                                    https://shop.billa.at/produkte/billa-knusperstangerl-00674914            1.0
                                    https://shop.billa.at/produkte/caol-ila-12-years-old-00677036           56.9
                              https://shop.billa.at/produkte/frierss-bergsalami-kaernten-00695129           19.9
                 https://shop.billa.at/produkte/talisker-10-years-old-single-malt-whisky-00696211           59.9
                             https://shop.billa.at/produkte/ja-natuerlich-bio-handsemmel-00700602            0.9
                                  https://shop.billa.at/produkte/glenmorangie-nectar-dor-00700816           89.9
                           https://shop.billa.at/produkte/ardbeg-10yo-single-malt-whisky-00700819           65.9
                              https://shop.billa.at/produkte/japanische-kammmuscheln-msc-00702520           89.9
                            https://shop.billa.at/produkte/brunch-platte-rein-pflanzlich-00703705           28.9
                  https://shop.billa.at/produkte/party-breze-raeucherlachssinfonie-sesam-00705136           62.9
                                            https://shop.billa.at/produkte/brunch-platte-00705266           28.9
                             https://shop.billa.at/produkte/partybreze-vegetarisch-lauge-00705843           44.9
                             https://shop.billa.at/produkte/partybreze-vegetarisch-sesam-00706210           42.9
                          https://shop.billa.at/produkte/ja-natuerlich-seesaiblingsfilet-00708455           64.9
                                          https://shop.billa.at/produkte/barilla-lasagne-00712252            1.7
           https://shop.billa.at/produkte/schnitzer-bread-less-bio-saatenbrot-glutenfrei-00716799            3.8
                                             https://shop.billa.at/produkte/absolut-elyx-00716876           43.9
                                  https://shop.billa.at/produkte/pampero-aniversario-rum-00717879           39.9
                               https://shop.billa.at/produkte/ja-natuerlich-bachsaibling-00718667           48.9
https://shop.billa.at/produkte/frosta-gemuese-beilage-gelbe-karotten-und-gruener-spargel-00719416            3.7

In [43]:
price_cols = ['regular_price', 'selling_price']

for col in price_cols:
    # Check exactly 2 decimal places
    mask = (
        df[col].notna() &
        ~df[col].astype(str).str.match(r'^\d+\.\d{2}$')
    )

    if mask.any():
        issues = df.loc[mask, ['pdp_url', col]].copy()

        # Row number = dataframe index + 2
        issues.insert(0, 'row_no', issues.index + 2)

        print(f"\n=== {col} - Invalid 2 Decimal Format ===")
        print(issues.to_string(index=False))
        print(f"\nTotal issues: {len(issues)}")

    else:
        print(f"{col}: All values are in 2 decimal format.")

=== regular_price - Invalid 2 Decimal Format ===
 row_no                                                                                                            pdp_url  regular_price
    192               https://sortiment.lidl.ch/de/catalog/product/view/id/21483/s/spezialwaschmittel-1012861/category/54/            2.6
    433             https://sortiment.lidl.ch/de/catalog/product/view/id/20849/s/schweizer-kartoffeln-0083292/category/54/            3.3
    645 https://sortiment.lidl.ch/de/catalog/product/view/id/20044/s/calanda-radler-mango-spritz-0-0--5113623/category/54/            8.5
    998               https://sortiment.lidl.ch/de/catalog/product/view/id/18360/s/recybag-sammelsack-5113234/category/54/           16.0
   1003               https://sortiment.lidl.ch/de/catalog/product/view/id/18359/s/recybag-sammelsack-5113221/category/54/           10.0
   1005               https://sortiment.lidl.ch/de/catalog/product/view/id/18358/s/recybag-sammelsack-5113220/category/54/           24.0
   1010     https://sortiment.lidl.ch/de/catalog/product/view/id/18328/s/high-protein-fruchtquark-xxl-0173558/category/54/            2.7
   1107            https://sortiment.lidl.ch/de/catalog/product/view/id/17754/s/tempo-toilettenpapier-1800482/category/54/           26.5
   1279   https://sortiment.lidl.ch/de/catalog/product/view/id/16605/s/calanda-radler-grapefruit-0-0--5112745/category/54/            8.5
   1778                  https://sortiment.lidl.ch/de/catalog/product/view/id/15496/s/sushi-staebchen-0174609/category/54/            0.1
   1939   https://sortiment.lidl.ch/de/catalog/product/view/id/14697/s/holzbesteck-gabel-loeffel-2in1-0158261/category/54/            0.1
   2115                      https://sortiment.lidl.ch/de/catalog/product/view/id/14074/s/saftorangen-0080155/category/54/            2.1
   2679                     https://sortiment.lidl.ch/de/catalog/product/view/id/12536/s/schokoriegel-0143861/category/54/            1.7
   3093                                                  https://www.lidl.ch/p/de-CH/fisher-price-schlummer-tier/p10056963           29.9
   3100                                                        https://www.lidl.ch/p/de-CH/lupilu-activity-decke/p10056960           29.9
   3102                                                          https://www.lidl.ch/p/de-CH/livarno-bad-vitrine/p10057000           59.9
   3103                                                     https://www.lidl.ch/p/de-CH/singer-naehmaschine-323l/p10056975          119.0
   3106                                                            https://www.lidl.ch/p/de-CH/esmara-trenchcoat/p10057023           24.9
   3107                                              https://www.lidl.ch/p/de-CH/livarno-waschbeckenunterschrank/p10057001           59.9
   3111                                              https://www.lidl.ch/p/de-CH/livarno-home-kinderschreibtisch/p10057318          119.0
   3113                                      https://www.lidl.ch/p/de-CH/michalsky-satin-wende-bettwaesche-3-tlg/p10056761           39.9
   3116                                      https://www.lidl.ch/p/de-CH/michalsky-satin-wende-bettwaesche-2-tlg/p10056760           29.9
   3119                                             https://www.lidl.ch/p/de-CH/silvercrest-3-in-1-sandwichmaker/p10057333           24.9
   3122                                                       https://www.lidl.ch/p/de-CH/silvercrest-mikrowelle/p10057358           69.9
   3129                                                  https://www.lidl.ch/p/de-CH/silvercrest-kuechenmaschine/p10057357           49.9
   3305                                         https://www.lidl.ch/p/de-CH/milbona-high-protein-fruchtquark-xxl/p10057225            2.7
   3349                                 https://www.lidl.ch/p/de-CH/parkside-doppelschleifer-mit-flexibler-welle/p10056976           29.9
   3362                                              https://www.lidl.ch/p/de-CH/parkside-multifunktionswerkzeug/p10056986           29.9
   3376                                                   https://www.lidl.ch/p/de-CH/kibernetik-entfeuchter-m16/p10057022          129.0
   3435                                     https://www.lidl.ch/p/de-CH/crivit-premium-laufschuhe-carbonlite-1-0/p10057304           29.9
   3444                                              https://www.lidl.ch/p/de-CH/livarno-waschbeckenunterschrank/p10057003           39.9
   3450                                     https://www.lidl.ch/p/de-CH/crivit-premium-laufschuhe-carbonlite-1-0/p10057305           29.9
   3459                                                 https://www.lidl.ch/p/de-CH/silvercrest-espressomaschine/p10057353           79.9
   3463  https://www.lidl.ch/p/de-CH/silvercrest-heissluftfritteuse-2-l-aktion-nur-in-der-deutschschweiz-gueltig/p10057332           29.9
   3468                                                       https://www.lidl.ch/p/de-CH/silvercrest-standmixer/p10057349           34.9
   3479                                                       https://www.lidl.ch/p/de-CH/silvercrest-crepemaker/p10057334           29.9
   3490                                                                   https://www.lidl.ch/p/de-CH/lycamobile/p10000052           10.0
   3493                                                                  https://www.lidl.ch/p/de-CH/paysafecard/p77772797           25.0
   3495                                                                       https://www.lidl.ch/p/de-CH/roblox/p10045176           10.0
   3498                                                                            https://www.lidl.ch/p/de-CH/h-m/p912021           20.0
   3504                                                                     https://www.lidl.ch/p/de-CH/swisscom/p10000043           10.0
   3513                                                                        https://www.lidl.ch/p/de-CH/yallo/p10000051           10.0
   3520                                                                       https://www.lidl.ch/p/de-CH/lebara/p10000053           10.0
   3538                                                           https://www.lidl.ch/p/de-CH/lidl-geschenkkarte/p11051105            5.0
   3540                                                                  https://www.lidl.ch/p/de-CH/apple-gift-card/p1106           30.0
   3543                                                                     https://www.lidl.ch/p/de-CH/nintendo/p88881105           35.0
   3544                                                                        https://www.lidl.ch/p/de-CH/steam/p10045175           20.0
   3562                                                                    https://www.lidl.ch/p/de-CH/cryptonow/p10029139           50.0
   3565                                                                 https://www.lidl.ch/p/de-CH/lidl-connect/p10053079           10.0
   3570                                                                  https://www.lidl.ch/p/de-CH/paysafecard/p99992797          150.0
   3582                                                                      https://www.lidl.ch/p/de-CH/sunrise/p10000044           10.0
   3588                                                                      https://www.lidl.ch/p/de-CH/one4all/p10029140           30.0
   3590                                                                  https://www.lidl.ch/p/de-CH/paysafecard/p88882797           75.0
   3592                                                                         https://www.lidl.ch/p/de-CH/salt/p10000045           10.0
   3599                                                                          https://www.lidl.ch/p/de-CH/zalando/p1108           30.0
   3602                                                                      https://www.lidl.ch/p/de-CH/google-play/p8746            5.0
   3603                                                             https://www.lidl.ch/p/de-CH/sony-playstation/p10000057           30.0
   3608                                                           https://www.lidl.ch/p/de-CH/lidl-geschenkkarte/p11041104            5.0

Total issues: 58

=== selling_price - Invalid 2 Decimal Format ===
 row_no                                                                                                           pdp_url  selling_price
    192              https://sortiment.lidl.ch/de/catalog/product/view/id/21483/s/spezialwaschmittel-1012861/category/54/            2.6
    433            https://sortiment.lidl.ch/de/catalog/product/view/id/20849/s/schweizer-kartoffeln-0083292/category/54/            3.3
    998              https://sortiment.lidl.ch/de/catalog/product/view/id/18360/s/recybag-sammelsack-5113234/category/54/           16.0
   1003              https://sortiment.lidl.ch/de/catalog/product/view/id/18359/s/recybag-sammelsack-5113221/category/54/           10.0
   1005              https://sortiment.lidl.ch/de/catalog/product/view/id/18358/s/recybag-sammelsack-5113220/category/54/           24.0
   1010    https://sortiment.lidl.ch/de/catalog/product/view/id/18328/s/high-protein-fruchtquark-xxl-0173558/category/54/            2.7
   1330                  https://sortiment.lidl.ch/de/catalog/product/view/id/16482/s/zinfandel-rose-0206816/category/54/            3.0
   1400                       https://sortiment.lidl.ch/de/catalog/product/view/id/16343/s/piu-secco-0206227/category/54/            2.2
   1778                 https://sortiment.lidl.ch/de/catalog/product/view/id/15496/s/sushi-staebchen-0174609/category/54/            0.1
   1906          https://sortiment.lidl.ch/de/catalog/product/view/id/14801/s/freixenet-carta-nevada-0007533/category/54/            7.8
   1939  https://sortiment.lidl.ch/de/catalog/product/view/id/14697/s/holzbesteck-gabel-loeffel-2in1-0158261/category/54/            0.1
   2115                     https://sortiment.lidl.ch/de/catalog/product/view/id/14074/s/saftorangen-0080155/category/54/            2.1
   2228                    https://sortiment.lidl.ch/de/catalog/product/view/id/13675/s/prosecco-doc-0127982/category/54/            3.0
   2421              https://sortiment.lidl.ch/de/catalog/product/view/id/13196/s/weisswein-lieblich-0025273/category/54/            2.2
   2441                https://sortiment.lidl.ch/de/catalog/product/view/id/13146/s/rotwein-lieblich-0025275/category/54/            2.2
   2679                    https://sortiment.lidl.ch/de/catalog/product/view/id/12536/s/schokoriegel-0143861/category/54/            1.7
   3093                                                 https://www.lidl.ch/p/de-CH/fisher-price-schlummer-tier/p10056963           24.9
   3100                                                       https://www.lidl.ch/p/de-CH/lupilu-activity-decke/p10056960           24.9
   3102                                                         https://www.lidl.ch/p/de-CH/livarno-bad-vitrine/p10057000           49.9
   3103                                                    https://www.lidl.ch/p/de-CH/singer-naehmaschine-323l/p10056975           99.0
   3106                                                           https://www.lidl.ch/p/de-CH/esmara-trenchcoat/p10057023           19.9
   3107                                             https://www.lidl.ch/p/de-CH/livarno-waschbeckenunterschrank/p10057001           49.9
   3111                                             https://www.lidl.ch/p/de-CH/livarno-home-kinderschreibtisch/p10057318           59.0
   3113                                     https://www.lidl.ch/p/de-CH/michalsky-satin-wende-bettwaesche-3-tlg/p10056761           34.9
   3116                                     https://www.lidl.ch/p/de-CH/michalsky-satin-wende-bettwaesche-2-tlg/p10056760           24.9
   3122                                                      https://www.lidl.ch/p/de-CH/silvercrest-mikrowelle/p10057358           59.9
   3129                                                 https://www.lidl.ch/p/de-CH/silvercrest-kuechenmaschine/p10057357           39.9
   3305                                        https://www.lidl.ch/p/de-CH/milbona-high-protein-fruchtquark-xxl/p10057225            2.7
   3349                                https://www.lidl.ch/p/de-CH/parkside-doppelschleifer-mit-flexibler-welle/p10056976           29.9
   3362                                             https://www.lidl.ch/p/de-CH/parkside-multifunktionswerkzeug/p10056986           29.9
   3376                                                  https://www.lidl.ch/p/de-CH/kibernetik-entfeuchter-m16/p10057022          109.0
   3435                                    https://www.lidl.ch/p/de-CH/crivit-premium-laufschuhe-carbonlite-1-0/p10057304           29.9
   3444                                             https://www.lidl.ch/p/de-CH/livarno-waschbeckenunterschrank/p10057003           39.9
   3450                                    https://www.lidl.ch/p/de-CH/crivit-premium-laufschuhe-carbonlite-1-0/p10057305           29.9
   3459                                                https://www.lidl.ch/p/de-CH/silvercrest-espressomaschine/p10057353           59.9
   3463 https://www.lidl.ch/p/de-CH/silvercrest-heissluftfritteuse-2-l-aktion-nur-in-der-deutschschweiz-gueltig/p10057332           29.9
   3465                                              https://www.lidl.ch/p/de-CH/tefal-heissluftfritteuse-3-5-l/p10057336           49.9
   3468                                                      https://www.lidl.ch/p/de-CH/silvercrest-standmixer/p10057349           34.9
   3479                                                      https://www.lidl.ch/p/de-CH/silvercrest-crepemaker/p10057334           29.9
   3490                                                                  https://www.lidl.ch/p/de-CH/lycamobile/p10000052           10.0
   3493                                                                 https://www.lidl.ch/p/de-CH/paysafecard/p77772797           25.0
   3495                                                                      https://www.lidl.ch/p/de-CH/roblox/p10045176           10.0
   3498                                                                           https://www.lidl.ch/p/de-CH/h-m/p912021           20.0
   3504                                                                    https://www.lidl.ch/p/de-CH/swisscom/p10000043           10.0
   3513                                                                       https://www.lidl.ch/p/de-CH/yallo/p10000051           10.0
   3520                                                                      https://www.lidl.ch/p/de-CH/lebara/p10000053           10.0
   3538                                                          https://www.lidl.ch/p/de-CH/lidl-geschenkkarte/p11051105            5.0
   3540                                                                 https://www.lidl.ch/p/de-CH/apple-gift-card/p1106           30.0
   3543                                                                    https://www.lidl.ch/p/de-CH/nintendo/p88881105           35.0
   3544                                                                       https://www.lidl.ch/p/de-CH/steam/p10045175           20.0
   3562                                                                   https://www.lidl.ch/p/de-CH/cryptonow/p10029139           50.0
   3565                                                                https://www.lidl.ch/p/de-CH/lidl-connect/p10053079           10.0
   3570                                                                 https://www.lidl.ch/p/de-CH/paysafecard/p99992797          150.0
   3582                                                                     https://www.lidl.ch/p/de-CH/sunrise/p10000044           10.0
   3588                                                                     https://www.lidl.ch/p/de-CH/one4all/p10029140           30.0
   3590                                                                 https://www.lidl.ch/p/de-CH/paysafecard/p88882797           75.0
   3592                                                                        https://www.lidl.ch/p/de-CH/salt/p10000045           10.0
   3599                                                                         https://www.lidl.ch/p/de-CH/zalando/p1108           30.0
   3602                                                                     https://www.lidl.ch/p/de-CH/google-play/p8746            5.0
   3603                                                            https://www.lidl.ch/p/de-CH/sony-playstation/p10000057           30.0
   3608                                                          https://www.lidl.ch/p/de-CH/lidl-geschenkkarte/p11041104            5.0

Total issues: 61

In [55]:
# Check whether price_was is the same as regular_price
# If they are different, the record is reported as an issue.

mask = (
    df['price_was'].notna() &
    df['regular_price'].notna() &
    (df['price_was'].astype(str) != df['regular_price'].astype(str))
)

issues = df.loc[
    mask,
    ['pdp_url', 'price_was', 'regular_price']
].copy()

# Add Excel row number (+2 because row 1 is the header)
issues['row_no'] = issues.index + 2

# Reorder columns
issues = issues[['row_no', 'pdp_url', 'price_was', 'regular_price']]

print(f"Total issues: {len(issues)}")
print(issues.to_string(index=False))

Total issues: 0
Empty DataFrame
Columns: [row_no, pdp_url, price_was, regular_price]
Index: []