In [1]:
import pandas as pd
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option("display.max_colwidth", None)

In [ ]:
df = pd.read_csv(r'/home/user/Downloads/DataHut_SI_Mercator_PriceExtractions_20260727.CSV', low_memory=False, sep='|')

       id reference_number  \
0  265842              006
1  243515         FZ01VFLT
2  175865        CAP165LSL
3  232366           SM-022
4  252788        CAP128ASD

                                                                              title  \
0                                             BRAND NEW 2BHK FOR FAMILIES AT ALKHOR
1                           Brand New Villa Apartment| 02 Bedrooms| Inclusive bills
2                          LUSAIL 1BHK NO COMMISSION | BILLS INCLUDED | WORRY FREE!
3  Brand New 2BHK Apartment In Old Airport Near Commercial Street With 1 Month Free
4                                FURNISHED 2BHK ALSADD NEAR METRO BILLS INCL NO FEE

                                                                                                                                                            url  \
0                                             https://qlp.qatarliving.com/en/properties/rent/residential/apartment/brand_new_2bhk_for_families_at_alkhor/265842
1                       https://qlp.qatarliving.com/en/properties/rent/residential/villa_apartment/brand_new_villa_apartment_02_bedrooms_inclusive_bills/243515
2                              https://qlp.qatarliving.com/en/properties/rent/residential/apartment/lusail_1bhk_no_commission_bills_included_worry_free_/175865
3  https://qlp.qatarliving.com/en/properties/rent/residential/apartment/brand_new_2bhk_apartment_in_old_airport_near_commercial_street_with_1_month_free/232366
4                                https://qlp.qatarliving.com/en/properties/rent/residential/apartment/furnished_2bhk_alsadd_near_metro_bills_incl_no_fee/252788

   category  \
0  For rent
1  For rent
2  For rent
3  For rent
4  For rent

                                                             category_url  \
0  https://qlp.qatarliving.com/en/properties/residential?purpose=For+Rent
1  https://qlp.qatarliving.com/en/properties/residential?purpose=For+Rent
2  https://qlp.qatarliving.com/en/properties/residential?purpose=For+Rent
3  https://qlp.qatarliving.com/en/properties/residential?purpose=For+Rent
4  https://qlp.qatarliving.com/en/properties/residential?purpose=For+Rent

                     broker_display_name  \
0                  LAND ROYAL PROPERTIES
1                FZ Evercore Real Estate
2                Capital One Real Estate
3  ORBIT HOMES REAL ESTATE, DOHA - QATAR
4                Capital One Real Estate

                                  broker  price currency price_per  details  \
0                  LAND ROYAL PROPERTIES   5000      QAR     Month  100 Sqm
1                FZ EVERCORE REAL ESTATE   5000      QAR     Month  125 Sqm
2                CAPITAL ONE REAL ESTATE   5500      QAR     Month   60 Sqm
3  ORBIT HOMES REAL ESTATE, DOHA - QATAR   4500      QAR     Month
4                CAPITAL ONE REAL ESTATE   6500      QAR     Month  100 Sqm

  number_of_photos                                 location bathrooms  \
0               11                    Al Khor,Al Khor,Qatar         2
1               10  Al Dhakhira / Al Thakhira,Al Khor,Qatar         2
2               25                     Erkiyah,Lusail,Qatar         1
3               16                   Old Airport,Doha,Qatar         2
4               24                       Al Sadd,Doha,Qatar         2

  bedrooms        furnished  \
0        2      Unfurnished
1        2      Unfurnished
2        1  Fully furnished
3        2      Unfurnished
4        2  Fully furnished

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           description  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      NO COMMISSION, DIRECT FROM COMPANY 📍 Location: Close to the Al Owaina Family Park, behind QNB main branch AL KHOR A perfect residential spot for families and ladies staff looking for comfort, convenience, and community. 🏠 Available Units & Monthly Rent: 2 BHK | 2 Bathrooms – QAR 5250/- (Balcony) 2 BHK | 2 Bathrooms – QAR 5000/- 2 BHK | 1 Bathrooms – QAR 4250/- ✅ Features & Amenities: WIFI INCLUDED 🚗 Covered Parking 🏙️ Scenic City View 🛠️ On-Call Maintenance Services 🚶‍♀️ Walking Distance to AL OWAINA Family Park 🛏️ Spacious Layouts 🏡 Brand New Construction Enjoy modern living in a peaceful community with easy access to all major facilities. These apartments are brand new and ready for immediate move-in! Terms & Conditions: Contract Duration: Minimum 1 Year Payment: 12 Post-Dated Cheques + 1 Security Cheque Contact: Mr. Jasheel 77713653
1  Brand new villa aprtment available for rent located in Al Dhakira. Bills and maintenance including. Call us for viewing! Key Facts •Style: Villa apartment •Rental type: Minimum 1 Year •Furnished: Unfurnished •A/C: Split Rooms & Floor Plans •Bedroom: 02 •Bathroom: 02 •Kitchen: 01 Financial | Payment | Contract terms & Conditions: •Lease period: Minimum 12 months •Monthly Rent: QAR. 5,000 X 12 months •Security Deposit: QAR. 5,000 (Undated cheque) •Utilities: Inclusive •Broker Fee Paid By: Tenant •Broker Fee: Half month rent payable to ‘F Z Evercore Real Estate’ •Payment mode: 12 Post dated cheques + 01-month security deposit For more information contact the below Mobile | 33699972 | 33699957 Email | info@fzevercorerealestate.com Disclaimer: All information deemed reliable, but not guaranteed, and should be independently verified. The real estate information and related content displayed on this site is provided for consumers personal, non-commercial use and may not be used for any purpose other than to identify prospective properties consumers may be interested in purchasing/leasing. All information provided herein has been obtained from sources believed reliable, but may be subject to errors, omissions, change of price, prior sale, rent or withdrawal without notice. F Z Evercore Real Estate and its affiliates make no representation, warranty or guaranty as to the accuracy of any information contained herein. You should consult your agent for an independent verification of any properties and to view further details.
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 Reference: CAP165LSL Location: Lusail Enjoy contemporary living with pool, gym, and BBQ area. Excellent connectivity via Tram and Coastal Highway. Unit Details: Spacious 1BHK units with open kitchen layout and private balcony and dedicated parking. Amenities including:  Swimming Pool Fully equipped Gym Recreational Area BBQ Area Play Area Outdoor Gym  Rent Options: 3-month rental term at 7,500QAR/Month 6-month rental term at 6,000QAR/Month 1-year rental term at 5,500QAR/Month Prime Lusail location with easy access to Lusail Stadium, QNB Metro Station, Tram, and Al Khor Coastal Highway Inclusions:  Bills included (Kahramaa and Marafeq Chilled Water) 24/7 security and maintenance support Entire building fully managed by Capital One Real Estate  *** No Commission Charged *** Disclaimer: All images used are for illustrative purposes only. Photos and the actual property may have some minimal variation due to editing and property designs. All images and dimensions are not intended to be relied upon for.
3                               Enjoy modern and comfortable living in this brand-new 2BHK apartment located in Old Airport, near Main Commerical Street, in a convenient and well-connected area close to all daily services. This apartment is first tenant, unfurnished, and offers a practical layout, making it an excellent choice for families or individuals seeking a clean and ready-to-move-in home. Rental Details: • Monthly Rent: QAR 4,500 • 1 Month Free • Long-term lease (12 months) • 1 Security cheque • Bills excluded • Agency service fee equivalent to half a month’s rent applies Apartment Layout & Features: • 2 Bedrooms • Living hall • 2 Bathrooms • Closed kitchen • Unfurnished unit • Brand new – first tenant • Split A/C installed • Practical and comfortable layout Property Highlights: • Brand new apartment • First tenant • Clean and modern finishing • Quiet and well-maintained building • Suitable for families • Ready to move in Location Highlights: • Located in Old Airport • Near Main Commerical Street • Easy access to main roads Matar Street. • Close to supermarkets, restaurants, and daily services • Central and convenient location This apartment offers a great combination of new condition, practicality, and location, making it an ideal choice for tenants seeking a brand-new home in Old Airport. About Us: We believe that challenging ourselves to be better each day positively impacts the people and the community we serve as a ORBIT HOMES REAL ESTATE COMPANY.  Talk to us and discover exclusive market deals in Qatar.
4                                                                                                                                                                                                                                                                                                                                               Property Name: CAP128ASD Location: Al Sadd Street Name: Ibn Waila St. Introducing our brand new fully furnished 1, 2 and 3-bedroom apartments with large balconies located at the heart of Al Sadd exactly behind Ooredoo. Primely located with just minutes away from Metro Station, Fereej Al Nasser commercial street. Monthly rent options: - 1 BHK QAR 6,000 per month (including bills with QAR150 limit) - 2 BHK QAR 6,500 per month (including bills with QAR250 limit) - 3 BHK QAR 7,900 per month (including bills with QAR300 limit) Unit Details for 2BHK: Property Features / Amenities: • 2 Bedrooms • 2 Bathrooms • Living Room Area • Fully Fitted Kitchen • Balcony Amenities: - Dedicated Parking - Maintenance service - 24 Hours Security with CCTV surveillance. Contact Us Now To Know More About This Property And For Viewing! Requirements: • One Month Security Deposit • Kahramaa Deposit (Refundable) • Post-Dated Cheques *** No Commission Charged *** Disclaimer: All Images Used Are For Illustrative Purposes Only, Photos And The Actual Property May Have Some Minimal Variation Due To Editing And Property Designs. All Images And Dimensions Are Not Intended To Be Relied Upon For. *Terms and Conditions Apply

  sub_category_1 sub_category_2 agent_name  scraped_ts     depth  \
0    Residential                              20260727  FEATURED
1    Residential                              20260727  FEATURED
2    Residential                              20260727  FEATURED
3    Residential                              20260727  FEATURED
4    Residential                              20260727  FEATURED

  iteration_number    phone_number       date rera_permit_number  user_id  \
0       2026-07-04    +97477713653 2026-07-27                      376723
1       2026-07-04  +974 3369 9957 2026-07-27                      156347
2       2026-07-04    +97450699444 2026-07-27                      254906
3       2026-07-04  +974 5555 0491 2026-07-27                     2113454
4       2026-07-04    +97450699444 2026-07-27                      254906

     property_type  \
0        apartment
1  villa-apartment
2        apartment
3        apartment
4        apartment

                                                                                                                                                                amenities  \
0                                                                                                 Balcony,Elevator,Garden view,Networked,Maintenance,Security,Near Mosque
1                                                                                                              Bbq Area,City View,Ground Floor,Maintenance,Bills Included
2                                                      Balcony,Bbq Area,Elevator,Near Metro,Gym,Outdoor Pool,Bills Included,Concierge,Maintenance,Security,Kids Play Area
3  City View,Elevator,Near Metro,Near School,Ground Floor,High Floor,Mid Floor,Cafe,Restaurants,Maintenance,Near Airport,Near Mosque,Near Public Transport,Express Market
4                                                                                                                Balcony,Elevator,Kitchen Appliances,Maintenance,Security

  dtcm_licence published_at
0                2026-07-20
1                2026-06-13
2                2025-12-18
3                2026-05-16
4                2026-06-27

In [5]:
import pandas as pd

text_cols = df.select_dtypes(include="object").columns

issues = {}

for col in text_cols:
    # Match | not preceded by a backslash
    mask = (
        df[col]
        .fillna("")
        .astype(str)
        .str.contains(r"(?<!\\)\|", regex=True)
    )

    if mask.any():
        issues[col] = df.loc[mask, ["unique_id", col]]

# Print results
if issues:
    print("Columns containing unescaped '|':\n")
    for col, data in issues.items():
        print(f"\n=== {col} ({len(data)} rows) ===")
        print(data.to_string(index=False))
else:
    print("No unescaped '|' found.")

KeyError: "['unique_id'] not in index"

In [4]:
df.shape

(16866, 21)

In [5]:
empty_cols = df.columns[df.isna().all()].tolist()
empty_cols

['price_valid_from',
 'promotion_valid_from',
 'promotion_valid_upto',
 'region',
 'pack_size']

In [6]:
req_cols = """unique_id,competitor_name,extraction_date,product_name,grammage_quantity,grammage_unit,regular_price,selling_price,price_valid_from,price_per_unit,percentage_discount,promotion_price,promotion_valid_from,promotion_valid_upto,promotion_description,currency,breadcrumb,pdp_url,region,pack_size,site_shown_uom"""

req_cols = [c.strip() for c in req_cols.split(",") if c.strip()]

missing = [c for c in req_cols if c not in df.columns]
extra = [c for c in df.columns if c not in req_cols]

print("Requirement columns:", len(req_cols))
print("File columns:", len(df.columns))
print("Missing:", missing)
print("Extra:", extra)
print("Order matches:", req_cols == list(df.columns))

Requirement columns: 21
File columns: 21
Missing: []
Extra: []
Order matches: True

In [7]:
# Empty columns as per requirement
req_empty = """age_of_the_product,alchol_by_volume,barcode,beer_deg,brand_type,care_instructions,chilled,competitor_product_key,cooking_part,dietary_lifestyle,dimensions,distributor_address,dosage_recommendation,environmental,fit_guide,food_preservation,frozen,grade,grape_variety,handmade,heel_height,heel_type,importer_address,manufacturer_address,material_composition,max_heating_temperature,model_number,multi_buy_item_count,multi_buy_items_price_total,multibuy_items_pricesingle,netcontent,netweight,occasion,package_sizeof_sellingprice,per_unit_sizedescription,percentage_discount,perfect_match,processed_food,promo_limit,promotion_description,promotion_type,promotion_valid_upto,random_weight_flag,receipies,recycling_information,region,return_address,servings_per_pack,size,special_nutrition_purpose,standard_drinks,store_addressid,store_addressline1,store_addressline2,store_name,store_postcode,store_state,store_suburb,style,suitable_for,upc,usp,vinification_details,warranty,producthierarchy_level7,producthierarchy_level6,retail_limit"""

req_empty = [c.strip() for c in req_empty.split(",") if c.strip()]

# Empty columns in the file
file_empty = df.columns[df.isna().all()].tolist()

# Compare
missing_empty = [c for c in req_empty if c not in file_empty]
unexpected_empty = [c for c in file_empty if c not in req_empty]
matching_empty = [c for c in req_empty if c in file_empty]

print("Requirement empty columns :", len(req_empty))
print("File empty columns        :", len(file_empty))
print("Matching                 :", len(matching_empty))
print("Expected empty but not empty:", missing_empty)
print("Unexpected empty columns     :", unexpected_empty)

Requirement empty columns : 67
File empty columns        : 5
Matching                 : 2
Expected empty but not empty: ['age_of_the_product', 'alchol_by_volume', 'barcode', 'beer_deg', 'brand_type', 'care_instructions', 'chilled', 'competitor_product_key', 'cooking_part', 'dietary_lifestyle', 'dimensions', 'distributor_address', 'dosage_recommendation', 'environmental', 'fit_guide', 'food_preservation', 'frozen', 'grade', 'grape_variety', 'handmade', 'heel_height', 'heel_type', 'importer_address', 'manufacturer_address', 'material_composition', 'max_heating_temperature', 'model_number', 'multi_buy_item_count', 'multi_buy_items_price_total', 'multibuy_items_pricesingle', 'netcontent', 'netweight', 'occasion', 'package_sizeof_sellingprice', 'per_unit_sizedescription', 'percentage_discount', 'perfect_match', 'processed_food', 'promo_limit', 'promotion_description', 'promotion_type', 'random_weight_flag', 'receipies', 'recycling_information', 'return_address', 'servings_per_pack', 'size', 'special_nutrition_purpose', 'standard_drinks', 'store_addressid', 'store_addressline1', 'store_addressline2', 'store_name', 'store_postcode', 'store_state', 'store_suburb', 'style', 'suitable_for', 'upc', 'usp', 'vinification_details', 'warranty', 'producthierarchy_level7', 'producthierarchy_level6', 'retail_limit']
Unexpected empty columns     : ['price_valid_from', 'promotion_valid_from', 'pack_size']

In [8]:
df.instock.value_counts()

AttributeError: 'DataFrame' object has no attribute 'instock'

In [9]:
df.columns

Index(['unique_id', 'competitor_name', 'extraction_date', 'product_name',
       'grammage_quantity', 'grammage_unit', 'regular_price', 'selling_price',
       'price_valid_from', 'price_per_unit', 'percentage_discount',
       'promotion_price', 'promotion_valid_from', 'promotion_valid_upto',
       'promotion_description', 'currency', 'breadcrumb', 'pdp_url', 'region',
       'pack_size', 'site_shown_uom'],
      dtype='object')

In [10]:
df.nunique()

unique_id                16866
competitor_name              1
extraction_date              1
product_name             16740
grammage_quantity          685
grammage_unit                6
regular_price              820
selling_price              920
price_valid_from             0
price_per_unit            4483
percentage_discount         50
promotion_price            439
promotion_valid_from         0
promotion_valid_upto         0
promotion_description      139
currency                     1
breadcrumb                 461
pdp_url                  16866
region                       0
pack_size                    0
site_shown_uom           16740
dtype: int64

In [11]:
df.unique_id.nunique()

16866

In [12]:
df.competitor_name.unique()

array(['mercator'], dtype=object)

In [13]:
df.currency.value_counts()

currency
EUR    16866
Name: count, dtype: int64

In [14]:
df.extraction_date.value_counts()

extraction_date
2026-07-27    16866
Name: count, dtype: int64

In [15]:
df[df.selling_price==0]

Empty DataFrame
Columns: [unique_id, competitor_name, extraction_date, product_name, grammage_quantity, grammage_unit, regular_price, selling_price, price_valid_from, price_per_unit, percentage_discount, promotion_price, promotion_valid_from, promotion_valid_upto, promotion_description, currency, breadcrumb, pdp_url, region, pack_size, site_shown_uom]
Index: []

In [43]:
pattern = r'^[^>]+( > [^>]+)*$'

# Invalid breadcrumbs
invalid = df[
    df["breadcrumb"].isna() |
    (df["breadcrumb"].str.strip() == "") |
    (~df["breadcrumb"].str.fullmatch(pattern, na=False))
]

print(f"Total invalid breadcrumbs: {len(invalid)}")

if not invalid.empty:
    print(invalid[["breadcrumb"]])

Total invalid breadcrumbs: 0

In [17]:
df.columns.to_list()

['unique_id',
 'competitor_name',
 'extraction_date',
 'product_name',
 'grammage_quantity',
 'grammage_unit',
 'regular_price',
 'selling_price',
 'price_valid_from',
 'price_per_unit',
 'percentage_discount',
 'promotion_price',
 'promotion_valid_from',
 'promotion_valid_upto',
 'promotion_description',
 'currency',
 'breadcrumb',
 'pdp_url',
 'region',
 'pack_size',
 'site_shown_uom']

In [18]:
import pandas as pd

price_columns = [
    "regular_price",
    "selling_price",
    "price_was",
    "promotion_price",
    "percentage_discount",
    "price_per_unit",
    "multi_buy_items_price_total",
    "multibuy_items_pricesingle"
]

for col in price_columns:
    if col not in df.columns:
        continue

    s = df[col].fillna("").astype(str)

    issues = {
        "Zero values": pd.to_numeric(s, errors="coerce") == 0,
        "Negative values": pd.to_numeric(s, errors="coerce") < 0,
        "Multiple decimal points": s.str.count(r"\.") > 1,
        "More than 2 decimal places": s.str.contains(r"\.\d{3,}$", regex=True),
        "Non-numeric values": (~s.str.match(r"^-?\d+(\.\d+)?$", na=False)) & (s != ""),
        "Leading/Trailing whitespace": s != s.str.strip(),
    }

    print(f"\n{'='*15} {col} {'='*15}")

    for issue, mask in issues.items():
        if mask.any():
            print(f"{issue}: {mask.sum()}")
            print(df.loc[mask, [col]].head(5).to_string(index=False))

=============== regular_price ===============

=============== selling_price ===============

=============== promotion_price ===============

=============== percentage_discount ===============

=============== price_per_unit ===============
Non-numeric values: 15105
price_per_unit
   0.26€ / kos
   0.26€ / kos
   0.23€ / kos
   0.32€ / kos
   0.40€ / kos

In [19]:
import re

col = "regular_price"

# More than one decimal point in the numeric part
invalid = df[
    df[col]
    .fillna("")
    .astype(str)
    .str.contains(r'\d+\.\d+\.', regex=True)
]

print(f"Rows with multiple decimal points: {len(invalid)}")
print(invalid[[col]])

Rows with multiple decimal points: 0
Empty DataFrame
Columns: [regular_price]
Index: []

In [44]:
import re

url_pattern = re.compile(
    r"^https?://[^\s/$.?#].[^\s]*$",
    re.IGNORECASE
)

invalid_urls = df[
    df["pdp_url"].isna() |
    ~df["pdp_url"].astype(str).str.match(url_pattern)
]

print(f"Invalid URLs: {len(invalid_urls)}")
print(invalid_urls[["unique_id", "pdp_url"]])

Invalid URLs: 0
Empty DataFrame
Columns: [unique_id, pdp_url]
Index: []

In [45]:
invalid_urls = invalid_urls["pdp_url"].unique()

print("Unique invalid URLs:", len(invalid_urls))
for url in invalid_urls:
    print(repr(url))

Unique invalid URLs: 0

In [46]:
import re

image_cols = [c for c in df.columns if c.startswith("image_url_")]

# Basic image URL pattern
pattern = re.compile(
    r"^https?://[^\s]+\.(jpg|jpeg|png|webp|gif|bmp|avif)(\?.*)?$",
    re.IGNORECASE
)

for col in image_cols:
    invalid = df[
        df[col].notna() &
        (df[col].astype(str).str.strip() != "") &
        ~df[col].astype(str).str.match(pattern)
    ]

    print(f"\n{col}: {len(invalid)} invalid URLs")

    if not invalid.empty:
        print(invalid[["unique_id", col]].head())

In [23]:
import re

pattern = re.compile(r"^https?://[^\s]+$", re.IGNORECASE)

for col in image_cols:
    invalid = df[
        df[col].notna() &
        (df[col].astype(str).str.strip() != "") &
        ~df[col].astype(str).str.match(pattern)
    ]

    print(f"{col}: {len(invalid)} invalid URLs")

In [24]:
price_cols = [
    "regular_price",
    "selling_price",
   
    "price_per_unit"
   
]

# Keep only columns that exist in the file
price_cols = [c for c in price_cols if c in df.columns]

# Rows where at least one price column is empty
empty_price_rows = df[df[price_cols].replace("", pd.NA).isna().any(axis=1)]

print(f"Rows with empty price fields: {len(empty_price_rows)}")
display(empty_price_rows[["unique_id", "product_name"] + price_cols])

Rows with empty price fields: 1761

,unique_id,product_name,regular_price,selling_price,price_per_unit
2660,1310867,"Pirina moka T 850, Farina, 1 kg",2.79,2.79,NaN
2737,13194252,"Rjavi trsni sladkor, Tims, 5 g x 1000",16.19,16.19,NaN
3229,16847275,"Aroma Bourbonske vanilije, Finesse, Dr. Oetker, 2 x 5 g",1.99,1.99,NaN
3354,18020378,"Vanilija cela, Kotanyi, 1 strok, 3 g",4.79,4.79,NaN
3535,15938627,"Ovseni kosmiči, Mornflake, 500 g",2.69,2.69,NaN
4125,20065011,"Kava, Loka, 2 x 250 g + džezva",9.89,9.89,NaN
4138,20153572,"Mleta kava, Loka, 2 x 250 g + skodelica",9.98,9.98,NaN
4141,20071736,"Božično darilno pakiranje, Illy, mleta kava 250 g + 2 skodelici",24.99,24.99,NaN
4750,18182837,"Jabolčni bistri sok, Trstenjak, 1 l",2.29,2.29,NaN
5320,19744992,"Whiskey, Jameson, 40 % alkohola, 3 x 0,05 l",12.99,12.99,NaN
5450,19756158,"Grenčica Pelinkovec Orange, Badel, 25 % alkohola, 0,7 l + 1 kozarec",19.39,19.39,NaN
6454,16026562,"Testenine, Vesuvio, Pasta di Gragnano, Gentile, ZGO, 500 g",4.49,4.49,NaN
6520,16026538,"Špageti, Pasta di Gragnano, Gentile, ZGO, 500 g",4.49,4.49,NaN
6778,13142452,"Tris tartufi, darilni paket, Zigante",13.99,13.99,NaN
8330,19677301,"Bonbnočki z igračo Water Gun, Johny Bee, 15 g",1.99,1.99,NaN
8575,17410909,"Lizike na stojalu, kolo, Chupa Chups, 200/1, stojalo KIT, 2,4 kg",74.67,74.67,NaN
9549,19596782,"Direct Magnezij 400 + D3, ""on the go"", Medex, 20/1",10.49,10.49,NaN
9753,16954696,"Kapsule Guarana natural energy, Medex, 30 kapsul",8.79,8.79,NaN
9859,19596793,"Instant napitek, Magnezij 400 in D3, Medex, 20/1",11.49,11.49,NaN
10270,1115587,"Prigrizek za pse Beef Stick z govedino, Vitakraft, 12 g",0.79,0.79,NaN
10401,13301376,"Prigrizek za mačke mini palčke z lososom, Vitakraft, 3x18 g",1.19,1.19,NaN
10403,13301388,"Prigrizek za mačke mini palčke s puranom, Vitakraft, 3x18 g",1.29,1.29,NaN
10605,18316313,"Mačja ovratnica proti zajedalcem z biocidom, Vitakratft, 35 cm",6.09,6.09,NaN
10606,16447539,"Insekticidna pipeta za mačke, Vetocanis",7.99,7.99,NaN
10607,17468993,"Igrača za mačke, miška vitak.za navij.35 cm",2.59,2.59,NaN
10609,17469004,"Lopatica za posip, Vitakraft, compact ultra, 29 cm",1.49,1.49,NaN
10610,16447587,"Mačja ovratnica, insekticid, Vetoc, 35 cm",5.89,5.89,NaN
10612,17468982,"Ovratnica, Vitakraft, elastika, zvonček",4.49,4.49,NaN
10622,17976264,"Posip za mačje stranišče Magic Clean, Vitakraft, 3,8 l",12.99,12.99,NaN
10626,1242299,"Bombažna pisana vleka, Vitakraft, 26 cm",2.69,2.69,NaN
10628,17976330,"Žoga, jež, Vitakraft, 10 cm",2.39,2.39,NaN
10629,17976341,"Piskajoči plastični jež, Vitakraft, fi 7,5 cm",2.59,2.59,NaN
10630,17468773,"Igrača za psa petelin, Vitakraft, latex, 15 cm",6.29,6.29,NaN
10632,18316302,"Biocidna pasja ovratnica proti zajedalcem, za odrasle pse in mladiče, Vitakraft, 60 g",6.79,6.79,NaN
10633,16968090,"Dvojno plastična posoda za pse, Vitakraft, 2x330ml",4.59,4.59,NaN
10634,17468883,"Dvostranska ovalna krtača za pse, Vitakraft, Pvc",7.49,7.49,NaN
10635,16789391,"Nastavljiv pasji povodec iz najlona, Vitakraft, 200 cm/25 mm",8.05,8.05,NaN
10637,16447551,"Insekticidna pipeta za pse, 2-10 kg, Vetocanis",8.29,8.29,NaN
10638,17468795,"Posoda za pse, Vitakraft, z gumi robom, različne barve, plastična, 735 ml",5.09,5.09,NaN
10639,16447575,"Insekticidna pipeta za pse, 20-40 kg, Vetocanis, 2/1",9.99,9.99,NaN
10640,17468949,"Igrača za pse, Vitakraft, 6 cm",4.59,4.59,NaN
10641,17976286,"Nogometna piskajoča žoga, guma moos, Vitakraft, fi 10 cm",3.39,3.39,NaN
10642,16447563,"Insekticidna pipeta za pse, 10-20 kg, Vetocanis",8.99,8.99,NaN
10646,16447599,"Insekticidna pasja ovratnica, Vetocanis",6.79,6.79,NaN
10650,17468894,"Krtača za pse, Vitakraft",4.19,4.19,NaN
10842,4786345,"Avokado, cena za kos",1.59,1.59,NaN
10844,4786361,"Mango, cena za kos",1.89,1.89,NaN
10845,13086488,"Mango, Ready to eat, cena za kos",2.89,2.89,NaN
10848,14834446,"Avokado, Ready to eat, cena za kos",2.89,2.89,NaN
10857,1525707,"Kokosov oreh, cena za kos",1.29,1.29,NaN
11007,17800137,"Solata kristalka, cena za kos",1.19,1.19,NaN
11012,20022690,"Slovenska solata kristalka, Frišno, Panvita, cena za kos",1.39,1.39,NaN
11013,20022701,"Slovenska solata trio, Frišno, Panvita, cena za kos",1.39,1.39,NaN
11019,20022712,"Slovenska mehka solata, Frišno, Panvita, cena za kos",1.39,1.39,NaN
11034,18664277,"Dolga kumara, kos",1.19,1.19,NaN
11073,17494319,"Cvetača, cena za kos",1.99,1.99,NaN
11449,17651533,"Zobna ščetka soft, Lumpi",0.69,0.69,NaN
11452,16742659,"Otroška zobna ščetka Elmex, 0-3 leta",4.69,4.69,NaN
11463,17908794,"Otroška zobna ščetka, Elmex, 3-6 let",4.69,4.69,NaN
11464,153699,"Otroška zobna ščetka Oral B Stages, 5-7 let",3.19,3.19,NaN
11465,16646909,"Otroška zobna ščetka Aquafresh Little Teeth, 3-5 let",4.19,4.19,NaN
11466,358035,Otroška zobna ščetka Signal Kids,3.49,3.49,NaN
11468,16735225,"Otroška zobna ščetka Aquafresh Big Teeth, 6+ let",4.19,4.19,NaN
11470,18175621,"Otroška zobna ščetka, Oral B, junior 6-12 let",3.19,3.19,NaN
11473,17701142,"Otroška zobna ščetka Youth Smile, 6+ let, Colgate",3.49,3.49,NaN
11475,15923179,"Otroška zobna ščetka Elmex Junior, 6-12 let",4.69,4.69,NaN
11489,18969806,"Zobna ščetka, Baby CS 4260, Curaprox",6.49,6.49,NaN
11499,18388073,"Zobna ščetka Advance Kids, Aquafresh, 9-12 let",4.19,4.19,NaN
11548,19984478,"Otroška zobna ščetka, Super Mario, Signal",5.99,5.99,NaN
11552,19985014,"Otroška zobna pasta, Junior, 6-12 let, Oral-B",3.19,3.19,NaN
11567,19985003,"Otroška zobna pasta, Kids, 0-6 let, Oral-B",3.19,3.19,NaN
11670,13512984,"Grizalo s ščetko, Mam",6.89,6.89,NaN
11672,17368485,Držalo za dudo Mam Clit It,5.99,4.59,NaN
11673,13134724,Grizalo Mam Cooler s hladilno tekočino,5.79,5.79,NaN
11674,17035476,"Silikonska duda Perfect Night, 0+ m, Mam, 1 kos",6.89,5.49,NaN
11675,19782979,"Grizalo Lucy polžek, Mam",6.79,6.79,NaN
11677,13296812,"Silikonska duda Perfect, 6+ m, Mam, 1 kos",6.89,5.49,NaN
11680,17035488,"Silikonska duda Perfect Night, 6+ m, Mam, 1 kos",6.89,6.89,NaN
11682,13296820,"Silikonska duda Perfect, 0-6 m, Mam, 1 kos",6.89,5.49,NaN
11686,110907,Otroška zobna ščetka Mam,3.99,2.00,NaN
11687,697371,"Prva otroška zobna ščetka, Mam",3.29,3.29,NaN
11688,12262824,"Lonček Learn to Drink, Mam",6.79,6.79,NaN
11689,19029850,"Lonček z ustnikom, 6+, roza, Avent, 200 ml",8.49,8.49,NaN
11690,11101140,"Duda za stekleničko, Ultivent X, Mam",5.99,5.99,NaN
11691,19472413,"Tetra plenice, medo, 48013, Bubaba",12.59,12.59,NaN
11692,19472402,"Tetra plenice, zajček, 48037, Bubaba",12.59,12.59,NaN
11693,19029861,"Lonček z ustnikom, 6+, modra, Avent, 200 ml",8.49,8.49,NaN
11694,698367,"Rokavica zajček za ustno nego, Mam",7.59,7.59,NaN
11695,15819554,"Aspirator PhysioClean, Chicco",8.75,8.75,NaN
11696,11101172,"Škatlica za dudo, Mam",7.99,7.99,NaN
11697,17309298,"Trak za merjenje toplote tekočine v steklenički, Termoband",11.99,1.20,NaN
11698,19265098,"Kovinski pribor za hranjenje, Tommee Tippee, 3/1",9.59,9.59,NaN
11699,18169019,Kahlica Relax OK Baby,7.99,7.99,NaN
11700,11101148,"Steklenica Mam Baby Bottle, 330 ml",5.99,4.59,NaN
11701,110687,"Steklenička Mam Anti-colic, 260 ml",7.99,6.15,NaN
11702,11101152,"Steklenička Mam z mehkim nastavkom, 220 ml",5.75,5.75,NaN
11703,11101144,"Duda za stekleničko Ultivent 3, Mam",5.99,5.99,NaN
11705,16594330,"Steklena steklenička Mam 0+ mesecev, 170 ml",10.99,8.79,NaN
11706,16594342,"Steklena steklenička, 2+ mesecev, Mam, 260 ml",12.99,9.99,NaN
11707,18426080,"Lonček s slamico 12+, Avent, 300 ml",10.99,10.99,NaN
11708,110719,"Steklenička Mam Ultivent, 160 ml",6.99,5.38,NaN
11709,19669407,"Plastična steklenička, Natural Response, Avent, 260 ml",10.99,10.99,NaN
11712,17654655,"Steklenička Mam Easy Start Anti Colic, 320 ml",7.99,6.39,NaN
11713,11101136,"Duda za stekleničko Ultivent 2, Mam",5.99,5.99,NaN
11714,19669363,"Steklenička, Natural Response, Avent, 120 ml",12.99,12.99,NaN
11715,11101160,"Lonček Mam Learn to Drink, 190 ml",6.99,6.99,NaN
11716,18426091,"Lonček s slamico 12+, Avent, 300 ml",10.99,10.99,NaN
11718,11881252,"Ultrazvočna zaščita proti komarjem, Chicco",9.99,9.99,NaN
11719,18361349,"Nočna posoda Stars, bela, Keeper",12.99,12.99,NaN
11720,1515955,"Zložljiv slinček Roll-On, 7+ mesecev, Tommee Tippee",5.59,5.59,NaN
11722,19775338,"Športni voziček, Simple grey 48532, FreeON",79.99,79.99,NaN
11723,18347351,"Nastavek za wc Stars, siva, Keeper",9.99,9.99,NaN
11725,19902640,"Glasbena igralna podloga, Playgro",44.99,44.99,NaN
11726,18116597,"Prenosna UZ zaščita, Chicco",9.99,5.00,NaN
11728,19995629,"Igrača magnetna abeceda, 48/1",8.99,2.70,NaN
11729,19627219,"Prijatelji za izdelavo milnih mehurčkov, Bubbletastic",3.49,3.49,NaN
11730,15177451,"Set posodic s pokrovon in žličko, 4+ mesece, Tommee Tippee, 2 kosa",8.99,8.99,NaN
11731,19995662,"Igrača magnetne številke, 48/1",8.99,4.50,NaN
11732,19578819,"Otroška tablica, Moj prvi atlas",21.99,21.99,NaN
11733,17284727,"Plastelin lonček, Play Doh",2.29,2.29,NaN
11734,18426422,"Igrača, Čudežno jajce",3.49,1.05,NaN
11735,19943686,"Igrača, Deluxe set izstreljevalnik, Beyblade",29.99,17.99,NaN
11736,19915911,"Interaktivni ljubljenček Magicals, Bitzee",42.49,42.49,NaN
11737,19770040,"Kocke, Narcise 40747, Lego Flowers",14.99,10.49,NaN
11738,19962697,"Kocke, zajec, Lego Creator",20.99,14.69,NaN
11739,19578841,"Otroška tablica, Bistroumna sovica",21.99,21.99,NaN
11740,19578830,"Otroška tablica, Moja prva abeceda",21.99,21.99,NaN
11741,18162307,"Potovalna igra, Človek ne jezi se, Purple Cow",7.19,7.19,NaN
11742,19564988,"Igralne karte, E-Power avtomobili",3.19,3.19,NaN
11743,20040186,Magnetna mizica za risanje,9.99,6.99,NaN
11744,19804978,"Set figuric, Freak marbles, modra, 18457, World Alive, 6/1",24.99,12.50,NaN
11745,17894905,"Ken Fashionistas, Barbie",22.99,22.99,NaN
11746,19937754,"Punčka Flower Hair z glavnikom in dodatki, Steffi",14.99,4.50,NaN
11747,20098407,"Plišasta igrača, medvedek, 18 cm",8.59,8.59,NaN
11748,19962367,"Kocke, Šopek rož, Lego Botanik",64.99,45.49,NaN
11749,19769143,"Kocke, Kombi s hamburgerji 60404, Lego City",21.99,15.39,NaN
11750,19769253,"Kocke, Astronavtski gradbeni robotski oklep, 60428, Lego City",9.99,6.99,NaN
11751,19864593,"Kocke, Kiosk s smutiji na plaži 42625, Lego Friends",21.99,15.39,NaN
11752,19770172,"Kocke, Glasbena zabava s karaokami, Lego Friends",21.99,15.39,NaN
11753,19963164,"Kocke, Avtomehanična delavnica F1, Lego City",79.99,55.99,NaN
11754,19943796,"Kreativi set, Character Art set, Gabbys Dollhouse",4.99,3.49,NaN
11755,20095961,"Kocke, Marjetice, Lego",14.99,14.99,NaN
11756,17785294,Družabna igra Angleščina za otroke,19.49,19.49,NaN
11757,19936621,"Set za izdelavo zapestnic in obeskov, Make It Real",13.99,1.40,NaN
11758,19714300,"Družabna igra, Hedbanz lightspeed",19.99,10.00,NaN
11759,19122169,"Kreativni set, prijateljica, Nebulous Stars",9.99,9.99,NaN
11760,18162329,"Potovalna igra, Vislice, Purple Cow",7.19,7.19,NaN
11761,18629086,"Miselna igra Zajčki skačejo, 60 izzivov, Smart Games",23.69,11.85,NaN
11762,19904942,"Magnetna igrača, 66/1",39.99,12.00,NaN
11763,19937787,"Mikrofon, Simba",24.99,7.50,NaN
11764,405751,Karte šnops,4.29,4.29,NaN
11765,19864056,"Igrača, 65. rojstni dan, Barbie",19.99,19.99,NaN
11766,20019411,"Kocke, Angel, Lego Disney",69.99,48.99,NaN
11767,19649855,"Kocke, Mala morska deklica, Lego Disney",23.99,16.79,NaN
11768,19864659,"Kocke, Simba mladi levji kralj 43243, Lego Disney",21.99,15.39,NaN
11769,19870006,"Set mini golov, 95 x 70 x 48 cm, 2/1",27.99,19.59,NaN
11770,19538741,"Igrača, Jajce Dino",3.99,0.40,NaN
11771,19729589,"Interaktivna igrača, Medvedek Bubica",49.99,15.00,NaN
11772,19941443,"Set za izdelovanje, Pen Creator Studio",37.99,37.99,NaN
11773,20029541,"Kocke, Dodge Challenger SRT Hellcat, 77237, LEGO",27.99,19.59,NaN
11774,17865023,"Igrača Slimy v lončku, Original, 80 g",4.59,4.59,NaN
11775,197019,"Karte Tarok, 54 kart, dve vrsti",10.99,10.99,NaN
11776,18513196,"Družabna igra, Igra življenja",47.29,33.10,NaN
11777,18162351,"Potovalna igra, Bingo, Purple Cow",7.19,7.19,NaN
11778,17651182,"Družabna igra, država, mesto in vas",30.99,30.99,NaN
11779,16978768,"Kreativni set, Sončni sistem in planetarij",12.99,12.99,NaN
11780,19500584,"Miselna igra, Parkiraj vozilo, 60 izzivov, Smart Games",21.09,10.55,NaN
11781,16793129,"Plastelin s stiskalnico, Unikatoy",13.99,13.99,NaN
11782,19941630,"Družabna igra, Resnica ali laž",34.99,34.99,NaN
11783,19936835,"Igralni set, Looping z avtomobilčkom",19.99,6.00,NaN
11784,17890095,"Plišasta igrača, Racman Jaka, 20 cm, Disney",17.49,8.75,NaN
11785,17225514,"Set družina, Steffi",19.99,11.99,NaN
11786,18447440,Figura Letrabots,2.99,0.30,NaN
11787,20047518,"Garažna hiša, 46 x 19 x 43 cm",29.99,15.00,NaN
11788,19937952,Dojenček New Born Baby,22.99,13.79,NaN
11789,20019334,"Kocke, Avtomobil za prijateljsko potovanje, Lego Friends",19.99,19.99,NaN
11790,20079606,"Igralne kocke, motor, Engino",21.99,11.00,NaN
11791,19962686,"Kocke, Srednjeveški zmaj, Lego Kreator",64.99,45.49,NaN
11792,19560688,"Kocke, Lianina soba, Lego Friends",20.99,14.69,NaN
11793,19769864,"Kocke, Orožarna 21252, Lego Minecraft",21.99,15.39,NaN
11794,20096522,"Kocke, Policijsko vozilo za prevoz zapornikov, Lego",20.99,20.99,NaN
11795,19962917,"Kocke, Veterinarska klinika, Lego Friends",49.99,34.99,NaN
11796,19962840,"Kocke, Prijatelji na plaži, Lego",14.99,10.49,NaN
11797,19963329,"Kocke, Dirkalnika Williams Racing, Lego City",19.99,13.99,NaN
11798,19962928,"Kocke, Drevesna hiška, Lego Friends",74.99,52.49,NaN
11799,19962444,"Kocke, Pustolovski vlak, Lego Duplo",79.99,55.99,NaN
11800,20019708,"Kocke Lego, mikrobojevnik",15.99,15.99,NaN
11801,20096181,"Kocke, Kombajn s kolesi John Deere, Lego Technic",9.99,9.99,NaN
11802,17894641,"Punčka Fashionistas, Barbie",22.99,22.99,NaN
11803,19963428,"Kocke, Zeleni zmaj, Lego Ninjago",20.99,20.99,NaN
11804,19962466,"Kocke, Drevo za skladanje in uravnovešanje, Lego Duplo",19.99,13.99,NaN
11805,19962994,"Kocke, Mini orhideja, Lego Botanik",31.99,31.99,NaN
11806,20096588,"Kocke, Superavto, Lego City",9.99,9.99,NaN
11807,20057476,"Kocke, Ferrari, Lego Technic",59.99,59.99,NaN
11808,19937732,"Punčka s psom, Steffi",14.99,7.50,NaN
11809,17885336,"Sestavljanka, 3 x 49 delna, Ravensburger",13.79,13.79,NaN
11810,19937908,"Želvica za v vodo, ABC",9.99,5.00,NaN
11811,19769765,"Kocke, Skrb za čebele in čebelnjake 10419, Lego Duplo",21.99,15.39,NaN
11812,11180380,"Karte, Original, Uno",10.99,5.50,NaN
11813,1368383,Karte črni peter,4.99,4.99,NaN
11814,16793105,"Mini plastelin v lončku, Unikatoy, 4/1",6.99,6.99,NaN
11815,5083566,"Družabna igra, Activity",42.99,42.99,NaN
11816,19637123,"Igra Potovalnih 50, 7 razlik",7.99,5.59,NaN
11817,66639,"Igralne karte, Remi/Bridge",11.99,11.99,NaN
11818,19318065,"Igra, Berem, pišem in se igram",12.99,12.99,NaN
11819,19938029,"Set treh reševalnih vozil, Dickie",7.99,2.40,NaN
11820,11426540,"Družabna igra, Activity Junior, Piatnik",31.99,31.99,NaN
11821,19637145,"Igra Potovalnih 50, Labirint",7.99,5.59,NaN
11822,18162296,"Potovalna igra, Šah, Purple Cow",7.19,7.19,NaN
11823,18860906,"Igralne karte, Uno Flip",13.99,13.99,NaN
11824,18162340,"Potovalna igra, Potapljanje ladjic, Purple Cow",7.19,7.19,NaN
11825,18629108,"Miselna igra Zabava s pingvini, 60 izzivov, Smart Games",23.69,11.85,NaN
11826,18545069,"Kreativni set, lovilec sanj, Nebulous Stars",12.99,3.90,NaN
11827,20057685,"Kocke, Lamborghini Revuelto, Lego",52.99,37.09,NaN
11828,19938018,"Walkie Talkie, Dickie",19.99,10.00,NaN
11829,19250478,"Igrača, Hrček na baterije",9.99,5.00,NaN
11830,19943708,"Izstreljevalnik, Beyblade",11.99,1.20,NaN
11831,19936890,"Mini set za kuhanje, 33 cm",17.99,9.00,NaN
11832,19112925,"Ročni metalec, Elite 2.0 volt, Nerf",20.99,14.69,NaN
11833,19943741,"Metalec, N serija Ward, Nerf",8.99,8.99,NaN
11834,19176538,"Avto z mehkimi kockami, Clemmy",22.99,22.99,NaN
11835,19943851,"Začetni set, Beyblade",15.99,15.99,NaN
11836,19935905,"LCD barvna tablica, Unicorn, Free 2 Play",19.99,19.99,NaN
11837,19941718,"Igrača Deluxe, Rubble's bulldozer, Rubble & Crew",59.99,41.99,NaN
11838,19941586,"Igrača, Space Rocket, Astro Venture",42.99,30.09,NaN
11839,19943697,"Arena, Beyblade",18.99,13.29,NaN
11840,19943730,"Metalec, N serija Flex, Nerf",6.99,4.89,NaN
11841,19941817,"Igrača, Hiša praznovanj, Gabbys Dollhouse",99.99,69.99,NaN
11842,19935916,"LCD barvna tablica, Dinozaver, Free 2 Play",19.99,19.99,NaN
11843,19941729,"Igrača Deluxe, Wheeler's truck, Rubble & Crew",59.99,41.99,NaN
11844,19936879,"Kuhinja z dodatki, 70 cm",29.99,15.00,NaN
11845,19941696,"Figure Build-it pack, Rubble & Crew",15.99,15.99,NaN
11846,20047529,"Otroška kuhinja z zvokom, 50 x 25 x 14 cm, modra",21.99,15.39,NaN
11847,19936566,"Set za izdelavo zapesnic, Mini Juicy Couture, Make It Real",14.99,1.50,NaN
11848,19927366,"Klobuk, Squishmallows",17.99,12.59,NaN
11849,20138061,"Igrača s presenečenjem, Surprise Fifa Ballers",16.99,16.99,NaN
11850,19936555,"Dnevnik z bleščicami, Make It Real",15.99,11.19,NaN
11851,20047452,"Otroška kuhinja z zvokom, 50 x 25 x 14 cm, roza",21.99,11.00,NaN
11852,19614729,"Družabna igra, Twister Junior",29.99,29.99,NaN
11853,20142095,Namizni elektronski nogomet,24.99,24.99,NaN
11854,19437237,"Družabna igra, Besedni izziv, Zanzoon",30.99,30.99,NaN
11855,19565010,"Igralne karte, Poker classic",3.99,3.99,NaN
11856,17133457,"Lesena družabna Igra, Človek ne jezi se",21.99,21.99,NaN
11857,18036590,"Miselna igra, IQ Puzzler PRO, Smart Games",13.39,13.39,NaN
11858,19498749,"Družabna igra, Penalty Shootout",15.99,15.99,NaN
11859,19943763,"Družabna igra, Prst resnice",37.99,26.59,NaN
11860,19927454,"Družabna igra, Strava glava",27.99,19.59,NaN
11861,19948235,"Družabna igra, Monkey Palace, Lego",49.99,34.99,NaN
11862,19941153,"Družabna igra, Očala nemogoč pogled",25.99,13.00,NaN
11863,19697021,"Namizna igra, nogomet, KingSport",12.49,12.49,NaN
11864,19351313,"Družabna igra, Fanzone",44.99,31.49,NaN
11865,19944379,"Družabna igra, Duholov",49.99,34.99,NaN
11866,19936114,"Družabna igra, Akcija NLP",21.99,21.99,NaN
11867,18036601,"Miselna igra IQ Fit, Smart Games",13.39,13.39,NaN
11868,19730841,"Družabna igra, Balkanopoly",34.99,3.50,NaN
11869,17571607,"Otroške puzzle iz pene, Unikatoy, 9/1",15.99,11.19,NaN
11870,19944126,"Družabna igra, Kokošji Limbo",39.99,27.99,NaN
11871,17434724,"Igralni set Otroški laboratorij, Znanost s kristali, 4M",15.99,15.99,NaN
11872,18629119,"Miselna igra Veveričke nabirajo želod, 60 izzivov, Smart Games",23.69,11.85,NaN
11873,20040142,"Magnetna igrača, 105/1",27.99,19.59,NaN
11874,19936813,"Igralni set, Parkirišče z dvema avtomobiloma in letalom",21.99,11.00,NaN
11875,19500705,"Miselna igra, IQ Six Pro, 120 izzivov, Smart Games",12.99,12.99,NaN
11876,16460013,"Igrača Formula, z zvokom, 25 cm, Unikatoy",9.99,9.99,NaN
11877,20019290,"Kocke, zavetišče za pande, Lego",29.99,29.99,NaN
11878,20149923,"Kocke, Kylian Mbappe, Lego",30.99,30.99,NaN
11879,20057531,"Kocke, Snowspeeder s pogonom na Silo, 75414, LEGO",52.99,37.09,NaN
11880,20149956,"Kocke, FIFA World Cup, Lego",184.99,184.99,NaN
11881,19963307,"Kocke, Remiks helikopter, gasildko vozilo in podmornica, Lego City",59.99,41.99,NaN
11882,20019488,"Kocke Lego City, pregon s policijskim motorjem",9.99,9.99,NaN
11883,20069841,"Kocke, Gobja hiša, Lego",49.99,34.99,NaN
11884,20019323,"Kocke Lego Friends, zabava na bazenu",9.99,6.99,NaN
11885,20057454,"Kocke, Retro telefon, 31174, LEGO",31.99,22.39,NaN
11886,20096566,"Kocke, Igričarski dirkalnik, Lego City",9.99,9.99,NaN
11887,20096643,"Kocke, Transportno vozilo za motorje, Lego City",20.99,20.99,NaN
11888,20149967,"Kocke, Lionel Messi, Lego",84.99,84.99,NaN
11889,20079595,"Igralne kocke, kamion nakladač 3v1, Engino",15.99,8.00,NaN
11890,19963483,"Kocke, Interceptor, Lego Star Wars",44.99,44.99,NaN
11891,19769638,"Kocke, Sončnice, Lego Lel Flowers",14.99,10.49,NaN
11892,19775286,"Kocke, Šopek vrtnic, 10328, Lego Icons",64.99,45.49,NaN
11893,19864494,"Kocke, Gabijina hišica za punčke 10795, Lego",15.99,11.19,NaN
11894,20057740,"Kocke, Pustolovščina v akvariju z morsko deklico Gabi, 11204, LEGO",20.99,14.69,NaN
11895,20069929,"Kocke, Modularna vesoljska postaja, Lego",99.99,69.99,NaN

In [48]:
import pandas as pd

# Treat empty strings as missing values
promo_price = df["promotion_price"].replace("", pd.NA)
promo_desc = df["promotion_description"].replace("", pd.NA)

# 1. Promotion price present but promotion description missing
price_no_desc = df[
    promo_price.notna() & promo_desc.isna()
]

# 2. Promotion description present but promotion price missing
desc_no_price = df[
    promo_desc.notna() & promo_price.isna()
]

print("Promotion price present but description missing:", len(price_no_desc))
display(price_no_desc[["unique_id", "product_name", "promotion_price", "promotion_description"]])

print("\nPromotion description present but price missing:", len(desc_no_price))
display(desc_no_price[["unique_id", "product_name", "promotion_price", "pdp_url","promotion_description"]])

Promotion price present but description missing: 8

,unique_id,product_name,promotion_price,promotion_description
5381,975419,"Kanadski Whiskey, Canadian Club, 40 % alkohola, 0,7 l",18.69,NaN
5882,34755,"Sivi pinot, vrhunsko belo vino, Jeruzalem Ormož, 0,75 l",6.79,NaN
15615,20014827,"Odcejalnik solate Delight, Delimano, 4 l",13.99,NaN
16347,19558450,"Gugalnik, siv, Bologna",132.30,NaN
16354,19974789,"Gugalnik, mint zelen, Bologna",132.30,NaN
16356,20101820,"Gugalnik jajček, 153 x 65 x 111 cm",125.99,NaN
16368,20108087,"Gugalnik, temno moder, Bologna",132.30,NaN
16453,19611809,"Okrogel bazen, Avenli, 450 x 122 cm",279.99,NaN

Promotion description present but price missing: 2439

       unique_id  \
36       5123130
53       5123122
73      17164308
80      19979036
95      19744891
101       301643
178      5120904
181     17721109
201     19744913
228     19463279
233     19304194
235     19463268
287     19462507
289     19462529
294     19462540
310     19799869
311     20077996
324     20010129
331     20010107
334     20010118
335     20025050
350     18459713
355     11395392
357       278199
371       876971
375       358947
380     18459702
385     17467369
392     19085433
455     19898122
457      1161859
474     17180304
479     15155427
489     19217645
518     15836796
520     15836808
536     19304328
558       261199
573     16644803
611     15836820
616     19994904
634     19589689
703      1336203
707      8886672
716      1336239
718      8423688
719      8886648
727     19697045
728      1336179
729      5068481
774     19800082
798     19832343
804     19625249
822     17572648
838     19876938
844     19397073
892       497403
900     19979014
952     18633189
975     19388113
976     19621009
988     19979003
992      8423712
993     18462557
1001    18291087
1011      876827
1047     5346561
1050     5248376
1065       74979
1077    14735602
1084    19300957
1085      287731
1103    17039996
1108    17039960
1116    17039984
1119    17039936
1122    17039948
1124    18924653
1126    17040008
1130    16841157
1132    17039972
1136    19790841
1184    19369326
1235    18384399
1237    18867733
1241    17591393
1242    19993414
1248    17794581
1254      771175
1256     1115263
1265    16893012
1271    19247886
1278    19742402
1281      698559
1287    17460439
1292      771067
1294    18885821
1295      771283
1296      802139
1298    17631897
1299    14239509
1300    18733945
1301      771227
1302    17687529
1303      770959
1305    18285649
1307      771119
1308    19157386
1310      899607
1312    17959815
1317    14239709
1324    16213089
1340    19682125
1349    18633102
1376    19235373
1383    19898293
1385      984563
1386      742791
1387    16269560
1399    17230457
1403    16095718
1411    15875003
1413    15575287
1416    15875015
1417    19471837
1420    15580111
1441    19678029
1449    17955658
1450    18579084
1455    18579106
1458    20067464
1459    19678018
1520    18916794
1534      771147
1542    19157397
1543    20002636
1563    19311033
1564    19944730
1573     5245303
1575    19872705
1577    18118129
1583    19624878
1586    19525981
1598    20064329
1603    19624889
1607    20124063
1612    18285597
1623    20002658
1625    20124085
1630    20129233
1636    20124074
1650    20129244
1678    18997293
1684    16166927
1693    19519697
1707    17976029
1712     1532339
1714    19712729
1763     8669803
1774    16169396
1796    17573917
1819    17907072
1828    17907094
1845    11919312
1869    18301417
1953      510491
1964    18840121
2007    14426837
2036    19999429
2042    20070564
2050     8047996
2056    20079041
2064    20079052
2129    17698295
2201    18390918
2225    19073917
2238    20018928
2240    20018917
2250      119747
2295    19780017
2307    19959313
2344      445683
2378      543063
2409      183703
2413     1393167
2423     5074136
2431    18064485
2434    18412008
2446     1391323
2458    19605281
2475    19817853
2490    19817748
2492    14779335
2502    18780668
2510    20118994
2517    20145099
2519    20122929
2523    20145088
2525    17771949
2538    20127434
2539    20145121
2545    20127423
2549    20127445
2553    14779359
2555       82079
2557      181663
2563    20123028
2580    20122940
2586    20126945
2587    20123006
2588       23875
2599    20160330
2600       29143
2618    19975109
2636    18367685
2650      781779
2657       26983
2671       23851
2692    20160319
2721    16363452
2733    19429393
2734    13893009
2739    18760766
2741    19181353
2749    13789528
2750    17629486
2753    13317660
2766    17839109
2771     7918819
2774       83687
2780     1436803
2789     1436815
2791    18436281
2806      312791
2807       83635
2821      284991
2824      867903
2830      489155
2835    10701228
2836      378651
2838    16877323
2839    18033481
2842    19163413
2849    19896380
2858    19896369
2859    19998886
2878       29411
2889    18535790
2891    18790037
2897    19124153
2899     5229836
2902      208439
2906    17661176
2915    15878921
2917    17661187
2921    19759628
2933    18434877
2938    18434866
2966      534195
3171    19999381
3323    20102984
3324    20103006
3325    19804393
3339    20102995
3373    15884142
3393      204339
3394    16607809
3422    20074418
3429    20074429
3530    17435709
3538    19403706
3548    19403717
3560    19964598
3563    19964587
3565    17609501
3569    19246726
3571    19133745
3572    17609479
3574    19964609
3575    19967385
3577    18985925
3586    17235282
3592    16116711
3606    16596165
3618    16327959
3633    20042397
3641    19967396
3647    20042386
3653    20102401
3661    20102412
3668     5319571
3677    17949045
3691    17425283
3692    19600729
3693    19639167
3698    19187103
3701    17476865
3736    16409797
3753    17665202
3759    18145145
3760    17665191
3778    17983373
3782    19602549
3786    20049950
3793    20148138
3800    20148149
3801    19799085
3802    19799074
3804    19967913
3805    20114839
3806    20114828
3813    19401185
3819    18145123
3822    15236488
3826    17660864
3830      896175
3831    20042130
3833    18559798
3837    17660897
3839    20042119
3845    17665213
3846    17665290
3849    19144325
3851    19086909
3852    16795409
3859    19144314
3866    19507629
3867    19796505
3873    19907373
3883    19900601
3884     1136943
3886    17576369
3906       28867
3923    20123893
3925    20123882
3928    20123871
3929     5324962
3941     1380387
3947    14400664
3960     5306466
3961      755083
3963       83335
3967    19843077
3969     1046931
3970    18591762
3982      256039
3986    17774709
3993    19617983
4002    19633517
4025    14471945
4027    19931581
4029    14471957
4030    14471969
4031    19931603
4034    18730202
4041    19618005
4042    19931592
4055    19216853
4058    18316646
4066    19469745
4070     1380399
4072    19686309
4077    19846300
4083    18228177
4089    19931614
4090    19931625
4096    19900565
4098    19360513
4104    20010338
4112    17879981
4120    20010327
4124    19919181
4130    19612129
4136    19119181
4137    18242285
4138    20153572
4142    20042002
4143     8821268
4151     8821280
4154    17582450
4155    20071541
4160    20071519
4163    20157014
4165    20157003
4168    20071530
4173    19919169
4194    14261805
4196     7371776
4204      199307
4209    17773227
4212    17773040
4214    19210161
4225    16854981
4229    19210150
4237      604835
4242    15192887
4251       44731
4262    19213477
4266     1284315
4273    20041825
4277    17773150
4278    18929406
4286    17773106
4318    17153752
4321      199271
4338    19919393
4348    17773568
4350    17773546
4359    18274258
4380     1231435
4381    18216297
4391     4685872
4392    17373741
4405    17604122
4412    18740786
4414    17373422
4415    18809069
4420    19117865
4425    19563746
4429    19563735
4433    19863994
4436    19136881
4438    19563757
4451     1362207
4453    17858127
4454    17728080
4455     1362219
4456    17728113
4457    12168692
4460    17743010
4475    18739725
4482    19811045
4496    19811078
4497    19995686
4498    19995697
4518    19484294
4526      365299
4527       30623
4528      873419
4530    17702079
4534    17702101
4537    17702090
4539      873431
4540      873443
4546    18166185
4554    19314648
4555    18087009
4565    19486601
4570       31991
4579    18739666
4583      335767
4584      511895
4590    18484657
4598    19976462
4599    19976473
4602    19465912
4604    19976451
4608    16394381
4612    16638953
4622    19136914
4623    19465945
4629    19902089
4637    20159277
4638    16638905
4641    16638893
4642    16638941
4644    19816845
4645    19948681
4646    19945198
4647    16638917
4648    19976440
4655    18484635
4657    16638929
4659    16651325
4660    19945176
4664    19465923
4667    19465934
4678      172087
4700    19334402
4712    18482331
4713    20149835
4714    19642625
4720    19314828
4735    15149923
4755    15149935
4779    15795595
4799    17855525
4803    17855514
4822    19066782
4825    13776371
4838      429967
4840    16029673
4873    19996325
4884    20022808
4891      876155
4900    18739537
4904    18739559
4905    18739581
4925    20002340
4976    19816423
4977    19816412
4978    20105417
4981    16605525
4989      489383
4992      388883
4993    14882367
5005    19643446
5007    17387261
5009    19816885
5011    18506067
5013    19971813
5018    19157501
5021    19066760
5022    19157490
5029    19885798
5034    19885149
5036    20109683
5037    20023538
5044    19990742
5046    20109694
5052    19885809
5053    19379581
5054    19990753
5064    19816434
5065    19816445
5066    18194389
5069    18194411
5073       23539
5089    11612064
5097    16605549
5100    17196441
5104    19722665
5105       83891
5107       90819
5126    20112262
5129    19617670
5133    19617648
5135    19617681
5136    19822636
5150    19828422
5151    18424957
5154    17942781
5160    18721938
5171    19605817
5182    19622913
5186    12586788
5187    18741353
5190    20101934
5219      313163
5239    19114445
5240    14900199
5247    18099633
5259     7495244
5260    10943388
5264      806559
5267     8655544
5272    17976694
5274    18432001
5278    14463697
5284      976087
5285    16716057
5286    10957828
5287     9798908
5291    19670006
5293     7369604
5300    10926904
5305    20157338
5327    19514425
5357    19611929
5359    11196692
5385      863955
5388    19402192
5423    16809546
5428    18806521
5429    18806510
5431    16809558
5432    16994592
5433    17371194
5436    18053148
5438    17371205
5439    16809570
5447      117831
5460      750943
5523    19611962
5534    19611918
5541    19611940
5549    19974345
5550    20012779
5551    19611973
5556    10939748
5563      274567
5570    20016968
5584    19611951
5597      118623
5601    20016957
5602    19828367
5603    20016979
5616    20142203
5618    20142192
5655      258863
5659    19589306
5660    19589317
5665      472355
5666    20021205
5684    20021194
5691    20021183
5696    20007549
5750    19941382
5769       24387
5771    19945740
5776    19157102
5795    12206832
5800      130491
5802    19157069
5815      835227
5821      130455
5825    14441764
5857      493339
5858      228711
5861    19157058
5870    16503977
5872    19787716
5874     7840664
5877       34695
5878    18489837
5885     5079357
5889    14000867
5890      575603
5894      192323
5896    17860510
5901    14943417
5904    18489881
5906    19527670
5910    10926752
5918    16503965
5920     5230612
5926    17494275
5933    15463427
5939       24615
5940    19768297
5942    19877833
5949    20087144
5952      839855
5955       24627
5959    19941130
5962    18665737
5976    15942379
6004    20101737
6006     5490760
6010    18528655
6011      835215
6014    19974334
6015      173031
6021    17860521
6024    19046077
6028    19495238
6029    19667120
6033    19495249
6038    15834752
6039    17883194
6043    19670145
6077    19273169
6114      835239
6115      498771
6123    13957268
6124    18695130
6127      681055
6132    18695141
6137    18489859
6147    15258911
6151    19788242
6155    17494242
6156    19601342
6159    19669870
6167     1235491
6173    19493892
6175    18020313
6176      221591
6187    19161273
6209    19157091
6218      615299
6233      190487
6237    19046529
6244      577611
6247      647931
6249    18636453
6253    19670123
6255    18489826
6258    18528721
6268    16891752
6274    17883205
6277    18489848
6282    17883227
6283    20064975
6284     7729136
6293    19947733
6294    18528677
6297      577555
6299     5242302
6307      498715
6319    19667131
6321     1395639
6324    14732264
6365       27231
6372       92335
6379    15454481
6382    15454489
6383    15454473
6387    17405582
6389    17405637
6391    15454465
6395       27243
6402      190883
6416    19634340
6460    19933189
6464    19634439
6465    19634428
6466    19634494
6467    19634472
6474    18647417
6482    19495216
6491    20000049
6493    18647329
6500    15525149
6505    19046496
6508    18862316
6515    20000071
6519    20024463
6521    20000027
6524    19634406
6526    20000016
6535    19634329
6538    19167823
6542    19634384
6543    19634362
6552    18862327
6559    20105738
6576    19167713
6578    19634505
6579    19167834
6613    19167757
6616    19167724
6617    19167702
6620    19167669
6633    19167801
6634    19167812
6637    20105727
6642    18574806
6653    19759617
6661     5076874
6665       28555
6670      104619
6677    12068208
6690    17755257
6696    19666581
6698    16722441
6706    19085839
6707    19405641
6723    19998864
6731     5318815
6732     5066312
6742     5066300
6768     8811461
6847       32927
6850    18235892
6853    17770229
6855    19745933
6860    19745911
6862    19745900
6877      647595
6881    19745889
6885    19745922
6887     5345027
6902    19122534
6911    19983863
6922    18572645
6924    18572667
6926    19122545
6939    19122523
6949     5304270
6953      261951
6954     5066632
6959    16310857
6960     5230452
6962     5076322
6966    14976083
6972    17792507
6973      229707
6979    17558281
6981    19123218
6988    16310869
6994    19016187
6999    19549197
7000    18087945
7001    19123273
7003    19905206
7006    19090806
7007    10920032
7009    19123262
7010    19905217
7015    19684269
7016    19507675
7017      220079
7019     6007386
7023    10920000
7026    17183909
7030    19207413
7034    19785174
7037    16604109
7039    19886502
7042    19090795
7051    19905195
7053    19549175
7054    19983328
7057    19983350
7061    19016198
7063    20037575
7064    20037886
7065    19507686
7066    19942009
7069    16604085
7070    19507697
7073    19983339
7074    20070482
7076    16209664
7079    20140104
7090    17865453
7091    19887537
7095    19952864
7101    19549314
7125    18837069
7141      994319
7143      994287
7144     1400391
7150     8863244
7164      994307
7166    19952798
7190    20140148
7197    17153568
7198      701831
7225      759771
7234     1113839
7265     1033291
7285    19136629
7305      323787
7324     4705675
7326     1194211
7327     1252943
7358    20140126
7360    20140115
7361    20140137
7363    20140082
7366    20140093
7369    20140071
7371     1113827
7373    18718418
7385    19894978
7399       91579
7402     8603365
7433    19980709
7454    19263629
7459    12096652
7465    19263662
7483    19263618
7484    19791184
7495    19263640
7505    19263651
7516    18046087
7517    18046098
7522    11764816
7562      368623
7597    19940603
7603       33123
7616    18420107
7630    19978226
7635    18420129
7645    19990113
7649    19825762
7659       28951
7663    17094628
7666      238331
7671    17354183
7679    15214822
7721    18126685
7723    19996645
7724    19136714
7725    19976794
7743    15238365
7747    18046021
7749    16784701
7753    18046043
7786    18046032
7791    18276209
7792    18046010
7800    20081113
7807    17532669
7814     1313603
7820    14828555
7838     1313615
7842    18239570
7865    19246677
7867    19553830
7871    17632916
7873    19761223
7878    19997248
7882    19997314
7898    19553346
7900     8349504
7907    19242908
7916    19740465
7922    19264716
7927    19992384
7949    16396365
7950    18554481
7960     8349400
7972    19992296
7984    14275477
7985    19997369
7994    15599299
8006    19997292
8017    19997270
8024    16300682
8055    19814936
8056    15599311
8073       92223
8090       32451
8100    19997281
8155     5714003
8176    19792593
8182    19333902
8185    14275453
8187    14275465
8191    18239548
8192     5230982
8216    20133974
8243    19996759
8256    17921196
8260    19957267
8264    19737449
8265    19792571
8266    19957256
8267    19792582
8276    19957245
8294    20142702
8327    20136450
8351      263783
8355     1408887
8356    17030776
8357     5236949
8359    13062500
8361    17030788
8365      429143
8377    17632960
8378    19142501
8389       32723
8398    15525077
8400    19828315
8441     7792264
8453    19854522
8472    19142479
8474    18148877
8478    19793295
8482     5324494
8491    17294781
8529    17117612
8541    18837081
8569    19651037
8570    17100428
8577    20036914
8581    20036826
8589    20112512
8592    20112490
8593    20160926
8595    20112501
8611    14202696
8621       32707
8640      486779
8668      700403
8675    15405765
8681    17927733
8690    20020372
8691    17444193
8701    11900492
8704    17946678
8706    11900432
8726    18868874
8730    19032233
8732    17946689
8748     5102879
8750    14211196
8752    19617161
8755    19183758
8762    19213313
8763    14554629
8767    19027907
8768    19559390
8775    19985971
8777    19984513
8778    19223277
8779    11900480
8782    19559412
8794    19559456
8814    20070781
8828    20070792
8833    19942901
8837    18973033
8843    20110143
8845    20110154
8846    20140720
8847    19171965
8852      757759
8853    19997303
8861    17653269
8872      428579
8881    19794713
8885      757783
8888    18730105
8889    10989984
8896    19971561
8905    20075395
8920    18730293
8923    19835319
8928    12818096
8929      684003
8932    12818084
8933    17819369
8942    19479219
8943    19728677
8944    19960154
8945    19559445
8947    19835341
8952    19920142
8955    19835330
8960    19617139
8963    19617205
8968    19898222
8981    19617150
8988    19997142
8991    18556801
8995    20141370
9001     5325074
9006    17912141
9020    20013384
9032    17030824
9040    16906684
9042    11615340
9043    16906732
9049    16906708
9054    11842160
9062    11515832
9065    13608712
9067    16906672
9068    19415782
9071    19906240
9072    19415826
9074    19415815
9075    19617766
9076    20053372
9079    19983552
9080    19415793
9081    19849061
9087    19906262
9088    19906251
9089    19983541
9098    18020533
9115    20114892
9116    19848786
9127    20001130
9138    20161695
9139    20161684
9140    19970620
9148     1339775
9151    18323725
9157    19956460
9164      323571
9170    18818982
9171    18818993
9174    20015296
9176       82835
9177    19774817
9179    20015285
9181       32939
9183    19803756
9185    19912869
9186    20015274
9190    19045253
9194    19133565
9195    20015307
9196    19046013
9198    20015263
9203    20052405
9204    19939421
9205    20148980
9206    18297410
9207    18433805
9208    20148969
9209    20052383
9211    20010750
9221    20156878
9225      527435
9230    19201196
9235      792631
9237    19201229
9244    18920541
9246    18690909
9249    18690865
9252    18690843
9253    20149028
9254    20154297
9255    18690854
9256    18152328
9257    18690887
9258    18690931
9262    18934545
9263    19241005
9265    18934556
9360    18436819
9383    19984025
9408    19984014
9420      427583
9451    18987679
9492    18433732
9553    19874629
9556    17282213
9567    18468449
9568    19381526
9570    19381548
9571    18468493
9581    18053973
9586    18053940
9610    18468460
9626    18053962
9653    18433710
9671    18433743
9676    18433721
9692    18278717
9724    19381537
9731    20043755
9734    19068859
9756    19952690
9757    19952701
9759    20043788
9764    19068991
9775    20043766
9785    13892928
9790    13892940
9813    19075169
9843    19566829
9845    20046383
9860    19068870
9862    19782298
9864    19075136
9869    19159747
9890    18468438
9899    19159758
9902    20043842
9938    20043831
9940    19782309
10019   20046372
10025   19498269
10030   20046361
10033   20046394
10060   19783777
10076   19653338
10089   19332603
10114   19783766
10125   19159769
10176   14490932
10181   19159736
10197   18580769
10226   20119158
10236   20119147
10255   16176856
10256   16115571
10258   19306688

In [28]:
display(
    desc_no_price[
        ["unique_id", "product_name", "promotion_price", "regular_price","selling_price","promotion_description", "pdp_url"]
    ]
)

Empty DataFrame
Columns: [unique_id, product_name, promotion_price, regular_price, selling_price, promotion_description, pdp_url]
Index: []

In [29]:
invalid = df[df["breadcrumb"].str.contains("…", na=False)]

print(f"Rows with truncated breadcrumbs: {len(invalid)}")
display(invalid[["unique_id", "breadcrumb"]])

Rows with truncated breadcrumbs: 0

Empty DataFrame
Columns: [unique_id, breadcrumb]
Index: []

In [30]:
result = df[
    df["selling_price"].isna() &
    df["regular_price"].isna()import pandas as pd

text_cols = df.select_dtypes(include="object").columns

issues = {}

for col in text_cols:
    # Match | not preceded by a backslash
    mask = (
        df[col]
        .fillna("")
        .astype(str)
        .str.contains(r"(?<!\\)\|", regex=True)
    )

    if mask.any():
        issues[col] = df.loc[mask, ["unique_id", col]]

# Print results
if issues:
    print("Columns containing unescaped '|':\n")
    for col, data in issues.items():
        print(f"\n=== {col} ({len(data)} rows) ===")
        print(data.to_string(index=False))
else:
    print("No unescaped '|' found.")
]

print(result)

SyntaxError: invalid syntax (273453188.py, line 3)

In [31]:
import pandas as pd

# Text columns only
text_cols = df.select_dtypes(include="object").columns

invalid_chars = [ "\n", "\r", "\t"]

issues = {}

for col in text_cols:
    mask = df[col].fillna("").astype(str).str.contains(r"[\n\r\t]", regex=True)
    if mask.any():
        issues[col] = df.loc[mask, ["unique_id", col]]

# Summary
if issues:
    print("Columns containing \\n, \\r or \\t:\n")
    for col, data in issues.items():
        print(f"{col}: {len(data)} rows")
else:
    print("No \\n, \\r or \\t found.")

No \n, \r or \t found.

In [32]:
columns = ["product_description", "special_information", "manufacturer_address"]

for col in columns:
    rows = df[
        df[col]
        .fillna("")
        .astype(str)
        .str.contains("|", regex=False, na=False)
    ]

    print(f"\n=== {col}: {len(rows)} rows ===")

    if not rows.empty:
        display(rows[["unique_id", "product_name", col]])

KeyError: 'product_description'

In [ ]:
import pandas as pd
import re




df["dimensions"] = df["dimensions"].fillna("").str.strip()

pattern = re.compile(
    r'^\d+(\.\d+)?(\s*[a-zA-Z]+)?\s*[xX×]\s*'
    r'\d+(\.\d+)?(\s*[a-zA-Z]+)?\s*[xX×]\s*'
    r'\d+(\.\d+)?(\s*[a-zA-Z]+)?$'
)

invalid = df[
    (df["dimensions"] != "") &
    (~df["dimensions"].str.match(pattern))
]

print(f"Invalid values: {len(invalid)}")
print(invalid[["unique_id", "product_name", "dimensions"]])

KeyError: 'dimensions'

In [33]:

# Replace empty strings with NA
df = df.replace(r'^\s*$', pd.NA, regex=True)

# Filter Fleisch & Fisch
ff = df[df["producthierarchy_level1"] == "Fleisch & Fisch"]

# Subcategories that should have price_per_unit
ppu_subcats = ["Fleisch & Geflügel", "Frischfisch & Schalentiere"]

# Missing price_per_unit
invalid_ppu = ff[
    ff["producthierarchy_level2"].isin(ppu_subcats) &
    ff["price_per_unit"].isna()
]

print("Missing price_per_unit:")
print(invalid_ppu[["unique_id","product_name","producthierarchy_level2","price_per_unit"]])

KeyError: 'producthierarchy_level1'

In [26]:
date_columns = [
    "promotion_valid_upto",
    "promotion_valid_from",
    "price_valid_from"
]

for col in date_columns:
    print("\nColumn:", col)
    print(df[col].value_counts(dropna=False))

Column: promotion_valid_upto
promotion_valid_upto
NaN    16866
Name: count, dtype: int64

Column: promotion_valid_from
promotion_valid_from
NaN    16866
Name: count, dtype: int64

Column: price_valid_from
price_valid_from
NaN    16866
Name: count, dtype: int64

In [27]:
invalid_discount = df[
    df["percentage_discount"]
    .astype(str)
    .str.contains(r"[%\-]", regex=True, na=False)
]

print("Invalid percentage_discount values:")
print(invalid_discount[["unique_id", "product_name", "percentage_discount"]])

print("\nCount:", len(invalid_discount))

Invalid percentage_discount values:
Empty DataFrame
Columns: [unique_id, product_name, percentage_discount]
Index: []

Count: 0

In [28]:
invalid = df[
    df["promotion_description"].notna() &
    (
        df["promotion_valid_from"].isna() |
        df["promotion_valid_upto"].isna()
    )
]

print(f"Rows with promotion description but missing promotion dates: {len(invalid)}")

display(
    invalid[
        [
            "unique_id",
            "product_name",
            "promotion_description",
            "promotion_valid_from",
            "promotion_valid_upto",
            "pdp_url"
        ]
    ]
)

Rows with promotion description but missing promotion dates: 3725

       unique_id  \
36       5123130
53       5123122
73      17164308
80      19979036
95      19744891
101       301643
178      5120904
181     17721109
201     19744913
228     19463279
233     19304194
235     19463268
287     19462507
289     19462529
294     19462540
310     19799869
311     20077996
324     20010129
331     20010107
334     20010118
335     20025050
350     18459713
355     11395392
357       278199
371       876971
375       358947
380     18459702
385     17467369
392     19085433
455     19898122
457      1161859
474     17180304
479     15155427
489     19217645
518     15836796
520     15836808
536     19304328
558       261199
573     16644803
582     16857209
611     15836820
616     19994904
634     19589689
703      1336203
707      8886672
716      1336239
718      8423688
719      8886648
727     19697045
728      1336179
729      5068481
774     19800082
798     19832343
804     19625249
822     17572648
838     19876938
844     19397073
892       497403
900     19979014
952     18633189
975     19388113
976     19621009
988     19979003
992      8423712
993     18462557
1001    18291087
1011      876827
1047     5346561
1050     5248376
1065       74979
1077    14735602
1084    19300957
1085      287731
1103    17039996
1108    17039960
1109    15870003
1110    15870015
1113    15878303
1116    17039984
1119    17039936
1122    17039948
1124    18924653
1126    17040008
1130    16841157
1132    17039972
1134    14689885
1136    19790841
1141    15878339
1155    19993425
1158    19089573
1160    14689897
1181    18867045
1183    19825389
1184    19369326
1193    20024861
1195    16436037
1196    16436049
1197    18886777
1204    19993458
1205    19993447
1214    20130985
1215    17159180
1218    16934792
1219    15878315
1222    18384421
1224    17776870
1226    15948175
1229    19181245
1235    18384399
1237    18867733
1238    20090775
1239    19233999
1241    17591393
1242    19993414
1248    17794581
1252    18781956
1254      771175
1256     1115263
1259    16207148
1260    16207160
1265    16893012
1271    19247886
1278    19742402
1281      698559
1287    17460439
1291    16179888
1292      771067
1294    18885821
1295      771283
1296      802139
1298    17631897
1299    14239509
1300    18733945
1301      771227
1302    17687529
1303      770959
1305    18285649
1307      771119
1308    19157386
1310      899607
1312    17959815
1317    14239709
1324    16213089
1337    16207184
1340    19682125
1343    16207136
1347    17425112
1349    18633102
1369    16207172
1376    19235373
1383    19898293
1385      984563
1386      742791
1387    16269560
1399    17230457
1403    16095718
1411    15875003
1413    15575287
1414    19960926
1416    15875015
1417    19471837
1420    15580111
1424    15629891
1428    19614717
1441    19678029
1449    17955658
1450    18579084
1453    17425145
1455    18579106
1458    20067464
1459    19678018
1473    17425079
1487    15932849
1507    19240477
1520    18916794
1534      771147
1542    19157397
1543    20002636
1563    19311033
1564    19944730
1566    17944574
1573     5245303
1575    19872705
1577    18118129
1583    19624878
1586    19525981
1587    20087156
1591    20078103
1598    20064329
1603    19624889
1607    20124063
1611    19637984
1612    18285597
1623    20002658
1625    20124085
1630    20129233
1636    20124074
1638    19637962
1643    20147980
1650    20129244
1653    19654049
1678    18997293
1684    16166927
1693    19519697
1695    16166915
1707    17976029
1712     1532339
1714    19712729
1736    18806869
1746    19862892
1763     8669803
1770    17726297
1773    18876834
1774    16169396
1790    17571871
1796    17573917
1819    17907072
1828    17907094
1829    19886345
1845    11919312
1855     1197895
1869    18301417
1874     1401547
1945    17104384
1953      510491
1962    18469465
1964    18840121
1971    19284025
1978    18935387
2007    14426837
2036    19999429
2042    20070564
2050     8047996
2056    20079041
2064    20079052
2129    17698295
2201    18390918
2225    19073917
2238    20018928
2240    20018917
2250      119747
2281     1403335
2295    19780017
2307    19959313
2344      445683
2378      543063
2401      545819
2409      183703
2410      545807
2413     1393167
2423     5074136
2431    18064485
2434    18412008
2446     1391323
2458    19605281
2475    19817853
2490    19817748
2492    14779335
2502    18780668
2510    20118994
2517    20145099
2519    20122929
2522    19601733
2523    20145088
2525    17771949
2538    20127434
2539    20145121
2545    20127423
2549    20127445
2552    16933684
2553    14779359
2555       82079
2557      181663
2563    20123028
2580    20122940
2586    20126945
2587    20123006
2588       23875
2599    20160330
2600       29143
2618    19975109
2636    18367685
2650      781779
2657       26983
2671       23851
2692    20160319
2721    16363452
2733    19429393
2734    13893009
2739    18760766
2741    19181353
2749    13789528
2750    17629486
2753    13317660
2766    17839109
2771     7918819
2774       83687
2780     1436803
2784    19245133
2789     1436815
2791    18436281
2806      312791
2807       83635
2821      284991
2824      867903
2830      489155
2835    10701228
2836      378651
2838    16877323
2839    18033481
2842    19163413
2849    19896380
2858    19896369
2859    19998886
2878       29411
2889    18535790
2891    18790037
2897    19124153
2899     5229836
2902      208439
2906    17661176
2915    15878921
2917    17661187
2921    19759628
2933    18434877
2938    18434866
2966      534195
3171    19999381
3323    20102984
3324    20103006
3325    19804393
3339    20102995
3373    15884142
3393      204339
3394    16607809
3422    20074418
3429    20074429
3509    17919519
3530    17435709
3538    19403706
3548    19403717
3553    19901731
3560    19964598
3563    19964587
3565    17609501
3567    19901764
3569    19246726
3571    19133745
3572    17609479
3573    19901742
3574    19964609
3575    19967385
3577    18985925
3586    17235282
3589    19907183
3592    16116711
3606    16596165
3618    16327959
3630    19907238
3633    20042397
3641    19967396
3647    20042386
3650    19247539
3653    20102401
3661    20102412
3668     5319571
3677    17949045
3691    17425283
3692    19600729
3693    19639167
3698    19187103
3701    17476865
3705    19980407
3736    16409797
3753    17665202
3759    18145145
3760    17665191
3778    17983373
3781    16424917
3782    19602549
3786    20049950
3793    20148138
3797    20097746
3798    19719965
3800    20148149
3801    19799085
3802    19799074
3803    19968922
3804    19967913
3805    20114839
3806    20114828
3813    19401185
3819    18145123
3822    15236488
3826    17660864
3830      896175
3831    20042130
3833    18559798
3837    17660897
3838    16903152
3839    20042119
3845    17665213
3846    17665290
3849    19144325
3851    19086909
3852    16795409
3853    19133659
3859    19144314
3865    18559831
3866    19507629
3867    19796505
3873    19907373
3883    19900601
3884     1136943
3886    17576369
3906       28867
3923    20123893
3925    20123882
3928    20123871
3929     5324962
3941     1380387
3945    17798510
3947    14400664
3955     1046955
3960     5306466
3961      755083
3963       83335
3967    19843077
3969     1046931
3970    18591762
3982      256039
3986    17774709
3993    19617983
4002    19633517
4025    14471945
4027    19931581
4029    14471957
4030    14471969
4031    19931603
4034    18730202
4041    19618005
4042    19931592
4055    19216853
4058    18316646
4066    19469745
4070     1380399
4072    19686309
4077    19846300
4083    18228177
4089    19931614
4090    19931625
4096    19900565
4098    19360513
4104    20010338
4112    17879981
4120    20010327
4124    19919181
4130    19612129
4136    19119181
4137    18242285
4138    20153572
4142    20042002
4143     8821268
4151     8821280
4154    17582450
4155    20071541
4160    20071519
4163    20157014
4165    20157003
4168    20071530
4173    19919169
4194    14261805
4196     7371776
4204      199307
4209    17773227
4212    17773040
4214    19210161
4225    16854981
4229    19210150
4237      604835
4242    15192887
4251       44731
4262    19213477
4266     1284315
4273    20041825
4277    17773150
4278    18929406
4286    17773106
4297    19967304
4303    19952229
4307    19932027
4308    19931994
4318    17153752
4320    16220116
4321      199271
4338    19919393
4343    18916773
4348    17773568
4349    19967315
4350    17773546
4358    19952218
4359    18274258
4367    19718631
4372     1231447
4380     1231435
4381    18216297
4391     4685872
4392    17373741
4405    17604122
4412    18740786
4414    17373422
4415    18809069
4420    19117865
4425    19563746
4429    19563735
4433    19863994
4436    19136881
4438    19563757
4440    18891941
4451     1362207
4453    17858127
4454    17728080
4455     1362219
4456    17728113
4457    12168692
4460    17743010
4475    18739725
4482    19811045
4496    19811078
4497    19995686
4498    19995697
4509    18739515
4518    19484294
4526      365299
4527       30623
4528      873419
4530    17702079
4534    17702101
4536    18506391
4537    17702090
4539      873431
4540      873443
4543    18816507
4546    18166185
4554    19314648
4555    18087009
4565    19486601
4570       31991
4575    18125526
4579    18739666
4581    16272256
4583      335767
4584      511895
4590    18484657
4594    19112717
4598    19976462
4599    19976473
4602    19465912
4603    16272244
4604    19976451
4608    16394381
4612    16638953
4622    19136914
4623    19465945
4629    19902089
4637    20159277
4638    16638905
4641    16638893
4642    16638941
4644    19816845
4645    19948681
4646    19945198
4647    16638917
4648    19976440
4655    18484635
4657    16638929
4659    16651325
4660    19945176
4664    19465923
4667    19465934
4678      172087
4700    19334402
4712    18482331
4713    20149835
4714    19642625
4720    19314828
4733    16437447
4735    15149923
4736     1337547
4755    15149935
4773    16437471
4779    15795595
4781    17573349
4785    16437507
4790     1345919
4799    17855525
4803    17855514
4822    19066782
4825    13776371
4831       23683
4832       23695
4838      429967
4840    16029673
4857    16970378
4859    19940781
4873    19996325
4884    20022808
4891      876155
4900    18739537
4904    18739559
4905    18739581
4925    20002340
4976    19816423
4977    19816412
4978    20105417
4981    16605525
4989      489383
4992      388883
4993    14882367
5005    19643446
5007    17387261
5009    19816885
5011    18506067
5013    19971813
5018    19157501
5021    19066760
5022    19157490
5029    19885798
5034    19885149
5036    20109683
5037    20023538
5044    19990742
5046    20109694
5047    19958554
5051    19958565
5052    19885809
5053    19379581
5054    19990753
5064    19816434
5065    19816445
5066    18194389
5069    18194411
5073       23539
5089    11612064
5097    16605549
5100    17196441
5104    19722665
5105       83891
5107       90819
5125    17517974
5126    20112262
5129    19617670
5131    17518007
5133    19617648
5134    17518029
5135    19617681
5136    19822636
5150    19828422
5151    18424957
5154    17942781
5160    18721938
5164    19926201
5171    19605817
5182    19622913
5186    12586788
5187    18741353
5190    20101934
5219      313163
5236    19464142
5238    19439328
5239    19114445
5240    14900199
5241    17113128
5245    19455377
5247    18099633
5259     7495244
5260    10943388
5264      806559
5265    18421329
5267     8655544
5272    17976694
5274    18432001
5278    14463697
5284      976087
5285    16716057
5286    10957828
5287     9798908
5291    19670006
5293     7369604
5300    10926904
5305    20157338
5314    19192109
5325      328755
5327    19514425
5328    17998148
5329       92395
5330    19576215
5348       23483
5350      325427
5351    18648821
5354       82371
5357    19611929
5359    11196692
5361      379115
5362       30959
5363       82311
5365       23495
5367    19132396
5369     1231327
5371    18223345
5377      355075
5383    11026340
5385      863955
5386    15386799
5388    19402192
5389    19697517
5391    17917869
5394      484231
5404     7512885
5405     1215235
5407      928743
5408      342411
5410    18019481
5412     5117807
5416    19337794
5418     1232835
5419      383631
5423    16809546
5428    18806521
5429    18806510
5431    16809558
5432    16994592
5433    17371194
5436    18053148
5438    17371205
5439    16809570
5440       30991
5441       23551
5443     1398563
5446       91911
5447      117831
5453    19586965
5460      750943
5471    18271327
5475     5321467
5476    18271305
5479    19671822
5481    18565034
5482      791839
5486     1007023
5487    19589931
5490      970319
5493    19856438
5495    19858207
5497    18849289
5501    20103067
5506    18876728
5518     1398551
5519    18885793
5523    19611962
5526    19970462
5528    19954749
5530    17124044
5532    18987774
5534    19611918
5538    16404008
5539    20087060
5540    17741110
5541    19611940
5543     7372696
5544    20078668
5546     5306286
5547    19132429
5549    19974345
5550    20012779
5551    19611973
5555    13289808
5556    10939748
5561    20016774
5563      274567
5567    19629185
5570    20016968
5571    19558781
5573    18310645
5574    19291185
5577    19896613
5584    19611951
5595    17079596
5596    17077424
5597      118623
5601    20016957
5602    19828367
5603    20016979
5616    20142203
5618    20142192
5627    19576237
5628    19293481
5629    19924249
5632    17574809
5639    17545505
5646    20077842
5650    17050700
5651    18863853
5655      258863
5656    19744981
5659    19589306
5660    19589317
5665      472355
5666    20021205
5667    19590085
5668    19293459
5684    20021194
5688    19856449
5690    19856427
5691    20021183
5694      427119
5696    20007549
5700     5381391
5709    19681168
5715    13171112
5750    19941382
5757    20103045
5759    19858163
5767      204867
5769       24387
5771    19945740
5776    19157102
5778       82963
5779    12779880
5793    18927565
5795    12206832
5800      130491
5802    19157069
5806    12779892
5813    19181330
5815      835227
5817      693083
5821      130455
5825    14441764
5850    17563477
5856    19787727
5857      493339
5858      228711
5861    19157058
5870    16503977
5872    19787716
5874     7840664
5877       34695
5878    18489837
5880    20149738
5885     5079357
5889    14000867
5890      575603
5892    19181341
5893      261923
5894      192323
5896    17860510
5897      498507
5899      498539
5901    14943417
5904    18489881
5906    19527670
5910    10926752
5918    16503965
5920     5230612
5922    20087216
5926    17494275
5927    14305801
5928     1322147
5931    15058365
5933    15463427
5939       24615
5940    19768297
5942    19877833
5949    20087144
5952      839855
5955       24627
5959    19941130
5962    18665737
5963    15464515
5974    18523595
5976    15942379
5990    19671436
5992    19854105
6002    19681157
6004    20101737
6005      498547
6006     5490760
6010    18528655
6011      835215
6014    19974334
6015      173031
6021    17860521
6024    19046077
6028    19495238
6029    19667120
6033    19495249
6034    19181308
6035      667231
6038    15834752
6039    17883194
6043    19670145
6048      498519
6077    19273169
6079      498531
6114      835239
6115      498771
6116     1322135
6123    13957268
6124    18695130
6127      681055
6132    18695141
6133    19854083
6137    18489859
6147    15258911
6151    19788242
6155    17494242
6156    19601342
6157    19671601
6158    19671414
6159    19669870
6167     1235491
6172      660615
6173    19493892
6175    18020313
6176      221591
6186    19744948
6187    19161273
6202     1508003
6205     1419811
6209    19157091
6218      615299
6227      498575
6233      190487
6236    19949505
6237    19046529
6241    20048915
6244      577611
6247      647931
6249    18636453
6253    19670123
6255    18489826
6258    18528721
6262    17978758
6268    16891752
6274    17883205
6277    18489848
6278      667223
6282    17883227
6283    20064975
6284     7729136
6286     5257730
6288      498831
6292      498563
6293    19947733
6294    18528677
6296     5097159
6297      577555
6299     5242302
6307      498715
6312    20048937
6316    19212911
6319    19667131
6321     1395639
6324    14732264
6365       27231
6372       92335
6379    15454481
6382    15454489
6383    15454473
6387    17405582
6389    17405637
6391    15454465
6395       27243
6402      190883
6416    19634340
6460    19933189
6464    19634439
6465    19634428
6466    19634494
6467    19634472
6474    18647417
6480    19949428
6481    17978769
6482    19495216
6491    20000049
6493    18647329
6497    17978780
6500    15525149
6505    19046496
6507    20048926
6508    18862316
6515    20000071
6519    20024463
6521    20000027
6524    19634406
6526    20000016
6535    19634329
6538    19167823
6542    19634384
6543    19634362
6552    18862327
6559    20105738
6576    19167713
6578    19634505
6579    19167834
6613    19167757
6616    19167724
6617    19167702
6620    19167669
6633    19167801
6634    19167812
6637    20105727
6642    18574806
6653    19759617
6661     5076874
6665       28555
6670      104619
6677    12068208
6690    17755257
6696    19666581
6698    16722441
6706    19085839
6707    19405641
6723    19998864
6731     5318815
6732     5066312
6742     5066300
6768     8811461
6847       32927
6850    18235892
6853    17770229
6855    19745933
6860    19745911
6862    19745900
6877      647595
6881    19745889
6885    19745922
6887     5345027
6902    19122534
6911    19983863
6922    18572645
6924    18572667
6926    19122545
6939    19122523
6949     5304270
6953      261951
6954     5066632
6959    16310857
6960     5230452
6962     5076322
6966    14976083
6972    17792507
6973      229707
6979    17558281
6981    19123218
6988    16310869
6994    19016187
6999    19549197
7000    18087945
7001    19123273
7003    19905206
7006    19090806
7007    10920032
7009    19123262
7010    19905217
7015    19684269
7016    19507675
7017      220079
7019     6007386
7023    10920000
7026    17183909
7030    19207413
7034    19785174
7037    16604109
7039    19886502
7042    19090795
7051    19905195
7053    19549175
7054    19983328
7057    19983350
7061    19016198
7063    20037575
7064    20037886
7065    19507686
7066    19942009
7069    16604085
7070    19507697
7073    19983339
7074    20070482
7076    16209664
7079    20140104
7090    17865453
7091    19887537
7095    19952864
7101    19549314
7108     8811353
7125    18837069
7134    19543357
7141      994319
7143      994287
7144     1400391
7150     8863244
7164      994307
7166    19952798
7190    20140148
7197    17153568
7198      701831
7225      759771
7234     1113839
7265     1033291
7285    19136629
7305      323787
7324     4705675
7326     1194211
7327     1252943
7347     5251391
7358    20140126
7360    20140115
7361    20140137
7363    20140082
7366    20140093
7369    20140071
7371     1113827
7373    18718418
7374     8578664
7377     8669972
7385    19894978
7399       91579
7402     8603365
7433    19980709
7454    19263629
7459    12096652
7465    19263662
7483    19263618
7484    19791184
7495    19263640
7505    19263651
7516    18046087
7517    18046098
7522    11764816
7562      368623
7597    19940603
7603       33123
7616    18420107
7630    19978226
7635    18420129
7645    19990113
7649    19825762
7659       28951
7663    17094628
7666      238331
7671    17354183
7679    15214822
7721    18126685
7723    19996645
7724    19136714
7725    19976794
7743    15238365
7747    18046021
7749    16784701
7753    18046043
7786    18046032
7791    18276209
7792    18046010
7800    20081113
7807    17532669
7814     1313603
7820    14828555
7838     1313615
7842    18239570
7850    17632927
7865    19246677
7867    19553830
7871    17632916

In [29]:
import pandas as pd

# Normalize for case-insensitive comparison
df["site_shown_uom"] = df["site_shown_uom"].fillna("").astype(str)
df["grammage_unit"] = df["grammage_unit"].fillna("").astype(str)
df["grammage_quantity"] = df["grammage_quantity"].fillna("").astype(str)

# -----------------------------
# Rule 1: Teebeutel / Beutel -> btl
# -----------------------------
btl_keywords = [
    "Teebeutel Packung",
    "Teebeutel",
    "Beutel",
    "Btl",
    "Teebeutel Karton",
    "Teebeutel Paket",
    "Packung Beutel"
]

btl_invalid = df[
    df["site_shown_uom"].str.contains("|".join(btl_keywords), case=False, regex=True)
    &
    (df["grammage_unit"].str.lower() != "btl")
]

print(f"BTL unit mismatches: {len(btl_invalid)}")
display(btl_invalid[[
    "unique_id",
    "product_name",
    "site_shown_uom",
    "grammage_quantity",
    "grammage_unit"
]])

# -----------------------------
# Rule 2: Portion Packung / ANW -> stuck
# -----------------------------
stuck_keywords = [
    "Portion Packung",
    "ANW"
]

stuck_invalid = df[
    df["site_shown_uom"].str.contains("|".join(stuck_keywords), case=False, regex=True)
    &
    (df["grammage_unit"].str.lower() != "stuck")
]

print(f"STUCK unit mismatches: {len(stuck_invalid)}")
display(stuck_invalid[[
    "unique_id",
    "product_name",
    "site_shown_uom",
    "grammage_quantity",
    "grammage_unit"
]])

# -----------------------------
# Rule 3: wg / Waschgänge -> wg
# -----------------------------
wg_keywords = [
    "wg",
    "Waschgänge"
]

wg_invalid = df[
    df["site_shown_uom"].str.contains("|".join(wg_keywords), case=False, regex=True)
    &
    (df["grammage_unit"].str.lower() != "wg")
]

print(f"WG unit mismatches: {len(wg_invalid)}")
display(wg_invalid[[
    "unique_id",
    "product_name",
    "site_shown_uom",
    "grammage_quantity",
    "grammage_unit",
    "pdp_url"
]])

BTL unit mismatches: 0

Empty DataFrame
Columns: [unique_id, product_name, site_shown_uom, grammage_quantity, grammage_unit]
Index: []

STUCK unit mismatches: 0

Empty DataFrame
Columns: [unique_id, product_name, site_shown_uom, grammage_quantity, grammage_unit]
Index: []

WG unit mismatches: 0

Empty DataFrame
Columns: [unique_id, product_name, site_shown_uom, grammage_quantity, grammage_unit, pdp_url]
Index: []

In [30]:
import pandas as pd

price_cols = ["regular_price", "selling_price"]

for col in price_cols:
    # Ignore missing values
    mask = (
        df[col].notna() &
        (~df[col].astype(float).round(2).eq(df[col].astype(float)))
    )

    invalid = df.loc[mask, ["unique_id", "product_name", col]]

    print(f"\n{col}: {len(invalid)} values not in 2-decimal format")
    display(invalid)

regular_price: 0 values not in 2-decimal format

Empty DataFrame
Columns: [unique_id, product_name, regular_price]
Index: []

selling_price: 0 values not in 2-decimal format

Empty DataFrame
Columns: [unique_id, product_name, selling_price]
Index: []

In [31]:
import re
import pandas as pd

# Normalize grammage_unit
df["grammage_unit_norm"] = df["grammage_unit"].fillna("").str.lower().str.strip()

# Extract quantity from site_shown_uom
df["site_qty"] = (
    df["site_shown_uom"]
      .str.extract(r"(\d+(?:[.,]\d+)?)", expand=False)
      .str.replace(",", ".", regex=False)
)

df["site_qty"] = pd.to_numeric(df["site_qty"], errors="coerce")

# ---------- Rule 1 : Beutel / Btl ----------
btl_pattern = (
    r"Teebeutel Packung|Teebeutel Karton|Teebeutel Paket|"
    r"Packung Beutel|Teebeutel|Beutel|Btl"
)

btl_issue = df[
    df["site_shown_uom"].fillna("").str.contains(btl_pattern, case=False, regex=True)
    &
    (
        (df["grammage_unit_norm"] != "btl") |
        (df["grammage_quantity"] != df["site_qty"])
    )
]

# ---------- Rule 2 : Portion Packung / ANW ----------
stuck_pattern = r"Portion Packung|ANW"

stuck_issue = df[
    df["site_shown_uom"].fillna("").str.contains(stuck_pattern, case=False, regex=True)
    &
    (
        (df["grammage_unit_norm"] != "stuck") |
        (df["grammage_quantity"] != df["site_qty"])
    )
]

# ---------- Rule 3 : Waschgang / Waschgänge / wg ----------
wg_pattern = r"\bwg\b|Waschgänge|Waschgang"

wg_issue = df[
    df["site_shown_uom"].fillna("").str.contains(wg_pattern, case=False, regex=True)
    &
    (
        (df["grammage_unit_norm"] != "wg") |
        (df["grammage_quantity"] != df["site_qty"])
    )
]

print("Btl issues:", len(btl_issue))
print("Stuck issues:", len(stuck_issue))
print("WG issues:", len(wg_issue))

Btl issues: 0
Stuck issues: 0
WG issues: 0

In [32]:
btl_issue[
    [
        "unique_id",
        "product_name",
        "site_shown_uom",
        "grammage_quantity",
        "grammage_unit",
        "site_qty"
    ]
].head(20)

Empty DataFrame
Columns: [unique_id, product_name, site_shown_uom, grammage_quantity, grammage_unit, site_qty]
Index: []

In [33]:
wrong_unit_wg = wg_issue[
    wg_issue["grammage_unit_norm"] != "wg"
]

wrong_qty_wg = wg_issue[
    (wg_issue["grammage_unit_norm"] == "wg") &
    (wg_issue["grammage_quantity"] != wg_issue["site_qty"])
]

print("WG - Wrong unit:", len(wrong_unit_wg))
print("WG - Wrong quantity:", len(wrong_qty_wg))

WG - Wrong unit: 0
WG - Wrong quantity: 0

In [34]:
wrong_unit_wg[
    [
        "unique_id",
        "product_name",
        "site_shown_uom",
        "grammage_quantity",
        "grammage_unit"
    ]
]

Empty DataFrame
Columns: [unique_id, product_name, site_shown_uom, grammage_quantity, grammage_unit]
Index: []

In [35]:
df[df.product_name == "Cartelletta 3 lembi monocromo pastel	"]

Empty DataFrame
Columns: [unique_id, competitor_name, extraction_date, product_name, grammage_quantity, grammage_unit, regular_price, selling_price, price_valid_from, price_per_unit, percentage_discount, promotion_price, promotion_valid_from, promotion_valid_upto, promotion_description, currency, breadcrumb, pdp_url, region, pack_size, site_shown_uom, grammage_unit_norm, site_qty]
Index: []

In [36]:
text_cols = df.select_dtypes(include="object").columns

leading_trailing = {}

for col in text_cols:
    mask = (
        df[col].fillna("").astype(str)
        != df[col].fillna("").astype(str).str.strip()
    )
    if mask.any():
        leading_trailing[col] = df.loc[mask, col]

print(leading_trailing.keys())

dict_keys([])

In [37]:
multiple_spaces = {}

for col in text_cols:
    mask = df[col].fillna("").str.contains(r"\s{2,}", regex=True)
    if mask.any():
        multiple_spaces[col] = df.loc[mask, col]

print(multiple_spaces.keys())

dict_keys([])

In [38]:
special_space = {}

for col in text_cols:
    mask = df[col].fillna("").str.contains(r"[\t\r\n]", regex=True)
    if mask.any():
        special_space[col] = df.loc[mask, col]

print(special_space.keys())

dict_keys([])

In [39]:
special_space

{}

In [40]:
issues = []

for col in text_cols:
    mask = (
        (df[col].fillna("") != df[col].fillna("").str.strip()) |
        df[col].fillna("").str.contains(r"\s{2,}", regex=True) |
        df[col].fillna("").str.contains(r"[\t\r\n]", regex=True) |
        df[col].fillna("").str.contains("\u00A0", regex=False)
    )

    if mask.any():
        tmp = df.loc[mask, ["unique_id", col]].copy()
        tmp["column"] = col
        issues.append(tmp)

issues = pd.concat(issues, ignore_index=True)

issues.head()

ValueError: No objects to concatenate

In [41]:
import pandas as pd

# Convert price columns to numeric
cols = ["regular_price", "selling_price", "promotion_price", "price_per_unit"]
df[cols] = df[cols].apply(pd.to_numeric, errors="coerce")

invalid = df[
    # Mehrweg product
    (
        df["product_name"].fillna("").str.contains("Mehrweg", case=False) |
        df["breadcrumb"].fillna("").str.contains("Mehrweg", case=False)
    )
    &
    # Has AKTION promotion
    df["promotion_description"].fillna("").str.contains("AKTION", case=False)
    &
    # Rule violation
    (
        df["regular_price"].notna() |
        (df["selling_price"] != df["price_per_unit"]) |
        (df["promotion_price"] != df["price_per_unit"])
    )
]

print("Invalid rows:", len(invalid))

invalid[
    [
        "unique_id",
        "product_name",
        "regular_price",
        "selling_price",
        "promotion_price",
        "price_per_unit",
        "promotion_description",
        "pdp_url",
    ]
]

Invalid rows: 0

Empty DataFrame
Columns: [unique_id, product_name, regular_price, selling_price, promotion_price, price_per_unit, promotion_description, pdp_url]
Index: []

In [42]:
df.isnull().sum()

unique_id                    0
competitor_name              0
extraction_date              0
product_name                 0
grammage_quantity            0
grammage_unit                0
regular_price                0
selling_price                0
price_valid_from         16866
price_per_unit           16866
percentage_discount      14135
promotion_price          15572
promotion_valid_from     16866
promotion_valid_upto     16866
promotion_description    13141
currency                     0
breadcrumb                   0
pdp_url                      0
region                   16866
pack_size                16866
site_shown_uom               0
grammage_unit_norm           0
site_qty                   820
dtype: int64

In [46]:
df[df.regular_price.isna()]

Empty DataFrame
Columns: [unique_id, competitor_name, extraction_date, product_name, grammage_quantity, grammage_unit, regular_price, selling_price, price_valid_from, price_per_unit, percentage_discount, promotion_price, promotion_valid_from, promotion_valid_upto, promotion_description, currency, breadcrumb, pdp_url, region, pack_size, site_shown_uom, grammage_unit_norm, site_qty]
Index: []