In [1]:
import pandas as pd
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option("display.max_colwidth", None)

In [2]:
import pandas as pd
import json

df = pd.read_json(
    r"/home/user/Downloads/kentwood_2026_08_05.json",
    lines=True
)

# Convert list/dict columns into strings
df = df.apply(
    lambda col: col.map(
        lambda x: json.dumps(x, sort_keys=True)
        if isinstance(x, (list, dict))
        else x
    )
)

In [3]:
import pandas as pd
import re
import unicodedata

def normalize(text):
    if pd.isna(text):
        return ""
    text = str(text).strip().lower()

    # Remove accents
    text = "".join(
        c for c in unicodedata.normalize("NFKD", text)
        if not unicodedata.combining(c)
    )

    # Keep only letters, numbers, hyphens and spaces
    text = re.sub(r"[^a-z0-9\s-]", "", text)

    # Replace spaces with hyphens
    text = re.sub(r"\s+", "-", text)

    return text

def profile_name_matches(row):
    url = str(row["profile_url"]).lower()

    # Extract the slug after /our-advisors/ or /bio/
    m = re.search(r"/(?:our-advisors|bio)/([^/?]+)", url)
    if not m:
        return False

    slug = normalize(m.group(1))

    first = normalize(row["first_name"])
    last = normalize(row["last_name"])

    return first in slug and last in slug

invalid_profile_urls = df[
    ~df.apply(profile_name_matches, axis=1)
]

print(f"Profile URL name mismatches: {len(invalid_profile_urls)}")
display(invalid_profile_urls[["profile_url", "first_name", "last_name"]])

Profile URL name mismatches: 116

,profile_url,first_name,last_name
0,https://www.kentwood.com/bio/bkelly,Bob,Kelly
2,https://www.kentwood.com/bio/bgustafson,Brendan,Gustafson
3,https://www.kentwood.com/bio/Brandon,Brandon,Brennick
6,https://www.kentwood.com/bio/HarrisTeam,Brian and Jamie Harris,
8,https://www.kentwood.com/bio/brosen,Brian,Rosen
9,https://www.kentwood.com/bio/bridgetm,Bridget,Marx
10,https://www.kentwood.com/bio/BrinckerhoffEmery,Brinckerhoff Emery & Associates,
11,https://www.kentwood.com/bio/uhl,Bryan & Kris Uhl,
12,https://www.kentwood.com/bio/Jbuckley,Buckley,Team
14,https://www.kentwood.com/bio/Carolyn,Carolyn,O'Donnell
17,https://www.kentwood.com/bio/charlotte,Charlotte,Connolly
20,https://www.kentwood.com/bio/chris,Christopher,Ansay
21,https://www.kentwood.com/bio/chowey2,Christopher,Howey
22,https://www.kentwood.com/bio/cgargotto,Chuck,Gargotto
25,https://www.kentwood.com/bio/dan,Dan,Buckley
26,https://www.kentwood.com/bio/danielle,Danielle,Ewing
27,https://www.kentwood.com/bio/david,David,Morrison
28,https://www.kentwood.com/bio/dawn,Dawn,Raymond
29,https://www.kentwood.com/bio/deec,Dee,Chirafisi
30,https://www.kentwood.com/bio/DenaP,Dena,Reeves-Pastorini
32,https://www.kentwood.com/bio/Diane,Diane,Sorensen
33,https://www.kentwood.com/bio/dierk,Dierk,Herbermann
34,https://www.kentwood.com/bio/dotson,Dotson,Skaggs
35,https://www.kentwood.com/bio/emarks,Edie,Marks
36,https://www.kentwood.com/bio/elise,Elise,Marks
37,https://www.kentwood.com/bio/EHotz,Elizabeth,Hotz
38,https://www.kentwood.com/bio/Elizabeth,Elizabeth,Sacerdoti
42,https://www.kentwood.com/bio/gglucksman,Gayle,Glucksman
43,https://www.kentwood.com/bio/GhassanK,Ghassan,Kanafani
44,https://www.kentwood.com/bio/ginaandkara2,Gina Lorenzen & Kara Couzens,
45,https://www.kentwood.com/bio/GELSNER,Greg,Elsner
46,https://www.kentwood.com/bio/greg,Greg,Yoshida
49,https://www.kentwood.com/bio/gthurman,J.,Thurman
50,https://www.kentwood.com/bio/JacciandSana-JSCollective,Jacci,Geiger
51,https://www.kentwood.com/bio/jaden,Jaden,Combs
53,https://www.kentwood.com/bio/janelleh,Janelle,Howard
56,https://www.kentwood.com/bio/jalton,Janiese,Alton
58,https://www.kentwood.com/bio/Jay,Jay,Modglin
59,https://www.kentwood.com/bio/jvanderhule,Jeff,Vanderhule
61,https://www.kentwood.com/bio/jen,Jen,Fillion
62,https://www.kentwood.com/bio/jmarkus2,Jennifer,Markus
63,https://www.kentwood.com/bio/Jim,Jim,Nussbaum
64,https://www.kentwood.com/bio/jrhye,Jim,Rhye
65,https://www.kentwood.com/bio/TRAYNOR,Jim,Traynor
67,https://www.kentwood.com/bio/jinnohn,Jinnohn,Gilmore
68,https://www.kentwood.com/bio/jfitz,John,Fitzpatrick
70,https://www.kentwood.com/bio/jhayden,John,Hayden
72,https://www.kentwood.com/bio/jonlopez,Jonathan,Lopez
73,https://www.kentwood.com/bio/jonp,Jonathan,Pierotti
74,https://www.kentwood.com/bio/jhummel,Julie,Hummel
77,https://www.kentwood.com/bio/KarenLanders,Karen,Zeile
78,https://www.kentwood.com/bio/karen,Karen,Brinckerhoff
81,https://www.kentwood.com/bio/katherinel,Katherine,Lillydahl
85,https://www.kentwood.com/bio/KCOMBS,Keith,Combs
86,https://www.kentwood.com/bio/ksophinos,Kelly Sophinos and Greg Margheim,
88,https://www.kentwood.com/bio/Keri,Keri,Duffy
92,https://www.kentwood.com/bio/lhotz,Larry,Hotz
94,https://www.kentwood.com/bio/lmonaco,Leslie,Monaco
95,https://www.kentwood.com/bio/libby,Libby,Levinson
97,https://www.kentwood.com/bio/lisag,Lisa,Gould
98,https://www.kentwood.com/bio/Lori,Lori,Pace
99,https://www.kentwood.com/bio/MacM,Mac,Martin
100,https://www.kentwood.com/bio/martha,Martha,Potter-Goldstein
101,https://www.kentwood.com/bio/mary,Mary,Jones
103,https://www.kentwood.com/bio/MattP,Matt,Peterson
107,https://www.kentwood.com/bio/mhotz,Meredith,Hotz
108,https://www.kentwood.com/bio/MikeC,Michael,Csrnko
112,https://www.kentwood.com/bio/mitch,Mitchell,Rothman
113,https://www.kentwood.com/bio/nnielsen,Nancy,Nielsen
114,https://www.kentwood.com/bio/nwalters,Nancy,Walters
121,https://www.kentwood.com/bio/pattygreg,Patty Ryan Anton & Greg Card,
122,https://www.kentwood.com/bio/pwall,Pat,Wall
126,https://www.kentwood.com/bio/phyllis,Phyllis,Sinclair
129,https://www.kentwood.com/bio/renitah,Renita,Heald
130,https://www.kentwood.com/bio/goldhammer2,Rob,Goldhammer
131,https://www.kentwood.com/bio/rlandry,Robyn,Landry
133,https://www.kentwood.com/bio/sana,Sana,Wood
134,https://www.kentwood.com/bio/sweigand,Sandy,Weigand
135,https://www.kentwood.com/bio/sglaze,Sara,Glaze
138,https://www.kentwood.com/bio/Scott,Scott,Scholbe
140,https://www.kentwood.com/bio/larkin,Sean & Debbie Larkin,
141,https://www.kentwood.com/bio/skelly,Sean,Kelly
143,https://www.kentwood.com/bio/sheila,Sheila,Schlifkin
144,https://www.kentwood.com/bio/Soley,Soley,Maria
146,https://www.kentwood.com/bio/Staci,Staci,Burns
148,https://www.kentwood.com/bio/stephanie,Stephanie,Lepard
149,https://www.kentwood.com/bio/StephanieS,Stephanie,Sulstrom
150,https://www.kentwood.com/bio/skruse,Steven,Kruse
151,https://www.kentwood.com/bio/steve,Steve,Travers
152,https://www.kentwood.com/bio/stock,Stock,Jonekos
153,https://www.kentwood.com/bio/sdiliberti,Susan,Diliberti
158,https://www.kentwood.com/bio/dutzerteam,Thomas & Rosanne Dutzer,
160,https://www.kentwood.com/bio/tglucksman,Tiffany,Appel
161,https://www.kentwood.com/bio/tcolleran,Tim,Colleran
162,https://www.kentwood.com/bio/todd,Todd,Landgrave
164,https://www.kentwood.com/bio/Tom,Tom,Gross
166,https://www.kentwood.com/bio/awolfe,Aaron,Wolfe
167,https://www.kentwood.com/bio/aimee,Aimee,Twarogowski
168,https://www.kentwood.com/bio/alarson,Alan,Larson
170,https://www.kentwood.com/bio/acraig,Allison,Craig
171,https://www.kentwood.com/bio/asmookler,Allison,Smookler
176,https://www.kentwood.com/bio/anastasia,Anastasia,Williamson
177,https://www.kentwood.com/bio/andrea,Andrea,Bell
178,https://www.kentwood.com/bio/andreac,Andrea,Chirich
180,https://www.kentwood.com/bio/agonzales,Andrew,Gonzales
181,https://www.kentwood.com/bio/andy2,Andrew,Maguire
182,https://www.kentwood.com/bio/Angela,Angela,Beldy
184,https://www.kentwood.com/bio/amcwilliams,Anne,McWilliams
185,https://www.kentwood.com/bio/ann,Ann,Lenane
186,https://www.kentwood.com/bio/Annzo,Annzo,Phelps
187,https://www.kentwood.com/bio/autumns,Autumn,Mestas
188,https://www.kentwood.com/bio/BFIEST,Barb,Fiest
190,https://www.kentwood.com/bio/BILL,Bill,Verdon
191,https://www.kentwood.com/bio/BobbyB,Bobby,Bolyard
192,https://www.kentwood.com/bio/afshins,Afshin,Sarvestani
193,https://www.kentwood.com/bio/bob,Bob,Lee

In [7]:
import re

email_pattern = re.compile(
    r'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'
)

invalid_emails = df[
    df["email"].notna() &
    (df["email"].str.strip() != "") &
    ~df["email"].astype(str).str.match(email_pattern)
]

print(f"Invalid emails: {len(invalid_emails)}")

display(invalid_emails[["profile_url", "email"]])

Invalid emails: 0

Empty DataFrame
Columns: [profile_url, email]
Index: []

In [8]:
import re

description_issues = df[
    df["description"].notna() &
    (
        df["description"].str.contains(r"<[^>]+>", regex=True) |                  # HTML tags
        df["description"].ne(df["description"].str.strip()) |                     # Leading/trailing spaces
        df["description"].str.contains(r"\s{2,}", regex=True) |                   # Multiple spaces
        df["description"].str.contains(r"[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]", regex=True)  # Control chars
    )
]

print(f"Descriptions with issues: {len(description_issues)}")
display(description_issues[["profile_url", "description"]])

Descriptions with issues: 0

Empty DataFrame
Columns: [profile_url, description]
Index: []

In [9]:
import re

first_name_issues = df[
    df["first_name"].isna() |
    (df["first_name"].str.strip() == "") |
    (df["first_name"] != df["first_name"].str.strip()) |
    df["first_name"].fillna("").str.contains(r"\s{2,}") |
    df["first_name"].fillna("").str.contains(r"[0-9@#$%^&*_=+<>/\\|{}\[\]~`]")
]

print(f"First names with issues: {len(first_name_issues)}")
display(first_name_issues[["profile_url", "first_name"]])

First names with issues: 6

,profile_url,first_name
10,https://www.kentwood.com/bio/BrinckerhoffEmery,Brinckerhoff Emery & Associates
11,https://www.kentwood.com/bio/uhl,Bryan & Kris Uhl
44,https://www.kentwood.com/bio/ginaandkara2,Gina Lorenzen & Kara Couzens
121,https://www.kentwood.com/bio/pattygreg,Patty Ryan Anton & Greg Card
140,https://www.kentwood.com/bio/larkin,Sean & Debbie Larkin
158,https://www.kentwood.com/bio/dutzerteam,Thomas & Rosanne Dutzer

In [10]:
import pandas as pd
import re

# URL regex
url_pattern = re.compile(
    r'^https?://'
    r'(([A-Za-z0-9-]+\.)+[A-Za-z]{2,})'
    r'(:\d+)?'
    r'(/[^\s]*)?$',
    re.IGNORECASE
)

issues = []

# Top-level URL columns
url_cols = ["profile_url", "website", "image_url"]

for col in url_cols:
    if col in df.columns:
        mask = (
            df[col].fillna("").astype(str).str.strip().ne("") &
            ~df[col].astype(str).str.strip().str.match(url_pattern)
        )

        if mask.any():
            temp = df.loc[mask, ["profile_url", col]].copy()
            temp.insert(0, "row_no", temp.index + 1)
            temp["column"] = col
            temp.rename(columns={col: "invalid_value"}, inplace=True)
            issues.append(temp)

# Check URLs inside social dictionary
if "social" in df.columns:
    social_fields = ["facebook_url", "twitter_url", "linkedin_url"]

    for idx, value in df["social"].items():
        if isinstance(value, dict):
            # facebook, twitter, linkedin
            for key in social_fields:
                url = str(value.get(key, "")).strip()
                if url and not url_pattern.match(url):
                    issues.append(pd.DataFrame({
                        "row_no": [idx + 1],
                        "profile_url": [df.at[idx, "profile_url"]],
                        "column": [f"social.{key}"],
                        "invalid_value": [url]
                    }))

            # other_urls (list)
            other_urls = value.get("other_urls", [])
            if isinstance(other_urls, list):
                for url in other_urls:
                    url = str(url).strip()
                    if url and not url_pattern.match(url):
                        issues.append(pd.DataFrame({
                            "row_no": [idx + 1],
                            "profile_url": [df.at[idx, "profile_url"]],
                            "column": ["social.other_urls"],
                            "invalid_value": [url]
                        }))

if issues:
    result = pd.concat(issues, ignore_index=True)
    display(result)
    print(f"\nTotal invalid URLs found: {len(result)}")
else:
    print("No invalid URL values found.")

No invalid URL values found.

In [12]:
df.profile_url.duplicated().sum()

np.int64(0)

In [13]:
df.shape

(195, 19)

In [14]:
import json

duplicate_count = (
    df.applymap(
        lambda x: json.dumps(x, sort_keys=True)
        if isinstance(x, (list, dict))
        else x
    )
    .duplicated()
    .sum()
)

print("Duplicate rows:", duplicate_count)

Duplicate rows: 0

/tmp/ipykernel_11794/600954025.py:4: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(

In [15]:
req_cols = """first_name, middle_name, last_name, office_name, title, description, languages, image_url, address, city, state, country, zipcode, office_phone_numbers, agent_phone_numbers, email, website, social, profile_url"""

req_cols = [c.strip() for c in req_cols.split(",") if c.strip()]

missing = [c for c in req_cols if c not in df.columns]
extra = [c for c in df.columns if c not in req_cols]

print("Requirement columns:", len(req_cols))
print("File columns:", len(df.columns))
print("Missing:", missing)
print("Extra:", extra)
print("Order matches:", req_cols == list(df.columns))

Requirement columns: 19
File columns: 19
Missing: []
Extra: []
Order matches: False

In [16]:
import re

pattern = r'^\d+(\.\d+)?\s*م²$'

invalid = df[
    ~df["details"].fillna("").astype(str).str.match(pattern)
]

invalid.insert(0, "row_no", invalid.index + 1)

display(invalid[["row_no", "url", "details"]])

KeyError: 'details'

In [17]:
df.nunique()

profile_url             195
first_name              161
middle_name               8
last_name               173
image_url               195
office_name               8
address                   7
description             194
languages                14
social                  134
website                 146
email                     1
title                    54
country                   1
city                      5
zipcode                   6
state                     1
agent_phone_numbers     194
office_phone_numbers      7
dtype: int64

In [18]:
df.country.value_counts()

country
United States    195
Name: count, dtype: int64

In [19]:
df.state.value_counts()

state
CO    195
Name: count, dtype: int64

In [20]:
df[df.state == ""]

Empty DataFrame
Columns: [profile_url, first_name, middle_name, last_name, image_url, office_name, address, description, languages, social, website, email, title, country, city, zipcode, state, agent_phone_numbers, office_phone_numbers]
Index: []

In [21]:
df.country.value_counts()

country
United States    195
Name: count, dtype: int64

In [22]:
import pandas as pd

df1 = df.replace(r'^\s*$', pd.NA, regex=True)

empty_columns = df1.columns[df1.isna().all()]

print("Completely empty columns:")
print(list(empty_columns))

Completely empty columns:
['email']

In [23]:
import pandas as pd

# Treat empty strings and whitespace-only values as NA
df1 = df.replace(r'^\s*$', pd.NA, regex=True)

# Requirement empty columns
req_empty_cols =  """
"""

req_empty_cols = [c.strip() for c in req_empty_cols.split(",") if c.strip()]

# File empty columns
file_empty_cols = list(df1.columns[df1.isna().all()])

matching = sorted(set(req_empty_cols) & set(file_empty_cols))
expected_not_empty = sorted(set(req_empty_cols) - set(file_empty_cols))
unexpected_empty = sorted(set(file_empty_cols) - set(req_empty_cols))

print("Requirement empty columns :", len(req_empty_cols))
print("File empty columns        :", len(file_empty_cols))
print("Matching                  :", len(matching))
print("Expected empty but not empty:", expected_not_empty)
print("Unexpected empty columns     :", unexpected_empty)

Requirement empty columns : 0
File empty columns        : 1
Matching                  : 0
Expected empty but not empty: []
Unexpected empty columns     : ['email']

In [25]:
import re

url_pattern = re.compile(
    r'^(https?://)'
    r'([a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}'
    r'(/[^\s]*)?$'
)

invalid_url = df[
    df["website"].notna() &
    (df["website"].str.strip() != "") &
    ~df["website"].astype(str).str.match(url_pattern)
]

print(f"Invalid URLs: {len(invalid_url)}")

display(invalid_url[["website", "profile_url"]])

Invalid URLs: 0

Empty DataFrame
Columns: [website, profile_url]
Index: []

In [27]:
df.city.value_counts()

city
Denver              165
Ft Collins           19
Boulder               8
Dillon                2
Colorado Springs      1
Name: count, dtype: int64

In [28]:
duplicates = df[df.duplicated(subset="profile_url", keep=False)]

print(f"Duplicate URLs: {len(duplicates)}")
display(duplicates.sort_values("profile_url"))

Duplicate URLs: 0

Empty DataFrame
Columns: [profile_url, first_name, middle_name, last_name, image_url, office_name, address, description, languages, social, website, email, title, country, city, zipcode, state, agent_phone_numbers, office_phone_numbers]
Index: []

In [29]:
import re

url_pattern = re.compile(
    r'^(https?://)'
    r'([a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}'
    r'(/[^\s]*)?$'
)

invalid_url = df[
    df["image_url"].notna() &                      # Exclude NaN
    (df["image_url"].str.strip() != "") &         # Exclude empty strings
    ~df["image_url"].astype(str).str.match(url_pattern)
]

print(f"Invalid URLs: {len(invalid_url)}")
display(invalid_url[["image_url"]])

Invalid URLs: 0

Empty DataFrame
Columns: [image_url]
Index: []

In [31]:
import re

url_pattern = re.compile(
    r'^(https?://)'
    r'([a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}'
    r'(/[^\s]*)?$'
)

invalid_url = df[
    ~df["image_url"].fillna("").astype(str).str.match(url_pattern)
]

print(f"Invalid URLs: {len(invalid_url)}")
display(invalid_url[["image_url"]])

Invalid URLs: 0

Empty DataFrame
Columns: [image_url]
Index: []

In [32]:
empty_counts = (
    df.astype(str)
      .apply(lambda col: (col.str.strip() == "").sum())
)

print(empty_counts)

profile_url               0
first_name                0
middle_name             188
last_name                 8
image_url                 0
office_name               0
address                   0
description               1
languages                 0
social                    0
website                  30
email                   195
title                     0
country                   0
city                      0
zipcode                   0
state                     0
agent_phone_numbers       0
office_phone_numbers      0
dtype: int64

In [41]:
df[df.description == ""]

,profile_url,first_name,middle_name,last_name,image_url,office_name,address,description,languages,social,website,email,title,country,city,zipcode,state,agent_phone_numbers,office_phone_numbers
36,https://www.kentwood.com/bio/elise,Elise,,Marks,https://content.mediastg.net/Dynamic/RealEstate/company/624/account/539902/539902_06222023233404.jpg,Kentwood DTC,4949 South Niagara St 400,,[],{},https://elise.kentwood.com,,"Broker Associate, Realtor ®",United States,Denver,80237,CO,"[""(303) 947-0884""]","[""(303) 773-3399""]"

In [33]:
df.office_phone_numbers.value_counts()

office_phone_numbers
["(303) 773-3399"]    91
["(303) 331-1400"]    48
["(303) 820-2489"]    24
["(970) 300-1985"]    19
["303-785-3561"]      10
["970-300-1985"]       2
["719-259-3500"]       1
Name: count, dtype: int64

In [44]:
df[df['city'].isin(["Dillon", "Colorado Springs"])]

,profile_url,first_name,middle_name,last_name,image_url,office_name,address,description,languages,social,website,email,title,country,city,zipcode,state,agent_phone_numbers,office_phone_numbers
117,https://www.kentwood.com/bio/NoahBrooks,Noah,,Brooks,https://content.mediastg.net/Dynamic/RealEstate/company/624/account/6600175/6600175_04172026215716.jpg,Kentwood Mountain Properties,"265 Dillon Ridge Rd, Unit C/450","Noah and Danielle bring a dynamic partnership to the real estate experience. Noah, a former Director of the Ski Club Vail Freeride Team and a Warren Miller athlete, has a contagious enthusiasm for the outdoors that he shares with Danielle and their four boys. As residents of Clark, Colorado, they are often found exploring the mountains of North Routt County through hiking, skiing, snowmobiling, and biking. With over two decades of experience in real estate, Noah Brooks is a seasoned professional. He is a proud alumnus of Cherry Creek High School in Greenwood Village, Colorado, and the University of Colorado Boulder, where he majored in Economics with a Business Emphasis. While in college, he remodeled his first property to house the CU Ski Team in Winter Parksparking a passion that has since led him to remodel and sell more than 30 properties throughout Colorado. Noah also holds a Certification in Property Management from New York University. Danielle, a native of East Hampton, New York, studied Art and Photography at the University of Colorado Boulder. Her passion for healthy living led her and Noah to own and operate ranches in Colorado and Vermont, where they raised Himalayan yaks known for their lean, healthy meat. Through their ranch, Raddog Ranch, they even supplied meat to the Boston Red Sox. Danielle now owns and operates Neat and Nest, LLC in Clark, Colorado, specializing in the cleaning and maintenance of mountain homes. While not a licensed real estate agent, Danielle plays an integral role behind the scenes, offering valuable insight into home presentation, organization, and lifestyle considerations. Together, Noah and Danielle bring a wealth of knowledge in ranching and resort-area living, providing clients with a well-rounded perspective. Noahs extensive understanding of property values and features across marketsincluding Denver, Boulder, Golden, Conifer, Vail, Red Cliff, Steamboat Springs, Winter Park, Crested Butte, Clark, and Vermontallows him to expertly guide buyers and sellers through every step of the process. With Danielles eye for design and Noahs proven real estate expertise, clients benefit from both strategic guidance and thoughtful presentation. When you work with Noah, you gain not only a trusted real estate professional, but also the added support and insight that Danielle brings to the overall experience.",[],"{""facebook_url"": """", ""linkedin_url"": """", ""other_urls"": [""https://www.instagram.com/teambrookscolorado""], ""twitter_url"": """"}",https://NoahBrooks.kentwood.com,,"Broker Associate, Realtor®",United States,Dillon,80435,CO,"[""970-761-0678""]","[""970-300-1985""]"
124,https://www.kentwood.com/bio/PaulVandervort,Paul,,Vandervort,https://content.mediastg.net/Dynamic/RealEstate/company/624/account/6587716/6587716_03182026220550.jpg,Kentwood Southern Colorado,"1755 Telstar Drive, 3rd Floor","Paul Vandervort is a Broker Associate with Kentwood Real Estate, working with buyers, sellers, and investors across Colorado, with a strong focus on Colorado Springs. His work centers on helping clients navigate residential, luxury, and investment real estate with clear strategy, disciplined execution, and long-term perspective. Paul brings a capital-informed approach to real estate, supported by his background as a licensed mortgage originator and investor. This integrated experience allows him to help clients evaluate not only the property itself, but also how financing structure, timing, and risk affect the overall decision, particularly in new construction, luxury homes, and complex transactions. Prior to entering brokerage, Paul spent years working in high-end residential real estate environments as a producer and filmmaker, collaborating closely with real estate professionals, property owners, and investors. That experience sharpened his understanding of how properties are positioned, marketed, and transacted at the upper end of the residential market. A Colorado native, Paul was born in Aspen and grew up in Colorado Springs before spending time in California, giving him a grounded perspective on both local and coastal markets. He works extensively throughout Colorado Springs, including areas such as The Broadmoor, Old North End, Flying Horse, and Monument. Paul holds a Bachelor of Science in Business Administration from the Fowler College of Business at San Diego State University, with a focus on entrepreneurship, finance, and organizational behavior. His approach is consultative, precise, and execution-focused, with an emphasis on helping clients make confident, well-structured decisions from first conversation through closing.",[],{},https://www.paulvandervort.com,,"Broker Associate, Realtor®",United States,Colorado Springs,80920,CO,"[""719-428-5158""]","[""719-259-3500""]"
144,https://www.kentwood.com/bio/Soley,Soley,,Maria,https://content.mediastg.net/Dynamic/RealEstate/company/624/account/540016/540016_07022024201401.jpg,Kentwood Mountain Properties,"265 Dillon Ridge Rd, Unit C/450","Born and raised in Iceland, Soley Maria was drawn to Colorado for its endless sunshine, vibrant communities, and unparalleled mountain lifestyle. Since 2013, she has helped buyers, sellers, investors, and second-home owners navigate Colorados dynamic real estate market with a strategic, client-focused approach built on expertise, integrity, and long-term relationships. As a Broker Associate with Kentwood Real Estate Mountain Properties, Soley specializes in Colorados mountain communities, Boulder County, and the Denver metro area. Her experience spans luxury residences, mountain retreats, investment properties, vacation homes, and short-term rental opportunities, giving her clients valuable insight into both the lifestyle and financial aspects of real estate ownership. Before launching her real estate career, Soley built a foundation in sales, marketing, and customer experience with globally recognized brands including Toyota, Yamaha, and Chipotle. That background continues to shape her approach today, helping sellers position their properties effectively while providing buyers with a thoughtful, data-driven perspective throughout the transaction process. Soley earned dual degrees in Economics and Finance from the University of Colorado Boulder and later completed a Master of Public Administration with an emphasis in housing policy. Her academic background provides a deeper understanding of the economic, regulatory, and market forces that influence real estate decisions at both the local and statewide level. Beyond her work with clients, Soley is actively involved in industry leadership and housing advocacy. She serves on multiple committees with the Colorado Association of Realtors, including the Legislative Policy Committee, where she helps evaluate and provide input on issues affecting property owners, housing policy, and the real estate industry throughout Colorado. She also serves on the board of the Kentwood Cares Foundation, supporting charitable initiatives that strengthen communities across the state. Having called Colorado home for more than a decade, Soley embraces the lifestyle that attracts so many of her clients. Whether shes skiing, snowboarding, hiking, practicing yoga, playing tennis, exploring Colorados food and wine scene, or enjoying live music and the arts, she appreciates the unique balance of outdoor adventure and cultural vibrancy that defines life in Colorado. Whether guiding a first-time buyer, marketing a luxury home, identifying an investment opportunity, or helping a client find the perfect mountain escape, Soley combines market expertise, strategic thinking, and personalized service to help her clients achieve their real estate goals with confidence.","[""English"", ""Icelandic""]","{""facebook_url"": ""https://www.facebook.com/soleymariarealestate"", ""linkedin_url"": ""https://www.linkedin.com/in/soleymaria"", ""other_urls"": [""https://www.instagram.com/accounts/login/?next=/soleym/""], ""twitter_url"": """"}",https://www.soleymaria.com/,,"Broker Associate, Realtor®",United States,Dillon,80435,CO,"[""(970) 401-0304""]","[""970-300-1985""]"

In [34]:
df.title.value_counts()

title
Broker Associate, Realtor®                                                106
Broker Associate, Realtor ®                                                13
Broker Associate                                                            7
Senior Commercial Advisor                                                   5
Broker Associate, Realtor®, CNE                                             4
Broker Associates, Realtors ®                                               3
Kentwood Real Estate Services                                               3
Broker Associates, Realtors®                                                3
Broker Associate, Realtor®, MBA                                             2
Broker Associate, Emeritus Status                                           2
Commercial Advisor                                                          2
Broker Associate, Realtor®, CRS                                             2
Broker Associate, GRI, CRS                                                  2
Broker Associates, Realtors®, CRS                                           1
Broker Associates, Realtors®, SCRP                                          1
Realtors®, BPOR, CNE, SRS                                                   1
Broker Associate ABR,CRS                                                    1
Broker Associate/Founder                                                    1
Broker Associate, MBA, ABR, CRS, GRI, CLHMS, CDPE, MCNE                     1
Broker Associate, Realtor®, Certified Negotiation Expert                    1
Broker Associate, Realtor®, RCS-D™                                          1
Managing Broker, Broker Associate, Realtor ®                                1
Realtor®, SRS, SRES, CNHS                                                   1
Broker Associate, Realtor®, PSA                                             1
COO and Employing Broker                                                    1
Broker Associate, GRI, CRS, SRES, CIPS, CDPE, Broker/Founder                1
Broker Associate, Realtor®, GRI, CNE                                        1
Managing Broker of Kentwood Commercial, Senior Commercial Advisor           1
Broker Associate, Realtor®, GRI                                             1
Broker Associate, Realtor®, SRES, CRS                                       1
Broker Associate, RPA, CNE                                                  1
Commercial Broker, Residential Broker Associate, Realtor®                   1
Broker Associate, GRI, CRS, CIPS                                            1
Broker Associate, Realtor®, RSPS                                            1
Broker Associate, CRS, CNE                                                  1
Realtor®, GRI, ABR                                                          1
Broker Associate, Realtor®, CNE, CTA                                        1
Broker Associates                                                           1
Broker Associate, GRI, CRS, MRE, SRS, Emeritus Status                       1
Broker Associate, CNE, CIPS, RSPS, RENE                                     1
Realtor®, CREN, ABR                                                         1
Realtor®, CLHMS, CNE                                                        1
Broker Associate, Realtor®, SRES                                            1
Realtor®, CME, CREN, RENE                                                   1
Broker Associates, REALTORS, CNE, MCNE                                      1
Broker Associates, Realtors ®, GRI                                          1
Managing Broker of Kentwood City Properties & Boulder Valley, Realtor®      1
Broker Associate, SRES, RENE                                                1
Broker Associate, CRS, ABR, SRES                                            1
Broker Associate, Realtor®, MS, CNE                                         1
Broker Associate, CNE, ABR                                                  1
Realtor®, CMAS, CLMS, CDS                                                   1
Kentwood Northern Properties, Managing Broker | Realtor ®                   1
Broker Associate, Realtor®, MilRES                                          1
Name: count, dtype: int64

In [35]:
df.country.value_counts()

country
United States    195
Name: count, dtype: int64

In [37]:
df[df.website == ""]

,profile_url,first_name,middle_name,last_name,image_url,office_name,address,description,languages,social,website,email,title,country,city,zipcode,state,agent_phone_numbers,office_phone_numbers
4,https://www.kentwood.com/bio/BrentGilles,Brent,,Gilles,https://content.mediastg.net/Dynamic/RealEstate/company/624/account/6318785/6318785_07312023034421.jpg,Kentwood Cherry Creek,215 St. Paul Street #200,"Brent Gilles understands the difference between finding clients a house and finding them a home. The fundamental distinction, he believes, is that while there may be lots of houses to consider in a given market, only a handful may truly satisfy the needs and desires of his client. For Brent, his reputation as a highly respected realtor is less about location, location, location, and more about experience, experience, experience. His 28 years spent working in real estate enables him to think outside the box, structuring deals and transactions that help his clients feel great about their experience and know they have made a solid decision. Whether he is showing someone 5 homes or 50, Brent brings enthusiasm and passion to every client. Brent prides himself on working diligently to make sure everyone -- family, friend, client or even someone hes just met -- is made to feel important. Putting others first, he believes, brings happiness and success to all, a key factor that brings him a steady base of referrals and repeat clients. He has experienced a wide spectrum of market conditions during his 28 years as a residential broker and imparts that vast knowledge to his clients. Brents enthusiasm for his profession stems from the belief that every day is different, and every transaction is unique, beginning with a clients wants, needs and ultimately their goals. He uses his strong knowledge of current market conditions to successfully navigate transactions in a professional and thoughtful manner. A Colorado native, Brent is well-versed in the unique neighborhoods that are part and parcel of the Denver metro area. His familiarity with Denver and surrounding suburbs helps him match clients with areas that best suit their needs, and he works tirelessly to help them find the perfect home that will serve them now and in the future. His clients appreciate his candor, and he will not hesitate to point out aspects of a home they may not recognize, discussing pros and cons to ensure they have as much information as possible. Im a real people person and I take the time to listen and understand what is best for my client, Brent says. My goal is for every client to understand how we can together successfully meet their expectations. My clients value my honesty and know I will never encourage them to consider a property that is not aligned with their wants, needs and goals. An avid skier, Brent clicked into his first pair of skis at age three and could not get enough of the sport and gratitude for the surroundings. Eventually the passion for skiing and particularly moguls led to competing for the Winter Park Freestyle Ski Team. He also enjoys golf, tennis, volleyball, pickleball and loves to take advantage of Colorados endless outdoor activities!",[],{},,,"Broker Associate, Realtor®",United States,Denver,80206,CO,"[""720-217-8172""]","[""(303) 331-1400""]"
15,https://www.kentwood.com/bio/CarynGillman,Caryn,,Gillman,https://content.mediastg.net/Dynamic/RealEstate/company/624/account/6518158/6518158_02052026183143.png,Kentwood Northern Properties,2950 E Harmony Road #210,"You may know something about me, you may know nothing. Here's a short intro on me and I look forward to getting to know YOU, what you love and what is important to YOU! Meet Caryn :Proud mom of two energetic boys, a loving wife, outdoor enthusiast and dedicated Realtor. Caryn has 13 years of experience in Real Estate both locally and internationally, she is passionate about helping people and developing authentic connections built on transparency and trust. Caryn is known for her honesty, deep knowledge, and unwavering integrity. She is in constant communication with her clients as they go through the process, and she continually goes above and beyond the realtor call of duty. Caryn has a tenacious work ethics as both a homeowner, income property owner and realtor which makes her empathetic to clients as they experience the current real estate climate. Whether you're buying or selling, shell always have your best interests at heart, guiding you through the process with a personal touch and a smile! My personal motto : Do more of what YOU love! Here to help!","[""English"", ""Afrikaans""]","{""facebook_url"": ""https://www.facebook.com/caryngillmanrealtor"", ""linkedin_url"": ""https://www.linkedin.com/in/caryn-gillman/"", ""other_urls"": [""https://www.instagram.com/caryn.gillman/""], ""twitter_url"": """"}",,,"Broker Associate, Realtor®",United States,Ft Collins,80528,CO,"[""970-689-4610""]","[""(970) 300-1985""]"
17,https://www.kentwood.com/bio/charlotte,Charlotte,,Connolly,https://content.mediastg.net/Dynamic/RealEstate/company/624/account/645458/645458_06082023225246.jpeg,Kentwood DTC,4949 South Niagara St 400,"Charlotte lives by the mantra that first impressions are everything. Before getting her real estate license, Charlotte honed her design eye as a buyer in womens contemporary and designer clothing. She built a loyal clientele with her strong sense of fashion and the desire to make everyone look and feel like the best version of themselves. Since relocating to Denver, she helped numerous clients transform their wardrobes and closets. She has translated that love of aesthetics to real estate. She is able to see potential in almost every home she enters whether its a fixer upper or a new build that needs your personal stamp. She loves staging homes by bringing in furniture, art, and accessories to ensure your home feels unique, modern, and stylish. She uses her past experience in some of the best closets in Denver to help edit and organize your home before you list. Small details matter, and she wants your home to shine the minute it hits the market. Charlotte attended Tulane University in New Orleans where her love of historic architecture and design was cemented. She has a particular affinity for homes with a bit of a past. Her clients value her attention to detail and no-nonsense east coast sensibility. She will always tell you what you need to hear rather than what you want to hear. The process of buying a home (whether its your first or last) can be confusing and stressful, and she aims to walk you through every step of the way with a little bit of humor thrown in for good measure. Charlotte jokes that she is probably the least Colorado person in all of Denver. She has never skied in her life and has zero desire to ever hike a 14-er. She will work 24-7 if you let her, but when she takes that rare time off, she loves playing tennis, entertaining friends with a fabulous dinner party, and cheering for all the Washington, DC sports teams even when theyre terrible.",[],{},,,"Broker Associate, Realtor®",United States,Denver,80237,CO,"[""(720) 486-9257""]","[""(303) 773-3399""]"
23,https://www.kentwood.com/bio/ConnorDonahue,Connor,,Donahue,https://content.mediastg.net/Dynamic/RealEstate/company/624/account/4189956/4189956_06082023225249.jpeg,Kentwood Commercial,215 St. Paul Street #200,"Since moving to Denver in 2016, Connor has gained ample experience in Denvers commercial real estate market. Specializing in landlord representation, tenant/occupier services and investment sales, Conner leverages his background to create custom real estate solutions for all of his clients that include: leasing, subleasing, renewals, relocation, consolidation & expansion, and build-to-suit opportunities. Connors holistic approach not only satisfies the short-term needs of his clients, but also anticipates and achieves their long-term objectives making him a trusted strategic business advisor and resource. Prior to joining Kentwood Commercial, Connor was a leasing and sales specialist with NAI Shames Makovsky and Coldwell Banker Commercial Advisors, focusing his efforts in Denvers Central Business District (CBD) and downtown periphery. Connor graduated from the University of Colorado with a bachelors degree in communications and advertising. A Montana native, he is an avid fly-fisherman, enjoys skiing and golf and taking advantage of both the bustling Denver scene and the tranquility of the mountains. Relevant transactions: Tenant & Landlord representation completing over 390,000sf in leasing and sales assignments totaling over $70,000,000 in transaction value. Relevant transactions include: VF Corporation US Department of Veteran Affairs Urology Center of Colorado CoreSite Cannon Design Experience: 2022-Present: Broker, Kentwood Commercial, Denver, CO 2017-2022: Broker, NAI Shames Makovsky, Denver, CO 2016-2017: Broker, Coldwell Banker Commercial Advisors, Denver, CO Affiliations EO Colorado National Federal Developers Association (NFDA)",[],{},,,Senior Commercial Advisor,United States,Denver,80206,CO,"[""406.871.3924""]","[""303-785-3561""]"
27,https://www.kentwood.com/bio/david,David,,Morrison,https://content.mediastg.net/Dynamic/RealEstate/company/624/account/540022/540022_08152023200623.jpg,Kentwood Commercial,215 St. Paul Street #200,"David Morrison has 35 years of commercial experience in Denver with Oxford Ansco, Brookfield Properties, CBRE, Grubb & Ellis, and Colliers International. He has leased over 3M sqft of office space and 500 lease transactions and has done over $100M of sales volume.",[],{},,,Kentwood Real Estate Services,United States,Denver,80206,CO,"[""(303) 324-9053""]","[""303-785-3561""]"
30,https://www.kentwood.com/bio/DenaP,Dena,,Reeves-Pastorini,https://content.mediastg.net/Dynamic/RealEstate/company/624/account/6414463/6414463_11032023225742.jpg,Kentwood City Properties,215 Saint Paul Street #200,"Known as Downtown Dena, Dena Reeves-Pastorini is a trusted Downtown Denver real estate expert with over 26 years of experience living and working in the heart of the city. With in-depth knowledge of the Union Station redevelopment, LoHi rezoning, and the ever-evolving LoDo dining and lifestyle scene, she stays ahead of market trends that impact Downtown Denver homes for sale, luxury condos, and urban real estate investments. Her hyper-local expertise and passion for Denvers city lifestyle make her a go-to Denver Realtor for buyers and sellers seeking a competitive edge. As a new development specialist in Denver, Dena was one of the first residents of Riverfront Park and worked directly with East West Partners, helping sell homes in one of Denvers most sought-after communities near Commons Park. Early in her career, she earned the Silver Rookie of the Year Award from the Colorado Home Builders Association and went on to contribute to over $500 million in Denver new construction and development sales. Expanding her reach in 2011, Dena became a top-producing Central Denver real estate agent, with more than $50 million in sales across the citys most desirable neighborhoods. Dena's expertise spans Downtown Denver condos, LoHi real estate, LoDo lofts, and luxury urban properties, as well as nearby and luxury communities including RiNo, Highland, Five Points, Capitol Hill, City Park West, Baker, Cherry Creek North, Hilltop, Congress Park, and Washington Parkproviding clients with strategic guidance and results-driven service across Denvers most vibrant and sought-after areas. Originally from Houston, Dena graduated magna cum laude from the University of Houston before moving to Colorado in 1991. She previously lived and worked in the Vail Valley and brings a diverse professional background, including business ownership, television production, and on-air media experience. Deeply connected to the community, she supports organizations such as the Denver Art Museum, Project Angel Heart, Denver Rescue Mission, CultureHaus, and the Museum of Contemporary Art Denver. When Denas not helping clients buy and sell Downtown Denver real estate, she enjoys skiing, theater, music, and fully embracing the vibrant Denver lifestyle she proudly calls home.",[],{},,,Broker Associate,United States,Denver,80206,CO,"[""720-233-9096""]","[""(303) 820-2489""]"
33,https://www.kentwood.com/bio/dierk,Dierk,,Herbermann,https://content.mediastg.net/Dynamic/RealEstate/company/624/account/539876/539876_06082023225312.jpeg,Kentwood DTC,4949 South Niagara St 400,"Dierk Herbermann is Chief Operating Officer and Employing Broker at Kentwood Real Estate. Kentwood serves communities along the front range Denver metropolitan area to Fort Collins and northern Colorado and operates residential and commercial brokerage, leasing and property management, and a subsidiary mortgage company, Prosperity Home Mortgage. Kentwood Real Estate is an affiliate of HomeServices of America. Dierks vast experience leading real estate brokerages as General Manager and Counsel in the San Francisco Bay area and most recently in Denver for LIV Sothebys, prior to joining Kentwood Real Estate, provide the growing executive team an opportunity to expand their focus on business development opportunities and strategy, while remaining solidly mindful of their highly successful brokers and brand. Im thrilled to be returning to a local brand with a Leading RE and Luxury Portfolio Connection, says Dierk. Its where I feel most at home in brokerage, and where the customer is always best served. While in San Francisco, Dierk played a role on a collaborative management team at Paragon Real Estate Group in their becoming the #1 brokerage in San Francisco in 2017. A management team operated much like Kentwoods. Prior to moving into real estate management, Dierk was a top sales agent. An experience which today provides him the empathy to understand the day to day life of an agent/broker and has helped him successfully build offices and companies.",[],{},,,COO and Employing Broker,United States,Denver,80237,CO,[],"[""(303) 773-3399""]"
43,https://www.kentwood.com/bio/GhassanK,Ghassan,,Kanafani,https://content.mediastg.net/Dynamic/RealEstate/company/624/account/6375975/6375975_03252026171512.jpg,Kentwood Cherry Creek,215 St. Paul Street #200,"Are you ready to embark on your journey to homeownership? Look no further I'm here to help make your real estate dreams a reality! With over two decades of experience in the dynamic world of real estate, I've worn many hats from helping individuals like you buy and sell homes to guiding investments in properties, arranging mortgages, and overseeing home development projects. Your passion for finding the right home and achieving your real estate goals is my driving force. What sets me apart? I'm not just a realtor; I'm also a seasoned mortgage lender. This dual expertise gives you a unique advantage, allowing you to navigate both sides of the transaction with confidence. You deserve the best deal possible, and I know the ins and outs, the hurdles, and the shortcuts to get you there. Your schedule is my priority. I'm available seven days a week, and I'll gladly work around your evenings to accommodate your needs. Communication is key, and I promise to keep the lines open and transparent throughout the entire process. Whether you're a first-time buyer stepping into the world of homeownership or a seasoned pro looking for your forever home, I'm here to simplify the process for you. My goal is to see you wear a smile of satisfaction throughout your journey, from the first showing to the final closing. Let's turn your homeownership dreams into reality together. Reach out to me today, and let's get started on your path to the perfect home.",[],"{""facebook_url"": ""https://www.facebook.com/GhassanKanafaniRealtor/"", ""linkedin_url"": """", ""other_urls"": [], ""twitter_url"": """"}",,,"Broker Associate, Realtor®",United States,Denver,80206,CO,"[""619-300-2390""]","[""(303) 331-1400""]"
47,https://www.kentwood.com/bio/HannahStrunc,Hannah,,Strunc,https://content.mediastg.net/Dynamic/RealEstate/company/624/account/6513446/6513446_07312024202816.jpg,Kentwood DTC,4949 South Niagara St 400,"As a third-generation real estate professional and broker with Kentwood Real Estate at the Denver Tech Center, I combine a lifelong passion for real estate with a strong background in finance, marketing, and negotiation. I earned dual BSBA degrees in Finance and Marketing and an MBA from the University of Denver, and previously worked as a Landman specializing in title research and property acquisitions in the oil and gas industry. This experience gives my clients a unique advantage when navigating complex transactions. Originally from Iowa but deeply connected to Colorado, I am committed to providing exceptional service, meticulous attention to detail, and a seamless experience for buyers and sellers alike. Outside of real estate, my husband and I enjoy raising our two young children, renovating our home, and spending as much time in the mountains as possible.",[],{},,,"Broker Associate, Realtor®, MBA",United States,Denver,80237,CO,"[""515-988-4590""]","[""(303) 773-3399""]"
59,https://www.kentwood.com/bio/jvanderhule,Jeff,,Vanderhule,https://content.mediastg.net/Dynamic/RealEstate/company/624/account/6183211/6183211_06262023223932.jpg,Kentwood City Properties,215 Saint Paul Street #200,"Jeff VanDerhule is a true Colorado native, having spent the majority of his life in the Centennial and Aurora areas. He is proud to call these places home and has a deep appreciation for the beauty, culture, and community of the Denver Metro area. As an experienced real estate agent, selling over 100 homes in Denver Metro, Jeff thrives on helping his clients through some of their biggest life transitions. He is passionate about helping people find their dream homes or sell their properties for the best possible price, and he takes great pride in delivering exceptional results for his clients. Jeff's drive for client excellence and passion for helping as many people as possible led him to Kentwood, where he has become a highly respected and successful agent. His experience with project management, client satisfaction, and clear communication has been instrumental in his career as a real estate professional, and he has built a reputation for providing personalized, one-on-one service and building lasting relationships with his clients. Whether you are buying or selling a home, Jeff has the knowledge, expertise, and resources to guide you through every step of the process. He takes the time to understand your unique needs and goals, and he works tirelessly to help you achieve your desired outcomes. With his exceptional communication skills, attention to detail, and strong work ethic, Jeff is a top-performing agent who you can trust to deliver exceptional results. In his free time, Jeff enjoys exploring the great outdoors and spending time with his family. If you're looking for a real estate agent who is dedicated to your success and has a deep understanding of the Denver Metro area, look no further than Jeff VanDerhule.",[],"{""facebook_url"": """", ""linkedin_url"": ""https://www.linkedin.com/in/jeff-vanderhule-79668210/"", ""other_urls"": [""https://www.instagram.com/jeffvanderhule/""], ""twitter_url"": """"}",,,"Broker Associate, Realtor®",United States,Denver,80206,CO,"[""(303) 667-2563""]","[""(303) 820-2489""]"

In [31]:
df.image_url.value_counts()

image_url
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6365079/6365079_11292023150828.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181848/6181848_06222023011629.jpeg    1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181847/6181847_06222023011312.jpeg    1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181796/6181796_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6568451/6568451_02062026170958.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181661/6181661_06162023213933.jpeg    1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6593859/6593859_03232026123921.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181658/6181658_01082025211247.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6387774/6387774_10242023194810.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6563140/6563140_05292026152945.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6485358/6485358_02052024165157.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6551277/6551277_05162025195926.jpeg    1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181775/6181775_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6212596/6212596_06262023162420.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6596169/6596169_03242026180806.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6604212/6604212_06242026135557.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6555067/6555067_06202025125004.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6536752/6536752_01032025173329.jpeg    1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6518613/6518613_10082024162247.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181849/6181849_06212023191012.jpeg    1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181760/6181760_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181823/6181823_05112026134200.png     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181726/6181726_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181850/6181850_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6540499/6540499_02112025162732.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181851/6181851_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6617155/6617155_06172026153803.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181691/6181691_06022025231805.png     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181631/6181631_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181720/6181720_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181894/6181894_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181737/6181737_06222023194006.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181878/6181878_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181776/6181776_12132024151843.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6534120/6534120_11192024150537.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181779/6181779_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181740/6181740_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181682/6181682_05052023171728.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6464265/6464265_01162024190456.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6587163/6587163_03172026195845.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6400495/6400495_10032025220433.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6588695/6588695_02032026212337.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181852/6181852_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181715/6181715_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181810/6181810_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181892/6181892_05152023140332.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181696/6181696_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6538387/6538387_01032025185850.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6616964/6616964_07062026185436.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6517020/6517020_06272025132150.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6564236/6564236_08242025202515.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181717/6181717_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181756/6181756_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6606200/6606200_05292026162614.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181854/6181854_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6618192/6618192_06162026132259.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181777/6181777_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181774/6181774_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6540502/6540502_02072025222710.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181828/6181828_10152024184521.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181858/6181858_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181716/6181716_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6491706/6491706_01312024164050.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6541263/6541263_02132025160441.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6553005/6553005_06112025141847.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6514226/6514226_06252024174330.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6410287/6410287_11172023201144.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6257727/6257727_06082023181041.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181657/6181657_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6286589/6286589_07202023203750.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6557313/6557313_02102026193520.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181805/6181805_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181638/6181638_05292026155051.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181855/6181855_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6233392/6233392_04172026150601.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181781/6181781_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6592049/6592049_03102026165647.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181736/6181736_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6573136/6573136_10242025142231.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181701/6181701_01072026203715.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6419568/6419568_11292023150721.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181856/6181856_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6588697/6588697_02032026212252.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6571404/6571404_10132025162844.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181662/6181662_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181865/6181865_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6606205/6606205_05292026143242.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6278584/6278584_06222023154128.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181895/6181895_06172024194155.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181693/6181693_07092026161211.png     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181873/6181873_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181817/6181817_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181809/6181809_03052025174714.jpeg    1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181815/6181815_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6602924/6602924_06052026151315.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6560541/6560541_08042025142136.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6574025/6574025_11182025164021.png     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181719/6181719_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181769/6181769_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6591512/6591512_07172026160644.png     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6602935/6602935_05012026195128.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6554921/6554921_06242025001816.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181695/6181695_10182023184622.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181875/6181875_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181722/6181722_05132025224026.png     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6361775/6361775_01092026203912.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181902/6181902_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6519597/6519597_10242024184303.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181812/6181812_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181735/6181735_11202025170832.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181753/6181753_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6286632/6286632_07242023155529.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6587166/6587166_01212026162621.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6603665/6603665_05082026160007.png     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6557309/6557309_08262025182046.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6556638/6556638_07152025171700.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6571793/6571793_05082026132625.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6536933/6536933_01212026181341.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6505250/6505250_03052024160149.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6581984/6581984_01072026183349.jpeg    1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6511011/6511011_05072026135930.jpeg    1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6602923/6602923_05012026195653.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181730/6181730_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6539456/6539456_02072025222818.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181741/6181741_01152025221259.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6579304/6579304_12112025181253.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6480131/6480131_01292024162429.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181729/6181729_06152023230435.jpeg    1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181824/6181824_05292025121533.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181891/6181891_06232025223836.jpeg    1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6316430/6316430_05072026135354.png     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181818/6181818_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181833/6181833_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181794/6181794_03182024155916.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181725/6181725_06152023230215.jpeg    1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181765/6181765_10102025151807.jpeg    1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6559842/6559842_09092025160828.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181666/6181666_03162026210230.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181628/6181628_04182024144202.jpeg    1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181783/6181783_01122026181146.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6511013/6511013_05032024195317.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6553656/6553656_06112025142233.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181839/6181839_03032026162608.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181797/6181797_07232026143305.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6553004/6553004_01162026160420.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6516460/6516460_08202024213001.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6507829/6507829_04082024145315.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6571601/6571601_10132025162744.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181886/6181886_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6231289/6231289_02112026150459.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6505270/6505270_03012024144705.jpeg    1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181727/6181727_10162024171431.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181867/6181867_04132026164520.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181814/6181814_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181861/6181861_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181748/6181748_02132025192429.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6607003/6607003_05292026162547.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181860/6181860_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181888/6181888_06222023003514.jpeg    1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6579733/6579733_12112025181442.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6347716/6347716_09122023194326.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6257728/6257728_06132023192032.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181780/6181780_05092023221522.jpeg    1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6588696/6588696_02032026211935.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181903/6181903_10162024171511.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181763/6181763_06222023004359.jpeg    1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181711/6181711_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181640/6181640_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181670/6181670_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181880/6181880_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6511014/6511014_05022024212854.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181803/6181803_03272023142000.jpg     1
Name: count, dtype: int64

In [32]:
df.image_url.duplicated().sum()

np.int64(0)

In [33]:
df.columns

Index(['profile_url', 'first_name', 'middle_name', 'last_name', 'image_url',
       'office_name', 'address', 'description', 'languages', 'social',
       'website', 'email', 'title', 'country', 'city', 'zipcode', 'state',
       'agent_phone_numbers', 'office_phone_numbers'],
      dtype='object')

In [34]:
df.profile_url.duplicated().sum()

np.int64(0)

In [35]:
# Find records with duplicate image_url
duplicates = df[df.duplicated(subset=["image_url"], keep=False)] \
    .reset_index(names="row_no") \
    .sort_values("image_url")

print(f"Duplicate image URLs: {duplicates['image_url'].nunique()}")
print(duplicates[["row_no", "profile_url", "image_url"]])

Duplicate image URLs: 0
Empty DataFrame
Columns: [row_no, profile_url, image_url]
Index: []

In [36]:
duplicate_records = (
    df.reset_index(names="row_no")
      .loc[lambda x: x.duplicated(subset=["image_url"], keep=False)]
      .sort_values("image_url")
)

duplicate_records

Empty DataFrame
Columns: [row_no, profile_url, first_name, middle_name, last_name, image_url, office_name, address, description, languages, social, website, email, title, country, city, zipcode, state, agent_phone_numbers, office_phone_numbers]
Index: []

In [37]:
print(df["image_url"].isna().sum())
print(df["image_url"].eq("").sum())   # empty strings

0
0

In [38]:
print(df["image_url"].nunique(dropna=True))

172

In [39]:
print(df["image_url"].value_counts(dropna=False).head(30))

image_url
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6365079/6365079_11292023150828.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181848/6181848_06222023011629.jpeg    1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181847/6181847_06222023011312.jpeg    1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181796/6181796_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6568451/6568451_02062026170958.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181661/6181661_06162023213933.jpeg    1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6593859/6593859_03232026123921.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181658/6181658_01082025211247.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6387774/6387774_10242023194810.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6563140/6563140_05292026152945.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6485358/6485358_02052024165157.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6551277/6551277_05162025195926.jpeg    1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181775/6181775_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6212596/6212596_06262023162420.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6596169/6596169_03242026180806.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6604212/6604212_06242026135557.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6555067/6555067_06202025125004.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6536752/6536752_01032025173329.jpeg    1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6518613/6518613_10082024162247.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181849/6181849_06212023191012.jpeg    1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181760/6181760_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181823/6181823_05112026134200.png     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181726/6181726_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181850/6181850_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6540499/6540499_02112025162732.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181851/6181851_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6617155/6617155_06172026153803.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181691/6181691_06022025231805.png     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181631/6181631_03272023142000.jpg     1
https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181720/6181720_03272023142000.jpg     1
Name: count, dtype: int64

In [40]:
vc = df["image_url"].value_counts()

print(vc[vc > 1])

Series([], Name: count, dtype: int64)

In [13]:
import ast
import re
import pandas as pd

phone_cols = ["agent_phone_numbers", "office_phone_numbers"]

# Allowed: digits, spaces, +, -, (, )
phone_pattern = re.compile(r'^[\d\s()+-]+$')

for col in phone_cols:
    invalid_rows = []

    for idx, val in df[col].items():

        if pd.isna(val) or val == "":
            continue

        # Convert string representation of list to list
        if isinstance(val, str):
            try:
                phones = ast.literal_eval(val)
            except Exception:
                phones = [val]
        else:
            phones = val

        if not isinstance(phones, list):
            phones = [phones]

        for phone in phones:
            phone = str(phone).strip()

            # Ignore empty entries
            if phone == "":
                continue

            # Check invalid characters
            if not phone_pattern.fullmatch(phone):
                invalid_rows.append(idx)
                break

    if invalid_rows:
        print(f"\n{col}: {len(invalid_rows)} invalid records")
        print(df.loc[invalid_rows, [col]])
    else:
        print(f"\n{col}: No invalid phone numbers found.")

KeyError: 'agent_phone_numbers'

In [42]:
df[df.middle_name == ""]

                                                    profile_url  first_name  \
0           https://www.robertsbrothers.com/bio/cherishtrocchio     Cherish
2               https://www.robertsbrothers.com/bio/chrisclarke       Chris
3              https://www.robertsbrothers.com/bio/chrissimoore     Chrissi
4            https://www.robertsbrothers.com/bio/cindynicholson       Cindy
5               https://www.robertsbrothers.com/bio/clintmorgan       Clint
6              https://www.robertsbrothers.com/bio/clydestewart       Clyde
7              https://www.robertsbrothers.com/bio/colleenbowen     Colleen
8             https://www.robertsbrothers.com/bio/conniekillian      Connie
9            https://www.robertsbrothers.com/bio/danielletaylor    Danielle
10            https://www.robertsbrothers.com/bio/dannydriskell       Danny
11                  https://www.robertsbrothers.com/bio/deerowe         Dee
12               https://www.robertsbrothers.com/bio/devinscott       Devin
13              https://www.robertsbrothers.com/bio/dianehunter       Diane
14            https://www.robertsbrothers.com/bio/donnafaulkner       Donna
15                https://www.robertsbrothers.com/bio/dorismith        Dori
16            https://www.robertsbrothers.com/bio/dottiekenoyer      Dottie
17              https://www.robertsbrothers.com/bio/drereynolds         Dre
18               https://www.robertsbrothers.com/bio/duncancrow      Duncan
19             https://www.robertsbrothers.com/bio/edmundzoghby      Edmund
20           https://www.robertsbrothers.com/bio/elainesessions      Elaine
21         https://www.robertsbrothers.com/bio/eliesemcallister      Eliese
22                https://www.robertsbrothers.com/bio/ellenginn       Ellen
23              https://www.robertsbrothers.com/bio/emilihansen       Emili
24              https://www.robertsbrothers.com/bio/emilybarber       Emily
25          https://www.robertsbrothers.com/bio/ernestbulwinkle      Ernest
26                https://www.robertsbrothers.com/bio/evanburns        Evan
27           https://www.robertsbrothers.com/bio/frankiegregory     Frankie
28                  https://www.robertsbrothers.com/bio/genefox        Gene
30           https://www.robertsbrothers.com/bio/harrisonbixler    Harrison
31               https://www.robertsbrothers.com/bio/hopebrooks        Hope
32                https://www.robertsbrothers.com/bio/hopebrown        Hope
33              https://www.robertsbrothers.com/bio/ivythompson         Ivy
34              https://www.robertsbrothers.com/bio/JamalTipton       Jamal
35               https://www.robertsbrothers.com/bio/jameebooth       Jamee
36           https://www.robertsbrothers.com/bio/jamesonpedrosa     Jameson
37              https://www.robertsbrothers.com/bio/jamesossler       James
38   https://www.robertsbrothers.com/bio/janetboullemetukangsin       Janet
39                https://www.robertsbrothers.com/bio/jasonpugh       Jason
40          https://www.robertsbrothers.com/bio/jenniferjohnson    Jennifer
41              https://www.robertsbrothers.com/bio/jeremysharp      Jeremy
42            https://www.robertsbrothers.com/bio/joeburkholder         Joe
43                  https://www.robertsbrothers.com/bio/joeemer         Joe
44           https://www.robertsbrothers.com/bio/johnnyjernigan      Johnny
45                  https://www.robertsbrothers.com/bio/joycave         Joy
46                 https://www.robertsbrothers.com/bio/joyguinn         Joy
47             https://www.robertsbrothers.com/bio/juliebrannon       Julie
48            https://www.robertsbrothers.com/bio/juliemitchell       Julie
49              https://www.robertsbrothers.com/bio/katiemiller       Katie
50           https://www.robertsbrothers.com/bio/katrinaaddison     Katrina
51                https://www.robertsbrothers.com/bio/kaycorley         Kay
52               https://www.robertsbrothers.com/bio/kevinloper       Kevin
53          https://www.robertsbrothers.com/bio/KimberlynMiller   Kimberlyn
54                 https://www.robertsbrothers.com/bio/kimklyce         Kim
55              https://www.robertsbrothers.com/bio/kistrascott      Kistra
56             https://www.robertsbrothers.com/bio/kristihunter      Kristi
57             https://www.robertsbrothers.com/bio/kristyharper      Kristy
58          https://www.robertsbrothers.com/bio/krystalmccollum     Krystal
59                https://www.robertsbrothers.com/bio/kulagandy        Kula
60                 https://www.robertsbrothers.com/bio/kymtrest         Kym
61           https://www.robertsbrothers.com/bio/ladonyamerrell     LaDonya
62              https://www.robertsbrothers.com/bio/lancelawley       Lance
63                https://www.robertsbrothers.com/bio/larrycole       Larry
64              https://www.robertsbrothers.com/bio/latwilahall     Latwila
65            https://www.robertsbrothers.com/bio/lauragerhardt       Laura
66            https://www.robertsbrothers.com/bio/laurasantiago       Laura
67              https://www.robertsbrothers.com/bio/laurawerner       Laura
68             https://www.robertsbrothers.com/bio/laurendobson      Lauren
69            https://www.robertsbrothers.com/bio/laurenwhigham      Lauren
70               https://www.robertsbrothers.com/bio/lilymizell        Lily
71        https://www.robertsbrothers.com/bio/lolitaelkartabani      Lolita
72          https://www.robertsbrothers.com/bio/lorenagregorius      Lorena
73               https://www.robertsbrothers.com/bio/lynneweeks       Lynne
74              https://www.robertsbrothers.com/bio/maddypowell       Maddy
75        https://www.robertsbrothers.com/bio/madelineculpepper    Madeline
76            https://www.robertsbrothers.com/bio/mallorymosley     Mallory
78               https://www.robertsbrothers.com/bio/mariechalk       Marie
79              https://www.robertsbrothers.com/bio/mariemiller       Marie
80              https://www.robertsbrothers.com/bio/markpittman        Mark
82              https://www.robertsbrothers.com/bio/maysamsalim      Maysam
83                 https://www.robertsbrothers.com/bio/mdhudson          MD
84              https://www.robertsbrothers.com/bio/megmcgovern         Meg
85            https://www.robertsbrothers.com/bio/melaniesusman     Melanie
86            https://www.robertsbrothers.com/bio/melissaparent     Melissa
87          https://www.robertsbrothers.com/bio/MichaelSubirats     Michael
88            https://www.robertsbrothers.com/bio/michelleautio    Michelle
89             https://www.robertsbrothers.com/bio/mikereynolds        Mike
90              https://www.robertsbrothers.com/bio/nancyhughes       Nancy
91           https://www.robertsbrothers.com/bio/nancyraulerson       Nancy
92          https://www.robertsbrothers.com/bio/natalyabaranyuk     Natalya
94             https://www.robertsbrothers.com/bio/NikkiBraxton       Nikki
95               https://www.robertsbrothers.com/bio/olganelson        Olga
96             https://www.robertsbrothers.com/bio/pamelapierce      Pamela
97             https://www.robertsbrothers.com/bio/paulascruggs       Paula
98               https://www.robertsbrothers.com/bio/peggylents       Peggy
99            https://www.robertsbrothers.com/bio/peterflammini       Peter
100           https://www.robertsbrothers.com/bio/pleasuredavis    Pleasure
101            https://www.robertsbrothers.com/bio/rachelhodges      Rachel
102         https://www.robertsbrothers.com/bio/rhondaledbetter      Rhonda
103           https://www.robertsbrothers.com/bio/richardharski     Richard
104                 https://www.robertsbrothers.com/bio/robbarr         Rob
105            https://www.robertsbrothers.com/bio/robertdubose      Robert
106          https://www.robertsbrothers.com/bio/robertwilliams      Robert
107              https://www.robertsbrothers.com/bio/ronwallace         Ron
108              https://www.robertsbrothers.com/bio/ruthgrubbs        Ruth
109          https://www.robertsbrothers.com/bio/sandraeldridge      Sandra
110              https://www.robertsbrothers.com/bio/sandyfrost       Sandy
111               https://www.robertsbrothers.com/bio/scottgill       Scott
112            https://www.robertsbrothers.com/bio/scottjohnsey       Scott
113         https://www.robertsbrothers.com/bio/sebastiaansmits  Sebastiaan
114               https://www.robertsbrothers.com/bio/sethkruse        Seth
115             https://www.robertsbrothers.com/bio/shaibrandon        Shai
116         https://www.robertsbrothers.com/bio/shaundamatthews     Shaunda
117            https://www.robertsbrothers.com/bio/shawnjenkins       Shawn
118         https://www.robertsbrothers.com/bio/sherryarchibald      Sherry
119             https://www.robertsbrothers.com/bio/skipherndon        Skip
120          https://www.robertsbrothers.com/bio/SomerlynBouler    Somerlyn
121          https://www.robertsbrothers.com/bio/spencertrimble     Spencer
122         https://www.robertsbrothers.com/bio/stephaniefowler   Stephanie
123           https://www.robertsbrothers.com/bio/stevemccollum       Steve
124             https://www.robertsbrothers.com/bio/susanpascoe       Susan
125           https://www.robertsbrothers.com/bio/sydneyburgess      Sydney
126          https://www.robertsbrothers.com/bio/sydneyferguson      Sydney
127          https://www.robertsbrothers.com/bio/tamaracosgrove      Tamara
128               https://www.robertsbrothers.com/bio/tammycurl       Tammy
129          https://www.robertsbrothers.com/bio/taylormedeiros      Taylor
130                https://www.robertsbrothers.com/bio/timbates         Tim
131            https://www.robertsbrothers.com/bio/tomeshaperry     Tomesha
132               https://www.robertsbrothers.com/bio/toribritt        Tori
133            https://www.robertsbrothers.com/bio/traceygrimes      Tracey
134           https://www.robertsbrothers.com/bio/trevellperdue     Trevell
135            https://www.robertsbrothers.com/bio/triciagraham      Tricia
136            https://www.robertsbrothers.com/bio/valeriebrown     Valerie
137          https://www.robertsbrothers.com/bio/vanessastinson     Vanessa
138          https://www.robertsbrothers.com/bio/wendydickerson       Wendy
139           https://www.robertsbrothers.com/bio/whitneytucker     Whitney
140        https://www.robertsbrothers.com/bio/AlicenBrizendine      Alicen
141              https://www.robertsbrothers.com/bio/alyssalong      Alyssa
142            https://www.robertsbrothers.com/bio/amandahasiak      Amanda
143             https://www.robertsbrothers.com/bio/amberbaxter       Amber
144             https://www.robertsbrothers.com/bio/amberperdue       Amber
145               https://www.robertsbrothers.com/bio/amybusbee         Amy
146             https://www.robertsbrothers.com/bio/andreasasso      Andrea
149           https://www.robertsbrothers.com/bio/apriljohnston       April
150             https://www.robertsbrothers.com/bio/ashleyduffy      Ashley
151          https://www.robertsbrothers.com/bio/barbaraandrews     Barbara
152             https://www.robertsbrothers.com/bio/beckymiller       Becky
153           https://www.robertsbrothers.com/bio/behnazghasemi      Behnaz
154             https://www.robertsbrothers.com/bio/belveturner       Belve
155              https://www.robertsbrothers.com/bio/billhinton        Bill
156              https://www.robertsbrothers.com/bio/bobbinolan       Bobbi
157              https://www.robertsbrothers.com/bio/bobbymoore       Bobby
158             https://www.robertsbrothers.com/bio/brandinolen      Brandi
159            https://www.robertsbrothers.com/bio/breannasharp     Breanna
160            https://www.robertsbrothers.com/bio/brendarohlfs      Brenda
161              https://www.robertsbrothers.com/bio/brentbaker       Brent
162           https://www.robertsbrothers.com/bio/brettkittrell       Brett
163             https://www.robertsbrothers.com/bio/brookewalsh      Brooke
164              https://www.robertsbrothers.com/bio/bryanolson       Bryan
165               https://www.robertsbrothers.com/bio/butchblum       Butch
166                https://www.robertsbrothers.com/bio/carollee       Carol
167           https://www.robertsbrothers.com/bio/carynbuchanan       Caryn
168        https://www.robertsbrothers.com/bio/catherinequinley   Catherine
169         https://www.robertsbrothers.com/bio/catherinevailes   Catherine
170              https://www.robertsbrothers.com/bio/CheekaPack      Cheeka
171           https://www.robertsbrothers.com/bio/cherilmcaleer      Cheril

    middle_name          last_name  \
0                         Trocchio
2                           Clarke
3                            Moore
4                        Nicholson
5                           Morgan
6                          Stewart
7                            Bowen
8                          Killian
9                           Taylor
10                        Driskell
11                            Rowe
12                           Scott
13                          Hunter
14                        Faulkner
15                           Smith
16                         Kenoyer
17                        Reynolds
18                            Crow
19                          Zoghby
20                        Sessions
21                      McAllister
22                            Ginn
23                          Hansen
24                          Barber
25                       Bulwinkle
26                           Burns
27                         Gregory
28                             Fox
30                          Bixler
31                          Brooks
32                           Brown
33                        Thompson
34                          Tipton
35                           Booth
36                         Pedrosa
37                          Ossler
38               BoullemetUkangsin
39                            Pugh
40                         Johnson
41                           Sharp
42                      Burkholder
43                            Emer
44                        Jernigan
45                            Cave
46                           Guinn
47                         Brannon
48                        Mitchell
49                          Miller
50                         Addison
51                          Corley
52                           Loper
53                          Miller
54                           Klyce
55                           Scott
56                          Hunter
57                          Harper
58                        McCollum
59                           Gandy
60                           Trest
61                         Merrell
62                          Lawley
63                            Cole
64                            Hall
65                        Gerhardt
66                        Santiago
67                          Werner
68                          Dobson
69                         Whigham
70                          Mizell
71                     Elkartabani
72                       Gregorius
73                           Weeks
74                          Powell
75                       Culpepper
76                          Mosley
78                           Chalk
79                          Miller
80                         Pittman
82                           Salim
83                          Hudson
84                        McGovern
85                          Susman
86                          Parent
87                        Subirats
88                           Autio
89                        Reynolds
90                          Hughes
91                       Raulerson
92                        Baranyuk
94                         Braxton
95                          Nelson
96                          Pierce
97                         Scruggs
98                           Lents
99                        Flammini
100                          Davis
101                         Hodges
102                      Ledbetter
103                         Harski
104                           Barr
105                         Dubose
106                       Williams
107                        Wallace
108                         Grubbs
109                       Eldridge
110                          Frost
111                           Gill
112                        Johnsey
113                          Smits
114                          Kruse
115                        Brandon
116                       Matthews
117                        Jenkins
118                      Archibald
119                        Herndon
120                         Bouler
121                        Trimble
122                         Fowler
123                       McCollum
124                         Pascoe
125                        Burgess
126                       Ferguson
127                       Cosgrove
128                           Curl
129                       Medeiros
130                          Bates
131                          Perry
132                          Britt
133                         Grimes
134                         Perdue
135                         Graham
136                          Brown
137                        Stinson
138                      Dickerson
139                         Tucker
140                     Brizendine
141                           Long
142                         Hasiak
143                         Baxter
144                         Perdue
145                         Busbee
146                          Sasso
149                       Johnston
150                          Duffy
151                        Andrews
152                         Miller
153                        Ghasemi
154                         Turner
155                         Hinton
156                          Nolan
157                          Moore
158                          Nolen
159                          Sharp
160                         Rohlfs
161                          Baker
162                       Kittrell
163                          Walsh
164                          Olson
165                           Blum
166                            Lee
167                       Buchanan
168                        Quinley
169                         Vailes
170                           Pack
171                        McAleer

                                                                                                   image_url  \
0     https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6365079/6365079_11292023150828.jpg
2    https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181847/6181847_06222023011312.jpeg
3     https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181796/6181796_03272023142000.jpg
4     https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6568451/6568451_02062026170958.jpg
5    https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181661/6181661_06162023213933.jpeg
6     https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6593859/6593859_03232026123921.jpg
7     https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181658/6181658_01082025211247.jpg
8     https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6387774/6387774_10242023194810.jpg
9     https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6563140/6563140_05292026152945.jpg
10    https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6485358/6485358_02052024165157.jpg
11   https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6551277/6551277_05162025195926.jpeg
12    https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6181775/6181775_03272023142000.jpg
13    https://content.mediastg.net/Dynamic/RealEstate/company/772/account/6212596/6212596_06262023162420.jpg

In [38]:
df[df.zipcode == ""]

Empty DataFrame
Columns: [profile_url, first_name, middle_name, last_name, image_url, office_name, address, description, languages, social, website, email, title, country, city, zipcode, state, agent_phone_numbers, office_phone_numbers]
Index: []

In [39]:
df.zipcode.value_counts()

zipcode
80237    83
80206    82
80528    19
80302     8
80435     2
80920     1
Name: count, dtype: int64

In [40]:
import pandas as pd
import re
import unicodedata

def normalize(text):
    if pd.isna(text):
        return ""
    text = str(text).strip().lower()

    # Remove accents
    text = "".join(
        c for c in unicodedata.normalize("NFKD", text)
        if not unicodedata.combining(c)
    )

    # Keep only letters, numbers, hyphens and spaces
    text = re.sub(r"[^a-z0-9\s-]", "", text)

    # Replace spaces with hyphens
    text = re.sub(r"\s+", "-", text)

    return text

def profile_name_matches(row):
    url = str(row["profile_url"]).lower()

    # Extract the slug after /our-advisors/ or /bio/
    m = re.search(r"/(?:our-advisors|bio)/([^/?]+)", url)
    if not m:
        return False

    slug = normalize(m.group(1))

    first = normalize(row["first_name"])
    last = normalize(row["last_name"])

    return first in slug and last in slug

invalid_profile_urls = df[
    ~df.apply(profile_name_matches, axis=1)
]

print(f"Profile URL name mismatches: {len(invalid_profile_urls)}")
display(invalid_profile_urls[["profile_url", "first_name", "last_name"]])

Profile URL name mismatches: 116

,profile_url,first_name,last_name
0,https://www.kentwood.com/bio/bkelly,Bob,Kelly
2,https://www.kentwood.com/bio/bgustafson,Brendan,Gustafson
3,https://www.kentwood.com/bio/Brandon,Brandon,Brennick
6,https://www.kentwood.com/bio/HarrisTeam,Brian and Jamie Harris,
8,https://www.kentwood.com/bio/brosen,Brian,Rosen
9,https://www.kentwood.com/bio/bridgetm,Bridget,Marx
10,https://www.kentwood.com/bio/BrinckerhoffEmery,Brinckerhoff Emery & Associates,
11,https://www.kentwood.com/bio/uhl,Bryan & Kris Uhl,
12,https://www.kentwood.com/bio/Jbuckley,Buckley,Team
14,https://www.kentwood.com/bio/Carolyn,Carolyn,O'Donnell
17,https://www.kentwood.com/bio/charlotte,Charlotte,Connolly
20,https://www.kentwood.com/bio/chris,Christopher,Ansay
21,https://www.kentwood.com/bio/chowey2,Christopher,Howey
22,https://www.kentwood.com/bio/cgargotto,Chuck,Gargotto
25,https://www.kentwood.com/bio/dan,Dan,Buckley
26,https://www.kentwood.com/bio/danielle,Danielle,Ewing
27,https://www.kentwood.com/bio/david,David,Morrison
28,https://www.kentwood.com/bio/dawn,Dawn,Raymond
29,https://www.kentwood.com/bio/deec,Dee,Chirafisi
30,https://www.kentwood.com/bio/DenaP,Dena,Reeves-Pastorini
32,https://www.kentwood.com/bio/Diane,Diane,Sorensen
33,https://www.kentwood.com/bio/dierk,Dierk,Herbermann
34,https://www.kentwood.com/bio/dotson,Dotson,Skaggs
35,https://www.kentwood.com/bio/emarks,Edie,Marks
36,https://www.kentwood.com/bio/elise,Elise,Marks
37,https://www.kentwood.com/bio/EHotz,Elizabeth,Hotz
38,https://www.kentwood.com/bio/Elizabeth,Elizabeth,Sacerdoti
42,https://www.kentwood.com/bio/gglucksman,Gayle,Glucksman
43,https://www.kentwood.com/bio/GhassanK,Ghassan,Kanafani
44,https://www.kentwood.com/bio/ginaandkara2,Gina Lorenzen & Kara Couzens,
45,https://www.kentwood.com/bio/GELSNER,Greg,Elsner
46,https://www.kentwood.com/bio/greg,Greg,Yoshida
49,https://www.kentwood.com/bio/gthurman,J.,Thurman
50,https://www.kentwood.com/bio/JacciandSana-JSCollective,Jacci,Geiger
51,https://www.kentwood.com/bio/jaden,Jaden,Combs
53,https://www.kentwood.com/bio/janelleh,Janelle,Howard
56,https://www.kentwood.com/bio/jalton,Janiese,Alton
58,https://www.kentwood.com/bio/Jay,Jay,Modglin
59,https://www.kentwood.com/bio/jvanderhule,Jeff,Vanderhule
61,https://www.kentwood.com/bio/jen,Jen,Fillion
62,https://www.kentwood.com/bio/jmarkus2,Jennifer,Markus
63,https://www.kentwood.com/bio/Jim,Jim,Nussbaum
64,https://www.kentwood.com/bio/jrhye,Jim,Rhye
65,https://www.kentwood.com/bio/TRAYNOR,Jim,Traynor
67,https://www.kentwood.com/bio/jinnohn,Jinnohn,Gilmore
68,https://www.kentwood.com/bio/jfitz,John,Fitzpatrick
70,https://www.kentwood.com/bio/jhayden,John,Hayden
72,https://www.kentwood.com/bio/jonlopez,Jonathan,Lopez
73,https://www.kentwood.com/bio/jonp,Jonathan,Pierotti
74,https://www.kentwood.com/bio/jhummel,Julie,Hummel
77,https://www.kentwood.com/bio/KarenLanders,Karen,Zeile
78,https://www.kentwood.com/bio/karen,Karen,Brinckerhoff
81,https://www.kentwood.com/bio/katherinel,Katherine,Lillydahl
85,https://www.kentwood.com/bio/KCOMBS,Keith,Combs
86,https://www.kentwood.com/bio/ksophinos,Kelly Sophinos and Greg Margheim,
88,https://www.kentwood.com/bio/Keri,Keri,Duffy
92,https://www.kentwood.com/bio/lhotz,Larry,Hotz
94,https://www.kentwood.com/bio/lmonaco,Leslie,Monaco
95,https://www.kentwood.com/bio/libby,Libby,Levinson
97,https://www.kentwood.com/bio/lisag,Lisa,Gould
98,https://www.kentwood.com/bio/Lori,Lori,Pace
99,https://www.kentwood.com/bio/MacM,Mac,Martin
100,https://www.kentwood.com/bio/martha,Martha,Potter-Goldstein
101,https://www.kentwood.com/bio/mary,Mary,Jones
103,https://www.kentwood.com/bio/MattP,Matt,Peterson
107,https://www.kentwood.com/bio/mhotz,Meredith,Hotz
108,https://www.kentwood.com/bio/MikeC,Michael,Csrnko
112,https://www.kentwood.com/bio/mitch,Mitchell,Rothman
113,https://www.kentwood.com/bio/nnielsen,Nancy,Nielsen
114,https://www.kentwood.com/bio/nwalters,Nancy,Walters
121,https://www.kentwood.com/bio/pattygreg,Patty Ryan Anton & Greg Card,
122,https://www.kentwood.com/bio/pwall,Pat,Wall
126,https://www.kentwood.com/bio/phyllis,Phyllis,Sinclair
129,https://www.kentwood.com/bio/renitah,Renita,Heald
130,https://www.kentwood.com/bio/goldhammer2,Rob,Goldhammer
131,https://www.kentwood.com/bio/rlandry,Robyn,Landry
133,https://www.kentwood.com/bio/sana,Sana,Wood
134,https://www.kentwood.com/bio/sweigand,Sandy,Weigand
135,https://www.kentwood.com/bio/sglaze,Sara,Glaze
138,https://www.kentwood.com/bio/Scott,Scott,Scholbe
140,https://www.kentwood.com/bio/larkin,Sean & Debbie Larkin,
141,https://www.kentwood.com/bio/skelly,Sean,Kelly
143,https://www.kentwood.com/bio/sheila,Sheila,Schlifkin
144,https://www.kentwood.com/bio/Soley,Soley,Maria
146,https://www.kentwood.com/bio/Staci,Staci,Burns
148,https://www.kentwood.com/bio/stephanie,Stephanie,Lepard
149,https://www.kentwood.com/bio/StephanieS,Stephanie,Sulstrom
150,https://www.kentwood.com/bio/skruse,Steven,Kruse
151,https://www.kentwood.com/bio/steve,Steve,Travers
152,https://www.kentwood.com/bio/stock,Stock,Jonekos
153,https://www.kentwood.com/bio/sdiliberti,Susan,Diliberti
158,https://www.kentwood.com/bio/dutzerteam,Thomas & Rosanne Dutzer,
160,https://www.kentwood.com/bio/tglucksman,Tiffany,Appel
161,https://www.kentwood.com/bio/tcolleran,Tim,Colleran
162,https://www.kentwood.com/bio/todd,Todd,Landgrave
164,https://www.kentwood.com/bio/Tom,Tom,Gross
166,https://www.kentwood.com/bio/awolfe,Aaron,Wolfe
167,https://www.kentwood.com/bio/aimee,Aimee,Twarogowski
168,https://www.kentwood.com/bio/alarson,Alan,Larson
170,https://www.kentwood.com/bio/acraig,Allison,Craig
171,https://www.kentwood.com/bio/asmookler,Allison,Smookler
176,https://www.kentwood.com/bio/anastasia,Anastasia,Williamson
177,https://www.kentwood.com/bio/andrea,Andrea,Bell
178,https://www.kentwood.com/bio/andreac,Andrea,Chirich
180,https://www.kentwood.com/bio/agonzales,Andrew,Gonzales
181,https://www.kentwood.com/bio/andy2,Andrew,Maguire
182,https://www.kentwood.com/bio/Angela,Angela,Beldy
184,https://www.kentwood.com/bio/amcwilliams,Anne,McWilliams
185,https://www.kentwood.com/bio/ann,Ann,Lenane
186,https://www.kentwood.com/bio/Annzo,Annzo,Phelps
187,https://www.kentwood.com/bio/autumns,Autumn,Mestas
188,https://www.kentwood.com/bio/BFIEST,Barb,Fiest
190,https://www.kentwood.com/bio/BILL,Bill,Verdon
191,https://www.kentwood.com/bio/BobbyB,Bobby,Bolyard
192,https://www.kentwood.com/bio/afshins,Afshin,Sarvestani
193,https://www.kentwood.com/bio/bob,Bob,Lee