In [1]:
import pandas as pd
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option("display.max_colwidth", None)

In [2]:
df = pd.read_csv(r'/home/user/Documents/zepto_2026_07_16.csv/zepto_2026_07_16.csv',  low_memory=False)

In [9]:
df.shape

(530232, 31)

In [11]:
df.isnull().sum()

crawl_date_and_time             0
platform_name                   0
store_id                        0
store_name_location             0
city                            0
pin_code                        0
unique_id                       0
product_id_upc_ean              0
department                      0
category                        0
sub_category                    0
product_type               530232
brand_name                      0
product_name                    0
product_description        530232
product_grammage            95917
package_type               530232
net_quantity                    0
variants                   515612
item_mrp                        0
item_selling_price              0
out_of_stock_flag               0
discount_flag                   0
product_price                   0
unit_price                 530232
promo_offer_description         0
promo_offer_price               0
discount_in_percent             0
stock_count                     0
product_url                     0
product_image_urls         530232
dtype: int64

In [12]:
df.nunique()

crawl_date_and_time        13619
platform_name                  1
store_id                     198
store_name_location          146
city                          34
pin_code                     134
unique_id                  14804
product_id_upc_ean         14376
department                    10
category                      23
sub_category                 159
product_type                   0
brand_name                  1624
product_name               13281
product_description            0
product_grammage             982
package_type                   0
net_quantity                1864
variants                     265
item_mrp                    1112
item_selling_price          1997
out_of_stock_flag              2
discount_flag                  2
product_price               1997
unit_price                     0
promo_offer_description     1390
promo_offer_price           1997
discount_in_percent           94
stock_count                   51
product_url                14804
product_image_urls             0
dtype: int64

In [13]:
df.city.value_counts()

city
Bangalore          99045
Hyderabad          75245
Mumbai             67305
Chennai            45380
Kolkata            29102
Pune               28990
Jaipur             18250
Faridabad          15550
Surat              14436
Nagpur             10896
Ahmedabad          10799
Kanpur             10796
Prayagraj          10394
Nashik              7463
Mysuru              7278
Ludhiana            6790
Vasai Virar         6573
Amritsar            6393
Greater Noida       4549
Behta Hajipur       4529
S.A.S Nagar         4435
Secunderabad        4401
Dehradun            4086
Hubballi            3908
Udaipur             3750
Karimnagar          3697
Hosur               3676
Kharar              3498
Chandigarh          3467
Jalandhar           3292
Navsari             3161
Coimbatore          3152
Meerut              3054
Kalyan-Dombivli     2892
Name: count, dtype: int64

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
df.unique_id.duplicated().sum()

np.int64(515428)

In [16]:
pin_check = (
    df.groupby("store_name_location")["pin_code"]
        .nunique()
        .sort_values(ascending=False)
)

pin_check[pin_check > 1]

Series([], Name: pin_code, dtype: int64)

In [17]:
missing_grammage = df[df["product_grammage"].isna()]

print("Rows with missing product_grammage:", len(missing_grammage))
missing_grammage.head()

Rows with missing product_grammage: 95917

,crawl_date_and_time,platform_name,store_id,store_name_location,city,pin_code,unique_id,product_id_upc_ean,department,category,sub_category,product_type,brand_name,product_name,product_description,product_grammage,package_type,net_quantity,variants,item_mrp,item_selling_price,out_of_stock_flag,discount_flag,product_price,unit_price,promo_offer_description,promo_offer_price,discount_in_percent,stock_count,product_url,product_image_urls
22,2026-07-16 00:05:14,zepto,ab3bee45-6ef0-4dbe-bf5f-253d0817ceb5,"Abakash Apartment Nagerbazar, Nagendra Nath Rd, Nagerbazar, Kamardanga, Kolkata, West Bengal, 700028, India",Kolkata,700028,ecba9a6e-88d2-4570-bb24-58e4f23b5815,1504f65b-a599-4093-9749-0c5ab5d9f670,"Atta, Rice & Dal","Atta, Rice, Oil & Dals",Atta,NaN,Ganesh,GANESH PREMIUM SHARBATI ATTA,NaN,NaN,NaN,1 kg,NaN,78.0,64.0,No,Yes,64.0,NaN,₹14 OFF,64.0,17,3,https://www.zepto.com/pn/ganesh-premium-sharbati-atta/pvid/ecba9a6e-88d2-4570-bb24-58e4f23b5815,NaN
33,2026-07-16 00:05:14,zepto,ab3bee45-6ef0-4dbe-bf5f-253d0817ceb5,"Abakash Apartment Nagerbazar, Nagendra Nath Rd, Nagerbazar, Kamardanga, Kolkata, West Bengal, 700028, India",Kolkata,700028,c0ffd674-fc8a-4458-8d7a-fdaa621c8eaf,2a035497-97d9-4b65-9cf1-1894cfeeb75e,"Atta, Rice & Dal","Atta, Rice, Oil & Dals","Besan, Sooji & Maida",NaN,Satyendra,Satyendra Sattoo,NaN,NaN,NaN,500 g,NaN,93.5,93.5,No,No,93.5,NaN,No offer,93.5,0,6,https://www.zepto.com/pn/satyendra-sattoo/pvid/c0ffd674-fc8a-4458-8d7a-fdaa621c8eaf,NaN
106,2026-07-16 00:05:15,zepto,ab3bee45-6ef0-4dbe-bf5f-253d0817ceb5,"Abakash Apartment Nagerbazar, Nagendra Nath Rd, Nagerbazar, Kamardanga, Kolkata, West Bengal, 700028, India",Kolkata,700028,5746b287-343c-472e-9422-5391932fe712,89138dd9-db57-4b91-bd49-10ce2201da8c,"Atta, Rice & Dal","Atta, Rice, Oil & Dals",Millets & Other Flours,NaN,24 Mantra,24 Mantra Organic Ragi Flour Combo,NaN,NaN,NaN,500 g X 2,NaN,190.0,168.0,No,Yes,168.0,NaN,₹22 OFF,168.0,11,2,https://www.zepto.com/pn/24-mantra-organic-ragi-flour-combo/pvid/5746b287-343c-472e-9422-5391932fe712,NaN
109,2026-07-16 00:05:15,zepto,ab3bee45-6ef0-4dbe-bf5f-253d0817ceb5,"Abakash Apartment Nagerbazar, Nagendra Nath Rd, Nagerbazar, Kamardanga, Kolkata, West Bengal, 700028, India",Kolkata,700028,1d381b32-f42f-425f-859c-54aa9922971a,e1626c4a-0445-4879-a43d-72c0a96f9a30,"Atta, Rice & Dal","Atta, Rice, Oil & Dals",Millets & Other Flours,NaN,Puramate,Puramate Corn Flour Combo,NaN,NaN,NaN,100 g X 2,NaN,66.0,66.0,No,No,66.0,NaN,No offer,66.0,0,5,https://www.zepto.com/pn/puramate-corn-flour-combo/pvid/1d381b32-f42f-425f-859c-54aa9922971a,NaN
111,2026-07-16 00:05:15,zepto,ab3bee45-6ef0-4dbe-bf5f-253d0817ceb5,"Abakash Apartment Nagerbazar, Nagendra Nath Rd, Nagerbazar, Kamardanga, Kolkata, West Bengal, 700028, India",Kolkata,700028,f76ce670-12a5-4dd6-87e6-81369659597a,e211254e-f048-46f1-a66c-f35f321df093,"Atta, Rice & Dal","Atta, Rice, Oil & Dals",Millets & Other Flours,NaN,Daily Good,Daily Good Ragi / Finger Millet Flour Combo,NaN,NaN,NaN,500 g X 2,NaN,150.0,120.0,No,Yes,120.0,NaN,₹30 OFF,120.0,20,5,https://www.zepto.com/pn/daily-good-ragi-finger-millet-flour-combo/pvid/f76ce670-12a5-4dd6-87e6-81369659597a,NaN

In [18]:
df.net_quantity.value_counts()

net_quantity
1 pc                                  39140
1 pack (200 g)                        19076
1 pack (500 g)                        17730
1 pack (1 kg)                         15152
1 pc (100 ml)                         13642
1 pc (200 ml)                         11046
1 pack (100 g)                        10632
1 pc (250 ml)                         10621
1 set                                 10088
1 pc (100 g)                           9931
1 pc (1 L)                             9892
1 pc (50 g)                            8870
1 pc (50 ml)                           7519
1 pack (5 kg)                          7020
1 pack (250 g)                         6026
1 pack (1 L)                           5454
1 pack (400 g)                         5444
1 pc (150 ml)                          5196
1 pc (400 ml)                          4683
1 pack (500 ml)                        4385
1 pc (30 ml)                           4320
1 pack (150 g)                         4185
1 pc (200 g)                           3894
1 pc (180 ml)                          3857
1 pack (6 pcs)                         3797
1 pack (50 g)                          3579
1 pc (300 ml)                          3508
1 pack (2 pcs)                         3415
1 pack (10 pcs)                        3201
1 pc (500 ml)                          3012
1 pc (120 ml)                          2899
1 pc (250 g)                           2894
1 pc (80 g)                            2874
1 pack (60 g)                          2813
1 pack (3 pcs)                         2811
1 pc (60 ml)                           2784
1 pc (150 g)                           2783
1 pc (1 kg)                            2765
1 pack (5 pcs)                         2751
1 pack (100 ml)                        2715
1 pack (40 g)                          2703
1 pack (300 g)                         2494
1 pc (75 g)                            2477
1 pack                                 2456
1 pack (30 pcs)                        2228
1 pack (20 pcs)                        2208
1 pc (300 g)                           2146
1 pack (4 pcs)                         2123
1 pack (80 g)                          2077
2 combo                                2073
1 pc (10 ml)                           2013
1 pc (70 ml)                           1874
1 pack (25 pcs)                        1790
1 pc (400 g)                           1782
1 pc (30 g)                            1769
1 pc (750 ml)                          1767
1 pc (40 ml)                           1722
1 pack (12 pcs)                        1671
1 pc (110 ml)                          1657
1 pack (70 g)                          1590
1 pack (45 g)                          1540
1 pc (600 ml)                          1525
1 pack (25 g)                          1525
1 pc (40 g)                            1510
1 pc (175 ml)                          1473
1 pack (160 g)                         1458
1 pack (40 pcs)                        1417
1 pc (500 g)                           1413
1 pack (120 g)                         1401
1 pack (75 g)                          1377
1 pc (80 ml)                           1365
1 pack (20 g)                          1354
1 pc (125 ml)                          1327
1 pc (45 g)                            1318
1 pack (450 g)                         1273
1 pc (350 g)                           1256
1 pack (180 g)                         1251
1 pack (10 kg)                         1242
1 x 72 pulls                           1220
1 pack (55 g)                          1143
1 pack (140 g)                         1140
1 pack (350 g)                         1113
1 pack (85 g)                          1083
1 pack (30 g)                          1077
1 pc (4 g)                             1072
1 pack (200 ml)                        1050
1 pc (70 g)                            1020
1 pc (330 ml)                          1017
1 pc (170 ml)                           975
1 pc (90 g)                             963
1 pc (15 ml)                            949
1 pack (16 pcs)                         945
1 pack (24 pcs)                         934
1 pack (18 pcs)                         916
1 pc (6 ml)                             912
62pcs                                   909
1 pc (125 g)                            900
1 set (3 pcs)                           865
1 pack (35 g)                           864
1 pc (85 g)                             808
1 pack (125 ml)                         796
3 pcs                                   779
1 pc (55 g)                             779
100 g                                   774
1 pack (800 g)                          765
1 pc (5 ml)                             763
1 pc (225 ml)                           762
1 pc (75 ml)                            756
1 pc (510 g)                            747
1 pc (230 ml)                           746
1 pack (450 ml)                         743
1 pack (125 g)                          739
1 pc (236 ml)                           735
1 pc (190 ml)                           735
50 g                                    728
1 set (2 pcs)                           725
3 x 72 pulls                            723
1 pc (35 g)                             715
1 pc (220 ml)                           712
54pcs                                   711
250 ml X 2                              708
1 pack (15 pcs)                         704
1 pc (60 g)                             693
1 pc (105 ml)                           672
1 pack (5 x 125 g)                      654
1 pack (150 ml)                         625
1 pack (50 pcs)                         623
1 pc (10 g)                             619
1 pc (924 g)                            616
1 pack (28 g)                           613
1 set (5 pcs)                           604
72pcs                                   594
1 pc (4.5 g)                            584
100 ml                                  583
1 pc (180 g)                            581
1 pack (25 ml)                          573
1 pack (77 g)                           573
1 pc (65 ml)                            570
1 pc (1.2 L)                            549
1 pc (9 g)                              540
1 pc (25 ml)                            536
1 pack (2 x 150 g)                      529
1 set (7 pcs)                           528
200 ml                                  522
1 pc (20 ml)                            521
1 pack (36 pcs)                         520
1 pc (120 g)                            514
250 ml                                  509
1 pc (15 g)                             504
1 pc (9 ml)                             504
1 pc (20 g)                             497
1 pack (700 ml)                         496
2 pcs                                   493
1 pack (65 g)                           492
4 pcs                                   490
350 ml                                  481
1 pack (750 ml)                         470
1 pc (190 g)                            466
150 g + 60 g                            466
1 set (4 pcs)                           463
1 pack (4 x 150 g)                      459
1 pack (850 g)                          454
1 pc (25 g)                             443
1 pc (750 g)                            443
1 pc (8 ml)                             441
1 pc (4.8 g)                            440
1 pair                                  440
1 pc (5 L)                              437
1 pc (0.35 g)                           433
1 pack (115 ml)                         432
1 pc (170 g)                            432
180 ml                                  419
1 pack (3 x 100 g)                      418
1 pack (57 g)                           416
1 pc (350 ml)                           415
1 pc (12 g)                             412
100 g X 2                               406
1 pack (2 kg)                           403
1 pack (41 g)                           402
1 pack (750 g)                          400
200 g                                   399
1 pc (236 ml or 250 ml)                 393
1 pack (170 g)                          393
1 pc (90 ml)                            393
0.35 g                                  388
300 ml                                  388
1 pc (88 ml)                            385
1 pc (450 g)                            377
500 ml X 2                              372
1 piece                                 370
1 kg                                    368
1 pc (135 ml)                           367
1 pc (12 ml)                            365
1 pack (144 g)                          364
1 pack (19.8 g)                         362
1 pack (60 g or 64 g)                   362
2 x 72 pulls                            359
60 ml X 2                               359
500 g                                   358
1 pc (2 L)                              355
200 ml X 2                              352
1 pack (7 pcs)                          351
1 pc (2.25 L)                           349
1 pack (130 g)                          345
1 pc (175 g)                            344
5 ml                                    342
1 pack (375 g)                          341
1 set (8 pcs)                           336
2 pack (10 pcs)                         334
1 pc (4 ml)                             333
1 pack (43 g)                           332
1 pc (17 g)                             329
1 pack (100 pcs)                        324
1 pack (250 ml)                         320
1 pack (240 g)                          319
1 pack (600 g)                          317
1 pack (52 g)                           313
1 pack (275 g)                          313
1 pack (900 g)                          309
1 set (4 x 20 ml)                       307
1 pack (79 g)                           304
1 set (4 x 25 ml)                       303
30 ml                                   301
1 pc (5 g)                              297
1 pc (6 g)                              296
1 pack (8 pcs)                          295
1 pc (320 ml)                           294
1 pc (61 g)                             294
1 pack (3 x 150 g)                      291
74pcs                                   290
1 pc (55 ml)                            289
1 x 80 pulls                            287
1 set (11 pcs)                          287
1 pc (3.5 ml)                           286
1 pc (118 ml or 125 ml)                 285
10 ml X 2                               285
1 set (6 pcs)                           282
1 pack (14 pcs)                         280
1 pack (3 x 40 g)                       280
1 pack (44 g)                           280
3 combo                                 278
1 pack (99 g)                           277
1.15 kg                                 275
70pcs                                   275
1 pack (270 g)                          271
1 pc (196 ml)                           271
1 pack (4 x 70 g)                       270
1 pack (142 g)                          270
1 kg X 2                                269
1 pack (48 g or 52.9 g)                 269
1.2 kg                                  266
1 pack (67.5 g)                         264
1 pack (1.2 kg)                         263
1 pc (18 ml)                            261
0.3 g                                   260
1 pack (168 g)                          259
250 ml X 3                              259
70 ml + 60 g                            258
1 pack (38 g)                           257
1 L X 3                                 257
1 pack (3 x 125 g)                      255
1 pack (900 ml)                         254
1 pc (245 ml)                           252
1 pack (160 g or 171 g)                 251
56pcs                                   250
230 g                                   247
1 pack (210 g)                          246
1 pc (340 ml)                           245
1 pc (45 ml)                            245
1 pack (25 x 2 g)                       245
1 pack (4 x 125 g)                      244
1 pack (55 g or 57 g)                   244
40pcs                                   244
1 pack (25 x 1.7 g)                     243
1 pc (3 g)                              240
400 g                                   240
1 pc (240 ml)                           238
450 ml                                  237
1 pc (300 ml or 330 ml)                 235
1 pack (30.6 g or 28.9 g)               234
1 pack (280 g)                          233
1 pack (128 g)                          232
1 pc (1.25 kg)                          231
1 pc (340 g)                            230
5.6 ml                                  230
1 pack (48 g)                           229
80 g                                    229
1 pack (2 x 100 ml)                     228
100 g X 3                               228
1 pc (227 g)                            227
1 pack (90 g)                           227
1 pack (33 g)                           223
1 pack (110 g)                          222
1 pc (4.5 ml)                           220
1 pc (35 ml)                            220
1 pc (65 g)                             219
1 L                                     218
1 pack (225 g)                          218
1 pack (10 x 10 g)                      218
1 pack (37.5 g)                         218
1 pcs                                   217
1 pc (210 g)                            217
1 pack (8 x 250 ml)                     215
1 pack (69 g)                           213
1 set (60 g)                            213
1 pack (60 pcs)                         212
1 pack (415 g)                          210
1 pack (159 g)                          209
1 pc (280 ml)                           208
1 pc (175 ml or 180 ml)                 207
150 g X 2                               206
1 pack (120 ml)                         203
60 ml X 3                               202
1 pc (180 ml or 190 ml)                 200
1 pack (95 g)                           199
30 g                                    197
1 pc (1.5 L)                            197
1 pack (165 g)                          196
1 pack (72 pcs)                         196
1 pack (5 x 100 g)                      195
1 pack (180 ml)                         193
400g                                    193
1 pack (153 g)                          193
1 pack (700 g)                          192
1 pc (700 g)                            192
30pcs                                   192
1 pack (4 x 100 g)                      191
87.5 g + 72 ml                          190
1 pack (2 x 12.5 g)                     190
1 pack (34 g)                           190
1 pc (7 ml)                             186
1 pc (225 g)                            186
250 g X 2                               184
1 pack (20 g or 16 g)                   184
1 pack (27.3 g or 28.2 g)               183
1 pack (6 x 12.5 g)                     182
1 set (10 pcs)                          179
260 g                                   179
1 L X 2                                 178
1 pack (108 g)                          175
1 pc (1.5 g)                            175
1 kg X 3                                174
1 set (9 pcs)                           174
1 pc (100 or 110 g)                     173
1 pc (600 g)                            172
1 pc (18 g)                             171
500 g X 2                               169
1 pc (46 g)                             168
1 pack (240 pcs)                        166
60 g                                    165
1 pc (1 ml)                             163
1 pack (110 ml)                         163
1 pc (354 ml)                           160
1 pack (22 g)                           160
32pcs                                   156
1 pc (36 g)                             155
1 pack (62.5 g)                         155
1 pack (6 Sachets)                      154
1 pack (42 g)                           153
1 pack (360 g)                          152
1 pack (248 g)                          152
20 pc X 2                               152
1 pc (110 g)                            151
180 g                                   150
1 pc (63 g)                             148
1 pack (59.4 g)                         147
55 g X 2                                147
144 g X 2                               147
1 pack (67 g)                           146
70 ml X 2                               145
1 Pack (40 g)                           145
1 pack (75 g or 80 g)                   145
1 pack (285 g)                          145
1 pack (16 g)                           145
400 g X 2                               144
1 pack (9 pcs)                          144
1 pack (32 g)                           144
1000 ml                                 144
5 x 72 pulls                            144
1 pack (56 g)                           143
1 pack (950 g)                          143
1 pack (145 g)                          143
1 pc (380 g)                            143
1 set (6 pack)                          142
1 kg X 4                                142
1 pc (100 ml or 118 ml)                 142
1 pack (135 g or 140 g)                 142
1 pc (80 g or 100 g)                    142
1 pack (20 ml)                          141
1 pack (48 pcs)                         141
1 pack (10 x 20 g)                      141
1 pack (0.5 g)                          141
70 g                                    141
52pcs                                   140
1 pack (70 g or 100 g)                  140
1 pack (4 x 75 g)                       140
1 pc (355 ml)                           140
1 pc (500 ml or 473 ml)                 139
1 pc (27.5 g or 30 g)                   139
1 pack (112.5 g)                        139
1 x 60 pulls                            139
1 pack (188 g)                          139
1 pack (100 g or 112 g)                 139
1 pack (183 g)                          139
1 pack (295 g)                          139
1 pc (47 g or 50 g)                     138
1 pc (56 g)                             138
1 pack (172 g)                          138
1 x 30 pulls                            138
1 pack (250 ml or 300 ml)               138
1 pack (165 ml)                         138
1 pack (29.7g)                          138
1 pc (78 g)                             138
1 pack (29.7 g)                         138
1 pc (150 g + 60 g)                     138
1 pc (62 g)                             138
1 pack (475 g)                          137
1 pack (960 g)                          137
2 x 150 g                               137
1 pack (150 g + 60 g)                   137
1 pack (172 ml)                         137
1 pack (100 g or 115.5 g)               137
1.6 g                                   137
1 pack (91.7 g or 100 g)                137
1 pc (10 L)                             137
1 pack (66.6 or 75 g)                   137
1 pack (52.9 g or 58 g)                 137
1 pc (825 ml)                           136
1 pack (5 x 20 g)                       136
7 pack (140 g)                          136
1 Pack (30 g)                           136
1 pc (45 or 48.5 g)                     136
1 pack (696 g)                          136
300 g                                   136
2 x 225 g                               135
200 g X 2                               135
1 pack (75 g or 82 g)                   135
2 x 25 g + 25 ml                        135
1 pack (84 g)                           135
1 pack (50 or 55 g)                     135
1 pack (159 ml)                         134
1 pack (88 g)                           134
1 pack (251 g or 275 g)                 134
1 Pack(350 g)                           134
21 g + 24 ml                            134
1 pack (585 g)                          133
350 g                                   133
1 pack (4 x 250 ml)                     133
1 pack (94 g)                           132
1 pack (80 ml)                          132
1 pack(30 pcs)                          132
1 pc (1 L or 1.2 L)                     131
6X1L                                    131
1 pack (120 g or 150 g)                 131

In [20]:
city_department = pd.crosstab(df["city"], df["department"])

city_department

department,"Atta, Rice & Dal",Baby Care,Bakery & Biscuits,Beauty & Cosmetics,Cold Drinks & Juices,Dairy & Breakfast,Munchies,Organic & Premium,Personal Care,Sweet Tooth
city,,,,,,,,,,
Ahmedabad,479,1490,790,1850,893,1257,569,1106,1571,794
Amritsar,314,712,528,1152,541,637,378,785,841,505
Bangalore,3983,14277,7358,15477,8625,10931,4734,11147,15097,7416
Behta Hajipur,160,787,319,768,316,458,192,437,808,284
Chandigarh,156,405,275,649,292,392,183,408,446,261
Chennai,1799,6381,3502,7209,3975,5306,2249,4841,6910,3208
Coimbatore,152,352,231,570,271,347,191,396,400,242
Dehradun,129,663,312,717,357,381,191,426,596,314
Faridabad,618,1806,1262,2676,1535,1787,764,1683,2222,1197
Greater Noida,160,819,319,756,400,477,189,462,669,298
Hosur,160,436,304,657,355,395,192,419,461,297
Hubballi,160,562,299,697,362,403,186,420,518,301
Hyderabad,2934,10977,5569,12587,6308,8012,3505,8342,11085,5926
Jaipur,754,2410,1420,3197,1517,2137,928,1852,2531,1504
Jalandhar,148,358,238,617,285,332,192,402,464,256
Kalyan-Dombivli,132,194,245,437,288,439,181,373,349,254
Kanpur,480,1353,892,1904,928,1052,576,1218,1469,924
Karimnagar,157,425,316,646,358,375,191,418,508,303
Kharar,150,374,277,508,332,429,185,425,506,312
Kolkata,1038,4114,2324,5031,2743,3213,1502,3233,3887,2017
Ludhiana,316,797,571,1211,579,698,382,808,898,530
Meerut,154,322,266,523,279,313,189,392,385,231
Mumbai,2592,9126,5078,11190,6514,7940,3144,7323,9553,4845
Mysuru,318,902,582,1312,639,784,384,829,935,593
Nagpur,476,1391,838,1902,1021,1093,576,1259,1486,854
Nashik,319,889,620,1334,673,772,376,805,1057,618
Navsari,152,332,257,553,277,308,190,382,424,286
Prayagraj,480,1274,832,1916,940,856,576,1229,1435,856
Pune,1098,4506,2167,4595,2389,3198,1332,3003,4557,2145
S.A.S Nagar,160,800,318,762,328,438,192,435,688,314
Secunderabad,160,763,318,741,364,419,192,441,688,315
Surat,624,1863,1123,2540,1257,1455,765,1574,2017,1218
Udaipur,160,484,303,702,291,396,190,400,511,313
Vasai Virar,278,536,545,1035,679,900,363,822,862,553

In [21]:
### city wise category distribution
city_category = pd.crosstab(df["city"], df["category"])

# Cities where any category is missing
missing_categories = city_category[city_category.eq(0).any(axis=1)]

missing_categories

category,"Atta, Rice, Oil & Dals",Baby Care,Bath & Body,Biscuits,Breakfast & Sauces,Cold Drinks & Juices,"Dairy, Bread & Eggs",Electronics & Appliances,Feminine Hygiene,Fragrances & Grooming,Frozen Food,Hair Care,Ice Creams & More,Makeup & Beauty,"Masala, Dry Fruits & More",Munchies,Packaged Food,Pharma & Wellness,Skincare,Sweet Cravings,"Tea, Coffee & More",Toys & Sports,Zepto Cafe
city,,,,,,,,,,,,,,,,,,,,,,,
Ludhiana,456,425,402,382,311,437,343,22,268,173,52,348,369,273,259,435,315,0,624,334,246,312,4

In [22]:
city_category = pd.crosstab(df["city"], df["category"])

print(city_category)

category         Atta, Rice, Oil & Dals  Baby Care  Bath & Body  Biscuits  \
city
Ahmedabad                           700        697          651       597
Amritsar                            442        389          384       347
Bangalore                          6229       6887         6163      5004
Behta Hajipur                       256        388          312       230
Chandigarh                          226        195          204       180
Chennai                            2841       3095         3004      2390
Coimbatore                          218        196          193       156
Dehradun                            208        318          256       226
Faridabad                           933        777          999       878
Greater Noida                       256        368          287       224
Hosur                               234        229          216       208
Hubballi                            235        286          230       223
Hyderabad                          4623       5316         4606      3809
Jaipur                             1006       1180         1091       972
Jalandhar                           217        197          208       154
Kalyan-Dombivli                     201        106          168       159
Kanpur                              687        727          631       610
Karimnagar                          233        216          231       220
Kharar                              221        223          214       188
Kolkata                            1537       1954         1627      1574
Ludhiana                            456        425          402       382
Meerut                              223        169          180       179
Mumbai                             4060       4886         3702      3530
Mysuru                              462        435          443       400
Nagpur                              704        616          665       612
Nashik                              464        463          453       430
Navsari                             217        164          191       176
Prayagraj                           690        699          618       586
Pune                               1745       2124         1961      1509
S.A.S Nagar                         239        347          294       224
Secunderabad                        255        363          277       223
Surat                               894        978          884       765
Udaipur                             228        256          224       222
Vasai Virar                         441        308          371       373

category         Breakfast & Sauces  Cold Drinks & Juices  \
city
Ahmedabad                       478                   617
Amritsar                        317                   405
Bangalore                      3945                  5937
Behta Hajipur                   159                   203
Chandigarh                      160                   214
Chennai                        1721                  2792
Coimbatore                      159                   203
Dehradun                        160                   252
Faridabad                       538                  1011
Greater Noida                   160                   241
Hosur                           160                   241
Hubballi                        160                   253
Hyderabad                      2981                  3988
Jaipur                          779                   934
Jalandhar                       160                   213
Kalyan-Dombivli                 147                   208
Kanpur                          480                   676
Karimnagar                      160                   254
Kharar                          155                   237
Kolkata                        1265                  1804
Ludhiana                        311                   437
Meerut                          159                   204
Mumbai                         2646                  4128
Mysuru                          320                   455
Nagpur                          480                   722
Nashik                          312                   479
Navsari                         156                   209
Prayagraj                       480                   663
Pune                           1110                  1609
S.A.S Nagar                     160                   256
Secunderabad                    160                   233
Surat                           640                   942
Udaipur                         160                   211
Vasai Virar                     296                   451

category         Dairy, Bread & Eggs  Electronics & Appliances  \
city
Ahmedabad                        730                        60
Amritsar                         298                         7
Bangalore                       6786                       534
Behta Hajipur                    291                        32
Chandigarh                       209                         5
Chennai                         3236                       273
Coimbatore                       144                         4
Dehradun                         187                        32
Faridabad                       1259                        72
Greater Noida                    318                        32
Hosur                            221                         6
Hubballi                         200                        31
Hyderabad                       5355                       385
Jaipur                          1322                        64
Jalandhar                        137                         4
Kalyan-Dombivli                  276                         1
Kanpur                           578                        36
Karimnagar                       187                        21
Kharar                           252                        12
Kolkata                         1922                       155
Ludhiana                         343                        22
Meerut                           124                         4
Mumbai                          5182                       394
Mysuru                           403                        33
Nagpur                           503                        66
Nashik                           388                        30
Navsari                          121                         2
Prayagraj                        394                        29
Pune                            2001                       178
S.A.S Nagar                      252                        32
Secunderabad                     293                        32
Surat                            709                        65
Udaipur                          199                        14
Vasai Virar                      589                        18

category         Feminine Hygiene  Fragrances & Grooming  Frozen Food  \
city
Ahmedabad                     444                    295           88
Amritsar                      267                    165           28
Bangalore                    3871                   2324          594
Behta Hajipur                 160                    112           30
Chandigarh                    142                     89           28
Chennai                      1591                   1030          360
Coimbatore                    124                     79           28
Dehradun                      161                    110           31
Faridabad                     641                    415          108
Greater Noida                 163                     99           27
Hosur                         134                     84           32
Hubballi                      141                     95           31
Hyderabad                    2976                   1925          417
Jaipur                        740                    527          137
Jalandhar                     139                     91           26
Kalyan-Dombivli                96                     70           29
Kanpur                        428                    270            3
Karimnagar                    143                    104           32
Kharar                        142                     87           27
Kolkata                      1027                    733          237
Ludhiana                      268                    173           52
Meerut                        122                     75           27
Mumbai                       2252                   1836          501
Mysuru                        263                    190           60
Nagpur                        422                    305           59
Nashik                        304                    199           60
Navsari                       130                     89           29
Prayagraj                     433                    256            3
Pune                         1115                    681          215
S.A.S Nagar                   163                    101           27
Secunderabad                  171                    109            1
Surat                         582                    431          119
Udaipur                       144                    104           27
Vasai Virar                   229                    180           57

category         Hair Care  Ice Creams & More  Makeup & Beauty  \
city
Ahmedabad              506                636              453
Amritsar               338                325              265
Bangalore             4136               5764             3576
Behta Hajipur          193                212              184
Chandigarh             190                176              154
Chennai               1957               2382             1601
Coimbatore             166                159              134
Dehradun               191                243              175
Faridabad              756                966              683
Greater Noida          192                233              192
Hosur                  184                238              172
Hubballi               188                239              178
Hyderabad             3221               4675             3188
Jaipur                 870               1154              806
Jalandhar              174                168              148
Kalyan-Dombivli         92                207              114
Kanpur                 515                664              482
Karimnagar             165                243              171
Kharar                 153                219              103
Kolkata               1333               1657             1285
Ludhiana               348                369              273
Meerut                 162                196              111
Mumbai                2786               3777             2806
Mysuru                 362                450              330
Nagpur                 521                728              474
Nashik                 359                487              345
Navsari                137                211              135
Prayagraj              546                593              450
Pune                  1255               1556             1139
S.A.S Nagar            193                217              189
Secunderabad           190                249              191
Surat                  619                905              589
Udaipur                189                224              170
Vasai Virar            233                451              265

category         Masala, Dry Fruits & More  Munchies  Packaged Food  \
city
Ahmedabad                              292       648            399
Amritsar                               251       435            306
Bangalore                             3114      5495           4263
Behta Hajipur                          128       217            179
Chandigarh                             127       211            163
Chennai                               1442      2633           1561
Coimbatore                             126       218            157
Dehradun                               128       222            175
Faridabad                              518       876            641
Greater Noida                          129       217            178
Hosur                                  130       220            160
Hubballi                               124       219            168
Hyderabad                             2300      4125           2762
Jaipur                                 630      1084            787
Jalandhar                              127       221            160
Kalyan-Dombivli                        119       216            123
Kanpur                                 384       660            483
Karimnagar                             129       220            161
Kharar                                 122       213            156
Kolkata                               1009      1732           1244
Ludhiana                               259       435            315
Meerut                                 118       213            154
Mumbai                                2057      3603           2754
Mysuru                                 258       440            314
Nagpur                                 392       657            480
Nashik                                 254       434            310
Navsari                                123       213            150
Prayagraj                              384       660            480
Pune                                   899      1520           1182
S.A.S Nagar                            128       218            169
Secunderabad                           128       221            169
Surat                                  504       856            634
Udaipur                                130       215            162
Vasai Virar                            245       426            263

category         Pharma & Wellness  Skincare  Sweet Cravings  \
city
Ahmedabad                       11      1014             342
Amritsar                         5       571             342
Bangalore                       57      9925            4424
Behta Hajipur                    3       554             172
Chandigarh                       1       312             170
Chennai                         26      4611            2124
Coimbatore                       2       266             163
Dehradun                         6       396             179
Faridabad                        8      1316             699
Greater Noida                    5       452             173
Hosur                            2       324             176
Hubballi                         2       350             179
Hyderabad                       57      7352            3312
Jaipur                           8      1611             829
Jalandhar                        3       308             173
Kalyan-Dombivli                  2       239             136
Kanpur                           6      1005             524
Karimnagar                       2       321             177
Kharar                           3       289             170
Kolkata                         26      2773            1100
Ludhiana                         0       624             334
Meerut                           2       251             130
Mumbai                          64      6901            2798
Mysuru                           6       632             355
Nagpur                           3       926             478
Nashik                           6       701             358
Navsari                          1       289             159
Prayagraj                       10      1007             522
Pune                            19      2764            1075
S.A.S Nagar                      3       486             176
Secunderabad                     3       456             179
Surat                            8      1377             668
Udaipur                          2       365             172
Vasai Virar                      6       592             297

category         Tea, Coffee & More  Toys & Sports  Zepto Cafe
city
Ahmedabad                       373            700          68
Amritsar                        245            257           4
Bangalore                      3034           6457         526
Behta Hajipur                   128            384           2
Chandigarh                      128            181           2
Chennai                        1343           3100         267
Coimbatore                      123            132           2
Dehradun                        128            299           3
Faridabad                       503            938          15
Greater Noida                   128            413          62
Hosur                           128            175           2
Hubballi                        128            246           2
Hyderabad                      2338           5088         446
Jaipur                          617           1091          11
Jalandhar                       124            138           2
Kalyan-Dombivli                 108             74           1
Kanpur                          384            556           7
Karimnagar                      126            179           2
Kharar                          122            132          58
Kolkata                         998           1882         228
Ludhiana                        246            312           4
Meerut                          120            129           2
Mumbai                         2049           3704         889
Mysuru                          254            409           4
Nagpur                          381            695           7
Nashik                          247            372           8
Navsari                         118            139           2
Prayagraj                       374            510           7
Pune                            870           2207         256
S.A.S Nagar                     128            414          19
Secunderabad                    126            370           2
Surat                           495            761          11
Udaipur                         128            202           2
Vasai Virar                     222            196          64

In [23]:
dept_category = (
    df.groupby("department")["category"]
    .apply(lambda x: sorted(x.unique()))
    .reset_index()
)

dept_category

,department,category
0,"Atta, Rice & Dal","[Atta, Rice, Oil & Dals]"
1,Baby Care,"[Baby Care, Dairy, Bread & Eggs, Packaged Food, Pharma & Wellness, Toys & Sports]"
2,Bakery & Biscuits,"[Biscuits, Dairy, Bread & Eggs, Packaged Food, Sweet Cravings]"
3,Beauty & Cosmetics,"[Fragrances & Grooming, Hair Care, Makeup & Beauty, Skincare]"
4,Cold Drinks & Juices,"[Cold Drinks & Juices, Dairy, Bread & Eggs, Ice Creams & More, Packaged Food, Pharma & Wellness, Tea, Coffee & More, Zepto Cafe]"
5,Dairy & Breakfast,"[Breakfast & Sauces, Cold Drinks & Juices, Dairy, Bread & Eggs, Frozen Food, Munchies, Packaged Food]"
6,Munchies,"[Biscuits, Masala, Dry Fruits & More, Munchies, Packaged Food]"
7,Organic & Premium,"[Atta, Rice, Oil & Dals, Biscuits, Breakfast & Sauces, Masala, Dry Fruits & More, Munchies, Packaged Food, Sweet Cravings, Tea, Coffee & More, Zepto Cafe]"
8,Personal Care,"[Baby Care, Bath & Body, Electronics & Appliances, Feminine Hygiene, Fragrances & Grooming, Skincare]"
9,Sweet Tooth,"[Bath & Body, Biscuits, Dairy, Bread & Eggs, Frozen Food, Ice Creams & More, Munchies, Packaged Food, Sweet Cravings]"

In [24]:
master = df[["department", "category"]].drop_duplicates()
city_stock = (
    df.groupby("city")["out_of_stock_flag"]
    .value_counts()
    .unstack(fill_value=0)
)

city_stock["Total"] = city_stock.sum(axis=1)
city_stock["Out_of_stock_%"] = (
    city_stock["Yes"] / city_stock["Total"] * 100
).round(2)

city_stock.sort_values("Out_of_stock_%", ascending=False)

out_of_stock_flag     No    Yes  Total  Out_of_stock_%
city
Karimnagar          2176   1521   3697           41.14
Vasai Virar         4354   2219   6573           33.76
Mumbai             47266  20039  67305           29.77
Kolkata            21116   7986  29102           27.44
Kharar              2622    876   3498           25.04
Chennai            34430  10950  45380           24.13
Chandigarh          2650    817   3467           23.57
Behta Hajipur       3468   1061   4529           23.43
Faridabad          11947   3603  15550           23.17
Hyderabad          58280  16965  75245           22.55
Jaipur             14264   3986  18250           21.84
Pune               22672   6318  28990           21.79
Nashik              5866   1597   7463           21.40
Udaipur             3000    750   3750           20.00
Ahmedabad           8691   2108  10799           19.52
Greater Noida       3702    847   4549           18.62
Nagpur              8902   1994  10896           18.30
Surat              11823   2613  14436           18.10
Bangalore          81233  17812  99045           17.98
S.A.S Nagar         3660    775   4435           17.47
Secunderabad        3645    756   4401           17.18
Ludhiana            5734   1056   6790           15.55
Kalyan-Dombivli     2452    440   2892           15.21
Hubballi            3339    569   3908           14.56
Amritsar            5475    918   6393           14.36
Kanpur              9257   1539  10796           14.26
Prayagraj           8929   1465  10394           14.09
Dehradun            3529    557   4086           13.63
Jalandhar           2858    434   3292           13.18
Navsari             2760    401   3161           12.69
Hosur               3212    464   3676           12.62
Mysuru              6459    819   7278           11.25
Meerut              2838    216   3054            7.07
Coimbatore          3040    112   3152            3.55

In [25]:
dept_stock = (
    df.groupby("department")["out_of_stock_flag"]
    .value_counts()
    .unstack(fill_value=0)
)

dept_stock["Total"] = dept_stock.sum(axis=1)
dept_stock["Out_of_stock_%"] = (
    dept_stock["Yes"] / dept_stock["Total"] * 100
).round(2)

dept_stock.sort_values("Out_of_stock_%", ascending=False)

out_of_stock_flag        No    Yes  Total  Out_of_stock_%
department
Dairy & Breakfast     44050  14280  58330           24.48
Baby Care             55161  17719  72880           24.31
Cold Drinks & Juices  35761  11150  46911           23.77
Personal Care         59009  17825  76834           23.20
Bakery & Biscuits     31426   9172  40598           22.59
Organic & Premium     46527  11968  58495           20.46
Beauty & Cosmetics    71392  17029  88421           19.26
Atta, Rice & Dal      17292   4058  21350           19.01
Sweet Tooth           32628   7656  40284           19.01
Munchies              22403   3726  26129           14.26

In [26]:

cat_stock = (
    df.groupby("category")["out_of_stock_flag"]
    .value_counts()
    .unstack(fill_value=0)
)

cat_stock["Total"] = cat_stock.sum(axis=1)
cat_stock["Out_of_stock_%"] = (
    cat_stock["Yes"] / cat_stock["Total"] * 100
).round(2)

cat_stock.sort_values("Out_of_stock_%", ascending=False)

out_of_stock_flag             No    Yes  Total  Out_of_stock_%
category
Zepto Cafe                   313   2674   2987           89.52
Pharma & Wellness            229    139    368           37.77
Electronics & Appliances    1690    995   2685           37.06
Dairy, Bread & Eggs        23690  11719  35409           33.10
Fragrances & Grooming       9811   3622  13433           26.96
Baby Care                  26411   9566  35977           26.59
Feminine Hygiene           15390   4738  20128           23.54
Sweet Cravings             17853   5412  23265           23.26
Toys & Sports              25248   7594  32842           23.12
Makeup & Beauty            16690   4841  21531           22.48
Biscuits                   21935   6025  27960           21.55
Cold Drinks & Juices       25180   6502  31682           20.52
Atta, Rice, Oil & Dals     26059   6522  32581           20.02
Skincare                   41232  10128  51360           19.72
Hair Care                  18952   4468  23420           19.08
Bath & Body                26428   5912  32340           18.28
Ice Creams & More          25341   5632  30973           18.18
Packaged Food              18015   3747  21762           17.22
Munchies                   25141   5052  30193           16.73
Masala, Dry Fruits & More  14350   2858  17208           16.61
Breakfast & Sauces         18181   3453  21634           15.96
Frozen Food                 3003    527   3530           14.93
Tea, Coffee & More         14507   2457  16964           14.48

In [27]:
store_oos = (
    df.pivot_table(
        index=["city", "store_id"],
        columns="out_of_stock_flag",
        aggfunc="size",
        fill_value=0
    )
    .reset_index()
)

# Ensure both columns exist
for col in ["Yes", "No"]:
    if col not in store_oos.columns:
        store_oos[col] = 0

store_oos["Total"] = store_oos["Yes"] + store_oos["No"]
store_oos["Out_of_stock_%"] = (
    store_oos["Yes"] / store_oos["Total"] * 100
).round(2)

store_oos = store_oos.sort_values(
    "Out_of_stock_%",
    ascending=False
)

store_oos

out_of_stock_flag,city,store_id,No,Yes,Total,Out_of_stock_%
133,Mumbai,0b45bb12-e3bd-415b-b298-ee97db10a222,0,1,1,100.00
92,Hyderabad,819d4daf-ab7a-4291-be40-3070ebb46cec,0,59,59,100.00
61,Chennai,a98f0f81-73ab-4839-8d06-4e9427680054,1695,1325,3020,43.87
198,Vasai Virar,0b45bb12-e3bd-415b-b298-ee97db10a222,2123,1563,3686,42.40
66,Chennai,fb0d381c-e38f-4bcc-a5f8-872e3e033e62,2132,1527,3659,41.73
117,Karimnagar,a06b81f7-ce53-499c-bcd0-768ec804abae,2176,1521,3697,41.14
120,Kolkata,5d94bdb2-32fe-42f1-bc68-732d1d7ccb11,378,263,641,41.03
135,Mumbai,0ef81b30-ea84-46ec-98b0-6f3894d1ca1d,1221,828,2049,40.41
147,Mumbai,74aa405e-238e-4103-abb3-096bd7e6f553,1924,1220,3144,38.80
119,Kolkata,553c9cfa-5a00-4b98-a1d5-152c813e12d2,2200,1300,3500,37.14
154,Mumbai,94036a35-fd9f-4a7c-9697-782b5ef575f0,1342,774,2116,36.58
159,Mumbai,b8f93707-6d8d-4c31-8b58-627f09ba83cf,2061,1188,3249,36.57
157,Mumbai,ae984dc5-d33f-49cd-914c-d95d51f9e0ca,2126,1196,3322,36.00
134,Mumbai,0e8c4509-c9cd-4235-9da5-18fbede8ce72,762,426,1188,35.86
127,Kolkata,e879c6cf-e4bd-4b11-a605-4e9b2ee2365d,405,224,629,35.61
160,Mumbai,cc72f206-e146-43c5-a01b-56ddc8d11464,2187,1182,3369,35.08
128,Kolkata,eedbad6f-ada7-40cd-922e-828198efed50,2287,1225,3512,34.88
156,Mumbai,ab5b8567-c808-4008-8793-b83489a3c6fa,2075,1087,3162,34.38
138,Mumbai,238a227d-697c-4fa9-a4f5-4fd064760098,2120,1108,3228,34.32
164,Mumbai,fe7c8d05-02c0-4358-a794-1d5f862d74e8,2440,1267,3707,34.18
96,Hyderabad,a2271e79-a91e-4f7a-8a89-c69982cb5fbc,1890,969,2859,33.89
161,Mumbai,d390ee2b-1c8f-4236-9c8b-b60173fd330a,2163,1094,3257,33.59
145,Mumbai,52917883-e475-4632-9fa3-9c99ba0f4b78,2161,1092,3253,33.57
153,Mumbai,8c75d846-b50e-44c1-82d2-01bc39ad1ab3,2223,1122,3345,33.54
12,Bangalore,29b4c8b1-587b-497c-b4d9-bd2177fefb34,940,468,1408,33.24
78,Hyderabad,13ffc117-24d6-4854-a53e-a51d7330973e,2187,1052,3239,32.48
126,Kolkata,ab3bee45-6ef0-4dbe-bf5f-253d0817ceb5,2340,1120,3460,32.37
144,Mumbai,50be453c-91e9-4a62-913c-3d6add84eb57,370,170,540,31.48
152,Mumbai,8a278c72-1366-4926-b81e-ecc6e64df2a7,709,311,1020,30.49
58,Chennai,64b8c907-1b43-4f03-a739-fa20d2ac339f,2482,1079,3561,30.30
71,Faridabad,8f4404df-c3e2-4a76-9e9c-ade81e757c3e,2448,1057,3505,30.16
148,Mumbai,769200e9-30cc-47a2-81d4-58904ed953cc,728,311,1039,29.93
185,Pune,dd73c1bc-4757-4993-896b-cc949247ba76,2541,1026,3567,28.76
62,Chennai,b4d53703-4b49-4a38-85ca-7e321d1d5222,2006,810,2816,28.76
24,Bangalore,5f97e876-bbea-4c00-8df2-2005db7db8dc,2616,1052,3668,28.68
102,Hyderabad,b9881384-2b90-44c7-8af2-e22c10f20ca2,2638,1051,3689,28.49
87,Hyderabad,5ca7734d-e625-4328-8588-a4a102966b36,2421,952,3373,28.22
122,Kolkata,6de0ff52-a112-489b-bbb4-da655f8943ce,2468,967,3435,28.15
84,Hyderabad,43b12c97-dc99-431a-9ba3-e3cde9c716bb,2650,1025,3675,27.89
70,Faridabad,24419582-74c5-42eb-b56b-2ae54181e752,2764,1060,3824,27.72
109,Jaipur,2036c1f6-0885-407c-a607-6a237897ae33,2709,1038,3747,27.70
46,Behta Hajipur,49d9df40-6b3b-4f3e-ad7d-bda18f57d419,1373,517,1890,27.35
184,Pune,c7c3f33e-7fdb-4be2-9693-9809420f5200,2255,847,3102,27.30
32,Bangalore,97bf23f5-dc0c-4783-ba7d-9d6da842066b,2647,979,3626,27.00
22,Bangalore,5c85fffa-7130-43f2-9b34-0decc06beddc,2642,956,3598,26.57
88,Hyderabad,6671859b-cb7c-4dc7-bba6-d6554b27b7b2,2718,973,3691,26.36
142,Mumbai,4441ba38-6245-40db-9bdd-a2ac697f16fb,79,28,107,26.17
146,Mumbai,5feee4ae-dfd9-4484-b060-722c7802c642,2389,844,3233,26.11
151,Mumbai,87980e31-e60f-409d-bc05-e5a0e2bc90d5,2514,875,3389,25.82
41,Bangalore,e0e12ce6-3431-4ed8-a74b-b0de26426220,972,336,1308,25.69
59,Chennai,8e706906-0373-4de9-b9f7-cbfcc5ab2bca,2616,902,3518,25.64
170,Nashik,1794eede-9e42-4a9c-b132-0be5b0e4e4a4,2801,953,3754,25.39
50,Chennai,01c75445-012e-4df6-b075-6856318038cc,2257,761,3018,25.22
118,Kharar,2bf9f3ff-7b68-4ac5-a814-1059b71840cf,2622,876,3498,25.04
106,Hyderabad,e9c206f4-5e36-40ea-9d34-071b0c016be3,2808,936,3744,25.00
85,Hyderabad,4c93e224-40da-4c86-a5ff-c9c2cfee1168,991,328,1319,24.87
97,Hyderabad,a898c8dc-70a7-4af3-9bf8-7907d6d6f5de,2450,801,3251,24.64
129,Kolkata,f953916f-d684-447e-b750-c1f4ca34bc33,2877,933,3810,24.49
176,Pune,315e9d84-2c4a-45b2-88fb-f6733794efba,2401,777,3178,24.45
36,Bangalore,a7860f3d-39d4-4275-811d-904d4c2438f4,1086,348,1434,24.27
141,Mumbai,3b18ee5e-9d22-44cd-acff-646042e546bf,868,278,1146,24.26
26,Bangalore,6b1d82f8-b2ea-4e43-ae70-6f6bca1ec77a,1144,363,1507,24.09
1,Ahmedabad,1105d3fb-0556-4f7e-bd83-416274e9924a,2775,877,3652,24.01
150,Mumbai,80b12cfb-d607-43e3-bf17-6b2f8c854e40,2506,781,3287,23.76
107,Jaipur,07b1b3f7-203d-4d37-9297-1ea22235fe2c,3079,950,4029,23.58
49,Chandigarh,2c224926-8b10-4295-9710-004f8e7b3880,2650,817,3467,23.57
136,Mumbai,102af115-4cad-419f-9bd5-567159eefc5c,2540,782,3322,23.54
48,Behta Hajipur,f090d50a-60ed-4b98-9493-3f0d9751a3f3,884,271,1155,23.46
8,Bangalore,0cde9637-ca43-45b6-a89c-08c1e32bae57,2333,712,3045,23.38
181,Pune,8beb19a0-01c1-4e12-841d-7d7e440a296f,2477,751,3228,23.27
82,Hyderabad,314533d4-8bd7-4985-8ca5-9b737431149b,2821,855,3676,23.26
186,Pune,e2305bd9-95df-47f0-8b81-54b606b1497e,990,299,1289,23.20
103,Hyderabad,bd86f0fb-6044-45d9-be30-8b58c26e3688,3034,914,3948,23.15
110,Jaipur,32989280-a610-4395-aca5-5ba4823af4bd,2897,871,3768,23.12
57,Chennai,600240d4-efb5-484c-ac8a-2dbfe997975a,2749,825,3574,23.08
121,Kolkata,6acc6a77-e2fc-4772-94e5-41a0e031c59e,2046,613,2659,23.05
199,Vasai Virar,8185771a-0624-44cc-8370-b1299e6649a5,2231,656,2887,22.72
193,Surat,2918790f-421a-493e-84a3-e9a2d8f0b60d,494,145,639,22.69
80,Hyderabad,26ec9b6b-b566-4f36-b5dd-eb6fb92a0caf,273,78,351,22.22
81,Hyderabad,2a3b1c03-c42a-484e-bdd9-bc853efd6fca,2836,802,3638,22.05
11,Bangalore,2240913f-e14f-46cc-94e8-ff6f5c32ffab,2824,791,3615,21.88
180,Pune,7a75116f-d14e-49b3-bfde-a6c2a4d180a7,990,276,1266,21.80
17,Bangalore,3bf7d17f-4fa3-481d-b14d-66ca5c4f14da,1126,313,1439,21.75
108,Jaipur,133688fc-cadd-4750-bb5f-f595c5eca821,2925,809,3734,21.67
54,Chennai,3994880c-5e18-4de9-9f68-847c18108e27,2711,744,3455,21.53
52,Chennai,3587d930-d517-4847-8e2c-c48ecabeba45,2399,658,3057,21.52
162,Mumbai,e278914b-34ce-4bd8-a961-1a4456c620cc,901,246,1147,21.45
94,Hyderabad,95bc5024-3ef7-49b5-80a9-9c9df49638dc,2910,793,3703,21.42
139,Mumbai,250d0a67-ee4b-4cdd-ac75-0c5e65c25ee9,2154,579,2733,21.19
56,Chennai,5f9020d1-08d3-4f69-9185-c3933a67c67a,1081,289,1370,21.09
183,Pune,c00b42da-968d-46af-b09d-8313ed62be85,2582,686,3268,20.99
99,Hyderabad,adec0623-e83c-46cc-9eef-d33b4486d054,2467,644,3111,20.70
29,Bangalore,843e630a-7896-462d-b7cf-712140483ed3,1077,281,1358,20.69
6,Bangalore,0053a04d-aeb4-46b5-99fe-d740491e3843,2832,738,3570,20.67
74,Greater Noida,eb6b329a-e514-4f86-b1b0-d11991efc00a,2571,663,3234,20.50
90,Hyderabad,6fdc556b-2daf-480a-b272-b48c18e4460c,2887,735,3622,20.29
20,Bangalore,5400933d-3c5d-4015-a767-daed27781a0d,2539,644,3183,20.23
0,Ahmedabad,0bbde96c-7012-4731-afad-78c7bf7b381e,2484,628,3112,20.18
69,Faridabad,04c98d7c-c6bf-41f6-8d43-dc50e7c0edb1,3085,776,3861,20.10
197,Udaipur,8dd0f61c-7734-4af8-b5e2-bf198cf6fe56,3000,750,3750,20.00
194,Surat,2cad2a10-1a07-4006-971e-6b305738e8e4,2875,714,3589,19.89
10,Bangalore,1c9e155e-83a8-457a-a687-01eabb1e7a36,1188,294,1482,19.84
93,Hyderabad,8dcc9bd0-fb05-42e9-96c7-ef15a999c522,877,217,1094,19.84
30,Bangalore,917d20a7-58e4-4574-95dd-dfe3513dd1b2,2524,621,3145,19.75
18,Bangalore,416b9549-1413-435d-b08b-1d150131f6cd,2530,621,3151,19.71
63,Chennai,b51017b6-8aed-4bff-a391-ba12ec8f9cee,2493,611,3104,19.68
34,Bangalore,9fb087cf-076d-40a0-b974-8d26eaa69f44,2557,623,3180,19.59
189,S.A.S Nagar,7b2176ce-862d-4e58-9d5e-6373e729c2a6,2505,607,3112,19.51
167,Nagpur,2a87c5ee-1495-4e8f-a259-f1246ab1f2d2,2791,672,3463,19.41
44,Bangalore,eeea2403-3a6e-49b7-874b-3d8743ef3cd8,2629,632,3261,19.38
104,Hyderabad,c7cea2d4-d5c9-476b-aa5e-8c72bad4148d,2602,611,3213,19.02
125,Kolkata,a747aca8-5583-4f32-aa16-e804cefaa95a,2910,676,3586,18.85
169,Nagpur,ea7bcce0-6cbf-4a46-a731-3cc66449e073,2925,671,3596,18.66
83,Hyderabad,33a1d02e-1bb7-44cc-8d38-9697bcc23dba,937,215,1152,18.66
140,Mumbai,3608083a-c098-4f58-bc13-4a729a103909,964,219,1183,18.51
178,Pune,3a15115a-c99e-4421-bfcc-5b97a2716da5,2661,603,3264,18.47
47,Behta Hajipur,57a0c2ae-1cf1-4c4a-99eb-eb2e19864075,1211,273,1484,18.40
123,Kolkata,6de9aaa0-268d-44a5-8e39-aa2130d5354a,2962,664,3626,18.31
79,Hyderabad,1712e422-5717-4540-88ff-b22ef46f4963,2716,607,3323,18.27
195,Surat,4eeabcee-900c-419e-a2bb-102bbb205c7a,2720,599,3319,18.05
35,Bangalore,a1c67132-94e3-41b9-975b-4ef4e4851406,3235,710,3945,18.00
55,Chennai,59099ea0-3411-4169-9c90-206cb03ef12a,1106,242,1348,17.95
86,Hyderabad,56d50978-df14-48ba-aec8-79644b36fd6a,1001,219,1220,17.95
73,Faridabad,fb48fc60-af3a-421b-9cce-928e2c0cb95f,2940,640,3580,17.88
89,Hyderabad,6893b298-d63b-4c4f-b155-2e4a0ca502d5,2718,586,3304,17.74
158,Mumbai,b26ca2be-f12b-4645-a83a-adf09ecfd28b,965,207,1172,17.66
171,Nashik,72a5dc2f-b97c-406d-b3e4-090e99736baf,3065,644,3709,17.36
95,Hyderabad,9ea894e0-db78-45f7-beb1-10b6a52c3fb8,1024,215,1239,17.35
196,Surat,62648dc2-e2ea-48d9-8d26-314169b943ac,2983,623,3606,17.28
191,Secunderabad,819d4daf-ab7a-4291-be40-3070ebb46cec,2647,551,3198,17.23
137,Mumbai,1cf40b2e-95cd-4581-9ab9-bca81d4932ab,916,190,1106,17.18
187,Pune,f931724a-0140-4c06-b832-027e03fc320a,959,198,1157,17.11
190,Secunderabad,02a58e65-a110-4856-b787-16ba7ef238ec,998,205,1203,17.04
168,Nagpur,2b28a8f0-7027-4c5b-8a0b-63c748e5e29d,3186,651,3837,16.97
5,Amritsar,b9438b1f-1c27-4708-855d-f1b31b36186d,2541,519,3060,16.96
105,Hyderabad,d71ff3ac-0dbd-43de-bf48-6a1b0ba17c12,894,180,1074,16.76
51,Chennai,0bb39cdb-14fd-4692-b79f-db081ce25de3,1128,225,1353,16.63
3,Ahmedabad,e677968e-5901-4ff2-8613-ebd72359a67c,462,91,553,16.46
192,Surat,21217c69-8530-4f00-9366-e96ab493bfe8,2751,532,3283,16.20
179,Pune,68e86539-d883-4fc2-b735-0ab599643721,2713,520,3233,16.08
175,Prayagraj,fee654ba-4ae4-4295-89f0-fbd9116eb24a,3024,578,3602,16.05
115,Kanpur,30a65b0b-3941-4a5f-a0e4-8d0626b37c89,3129,590,3719,15.86
7,Bangalore,0059ff6a-7eb0-477a-a7f5-69256f2c444b,819,154,973,15.83
14,Bangalore,312fd0bd-4163-4768-8e94-ea1dc57783dd,2411,450,2861,15.73
37,Bangalore,abd85a95-f3f3-42fd-aeb0-71b9127335f5,1115,208,1323,15.72
25,Bangalore,658cf319-0b10-4dbe-809e-ea5c913974cb,1178,219,1397,15.68
131,Ludhiana,986955c7-3776-4a2f-affa-64e183f5c057,2649,488,3137,15.56
130,Ludhiana,7bd58b6d-6d2d-4056-8d6e-830f6d9f6e09,3085,568,3653,15.55
45,Bangalore,f6807d7c-9f71-49c7-9a15-50919b30fccf,1749,320,2069,15.47
100,Hyderabad,b0a2db37-733d-46d1-808b-7af068fc7f8a,1047,190,1237,15.36
15,Bangalore,320121c9-8af7-4921-9eea-5c456b7a900d,2679,483,3162,15.28
113,Kalyan-Dombivli,daa42edb-d1d5-49f7-8872-dcc94bddace1,2452,440,2892,15.21
28,Bangalore,774a725c-2c4b-4dc2-94d1-72b737f7e1f6,1169,209,1378,15.17
114,Kanpur,01084781-096d-4da8-bc1c-cd56769e8d87,3164,558,3722,14.99
31,Bangalore,93e0e2c3-23a6-471f-9025-8dd79ef87d60,369,65,434,14.98
177,Pune,34d81293-1443-44be-9db9-043f95f184ee,1042,183,1225,14.94
91,Hyderabad,778b5c2b-0468-4f1e-8fa0-241cc91608a2,945,166,1111,14.94
2,Ahmedabad,46b54f69-c5ff-4595-934d-3d98fbf33ec0,2970,512,3482,14.70
16,Bangalore,3a44ca1a-adde-4f8e-9e0c-613a98d348b7,2717,466,3183,14.64
77,Hubballi,50ec3eef-df88-4e0d-94d3-2e120efa7655,3339,569,3908,14.56
173,Prayagraj,2132443f-a32b-487a-b774-ce86e7184578,2970,506,3476,14.56
149,Mumbai,803931bb-511e-48bc-8611-4b9910682bb4,982,167,1149,14.53
33,Bangalore,992bee8f-8936-4b04-9d17-546cd0ba1b76,1202,204,1406,14.51
163,Mumbai,e5319547-8bba-4fee-862c-7d9ab6dc97c8,929,155,1084,14.30
43,Bangalore,ea49abf1-77df-4575-8022-fbcf9e25b3b4,2581,429,3010,14.25
155,Mumbai,a9588bc2-3d75-410c-88c3-ec029bf4593a,961,159,1120,14.20
101,Hyderabad,b0f7b4fe-835a-4ca6-907c-20be2be7cc50,2573,421,2994,14.06
75,Greater Noida,fc05177a-ca9e-4c93-9811-dbb101b0c8f7,1131,184,1315,13.99
65,Chennai,f503f309-0f93-4388-850f-1091f44232e0,2510,405,2915,13.89
68,Dehradun,d0e7fabd-57c5-4073-9c43-dc5bbdf3d8fd,3529,557,4086,13.63
143,Mumbai,47cc42b0-3e50-42e3-bd10-0ecbf677c981,986,152,1138,13.36
40,Bangalore,dccddf98-bc2f-4ca7-810e-93d59cca7ec2,1218,187,1405,13.31
38,Bangalore,b91d4052-6ea1-4b97-9aba-d6a642735146,2869,439,3308,13.27
112,Jalandhar,69a4936b-bb91-4e5a-b524-41ec759d4aa7,2858,434,3292,13.18
39,Bangalore,c9d7d275-70b0-4f96-a48f-2a49801fdee8,2820,411,3231,12.72
188,S.A.S Nagar,6b2bedfe-37f6-4d5d-9cf9-a19250f2a4e5,1155,168,1323,12.70
172,Navsari,bdd193e6-8ee2-4ee4-bf18-22ed8772b20d,2760,401,3161,12.69
76,Hosur,24161f96-e91b-451f-ae76-79a5c7469496,3212,464,3676,12.62
182,Pune,ac91c141-986b-4bb1-9bb8-5b0be08b65de,1061,152,1213,12.53
19,Bangalore,425e2ef0-02bc-4c87-b423-cfbc6e56984a,2841,395,3236,12.21
27,Bangalore,6cf381cd-d178-4bd1-8018-14218a4c0c0d,1224,168,1392,12.07
4,Amritsar,9c668882-09c3-4d40-8a71-de5200ded97e,2934,399,3333,11.97
9,Bangalore,1ba2b8e0-aa82-4a78-b38b-477b97eac054,2659,358,3017,11.87
21,Bangalore,5a365997-32ca-4016-a42c-7108b5701d65,2836,376,3212,11.71
166,Mysuru,9e3001c8-62f6-4305-87fc-7280c8028beb,3399,451,3850,11.71
116,Kanpur,7d68a957-c0e8-4841-ad02-f98b4dddcee2,2964,391,3355,11.65
53,Chennai,37906ef4-331c-471c-b332-0bf7a979fc07,1176,153,1329,11.51
174,Prayagraj,9b7e899c-2925-4eae-bf55-bed98c832df3,2935,381,3316,11.49
98,Hyderabad,ad36d77c-bdd7-427c-bbab-089efa9b5b1e,2965,371,3336,11.12
64,Chennai,b812518e-9cc3-45e3-8fef-a1dd3311194c,1243,155,1398,11.09
165,Mysuru,68737136-459b-40b1-82bd-64557d1d50f1,3060,368,3428,10.74
42,Bangalore,e58fff62-7695-44c2-aba0-6bc96074bc64,1920,230,2150,10.70
111,Jaipur,bf926ab8-f286-4011-8de2-2561674ec588,2654,318,2972,10.70
23,Bangalore,5ec071fd-78df-41f6-b3ae-7298d9f96a3d,2668,306,2974,10.29
72,Faridabad,a95989f3-34a1-4288-b318-a01c946b6919,710,70,780,8.97
13,Bangalore,2fd0f3ca-d788-41bc-be14-a18850bf78cc,2748,253,3001,8.43
60,Chennai,9a0f103e-1350-4c05-9e96-e01e02e758e6,2646,239,2885,8.28
132,Meerut,f8592f97-f226-4555-8ee7-16ff7cb3554a,2838,216,3054,7.07
67,Coimbatore,eafd2469-2d6a-41f6-910e-f2399603b53e,3040,112,3152,3.55
124,Kolkata,a6974b40-413b-4867-86c2-45e7e61fb13c,243,1,244,0.41

In [28]:
# Product count per store
store_distribution = (
    df.groupby(["city", "store_id"])
      .size()
      .reset_index(name="product_count")
      .sort_values("product_count")
)

print(store_distribution)

                city                              store_id  product_count
133           Mumbai  0b45bb12-e3bd-415b-b298-ee97db10a222              1
92         Hyderabad  819d4daf-ab7a-4291-be40-3070ebb46cec             59
142           Mumbai  4441ba38-6245-40db-9bdd-a2ac697f16fb            107
124          Kolkata  a6974b40-413b-4867-86c2-45e7e61fb13c            244
80         Hyderabad  26ec9b6b-b566-4f36-b5dd-eb6fb92a0caf            351
31         Bangalore  93e0e2c3-23a6-471f-9025-8dd79ef87d60            434
144           Mumbai  50be453c-91e9-4a62-913c-3d6add84eb57            540
3          Ahmedabad  e677968e-5901-4ff2-8613-ebd72359a67c            553
127          Kolkata  e879c6cf-e4bd-4b11-a605-4e9b2ee2365d            629
193            Surat  2918790f-421a-493e-84a3-e9a2d8f0b60d            639
120          Kolkata  5d94bdb2-32fe-42f1-bc68-732d1d7ccb11            641
72         Faridabad  a95989f3-34a1-4288-b318-a01c946b6919            780
7          Bangalore  0059ff6a-7eb0-477a-a7f5-69256f2c444b            973
152           Mumbai  8a278c72-1366-4926-b81e-ecc6e64df2a7           1020
148           Mumbai  769200e9-30cc-47a2-81d4-58904ed953cc           1039
105        Hyderabad  d71ff3ac-0dbd-43de-bf48-6a1b0ba17c12           1074
163           Mumbai  e5319547-8bba-4fee-862c-7d9ab6dc97c8           1084
93         Hyderabad  8dcc9bd0-fb05-42e9-96c7-ef15a999c522           1094
137           Mumbai  1cf40b2e-95cd-4581-9ab9-bca81d4932ab           1106
91         Hyderabad  778b5c2b-0468-4f1e-8fa0-241cc91608a2           1111
155           Mumbai  a9588bc2-3d75-410c-88c3-ec029bf4593a           1120
143           Mumbai  47cc42b0-3e50-42e3-bd10-0ecbf677c981           1138
141           Mumbai  3b18ee5e-9d22-44cd-acff-646042e546bf           1146
162           Mumbai  e278914b-34ce-4bd8-a961-1a4456c620cc           1147
149           Mumbai  803931bb-511e-48bc-8611-4b9910682bb4           1149
83         Hyderabad  33a1d02e-1bb7-44cc-8d38-9697bcc23dba           1152
48     Behta Hajipur  f090d50a-60ed-4b98-9493-3f0d9751a3f3           1155
187             Pune  f931724a-0140-4c06-b832-027e03fc320a           1157
158           Mumbai  b26ca2be-f12b-4645-a83a-adf09ecfd28b           1172
140           Mumbai  3608083a-c098-4f58-bc13-4a729a103909           1183
134           Mumbai  0e8c4509-c9cd-4235-9da5-18fbede8ce72           1188
190     Secunderabad  02a58e65-a110-4856-b787-16ba7ef238ec           1203
182             Pune  ac91c141-986b-4bb1-9bb8-5b0be08b65de           1213
86         Hyderabad  56d50978-df14-48ba-aec8-79644b36fd6a           1220
177             Pune  34d81293-1443-44be-9db9-043f95f184ee           1225
100        Hyderabad  b0a2db37-733d-46d1-808b-7af068fc7f8a           1237
95         Hyderabad  9ea894e0-db78-45f7-beb1-10b6a52c3fb8           1239
180             Pune  7a75116f-d14e-49b3-bfde-a6c2a4d180a7           1266
186             Pune  e2305bd9-95df-47f0-8b81-54b606b1497e           1289
41         Bangalore  e0e12ce6-3431-4ed8-a74b-b0de26426220           1308
75     Greater Noida  fc05177a-ca9e-4c93-9811-dbb101b0c8f7           1315
85         Hyderabad  4c93e224-40da-4c86-a5ff-c9c2cfee1168           1319
37         Bangalore  abd85a95-f3f3-42fd-aeb0-71b9127335f5           1323
188      S.A.S Nagar  6b2bedfe-37f6-4d5d-9cf9-a19250f2a4e5           1323
53           Chennai  37906ef4-331c-471c-b332-0bf7a979fc07           1329
55           Chennai  59099ea0-3411-4169-9c90-206cb03ef12a           1348
51           Chennai  0bb39cdb-14fd-4692-b79f-db081ce25de3           1353
29         Bangalore  843e630a-7896-462d-b7cf-712140483ed3           1358
56           Chennai  5f9020d1-08d3-4f69-9185-c3933a67c67a           1370
28         Bangalore  774a725c-2c4b-4dc2-94d1-72b737f7e1f6           1378
27         Bangalore  6cf381cd-d178-4bd1-8018-14218a4c0c0d           1392
25         Bangalore  658cf319-0b10-4dbe-809e-ea5c913974cb           1397
64           Chennai  b812518e-9cc3-45e3-8fef-a1dd3311194c           1398
40         Bangalore  dccddf98-bc2f-4ca7-810e-93d59cca7ec2           1405
33         Bangalore  992bee8f-8936-4b04-9d17-546cd0ba1b76           1406
12         Bangalore  29b4c8b1-587b-497c-b4d9-bd2177fefb34           1408
36         Bangalore  a7860f3d-39d4-4275-811d-904d4c2438f4           1434
17         Bangalore  3bf7d17f-4fa3-481d-b14d-66ca5c4f14da           1439
10         Bangalore  1c9e155e-83a8-457a-a687-01eabb1e7a36           1482
47     Behta Hajipur  57a0c2ae-1cf1-4c4a-99eb-eb2e19864075           1484
26         Bangalore  6b1d82f8-b2ea-4e43-ae70-6f6bca1ec77a           1507
46     Behta Hajipur  49d9df40-6b3b-4f3e-ad7d-bda18f57d419           1890
135           Mumbai  0ef81b30-ea84-46ec-98b0-6f3894d1ca1d           2049
45         Bangalore  f6807d7c-9f71-49c7-9a15-50919b30fccf           2069
154           Mumbai  94036a35-fd9f-4a7c-9697-782b5ef575f0           2116
42         Bangalore  e58fff62-7695-44c2-aba0-6bc96074bc64           2150
121          Kolkata  6acc6a77-e2fc-4772-94e5-41a0e031c59e           2659
139           Mumbai  250d0a67-ee4b-4cdd-ac75-0c5e65c25ee9           2733
62           Chennai  b4d53703-4b49-4a38-85ca-7e321d1d5222           2816
96         Hyderabad  a2271e79-a91e-4f7a-8a89-c69982cb5fbc           2859
14         Bangalore  312fd0bd-4163-4768-8e94-ea1dc57783dd           2861
60           Chennai  9a0f103e-1350-4c05-9e96-e01e02e758e6           2885
199      Vasai Virar  8185771a-0624-44cc-8370-b1299e6649a5           2887
113  Kalyan-Dombivli  daa42edb-d1d5-49f7-8872-dcc94bddace1           2892
65           Chennai  f503f309-0f93-4388-850f-1091f44232e0           2915
111           Jaipur  bf926ab8-f286-4011-8de2-2561674ec588           2972
23         Bangalore  5ec071fd-78df-41f6-b3ae-7298d9f96a3d           2974
101        Hyderabad  b0f7b4fe-835a-4ca6-907c-20be2be7cc50           2994
13         Bangalore  2fd0f3ca-d788-41bc-be14-a18850bf78cc           3001
43         Bangalore  ea49abf1-77df-4575-8022-fbcf9e25b3b4           3010
9          Bangalore  1ba2b8e0-aa82-4a78-b38b-477b97eac054           3017
50           Chennai  01c75445-012e-4df6-b075-6856318038cc           3018
61           Chennai  a98f0f81-73ab-4839-8d06-4e9427680054           3020
8          Bangalore  0cde9637-ca43-45b6-a89c-08c1e32bae57           3045
132           Meerut  f8592f97-f226-4555-8ee7-16ff7cb3554a           3054
52           Chennai  3587d930-d517-4847-8e2c-c48ecabeba45           3057
5           Amritsar  b9438b1f-1c27-4708-855d-f1b31b36186d           3060
184             Pune  c7c3f33e-7fdb-4be2-9693-9809420f5200           3102
63           Chennai  b51017b6-8aed-4bff-a391-ba12ec8f9cee           3104
99         Hyderabad  adec0623-e83c-46cc-9eef-d33b4486d054           3111
189      S.A.S Nagar  7b2176ce-862d-4e58-9d5e-6373e729c2a6           3112
0          Ahmedabad  0bbde96c-7012-4731-afad-78c7bf7b381e           3112
131         Ludhiana  986955c7-3776-4a2f-affa-64e183f5c057           3137
147           Mumbai  74aa405e-238e-4103-abb3-096bd7e6f553           3144
30         Bangalore  917d20a7-58e4-4574-95dd-dfe3513dd1b2           3145
18         Bangalore  416b9549-1413-435d-b08b-1d150131f6cd           3151
67        Coimbatore  eafd2469-2d6a-41f6-910e-f2399603b53e           3152
172          Navsari  bdd193e6-8ee2-4ee4-bf18-22ed8772b20d           3161
156           Mumbai  ab5b8567-c808-4008-8793-b83489a3c6fa           3162
15         Bangalore  320121c9-8af7-4921-9eea-5c456b7a900d           3162
176             Pune  315e9d84-2c4a-45b2-88fb-f6733794efba           3178
34         Bangalore  9fb087cf-076d-40a0-b974-8d26eaa69f44           3180
20         Bangalore  5400933d-3c5d-4015-a767-daed27781a0d           3183
16         Bangalore  3a44ca1a-adde-4f8e-9e0c-613a98d348b7           3183
191     Secunderabad  819d4daf-ab7a-4291-be40-3070ebb46cec           3198
21         Bangalore  5a365997-32ca-4016-a42c-7108b5701d65           3212
104        Hyderabad  c7cea2d4-d5c9-476b-aa5e-8c72bad4148d           3213
181             Pune  8beb19a0-01c1-4e12-841d-7d7e440a296f           3228
138           Mumbai  238a227d-697c-4fa9-a4f5-4fd064760098           3228
39         Bangalore  c9d7d275-70b0-4f96-a48f-2a49801fdee8           3231
179             Pune  68e86539-d883-4fc2-b735-0ab599643721           3233
146           Mumbai  5feee4ae-dfd9-4484-b060-722c7802c642           3233
74     Greater Noida  eb6b329a-e514-4f86-b1b0-d11991efc00a           3234
19         Bangalore  425e2ef0-02bc-4c87-b423-cfbc6e56984a           3236
78         Hyderabad  13ffc117-24d6-4854-a53e-a51d7330973e           3239
159           Mumbai  b8f93707-6d8d-4c31-8b58-627f09ba83cf           3249
97         Hyderabad  a898c8dc-70a7-4af3-9bf8-7907d6d6f5de           3251
145           Mumbai  52917883-e475-4632-9fa3-9c99ba0f4b78           3253
161           Mumbai  d390ee2b-1c8f-4236-9c8b-b60173fd330a           3257
44         Bangalore  eeea2403-3a6e-49b7-874b-3d8743ef3cd8           3261
178             Pune  3a15115a-c99e-4421-bfcc-5b97a2716da5           3264
183             Pune  c00b42da-968d-46af-b09d-8313ed62be85           3268
192            Surat  21217c69-8530-4f00-9366-e96ab493bfe8           3283
150           Mumbai  80b12cfb-d607-43e3-bf17-6b2f8c854e40           3287
112        Jalandhar  69a4936b-bb91-4e5a-b524-41ec759d4aa7           3292
89         Hyderabad  6893b298-d63b-4c4f-b155-2e4a0ca502d5           3304
38         Bangalore  b91d4052-6ea1-4b97-9aba-d6a642735146           3308
174        Prayagraj  9b7e899c-2925-4eae-bf55-bed98c832df3           3316
195            Surat  4eeabcee-900c-419e-a2bb-102bbb205c7a           3319
157           Mumbai  ae984dc5-d33f-49cd-914c-d95d51f9e0ca           3322
136           Mumbai  102af115-4cad-419f-9bd5-567159eefc5c           3322
79         Hyderabad  1712e422-5717-4540-88ff-b22ef46f4963           3323
4           Amritsar  9c668882-09c3-4d40-8a71-de5200ded97e           3333
98         Hyderabad  ad36d77c-bdd7-427c-bbab-089efa9b5b1e           3336
153           Mumbai  8c75d846-b50e-44c1-82d2-01bc39ad1ab3           3345
116           Kanpur  7d68a957-c0e8-4841-ad02-f98b4dddcee2           3355
160           Mumbai  cc72f206-e146-43c5-a01b-56ddc8d11464           3369
87         Hyderabad  5ca7734d-e625-4328-8588-a4a102966b36           3373
151           Mumbai  87980e31-e60f-409d-bc05-e5a0e2bc90d5           3389
165           Mysuru  68737136-459b-40b1-82bd-64557d1d50f1           3428
122          Kolkata  6de0ff52-a112-489b-bbb4-da655f8943ce           3435
54           Chennai  3994880c-5e18-4de9-9f68-847c18108e27           3455
126          Kolkata  ab3bee45-6ef0-4dbe-bf5f-253d0817ceb5           3460
167           Nagpur  2a87c5ee-1495-4e8f-a259-f1246ab1f2d2           3463
49        Chandigarh  2c224926-8b10-4295-9710-004f8e7b3880           3467
173        Prayagraj  2132443f-a32b-487a-b774-ce86e7184578           3476
2          Ahmedabad  46b54f69-c5ff-4595-934d-3d98fbf33ec0           3482
118           Kharar  2bf9f3ff-7b68-4ac5-a814-1059b71840cf           3498
119          Kolkata  553c9cfa-5a00-4b98-a1d5-152c813e12d2           3500
71         Faridabad  8f4404df-c3e2-4a76-9e9c-ade81e757c3e           3505
128          Kolkata  eedbad6f-ada7-40cd-922e-828198efed50           3512
59           Chennai  8e706906-0373-4de9-b9f7-cbfcc5ab2bca           3518
58           Chennai  64b8c907-1b43-4f03-a739-fa20d2ac339f           3561
185             Pune  dd73c1bc-4757-4993-896b-cc949247ba76           3567
6          Bangalore  0053a04d-aeb4-46b5-99fe-d740491e3843           3570
57           Chennai  600240d4-efb5-484c-ac8a-2dbfe997975a           3574
73         Faridabad  fb48fc60-af3a-421b-9cce-928e2c0cb95f           3580
125          Kolkata  a747aca8-5583-4f32-aa16-e804cefaa95a           3586
194            Surat  2cad2a10-1a07-4006-971e-6b305738e8e4           3589
169           Nagpur  ea7bcce0-6cbf-4a46-a731-3cc66449e073           3596
22         Bangalore  5c85fffa-7130-43f2-9b34-0decc06beddc           3598
175        Prayagraj  fee654ba-4ae4-4295-89f0-fbd9116eb24a           3602
196            Surat  62648dc2-e2ea-48d9-8d26-314169b943ac           3606
11         Bangalore  2240913f-e14f-46cc-94e8-ff6f5c32ffab           3615
90         Hyderabad  6fdc556b-2daf-480a-b272-b48c18e4460c           3622
123          Kolkata  6de9aaa0-268d-44a5-8e39-aa2130d5354a           3626
32         Bangalore  97bf23f5-dc0c-4783-ba7d-9d6da842066b           3626
81         Hyderabad  2a3b1c03-c42a-484e-bdd9-bc853efd6fca           3638
1          Ahmedabad  1105d3fb-0556-4f7e-bd83-416274e9924a           3652
130         Ludhiana  7bd58b6d-6d2d-4056-8d6e-830f6d9f6e09           3653
66           Chennai  fb0d381c-e38f-4bcc-a5f8-872e3e033e62           3659
24         Bangalore  5f97e876-bbea-4c00-8df2-2005db7db8dc           3668
84         Hyderabad  43b12c97-dc99-431a-9ba3-e3cde9c716bb           3675
82         Hyderabad  314533d4-8bd7-4985-8ca5-9b737431149b           3676
76             Hosur  24161f96-e91b-451f-ae76-79a5c7469496           3676
198      Vasai Virar  0b45bb12-e3bd-415b-b298-ee97db10a222           3686
102        Hyderabad  b9881384-2b90-44c7-8af2-e22c10f20ca2           3689
88         Hyderabad  6671859b-cb7c-4dc7-bba6-d6554b27b7b2           3691
117       Karimnagar  a06b81f7-ce53-499c-bcd0-768ec804abae           3697
94         Hyderabad  95bc5024-3ef7-49b5-80a9-9c9df49638dc           3703
164           Mumbai  fe7c8d05-02c0-4358-a794-1d5f862d74e8           3707
171           Nashik  72a5dc2f-b97c-406d-b3e4-090e99736baf           3709
115           Kanpur  30a65b0b-3941-4a5f-a0e4-8d0626b37c89           3719
114           Kanpur  01084781-096d-4da8-bc1c-cd56769e8d87           3722
108           Jaipur  133688fc-cadd-4750-bb5f-f595c5eca821           3734
106        Hyderabad  e9c206f4-5e36-40ea-9d34-071b0c016be3           3744
109           Jaipur  2036c1f6-0885-407c-a607-6a237897ae33           3747
197          Udaipur  8dd0f61c-7734-4af8-b5e2-bf198cf6fe56           3750
170           Nashik  1794eede-9e42-4a9c-b132-0be5b0e4e4a4           3754
110           Jaipur  32989280-a610-4395-aca5-5ba4823af4bd           3768
129          Kolkata  f953916f-d684-447e-b750-c1f4ca34bc33           3810
70         Faridabad  24419582-74c5-42eb-b56b-2ae54181e752           3824
168           Nagpur  2b28a8f0-7027-4c5b-8a0b-63c748e5e29d           3837
166           Mysuru  9e3001c8-62f6-4305-87fc-7280c8028beb           3850
69         Faridabad  04c98d7c-c6bf-41f6-8d43-dc50e7c0edb1           3861
77          Hubballi  50ec3eef-df88-4e0d-94d3-2e120efa7655           3908
35         Bangalore  a1c67132-94e3-41b9-975b-4ef4e4851406           3945
103        Hyderabad  bd86f0fb-6044-45d9-be30-8b58c26e3688           3948
107           Jaipur  07b1b3f7-203d-4d37-9297-1ea22235fe2c           4029
68          Dehradun  d0e7fabd-57c5-4073-9c43-dc5bbdf3d8fd           4086

In [31]:
import re

# Normalize brand names
df["brand_norm"] = (
    df["brand_name"]
    .fillna("")
    .str.lower()
    .str.replace(r"[^a-z0-9]", "", regex=True)   # remove spaces, ', -, &, etc.
)

# Find brands that become the same after normalization
brand_issue = (
    df.groupby("brand_norm")
    .agg(
        variant_count=("brand_name", "nunique"),
        brand_variants=("brand_name", lambda x: sorted(set(x)))
    )
    .reset_index()
)

brand_issue = brand_issue[brand_issue["variant_count"] > 1]

brand_issue

,brand_norm,variant_count,brand_variants
210,bonn,2,"[Bonn, bonn]"
214,borges,2,"[BORGES, Borges]"
374,delichic,2,"[Deli Chic, Delichic]"
757,kharifoods,2,"[KHARI FOODS, Khari Foods]"
1021,noto,2,"[NOTO, Noto]"
1095,paperboat,2,"[PAPER BOAT, Paper Boat]"
1108,patanjali,2,"[PATANJALI, Patanjali]"
1140,plixtheplantfix,2,"[Plix -The Plant Fix, Plix The Plant Fix]"
1343,star,2,"[STAR, Star]"
1375,sunscoop,2,"[SunScoop, Sunscoop]"

In [32]:
# 1. Group by unique_id to see if physical attributes split
id_integrity_check = (
    df.groupby("unique_id")
    .agg(
        grammage_count=("product_grammage", "nunique"),
        grammage_variants=("product_grammage", lambda x: list(set(x.dropna()))),
        quantity_count=("net_quantity", "nunique"),
        quantity_variants=("net_quantity", lambda x: list(set(x.dropna()))),
        category_count=("category", "nunique"),
        category_variants=("category", lambda x: list(set(x.dropna()))),
    )
    .reset_index()
)

# 2. Filter for rows where an ID maps to MORE THAN ONE physical variation
corrupted_ids = id_integrity_check[
    (id_integrity_check["grammage_count"] > 1) | 
    (id_integrity_check["quantity_count"] > 1)
]

# 3. Display the errors
print(f"Found {len(corrupted_ids)} unique_ids tied to different products.")
print(corrupted_ids)

Found 0 unique_ids tied to different products.
Empty DataFrame
Columns: [unique_id, grammage_count, grammage_variants, quantity_count, quantity_variants, category_count, category_variants]
Index: []

In [33]:
# 1. Group by identity columns to isolate the exact same physical product
product_identity_issues = (
    df.groupby(["unique_id", "product_grammage", "net_quantity"])
    .agg(
        # Count how many different spelling/name variations exist for this product
        name_variant_count=("product_name", "nunique"),
        # Create an alphabetised list of those unique name variations
        name_variants=("product_name", lambda x: sorted(set(x))),
        # Optional: capture variations in brand name for the same product
        brand_variants=("brand_name", lambda x: sorted(set(x.dropna()))),
    )
    .reset_index()
)

# 2. Filter for rows where the same product has more than 1 name variation
name_issues_by_id = product_identity_issues[
    product_identity_issues["name_variant_count"] > 1
]

# 3. View the final flagged discrepancies
print(name_issues_by_id)

Empty DataFrame
Columns: [unique_id, product_grammage, net_quantity, name_variant_count, name_variants, brand_variants]
Index: []

In [39]:
import pandas as pd

# Ensure stock_count is numeric
df["stock_count"] = pd.to_numeric(df["stock_count"], errors="coerce")

# Normalize out_of_stock_flag
flag = df["out_of_stock_flag"].astype(str).str.strip().str.lower()

# 1. out_of_stock_flag = Yes, but stock_count > 0
yes_stock_gt0 = df[
    (flag == "yes") &
    (df["stock_count"] > 0)
]

print(f"Rows with out_of_stock_flag='Yes' but stock_count > 0: {len(yes_stock_gt0)}")
print(yes_stock_gt0[["unique_id", "product_name", "store_id", "stock_count", "out_of_stock_flag"]])

# 2. out_of_stock_flag = No, but stock_count = 0
no_stock_0 = df[
    (flag == "no") &
    (df["stock_count"] == 0)
]

print(f"\nRows with out_of_stock_flag='No' but stock_count = 0: {len(no_stock_0)}")
print(no_stock_0[["unique_id", "product_name", "store_id", "stock_count", "out_of_stock_flag"]])

Rows with out_of_stock_flag='Yes' but stock_count > 0: 0
Empty DataFrame
Columns: [unique_id, product_name, store_id, stock_count, out_of_stock_flag]
Index: []

Rows with out_of_stock_flag='No' but stock_count = 0: 0
Empty DataFrame
Columns: [unique_id, product_name, store_id, stock_count, out_of_stock_flag]
Index: []

In [37]:
df.columns

Index(['crawl_date_and_time', 'platform_name', 'store_id',
       'store_name_location', 'city', 'pin_code', 'unique_id',
       'product_id_upc_ean', 'department', 'category', 'sub_category',
       'product_type', 'brand_name', 'product_name', 'product_description',
       'product_grammage', 'package_type', 'net_quantity', 'variants',
       'item_mrp', 'item_selling_price', 'out_of_stock_flag', 'discount_flag',
       'product_price', 'unit_price', 'promo_offer_description',
       'promo_offer_price', 'discount_in_percent', 'stock_count',
       'product_url', 'product_image_urls', 'brand_norm'],
      dtype='object')

In [40]:
df.groupby("product_url").agg(
    product_names=("product_name","nunique"),
    brands=("brand_name","nunique"),
).query("product_names>1 or brands>1")

Empty DataFrame
Columns: [product_names, brands]
Index: []

In [41]:
df.groupby("unique_id")["item_selling_price"].nunique().sort_values(ascending=False)

unique_id
83993140-0a88-4fe6-88c2-b57387112bf2    41
26510ea9-60a1-403c-a384-0c18b76b80fb    37
3210a5bf-160c-4e19-b460-ed058b10c668    37
84483b5d-7565-44c9-981c-e0af4513c4a3    35
8d1ef43e-241d-4cc6-b876-ab4fda4cf477    35
77d5f543-508a-402d-9dae-0f29849e9143    33
eda2cd5b-008e-4458-8ffb-d81ee4273355    32
030e8ebc-0f11-41d0-a10d-8480028490b5    31
f9062f3b-2491-48a9-b99f-810b11384187    31
3357387a-98b5-4f3d-bdfb-77d885ccc870    31
16806c97-f2dc-4374-9a1c-c2a45376d0f8    31
e6718341-7434-4716-af82-1a5641b0f9fd    30
ada057ef-353d-4fa5-a187-a34e5daf0864    29
2e678e64-bafc-42d1-a78a-225fe2941897    29
0a163074-c63f-4122-a28e-a344ab0dfb5d    29
2e1f7fe5-2d09-4282-81c7-b4eaf6b1d86d    29
09100e95-eb80-4089-8f4a-7cad4fc65be7    29
e1f1abda-2bd6-4e89-af90-9fef56d91408    29
e37b78d8-afb7-49d7-b210-c5a15d6a75b5    28
e470294c-6a0d-42ac-b2ff-409da0cae4d1    28
5287b430-8619-478b-a41a-0453f45093a6    28
b613076a-5e7b-4248-895d-5263de719157    28
0e83682e-664b-43de-a3d0-39c8b4dae8f7    27
82afa262-7f22-4fa4-b73b-8476d0cf5e6c    27
05977f30-4b13-4ab0-af08-a52fc04872e0    27
fdbbb7ba-7a0e-4339-95f4-d671e8cd2b24    27
7d641307-3a79-4495-871b-182a56ba6ab5    26
dc08d538-2786-4aca-9302-8608221fd376    26
9850d3f3-f5b8-4830-af33-35aa92d35211    26
ca65a05e-60ea-4cc3-a066-a6c06696465b    26
6e05255e-c395-4497-bc04-0845aa7a00d2    25
32a4ac79-8987-4c82-9cdd-caeaba7d6e7e    25
5a3f869a-ff8d-46ea-b4d3-b230b26d0b75    25
7474f472-5cdc-4362-98bf-71d3b6c6aae5    25
4e461724-3f74-4323-9eae-01b75e0c1e4a    25
fc46bf54-928d-4c57-a81d-ddd2f68af3ec    24
bef08b53-1620-4911-8021-76ebf2511619    24
bb3437d0-568b-41b5-81cd-d01db7af7804    24
974a07de-42dd-475e-b21a-073b4b9a028f    24
d4fafc6e-5137-4f23-bc86-647d7b7072da    24
435b32e5-e9a6-4216-be6a-eb4abf1df73d    24
f745287f-81bd-4e0f-adb0-d97a9b3d3a76    24
43e7fb9a-67eb-4447-998f-7853d8aac77c    24
cfbf008c-0d22-4a25-ae4b-c23629483eba    23
88f7b083-15a6-468c-9ed5-f33606bb3645    23
54e461e8-132f-4220-9f68-e0f5a0eabcde    23
0eec54ea-bc04-419e-997f-728f5f4e5b41    23
9a99b440-cf97-4601-b478-1b6b7ef3f17c    23
b4ab548e-a7ca-475c-8f54-28961b400a29    23
8ad80401-e58f-4d29-8d64-feb8c9359248    22
149465fe-cce1-4bdb-8c01-50c3a67f7a4d    22
27b3694d-cafe-4bf2-9db6-188c96a250d4    22
decec6a6-a951-4b22-bf3e-6c7cc440fac9    22
3de2caa9-911c-4091-9365-5b211f4d3470    22
2527dbce-7b96-47ef-9cfd-402411a99f27    22
1cbb3ad7-98ea-4287-acd1-bd195bfb187e    21
8546b13c-dc23-41bc-beaf-5f48baf28ac4    21
542ea023-523d-4f51-aaf7-a698a6a53ef9    21
9016525f-35ec-40f0-a4b9-83df8d9e719c    21
f20dcde7-4ed3-46a7-bbde-b6e9e582aa68    21
e33c5e7d-a115-4b2b-b99e-146a2dbfa887    21
613e85ff-be16-432c-b32a-ea576a4e12f0    21
ced1cc30-63c6-484c-a418-4d22a40d3a9b    20
219eef0d-a48a-428a-b4e8-ed6cf810ebda    20
191091bd-1b7e-4de2-82e3-ae090f075dbc    20
d3567ea3-d103-442d-bc34-2a40b0da1fc2    20
b45fe06f-fd6c-4f9f-acdb-55a7868e9561    20
45a8e9f4-89d4-4a8a-a257-b50a3f7d6a53    20
7fc43f46-7fd1-4e25-860a-74992f871a34    20
395dfe47-2e79-4af6-a9a5-0c8a6a8f31b9    20
e25b38c3-5c36-4d50-9e50-b60330125434    20
14a11cfe-fd72-4901-bf2e-22bc0aba21c0    20
aaabbe07-af05-4ea8-973b-29e8bb744af0    20
5a32f237-f030-4b97-a5c9-361cc3090f0d    20
70187bd1-dfe6-4c1d-94af-e0d52d5f446d    20
9089d753-f1b2-4771-99bf-f7b4edcd8598    20
e57d8f7b-839a-47e4-8976-0ebbdc415328    20
6eac5b92-118c-4c33-aca6-791ab268a868    19
019c70bc-9bc9-4f7c-b13c-722e7c6ed4f0    19
4a7d4796-0d8a-4627-907f-e6df14abf923    19
cd29ae34-341b-41b5-98e9-2a0c1ec49c97    19
a5b9d61d-6325-44a2-b71a-eef719285527    19
f81ef0f8-8249-4b5b-9c78-514a755a15c9    19
66ba554d-5f06-47ba-91fd-50ba62096bec    19
1a091cc5-bcde-4ba9-aa49-c81cf27efa72    19
f7743c4f-e1c4-4d1f-b795-e8c275561824    19
09a3fa35-819a-4ea3-8f34-12379761fc43    19
ef411392-7552-4a8b-8c36-a16250b23e6f    19
2f1589de-e6e2-4dd9-b9d4-3f8559c8cf26    19
a8277963-9eca-4e87-b5ef-8f0caafb1294    19
3502020f-8f35-4244-8c9b-b863617964e6    19
c1a836b1-a505-48de-b74d-40ba6e58b9f6    19
f0055c1d-3aec-47ee-9305-f87db2eb3208    19
4e74ae99-43a7-4ce6-8966-e1a176c37e16    19
ffa3b601-44a0-4f1a-aae2-9861ab804003    18
613f183f-f332-4357-ba58-176897cb9be9    18
f2de0c35-afd0-4c47-846e-fd3bb8ce4065    18
e0c65e93-3f0e-4a79-8d2b-e09d0348f90a    18
639f367c-3d05-466d-82dc-f7cf4954a98a    18
71a7eed6-36e9-4a7f-9f49-19ea6540a146    18
0fbd5e93-6d69-4930-ab73-7d72a8366515    18
4ac2eaf8-4f7f-4b66-9d6a-2c7100199094    18
4d8f43f8-3b1b-407c-9e20-19121e3f319e    18
586ba662-c061-487d-a3ab-8719399f9ab8    18
dcbca8b6-4855-4198-be37-607595d8d6ca    18
ad4f01f8-2093-43ca-b088-826ae7ec97ff    18
388882d8-24ef-44ad-aec2-84b33251956a    18
c82b6b6a-db8d-48fa-b8bb-d82bdbc90a28    18
c7514415-5dcb-4550-a18a-35fda15a2bbb    18
2487794b-17b5-4041-ae97-46a5fd413d98    18
ab5f5a5a-859c-447e-9bdf-c772b0061e6a    18
aca47ae2-f913-4920-a2b8-73197065a510    18
2894d81c-762f-4757-8b30-9db599529521    18
2b5cb65f-5440-47e4-bc97-5a94575dcbfa    18
2c157578-52ac-4ac6-84c0-d24747d8c894    18
ba9c6112-8a4e-453c-8a05-9effd4c8728e    18
61df3740-b205-42bc-a65c-af17cc20dcca    18
95133585-5a6a-41f1-94e5-d4e3406c1c58    18
fea626b7-c88d-4dd5-917b-c8404a17f036    17
960991d1-6892-4b3f-a9f0-53b22c3ed76d    17
975b7149-bc29-4206-b840-f3033c27ce63    17
649d3c41-fe6c-4cbe-b5dc-b655ad94e8cc    17
6213646d-38d6-4757-bf9c-65dc7062901c    17
f47a6dff-4d24-4aab-b679-a58a00f6cdcd    17
3145077b-a503-43b8-98ff-8f625497611f    17
48630434-1240-46bd-bdb3-f8783bb8fd3a    17
2da2dcca-ab8e-4e00-afbc-7dd0652fcaca    17
b898b507-c1cf-4db7-972a-1729449d0104    17
857b2613-87f3-4d3c-a26f-2a7fbac6e6a2    17
b5fdc5d4-0e78-44d8-b88a-a285190a7ae1    17
2e227c90-d06c-42f3-8cc4-cb9d5b466c14    17
7f4eb3c2-3a6f-4c7c-9dc2-165cfaa6acb0    17
b0fdb7cf-8be4-4b0f-bd71-b6fe05cb943c    17
33c15579-e33b-4ff0-86da-f5a8231d5305    17
c3b939d1-e0cf-4af1-92b0-c6a7223034ce    17
74641627-2fbf-4f9f-9809-5d8458b92beb    17
75118c7a-2b92-441a-995c-ea416b67c05e    17
8c1e993a-a1e7-4f56-b6e7-8b4b2836a79f    17
77731a97-e79e-425e-93f6-a06d8e45c4a5    17
13652e6c-c057-404d-b788-c6ded97898b3    17
3874e54b-fe0f-4b97-9e7b-963c61be5b18    17
cf7bfead-3f0d-443d-b7ae-714871d22485    17
f4248e23-40f0-4961-8c82-6d52801c469c    17
f74ec7b9-f4b8-43fb-8952-cc6f0b489195    17
01624b7e-f308-4ccf-92fe-4e24f8373c52    17
4ac99346-a191-4912-a641-a9b7ed107204    17
715c2127-d8b8-4563-9064-5397e641baa9    17
6385d009-d6f7-4566-977a-61c15a375155    17
9096031d-7f79-4bc3-831a-654d6ef650d6    17
48c91445-c9a3-4476-9cd1-e22f6f9e0ffd    17
02f06d00-5bfc-4574-9fe3-d96d443da0f8    16
ef4a81ca-a952-4c31-bc1d-527b1934dfe0    16
81f24788-2bae-4be8-aa45-c79d2c42e0fd    16
28edf098-05da-4844-be4d-bded5677c062    16
08aa72b7-cac2-4cbb-84d9-525c812f19fa    16
4524e68b-de30-4188-98ca-0c0c7a17807e    16
6233fc21-8d19-4e9a-bc22-5a9cea1f1fa9    16
ba15b027-ebf0-4d8b-8179-14bacc0965dc    16
4d9f6da9-ed1f-43d5-8ba6-4e30fa23a8a2    16
a98bdb28-a929-4fcd-a043-ba24d4924f9f    16
1e67bac7-aacd-432e-9b0b-1ebaec959879    16
d309d1bd-88fa-4f59-811e-c454b16ff283    16
4c244cd6-9464-4136-b057-d81376593e51    16
f7b9124f-022b-4896-a7a6-8c546d89a996    16
1838fc64-53b9-4c17-a1e8-a2cfe1bba163    16
aa47e77e-31bb-45ca-bafe-ab653385bd43    16
cf9fc46a-6fc6-44b8-bb65-efba05dac42c    16
6543ff39-5838-479a-a807-4050160061fb    16
0de96881-8bea-4c43-99a2-3b6e7a8a4404    16
0eb32131-29f3-4e16-8c2c-ad4b21d84925    16
74abb8da-390c-4d1a-a820-f9b1b9e68e5a    16
fd3d2f39-55b5-4f9f-9254-995881b4e0ec    16
e17bc673-734e-4ecc-991f-b84d0f25375a    16
4b3d2164-6d2f-4cab-a143-da6ca283aaa1    16
1e181b72-d3dd-4e9f-b891-89a0dc3dfcee    16
bcbc296e-7f4e-4ffc-a9d0-e6321907261a    16
c56d4253-ecba-4e33-a6e2-096f21b4afdc    16
c9ee2f29-e51c-46a3-b5f8-6d8979a448c7    16
2b798ea3-d301-4b17-b24e-d7326fa77d88    16
27f6d723-530b-4cb9-9d8d-15f145586b30    16
9d4721e4-988a-4198-a913-295abd4ba731    16
05682926-595c-4128-bb43-56dfb3554b84    16
3f0f0e0c-7600-4693-bae6-7cba28200086    16
6aaf813a-3c8d-4962-b9d6-0802b1b4f180    16
075c7a64-bd06-4212-8708-821b12498b61    16
4907f3af-c281-4005-aff6-a9aa3b2d76d9    16
49e9d348-c2c4-4e39-97d2-1423e0eed04c    16
ec12d5e5-decd-4d3f-89d3-ff7eefbb9034    15
0d0bf7e3-7dd4-438b-b383-4368a74171dd    15
69a13443-b86c-4f6f-ba38-01957f8ea51a    15
2b2fd349-2a57-4012-8fde-fc63dad18dd0    15
554cf524-77e5-444c-81c8-a9cb2457c886    15
353a9959-7d59-460c-87be-dbe6c9974722    15
c49afcbe-4659-419f-837d-a259d2581a6a    15
8223bc79-161b-4199-ab68-5ac5456ba63e    15
3399e640-9900-4eb4-b828-23a84b3537e6    15
c9f6d388-b25e-42d1-be23-106f79875580    15
cde7ab52-1f1a-4d33-8a17-77769524feb3    15
3c921d61-f4c7-4d4c-b103-20fcfc214231    15
f85fddf0-0be1-487d-b18d-3c846943e2f2    15
e14564e8-eb16-452b-b18e-04f088f4f99e    15
8be9c68f-a400-4aee-92e3-ba040f7979b3    15
8f0f5208-f2bf-42c4-a3ce-7e3a1da29602    15
744c9206-55f8-4da9-942c-00c89f8ab58e    15
e63d819d-c5d7-47f9-93df-898bfbc04c56    15
a5fea040-1493-46a4-ac8d-d80c65f1d2b4    15
99dc7f02-e56f-4dd5-b855-ac813f027306    15
05cc5db6-9efa-480a-8d0c-54784fbc9100    15
ea3df1d3-43d8-4488-bc87-62f43a292d40    15
655a3bcc-cb91-4142-89ae-f97d539c47a2    15
ffa5cbb7-35c2-4c8d-a8af-a267be241a47    15
417e0248-653c-4f8f-b602-47e82710f444    15
879d6c64-407a-4c1f-8870-c8a10a2b05c5    15
68f5c5a0-52a1-4fb0-b579-5d827c6e43e7    15
53723dd5-385f-42a2-a436-a458036c104a    15
32fe31b9-7ec7-445a-8497-96acee80b8d3    15
6bd93422-8c6f-453b-ae1b-1d1c729c87c5    15
458dea74-0871-4c81-b470-1a632879f709    15
2e87966f-e237-4c39-8441-db71f0299b55    15
30c8c4d8-813b-4993-8427-dde70b87d3f1    15
91b9227a-ae22-477a-858c-8e4b8618f075    15
53fa789d-c8d2-4c4a-b094-f388ab6c243a    15
e1bce14e-be6c-4d41-97de-98e8a5dccc08    15
7a8777d7-d5b3-40ff-8560-731e1011a2e0    15
1b3c9c59-924f-436c-91fb-910bcc3dee01    15
19f4ad81-ba8b-4b15-a967-626ff73fd513    15
d8ba87b0-564d-43ee-a0df-0a54dc8343a6    15
d442ea2f-fd6c-45c9-8a02-44b6c9e74361    15
d8edb52c-a2a8-4b02-8c32-593664e3743a    15
768f2da0-c540-43d3-ad7d-ac324890bd47    15
94572f53-c1fa-4349-b707-a48d7823376e    14
f34f778e-8d2b-4a7f-93e2-7e26ab08b29c    14
f5922860-41af-4a6e-9b8f-c245edc620db    14
9f2234df-575c-4565-95dc-ab0fb7087e9f    14
0edf8817-3d39-44fb-8535-016cac9b8387    14
9f6fc5f6-ec7f-4721-bb3d-b22141eb7e7c    14
5ff1be41-0298-4961-aba5-5a985e202364    14
0cdf3e42-df5b-4ba2-80f3-fcc620589e37    14
7c8fe3ac-b2f7-4e2e-b3c9-340ef93399ae    14
d2259114-9ce4-4d45-92c5-6fc37302c20f    14
581cae53-c9d0-4252-8aa1-9685bbfce841    14
8ba438ef-862d-45b9-b1b4-645d808d3ddb    14
1d9efb28-ced2-4766-8351-bfb6e45310f6    14
509ab892-5253-4d73-af78-6074ae214e12    14
31ad3e8b-e689-48c1-956c-ca36d9fcac2c    14
204bae0f-b5ec-4dcc-b242-3b74fe082f40    14
f727750a-d453-4a78-bd17-c390337128b9    14
38358849-27e1-4b7e-a60d-11091bd10584    14
0572bde1-4550-4376-862e-28e0231a9e1e    14
5cc9240d-113b-4c32-88e4-91a958172182    14
dca9c355-4eb0-463c-8378-5d6f5e7cf94e    14
dcd996b6-c892-48cb-9538-40ad23ecb9f4    14
cf854bbd-85e9-44bc-b638-6f961c090991    14
5f542063-3e4e-4718-8909-cda94ee6ffff    14
02d38d77-0dcc-4afe-b7f5-6fd44e1350b1    14
32542567-435c-4790-ae49-5718aa89e998    14
af6d72e8-8595-42f6-b793-64b013f75277    14
27874667-1ae6-4a3e-8ee0-b3a610bf15eb    14
fc0bdd04-2f61-4a5c-9126-486b4c041a76    14
c163250b-3001-40d5-8f84-cd63405d6fa4    14
2ae0c1ee-f4f1-44ef-a49b-6132ba09bc78    14
b0743ba8-9999-4c63-9bbe-06f2d8d96f52    14
cefba12d-2131-4e41-98e8-b7d78fc5ed41    14
ad176cf4-ea73-45a8-bcc1-0fd1fe475236    14
c8e831af-33e1-40d3-8bad-00b8335cd1ff    14
235888e5-1420-4a9b-bed3-65179d5d5a2b    14
cb3ee4d9-7e25-499f-b0fa-e9e6264520ef    14
24386ac7-d090-4d94-9409-2754adde3a4e    14
523fe8ca-3004-4317-9a78-48f79f3b786a    14
b4c7880a-bf17-4ec6-a459-f8dec064188c    14
b9606e95-79a6-4814-827d-104b680ca81f    14
08e5b8cc-6d36-41c7-bfd2-3e02dc831f42    14
b3509c76-ae8b-44c8-8e5f-cf936e31c154    14
855fcb95-ba25-4394-a258-dcac0d966e08    14
92f7b4eb-12a8-4ec0-b3b6-0965aba5bae1    13
b004a8a7-269a-4d4a-91bc-046ff039d3e8    13
b1c937d1-9261-4c67-8a65-0c9e8150a579    13
46cd042e-3078-45ac-926e-999d2afd3989    13
93191fbd-da23-4f0b-9f6b-bc0ad8bc96db    13
86cac8e8-6630-49f5-a719-fa5f4cf50225    13
fe83e377-084e-4ff0-8864-d730c4d697e2    13
efde57c1-5864-4f70-a47f-6703098b9b20    13
00e9993a-f99f-4665-b27b-08986a4656ba    13
0872187c-e750-42fc-b33d-1aba120ea12c    13
30b152b2-01d7-48e1-a2f8-dd186a629877    13
67a81fc2-805d-4a76-8b8d-fcb7213f2d61    13
cdfb753d-fb44-48fb-95c4-88a3172d1faa    13
cae2e985-0ea5-430e-a36b-d67db38440a9    13
c7d065ce-fada-4704-91fe-5e064b62b7d0    13
c8b9ebe9-8c73-40f8-ac82-c88b0422f36c    13
c7c18965-9de3-485b-8416-36adea2e1b2d    13
c64049e8-9fe7-48f6-8e6c-f3a682854de5    13
34e3e929-784e-40d6-bf90-c7a00f6e811f    13
c3f3f94e-e2da-408d-a1aa-d63db244135a    13
acb799d8-6207-4c87-bb10-16424cd9bf12    13
ac1ca509-f6dc-49b2-98ba-46158bc6642d    13
36153031-3e4e-4f9c-9082-16ec095479b4    13
037ea3c6-2e54-43a0-b661-13f2a10bd67e    13
814a464e-c18a-4354-ac70-47260fa51fcc    13
ac7b7e90-c3b6-457f-bae4-3c7e2c5889e8    13
5524e7ea-93f3-4370-b25f-c9297b1f95e4    13
bfe98cad-c52c-4c3f-9f99-ee9f0f71118f    13
4f1ae265-c0e0-45fc-a465-474b894aa365    13
68a46c0f-8162-47d3-a8e6-760f5a440913    13
52aa6ef7-5df5-4db1-b3e1-3c215ed8d23b    13
bb8417ab-2a00-44b3-af3f-e525ee3f8026    13
83bdbe14-f8e4-4d47-879a-3188e9167d1d    13
a7c6a97b-fd19-49d4-9e60-75c9b6aa06c8    13
1caaad95-f838-4496-8138-3d0ec901e085    13
cfc5e58e-1b02-4f88-9ae4-85630c217570    13
3898c8f8-ece2-4b20-908a-1b1a32b0561a    13
18e80b6c-a99b-4bf6-a73b-1550595534b5    13
4e19c635-76df-48ba-83b5-2c77160c5ce9    13
8a09b022-29c8-4ba0-ae64-8f6afe6a075e    13
f8c65255-f981-4c1d-9815-6e29cd68873e    13
f8d71d36-47b7-4698-b916-71ab6c409b0f    13
d6457ade-4d56-45c7-a4da-4bb6afbe27d2    13
d922a957-64e2-4668-9266-1606b1d8dfcb    13
a66ba5b4-313d-4469-becd-01b69bd19fc7    13
dfa322ca-723d-4643-a718-7c3969aa0f0a    13
199dfb62-de20-4cf2-bbbf-b97d3f65c5a5    13
77bfe56c-9477-464d-808f-f278447532c8    13
3d864a7a-472f-4a79-9a01-1fd3ed9b01a1    13
a183483e-2b62-4cf2-8f56-c247c120a403    13
a34d83f4-d16b-4900-9396-ee96d95efc88    13
a3c6b03e-8db7-4ea2-a1d8-a64b6131dbe7    13
5ad14521-f93c-4ac2-8fcc-da6588503ec8    13
e3eb93e8-c6f3-4546-add3-2e83f51ee54f    13
11746d45-226d-4ddc-9f20-ebdb177c9fac    13
728dcb00-71c0-443b-b41f-2fa610f90d68    13
8dc1764c-c222-4ccf-9bc1-6ece10e4cc10    13
3f3e18bb-6556-4a3f-9be6-c27897f3f814    13
40acaa97-bea6-47d3-9cb2-096832f53478    13
9e39e969-a986-4081-a8a8-1af7d6527cd3    13
0dc6eeae-c8da-4a10-91f9-c27f7092292c    13
e885d51e-6d37-47dd-9b02-42812c8f755e    13
0fa53887-990f-466a-a0b0-15fab43e587c    13
9cbcbdea-f766-4f74-9f95-34f8606886d8    13
499ae240-612d-49c2-ab91-d97d8bed73d3    13
995d79b0-b519-431f-9593-14153c5c2b48    13
9bd201f4-dc41-4bbc-a6e2-7c310a253a62    13
49985600-a0f1-4934-acb6-e47e72a5d62f    13
602c82c3-1f50-417e-98a4-b25a03d12f4e    13
942ea818-7b51-4d3b-8040-430fa8b4c48a    13
6b81904d-64e3-48a8-8218-0811995b817a    13
0af6a1a5-373b-4ddb-a661-cefc7f18298e    13
0bc71ba1-9e48-45a1-8bd5-2feace2493a6    13
6b74c69b-6c46-491c-9948-0f83b97199ab    13
ff5911cf-cce7-4d19-9efd-e53d2ffa7672    13
00043a6f-b506-433f-b9db-b293c0cf5797    13
662f8962-ae60-4b96-9576-2dcef343594e    12
790130a8-67e8-423f-8bfe-65ff979e3925    12
79231951-9ad9-401e-8e2b-225826d6522e    12
a1d5a506-7589-4bab-916b-023963bdcfd0    12
3d6b88b1-1560-4e17-a6b1-8451ecf90a4e    12
a0c0b2fa-9f63-4fba-8f11-622a3ccb98b5    12
1a045b07-a742-49f8-a013-ddda21e81f4b    12
d806fcb4-040f-4e6f-8d00-d2a75dc47532    12
a150d9de-7012-4129-9dbb-58737509b285    12
58afbca5-751f-43fb-9b27-27c603eb96c7    12
d4f55d77-d312-4fc3-96b1-bca933f4578f    12
19db9f2a-aa97-4efb-ab56-e4f98a54c697    12
7a7f3d8e-301b-4112-81e8-ac503c3dcb60    12
19960443-d118-432e-9d30-5b17cc358703    12
7886b5f6-5057-46a1-a12c-42bf99662844    12
f7db68e4-0f96-41eb-999b-ae45bc7a6519    12
8d9a353f-2365-447a-b5bd-13240cb5350b    12
a01fa7e7-fa5b-45e9-851f-a0cc719d796a    12
f4f7e38c-edc7-4744-ab79-554128ec8f6a    12
63285fe8-22f9-4aa8-85ab-3e8fc9fce6ab    12
075ad6d5-f149-4778-aadf-28006c05c37f    12
a2c09b3b-33df-4d18-a303-a5dcb0ad36b0    12
1de4add4-6913-4493-8c8a-623a9f93611c    12
db61cff9-1187-49af-9371-02d906c596c8    12
1f01a4c6-58a3-41e7-b281-04db458cfa56    12
d0115c08-b2d7-4030-99b2-45c014c66183    12
3eb079f0-ff8b-4147-8d19-82a0f3115770    12
fd3b8f1d-d5c2-40d5-8ebf-5b88eeee264e    12
fd596373-62eb-48fe-b2f3-db2f3c9906a5    12
5bb80dba-35df-4ee1-bf53-4d291c500a2c    12
9ee83a02-d976-4a17-960a-617ef79a2fac    12
cd62b99f-1079-403c-a2e2-3ebfd67a9f4b    12
14be28e7-7d84-4032-9d26-b20f71a85865    12
7e0ed43b-a0da-4b4b-b68e-5f61c3bb69a5    12
fbeb46dd-9edc-49f4-beb8-af66d1826812    12
40bf86d3-96c0-449d-b556-10ebc68864c9    12
8b0f5ca5-36a8-46a3-931d-c03ee296441a    12
22ab2df5-4421-4c4a-8fcc-e830ccf0c178    12
40b26866-dfc6-475a-bca1-7f16b3200fb8    12
e2e1b716-5b09-4f12-b33c-b8ed2104269d    12
744d3b9f-08b7-4404-96f1-104cb1f0efc5    12
7e6e1e61-1669-4f88-aa4e-3a843482f5c2    12
c8d338f1-a165-47aa-b37e-8d72f6121aa4    12
e3c72ece-b8f3-4443-b12c-500be91dc767    12
900b7f8b-f9b5-4fa9-b0f6-e8c1612e2343    12
7ea96138-bea0-4290-ae29-e836baabffbd    12
24a9f68f-00d1-4afc-a4b3-deb890bf3432    12
5dc6231b-b1d0-4a3a-9b72-535b34613ca6    12
7ffd54d7-c8be-47b3-83fb-1cc5c7e4cdb5    12
62b069eb-400c-4420-a173-e8f48a13a4b6    12
808ec98a-3fd4-4e14-b71f-bd270763ba40    12
2669fa33-7853-4e8b-928a-f4fba1f94ee4    12
e723b984-c0fb-4f72-bbff-146368925e9b    12
e76dcf81-93fb-4028-82c7-a369eef96750    12
6431a78f-cf70-42c1-baaa-3099d5999298    12
540c1546-e194-459b-9f54-e437b0d9d814    12
711e4576-4e1f-457e-8d12-e0f96c358769    12
9987df70-6c46-4528-a3cd-5c8b30ea5779    12
e8ae4dbd-90e2-4012-a84e-9ed9f69ce997    12
ac2794be-21f0-4ceb-912f-48788efe9e21    12
706bceeb-c8ab-413d-9d76-1d0d4e718278    12
c3480d95-a311-43ca-8429-27fe7dfeb40a    12
0e8c47cb-65ab-40aa-a197-300ab42f3b7d    12
02eb9ef2-deb9-433e-b19f-813c5bfd440a    12
43f70b75-b18f-4df4-a4ff-1cdee4eeba29    12
68ba22c8-6b2a-472b-b345-2525fd547b16    12
fee990c1-0f88-4ec9-b0b1-91cb62a4ce69    12
9817e5bc-05a7-4cf6-a813-6ad2ddaf92bc    12
48852b2a-3464-4168-8458-b303ee32fefe    12
beb074f2-5177-4d23-bcf6-2809bebf7e3e    12
0c331ede-39fb-4785-8bb3-cf026f214b0e    12
2a7ab3f9-838d-4176-bd5d-0da806212eb7    12
88499490-ee6c-465d-9918-942ef9c5cf9a    12
4ef49520-3b30-42a6-9fd3-1c957cdf29b6    12
34b10145-782c-4446-8119-132ef4f7ed62    12
82e8f251-f6a6-4329-afdf-5a4cfdf636ed    12
44f4ba73-ea5e-4614-b4fd-2e701def9609    12
ba6f6496-f00e-4f5d-a48b-7bab7d04b942    12
bad9d63c-5d61-4cc2-b70c-bb10a3286650    12
61380a4c-b4a9-4b38-b9e5-96fda9fcb641    12
2d663dbb-b37a-499d-8d7e-69d0e6280691    12
07fd1af5-e475-4887-9847-c857227da145    12
b9e1ac49-15ce-45da-b29e-857106ef9b92    12
47ed5e6d-9671-46d1-b270-d63bb2a8cf83    12
4f369899-59a5-4be6-a03b-812952277617    12
87dd168a-edb1-4f7b-9c41-44d858cc97c2    12
099615b9-3c86-4d39-b91b-c289ce1479a9    12
84c85a4c-3fd1-43b4-9b00-59c85178acf7    12
84e487cf-d36f-4c58-9b6e-26b18cfcfc53    12
0a11b273-3dcb-4e25-baab-6c1484ce8104    12
95503470-af74-4ff0-ae05-4dd1ea393069    12
b0ac7b04-6f46-4389-b27c-53b6edfc96c3    12
2e0f013e-656d-4268-a0d3-a24220be47a1    12
623a8198-09d3-4580-9375-d86075da50c9    12
868e6144-6b12-42fd-a77c-cbbae25c25ec    12
a13eae98-c10d-4820-bcb9-4ccabe16284e    12
46db6fe2-77ba-42d9-92d7-8885a81ecd78    11
63679135-5064-4b95-b2a8-7c5001c1ef2c    11
b3939770-63ce-4c56-9a14-90e2f2baeffc    11
dcaf9185-df23-46ea-9ed9-56e4c4dbc880    11
f19e60af-fec7-4e79-a21c-9de1a2e8773a    11
6499701b-7916-4d7e-8428-544ee6d39610    11
029374a8-2cf3-4d9f-bc5c-5ffc24bf3010    11
103929b3-80bc-4e3b-ad8c-ca10dd03e89a    11
f6c9eee8-8916-44d7-94e0-85e28c168ace    11
9a00845a-c34a-4f2c-bf1d-8a46e0543698    11
4258be74-7f9b-4862-940e-183be09b5c26    11
54099eb2-2d08-4013-a822-a3eebc72f19f    11
806ae9f7-b106-430e-871a-a6e00f43079a    11
dd7cbd38-59e1-4e76-8ee6-53313719994f    11
dc7e77e0-3cb3-4a6f-a0fb-bf35f131e184    11
aa82d15d-82f6-49fc-9b20-c3ee4fc04e37    11
3f07a1f0-2ac4-4a57-8d43-4e8d22b7bccb    11
1126dd64-d572-4856-a677-407f4505b72a    11

In [42]:
import pandas as pd

# Convert price columns to numeric
price_cols = [
    "item_mrp",
    "item_selling_price",
    "discount_in_percent"
]

for col in price_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

# Normalize discount flag
flag = df["discount_flag"].astype(str).str.strip().str.lower()

# 1. Selling Price > MRP
selling_gt_mrp = df[df["item_selling_price"] > df["item_mrp"]]

print(f"1. Selling Price > MRP : {len(selling_gt_mrp)} rows")
print(selling_gt_mrp[[
    "unique_id",
    "product_name",
    "item_mrp",
    "item_selling_price"
]])

# 2. Discount Flag = Yes but MRP == Selling Price
discount_no_difference = df[
    (flag == "yes") &
    (df["item_mrp"] == df["item_selling_price"])
]

print(f"\n2. Discount Flag = Yes but MRP == Selling Price : {len(discount_no_difference)} rows")
print(discount_no_difference[[
    "unique_id",
    "product_name",
    "item_mrp",
    "item_selling_price",
    "discount_flag"
]])

# 3. Discount % > 100
discount_gt_100 = df[df["discount_in_percent"] > 100]

print(f"\n3. Discount % > 100 : {len(discount_gt_100)} rows")
print(discount_gt_100[[
    "unique_id",
    "product_name",
    "item_mrp",
    "item_selling_price",
    "discount_in_percent"
]])

1. Selling Price > MRP : 0 rows
Empty DataFrame
Columns: [unique_id, product_name, item_mrp, item_selling_price]
Index: []

2. Discount Flag = Yes but MRP == Selling Price : 0 rows
Empty DataFrame
Columns: [unique_id, product_name, item_mrp, item_selling_price, discount_flag]
Index: []

3. Discount % > 100 : 0 rows
Empty DataFrame
Columns: [unique_id, product_name, item_mrp, item_selling_price, discount_in_percent]
Index: []

In [43]:
# Discount % < 0
negative_discount = df[df["discount_in_percent"] < 0]

# Negative prices
negative_prices = df[
    (df["item_mrp"] < 0) |
    (df["item_selling_price"] < 0)
]

# MRP present but selling price missing
mrp_only = df[
    df["item_mrp"].notna() &
    df["item_selling_price"].isna()
]

# Selling price present but MRP missing
selling_only = df[
    df["item_selling_price"].notna() &
    df["item_mrp"].isna()
]

In [46]:
import re

# Characters to search for
pattern = r"~|\^|\n|\r|\t"

for col in df.select_dtypes(include="object").columns:
    mask = df[col].astype(str).str.contains(pattern, regex=True, na=False)

    if mask.any():
        print(f"\nColumn: {col}")
        print(f"Rows affected: {mask.sum()}")
        print(df.loc[mask, [col]].head())

Column: product_name
Rows affected: 6
                                                                                                                                                                                             product_name
25345   Fast&Up Reload Ready To Drink ~ Low Sugar Energy Drink Instant Energy & Hydration Drink - Lemon Flavour (500ml) & Fast&Up Reload Berry Instant Energy Drink 5 Essential Electrolytes (20pc) Combo
119298                          Fast&Up Reload Ready To Drink ~ Low Sugar Energy Drink Instant Energy & Hydration Drink - Lemon Flavour (500ml) & Jimmy'S Sex On The Beach - Cocktail Mixer (250ml) Combo
266641  Fast&Up Reload Ready To Drink ~ Low Sugar Energy Drink Instant Energy & Hydration Drink - Lemon Flavour (500ml) & Fast&Up Reload Berry Instant Energy Drink 5 Essential Electrolytes (20pc) Combo
282501  Fast&Up Reload Ready To Drink ~ Low Sugar Energy Drink Instant Energy & Hydration Drink - Lemon Flavour (500ml) & Fast&Up Reload Berry Instant Energy Drink 5 Essential Electrolytes (20pc) Combo
435344                          Fast&Up Reload Ready To Drink ~ Low Sugar Energy Drink Instant Energy & Hydration Drink - Lemon Flavour (500ml) & Jimmy'S Sex On The Beach - Cocktail Mixer (250ml) Combo

In [47]:
import re

# ---------- Thresholds ----------
LONG_NAME_THRESHOLD = 150   # Adjust as needed
SHORT_NAME_THRESHOLD = 3    # Adjust as needed

# Clean product name
names = df["product_name"].fillna("").astype(str).str.strip()

# 1. Long product names
long_names = df[names.str.len() > LONG_NAME_THRESHOLD]

print(f"Long product names (> {LONG_NAME_THRESHOLD} chars): {len(long_names)}")
print(long_names[["unique_id", "product_name"]])

# 2. Very short product names
short_names = df[names.str.len() < SHORT_NAME_THRESHOLD]

print(f"\nVery short product names (< {SHORT_NAME_THRESHOLD} chars): {len(short_names)}")
print(short_names[["unique_id", "product_name"]])

# 3. Potentially invalid product names
# Contains only numbers/symbols OR no alphabetic characters
invalid_mask = (
    names.eq("") |
    ~names.str.contains(r"[A-Za-zÀ-ÿ]", regex=True)
)

invalid_names = df[invalid_mask]

print(f"\nPotentially invalid product names: {len(invalid_names)}")
print(invalid_names[["unique_id", "product_name"]])

Long product names (> 150 chars): 820
                                   unique_id  \
309     de52b53e-ef19-4db6-a22c-af6e884210a4
1052    de52b53e-ef19-4db6-a22c-af6e884210a4
1929    4907f3af-c281-4005-aff6-a9aa3b2d76d9
1940    f7b9124f-022b-4896-a7a6-8c546d89a996
2709    de52b53e-ef19-4db6-a22c-af6e884210a4
3527    de52b53e-ef19-4db6-a22c-af6e884210a4
3838    de52b53e-ef19-4db6-a22c-af6e884210a4
4104    f7b9124f-022b-4896-a7a6-8c546d89a996
4157    4907f3af-c281-4005-aff6-a9aa3b2d76d9
4231    de52b53e-ef19-4db6-a22c-af6e884210a4
4363    05099171-d97f-4169-99d8-2f6fc01a0c22
6160    f7b9124f-022b-4896-a7a6-8c546d89a996
6161    4907f3af-c281-4005-aff6-a9aa3b2d76d9
6805    f7b9124f-022b-4896-a7a6-8c546d89a996
6823    4907f3af-c281-4005-aff6-a9aa3b2d76d9
7123    f7b9124f-022b-4896-a7a6-8c546d89a996
7130    4907f3af-c281-4005-aff6-a9aa3b2d76d9
7243    de52b53e-ef19-4db6-a22c-af6e884210a4
8142    f7b9124f-022b-4896-a7a6-8c546d89a996
8143    4907f3af-c281-4005-aff6-a9aa3b2d76d9
9700    91a5bd82-b407-426f-a9f7-39af4a53b38f
10328   de52b53e-ef19-4db6-a22c-af6e884210a4
10492   05099171-d97f-4169-99d8-2f6fc01a0c22
10955   05099171-d97f-4169-99d8-2f6fc01a0c22
11614   edd24376-4a56-4c30-bc25-17740efa5f75
11615   7e1c699f-d191-4be4-9314-3506b1a75b97
11624   95e2be62-4c82-41ce-8b88-81aabe1b60ae
11628   169c14c3-14d5-4a05-b404-4c5c0181dd55
11976   edd24376-4a56-4c30-bc25-17740efa5f75
12393   f7b9124f-022b-4896-a7a6-8c546d89a996
12406   4907f3af-c281-4005-aff6-a9aa3b2d76d9
12630   7a8b5c44-5df6-4c61-9f82-114b659d19df
13115   de52b53e-ef19-4db6-a22c-af6e884210a4
14892   de52b53e-ef19-4db6-a22c-af6e884210a4
15172   f7b9124f-022b-4896-a7a6-8c546d89a996
15173   4907f3af-c281-4005-aff6-a9aa3b2d76d9
16174   05099171-d97f-4169-99d8-2f6fc01a0c22
18150   de52b53e-ef19-4db6-a22c-af6e884210a4
19282   f7b9124f-022b-4896-a7a6-8c546d89a996
19289   4907f3af-c281-4005-aff6-a9aa3b2d76d9
20995   f7b9124f-022b-4896-a7a6-8c546d89a996
20996   4907f3af-c281-4005-aff6-a9aa3b2d76d9
21132   de52b53e-ef19-4db6-a22c-af6e884210a4
24084   f7b9124f-022b-4896-a7a6-8c546d89a996
24087   4907f3af-c281-4005-aff6-a9aa3b2d76d9
25314   05099171-d97f-4169-99d8-2f6fc01a0c22
25345   e4a906ca-8ce7-4af1-9c93-2ff0d130b5fe
25386   de52b53e-ef19-4db6-a22c-af6e884210a4
28080   de52b53e-ef19-4db6-a22c-af6e884210a4
28158   f7b9124f-022b-4896-a7a6-8c546d89a996
29094   05099171-d97f-4169-99d8-2f6fc01a0c22
29994   05099171-d97f-4169-99d8-2f6fc01a0c22
31250   de52b53e-ef19-4db6-a22c-af6e884210a4
33095   f7b9124f-022b-4896-a7a6-8c546d89a996
33096   4907f3af-c281-4005-aff6-a9aa3b2d76d9
34218   f7b9124f-022b-4896-a7a6-8c546d89a996
34235   4907f3af-c281-4005-aff6-a9aa3b2d76d9
36105   de52b53e-ef19-4db6-a22c-af6e884210a4
37681   05099171-d97f-4169-99d8-2f6fc01a0c22
38035   05099171-d97f-4169-99d8-2f6fc01a0c22
38493   f7b9124f-022b-4896-a7a6-8c546d89a996
38498   4907f3af-c281-4005-aff6-a9aa3b2d76d9
42574   de52b53e-ef19-4db6-a22c-af6e884210a4
43797   f7b9124f-022b-4896-a7a6-8c546d89a996
43799   4907f3af-c281-4005-aff6-a9aa3b2d76d9
44710   edd24376-4a56-4c30-bc25-17740efa5f75
47340   4b45a46c-7559-4707-bc8a-a013171cfed1
50139   f7b9124f-022b-4896-a7a6-8c546d89a996
50152   4907f3af-c281-4005-aff6-a9aa3b2d76d9
50626   4b45a46c-7559-4707-bc8a-a013171cfed1
50663   05099171-d97f-4169-99d8-2f6fc01a0c22
52595   05099171-d97f-4169-99d8-2f6fc01a0c22
53012   05099171-d97f-4169-99d8-2f6fc01a0c22
55428   05099171-d97f-4169-99d8-2f6fc01a0c22
57537   cf171023-7a08-4fe0-9dcf-a2c037ba861e
57544   87f116b2-3b3e-4b23-a98d-30a0021aeaae
58494   4b45a46c-7559-4707-bc8a-a013171cfed1
58544   2bdf7ef7-4796-4969-ba37-5fca1e01b31c
58550   58caf284-73d7-4a9e-ab54-eb51f6b197f5
58618   58caf284-73d7-4a9e-ab54-eb51f6b197f5
58620   2bdf7ef7-4796-4969-ba37-5fca1e01b31c
58671   87f116b2-3b3e-4b23-a98d-30a0021aeaae
58673   cf171023-7a08-4fe0-9dcf-a2c037ba861e
59195   58caf284-73d7-4a9e-ab54-eb51f6b197f5
59197   2bdf7ef7-4796-4969-ba37-5fca1e01b31c
60027   05099171-d97f-4169-99d8-2f6fc01a0c22
61633   cf171023-7a08-4fe0-9dcf-a2c037ba861e
61634   87f116b2-3b3e-4b23-a98d-30a0021aeaae
62599   4b45a46c-7559-4707-bc8a-a013171cfed1
63717   cf171023-7a08-4fe0-9dcf-a2c037ba861e
63718   87f116b2-3b3e-4b23-a98d-30a0021aeaae
63719   58caf284-73d7-4a9e-ab54-eb51f6b197f5
63720   2bdf7ef7-4796-4969-ba37-5fca1e01b31c
64705   87f116b2-3b3e-4b23-a98d-30a0021aeaae
64706   cf171023-7a08-4fe0-9dcf-a2c037ba861e
64930   05099171-d97f-4169-99d8-2f6fc01a0c22
67982   de52b53e-ef19-4db6-a22c-af6e884210a4
68608   05099171-d97f-4169-99d8-2f6fc01a0c22
69463   87f116b2-3b3e-4b23-a98d-30a0021aeaae
69466   cf171023-7a08-4fe0-9dcf-a2c037ba861e
71584   cf171023-7a08-4fe0-9dcf-a2c037ba861e
71977   cf171023-7a08-4fe0-9dcf-a2c037ba861e
74195   05099171-d97f-4169-99d8-2f6fc01a0c22
75109   05099171-d97f-4169-99d8-2f6fc01a0c22
75667   05099171-d97f-4169-99d8-2f6fc01a0c22
76055   de52b53e-ef19-4db6-a22c-af6e884210a4
76662   de52b53e-ef19-4db6-a22c-af6e884210a4
76722   de52b53e-ef19-4db6-a22c-af6e884210a4
76919   4b45a46c-7559-4707-bc8a-a013171cfed1
77193   de52b53e-ef19-4db6-a22c-af6e884210a4
78380   cf171023-7a08-4fe0-9dcf-a2c037ba861e
78381   87f116b2-3b3e-4b23-a98d-30a0021aeaae
78382   58caf284-73d7-4a9e-ab54-eb51f6b197f5
78383   2bdf7ef7-4796-4969-ba37-5fca1e01b31c
78557   05099171-d97f-4169-99d8-2f6fc01a0c22
79699   f7b9124f-022b-4896-a7a6-8c546d89a996
80065   de52b53e-ef19-4db6-a22c-af6e884210a4
80101   58caf284-73d7-4a9e-ab54-eb51f6b197f5
80105   2bdf7ef7-4796-4969-ba37-5fca1e01b31c
80174   f7b9124f-022b-4896-a7a6-8c546d89a996
80197   4907f3af-c281-4005-aff6-a9aa3b2d76d9
81588   f7b9124f-022b-4896-a7a6-8c546d89a996
81589   4907f3af-c281-4005-aff6-a9aa3b2d76d9
83064   05099171-d97f-4169-99d8-2f6fc01a0c22
83147   de52b53e-ef19-4db6-a22c-af6e884210a4
83483   91a5bd82-b407-426f-a9f7-39af4a53b38f
83793   de52b53e-ef19-4db6-a22c-af6e884210a4
84210   05099171-d97f-4169-99d8-2f6fc01a0c22
84239   87f116b2-3b3e-4b23-a98d-30a0021aeaae
84240   cf171023-7a08-4fe0-9dcf-a2c037ba861e
84328   edd24376-4a56-4c30-bc25-17740efa5f75
84331   7e1c699f-d191-4be4-9314-3506b1a75b97
84689   05099171-d97f-4169-99d8-2f6fc01a0c22
85370   7e1c699f-d191-4be4-9314-3506b1a75b97
85371   edd24376-4a56-4c30-bc25-17740efa5f75
85383   95e2be62-4c82-41ce-8b88-81aabe1b60ae
85386   169c14c3-14d5-4a05-b404-4c5c0181dd55
85835   f7b9124f-022b-4896-a7a6-8c546d89a996
85840   4907f3af-c281-4005-aff6-a9aa3b2d76d9
86261   05099171-d97f-4169-99d8-2f6fc01a0c22
87123   eadf4b1b-f1b1-4b54-b7d1-ffb1fd085ae6
89201   4907f3af-c281-4005-aff6-a9aa3b2d76d9
89202   f7b9124f-022b-4896-a7a6-8c546d89a996
89340   05099171-d97f-4169-99d8-2f6fc01a0c22
90016   f7b9124f-022b-4896-a7a6-8c546d89a996
90017   4907f3af-c281-4005-aff6-a9aa3b2d76d9
90590   edd24376-4a56-4c30-bc25-17740efa5f75
93971   05099171-d97f-4169-99d8-2f6fc01a0c22
95725   de52b53e-ef19-4db6-a22c-af6e884210a4
96338   cf171023-7a08-4fe0-9dcf-a2c037ba861e
96340   87f116b2-3b3e-4b23-a98d-30a0021aeaae
96341   58caf284-73d7-4a9e-ab54-eb51f6b197f5
96342   2bdf7ef7-4796-4969-ba37-5fca1e01b31c
96734   de52b53e-ef19-4db6-a22c-af6e884210a4
98122   f7b9124f-022b-4896-a7a6-8c546d89a996
98141   4907f3af-c281-4005-aff6-a9aa3b2d76d9
101889  de52b53e-ef19-4db6-a22c-af6e884210a4
102301  4907f3af-c281-4005-aff6-a9aa3b2d76d9
102317  f7b9124f-022b-4896-a7a6-8c546d89a996
103045  05099171-d97f-4169-99d8-2f6fc01a0c22
103456  f7b9124f-022b-4896-a7a6-8c546d89a996
103461  4907f3af-c281-4005-aff6-a9aa3b2d76d9
104608  f7b9124f-022b-4896-a7a6-8c546d89a996
104612  4907f3af-c281-4005-aff6-a9aa3b2d76d9
104909  4907f3af-c281-4005-aff6-a9aa3b2d76d9
104910  f7b9124f-022b-4896-a7a6-8c546d89a996
106839  de52b53e-ef19-4db6-a22c-af6e884210a4
108639  91a5bd82-b407-426f-a9f7-39af4a53b38f
109470  05099171-d97f-4169-99d8-2f6fc01a0c22
109838  edd24376-4a56-4c30-bc25-17740efa5f75
111105  edd24376-4a56-4c30-bc25-17740efa5f75
111106  7e1c699f-d191-4be4-9314-3506b1a75b97
111108  95e2be62-4c82-41ce-8b88-81aabe1b60ae
111124  169c14c3-14d5-4a05-b404-4c5c0181dd55
112763  05099171-d97f-4169-99d8-2f6fc01a0c22
112962  4907f3af-c281-4005-aff6-a9aa3b2d76d9
112964  f7b9124f-022b-4896-a7a6-8c546d89a996
114131  f7b9124f-022b-4896-a7a6-8c546d89a996
114132  4907f3af-c281-4005-aff6-a9aa3b2d76d9
114447  de52b53e-ef19-4db6-a22c-af6e884210a4
117263  91a5bd82-b407-426f-a9f7-39af4a53b38f
117946  05099171-d97f-4169-99d8-2f6fc01a0c22
118377  05099171-d97f-4169-99d8-2f6fc01a0c22
119298  faa49fa5-6ff0-4321-9f66-ac40569e44e2
119326  edd24376-4a56-4c30-bc25-17740efa5f75
119327  95e2be62-4c82-41ce-8b88-81aabe1b60ae
119329  7e1c699f-d191-4be4-9314-3506b1a75b97
119330  169c14c3-14d5-4a05-b404-4c5c0181dd55
121057  f7b9124f-022b-4896-a7a6-8c546d89a996
121062  4907f3af-c281-4005-aff6-a9aa3b2d76d9
125795  05099171-d97f-4169-99d8-2f6fc01a0c22
126571  05099171-d97f-4169-99d8-2f6fc01a0c22
128916  de52b53e-ef19-4db6-a22c-af6e884210a4
130617  05099171-d97f-4169-99d8-2f6fc01a0c22
131167  58caf284-73d7-4a9e-ab54-eb51f6b197f5
131175  2bdf7ef7-4796-4969-ba37-5fca1e01b31c
131404  cf171023-7a08-4fe0-9dcf-a2c037ba861e
131405  87f116b2-3b3e-4b23-a98d-30a0021aeaae
134305  f7b9124f-022b-4896-a7a6-8c546d89a996
134701  cf171023-7a08-4fe0-9dcf-a2c037ba861e
135534  4b45a46c-7559-4707-bc8a-a013171cfed1
135651  2bdf7ef7-4796-4969-ba37-5fca1e01b31c
135652  58caf284-73d7-4a9e-ab54-eb51f6b197f5
137352  05099171-d97f-4169-99d8-2f6fc01a0c22
138000  05099171-d97f-4169-99d8-2f6fc01a0c22
138211  edd24376-4a56-4c30-bc25-17740efa5f75
138214  7e1c699f-d191-4be4-9314-3506b1a75b97
139440  4b45a46c-7559-4707-bc8a-a013171cfed1
139981  eadf4b1b-f1b1-4b54-b7d1-ffb1fd085ae6
141138  de52b53e-ef19-4db6-a22c-af6e884210a4
142615  cf171023-7a08-4fe0-9dcf-a2c037ba861e
142930  cf171023-7a08-4fe0-9dcf-a2c037ba861e
142931  87f116b2-3b3e-4b23-a98d-30a0021aeaae
143716  4b45a46c-7559-4707-bc8a-a013171cfed1
144786  05099171-d97f-4169-99d8-2f6fc01a0c22
146466  05099171-d97f-4169-99d8-2f6fc01a0c22
147104  05099171-d97f-4169-99d8-2f6fc01a0c22
147784  678a3f11-8e00-498d-8454-ae313c7d8842
147785  894a2134-728f-4c68-b572-f98908903ffd
147786  58caf284-73d7-4a9e-ab54-eb51f6b197f5
147788  2bdf7ef7-4796-4969-ba37-5fca1e01b31c
147854  05099171-d97f-4169-99d8-2f6fc01a0c22
148243  de52b53e-ef19-4db6-a22c-af6e884210a4
148583  cf171023-7a08-4fe0-9dcf-a2c037ba861e
149667  de52b53e-ef19-4db6-a22c-af6e884210a4
149826  cf171023-7a08-4fe0-9dcf-a2c037ba861e
149848  de52b53e-ef19-4db6-a22c-af6e884210a4
150636  de52b53e-ef19-4db6-a22c-af6e884210a4
151662  58caf284-73d7-4a9e-ab54-eb51f6b197f5
151663  2bdf7ef7-4796-4969-ba37-5fca1e01b31c
152436  58caf284-73d7-4a9e-ab54-eb51f6b197f5
152437  2bdf7ef7-4796-4969-ba37-5fca1e01b31c
152538  de52b53e-ef19-4db6-a22c-af6e884210a4
153184  f7b9124f-022b-4896-a7a6-8c546d89a996
153187  4907f3af-c281-4005-aff6-a9aa3b2d76d9
154032  f7b9124f-022b-4896-a7a6-8c546d89a996
154035  4907f3af-c281-4005-aff6-a9aa3b2d76d9
154179  f7b9124f-022b-4896-a7a6-8c546d89a996
154195  4907f3af-c281-4005-aff6-a9aa3b2d76d9
156102  f7b9124f-022b-4896-a7a6-8c546d89a996
156111  4907f3af-c281-4005-aff6-a9aa3b2d76d9
157392  4907f3af-c281-4005-aff6-a9aa3b2d76d9
157395  f7b9124f-022b-4896-a7a6-8c546d89a996
158259  cf171023-7a08-4fe0-9dcf-a2c037ba861e
158292  2bdf7ef7-4796-4969-ba37-5fca1e01b31c
158295  58caf284-73d7-4a9e-ab54-eb51f6b197f5
158458  05099171-d97f-4169-99d8-2f6fc01a0c22
158690  4907f3af-c281-4005-aff6-a9aa3b2d76d9
158692  f7b9124f-022b-4896-a7a6-8c546d89a996
160277  edd24376-4a56-4c30-bc25-17740efa5f75
161731  91a5bd82-b407-426f-a9f7-39af4a53b38f
162298  05099171-d97f-4169-99d8-2f6fc01a0c22
163309  edd24376-4a56-4c30-bc25-17740efa5f75
163311  95e2be62-4c82-41ce-8b88-81aabe1b60ae
163313  7e1c699f-d191-4be4-9314-3506b1a75b97
163317  169c14c3-14d5-4a05-b404-4c5c0181dd55
163613  de52b53e-ef19-4db6-a22c-af6e884210a4
165669  de52b53e-ef19-4db6-a22c-af6e884210a4
171375  de52b53e-ef19-4db6-a22c-af6e884210a4
171426  de52b53e-ef19-4db6-a22c-af6e884210a4
175831  05099171-d97f-4169-99d8-2f6fc01a0c22
175851  de52b53e-ef19-4db6-a22c-af6e884210a4
176727  de52b53e-ef19-4db6-a22c-af6e884210a4
177076  f7b9124f-022b-4896-a7a6-8c546d89a996
177088  4907f3af-c281-4005-aff6-a9aa3b2d76d9
177654  f7b9124f-022b-4896-a7a6-8c546d89a996
177657  4907f3af-c281-4005-aff6-a9aa3b2d76d9
177909  7a8b5c44-5df6-4c61-9f82-114b659d19df
178159  de52b53e-ef19-4db6-a22c-af6e884210a4
181544  05099171-d97f-4169-99d8-2f6fc01a0c22
181737  f7b9124f-022b-4896-a7a6-8c546d89a996
181740  4907f3af-c281-4005-aff6-a9aa3b2d76d9
182414  05099171-d97f-4169-99d8-2f6fc01a0c22
182640  edd24376-4a56-4c30-bc25-17740efa5f75
182790  4907f3af-c281-4005-aff6-a9aa3b2d76d9
183266  f7b9124f-022b-4896-a7a6-8c546d89a996
183738  169c14c3-14d5-4a05-b404-4c5c0181dd55
183921  4907f3af-c281-4005-aff6-a9aa3b2d76d9
183925  f7b9124f-022b-4896-a7a6-8c546d89a996
184331  de52b53e-ef19-4db6-a22c-af6e884210a4
185764  de52b53e-ef19-4db6-a22c-af6e884210a4
186309  de52b53e-ef19-4db6-a22c-af6e884210a4
186663  91a5bd82-b407-426f-a9f7-39af4a53b38f
187371  05099171-d97f-4169-99d8-2f6fc01a0c22
187910  05099171-d97f-4169-99d8-2f6fc01a0c22
188955  169c14c3-14d5-4a05-b404-4c5c0181dd55
188963  95e2be62-4c82-41ce-8b88-81aabe1b60ae
188964  edd24376-4a56-4c30-bc25-17740efa5f75
188965  7e1c699f-d191-4be4-9314-3506b1a75b97
190117  7a8b5c44-5df6-4c61-9f82-114b659d19df
191430  4907f3af-c281-4005-aff6-a9aa3b2d76d9
191431  f7b9124f-022b-4896-a7a6-8c546d89a996
191645  7a8b5c44-5df6-4c61-9f82-114b659d19df
193894  f7b9124f-022b-4896-a7a6-8c546d89a996
193897  4907f3af-c281-4005-aff6-a9aa3b2d76d9
196046  05099171-d97f-4169-99d8-2f6fc01a0c22
196787  05099171-d97f-4169-99d8-2f6fc01a0c22
198221  05099171-d97f-4169-99d8-2f6fc01a0c22
198813  05099171-d97f-4169-99d8-2f6fc01a0c22
201589  05099171-d97f-4169-99d8-2f6fc01a0c22
202025  05099171-d97f-4169-99d8-2f6fc01a0c22
203164  cf171023-7a08-4fe0-9dcf-a2c037ba861e
203166  87f116b2-3b3e-4b23-a98d-30a0021aeaae
204052  cf171023-7a08-4fe0-9dcf-a2c037ba861e
204749  87f116b2-3b3e-4b23-a98d-30a0021aeaae
204750  cf171023-7a08-4fe0-9dcf-a2c037ba861e
206754  58caf284-73d7-4a9e-ab54-eb51f6b197f5
206755  2bdf7ef7-4796-4969-ba37-5fca1e01b31c
207365  cf171023-7a08-4fe0-9dcf-a2c037ba861e
207808  58caf284-73d7-4a9e-ab54-eb51f6b197f5
207809  2bdf7ef7-4796-4969-ba37-5fca1e01b31c
211318  05099171-d97f-4169-99d8-2f6fc01a0c22
213966  4907f3af-c281-4005-aff6-a9aa3b2d76d9
213967  f7b9124f-022b-4896-a7a6-8c546d89a996
214996  cf171023-7a08-4fe0-9dcf-a2c037ba861e
214997  87f116b2-3b3e-4b23-a98d-30a0021aeaae
214998  58caf284-73d7-4a9e-ab54-eb51f6b197f5
217913  05099171-d97f-4169-99d8-2f6fc01a0c22
219060  05099171-d97f-4169-99d8-2f6fc01a0c22
219470  91a5bd82-b407-426f-a9f7-39af4a53b38f
219915  05099171-d97f-4169-99d8-2f6fc01a0c22
220148  05099171-d97f-4169-99d8-2f6fc01a0c22
220494  05099171-d97f-4169-99d8-2f6fc01a0c22
220712  edd24376-4a56-4c30-bc25-17740efa5f75
220714  95e2be62-4c82-41ce-8b88-81aabe1b60ae
220715  7e1c699f-d191-4be4-9314-3506b1a75b97
220875  58caf284-73d7-4a9e-ab54-eb51f6b197f5
220877  2bdf7ef7-4796-4969-ba37-5fca1e01b31c
222412  58caf284-73d7-4a9e-ab54-eb51f6b197f5
222414  2bdf7ef7-4796-4969-ba37-5fca1e01b31c
224533  05099171-d97f-4169-99d8-2f6fc01a0c22
224765  58caf284-73d7-4a9e-ab54-eb51f6b197f5
224766  2bdf7ef7-4796-4969-ba37-5fca1e01b31c
224776  cf171023-7a08-4fe0-9dcf-a2c037ba861e
224786  87f116b2-3b3e-4b23-a98d-30a0021aeaae
225389  05099171-d97f-4169-99d8-2f6fc01a0c22
225833  de52b53e-ef19-4db6-a22c-af6e884210a4
226209  de52b53e-ef19-4db6-a22c-af6e884210a4
226725  de52b53e-ef19-4db6-a22c-af6e884210a4
227414  de52b53e-ef19-4db6-a22c-af6e884210a4
227868  2bdf7ef7-4796-4969-ba37-5fca1e01b31c
227869  58caf284-73d7-4a9e-ab54-eb51f6b197f5
227873  cf171023-7a08-4fe0-9dcf-a2c037ba861e
227875  87f116b2-3b3e-4b23-a98d-30a0021aeaae
228792  de52b53e-ef19-4db6-a22c-af6e884210a4
228988  4907f3af-c281-4005-aff6-a9aa3b2d76d9
228989  f7b9124f-022b-4896-a7a6-8c546d89a996
229494  2bdf7ef7-4796-4969-ba37-5fca1e01b31c
229518  58caf284-73d7-4a9e-ab54-eb51f6b197f5
230685  f7b9124f-022b-4896-a7a6-8c546d89a996
230686  4907f3af-c281-4005-aff6-a9aa3b2d76d9
230744  f7b9124f-022b-4896-a7a6-8c546d89a996
231231  f7b9124f-022b-4896-a7a6-8c546d89a996
231233  4907f3af-c281-4005-aff6-a9aa3b2d76d9
231509  91a5bd82-b407-426f-a9f7-39af4a53b38f
231930  05099171-d97f-4169-99d8-2f6fc01a0c22
232060  05099171-d97f-4169-99d8-2f6fc01a0c22
232713  f7b9124f-022b-4896-a7a6-8c546d89a996
232715  4907f3af-c281-4005-aff6-a9aa3b2d76d9
232967  edd24376-4a56-4c30-bc25-17740efa5f75
232970  7e1c699f-d191-4be4-9314-3506b1a75b97
232975  169c14c3-14d5-4a05-b404-4c5c0181dd55
232983  95e2be62-4c82-41ce-8b88-81aabe1b60ae
233909  f7b9124f-022b-4896-a7a6-8c546d89a996
233910  05099171-d97f-4169-99d8-2f6fc01a0c22
233911  4907f3af-c281-4005-aff6-a9aa3b2d76d9
233946  05099171-d97f-4169-99d8-2f6fc01a0c22
234182  2bdf7ef7-4796-4969-ba37-5fca1e01b31c
234184  58caf284-73d7-4a9e-ab54-eb51f6b197f5
235618  7a8b5c44-5df6-4c61-9f82-114b659d19df
237454  cf171023-7a08-4fe0-9dcf-a2c037ba861e
237455  87f116b2-3b3e-4b23-a98d-30a0021aeaae
237456  2bdf7ef7-4796-4969-ba37-5fca1e01b31c
237458  58caf284-73d7-4a9e-ab54-eb51f6b197f5
237740  edd24376-4a56-4c30-bc25-17740efa5f75
238142  cf171023-7a08-4fe0-9dcf-a2c037ba861e
241143  f7b9124f-022b-4896-a7a6-8c546d89a996
241145  4907f3af-c281-4005-aff6-a9aa3b2d76d9
242586  de52b53e-ef19-4db6-a22c-af6e884210a4
244450  91a5bd82-b407-426f-a9f7-39af4a53b38f
245033  05099171-d97f-4169-99d8-2f6fc01a0c22
246266  edd24376-4a56-4c30-bc25-17740efa5f75
246269  95e2be62-4c82-41ce-8b88-81aabe1b60ae
246271  7e1c699f-d191-4be4-9314-3506b1a75b97
247077  de52b53e-ef19-4db6-a22c-af6e884210a4
248021  f7b9124f-022b-4896-a7a6-8c546d89a996
248022  4907f3af-c281-4005-aff6-a9aa3b2d76d9
248043  de52b53e-ef19-4db6-a22c-af6e884210a4
248439  de52b53e-ef19-4db6-a22c-af6e884210a4
250303  4b45a46c-7559-4707-bc8a-a013171cfed1
251660  f7b9124f-022b-4896-a7a6-8c546d89a996
251661  4907f3af-c281-4005-aff6-a9aa3b2d76d9
253676  f7b9124f-022b-4896-a7a6-8c546d89a996
253967  f7b9124f-022b-4896-a7a6-8c546d89a996
253968  4907f3af-c281-4005-aff6-a9aa3b2d76d9
254021  de52b53e-ef19-4db6-a22c-af6e884210a4
254081  de52b53e-ef19-4db6-a22c-af6e884210a4
254255  05099171-d97f-4169-99d8-2f6fc01a0c22
254463  de52b53e-ef19-4db6-a22c-af6e884210a4
255824  de52b53e-ef19-4db6-a22c-af6e884210a4
257191  05099171-d97f-4169-99d8-2f6fc01a0c22
257592  58caf284-73d7-4a9e-ab54-eb51f6b197f5
257593  2bdf7ef7-4796-4969-ba37-5fca1e01b31c
257914  05099171-d97f-4169-99d8-2f6fc01a0c22
259040  58caf284-73d7-4a9e-ab54-eb51f6b197f5
259043  2bdf7ef7-4796-4969-ba37-5fca1e01b31c
259046  894a2134-728f-4c68-b572-f98908903ffd
259049  678a3f11-8e00-498d-8454-ae313c7d8842
260076  4907f3af-c281-4005-aff6-a9aa3b2d76d9
260081  f7b9124f-022b-4896-a7a6-8c546d89a996
260087  f7b9124f-022b-4896-a7a6-8c546d89a996
260089  4907f3af-c281-4005-aff6-a9aa3b2d76d9
260834  de52b53e-ef19-4db6-a22c-af6e884210a4
262924  de52b53e-ef19-4db6-a22c-af6e884210a4
263959  de52b53e-ef19-4db6-a22c-af6e884210a4
265193  05099171-d97f-4169-99d8-2f6fc01a0c22
265222  05099171-d97f-4169-99d8-2f6fc01a0c22
266068  05099171-d97f-4169-99d8-2f6fc01a0c22
266641  e4a906ca-8ce7-4af1-9c93-2ff0d130b5fe
268249  4907f3af-c281-4005-aff6-a9aa3b2d76d9
268252  f7b9124f-022b-4896-a7a6-8c546d89a996
268479  7a8b5c44-5df6-4c61-9f82-114b659d19df
269608  f7b9124f-022b-4896-a7a6-8c546d89a996
269626  4907f3af-c281-4005-aff6-a9aa3b2d76d9
269738  4b45a46c-7559-4707-bc8a-a013171cfed1
270075  eadf4b1b-f1b1-4b54-b7d1-ffb1fd085ae6
270533  f7b9124f-022b-4896-a7a6-8c546d89a996
270534  4907f3af-c281-4005-aff6-a9aa3b2d76d9
272475  05099171-d97f-4169-99d8-2f6fc01a0c22
273000  05099171-d97f-4169-99d8-2f6fc01a0c22
274849  05099171-d97f-4169-99d8-2f6fc01a0c22
276010  58caf284-73d7-4a9e-ab54-eb51f6b197f5
276013  2bdf7ef7-4796-4969-ba37-5fca1e01b31c
276620  05099171-d97f-4169-99d8-2f6fc01a0c22
278032  58caf284-73d7-4a9e-ab54-eb51f6b197f5
278854  87f116b2-3b3e-4b23-a98d-30a0021aeaae
278855  cf171023-7a08-4fe0-9dcf-a2c037ba861e
278994  cf171023-7a08-4fe0-9dcf-a2c037ba861e
282501  e4a906ca-8ce7-4af1-9c93-2ff0d130b5fe
282972  05099171-d97f-4169-99d8-2f6fc01a0c22
283062  58caf284-73d7-4a9e-ab54-eb51f6b197f5
283913  de52b53e-ef19-4db6-a22c-af6e884210a4

In [51]:
df[df.product_name == "Deconstruct Brightening Lip Balm Spf 50 | Vitamin C & Resorcinol | Moisturizes & Brightens (4g) & Deconstruct Gel Sunscreen Spf 55+ Pa+++ | In Vivo Tested | Matte, Lightweight & Airy, Non-Greasy (50g) & Deconstruct Oil-Free Moisturizer | Lightweight, Non-Sticky, Non-Comedogenic | For Oily Skin (50g) & Deconstruct 10% Vitamin C Serum For Oily Skin | Clinically Tested | 30 Ml (30ml) Combo"]

,crawl_date_and_time,platform_name,store_id,store_name_location,city,pin_code,unique_id,product_id_upc_ean,department,category,sub_category,product_type,brand_name,product_name,product_description,product_grammage,package_type,net_quantity,variants,item_mrp,item_selling_price,out_of_stock_flag,discount_flag,product_price,unit_price,promo_offer_description,promo_offer_price,discount_in_percent,stock_count,product_url,product_image_urls,brand_norm
11615,2026-07-16 00:09:52,zepto,5feee4ae-dfd9-4484-b060-722c7802c642,"Hotel White House - Stay Elite, 95, White House, Sector 20, Kharghar, Navi Mumbai, Maharashtra, 410210, India",Mumbai,410210,7e1c699f-d191-4be4-9314-3506b1a75b97,8cd65533-d2a8-4def-9c11-bf16588899e0,Beauty & Cosmetics,Skincare,Eye & Lip Care,NaN,Deconstruct,"Deconstruct Brightening Lip Balm Spf 50 | Vitamin C & Resorcinol | Moisturizes & Brightens (4g) & Deconstruct Gel Sunscreen Spf 55+ Pa+++ | In Vivo Tested | Matte, Lightweight & Airy, Non-Greasy (50g) & Deconstruct Oil-Free Moisturizer | Lightweight, Non-Sticky, Non-Comedogenic | For Oily Skin (50g) & Deconstruct 10% Vitamin C Serum For Oily Skin | Clinically Tested | 30 Ml (30ml) Combo",NaN,NaN,NaN,4 combo,NaN,548.0,525.0,No,Yes,525.0,NaN,₹23 OFF,525.0,4,2,https://www.zepto.com/pn/deconstruct-brightening-lip-balm-spf-50-vitamin-c-resorcinol-moisturizes-brightens-4g-deconstruct-gel-sunscreen-spf-55-pa-in-vivo-tested-matte-lightweight-airy-non-greasy-50g-deconstruct-oil-free-moisturizer-lightweight-non-sticky-non-comedogenic-for-oily-skin-50g-deconstruct-10-vitamin-c-serum-for-oily-skin-clinically-tested-30-ml-30ml-combo/pvid/7e1c699f-d191-4be4-9314-3506b1a75b97,NaN,deconstruct
11624,2026-07-16 00:09:52,zepto,5feee4ae-dfd9-4484-b060-722c7802c642,"Hotel White House - Stay Elite, 95, White House, Sector 20, Kharghar, Navi Mumbai, Maharashtra, 410210, India",Mumbai,410210,95e2be62-4c82-41ce-8b88-81aabe1b60ae,8cd65533-d2a8-4def-9c11-bf16588899e0,Beauty & Cosmetics,Skincare,Eye & Lip Care,NaN,Deconstruct,"Deconstruct Brightening Lip Balm Spf 50 | Vitamin C & Resorcinol | Moisturizes & Brightens (4g) & Deconstruct Gel Sunscreen Spf 55+ Pa+++ | In Vivo Tested | Matte, Lightweight & Airy, Non-Greasy (50g) & Deconstruct Oil-Free Moisturizer | Lightweight, Non-Sticky, Non-Comedogenic | For Oily Skin (50g) & Deconstruct 10% Vitamin C Serum For Oily Skin | Clinically Tested | 30 Ml (30ml) Combo",NaN,NaN,NaN,4 combo,NaN,1696.0,1496.0,Yes,Yes,1496.0,NaN,₹200 OFF,1496.0,11,0,https://www.zepto.com/pn/deconstruct-brightening-lip-balm-spf-50-vitamin-c-resorcinol-moisturizes-brightens-4g-deconstruct-gel-sunscreen-spf-55-pa-in-vivo-tested-matte-lightweight-airy-non-greasy-50g-deconstruct-oil-free-moisturizer-lightweight-non-sticky-non-comedogenic-for-oily-skin-50g-deconstruct-10-vitamin-c-serum-for-oily-skin-clinically-tested-30-ml-30ml-combo/pvid/95e2be62-4c82-41ce-8b88-81aabe1b60ae,NaN,deconstruct
84331,2026-07-16 00:50:03,zepto,2b28a8f0-7027-4c5b-8a0b-63c748e5e29d,"Impulse Learning Library, Aamir Sir's Impulse Educations, New, Ring Road, Gandhi Layout, Jafar Nagar, New Mankapur, Nagpur, Maharashtra 440013, India",Nagpur,440013,7e1c699f-d191-4be4-9314-3506b1a75b97,8cd65533-d2a8-4def-9c11-bf16588899e0,Beauty & Cosmetics,Skincare,Eye & Lip Care,NaN,Deconstruct,"Deconstruct Brightening Lip Balm Spf 50 | Vitamin C & Resorcinol | Moisturizes & Brightens (4g) & Deconstruct Gel Sunscreen Spf 55+ Pa+++ | In Vivo Tested | Matte, Lightweight & Airy, Non-Greasy (50g) & Deconstruct Oil-Free Moisturizer | Lightweight, Non-Sticky, Non-Comedogenic | For Oily Skin (50g) & Deconstruct 10% Vitamin C Serum For Oily Skin | Clinically Tested | 30 Ml (30ml) Combo",NaN,NaN,NaN,4 combo,NaN,598.0,525.0,No,Yes,525.0,NaN,₹73 OFF,525.0,12,2,https://www.zepto.com/pn/deconstruct-brightening-lip-balm-spf-50-vitamin-c-resorcinol-moisturizes-brightens-4g-deconstruct-gel-sunscreen-spf-55-pa-in-vivo-tested-matte-lightweight-airy-non-greasy-50g-deconstruct-oil-free-moisturizer-lightweight-non-sticky-non-comedogenic-for-oily-skin-50g-deconstruct-10-vitamin-c-serum-for-oily-skin-clinically-tested-30-ml-30ml-combo/pvid/7e1c699f-d191-4be4-9314-3506b1a75b97,NaN,deconstruct
85370,2026-07-16 00:50:41,zepto,74aa405e-238e-4103-abb3-096bd7e6f553,"Vishwakiran Apartments, Subhash Nagar, Bandra East, Mumbai, Maharashtra, 400051, India",Mumbai,400051,7e1c699f-d191-4be4-9314-3506b1a75b97,8cd65533-d2a8-4def-9c11-bf16588899e0,Beauty & Cosmetics,Skincare,Eye & Lip Care,NaN,Deconstruct,"Deconstruct Brightening Lip Balm Spf 50 | Vitamin C & Resorcinol | Moisturizes & Brightens (4g) & Deconstruct Gel Sunscreen Spf 55+ Pa+++ | In Vivo Tested | Matte, Lightweight & Airy, Non-Greasy (50g) & Deconstruct Oil-Free Moisturizer | Lightweight, Non-Sticky, Non-Comedogenic | For Oily Skin (50g) & Deconstruct 10% Vitamin C Serum For Oily Skin | Clinically Tested | 30 Ml (30ml) Combo",NaN,NaN,NaN,4 combo,NaN,548.0,525.0,No,Yes,525.0,NaN,₹23 OFF,525.0,4,1,https://www.zepto.com/pn/deconstruct-brightening-lip-balm-spf-50-vitamin-c-resorcinol-moisturizes-brightens-4g-deconstruct-gel-sunscreen-spf-55-pa-in-vivo-tested-matte-lightweight-airy-non-greasy-50g-deconstruct-oil-free-moisturizer-lightweight-non-sticky-non-comedogenic-for-oily-skin-50g-deconstruct-10-vitamin-c-serum-for-oily-skin-clinically-tested-30-ml-30ml-combo/pvid/7e1c699f-d191-4be4-9314-3506b1a75b97,NaN,deconstruct
85383,2026-07-16 00:50:41,zepto,74aa405e-238e-4103-abb3-096bd7e6f553,"Vishwakiran Apartments, Subhash Nagar, Bandra East, Mumbai, Maharashtra, 400051, India",Mumbai,400051,95e2be62-4c82-41ce-8b88-81aabe1b60ae,8cd65533-d2a8-4def-9c11-bf16588899e0,Beauty & Cosmetics,Skincare,Eye & Lip Care,NaN,Deconstruct,"Deconstruct Brightening Lip Balm Spf 50 | Vitamin C & Resorcinol | Moisturizes & Brightens (4g) & Deconstruct Gel Sunscreen Spf 55+ Pa+++ | In Vivo Tested | Matte, Lightweight & Airy, Non-Greasy (50g) & Deconstruct Oil-Free Moisturizer | Lightweight, Non-Sticky, Non-Comedogenic | For Oily Skin (50g) & Deconstruct 10% Vitamin C Serum For Oily Skin | Clinically Tested | 30 Ml (30ml) Combo",NaN,NaN,NaN,4 combo,NaN,1696.0,1496.0,Yes,Yes,1496.0,NaN,₹200 OFF,1496.0,11,0,https://www.zepto.com/pn/deconstruct-brightening-lip-balm-spf-50-vitamin-c-resorcinol-moisturizes-brightens-4g-deconstruct-gel-sunscreen-spf-55-pa-in-vivo-tested-matte-lightweight-airy-non-greasy-50g-deconstruct-oil-free-moisturizer-lightweight-non-sticky-non-comedogenic-for-oily-skin-50g-deconstruct-10-vitamin-c-serum-for-oily-skin-clinically-tested-30-ml-30ml-combo/pvid/95e2be62-4c82-41ce-8b88-81aabe1b60ae,NaN,deconstruct
111106,2026-07-16 01:04:02,zepto,0b45bb12-e3bd-415b-b298-ee97db10a222,"Club One At Evershine Global City Virar West, 401303, Narangi ByPass Rd, Evershine Globle City, Dongarpada, Rustomjee Global City, Virar West, Virar, Maharashtra 401303, India",Vasai Virar,401303,7e1c699f-d191-4be4-9314-3506b1a75b97,8cd65533-d2a8-4def-9c11-bf16588899e0,Beauty & Cosmetics,Skincare,Eye & Lip Care,NaN,Deconstruct,"Deconstruct Brightening Lip Balm Spf 50 | Vitamin C & Resorcinol | Moisturizes & Brightens (4g) & Deconstruct Gel Sunscreen Spf 55+ Pa+++ | In Vivo Tested | Matte, Lightweight & Airy, Non-Greasy (50g) & Deconstruct Oil-Free Moisturizer | Lightweight, Non-Sticky, Non-Comedogenic | For Oily Skin (50g) & Deconstruct 10% Vitamin C Serum For Oily Skin | Clinically Tested | 30 Ml (30ml) Combo",NaN,NaN,NaN,4 combo,NaN,548.0,502.0,No,Yes,502.0,NaN,₹46 OFF,502.0,8,2,https://www.zepto.com/pn/deconstruct-brightening-lip-balm-spf-50-vitamin-c-resorcinol-moisturizes-brightens-4g-deconstruct-gel-sunscreen-spf-55-pa-in-vivo-tested-matte-lightweight-airy-non-greasy-50g-deconstruct-oil-free-moisturizer-lightweight-non-sticky-non-comedogenic-for-oily-skin-50g-deconstruct-10-vitamin-c-serum-for-oily-skin-clinically-tested-30-ml-30ml-combo/pvid/7e1c699f-d191-4be4-9314-3506b1a75b97,NaN,deconstruct
111108,2026-07-16 01:04:02,zepto,0b45bb12-e3bd-415b-b298-ee97db10a222,"Club One At Evershine Global City Virar West, 401303, Narangi ByPass Rd, Evershine Globle City, Dongarpada, Rustomjee Global City, Virar West, Virar, Maharashtra 401303, India",Vasai Virar,401303,95e2be62-4c82-41ce-8b88-81aabe1b60ae,8cd65533-d2a8-4def-9c11-bf16588899e0,Beauty & Cosmetics,Skincare,Eye & Lip Care,NaN,Deconstruct,"Deconstruct Brightening Lip Balm Spf 50 | Vitamin C & Resorcinol | Moisturizes & Brightens (4g) & Deconstruct Gel Sunscreen Spf 55+ Pa+++ | In Vivo Tested | Matte, Lightweight & Airy, Non-Greasy (50g) & Deconstruct Oil-Free Moisturizer | Lightweight, Non-Sticky, Non-Comedogenic | For Oily Skin (50g) & Deconstruct 10% Vitamin C Serum For Oily Skin | Clinically Tested | 30 Ml (30ml) Combo",NaN,NaN,NaN,4 combo,NaN,1696.0,1473.0,No,Yes,1473.0,NaN,₹223 OFF,1473.0,13,1,https://www.zepto.com/pn/deconstruct-brightening-lip-balm-spf-50-vitamin-c-resorcinol-moisturizes-brightens-4g-deconstruct-gel-sunscreen-spf-55-pa-in-vivo-tested-matte-lightweight-airy-non-greasy-50g-deconstruct-oil-free-moisturizer-lightweight-non-sticky-non-comedogenic-for-oily-skin-50g-deconstruct-10-vitamin-c-serum-for-oily-skin-clinically-tested-30-ml-30ml-combo/pvid/95e2be62-4c82-41ce-8b88-81aabe1b60ae,NaN,deconstruct
119327,2026-07-16 01:08:52,zepto,250d0a67-ee4b-4cdd-ac75-0c5e65c25ee9,"Metal Power Analytical Pvt. Ltd, 87, Marol CoOperative Industrial Estate Rd, Marol, Andheri East, Mumbai, Maharashtra, 400059, India",Mumbai,400059,95e2be62-4c82-41ce-8b88-81aabe1b60ae,8cd65533-d2a8-4def-9c11-bf16588899e0,Beauty & Cosmetics,Skincare,Eye & Lip Care,NaN,Deconstruct,"Deconstruct Brightening Lip Balm Spf 50 | Vitamin C & Resorcinol | Moisturizes & Brightens (4g) & Deconstruct Gel Sunscreen Spf 55+ Pa+++ | In Vivo Tested | Matte, Lightweight & Airy, Non-Greasy (50g) & Deconstruct Oil-Free Moisturizer | Lightweight, Non-Sticky, Non-Comedogenic | For Oily Skin (50g) & Deconstruct 10% Vitamin C Serum For Oily Skin | Clinically Tested | 30 Ml (30ml) Combo",NaN,NaN,NaN,4 combo,NaN,1696.0,1473.0,No,Yes,1473.0,NaN,₹223 OFF,1473.0,13,1,https://www.zepto.com/pn/deconstruct-brightening-lip-balm-spf-50-vitamin-c-resorcinol-moisturizes-brightens-4g-deconstruct-gel-sunscreen-spf-55-pa-in-vivo-tested-matte-lightweight-airy-non-greasy-50g-deconstruct-oil-free-moisturizer-lightweight-non-sticky-non-comedogenic-for-oily-skin-50g-deconstruct-10-vitamin-c-serum-for-oily-skin-clinically-tested-30-ml-30ml-combo/pvid/95e2be62-4c82-41ce-8b88-81aabe1b60ae,NaN,deconstruct
119329,2026-07-16 01:08:52,zepto,250d0a67-ee4b-4cdd-ac75-0c5e65c25ee9,"Metal Power Analytical Pvt. Ltd, 87, Marol CoOperative Industrial Estate Rd, Marol, Andheri East, Mumbai, Maharashtra, 400059, India",Mumbai,400059,7e1c699f-d191-4be4-9314-3506b1a75b97,8cd65533-d2a8-4def-9c11-bf16588899e0,Beauty & Cosmetics,Skincare,Eye & Lip Care,NaN,Deconstruct,"Deconstruct Brightening Lip Balm Spf 50 | Vitamin C & Resorcinol | Moisturizes & Brightens (4g) & Deconstruct Gel Sunscreen Spf 55+ Pa+++ | In Vivo Tested | Matte, Lightweight & Airy, Non-Greasy (50g) & Deconstruct Oil-Free Moisturizer | Lightweight, Non-Sticky, Non-Comedogenic | For Oily Skin (50g) & Deconstruct 10% Vitamin C Serum For Oily Skin | Clinically Tested | 30 Ml (30ml) Combo",NaN,NaN,NaN,4 combo,NaN,548.0,502.0,No,Yes,502.0,NaN,₹46 OFF,502.0,8,2,https://www.zepto.com/pn/deconstruct-brightening-lip-balm-spf-50-vitamin-c-resorcinol-moisturizes-brightens-4g-deconstruct-gel-sunscreen-spf-55-pa-in-vivo-tested-matte-lightweight-airy-non-greasy-50g-deconstruct-oil-free-moisturizer-lightweight-non-sticky-non-comedogenic-for-oily-skin-50g-deconstruct-10-vitamin-c-serum-for-oily-skin-clinically-tested-30-ml-30ml-combo/pvid/7e1c699f-d191-4be4-9314-3506b1a75b97,NaN,deconstruct
138214,2026-07-16 01:18:50,zepto,2a87c5ee-1495-4e8f-a259-f1246ab1f2d2,"TaTa Balak Mandir, Jaripatka Rd, Near Bezonbagh Ground, Bezonbagh, Nagpur, Maharashtra, 440004, India",Nagpur,440004,7e1c699f-d191-4be4-9314-3506b1a75b97,8cd65533-d2a8-4def-9c11-bf16588899e0,Beauty & Cosmetics,Skincare,Eye & Lip Care,NaN,Deconstruct,"Deconstruct Brightening Lip Balm Spf 50 | Vitamin C & Resorcinol | Moisturizes & Brightens (4g) & Deconstruct Gel Sunscreen Spf 55+ Pa+++ | In Vivo Tested | Matte, Lightweight & Airy, Non-Greasy (50g) & Deconstruct Oil-Free Moisturizer | Lightweight, Non-Sticky, Non-Comedogenic | For Oily Skin (50g) & Deconstruct 10% Vitamin C Serum For Oily Skin | Clinically Tested | 30 Ml (30ml) Combo",NaN,NaN,NaN,4 combo,NaN,548.0,502.0,No,Yes,502.0,NaN,₹46 OFF,502.0,8,1,https://www.zepto.com/pn/deconstruct-brightening-lip-balm-spf-50-vitamin-c-resorcinol-moisturizes-brightens-4g-deconstruct-gel-sunscreen-spf-55-pa-in-vivo-tested-matte-lightweight-airy-non-greasy-50g-deconstruct-oil-free-moisturizer-lightweight-non-sticky-non-comedogenic-for-oily-skin-50g-deconstruct-10-vitamin-c-serum-for-oily-skin-clinically-tested-30-ml-30ml-combo/pvid/7e1c699f-d191-4be4-9314-3506b1a75b97,NaN,deconstruct
163311,2026-07-16 01:33:54,zepto,b8f93707-6d8d-4c31-8b58-627f09ba83cf,"Mhada Apartments Gorai, Borivali West, Mumbai, 400092, India",Mumbai,400092,95e2be62-4c82-41ce-8b88-81aabe1b60ae,8cd65533-d2a8-4def-9c11-bf16588899e0,Beauty & Cosmetics,Skincare,Eye & Lip Care,NaN,Deconstruct,"Deconstruct Brightening Lip Balm Spf 50 | Vitamin C & Resorcinol | Moisturizes & Brightens (4g) & Deconstruct Gel Sunscreen Spf 55+ Pa+++ | In Vivo Tested | Matte, Lightweight & Airy, Non-Greasy (50g) & Deconstruct Oil-Free Moisturizer | Lightweight, Non-Sticky, Non-Comedogenic | For Oily Skin (50g) & Deconstruct 10% Vitamin C Serum For Oily Skin | Clinically Tested | 30 Ml (30ml) Combo",NaN,NaN,NaN,4 combo,NaN,1696.0,1473.0,Yes,Yes,1473.0,NaN,₹223 OFF,1473.0,13,0,https://www.zepto.com/pn/deconstruct-brightening-lip-balm-spf-50-vitamin-c-resorcinol-moisturizes-brightens-4g-deconstruct-gel-sunscreen-spf-55-pa-in-vivo-tested-matte-lightweight-airy-non-greasy-50g-deconstruct-oil-free-moisturizer-lightweight-non-sticky-non-comedogenic-for-oily-skin-50g-deconstruct-10-vitamin-c-serum-for-oily-skin-clinically-tested-30-ml-30ml-combo/pvid/95e2be62-4c82-41ce-8b88-81aabe1b60ae,NaN,deconstruct
163313,2026-07-16 01:33:54,zepto,b8f93707-6d8d-4c31-8b58-627f09ba83cf,"Mhada Apartments Gorai, Borivali West, Mumbai, 400092, India",Mumbai,400092,7e1c699f-d191-4be4-9314-3506b1a75b97,8cd65533-d2a8-4def-9c11-bf16588899e0,Beauty & Cosmetics,Skincare,Eye & Lip Care,NaN,Deconstruct,"Deconstruct Brightening Lip Balm Spf 50 | Vitamin C & Resorcinol | Moisturizes & Brightens (4g) & Deconstruct Gel Sunscreen Spf 55+ Pa+++ | In Vivo Tested | Matte, Lightweight & Airy, Non-Greasy (50g) & Deconstruct Oil-Free Moisturizer | Lightweight, Non-Sticky, Non-Comedogenic | For Oily Skin (50g) & Deconstruct 10% Vitamin C Serum For Oily Skin | Clinically Tested | 30 Ml (30ml) Combo",NaN,NaN,NaN,4 combo,NaN,548.0,502.0,Yes,Yes,502.0,NaN,₹46 OFF,502.0,8,0,https://www.zepto.com/pn/deconstruct-brightening-lip-balm-spf-50-vitamin-c-resorcinol-moisturizes-brightens-4g-deconstruct-gel-sunscreen-spf-55-pa-in-vivo-tested-matte-lightweight-airy-non-greasy-50g-deconstruct-oil-free-moisturizer-lightweight-non-sticky-non-comedogenic-for-oily-skin-50g-deconstruct-10-vitamin-c-serum-for-oily-skin-clinically-tested-30-ml-30ml-combo/pvid/7e1c699f-d191-4be4-9314-3506b1a75b97,NaN,deconstruct
188963,2026-07-16 01:48:46,zepto,0ef81b30-ea84-46ec-98b0-6f3894d1ca1d,"Pride Kitchen Hyderabadi Biryani, Shop No. 4, 6&7, Mermaid Tower, 1, Sector 11, CBD Belapur, Navi Mumbai, Maharashtra, 400614, India",Mumbai,400614,95e2be62-4c82-41ce-8b88-81aabe1b60ae,8cd65533-d2a8-4def-9c11-bf16588899e0,Beauty & Cosmetics,Skincare,Eye & Lip Care,NaN,Deconstruct,"Deconstruct Brightening Lip Balm Spf 50 | Vitamin C & Resorcinol | Moisturizes & Brightens (4g) & Deconstruct Gel Sunscreen Spf 55+ Pa+++ | In Vivo Tested | Matte, Lightweight & Airy, Non-Greasy (50g) & Deconstruct Oil-Free Moisturizer | Lightweight, Non-Sticky, Non-Comedogenic | For Oily Skin (50g) & Deconstruct 10% Vitamin C Serum For Oily Skin | Clinically Tested | 30 Ml (30ml) Combo",NaN,NaN,NaN,4 combo,NaN,1696.0,1473.0,Yes,Yes,1473.0,NaN,₹223 OFF,1473.0,13,0,https://www.zepto.com/pn/deconstruct-brightening-lip-balm-spf-50-vitamin-c-resorcinol-moisturizes-brightens-4g-deconstruct-gel-sunscreen-spf-55-pa-in-vivo-tested-matte-lightweight-airy-non-greasy-50g-deconstruct-oil-free-moisturizer-lightweight-non-sticky-non-comedogenic-for-oily-skin-50g-deconstruct-10-vitamin-c-serum-for-oily-skin-clinically-tested-30-ml-30ml-combo/pvid/95e2be62-4c82-41ce-8b88-81aabe1b60ae,NaN,deconstruct
188965,2026-07-16 01:48:46,zepto,0ef81b30-ea84-46ec-98b0-6f3894d1ca1d,"Pride Kitchen Hyderabadi Biryani, Shop No. 4, 6&7, Mermaid Tower, 1, Sector 11, CBD Belapur, Navi Mumbai, Maharashtra, 400614, India",Mumbai,400614,7e1c699f-d191-4be4-9314-3506b1a75b97,8cd65533-d2a8-4def-9c11-bf16588899e0,Beauty & Cosmetics,Skincare,Eye & Lip Care,NaN,Deconstruct,"Deconstruct Brightening Lip Balm Spf 50 | Vitamin C & Resorcinol | Moisturizes & Brightens (4g) & Deconstruct Gel Sunscreen Spf 55+ Pa+++ | In Vivo Tested | Matte, Lightweight & Airy, Non-Greasy (50g) & Deconstruct Oil-Free Moisturizer | Lightweight, Non-Sticky, Non-Comedogenic | For Oily Skin (50g) & Deconstruct 10% Vitamin C Serum For Oily Skin | Clinically Tested | 30 Ml (30ml) Combo",NaN,NaN,NaN,4 combo,NaN,548.0,502.0,Yes,Yes,502.0,NaN,₹46 OFF,502.0,8,0,https://www.zepto.com/pn/deconstruct-brightening-lip-balm-spf-50-vitamin-c-resorcinol-moisturizes-brightens-4g-deconstruct-gel-sunscreen-spf-55-pa-in-vivo-tested-matte-lightweight-airy-non-greasy-50g-deconstruct-oil-free-moisturizer-lightweight-non-sticky-non-comedogenic-for-oily-skin-50g-deconstruct-10-vitamin-c-serum-for-oily-skin-clinically-tested-30-ml-30ml-combo/pvid/7e1c699f-d191-4be4-9314-3506b1a75b97,NaN,deconstruct
220714,2026-07-16 02:04:17,zepto,ae984dc5-d33f-49cd-914c-d95d51f9e0ca,"Satyam Imperial Heights, Sec-11, Jijamata Nagar, Sector 11, Ghansoli, Navi Mumbai, Maharashtra, 400701, India",Mumbai,400701,95e2be62-4c82-41ce-8b88-81aabe1b60ae,8cd65533-d2a8-4def-9c11-bf16588899e0,Beauty & Cosmetics,Skincare,Eye & Lip Care,NaN,Deconstruct,"Deconstruct Brightening Lip Balm Spf 50 | Vitamin C & Resorcinol | Moisturizes & Brightens (4g) & Deconstruct Gel Sunscreen Spf 55+ Pa+++ | In Vivo Tested | Matte, Lightweight & Airy, Non-Greasy (50g) & Deconstruct Oil-Free Moisturizer | Lightweight, Non-Sticky, Non-Comedogenic | For Oily Skin (50g) & Deconstruct 10% Vitamin C Serum For Oily Skin | Clinically Tested | 30 Ml (30ml) Combo",NaN,NaN,NaN,4 combo,NaN,1696.0,1473.0,No,Yes,1473.0,NaN,₹223 OFF,1473.0,13,1,https://www.zepto.com/pn/deconstruct-brightening-lip-balm-spf-50-vitamin-c-resorcinol-moisturizes-brightens-4g-deconstruct-gel-sunscreen-spf-55-pa-in-vivo-tested-matte-lightweight-airy-non-greasy-50g-deconstruct-oil-free-moisturizer-lightweight-non-sticky-non-comedogenic-for-oily-skin-50g-deconstruct-10-vitamin-c-serum-for-oily-skin-clinically-tested-30-ml-30ml-combo/pvid/95e2be62-4c82-41ce-8b88-81aabe1b60ae,NaN,deconstruct

In [50]:
import re

# ---------- Thresholds ----------
LONG_NAME_THRESHOLD = 150   # Adjust as needed
SHORT_NAME_THRESHOLD = 3    # Adjust as needed

# Clean product name
names = df["product_name"].fillna("").astype(str).str.strip()

# 1. Long product names
long_names = df[names.str.len() > LONG_NAME_THRESHOLD]

print(f"Long product names (> {LONG_NAME_THRESHOLD} chars): {len(long_names)}")
print(long_names[["unique_id", "product_name"]])

# 2. Very short product names
short_names = df[names.str.len() < SHORT_NAME_THRESHOLD]

print(f"\nVery short product names (< {SHORT_NAME_THRESHOLD} chars): {len(short_names)}")
print(short_names[["unique_id", "product_name"]])

# 3. Potentially invalid product names
# Contains only numbers/symbols OR no alphabetic characters
invalid_mask = (
    names.eq("") |
    ~names.str.contains(r"[A-Za-zÀ-ÿ]", regex=True)
)

invalid_names = df[invalid_mask]

print(f"\nPotentially invalid product names: {len(invalid_names)}")
print(invalid_names[["unique_id", "product_name"]])

Long product names (> 150 chars): 820
                                   unique_id  \
309     de52b53e-ef19-4db6-a22c-af6e884210a4
1052    de52b53e-ef19-4db6-a22c-af6e884210a4
1929    4907f3af-c281-4005-aff6-a9aa3b2d76d9
1940    f7b9124f-022b-4896-a7a6-8c546d89a996
2709    de52b53e-ef19-4db6-a22c-af6e884210a4
3527    de52b53e-ef19-4db6-a22c-af6e884210a4
3838    de52b53e-ef19-4db6-a22c-af6e884210a4
4104    f7b9124f-022b-4896-a7a6-8c546d89a996
4157    4907f3af-c281-4005-aff6-a9aa3b2d76d9
4231    de52b53e-ef19-4db6-a22c-af6e884210a4
4363    05099171-d97f-4169-99d8-2f6fc01a0c22
6160    f7b9124f-022b-4896-a7a6-8c546d89a996
6161    4907f3af-c281-4005-aff6-a9aa3b2d76d9
6805    f7b9124f-022b-4896-a7a6-8c546d89a996
6823    4907f3af-c281-4005-aff6-a9aa3b2d76d9
7123    f7b9124f-022b-4896-a7a6-8c546d89a996
7130    4907f3af-c281-4005-aff6-a9aa3b2d76d9
7243    de52b53e-ef19-4db6-a22c-af6e884210a4
8142    f7b9124f-022b-4896-a7a6-8c546d89a996
8143    4907f3af-c281-4005-aff6-a9aa3b2d76d9
9700    91a5bd82-b407-426f-a9f7-39af4a53b38f
10328   de52b53e-ef19-4db6-a22c-af6e884210a4
10492   05099171-d97f-4169-99d8-2f6fc01a0c22
10955   05099171-d97f-4169-99d8-2f6fc01a0c22
11614   edd24376-4a56-4c30-bc25-17740efa5f75
11615   7e1c699f-d191-4be4-9314-3506b1a75b97
11624   95e2be62-4c82-41ce-8b88-81aabe1b60ae
11628   169c14c3-14d5-4a05-b404-4c5c0181dd55
11976   edd24376-4a56-4c30-bc25-17740efa5f75
12393   f7b9124f-022b-4896-a7a6-8c546d89a996
12406   4907f3af-c281-4005-aff6-a9aa3b2d76d9
12630   7a8b5c44-5df6-4c61-9f82-114b659d19df
13115   de52b53e-ef19-4db6-a22c-af6e884210a4
14892   de52b53e-ef19-4db6-a22c-af6e884210a4
15172   f7b9124f-022b-4896-a7a6-8c546d89a996
15173   4907f3af-c281-4005-aff6-a9aa3b2d76d9
16174   05099171-d97f-4169-99d8-2f6fc01a0c22
18150   de52b53e-ef19-4db6-a22c-af6e884210a4
19282   f7b9124f-022b-4896-a7a6-8c546d89a996
19289   4907f3af-c281-4005-aff6-a9aa3b2d76d9
20995   f7b9124f-022b-4896-a7a6-8c546d89a996
20996   4907f3af-c281-4005-aff6-a9aa3b2d76d9
21132   de52b53e-ef19-4db6-a22c-af6e884210a4
24084   f7b9124f-022b-4896-a7a6-8c546d89a996
24087   4907f3af-c281-4005-aff6-a9aa3b2d76d9
25314   05099171-d97f-4169-99d8-2f6fc01a0c22
25345   e4a906ca-8ce7-4af1-9c93-2ff0d130b5fe
25386   de52b53e-ef19-4db6-a22c-af6e884210a4
28080   de52b53e-ef19-4db6-a22c-af6e884210a4
28158   f7b9124f-022b-4896-a7a6-8c546d89a996
29094   05099171-d97f-4169-99d8-2f6fc01a0c22
29994   05099171-d97f-4169-99d8-2f6fc01a0c22
31250   de52b53e-ef19-4db6-a22c-af6e884210a4
33095   f7b9124f-022b-4896-a7a6-8c546d89a996
33096   4907f3af-c281-4005-aff6-a9aa3b2d76d9
34218   f7b9124f-022b-4896-a7a6-8c546d89a996
34235   4907f3af-c281-4005-aff6-a9aa3b2d76d9
36105   de52b53e-ef19-4db6-a22c-af6e884210a4
37681   05099171-d97f-4169-99d8-2f6fc01a0c22
38035   05099171-d97f-4169-99d8-2f6fc01a0c22
38493   f7b9124f-022b-4896-a7a6-8c546d89a996
38498   4907f3af-c281-4005-aff6-a9aa3b2d76d9
42574   de52b53e-ef19-4db6-a22c-af6e884210a4
43797   f7b9124f-022b-4896-a7a6-8c546d89a996
43799   4907f3af-c281-4005-aff6-a9aa3b2d76d9
44710   edd24376-4a56-4c30-bc25-17740efa5f75
47340   4b45a46c-7559-4707-bc8a-a013171cfed1
50139   f7b9124f-022b-4896-a7a6-8c546d89a996
50152   4907f3af-c281-4005-aff6-a9aa3b2d76d9
50626   4b45a46c-7559-4707-bc8a-a013171cfed1
50663   05099171-d97f-4169-99d8-2f6fc01a0c22
52595   05099171-d97f-4169-99d8-2f6fc01a0c22
53012   05099171-d97f-4169-99d8-2f6fc01a0c22
55428   05099171-d97f-4169-99d8-2f6fc01a0c22
57537   cf171023-7a08-4fe0-9dcf-a2c037ba861e
57544   87f116b2-3b3e-4b23-a98d-30a0021aeaae
58494   4b45a46c-7559-4707-bc8a-a013171cfed1
58544   2bdf7ef7-4796-4969-ba37-5fca1e01b31c
58550   58caf284-73d7-4a9e-ab54-eb51f6b197f5
58618   58caf284-73d7-4a9e-ab54-eb51f6b197f5
58620   2bdf7ef7-4796-4969-ba37-5fca1e01b31c
58671   87f116b2-3b3e-4b23-a98d-30a0021aeaae
58673   cf171023-7a08-4fe0-9dcf-a2c037ba861e
59195   58caf284-73d7-4a9e-ab54-eb51f6b197f5
59197   2bdf7ef7-4796-4969-ba37-5fca1e01b31c
60027   05099171-d97f-4169-99d8-2f6fc01a0c22
61633   cf171023-7a08-4fe0-9dcf-a2c037ba861e
61634   87f116b2-3b3e-4b23-a98d-30a0021aeaae
62599   4b45a46c-7559-4707-bc8a-a013171cfed1
63717   cf171023-7a08-4fe0-9dcf-a2c037ba861e
63718   87f116b2-3b3e-4b23-a98d-30a0021aeaae
63719   58caf284-73d7-4a9e-ab54-eb51f6b197f5
63720   2bdf7ef7-4796-4969-ba37-5fca1e01b31c
64705   87f116b2-3b3e-4b23-a98d-30a0021aeaae
64706   cf171023-7a08-4fe0-9dcf-a2c037ba861e
64930   05099171-d97f-4169-99d8-2f6fc01a0c22
67982   de52b53e-ef19-4db6-a22c-af6e884210a4
68608   05099171-d97f-4169-99d8-2f6fc01a0c22
69463   87f116b2-3b3e-4b23-a98d-30a0021aeaae
69466   cf171023-7a08-4fe0-9dcf-a2c037ba861e
71584   cf171023-7a08-4fe0-9dcf-a2c037ba861e
71977   cf171023-7a08-4fe0-9dcf-a2c037ba861e
74195   05099171-d97f-4169-99d8-2f6fc01a0c22
75109   05099171-d97f-4169-99d8-2f6fc01a0c22
75667   05099171-d97f-4169-99d8-2f6fc01a0c22
76055   de52b53e-ef19-4db6-a22c-af6e884210a4
76662   de52b53e-ef19-4db6-a22c-af6e884210a4
76722   de52b53e-ef19-4db6-a22c-af6e884210a4
76919   4b45a46c-7559-4707-bc8a-a013171cfed1
77193   de52b53e-ef19-4db6-a22c-af6e884210a4
78380   cf171023-7a08-4fe0-9dcf-a2c037ba861e
78381   87f116b2-3b3e-4b23-a98d-30a0021aeaae
78382   58caf284-73d7-4a9e-ab54-eb51f6b197f5
78383   2bdf7ef7-4796-4969-ba37-5fca1e01b31c
78557   05099171-d97f-4169-99d8-2f6fc01a0c22
79699   f7b9124f-022b-4896-a7a6-8c546d89a996
80065   de52b53e-ef19-4db6-a22c-af6e884210a4
80101   58caf284-73d7-4a9e-ab54-eb51f6b197f5
80105   2bdf7ef7-4796-4969-ba37-5fca1e01b31c
80174   f7b9124f-022b-4896-a7a6-8c546d89a996
80197   4907f3af-c281-4005-aff6-a9aa3b2d76d9
81588   f7b9124f-022b-4896-a7a6-8c546d89a996
81589   4907f3af-c281-4005-aff6-a9aa3b2d76d9
83064   05099171-d97f-4169-99d8-2f6fc01a0c22
83147   de52b53e-ef19-4db6-a22c-af6e884210a4
83483   91a5bd82-b407-426f-a9f7-39af4a53b38f
83793   de52b53e-ef19-4db6-a22c-af6e884210a4
84210   05099171-d97f-4169-99d8-2f6fc01a0c22
84239   87f116b2-3b3e-4b23-a98d-30a0021aeaae
84240   cf171023-7a08-4fe0-9dcf-a2c037ba861e
84328   edd24376-4a56-4c30-bc25-17740efa5f75
84331   7e1c699f-d191-4be4-9314-3506b1a75b97
84689   05099171-d97f-4169-99d8-2f6fc01a0c22
85370   7e1c699f-d191-4be4-9314-3506b1a75b97
85371   edd24376-4a56-4c30-bc25-17740efa5f75
85383   95e2be62-4c82-41ce-8b88-81aabe1b60ae
85386   169c14c3-14d5-4a05-b404-4c5c0181dd55
85835   f7b9124f-022b-4896-a7a6-8c546d89a996
85840   4907f3af-c281-4005-aff6-a9aa3b2d76d9
86261   05099171-d97f-4169-99d8-2f6fc01a0c22
87123   eadf4b1b-f1b1-4b54-b7d1-ffb1fd085ae6
89201   4907f3af-c281-4005-aff6-a9aa3b2d76d9
89202   f7b9124f-022b-4896-a7a6-8c546d89a996
89340   05099171-d97f-4169-99d8-2f6fc01a0c22
90016   f7b9124f-022b-4896-a7a6-8c546d89a996
90017   4907f3af-c281-4005-aff6-a9aa3b2d76d9
90590   edd24376-4a56-4c30-bc25-17740efa5f75
93971   05099171-d97f-4169-99d8-2f6fc01a0c22
95725   de52b53e-ef19-4db6-a22c-af6e884210a4
96338   cf171023-7a08-4fe0-9dcf-a2c037ba861e
96340   87f116b2-3b3e-4b23-a98d-30a0021aeaae
96341   58caf284-73d7-4a9e-ab54-eb51f6b197f5
96342   2bdf7ef7-4796-4969-ba37-5fca1e01b31c
96734   de52b53e-ef19-4db6-a22c-af6e884210a4
98122   f7b9124f-022b-4896-a7a6-8c546d89a996
98141   4907f3af-c281-4005-aff6-a9aa3b2d76d9
101889  de52b53e-ef19-4db6-a22c-af6e884210a4
102301  4907f3af-c281-4005-aff6-a9aa3b2d76d9
102317  f7b9124f-022b-4896-a7a6-8c546d89a996
103045  05099171-d97f-4169-99d8-2f6fc01a0c22
103456  f7b9124f-022b-4896-a7a6-8c546d89a996
103461  4907f3af-c281-4005-aff6-a9aa3b2d76d9
104608  f7b9124f-022b-4896-a7a6-8c546d89a996
104612  4907f3af-c281-4005-aff6-a9aa3b2d76d9
104909  4907f3af-c281-4005-aff6-a9aa3b2d76d9
104910  f7b9124f-022b-4896-a7a6-8c546d89a996
106839  de52b53e-ef19-4db6-a22c-af6e884210a4
108639  91a5bd82-b407-426f-a9f7-39af4a53b38f
109470  05099171-d97f-4169-99d8-2f6fc01a0c22
109838  edd24376-4a56-4c30-bc25-17740efa5f75
111105  edd24376-4a56-4c30-bc25-17740efa5f75
111106  7e1c699f-d191-4be4-9314-3506b1a75b97
111108  95e2be62-4c82-41ce-8b88-81aabe1b60ae
111124  169c14c3-14d5-4a05-b404-4c5c0181dd55
112763  05099171-d97f-4169-99d8-2f6fc01a0c22
112962  4907f3af-c281-4005-aff6-a9aa3b2d76d9
112964  f7b9124f-022b-4896-a7a6-8c546d89a996
114131  f7b9124f-022b-4896-a7a6-8c546d89a996
114132  4907f3af-c281-4005-aff6-a9aa3b2d76d9
114447  de52b53e-ef19-4db6-a22c-af6e884210a4
117263  91a5bd82-b407-426f-a9f7-39af4a53b38f
117946  05099171-d97f-4169-99d8-2f6fc01a0c22
118377  05099171-d97f-4169-99d8-2f6fc01a0c22
119298  faa49fa5-6ff0-4321-9f66-ac40569e44e2
119326  edd24376-4a56-4c30-bc25-17740efa5f75
119327  95e2be62-4c82-41ce-8b88-81aabe1b60ae
119329  7e1c699f-d191-4be4-9314-3506b1a75b97
119330  169c14c3-14d5-4a05-b404-4c5c0181dd55
121057  f7b9124f-022b-4896-a7a6-8c546d89a996
121062  4907f3af-c281-4005-aff6-a9aa3b2d76d9
125795  05099171-d97f-4169-99d8-2f6fc01a0c22
126571  05099171-d97f-4169-99d8-2f6fc01a0c22
128916  de52b53e-ef19-4db6-a22c-af6e884210a4
130617  05099171-d97f-4169-99d8-2f6fc01a0c22
131167  58caf284-73d7-4a9e-ab54-eb51f6b197f5
131175  2bdf7ef7-4796-4969-ba37-5fca1e01b31c
131404  cf171023-7a08-4fe0-9dcf-a2c037ba861e
131405  87f116b2-3b3e-4b23-a98d-30a0021aeaae
134305  f7b9124f-022b-4896-a7a6-8c546d89a996
134701  cf171023-7a08-4fe0-9dcf-a2c037ba861e
135534  4b45a46c-7559-4707-bc8a-a013171cfed1
135651  2bdf7ef7-4796-4969-ba37-5fca1e01b31c
135652  58caf284-73d7-4a9e-ab54-eb51f6b197f5
137352  05099171-d97f-4169-99d8-2f6fc01a0c22
138000  05099171-d97f-4169-99d8-2f6fc01a0c22
138211  edd24376-4a56-4c30-bc25-17740efa5f75
138214  7e1c699f-d191-4be4-9314-3506b1a75b97
139440  4b45a46c-7559-4707-bc8a-a013171cfed1
139981  eadf4b1b-f1b1-4b54-b7d1-ffb1fd085ae6
141138  de52b53e-ef19-4db6-a22c-af6e884210a4
142615  cf171023-7a08-4fe0-9dcf-a2c037ba861e
142930  cf171023-7a08-4fe0-9dcf-a2c037ba861e
142931  87f116b2-3b3e-4b23-a98d-30a0021aeaae
143716  4b45a46c-7559-4707-bc8a-a013171cfed1
144786  05099171-d97f-4169-99d8-2f6fc01a0c22
146466  05099171-d97f-4169-99d8-2f6fc01a0c22
147104  05099171-d97f-4169-99d8-2f6fc01a0c22
147784  678a3f11-8e00-498d-8454-ae313c7d8842
147785  894a2134-728f-4c68-b572-f98908903ffd
147786  58caf284-73d7-4a9e-ab54-eb51f6b197f5
147788  2bdf7ef7-4796-4969-ba37-5fca1e01b31c
147854  05099171-d97f-4169-99d8-2f6fc01a0c22
148243  de52b53e-ef19-4db6-a22c-af6e884210a4
148583  cf171023-7a08-4fe0-9dcf-a2c037ba861e
149667  de52b53e-ef19-4db6-a22c-af6e884210a4
149826  cf171023-7a08-4fe0-9dcf-a2c037ba861e
149848  de52b53e-ef19-4db6-a22c-af6e884210a4
150636  de52b53e-ef19-4db6-a22c-af6e884210a4
151662  58caf284-73d7-4a9e-ab54-eb51f6b197f5
151663  2bdf7ef7-4796-4969-ba37-5fca1e01b31c
152436  58caf284-73d7-4a9e-ab54-eb51f6b197f5
152437  2bdf7ef7-4796-4969-ba37-5fca1e01b31c
152538  de52b53e-ef19-4db6-a22c-af6e884210a4
153184  f7b9124f-022b-4896-a7a6-8c546d89a996
153187  4907f3af-c281-4005-aff6-a9aa3b2d76d9
154032  f7b9124f-022b-4896-a7a6-8c546d89a996
154035  4907f3af-c281-4005-aff6-a9aa3b2d76d9
154179  f7b9124f-022b-4896-a7a6-8c546d89a996
154195  4907f3af-c281-4005-aff6-a9aa3b2d76d9
156102  f7b9124f-022b-4896-a7a6-8c546d89a996
156111  4907f3af-c281-4005-aff6-a9aa3b2d76d9
157392  4907f3af-c281-4005-aff6-a9aa3b2d76d9
157395  f7b9124f-022b-4896-a7a6-8c546d89a996
158259  cf171023-7a08-4fe0-9dcf-a2c037ba861e
158292  2bdf7ef7-4796-4969-ba37-5fca1e01b31c
158295  58caf284-73d7-4a9e-ab54-eb51f6b197f5
158458  05099171-d97f-4169-99d8-2f6fc01a0c22
158690  4907f3af-c281-4005-aff6-a9aa3b2d76d9
158692  f7b9124f-022b-4896-a7a6-8c546d89a996
160277  edd24376-4a56-4c30-bc25-17740efa5f75
161731  91a5bd82-b407-426f-a9f7-39af4a53b38f
162298  05099171-d97f-4169-99d8-2f6fc01a0c22
163309  edd24376-4a56-4c30-bc25-17740efa5f75
163311  95e2be62-4c82-41ce-8b88-81aabe1b60ae
163313  7e1c699f-d191-4be4-9314-3506b1a75b97
163317  169c14c3-14d5-4a05-b404-4c5c0181dd55
163613  de52b53e-ef19-4db6-a22c-af6e884210a4
165669  de52b53e-ef19-4db6-a22c-af6e884210a4
171375  de52b53e-ef19-4db6-a22c-af6e884210a4
171426  de52b53e-ef19-4db6-a22c-af6e884210a4
175831  05099171-d97f-4169-99d8-2f6fc01a0c22
175851  de52b53e-ef19-4db6-a22c-af6e884210a4
176727  de52b53e-ef19-4db6-a22c-af6e884210a4
177076  f7b9124f-022b-4896-a7a6-8c546d89a996
177088  4907f3af-c281-4005-aff6-a9aa3b2d76d9
177654  f7b9124f-022b-4896-a7a6-8c546d89a996
177657  4907f3af-c281-4005-aff6-a9aa3b2d76d9
177909  7a8b5c44-5df6-4c61-9f82-114b659d19df
178159  de52b53e-ef19-4db6-a22c-af6e884210a4
181544  05099171-d97f-4169-99d8-2f6fc01a0c22
181737  f7b9124f-022b-4896-a7a6-8c546d89a996
181740  4907f3af-c281-4005-aff6-a9aa3b2d76d9
182414  05099171-d97f-4169-99d8-2f6fc01a0c22
182640  edd24376-4a56-4c30-bc25-17740efa5f75
182790  4907f3af-c281-4005-aff6-a9aa3b2d76d9
183266  f7b9124f-022b-4896-a7a6-8c546d89a996
183738  169c14c3-14d5-4a05-b404-4c5c0181dd55
183921  4907f3af-c281-4005-aff6-a9aa3b2d76d9
183925  f7b9124f-022b-4896-a7a6-8c546d89a996
184331  de52b53e-ef19-4db6-a22c-af6e884210a4
185764  de52b53e-ef19-4db6-a22c-af6e884210a4
186309  de52b53e-ef19-4db6-a22c-af6e884210a4
186663  91a5bd82-b407-426f-a9f7-39af4a53b38f
187371  05099171-d97f-4169-99d8-2f6fc01a0c22
187910  05099171-d97f-4169-99d8-2f6fc01a0c22
188955  169c14c3-14d5-4a05-b404-4c5c0181dd55
188963  95e2be62-4c82-41ce-8b88-81aabe1b60ae
188964  edd24376-4a56-4c30-bc25-17740efa5f75
188965  7e1c699f-d191-4be4-9314-3506b1a75b97
190117  7a8b5c44-5df6-4c61-9f82-114b659d19df
191430  4907f3af-c281-4005-aff6-a9aa3b2d76d9
191431  f7b9124f-022b-4896-a7a6-8c546d89a996
191645  7a8b5c44-5df6-4c61-9f82-114b659d19df
193894  f7b9124f-022b-4896-a7a6-8c546d89a996
193897  4907f3af-c281-4005-aff6-a9aa3b2d76d9
196046  05099171-d97f-4169-99d8-2f6fc01a0c22
196787  05099171-d97f-4169-99d8-2f6fc01a0c22
198221  05099171-d97f-4169-99d8-2f6fc01a0c22
198813  05099171-d97f-4169-99d8-2f6fc01a0c22
201589  05099171-d97f-4169-99d8-2f6fc01a0c22
202025  05099171-d97f-4169-99d8-2f6fc01a0c22
203164  cf171023-7a08-4fe0-9dcf-a2c037ba861e
203166  87f116b2-3b3e-4b23-a98d-30a0021aeaae
204052  cf171023-7a08-4fe0-9dcf-a2c037ba861e
204749  87f116b2-3b3e-4b23-a98d-30a0021aeaae
204750  cf171023-7a08-4fe0-9dcf-a2c037ba861e
206754  58caf284-73d7-4a9e-ab54-eb51f6b197f5
206755  2bdf7ef7-4796-4969-ba37-5fca1e01b31c
207365  cf171023-7a08-4fe0-9dcf-a2c037ba861e
207808  58caf284-73d7-4a9e-ab54-eb51f6b197f5
207809  2bdf7ef7-4796-4969-ba37-5fca1e01b31c
211318  05099171-d97f-4169-99d8-2f6fc01a0c22
213966  4907f3af-c281-4005-aff6-a9aa3b2d76d9
213967  f7b9124f-022b-4896-a7a6-8c546d89a996
214996  cf171023-7a08-4fe0-9dcf-a2c037ba861e
214997  87f116b2-3b3e-4b23-a98d-30a0021aeaae
214998  58caf284-73d7-4a9e-ab54-eb51f6b197f5
217913  05099171-d97f-4169-99d8-2f6fc01a0c22
219060  05099171-d97f-4169-99d8-2f6fc01a0c22
219470  91a5bd82-b407-426f-a9f7-39af4a53b38f
219915  05099171-d97f-4169-99d8-2f6fc01a0c22
220148  05099171-d97f-4169-99d8-2f6fc01a0c22
220494  05099171-d97f-4169-99d8-2f6fc01a0c22
220712  edd24376-4a56-4c30-bc25-17740efa5f75
220714  95e2be62-4c82-41ce-8b88-81aabe1b60ae
220715  7e1c699f-d191-4be4-9314-3506b1a75b97
220875  58caf284-73d7-4a9e-ab54-eb51f6b197f5
220877  2bdf7ef7-4796-4969-ba37-5fca1e01b31c
222412  58caf284-73d7-4a9e-ab54-eb51f6b197f5
222414  2bdf7ef7-4796-4969-ba37-5fca1e01b31c
224533  05099171-d97f-4169-99d8-2f6fc01a0c22
224765  58caf284-73d7-4a9e-ab54-eb51f6b197f5
224766  2bdf7ef7-4796-4969-ba37-5fca1e01b31c
224776  cf171023-7a08-4fe0-9dcf-a2c037ba861e
224786  87f116b2-3b3e-4b23-a98d-30a0021aeaae
225389  05099171-d97f-4169-99d8-2f6fc01a0c22
225833  de52b53e-ef19-4db6-a22c-af6e884210a4
226209  de52b53e-ef19-4db6-a22c-af6e884210a4
226725  de52b53e-ef19-4db6-a22c-af6e884210a4
227414  de52b53e-ef19-4db6-a22c-af6e884210a4
227868  2bdf7ef7-4796-4969-ba37-5fca1e01b31c
227869  58caf284-73d7-4a9e-ab54-eb51f6b197f5
227873  cf171023-7a08-4fe0-9dcf-a2c037ba861e
227875  87f116b2-3b3e-4b23-a98d-30a0021aeaae
228792  de52b53e-ef19-4db6-a22c-af6e884210a4
228988  4907f3af-c281-4005-aff6-a9aa3b2d76d9
228989  f7b9124f-022b-4896-a7a6-8c546d89a996
229494  2bdf7ef7-4796-4969-ba37-5fca1e01b31c
229518  58caf284-73d7-4a9e-ab54-eb51f6b197f5
230685  f7b9124f-022b-4896-a7a6-8c546d89a996
230686  4907f3af-c281-4005-aff6-a9aa3b2d76d9
230744  f7b9124f-022b-4896-a7a6-8c546d89a996
231231  f7b9124f-022b-4896-a7a6-8c546d89a996
231233  4907f3af-c281-4005-aff6-a9aa3b2d76d9
231509  91a5bd82-b407-426f-a9f7-39af4a53b38f
231930  05099171-d97f-4169-99d8-2f6fc01a0c22
232060  05099171-d97f-4169-99d8-2f6fc01a0c22
232713  f7b9124f-022b-4896-a7a6-8c546d89a996
232715  4907f3af-c281-4005-aff6-a9aa3b2d76d9
232967  edd24376-4a56-4c30-bc25-17740efa5f75
232970  7e1c699f-d191-4be4-9314-3506b1a75b97
232975  169c14c3-14d5-4a05-b404-4c5c0181dd55
232983  95e2be62-4c82-41ce-8b88-81aabe1b60ae
233909  f7b9124f-022b-4896-a7a6-8c546d89a996
233910  05099171-d97f-4169-99d8-2f6fc01a0c22
233911  4907f3af-c281-4005-aff6-a9aa3b2d76d9
233946  05099171-d97f-4169-99d8-2f6fc01a0c22
234182  2bdf7ef7-4796-4969-ba37-5fca1e01b31c
234184  58caf284-73d7-4a9e-ab54-eb51f6b197f5
235618  7a8b5c44-5df6-4c61-9f82-114b659d19df
237454  cf171023-7a08-4fe0-9dcf-a2c037ba861e
237455  87f116b2-3b3e-4b23-a98d-30a0021aeaae
237456  2bdf7ef7-4796-4969-ba37-5fca1e01b31c
237458  58caf284-73d7-4a9e-ab54-eb51f6b197f5
237740  edd24376-4a56-4c30-bc25-17740efa5f75
238142  cf171023-7a08-4fe0-9dcf-a2c037ba861e
241143  f7b9124f-022b-4896-a7a6-8c546d89a996
241145  4907f3af-c281-4005-aff6-a9aa3b2d76d9
242586  de52b53e-ef19-4db6-a22c-af6e884210a4
244450  91a5bd82-b407-426f-a9f7-39af4a53b38f
245033  05099171-d97f-4169-99d8-2f6fc01a0c22
246266  edd24376-4a56-4c30-bc25-17740efa5f75
246269  95e2be62-4c82-41ce-8b88-81aabe1b60ae
246271  7e1c699f-d191-4be4-9314-3506b1a75b97
247077  de52b53e-ef19-4db6-a22c-af6e884210a4
248021  f7b9124f-022b-4896-a7a6-8c546d89a996
248022  4907f3af-c281-4005-aff6-a9aa3b2d76d9
248043  de52b53e-ef19-4db6-a22c-af6e884210a4
248439  de52b53e-ef19-4db6-a22c-af6e884210a4
250303  4b45a46c-7559-4707-bc8a-a013171cfed1
251660  f7b9124f-022b-4896-a7a6-8c546d89a996
251661  4907f3af-c281-4005-aff6-a9aa3b2d76d9
253676  f7b9124f-022b-4896-a7a6-8c546d89a996
253967  f7b9124f-022b-4896-a7a6-8c546d89a996
253968  4907f3af-c281-4005-aff6-a9aa3b2d76d9
254021  de52b53e-ef19-4db6-a22c-af6e884210a4
254081  de52b53e-ef19-4db6-a22c-af6e884210a4
254255  05099171-d97f-4169-99d8-2f6fc01a0c22
254463  de52b53e-ef19-4db6-a22c-af6e884210a4
255824  de52b53e-ef19-4db6-a22c-af6e884210a4
257191  05099171-d97f-4169-99d8-2f6fc01a0c22
257592  58caf284-73d7-4a9e-ab54-eb51f6b197f5
257593  2bdf7ef7-4796-4969-ba37-5fca1e01b31c
257914  05099171-d97f-4169-99d8-2f6fc01a0c22
259040  58caf284-73d7-4a9e-ab54-eb51f6b197f5
259043  2bdf7ef7-4796-4969-ba37-5fca1e01b31c
259046  894a2134-728f-4c68-b572-f98908903ffd
259049  678a3f11-8e00-498d-8454-ae313c7d8842
260076  4907f3af-c281-4005-aff6-a9aa3b2d76d9
260081  f7b9124f-022b-4896-a7a6-8c546d89a996
260087  f7b9124f-022b-4896-a7a6-8c546d89a996
260089  4907f3af-c281-4005-aff6-a9aa3b2d76d9
260834  de52b53e-ef19-4db6-a22c-af6e884210a4
262924  de52b53e-ef19-4db6-a22c-af6e884210a4
263959  de52b53e-ef19-4db6-a22c-af6e884210a4
265193  05099171-d97f-4169-99d8-2f6fc01a0c22
265222  05099171-d97f-4169-99d8-2f6fc01a0c22
266068  05099171-d97f-4169-99d8-2f6fc01a0c22
266641  e4a906ca-8ce7-4af1-9c93-2ff0d130b5fe
268249  4907f3af-c281-4005-aff6-a9aa3b2d76d9
268252  f7b9124f-022b-4896-a7a6-8c546d89a996
268479  7a8b5c44-5df6-4c61-9f82-114b659d19df
269608  f7b9124f-022b-4896-a7a6-8c546d89a996
269626  4907f3af-c281-4005-aff6-a9aa3b2d76d9
269738  4b45a46c-7559-4707-bc8a-a013171cfed1
270075  eadf4b1b-f1b1-4b54-b7d1-ffb1fd085ae6
270533  f7b9124f-022b-4896-a7a6-8c546d89a996
270534  4907f3af-c281-4005-aff6-a9aa3b2d76d9
272475  05099171-d97f-4169-99d8-2f6fc01a0c22
273000  05099171-d97f-4169-99d8-2f6fc01a0c22
274849  05099171-d97f-4169-99d8-2f6fc01a0c22
276010  58caf284-73d7-4a9e-ab54-eb51f6b197f5
276013  2bdf7ef7-4796-4969-ba37-5fca1e01b31c
276620  05099171-d97f-4169-99d8-2f6fc01a0c22
278032  58caf284-73d7-4a9e-ab54-eb51f6b197f5
278854  87f116b2-3b3e-4b23-a98d-30a0021aeaae
278855  cf171023-7a08-4fe0-9dcf-a2c037ba861e
278994  cf171023-7a08-4fe0-9dcf-a2c037ba861e
282501  e4a906ca-8ce7-4af1-9c93-2ff0d130b5fe
282972  05099171-d97f-4169-99d8-2f6fc01a0c22
283062  58caf284-73d7-4a9e-ab54-eb51f6b197f5
283913  de52b53e-ef19-4db6-a22c-af6e884210a4

In [ ]:
import requests
from tqdm import tqdm

not_found = []

for idx, url in tqdm(df["product_url"].dropna().items()):
    try:
        r = requests.get(url, timeout=10, headers={"User-Agent":"Mozilla/5.0"})

        if r.status_code == 404:
            not_found.append(idx)

    except:
        pass

df_404 = df.loc[not_found]

print(f"404 URLs: {len(df_404)}")
df_404[["unique_id","product_name","product_url"]]

1397it [07:48,  4.17it/s]

In [53]:
!pip install tqdm

Collecting tqdm
  Downloading tqdm-4.68.4-py3-none-any.whl (676 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 676.6/676.6 KB 1.2 MB/s eta 0:00:00a 0:00:01
Installing collected packages: tqdm
Successfully installed tqdm-4.68.4

In [3]:
import re

valid_pattern = r"^https://www\.zepto\.com/"

invalid_urls = df[
    ~df["product_url"].astype(str).str.match(valid_pattern, na=False)
]

print(len(invalid_urls))

0

In [4]:
invalid = df[
    ~df["product_url"].str.contains(r"/pvid/", regex=True, na=False)
]

In [6]:
unique_urls = df["product_url"].dropna().unique()

print(len(unique_urls))

14804

In [7]:
import pandas as pd
import requests
from concurrent.futures import ThreadPoolExecutor, as_completed
from tqdm import tqdm

headers = {
    "User-Agent": "Mozilla/5.0"
}

unique_urls = df["product_url"].dropna().unique()

def check_url(url):
    try:
        r = requests.get(
            url,
            headers=headers,
            timeout=10,
            allow_redirects=True
        )
        return url, r.status_code
    except Exception:
        return url, "ERROR"

results = []

with ThreadPoolExecutor(max_workers=20) as executor:
    futures = [executor.submit(check_url, url) for url in unique_urls]

    for future in tqdm(as_completed(futures), total=len(futures)):
        results.append(future.result())

status_df = pd.DataFrame(results, columns=["product_url", "status_code"])

invalid_urls = status_df[status_df["status_code"] != 200]

print(invalid_urls)

100%|██████████| 14804/14804 [04:59<00:00, 49.39it/s]

                                                                                                                                                                                                                                                                                                                                                                                                                       product_url  \
401                                                                                                                                                                                                                                                                                                                                https://www.zepto.com/pn/sri-bhagyalakshmi-ground-nut/pvid/6c92632d-e112-4550-aeaa-cd1f117f26ba
409                                                                                                                                                                                                                                                                                                                  https://www.zepto.com/pn/daily-good-unpolished-urad-dal-split-white/pvid/d37a3cfd-ddbc-44df-8a3d-de1c40f0ae90
413                                                                                                                                                                                                                                                                                                                  https://www.zepto.com/pn/daily-good-unpolished-urad-dal-split-white/pvid/e0c65e93-3f0e-4a79-8d2b-e09d0348f90a
415                                                                                                                                                                                                                                                                                                                                https://www.zepto.com/pn/sri-bhagyalakshmi-fried-gram/pvid/77c6f32c-d410-49d0-a5ce-151de13f3485
416                                                                                                                                                                                                                                                                                                            https://www.zepto.com/pn/tata-sampann-unpolished-kabuli-chana-medium-size/pvid/ea6f2d5d-4f9d-4323-9513-09b1b8029e12
417                                                                                                                                                                                                                                                                                                                     https://www.zepto.com/pn/popular-essentials-toor-dal-un-polished/pvid/899ecab5-8bca-4c00-b13e-6aafc0889fe9
418                                                                                                                                                                                                                                                                                                                    https://www.zepto.com/pn/daily-good-unpolished-toor-tur-arhar-dal/pvid/d05b8f97-2ccb-49ea-b1a2-9ec699a82871
419                                                                                                                                                                                                                                                                                                    https://www.zepto.com/pn/faber-castell-modelling-dough-set-12-regular-neon-colors/pvid/d79a4e8e-ef2e-40ff-b2a0-3a68329fb70c
420                                                                                                                                                                                                                                                                                                   https://www.zepto.com/pn/skillmatics-foil-fun-up-in-space-art-craft-game-4-9-years/pvid/fc8edb97-54a9-4ee7-b9fd-5529bc202abd
421                                                                                                                                                                                                                                                                                              https://www.zepto.com/pn/toyshine-set-of-5-pcs-super-hero-cartoon-plastic-mask-for-kids/pvid/e2507ccb-c541-4454-891f-549d4f9f4dd5
422                                                                                                                                                                                                                                                                                                                      https://www.zepto.com/pn/tata-sampann-unpolished-urad-dal-split/pvid/e77c277f-7948-4142-a1dd-bf094f71f798
423                                                                                                                                                                                                                                                                                                     https://www.zepto.com/pn/fundough-bakery-playset-creative-kids-toy-for-birthdays/pvid/6cdb4525-a6da-4331-96de-f517ccc659bb
424                                                                                                                                                                                                                                                                                                                            https://www.zepto.com/pn/farmart-pantry-toor-dalarhar-dal/pvid/b9efcc09-b64b-4b6c-afd7-a14fdb63622f
425                                                                                                                                                                                                                                                                                        https://www.zepto.com/pn/einstein-box-ultimate-slime-kit-for-boys-girls-ages-4-6-8-12-14years/pvid/a44ac097-7681-4b37-881d-9a418d02fe35
426                                                                                                                                                                                                                                                                    https://www.zepto.com/pn/fablue-12-pcs-dry-colors-clay-toy-for-kids-creative-art-and-diy-crafts-toy-clay-for-kids/pvid/89a23064-c927-4753-b6b7-bbaa44bab8f1
427                                                                                                                                                                                                                                                                          https://www.zepto.com/pn/fevicreate-finger-painting-kit-for-toddlers-children-preschoolerscontains-washable/pvid/7f89320a-1ea1-42f0-8183-0aab0ae14eab
428                                                                                                                                                                                                                                                                    https://www.zepto.com/pn/imagimake-indian-art-forms-art-craft-kit-creative-birthday-gifting-toys-for-kids-8-years/pvid/7b5e6461-a530-4763-a1bd-f5d7a767e320
429                                                                                                                                                                                                                                                                https://www.zepto.com/pn/toyshine-1-kg-creative-sand-for-kids-with-free-8-pcs-castle-molds-1-bonus-mold-natural-color/pvid/1f6724ad-3660-456e-bbbb-bc2ebf67c7d1
430                                                                                                                                                                                                                                                                                                               https://www.zepto.com/pn/shree-akshara-premium-sona-masoori-rice-steam/pvid/eeb16c5d-8a67-48f2-b4de-1794d2bbf484
431                                                                                                                                                                                                                                                             https://www.zepto.com/pn/toyshine-diy-non-sticky-smooth-colorful-water-glossy-relief-toy-for-kids-party-favor-multicolor/pvid/b626e156-7512-430b-9b59-541f9ff0cdc4
432                                                                                                                                                                                                                                                                                https://www.zepto.com/pn/ekta-glow-in-the-dark-slime-coolest-spookiest-slime-super-stretchy-slime-kit/pvid/32c4305d-276a-4a79-977f-3fbf4be37f0f
433                                                                                                                                                                                                                                                                       https://www.zepto.com/pn/jogenii-neon-nature-art-colouring-kit-with-16-big-sheets-sketch-pens-and-glitter-tube/pvid/f27c8923-8a09-48d6-b13d-e37ae4e06bd4
434                                                                                                                                                                                                                                                                                                                            https://www.zepto.com/pn/daily-good-sona-masoori-raw-rice/pvid/bfe98cad-c52c-4c3f-9f99-ee9f0f71118f
435                                                                                                                                                                                                                                                                                                                                     https://www.zepto.com/pn/gts-original-kolam-rice/pvid/e48a9dce-f3bb-469f-939e-272eb64752a3
436                                                                                                                                                                                                                                                                                                                                     https://www.zepto.com/pn/gts-original-kolam-rice/pvid/29043823-7e55-4e8d-b2fe-5bdd4cf9c8c0
437                                                                                                                                                                                                                                                                                                                       https://www.zepto.com/pn/royal-bullet-sona-masuri-steamed-rice/pvid/2e3dc1b7-a552-4ea4-a7fc-09e04439b66e
438                                                                                                                                                                                                                                                                                                               https://www.zepto.com/pn/daawat-rozana-super-basmati-rice-medium-grain/pvid/7851f4a9-cab6-4b75-bae2-bcbc43bf0bdb
439                                                                                                                                                                                                                                                                                                                  https://www.zepto.com/pn/fortune-sona-masoori-supreme-raw-aged-rice/pvid/042bfda1-564b-44a7-b1df-9a968a11333c
440                                                                                                                                                                                                                                                                                                                               https://www.zepto.com/pn/daawat-rozana-mini-mogra-rice/pvid/3f3e18bb-6556-4a3f-9be6-c27897f3f814
441                                                                                                                                                                                                                                                                                                               https://www.zepto.com/pn/daawat-premium-sona-masoori-rice-medium-grain/pvid/82e8f251-f6a6-4329-afdf-5a4cfdf636ed
442                                                                                                                                                                                                                                                                                                                         https://www.zepto.com/pn/double-horse-jyothi-vadi-matta-rice/pvid/f0c863a9-6798-4d29-b912-f154176b6ee1
443                                                                                                                                                                                                                                                                                                                                     https://www.zepto.com/pn/gts-original-kolam-rice/pvid/77bfe56c-9477-464d-808f-f278447532c8
444                                                                                                                                                                                                                                                                                                                            https://www.zepto.com/pn/daily-good-sona-masoori-raw-rice/pvid/95edc2a8-2f28-43e4-871a-2308c0c6c62a
445                                                                                                                                                                                                                                                                                                  https://www.zepto.com/pn/devaaya-basmati-rice-aromatic-long-and-fluffy-medium-grain/pvid/dc08d538-2786-4aca-9302-8608221fd376
446                                                                                                                                                                                                                                                                                                               https://www.zepto.com/pn/india-gate-classic-gold-standard-basmati-rice/pvid/bb3437d0-568b-41b5-81cd-d01db7af7804
447                                                                                                                                                                                                                                                                                                                           https://www.zepto.com/pn/india-gate-jeera-rice-short-grain/pvid/aebefabf-6c81-409e-a4e8-2797d36b07d3
448                                                                                                                                                                                                                                                                                                                                        https://www.zepto.com/pn/daily-good-dosa-rice/pvid/6e80d7eb-4916-45f7-bf86-06039a80feae
449                                                                                                                                                                                                                                                                                                      https://www.zepto.com/pn/shree-akshara-premium-steam-sona-masoori-rice-polished/pvid/74abb8da-390c-4d1a-a820-f9b1b9e68e5a
450                                                                                                                                                                                                                                                                                                                 https://www.zepto.com/pn/shree-akshara-premium-sona-masoori-rice-raw/pvid/38358849-27e1-4b7e-a60d-11091bd10584
451                                                                                                                                                                                                                                                                                                                                    https://www.zepto.com/pn/daawat-rozana-mogra-rice/pvid/8d9a353f-2365-447a-b5bd-13240cb5350b
452                                                                                                                                                                                                                                                                                                           https://www.zepto.com/pn/india-gate-dubar-basmati-rice-long-slender-grains/pvid/1f01a4c6-58a3-41e7-b281-04db458cfa56
453                                                                                                                                                                                                                                                                                                                   https://www.zepto.com/pn/popular-essentials-bullet-wada-kolam-rice/pvid/68d45569-ee47-4f7e-9c48-572d02224b5e
454                                                                                                                                                                                                                                                                                                                          https://www.zepto.com/pn/double-horse-palakkadan-matta-rice/pvid/a8312897-ffa6-4bb8-b447-035dcbdd0157
455                                                                                                                                                                                                                                                                                                       https://www.zepto.com/pn/india-gate-everyday-basmati-rice-fluffy-medium-grains/pvid/62b069eb-400c-4420-a173-e8f48a13a4b6
456                                                                                                                                                                                                                                                                           https://www.zepto.com/pn/india-gate-all-rounder-feast-rozzana-basmati-rice-aged-rice-fluffy-and-non-sticky/pvid/75118c7a-2b92-441a-995c-ea416b67c05e
457                                                                                                                                                                                                                                                                                                                            https://www.zepto.com/pn/fortune-rozana-gold-basmati-rice/pvid/8188d4ba-20c4-4774-80fa-ccb1e3b6ba4a

In [8]:
(status_df["status_code"] == 404).any()

np.False_

In [11]:
status_df["status_code"].value_counts()

status_code
429      14380
200        412
ERROR       12
Name: count, dtype: int64

In [12]:
import pandas as pd
import requests
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from tqdm import tqdm

headers = {
    "User-Agent": "Mozilla/5.0"
}

# Sample 500 unique URLs
sample_urls = (
    pd.Series(df["product_url"].dropna().unique())
    .sample(500, random_state=42)
    .tolist()
)

def check_url(url):
    try:
        time.sleep(0.5)  # Reduce request rate
        r = requests.get(
            url,
            headers=headers,
            timeout=10,
            allow_redirects=True,
        )
        return url, r.status_code
    except Exception:
        return url, "ERROR"

results = []

with ThreadPoolExecutor(max_workers=3) as executor:
    futures = [executor.submit(check_url, url) for url in sample_urls]

    for future in tqdm(as_completed(futures), total=len(futures)):
        results.append(future.result())

status_df = pd.DataFrame(results, columns=["product_url", "status_code"])

print(status_df["status_code"].value_counts())

100%|██████████| 500/500 [03:01<00:00,  2.75it/s]

status_code
429    309
200    191
Name: count, dtype: int64