In [2]:
import pandas as pd
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option("display.max_colwidth", None)

In [3]:
df = pd.read_csv(r'/home/user/Documents/zepto_2026_07_15.csv',  low_memory=False)

In [3]:
df.shape

(553752, 31)

In [4]:
df.isnull().sum()

crawl_date_and_time             0
platform_name                   0
store_id                        0
store_name_location             0
city                            0
pin_code                        0
unique_id                       0
product_id_upc_ean              0
department                      0
category                        0
sub_category                    0
product_type               553752
brand_name                      0
product_name                    0
product_description        553752
product_grammage           100852
package_type               553752
net_quantity                    0
variants                   538835
item_mrp                        1
item_selling_price              0
out_of_stock_flag               0
discount_flag                   0
product_price                   0
unit_price                 553752
promo_offer_description         0
promo_offer_price               0
discount_in_percent             0
stock_count                     0
product_url                     0
product_image_urls         553752
dtype: int64

In [5]:
df.nunique()

crawl_date_and_time        14713
platform_name                  1
store_id                     206
store_name_location          147
city                          34
pin_code                     135
unique_id                  14936
product_id_upc_ean         14509
department                    10
category                      23
sub_category                 159
product_type                   0
brand_name                  1622
product_name               13395
product_description            0
product_grammage             981
package_type                   0
net_quantity                1870
variants                     260
item_mrp                    1111
item_selling_price          1952
out_of_stock_flag              2
discount_flag                  2
product_price               1952
unit_price                     0
promo_offer_description     1340
promo_offer_price           1952
discount_in_percent           92
stock_count                   52
product_url                14940
product_image_urls             0
dtype: int64

In [6]:
df.city.value_counts()

city
Bangalore        126721
Hyderabad         69118
Mumbai            66661
Chennai           57143
Pune              50162
Kolkata           25884
Surat             14649
Indore            14129
Mysuru            11240
Nagpur            10935
Ahmedabad         10607
Coimbatore         7460
Nashik             7448
Kochi              7431
Prayagraj          6199
Greater Noida      4271
Sonipat            4051
Haridwar           3908
Karnal             3746
Udaipur            3732
Vijayawada         3707
Hubballi           3705
Patiala            3687
Bhiwadi            3645
Panipat            3635
Bareilly           3573
Madurai            3555
S.A.S Nagar        3455
Dehradun           3358
Jalandhar          3273
Faridabad          3267
Kota               3262
Agra               3195
Barasat            2940
Name: count, dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.unique_id.duplicated().sum()

np.int64(538816)

In [9]:
pin_check = (
    df.groupby("store_name_location")["pin_code"]
        .nunique()
        .sort_values(ascending=False)
)

pin_check[pin_check > 1]

Series([], Name: pin_code, dtype: int64)

In [10]:
missing_grammage = df[df["product_grammage"].isna()]

print("Rows with missing product_grammage:", len(missing_grammage))
missing_grammage.head()

Rows with missing product_grammage: 100852

,crawl_date_and_time,platform_name,store_id,store_name_location,city,pin_code,unique_id,product_id_upc_ean,department,category,sub_category,product_type,brand_name,product_name,product_description,product_grammage,package_type,net_quantity,variants,item_mrp,item_selling_price,out_of_stock_flag,discount_flag,product_price,unit_price,promo_offer_description,promo_offer_price,discount_in_percent,stock_count,product_url,product_image_urls
35,2026-07-15 00:05:06,zepto,b359ba27-8fe9-4c95-85f0-0939de00f5a4,"Reliance Smart SuperStore, Platina Mall, Near Kunhadi Petrol Pump, Vishkarma Nagar, Kunadi, Electricity Board Area, Kota, Rajasthan, 324008, India",Kota,324008,293a8ceb-56df-4db5-9c4a-d519d2c3b871,d32259d2-d1e7-4680-aa98-b4d07a5154a6,"Atta, Rice & Dal","Atta, Rice, Oil & Dals",Millets & Other Flours,NaN,Shiva's,Shiva's Rajgiri Atta,NaN,NaN,NaN,500 g,NaN,170.0,103.0,No,Yes,103.0,NaN,₹67 OFF,103.0,39,2,https://www.zepto.com/pn/shivas-rajgiri-atta/pvid/293a8ceb-56df-4db5-9c4a-d519d2c3b871,NaN
37,2026-07-15 00:05:06,zepto,b359ba27-8fe9-4c95-85f0-0939de00f5a4,"Reliance Smart SuperStore, Platina Mall, Near Kunhadi Petrol Pump, Vishkarma Nagar, Kunadi, Electricity Board Area, Kota, Rajasthan, 324008, India",Kota,324008,bb8a9f07-bfc4-49aa-b134-de9c71b1c414,7a1cecde-b4a0-41c8-be61-1288486ef82a,"Atta, Rice & Dal","Atta, Rice, Oil & Dals",Millets & Other Flours,NaN,Shiva's,Shiva's Chawal | Rice Atta,NaN,NaN,NaN,500 g,NaN,46.0,46.0,No,No,46.0,NaN,No offer,46.0,0,4,https://www.zepto.com/pn/shivas-chawal-rice-atta/pvid/bb8a9f07-bfc4-49aa-b134-de9c71b1c414,NaN
41,2026-07-15 00:05:06,zepto,b359ba27-8fe9-4c95-85f0-0939de00f5a4,"Reliance Smart SuperStore, Platina Mall, Near Kunhadi Petrol Pump, Vishkarma Nagar, Kunadi, Electricity Board Area, Kota, Rajasthan, 324008, India",Kota,324008,270298e2-9067-4425-990e-50744f493c52,daacc8b0-ba9d-452c-b8c7-35a60775b437,"Atta, Rice & Dal","Atta, Rice, Oil & Dals",Millets & Other Flours,NaN,Shiva's,Shiva's Rajgiri Atta,NaN,NaN,NaN,200 g,NaN,72.0,46.0,No,Yes,46.0,NaN,₹26 OFF,46.0,36,4,https://www.zepto.com/pn/shivas-rajgiri-atta/pvid/270298e2-9067-4425-990e-50744f493c52,NaN
43,2026-07-15 00:05:06,zepto,b359ba27-8fe9-4c95-85f0-0939de00f5a4,"Reliance Smart SuperStore, Platina Mall, Near Kunhadi Petrol Pump, Vishkarma Nagar, Kunadi, Electricity Board Area, Kota, Rajasthan, 324008, India",Kota,324008,c645fb45-ab53-4d02-adfc-df4068d4ccf6,6bf92f31-8582-489f-ab12-1a6e6a8d9725,"Atta, Rice & Dal","Atta, Rice, Oil & Dals",Millets & Other Flours,NaN,Shiva's,Shiva's Pakodi Mix,NaN,NaN,NaN,400 g,NaN,145.0,80.0,No,Yes,80.0,NaN,₹65 OFF,80.0,44,2,https://www.zepto.com/pn/shivas-pakodi-mix/pvid/c645fb45-ab53-4d02-adfc-df4068d4ccf6,NaN
47,2026-07-15 00:05:06,zepto,b359ba27-8fe9-4c95-85f0-0939de00f5a4,"Reliance Smart SuperStore, Platina Mall, Near Kunhadi Petrol Pump, Vishkarma Nagar, Kunadi, Electricity Board Area, Kota, Rajasthan, 324008, India",Kota,324008,ecd087a6-de0c-4b25-b55f-ccbede1bf462,21839d04-c4f7-44af-aa6a-e0e42105b035,"Atta, Rice & Dal","Atta, Rice, Oil & Dals",Millets & Other Flours,NaN,Shiva's,Shiva's Bedmi Puri Mix,NaN,NaN,NaN,400 g,NaN,110.0,65.0,No,Yes,65.0,NaN,₹45 OFF,65.0,40,1,https://www.zepto.com/pn/shivas-bedmi-puri-mix/pvid/ecd087a6-de0c-4b25-b55f-ccbede1bf462,NaN

In [11]:
df.net_quantity.value_counts()

net_quantity
1 pc                                  41442
1 pack (200 g)                        19598
1 pack (500 g)                        18493
1 pack (1 kg)                         15772
1 pc (100 ml)                         14266
1 pc (200 ml)                         11507
1 pack (100 g)                        11126
1 pc (250 ml)                         10946
1 pc (1 L)                            10810
1 set                                 10489
1 pc (100 g)                          10359
1 pc (50 g)                            9215
1 pc (50 ml)                           7810
1 pack (5 kg)                          7321
1 pack (250 g)                         6214
1 pack (1 L)                           5686
1 pack (400 g)                         5472
1 pc (150 ml)                          5457
1 pc (400 ml)                          4804
1 pack (500 ml)                        4558
1 pc (30 ml)                           4487
1 pack (150 g)                         4306
1 pc (180 ml)                          4089
1 pc (200 g)                           3975
1 pack (6 pcs)                         3948
1 pack (50 g)                          3748
1 pc (300 ml)                          3674
1 pack (2 pcs)                         3552
1 pack (10 pcs)                        3275
1 pc (120 ml)                          3264
1 pc (500 ml)                          3052
1 pc (80 g)                            3005
1 pack (60 g)                          2980
1 pc (250 g)                           2957
1 pack (5 pcs)                         2935
1 pc (150 g)                           2933
1 pack (3 pcs)                         2924
1 pc (1 kg)                            2924
1 pc (60 ml)                           2907
1 pack (100 ml)                        2885
1 pack (40 g)                          2805
1 pc (75 g)                            2647
1 pack                                 2615
1 pack (300 g)                         2586
1 pack (30 pcs)                        2356
1 pc (300 g)                           2275
1 pack (20 pcs)                        2236
2 combo                                2222
1 pack (4 pcs)                         2184
1 pack (80 g)                          2122
1 pc (10 ml)                           2116
1 pc (70 ml)                           2060
1 pack (25 pcs)                        1870
1 pc (30 g)                            1825
1 pc (750 ml)                          1800
1 pc (40 ml)                           1796
1 pc (400 g)                           1788
1 pack (12 pcs)                        1750
1 pack (120 g)                         1707
1 pc (110 ml)                          1706
1 pack (70 g)                          1695
1 pack (45 g)                          1677
1 pc (40 g)                            1593
1 pack (25 g)                          1550
1 pc (600 ml)                          1540
1 pc (500 g)                           1535
1 pc (175 ml)                          1507
1 pc (80 ml)                           1486
1 pack (160 g)                         1472
1 pack (20 g)                          1470
1 pack (40 pcs)                        1450
1 pack (75 g)                          1424
1 pc (125 ml)                          1407
1 pc (45 g)                            1373
1 pc (350 g)                           1341
1 pack (180 g)                         1325
1 x 72 pulls                           1298
1 pack (450 g)                         1290
1 pack (10 kg)                         1226
1 pack (140 g)                         1208
1 pack (55 g)                          1198
1 pack (30 g)                          1131
1 pack (350 g)                         1114
1 pack (200 ml)                        1108
1 pack (85 g)                          1100
1 pc (125 g)                           1053
1 pc (170 ml)                          1052
1 pc (4 g)                             1010
1 pc (90 g)                            1009
1 pc (330 ml)                          1006
1 pack (35 g)                           992
1 pc (15 ml)                            987
1 pc (70 g)                             984
62pcs                                   979
1 pack (16 pcs)                         978
1 pack (24 pcs)                         957
1 pc (6 ml)                             947
1 pack (18 pcs)                         918
1 set (3 pcs)                           896
1 pc (225 ml)                           860
1 pack (125 ml)                         850
1 pc (85 g)                             849
1 pc (55 g)                             839
1 pack (800 g)                          802
3 pcs                                   802
100 g                                   792
1 pc (236 ml)                           787
1 pc (75 ml)                            786
1 pack (125 g)                          784
1 set (2 pcs)                           778
50 g                                    767
3 x 72 pulls                            766
1 pc (510 g)                            766
1 pack (450 ml)                         763
250 ml X 2                              758
1 pc (190 ml)                           757
1 pc (35 g)                             755
1 pc (105 ml)                           747
1 pc (230 ml)                           746
1 pc (5 ml)                             742
54pcs                                   720
1 pack (15 pcs)                         706
1 pc (60 g)                             680
1 pc (924 g)                            674
1 pack (28 g)                           671
1 pc (220 ml)                           654
1 pack (5 x 125 g)                      651
1 set (5 pcs)                           647
1 pack (50 pcs)                         646
72pcs                                   627
1 pc (9 ml)                             615
1 pc (10 g)                             607
1 pack (150 ml)                         604
1 pack (25 ml)                          598
1 pc (65 ml)                            597
1 pc (180 g)                            595
100 ml                                  584
1 pc (9 g)                              578
1 pc (20 ml)                            577
1 pc (25 ml)                            570
1 pc (4.5 g)                            570
200 ml                                  569
1 pack (2 x 150 g)                      567
1 pack (77 g)                           557
1 pc (1.2 L)                            550
1 set (7 pcs)                           546
1 pc (120 g)                            545
1 pc (15 g)                             545
1 pc (25 g)                             538
1 pack (65 g)                           535
250 ml                                  527
1 pack (36 pcs)                         519
1 pack (850 g)                          511
2 pcs                                   503
4 pcs                                   499
350 ml                                  494
1 pc (20 g)                             490
150 g + 60 g                            486
1 pack (700 ml)                         486
1 pack (115 ml)                         473
1 pc (190 g)                            470
180 ml                                  470
1 pc (170 g)                            468
1 pc (4.8 g)                            468
1 set (4 pcs)                           465
1 pc (5 L)                              461
1 pack (57 g)                           459
200 g                                   447
1 pc (750 g)                            446
1 pack (4 x 150 g)                      443
1 pack (750 ml)                         435
1 pc (0.35 g)                           434
1 pc (350 ml)                           432
200 ml X 2                              424
1 pack (41 g)                           424
1 pc (8 ml)                             422
1 pc (88 ml)                            420
1 pack (2 kg)                           420
1 pc (90 ml)                            411
1 pc (236 ml or 250 ml)                 408
1 pack (3 x 100 g)                      408
1 pc (2.25 L)                           408
100 g X 2                               407
1 pc (135 ml)                           404
1 pack (144 g)                          404
1 piece                                 398
1 pc (450 g)                            395
1 pack (170 g)                          391
1 pc (12 g)                             391
1 pack (130 g)                          390
1 pair                                  390
1 pc (175 g)                            382
0.35 g                                  382
300 ml                                  380
1 pack (750 g)                          380
1 pack (7 pcs)                          377
2 x 72 pulls                            374
500 ml X 2                              372
1 pack (60 g or 64 g)                   368
5 ml                                    363
1 pc (12 ml)                            362
1 pack (19.8 g)                         359
1 pack (375 g)                          357
1 pack (43 g)                           356
1 pack (240 g)                          355
1 set (8 pcs)                           355
60 ml X 2                               355
1 pc (2 L)                              352
1 pack (600 g)                          347
3 combo                                 339
2 pack (10 pcs)                         335
1 pc (4 ml)                             333
1 kg                                    328
1 pack (275 g)                          327
1 pack (250 ml)                         326
1 pack (100 pcs)                        326
1 pack (52 g)                           323
74pcs                                   318
1 pc (17 g)                             318
1 kg X 2                                316
1 set (4 x 20 ml)                       315
1 set (6 pcs)                           315
500 g                                   314
1 pack (900 g)                          313
1 pack (79 g)                           309
1 pack (8 pcs)                          308
1 pc (240 ml)                           307
1 pc (45 ml)                            307
10 ml X 2                               306
1 pack (142 g)                          305
30 ml                                   305
1 pc (5 g)                              302
1 pack (14 pcs)                         302
1 pack (3 x 40 g)                       301
1 pc (55 ml)                            300
1 x 80 pulls                            299
1 pc (118 ml or 125 ml)                 299
1 set (11 pcs)                          297
1 pc (61 g)                             297
1 pack (44 g)                           293
1 pack (99 g)                           293
1 pack (3 x 150 g)                      292
1.15 kg                                 286
1 pack (3 x 125 g)                      285
1 set (4 x 25 ml)                       284
1 pc (196 ml)                           282
1 pack (4 x 70 g)                       282
1 pack (67.5 g)                         279
5.6 ml                                  279
1.2 kg                                  278
250 ml X 3                              278
1 L X 2                                 276
1 pack (48 g or 52.9 g)                 275
70pcs                                   273
1 pc (245 ml)                           272
1 pc (320 ml)                           271
56pcs                                   270
1 pack (160 g or 171 g)                 269
0.3 g                                   269
1 pc (6 g)                              269
1 pack (38 g)                           267
1 pack (280 g)                          266
1 L X 3                                 265
230 g                                   261
1 pack (168 g)                          261
1 pack (270 g)                          261
1 pack (55 g or 57 g)                   260
70 ml + 60 g                            259
1 pack (90 g)                           259
1 pack (4 x 125 g)                      258
1 pc (18 ml)                            256
1 pack (1.2 kg)                         255
1 pc (35 ml)                            254
1 pc (300 ml or 330 ml)                 253
1 pack (25 x 1.7 g)                     252
1 pc (180 ml or 190 ml)                 252
1 pack (128 g)                          250
1 pc (3 g)                              250
1 pc (3.5 ml)                           247
450 ml                                  245
1 pcs                                   245
1 pc (340 ml)                           245
80 g                                    245
100 g X 3                               243
1 pack (33 g)                           240
1 pack (10 x 10 g)                      239
1 L                                     239
1 pack (8 x 250 ml)                     238
400 g                                   237
1 pack (30.6 g or 28.9 g)               235
1 pc (1.25 kg)                          235
1 pack (2 x 100 ml)                     235
1 pack (69 g)                           234
1 pack (900 ml)                         234
1 pc (340 g)                            233
1 pc (227 g)                            231
1 pack (25 x 2 g)                       230
1 pack (4 x 100 g)                      230
1 pack (210 g)                          229
1 pack (20 g or 16 g)                   228
1 pack (37.5 g)                         227
1 pack (48 g)                           226
1 pack (153 g)                          225
40pcs                                   224
1 pack (415 g)                          222
1 pc (210 g)                            218
1 pc (1.5 L)                            217
1 pack (225 g)                          217
1 pc (4.5 ml)                           212
1 pack (95 g)                           211
1 pack (165 g)                          210
1 pack (110 g)                          210
1 pc (175 ml or 180 ml)                 209
1 pc (280 ml)                           207
1 pack (120 ml)                         207
1 pack (159 g)                          206
1 pc (7 ml)                             206
60 ml X 3                               202
150 g X 2                               201
1 pack (700 g)                          201
1 pack (72 pcs)                         201
1 pack (60 pcs)                         201
1 set (60 g)                            200
1 pc (225 g)                            200
1 pack (6 x 12.5 g)                     200
1 pc (700 g)                            198
250 g X 2                               198
87.5 g + 72 ml                          197
1 pack (34 g)                           196
400g                                    196
1 pc (1.5 g)                            194
30 g                                    194
1 pack (27.3 g or 28.2 g)               193
1 set (9 pcs)                           189
30pcs                                   188
1 pc (100 or 110 g)                     188
1 kg X 3                                188
1 pack (2 x 12.5 g)                     188
1 pack (180 ml)                         187
1 pack (240 pcs)                        186
1 pc (36 g)                             186
260 g                                   184
1 pack (248 g)                          183
1 pc (65 g)                             181
1 pack (110 ml)                         181
3.8 ml                                  179
1 pc (46 g)                             176
1 pack (108 g)                          174
60 g                                    174
1 pc (140 g)                            174
1 kg X 4                                172
1 pack (135 g or 140 g)                 170
1 pack (360 g)                          170
1 set (10 pcs)                          168
1 pc (600 g)                            168
1 pc (1 ml)                             167
1 pc (354 ml)                           167
1 pc (110 g)                            166
70 ml X 2                               165
180 g                                   165
400 g X 2                               164
1 pack (32 g)                           164
20 pc X 2                               164
32pcs                                   164
1 pack (950 g)                          163
1 pack (22 g)                           161
5 x 72 pulls                            161
1 pack (5 x 100 g)                      161
1 pack (67 g)                           161
200 g X 2                               160
500 g X 2                               160
1 pack (20 ml)                          158
70 g                                    158
1 pc (8 g)                              158
1 pack (70 g or 100 g)                  157
1 pack (6 Sachets)                      157
1 pack (16 g)                           155
1 pc (63 g)                             155
55 g X 2                                155
1 pack (88 g)                           154
1 pack (0.5 g)                          153
1 Pack (40 g)                           153
1 pack (120 g or 150 g)                 152
1 pack (59.4 g)                         152
1 pack (42 g)                           152
1 pack (62.5 g)                         151
1 x 60 pulls                            151
1 pack (170 ml)                         150
1 pc (380 g)                            150
1 set (6 pack)                          149
1 pack (70 g or 75 g)                   149
1 pc (100 ml or 118 ml)                 149
1 pc (80 g or 100 g)                    149
144 g X 2                               149
1 pack (48 pcs)                         147
1 pack (10 x 20 g)                      147
1 pc (355 ml)                           147
3 x 75 g                                147
1 pack (75 g or 80 g)                   147
1 pack (80 ml)                          147
1 pack (56 g)                           146
1 pack (285 g)                          146
1 pc (56 g)                             146
1 pack (295 g)                          145
52pcs                                   145
1 pack (150 g + 60 g)                   145
1 pack (100 g or 112 g)                 145
1 pc (150 g + 60 g)                     145
1 pc (500 ml or 473 ml)                 145
1 pack (4 x 75 g)                       145
1 pack (188 g)                          145
1 pack (696 g)                          144
2 x 225 g                               144
1 pack (183 g)                          144
1 pack (29.7g)                          144
1 pack (100 g or 115.5 g)               144
1 pc (27.5 g or 30 g)                   144
1 pack (172 g)                          144
1 pack (250 ml or 300 ml)               144
1 pc (78 g)                             144
1 pack (29.7 g)                         144
1 pc (62 g)                             143
1 pack (172 ml)                         143
2 x 25 g + 25 ml                        143
1 pc (18 g)                             143
1 pc (825 ml)                           143
80g                                     143
120 g X 2                               143
1 pack (475 g)                          143
10 x 1.3 g                              143
1 pack (91.7 g or 100 g)                143
7 pack (140 g)                          142
1 pack (24 x 250 ml)                    142
1 pack (371.2 g)                        142
1 pack (4 x 250 ml)                     142
1 Pack(350 g)                           142
1 pack (960 g)                          142
1 pack(30 pcs)                          141
1 pack (66.6 or 75 g)                   141
64pcs                                   141
2 x 150 g                               141
1 pack (585 g)                          141
1 pack (9 pcs)                          141
44pcs                                   141
1 pack (52.9 g or 58 g)                 141
1000 ml                                 141
21 g + 24 ml                            141
1 pc (47 g or 50 g)                     140
1 pack (145 g)                          140
200 ml X 3                              140
1 pack (251 g or 275 g)                 140
1 pc (45 or 48.5 g)                     140
1 pack (50 or 55 g)                     140
1 pc (72 g)                             140

In [13]:
df[df["net_quantity"] == "PCS"]

,crawl_date_and_time,platform_name,store_id,store_name_location,city,pin_code,unique_id,product_id_upc_ean,department,category,sub_category,product_type,brand_name,product_name,product_description,product_grammage,package_type,net_quantity,variants,item_mrp,item_selling_price,out_of_stock_flag,discount_flag,product_price,unit_price,promo_offer_description,promo_offer_price,discount_in_percent,stock_count,product_url,product_image_urls
220920,2026-07-15 03:07:18,zepto,e879c6cf-e4bd-4b11-a605-4e9b2ee2365d,"Pride Plaza Hotel Kolkata, Service Rd, Opposite To Novotel, BG Block(newtown), Action Area I, NewTown, New Town, West Bengal, 700156, India",Kolkata,700156,2f3d223e-8924-40f2-a49e-2a00799236f7,ca59e965-9adc-4250-9d30-88cda96617ab,Personal Care,Electronics & Appliances,Grooming,NaN,Pro touch,PROTOUCH All Rounder Womens Trimmer Epilator Face Body Portable Rechargeable,NaN,NaN,NaN,PCS,NaN,2899.0,1998.0,No,Yes,1998.0,NaN,₹901 OFF,1998.0,31,1,https://www.zepto.com/pn/protouch-all-rounder-womens-trimmer-epilator-face-body-portable-rechargeable/pvid/2f3d223e-8924-40f2-a49e-2a00799236f7,NaN

In [14]:
df[df.item_mrp.isna()]

,crawl_date_and_time,platform_name,store_id,store_name_location,city,pin_code,unique_id,product_id_upc_ean,department,category,sub_category,product_type,brand_name,product_name,product_description,product_grammage,package_type,net_quantity,variants,item_mrp,item_selling_price,out_of_stock_flag,discount_flag,product_price,unit_price,promo_offer_description,promo_offer_price,discount_in_percent,stock_count,product_url,product_image_urls
472629,2026-07-15 05:05:08,zepto,4ab9ad5d-75ba-4cca-93cd-9f40062825c7,"Riya Men's PG, No14, Padmavathi Avenue, Near World Trade Centre, Phase-2, Thirumalai Nagar Annexe, Perungudi, Chennai, Tamil Nadu, 600096, India",Chennai,600096,d406cf5c-3cdc-4d17-ae3d-e5b8005682cc,b8c514bd-1079-4d6e-a0d1-a84ee0e47384,Dairy & Breakfast,"Dairy, Bread & Eggs",Batters & Mixes,NaN,iD Fresh,Id Idli & Dosa Batter (1kg) & Id Fresh Liquid Sambar (Heat & Eat) (350g) Combo,NaN,NaN,NaN,2 combo,NaN,NaN,0.0,Yes,No,0.0,NaN,No offer,0.0,0,0,https://www.zepto.com/pn/id-idli-dosa-batter-1kg-id-fresh-liquid-sambar-heat-eat-350g-combo/pvid/d406cf5c-3cdc-4d17-ae3d-e5b8005682cc,NaN

In [15]:
city_department = pd.crosstab(df["city"], df["department"])

city_department

department,"Atta, Rice & Dal",Baby Care,Bakery & Biscuits,Beauty & Cosmetics,Cold Drinks & Juices,Dairy & Breakfast,Munchies,Organic & Premium,Personal Care,Sweet Tooth
city,,,,,,,,,,
Agra,155,345,263,584,287,303,189,407,418,244
Ahmedabad,476,1327,792,1797,911,1266,573,1118,1540,807
Bangalore,4940,20307,9243,20520,10676,13544,5706,13745,19247,8793
Barasat,114,321,245,488,255,362,182,362,383,228
Bareilly,160,451,305,662,312,329,160,409,502,283
Bhiwadi,160,400,319,650,319,451,192,420,463,271
Chennai,2336,7255,4509,8938,5122,6730,2970,6213,8483,4587
Coimbatore,312,911,604,1325,671,815,384,827,981,630
Dehradun,126,371,272,597,309,325,189,413,460,296
Faridabad,149,332,275,549,301,364,191,399,441,266
Greater Noida,160,814,299,541,386,456,190,424,692,309
Haridwar,160,609,320,744,355,311,191,419,517,282
Hubballi,160,462,295,617,360,402,186,415,505,303
Hyderabad,2639,10328,5048,11411,6014,7711,3161,7436,10128,5242
Indore,634,1715,1123,2549,1257,1425,767,1611,1881,1167
Jalandhar,149,362,239,616,284,336,192,402,468,225
Karnal,158,470,301,637,355,417,187,409,501,311
Kochi,314,876,605,1242,669,843,382,869,1031,600
Kolkata,927,3594,2075,4409,2454,2900,1336,2908,3439,1842
Kota,146,382,252,590,254,309,191,402,439,297
Madurai,157,459,261,631,309,363,189,406,495,285
Mumbai,2545,8354,5035,10883,6495,7916,3182,7587,9621,5043
Mysuru,477,1420,905,1995,1014,1222,572,1257,1466,912
Nagpur,478,1350,841,1923,1026,1131,576,1258,1465,887
Nashik,320,890,620,1344,677,731,376,811,1062,617
Panipat,159,444,310,662,299,364,192,417,510,278
Patiala,159,445,298,665,300,399,190,407,528,296
Prayagraj,311,697,498,1118,549,523,381,783,806,533
Pune,2008,6947,3886,7891,4256,5780,2459,5440,7624,3871
S.A.S Nagar,150,368,281,509,332,429,161,426,487,312
Sonipat,160,533,320,721,383,452,190,419,554,319
Surat,628,1940,1152,2552,1254,1485,765,1579,2034,1260
Udaipur,160,476,302,691,290,402,191,400,506,314
Vijayawada,160,475,279,659,345,370,191,415,513,300

In [16]:
### city wise category distribution
city_category = pd.crosstab(df["city"], df["category"])

# Cities where any category is missing
missing_categories = city_category[city_category.eq(0).any(axis=1)]

missing_categories

category,"Atta, Rice, Oil & Dals",Baby Care,Bath & Body,Biscuits,Breakfast & Sauces,Cold Drinks & Juices,"Dairy, Bread & Eggs",Electronics & Appliances,Feminine Hygiene,Fragrances & Grooming,Frozen Food,Hair Care,Ice Creams & More,Makeup & Beauty,"Masala, Dry Fruits & More",Munchies,Packaged Food,Pharma & Wellness,Skincare,Sweet Cravings,"Tea, Coffee & More",Toys & Sports,Zepto Cafe
city,,,,,,,,,,,,,,,,,,,,,,,
Bareilly,230,238,220,210,160,235,171,29,144,94,0,192,219,163,129,187,160,2,330,146,127,185,2
Bhiwadi,234,186,219,223,160,192,288,9,137,90,30,187,238,161,130,221,164,0,318,148,128,180,2
Haridwar,233,319,233,224,160,253,155,12,150,99,0,193,243,191,128,218,163,4,391,150,128,259,2
Kota,213,190,194,177,160,175,139,5,134,86,25,178,209,121,128,192,159,0,310,173,127,165,2
Panipat,231,247,237,221,160,219,173,13,144,84,31,186,222,177,128,219,156,0,328,146,128,183,2

In [17]:
city_category = pd.crosstab(df["city"], df["category"])

print(city_category)

category       Atta, Rice, Oil & Dals  Baby Care  Bath & Body  Biscuits  \
city
Agra                              231        174          192       192
Ahmedabad                         696        650          638       595
Bangalore                        7672       9315         8035      6303
Barasat                           168        151          172       156
Bareilly                          230        238          220       210
Bhiwadi                           234        186          219       223
Chennai                          3677       3704         3719      3045
Coimbatore                        460        484          434       448
Dehradun                          200        198          218       188
Faridabad                         223        152          203       183
Greater Noida                     254        383          287       204
Haridwar                          233        319          233       224
Hubballi                          232        239          227       219
Hyderabad                        4156       5059         4184      3463
Indore                            910        858          819       791
Jalandhar                         218        201          208       155
Karnal                            228        258          222       207
Kochi                             475        492          425       421
Kolkata                          1375       1673         1438      1404
Kota                              213        190          194       177
Madurai                           229        243          233       188
Mumbai                           4044       4415         3849      3492
Mysuru                            703        661          690       626
Nagpur                            705        610          669       617
Nashik                            466        459          457       432
Panipat                           231        247          237       221
Patiala                           228        244          227       202
Prayagraj                         444        375          386       340
Pune                             3162       3474         3298      2691
S.A.S Nagar                       221        204          214       192
Sonipat                           232        248          240       224
Surat                             901       1039          895       787
Udaipur                           229        252          224       222
Vijayawada                        233        230          225       203

category       Breakfast & Sauces  Cold Drinks & Juices  Dairy, Bread & Eggs  \
city
Agra                          159                   207                   97
Ahmedabad                     473                   621                  767
Bangalore                    4905                  7405                 8392
Barasat                       144                   182                  194
Bareilly                      160                   235                  171
Bhiwadi                       160                   192                  288
Chennai                      2217                  3630                 4302
Coimbatore                    318                   508                  425
Dehradun                      160                   215                  132
Faridabad                     115                   216                  228
Greater Noida                 155                   231                  307
Haridwar                      160                   253                  155
Hubballi                      158                   253                  201
Hyderabad                    2670                  3945                 5138
Indore                        640                   907                  645
Jalandhar                     160                   213                  140
Karnal                        157                   252                  232
Kochi                         316                   492                  471
Kolkata                      1120                  1627                 1758
Kota                          160                   175                  139
Madurai                       159                   234                  162
Mumbai                       2649                  4095                 5230
Mysuru                        480                   696                  673
Nagpur                        479                   724                  511
Nashik                        312                   480                  378
Panipat                       160                   219                  173
Patiala                       158                   223                  217
Prayagraj                     302                   393                  211
Pune                         2054                  2819                 3617
S.A.S Nagar                   155                   237                  252
Sonipat                       160                   253                  291
Surat                         640                   940                  740
Udaipur                       160                   211                  205
Vijayawada                    158                   247                  162

category       Electronics & Appliances  Feminine Hygiene  \
city
Agra                                  4               124
Ahmedabad                            61               444
Bangalore                           714              4832
Barasat                               2                99
Bareilly                             29               144
Bhiwadi                               9               137
Chennai                             330              1977
Coimbatore                           24               281
Dehradun                              4               133
Faridabad                             6               132
Greater Noida                        32               164
Haridwar                             12               150
Hubballi                             29               138
Hyderabad                           384              2634
Indore                               35               543
Jalandhar                             6               140
Karnal                               17               144
Kochi                                38               300
Kolkata                             141               912
Kota                                  5               134
Madurai                              10               136
Mumbai                              356              2312
Mysuru                               61               404
Nagpur                               60               414
Nashik                               28               307
Panipat                              13               144
Patiala                              15               148
Prayagraj                            10               235
Pune                                246              1924
S.A.S Nagar                          12               143
Sonipat                              32               146
Surat                                52               584
Udaipur                              11               144
Vijayawada                           22               141

category       Fragrances & Grooming  Frozen Food  Hair Care  \
city
Agra                              86           25        177
Ahmedabad                        298           89        495
Bangalore                       2936          727       5324
Barasat                           68           30        140
Bareilly                          94            0        192
Bhiwadi                           90           30        187
Chennai                         1289          207       2493
Coimbatore                       212           62        359
Dehradun                          92           29        167
Faridabad                         88           24        175
Greater Noida                     94           22        154
Haridwar                          99            0        193
Hubballi                          94           31        179
Hyderabad                       1725          387       2922
Indore                           347          117        736
Jalandhar                         91           26        174
Karnal                            99           30        170
Kochi                            201           60        336
Kolkata                          656          216       1156
Kota                              86           25        178
Madurai                           97           28        189
Mumbai                          1812          492       2657
Mysuru                           291           90        548
Nagpur                           296           87        520
Nashik                           201           31        360
Panipat                           84           31        186
Patiala                           93           28        184
Prayagraj                        119            2        338
Pune                            1157          369       2197
S.A.S Nagar                       87           27        153
Sonipat                          120           32        190
Surat                            433          117        629
Udaipur                          101           27        189
Vijayawada                        89           30        182

category       Ice Creams & More  Makeup & Beauty  Masala, Dry Fruits & More  \
city
Agra                         200              131                        123
Ahmedabad                    643              476                        294
Bangalore                   6933             4871                       3813
Barasat                      178              141                        122
Bareilly                     219              163                        129
Bhiwadi                      238              161                        130
Chennai                     3510             1836                       1903
Coimbatore                   444              338                        259
Dehradun                     221              164                        128
Faridabad                    201              144                        127
Greater Noida                237              138                        127
Haridwar                     243              191                        128
Hubballi                     238              176                        124
Hyderabad                   4198             2911                       2085
Indore                       871              594                        515
Jalandhar                    166              147                        127
Karnal                       243              163                        128
Kochi                        448              347                        252
Kolkata                     1502             1164                        890
Kota                         209              121                        128
Madurai                      193              140                        128
Mumbai                      3973             2726                       2136
Mysuru                       718              512                        389
Nagpur                       734              499                        389
Nashik                       490              349                        256
Panipat                      222              177                        128
Patiala                      211              172                        128
Prayagraj                    371              251                        244
Pune                        2809             1801                       1668
S.A.S Nagar                  219              103                        122
Sonipat                      247              187                        128
Surat                        941              575                        505
Udaipur                      225              168                        129
Vijayawada                   243              180                        130

category       Munchies  Packaged Food  Pharma & Wellness  Skincare  \
city
Agra                218            159                  2       282
Ahmedabad           652            392                 12       932
Bangalore          6721           5294                 77     13146
Barasat             210            143                  3       249
Bareilly            187            160                  2       330
Bhiwadi             221            164                  0       318
Chennai            3488           1892                 32      5709
Coimbatore          442            326                  4       660
Dehradun            221            147                  5       282
Faridabad           219            134                  2       244
Greater Noida       220            178                  4       338
Haridwar            218            163                  4       391
Hubballi            219            161                  2       280
Hyderabad          3700           2690                 51      6741
Indore              871            621                  8      1314
Jalandhar           221            160                  2       309
Karnal              217            157                  3       324
Kochi               438            324                  7       628
Kolkata            1538           1129                 22      2395
Kota                192            159                  0       310
Madurai             218            158                  1       320
Mumbai             3689           2674                 58      6751
Mysuru              656            474                  9       967
Nagpur              659            480                  3       922
Nashik              434            309                  6       703
Panipat             219            156                  0       328
Patiala             221            153                  2       351
Prayagraj           434            316                  6       583
Pune               2823           2051                 32      4750
S.A.S Nagar         190            156                  3       290
Sonipat             218            172                  3       366
Surat               856            638                 12      1414
Udaipur             216            161                  2       357
Vijayawada          215            163                  2       326

category       Sweet Cravings  Tea, Coffee & More  Toys & Sports  Zepto Cafe
city
Agra                      139                 123            148           2
Ahmedabad                 341                 366            588          84
Bangalore                5124                3779           9761         642
Barasat                   131                 117            138           2
Bareilly                  146                 127            185           2
Bhiwadi                   148                 128            180           2
Chennai                  2802                1709           3348         324
Coimbatore                340                 255            371           6
Dehradun                  178                 124            150           2
Faridabad                 162                 121            166           2
Greater Noida             176                 126            412          28
Haridwar                  150                 128            259           2
Hubballi                  179                 126            198           2
Hyderabad                2908                2075           4764         328
Indore                    683                 510            784          10
Jalandhar                 144                 124            139           2
Karnal                    180                 124            189           2
Kochi                     352                 250            323          35
Kolkata                  1005                 889           1671         203
Kota                      173                 127            165           2
Madurai                   168                 125            194           2
Mumbai                   2865                2065           3470         851
Mysuru                    534                 380            671           7
Nagpur                    508                 382            659           8
Nashik                    358                 250            376           6
Panipat                   146                 128            183           2
Patiala                   175                 127            178           2
Prayagraj                 325                 238            272           4
Pune                     1958                1588           3249         425
S.A.S Nagar               170                 122            125          58
Sonipat                   181                 128            251           2
Surat                     672                 496            772          11
Udaipur                   172                 127            198           2
Vijayawada                176                 127            220           3

In [18]:
dept_category = (
    df.groupby("department")["category"]
    .apply(lambda x: sorted(x.unique()))
    .reset_index()
)

dept_category

,department,category
0,"Atta, Rice & Dal","[Atta, Rice, Oil & Dals]"
1,Baby Care,"[Baby Care, Dairy, Bread & Eggs, Packaged Food, Pharma & Wellness, Toys & Sports]"
2,Bakery & Biscuits,"[Biscuits, Dairy, Bread & Eggs, Packaged Food, Sweet Cravings]"
3,Beauty & Cosmetics,"[Fragrances & Grooming, Hair Care, Makeup & Beauty, Skincare]"
4,Cold Drinks & Juices,"[Cold Drinks & Juices, Dairy, Bread & Eggs, Ice Creams & More, Packaged Food, Pharma & Wellness, Tea, Coffee & More, Zepto Cafe]"
5,Dairy & Breakfast,"[Breakfast & Sauces, Cold Drinks & Juices, Dairy, Bread & Eggs, Frozen Food, Munchies, Packaged Food]"
6,Munchies,"[Biscuits, Masala, Dry Fruits & More, Munchies, Packaged Food]"
7,Organic & Premium,"[Atta, Rice, Oil & Dals, Biscuits, Breakfast & Sauces, Masala, Dry Fruits & More, Munchies, Packaged Food, Sweet Cravings, Tea, Coffee & More, Zepto Cafe]"
8,Personal Care,"[Baby Care, Bath & Body, Electronics & Appliances, Feminine Hygiene, Fragrances & Grooming, Skincare]"
9,Sweet Tooth,"[Bath & Body, Biscuits, Dairy, Bread & Eggs, Frozen Food, Ice Creams & More, Munchies, Packaged Food, Sweet Cravings]"

In [19]:
master = df[["department", "category"]].drop_duplicates()
city_stock = (
    df.groupby("city")["out_of_stock_flag"]
    .value_counts()
    .unstack(fill_value=0)
)

city_stock["Total"] = city_stock.sum(axis=1)
city_stock["Out_of_stock_%"] = (
    city_stock["Yes"] / city_stock["Total"] * 100
).round(2)

city_stock.sort_values("Out_of_stock_%", ascending=False)

out_of_stock_flag      No    Yes   Total  Out_of_stock_%
city
Vijayawada           2407   1300    3707           35.07
Greater Noida        2914   1357    4271           31.77
Chennai             40734  16409   57143           28.72
Mumbai              48324  18337   66661           27.51
S.A.S Nagar          2535    920    3455           26.63
Ahmedabad            7820   2787   10607           26.28
Nashik               5612   1836    7448           24.65
Pune                39119  11043   50162           22.01
Prayagraj            4845   1354    6199           21.84
Kolkata             20285   5599   25884           21.63
Hyderabad           54300  14818   69118           21.44
Kochi                5851   1580    7431           21.26
Madurai              2808    747    3555           21.01
Coimbatore           6013   1447    7460           19.40
Surat               11860   2789   14649           19.04
Udaipur              3025    707    3732           18.94
Hubballi             3020    685    3705           18.49
Faridabad            2695    572    3267           17.51
Bangalore          104671  22050  126721           17.40
Indore              11823   2306   14129           16.32
Patiala              3136    551    3687           14.94
Bareilly             3055    518    3573           14.50
Nagpur               9367   1568   10935           14.34
Panipat              3137    498    3635           13.70
Mysuru               9722   1518   11240           13.51
Karnal               3246    500    3746           13.35
Jalandhar            2868    405    3273           12.37
Sonipat              3572    479    4051           11.82
Kota                 2907    355    3262           10.88
Dehradun             2998    360    3358           10.72
Bhiwadi              3262    383    3645           10.51
Haridwar             3543    365    3908            9.34
Barasat              2758    182    2940            6.19
Agra                 3087    108    3195            3.38

In [20]:
dept_stock = (
    df.groupby("department")["out_of_stock_flag"]
    .value_counts()
    .unstack(fill_value=0)
)

dept_stock["Total"] = dept_stock.sum(axis=1)
dept_stock["Out_of_stock_%"] = (
    dept_stock["Yes"] / dept_stock["Total"] * 100
).round(2)

dept_stock.sort_values("Out_of_stock_%", ascending=False)

out_of_stock_flag        No    Yes  Total  Out_of_stock_%
department
Personal Care         61139  19051  80190           23.76
Baby Care             58306  18124  76430           23.71
Bakery & Biscuits     32901   9471  42372           22.35
Dairy & Breakfast     47735  13431  61166           21.96
Cold Drinks & Juices  38366  10714  49080           21.83
Organic & Premium     48911  12302  61213           20.10
Beauty & Cosmetics    74103  17607  91710           19.20
Sweet Tooth           34166   8044  42210           19.06
Atta, Rice & Dal      18338   3909  22247           17.57
Munchies              23354   3780  27134           13.93

In [21]:

cat_stock = (
    df.groupby("category")["out_of_stock_flag"]
    .value_counts()
    .unstack(fill_value=0)
)

cat_stock["Total"] = cat_stock.sum(axis=1)
cat_stock["Out_of_stock_%"] = (
    cat_stock["Yes"] / cat_stock["Total"] * 100
).round(2)

cat_stock.sort_values("Out_of_stock_%", ascending=False)

out_of_stock_flag             No    Yes  Total  Out_of_stock_%
category
Zepto Cafe                   441   2624   3065           85.61
Electronics & Appliances    1701   1109   2810           39.47
Pharma & Wellness            265    116    381           30.45
Dairy, Bread & Eggs        26108  10896  37004           29.45
Fragrances & Grooming       9936   3789  13725           27.61
Baby Care                  28008   9617  37625           25.56
Feminine Hygiene           15779   4965  20744           23.93
Sweet Cravings             18312   5557  23869           23.28
Toys & Sports              26726   8031  34757           23.11
Makeup & Beauty            17254   4963  22217           22.34
Biscuits                   22875   6370  29245           21.78
Skincare                   42870  10740  53610           20.03
Bath & Body                27662   6469  34131           18.95
Cold Drinks & Juices       27219   6311  33530           18.82
Atta, Rice, Oil & Dals     27727   6386  34113           18.72
Hair Care                  19903   4526  24429           18.53
Ice Creams & More          26787   5951  32738           18.18
Packaged Food              18827   3787  22614           16.75
Masala, Dry Fruits & More  15027   2985  18012           16.57
Frozen Food                 2947    581   3528           16.47
Munchies                   26576   4885  31461           15.53
Breakfast & Sauces         19244   3289  22533           14.60
Tea, Coffee & More         15125   2486  17611           14.12

In [22]:
store_oos = (
    df.pivot_table(
        index=["city", "store_id"],
        columns="out_of_stock_flag",
        aggfunc="size",
        fill_value=0
    )
    .reset_index()
)

# Ensure both columns exist
for col in ["Yes", "No"]:
    if col not in store_oos.columns:
        store_oos[col] = 0

store_oos["Total"] = store_oos["Yes"] + store_oos["No"]
store_oos["Out_of_stock_%"] = (
    store_oos["Yes"] / store_oos["Total"] * 100
).round(2)

store_oos = store_oos.sort_values(
    "Out_of_stock_%",
    ascending=False
)

store_oos

out_of_stock_flag,city,store_id,No,Yes,Total,Out_of_stock_%
143,Mumbai,37b900f0-25c0-448b-825a-74d62c8ceb41,385,369,754,48.94
77,Chennai,a98f0f81-73ab-4839-8d06-4e9427680054,1952,1630,3582,45.51
137,Mumbai,1b11ac6b-6de6-411b-80bf-a72874a80c51,1937,1455,3392,42.90
71,Chennai,691e4cd7-b08a-421b-a35d-6c89173b796e,2014,1403,3417,41.06
112,Hyderabad,d54cc989-bc58-4cb9-9c2e-3a3468546c3f,2094,1449,3543,40.90
87,Greater Noida,848cd607-f42d-42aa-b7d8-09241fe84d14,815,554,1369,40.47
81,Chennai,fb0d381c-e38f-4bcc-a5f8-872e3e033e62,2188,1443,3631,39.74
159,Mumbai,cc72f206-e146-43c5-a01b-56ddc8d11464,2073,1314,3387,38.80
151,Mumbai,751c003c-bbe4-453d-ae3d-404380528149,1129,668,1797,37.17
196,Pune,fe4a16ca-6c7c-4f1a-88a7-fecda52d8057,2292,1319,3611,36.53
76,Chennai,86ec9fc6-ed4b-4674-8175-68c88c75c16f,2260,1257,3517,35.74
136,Mumbai,18c249b1-83ec-4088-9680-686d57883dee,775,431,1206,35.74
2,Ahmedabad,863ee650-1df1-418c-a988-2a64f2c555e3,2272,1242,3514,35.34
205,Vijayawada,471b6b1b-6289-47bf-ac72-a61684f86181,2407,1300,3707,35.07
78,Chennai,aa16c37d-46a9-4e32-84b3-0e2401bd196f,2349,1242,3591,34.59
176,Prayagraj,28868283-c2ed-433d-bf3b-f968b5eeef8a,1789,925,2714,34.08
113,Hyderabad,de95e00b-0ebf-4f65-8f27-df66fd91dc13,638,329,967,34.02
153,Mumbai,8a278c72-1366-4926-b81e-ecc6e64df2a7,681,327,1008,32.44
133,Kolkata,e879c6cf-e4bd-4b11-a605-4e9b2ee2365d,400,192,592,32.43
145,Mumbai,4a54d5f5-0bd9-4b8f-b08a-120d8e7926d7,2226,1054,3280,32.13
150,Mumbai,72655f9e-d9be-4b01-b2ac-62e61d2efd47,2273,1075,3348,32.11
33,Bangalore,75946a5e-942e-4db1-9e7c-5fe2eb85088b,2128,977,3105,31.47
70,Chennai,65833924-5a42-4378-9556-8d10945f5a37,2479,1129,3608,31.29
154,Mumbai,8be2198a-76dd-42c7-a351-d1c2b80d459e,1789,798,2587,30.85
164,Mumbai,fdc84bec-ec86-4b5d-b18b-84daca52c609,2560,1134,3694,30.70
126,Kolkata,0af692ee-167f-4903-bf7c-959643e47899,2407,1053,3460,30.43
86,Greater Noida,5cc22671-70e0-4077-8f1c-5502c2c5522b,1357,593,1950,30.41
142,Mumbai,2e7ec440-fd1b-441e-90ee-9c8611648bb6,2272,988,3260,30.31
116,Hyderabad,f275b3c5-5538-46b4-940f-82d9358dba84,2620,1115,3735,29.85
163,Mumbai,f860ca85-ea81-46eb-9448-1de0226aa0fe,2101,870,2971,29.28
67,Chennai,4ab9ad5d-75ba-4cca-93cd-9f40062825c7,2550,1056,3606,29.28
72,Chennai,6db09732-73a0-424c-b528-1778ad7ba7e5,2064,814,2878,28.28
79,Chennai,b4d53703-4b49-4a38-85ca-7e321d1d5222,2005,788,2793,28.21
64,Chennai,1669ccf3-23b3-4ba3-b5c5-8a984549717c,1978,772,2750,28.07
75,Chennai,7fbf2dd5-101c-4f92-802d-728264804add,2611,1010,3621,27.89
27,Bangalore,6047c8fe-15ed-4c61-8d3e-060e800702f5,2609,996,3605,27.63
149,Mumbai,662012a6-9b5c-4471-8051-f83675b0d84c,2370,898,3268,27.48
66,Chennai,2699f532-61f3-431f-aab3-db586ec14085,2583,979,3562,27.48
172,Nashik,da931d01-2519-4d80-89ae-9d74dbb71918,2684,1011,3695,27.36
127,Kolkata,17532e16-28d2-4271-bbac-c48b9b3f8dd1,2662,974,3636,26.79
96,Hyderabad,43b12c97-dc99-431a-9ba3-e3cde9c716bb,2702,987,3689,26.76
197,S.A.S Nagar,2bf9f3ff-7b68-4ac5-a814-1059b71840cf,2535,920,3455,26.63
146,Mumbai,5116a0c5-42bc-487c-ac82-37af432606b0,2238,808,3046,26.53
155,Mumbai,95d6c1a2-b071-4cf3-a322-30b5754d7cb6,723,261,984,26.52
185,Pune,60252717-a8c5-4891-9b23-3db778b14477,391,141,532,26.50
54,Bangalore,e044093d-2a02-4fd7-a1e9-5542edbe746a,2223,797,3020,26.39
95,Hyderabad,33a1d02e-1bb7-44cc-8d38-9697bcc23dba,897,316,1213,26.05
188,Pune,7fe0f5bc-d9c2-4883-b9c2-35fc8f36e1c1,2610,912,3522,25.89
138,Mumbai,1cf40b2e-95cd-4581-9ab9-bca81d4932ab,987,342,1329,25.73
1,Ahmedabad,1105d3fb-0556-4f7e-bd83-416274e9924a,2715,938,3653,25.68
190,Pune,a6aaf608-0a95-47fd-a981-a52d1a5e5e2a,2540,868,3408,25.47
186,Pune,74dfeece-0ec5-4b41-a83b-576add66078e,2412,816,3228,25.28
92,Hyderabad,26ec9b6b-b566-4f36-b5dd-eb6fb92a0caf,2489,836,3325,25.14
148,Mumbai,5f267ad5-446b-4a8b-86f0-df174ad545dd,2378,798,3176,25.13
184,Pune,4cc5f8ae-6495-44d0-9212-b63fe11a3af5,2710,906,3616,25.06
124,Kochi,1dfb0f79-3c66-45e8-8b24-9d79ab1b2477,2791,928,3719,24.95
110,Hyderabad,b32bcacd-f047-47c1-a3b8-c1ccacf364a8,2756,906,3662,24.74
48,Bangalore,c48dd700-4314-4cc1-bffa-e1344e0298dc,2371,774,3145,24.61
157,Mumbai,b54c01f1-4f46-47d6-a3e7-bd040d3e8548,2414,774,3188,24.28
107,Hyderabad,ab5ca9c7-151c-45c6-97df-5a4844e981ea,2534,803,3337,24.06
65,Chennai,1e32417a-1c1c-4f1c-972e-9852a27904d0,2355,715,3070,23.29
34,Bangalore,76cae5a0-b75d-456b-9aab-df0b0b7559c2,1210,365,1575,23.17
100,Hyderabad,67ec5278-78c4-4654-b67d-c0433f5406c7,2428,731,3159,23.14
9,Bangalore,0cde9637-ca43-45b6-a89c-08c1e32bae57,1659,491,2150,22.84
104,Hyderabad,83e33858-a13f-4c67-a016-07de0cce8043,2548,747,3295,22.67
139,Mumbai,2175898f-b70e-46d9-8def-aba7f0745662,826,241,1067,22.59
30,Bangalore,6b1d82f8-b2ea-4e43-ae70-6f6bca1ec77a,1122,325,1447,22.46
52,Bangalore,cf384ecd-5e1f-47e9-9194-8e9dc940e8c3,2502,710,3212,22.10
160,Mumbai,d431e3b5-0ba8-4823-8c4b-c4ea0909dbde,2504,710,3214,22.09
88,Greater Noida,fc05177a-ca9e-4c93-9811-dbb101b0c8f7,742,210,952,22.06
94,Hyderabad,314533d4-8bd7-4985-8ca5-9b737431149b,2878,814,3692,22.05
171,Nashik,bc299560-8f6b-43ba-b146-879f3594ea7e,2928,825,3753,21.98
23,Bangalore,4e507e91-6be7-4f3c-8dfe-aaa051a6d0c8,2234,628,2862,21.94
187,Pune,7a75116f-d14e-49b3-bfde-a6c2a4d180a7,1013,284,1297,21.90
194,Pune,e9da3e70-081c-4c4d-abad-5d88303ced92,2375,658,3033,21.69
177,Pune,231186c7-f3b9-4b6e-9e17-f29a217c4de8,2511,689,3200,21.53
147,Mumbai,52278321-e20a-4a88-b24c-613fafa720e0,2586,708,3294,21.49
42,Bangalore,a09f04ca-3c1d-4523-8606-386ce213a7ae,2514,669,3183,21.02
135,Madurai,b91aec1b-7f2b-45a0-b047-bf7750d4d193,2808,747,3555,21.01
130,Kolkata,9cc80a80-f39d-4da4-9ce6-14fad42e470e,2914,774,3688,20.99
41,Bangalore,9fb087cf-076d-40a0-b974-8d26eaa69f44,2521,669,3190,20.97
63,Chennai,0f63c763-901b-4a64-8c53-da415735616b,2825,749,3574,20.96
82,Coimbatore,4942530d-03e3-44f5-ba28-30c05c238e24,2955,770,3725,20.67
36,Bangalore,7de4838b-ae7c-44d0-bf24-fb2040666654,2542,659,3201,20.59
37,Bangalore,843e630a-7896-462d-b7cf-712140483ed3,1146,297,1443,20.58
202,Surat,d2020a3b-0420-4886-8c55-3128f6a3f592,2879,742,3621,20.49
181,Pune,3a15115a-c99e-4421-bfcc-5b97a2716da5,2585,659,3244,20.31
203,Surat,e7cfb807-6977-42cb-90de-2a3a2527d6c3,2732,693,3425,20.23
182,Pune,3c8e6f2e-5b5d-4654-8e41-a1e0109e3972,2593,656,3249,20.19
47,Bangalore,b4dc8d65-ed2e-4142-81b6-373982b13500,2420,612,3032,20.18
141,Mumbai,291264cf-55b8-4ae3-93b2-cb23fd795054,2598,656,3254,20.16
18,Bangalore,376dd638-f05e-4171-b4e1-b97650b79fe7,341,85,426,19.95
20,Bangalore,40382f4d-61eb-4e99-9a0f-201fd9926f40,2566,634,3200,19.81
14,Bangalore,1c9e155e-83a8-457a-a687-01eabb1e7a36,1159,286,1445,19.79
178,Pune,252ed3f4-d99b-4793-951e-ae673cb9ebbf,2524,621,3145,19.75
8,Bangalore,07a6d7c0-aea9-434c-846e-9308e495db6a,1144,274,1418,19.32
24,Bangalore,4f54ea62-0269-4b93-87cd-ef7ed796c6b1,2544,609,3153,19.31
132,Kolkata,da5b2eac-c339-43fa-a59b-b153f2603b9c,2998,715,3713,19.26
40,Bangalore,992bee8f-8936-4b04-9d17-546cd0ba1b76,1149,274,1423,19.26
22,Bangalore,49879539-9538-42ca-b59e-952cdd73b506,1210,288,1498,19.23
97,Hyderabad,477d50e9-2c13-435c-8db4-dd0077b4ab2e,920,218,1138,19.16
204,Udaipur,ddd350df-f43c-408e-9d70-03fbf4417600,3025,707,3732,18.94
193,Pune,cb822812-1d29-440c-8759-b33d31f78248,2176,508,2684,18.93
144,Mumbai,38ac846f-6255-4a51-8bad-bf50f3c23827,2678,624,3302,18.90
199,Surat,2918790f-421a-493e-84a3-e9a2d8f0b60d,400,93,493,18.86
140,Mumbai,21db1e24-d6a7-484a-b5aa-b43e1aafb8fc,943,216,1159,18.64
98,Hyderabad,4c93e224-40da-4c86-a5ff-c9c2cfee1168,938,214,1152,18.58
90,Hubballi,913e4d9c-179c-43fc-b130-b0c9c39d3800,3020,685,3705,18.49
131,Kolkata,ad4637de-2e3e-4276-a524-0546f33fa0d9,2919,661,3580,18.46
91,Hyderabad,1712e422-5717-4540-88ff-b22ef46f4963,2751,622,3373,18.44
44,Bangalore,a7860f3d-39d4-4275-811d-904d4c2438f4,1109,250,1359,18.40
111,Hyderabad,bb713aac-cd12-4b4d-9026-704e3deaaac3,2707,603,3310,18.22
195,Pune,f931724a-0140-4c06-b832-027e03fc320a,1002,223,1225,18.20
201,Surat,8377168d-5d92-4937-943c-75dff1ed8575,2963,657,3620,18.15
83,Coimbatore,c0217c50-c66f-4c95-bc01-185979f9e33a,3058,677,3735,18.13
99,Hyderabad,56d50978-df14-48ba-aec8-79644b36fd6a,990,219,1209,18.11
128,Kolkata,56b34f56-7705-43b0-8fee-64125becba91,2982,655,3637,18.01
53,Bangalore,d4205b92-165a-4ad5-89c1-f857521a047f,1122,246,1368,17.98
119,Indore,a02cc832-e25e-4851-b7bd-3330a61c2158,2954,647,3601,17.97
15,Bangalore,1d852498-590f-4ffa-babf-aae026e3584d,2613,571,3184,17.93
5,Bangalore,0059ff6a-7eb0-477a-a7f5-69256f2c444b,1154,248,1402,17.69
3,Ahmedabad,a1b25791-8117-4059-bb44-cb57a42bd7be,2833,607,3440,17.65
125,Kochi,ea99ba63-8772-44b9-8a98-1c2b78fe3759,3060,652,3712,17.56
85,Faridabad,eedda2b5-04e2-466c-968e-3ba537af0eec,2695,572,3267,17.51
121,Indore,dbd8cb1b-0dd8-476d-8c3c-0b2be12536b2,2855,605,3460,17.49
114,Hyderabad,e052e083-dbfe-4156-a86e-e2fd848f8c3e,962,202,1164,17.35
200,Surat,5c849951-0ba3-4878-9b29-eb2d3ef252eb,2886,604,3490,17.31
69,Chennai,5a9291a1-3743-44ad-9c10-9d458d5b6325,2472,514,2986,17.21
191,Pune,aa27f94a-ddda-47a5-91c4-8677ef56052a,1105,229,1334,17.17
46,Bangalore,abd85a95-f3f3-42fd-aeb0-71b9127335f5,1143,233,1376,16.93
7,Bangalore,071461ac-2354-4e5e-b5f5-04ef935f591c,3149,628,3777,16.63
179,Pune,281082b4-7a69-4373-a3c3-385b02d134b1,1049,207,1256,16.48
93,Hyderabad,29f978f1-5bc3-4358-a811-4b817ebebfcb,2752,542,3294,16.45
58,Bangalore,eeea2403-3a6e-49b7-874b-3d8743ef3cd8,2697,530,3227,16.42
180,Pune,2c5f4d5e-e4b5-40d2-9230-d35756cfd601,2526,492,3018,16.30
59,Bangalore,f5ee88f8-c372-4160-ac4e-bb22d8b0158e,793,153,946,16.17
108,Hyderabad,adec0623-e83c-46cc-9eef-d33b4486d054,2642,509,3151,16.15
109,Hyderabad,b0a2db37-733d-46d1-808b-7af068fc7f8a,920,177,1097,16.13
189,Pune,8c4a9155-85ec-409f-a9d8-84b193ec06ad,1032,198,1230,16.10
162,Mumbai,e5319547-8bba-4fee-862c-7d9ab6dc97c8,949,182,1131,16.09
129,Kolkata,627273fe-a446-443c-b412-1f09a9131a72,3003,575,3578,16.07
105,Hyderabad,8c84e7ae-6e94-48f2-b4c8-af6c199aef1b,2909,555,3464,16.02
168,Nagpur,5bbd5e39-81de-4d1a-9706-25cbe2cb58af,3133,594,3727,15.94
117,Hyderabad,fc88e94a-f4b7-4eab-8ce0-fdecf2e29d5f,984,184,1168,15.75
101,Hyderabad,6893b298-d63b-4c4f-b155-2e4a0ca502d5,2811,525,3336,15.74
35,Bangalore,774a725c-2c4b-4dc2-94d1-72b737f7e1f6,1156,216,1372,15.74
183,Pune,3f82b919-5cc7-42a9-8e0a-147da44f9114,2609,487,3096,15.73
29,Bangalore,6abd3309-1e45-4411-943a-81f5c32fef41,2672,497,3169,15.68
106,Hyderabad,8d94ae95-db29-44f7-b705-d533f7c66176,1002,185,1187,15.59
115,Hyderabad,e4cb21ce-7d08-43cf-af28-bf84bac6e094,2583,477,3060,15.59
118,Indore,61064aad-9e86-41f1-a52c-03f0fd5ae970,3039,559,3598,15.54
103,Hyderabad,778b5c2b-0468-4f1e-8fa0-241cc91608a2,924,170,1094,15.54
45,Bangalore,a7c548c8-f8e5-41c6-9462-1b4d7e8de41e,1151,211,1362,15.49
165,Mysuru,31903708-6be4-4223-9730-aa1b43564b75,3268,596,3864,15.42
152,Mumbai,803931bb-511e-48bc-8611-4b9910682bb4,924,168,1092,15.38
32,Bangalore,7000d78e-6700-49e6-94ac-b4caa221a0f1,1892,342,2234,15.31
39,Bangalore,94528e28-a7cb-4b41-8127-6a5625f4516f,2714,482,3196,15.08
43,Bangalore,a559802e-0aed-4cc4-9e51-8f49be9d968e,865,152,1017,14.95
174,Patiala,309c7b5f-7840-442d-adc1-908c393f760e,3136,551,3687,14.94
74,Chennai,7cd6cb01-f62f-4c1a-8b2c-21c20b17526a,2476,432,2908,14.86
158,Mumbai,b7e326da-7679-428a-82b4-6cc1d91518ac,1012,175,1187,14.74
11,Bangalore,0f5f31f2-f764-498a-9cc5-606cf82f4f2e,2723,465,3188,14.59
169,Nagpur,f2c5a570-9b33-4094-9b3b-614319c81f8e,3291,562,3853,14.59
61,Bareilly,0be324c2-79de-426d-8d78-24b4d50cd9b4,3055,518,3573,14.50
120,Indore,be1ccc2b-a9dd-4372-82da-e831188bcb55,2975,495,3470,14.27
50,Bangalore,cc2189ac-d6e4-4b5c-9c3f-1f98470e9b1b,1913,314,2227,14.10
16,Bangalore,2614cabb-fff2-4ef6-aa5b-e94c2b875880,1145,187,1332,14.04
38,Bangalore,93e0e2c3-23a6-471f-9025-8dd79ef87d60,1143,186,1329,14.00
10,Bangalore,0f2d3f82-cf97-45e8-bd80-759fe5dfbf6c,2720,439,3159,13.90
156,Mumbai,a9588bc2-3d75-410c-88c3-ec029bf4593a,967,155,1122,13.81
192,Pune,ac91c141-986b-4bb1-9bb8-5b0be08b65de,1064,170,1234,13.78
173,Panipat,317f08d2-bf42-40ce-b4b9-2a1dd60dcbfe,3137,498,3635,13.70
55,Bangalore,e0e12ce6-3431-4ed8-a74b-b0de26426220,1942,306,2248,13.61
51,Bangalore,ccc9dc9b-9c6f-421e-bedc-f2e7463a75e9,2762,433,3195,13.55
25,Bangalore,542cf806-1216-4d13-b888-c3da22c20db0,1184,185,1369,13.51
19,Bangalore,38caa147-31a6-4fae-a5b6-1c21d1bbfa1d,1188,185,1373,13.47
123,Karnal,51e91140-ab27-4854-959e-b8e0b9b50b3b,3246,500,3746,13.35
166,Mysuru,411fefdc-6597-4e1e-ad2c-1cd7cdeadb5a,3051,470,3521,13.35
57,Bangalore,eacc5aad-4e93-4266-8cde-bee3b70926a8,1164,178,1342,13.26
73,Chennai,7732ead5-8482-4815-9559-7f4cb2a72f3e,1140,167,1307,12.78
56,Bangalore,e749e734-9e20-4090-b5c3-a66ed53b5e23,2827,408,3235,12.61
13,Bangalore,1ad29aa7-34e9-4268-9238-5a3a3fcd1bd2,812,116,928,12.50
122,Jalandhar,bfbe7463-5e2b-4358-9899-2dd0f8a631dd,2868,405,3273,12.37
175,Prayagraj,1abad930-6541-4216-afbe-fa376cf5bc72,3056,429,3485,12.31
170,Nagpur,fe47f2f1-6d89-4c25-949e-1427ba5d5620,2943,412,3355,12.28
6,Bangalore,055af6e1-5726-4e98-84fa-2ce7da4d382d,1220,169,1389,12.17
4,Bangalore,0053a04d-aeb4-46b5-99fe-d740491e3843,2835,390,3225,12.09
26,Bangalore,5ec071fd-78df-41f6-b3ae-7298d9f96a3d,2618,357,2975,12.00
161,Mumbai,de3fdf29-3177-4fb9-99f7-43b940f38175,1026,138,1164,11.86
198,Sonipat,2b25b1fd-8ab2-4065-9f8b-caef224c087c,3572,479,4051,11.82
167,Mysuru,56fa4f30-c992-4e19-9e84-c5ce28862207,3403,452,3855,11.73
102,Hyderabad,700d1509-0a10-4ca8-87b9-f8c3e612fb5c,2921,383,3304,11.59
49,Bangalore,c9d7d275-70b0-4f96-a48f-2a49801fdee8,2859,373,3232,11.54
68,Chennai,53e7b8c8-68fb-4ff9-85ea-018b5acd6367,1180,154,1334,11.54
31,Bangalore,6e4a3fce-7d2e-4cf2-8dad-3ef5e9922bfb,2593,334,2927,11.41
80,Chennai,b812518e-9cc3-45e3-8fef-a1dd3311194c,1253,155,1408,11.01
134,Kota,b359ba27-8fe9-4c95-85f0-0939de00f5a4,2907,355,3262,10.88
84,Dehradun,67b7452f-7def-49a9-8284-5c86df2068ac,2998,360,3358,10.72
21,Bangalore,425e2ef0-02bc-4c87-b423-cfbc6e56984a,894,105,999,10.51
62,Bhiwadi,44cd48b8-13b4-47a2-b689-11128d52c932,3262,383,3645,10.51
12,Bangalore,137b1539-52bc-4840-8bfe-4d71dceb8bb6,2642,304,2946,10.32
17,Bangalore,3123bc8b-6f8b-4eab-828e-5715162320e5,2682,304,2986,10.18
28,Bangalore,6252e437-b1f6-4ea7-9062-d90fba216c6f,1261,134,1395,9.61
89,Haridwar,9e330266-5ce4-4408-af82-5614f2b3b001,3543,365,3908,9.34
60,Barasat,1cfc00b2-b716-46b5-84ce-6fb13aefff1e,2758,182,2940,6.19
0,Agra,eec54adb-de2b-4387-a86e-44e5fa3de74c,3087,108,3195,3.38

In [4]:
store_oos = (
    df.pivot_table(
        index=["city", "store_id"],
        columns="out_of_stock_flag",
        aggfunc="size",
        fill_value=0
    )
    .reset_index()
)

# Ensure both columns exist
for col in ["Yes", "No"]:
    if col not in store_oos.columns:
        store_oos[col] = 0

store_oos["Total"] = store_oos["Yes"] + store_oos["No"]
store_oos["Out_of_stock_%"] = (
    store_oos["Yes"] / store_oos["Total"] * 100
).round(2)

store_oos = store_oos.sort_values(
    "Out_of_stock_%",
    ascending=False
)

store_oos

out_of_stock_flag,city,store_id,No,Yes,Total,Out_of_stock_%
143,Mumbai,37b900f0-25c0-448b-825a-74d62c8ceb41,385,369,754,48.94
77,Chennai,a98f0f81-73ab-4839-8d06-4e9427680054,1952,1630,3582,45.51
137,Mumbai,1b11ac6b-6de6-411b-80bf-a72874a80c51,1937,1455,3392,42.90
71,Chennai,691e4cd7-b08a-421b-a35d-6c89173b796e,2014,1403,3417,41.06
112,Hyderabad,d54cc989-bc58-4cb9-9c2e-3a3468546c3f,2094,1449,3543,40.90
87,Greater Noida,848cd607-f42d-42aa-b7d8-09241fe84d14,815,554,1369,40.47
81,Chennai,fb0d381c-e38f-4bcc-a5f8-872e3e033e62,2188,1443,3631,39.74
159,Mumbai,cc72f206-e146-43c5-a01b-56ddc8d11464,2073,1314,3387,38.80
151,Mumbai,751c003c-bbe4-453d-ae3d-404380528149,1129,668,1797,37.17
196,Pune,fe4a16ca-6c7c-4f1a-88a7-fecda52d8057,2292,1319,3611,36.53
76,Chennai,86ec9fc6-ed4b-4674-8175-68c88c75c16f,2260,1257,3517,35.74
136,Mumbai,18c249b1-83ec-4088-9680-686d57883dee,775,431,1206,35.74
2,Ahmedabad,863ee650-1df1-418c-a988-2a64f2c555e3,2272,1242,3514,35.34
205,Vijayawada,471b6b1b-6289-47bf-ac72-a61684f86181,2407,1300,3707,35.07
78,Chennai,aa16c37d-46a9-4e32-84b3-0e2401bd196f,2349,1242,3591,34.59
176,Prayagraj,28868283-c2ed-433d-bf3b-f968b5eeef8a,1789,925,2714,34.08
113,Hyderabad,de95e00b-0ebf-4f65-8f27-df66fd91dc13,638,329,967,34.02
153,Mumbai,8a278c72-1366-4926-b81e-ecc6e64df2a7,681,327,1008,32.44
133,Kolkata,e879c6cf-e4bd-4b11-a605-4e9b2ee2365d,400,192,592,32.43
145,Mumbai,4a54d5f5-0bd9-4b8f-b08a-120d8e7926d7,2226,1054,3280,32.13
150,Mumbai,72655f9e-d9be-4b01-b2ac-62e61d2efd47,2273,1075,3348,32.11
33,Bangalore,75946a5e-942e-4db1-9e7c-5fe2eb85088b,2128,977,3105,31.47
70,Chennai,65833924-5a42-4378-9556-8d10945f5a37,2479,1129,3608,31.29
154,Mumbai,8be2198a-76dd-42c7-a351-d1c2b80d459e,1789,798,2587,30.85
164,Mumbai,fdc84bec-ec86-4b5d-b18b-84daca52c609,2560,1134,3694,30.70
126,Kolkata,0af692ee-167f-4903-bf7c-959643e47899,2407,1053,3460,30.43
86,Greater Noida,5cc22671-70e0-4077-8f1c-5502c2c5522b,1357,593,1950,30.41
142,Mumbai,2e7ec440-fd1b-441e-90ee-9c8611648bb6,2272,988,3260,30.31
116,Hyderabad,f275b3c5-5538-46b4-940f-82d9358dba84,2620,1115,3735,29.85
163,Mumbai,f860ca85-ea81-46eb-9448-1de0226aa0fe,2101,870,2971,29.28
67,Chennai,4ab9ad5d-75ba-4cca-93cd-9f40062825c7,2550,1056,3606,29.28
72,Chennai,6db09732-73a0-424c-b528-1778ad7ba7e5,2064,814,2878,28.28
79,Chennai,b4d53703-4b49-4a38-85ca-7e321d1d5222,2005,788,2793,28.21
64,Chennai,1669ccf3-23b3-4ba3-b5c5-8a984549717c,1978,772,2750,28.07
75,Chennai,7fbf2dd5-101c-4f92-802d-728264804add,2611,1010,3621,27.89
27,Bangalore,6047c8fe-15ed-4c61-8d3e-060e800702f5,2609,996,3605,27.63
149,Mumbai,662012a6-9b5c-4471-8051-f83675b0d84c,2370,898,3268,27.48
66,Chennai,2699f532-61f3-431f-aab3-db586ec14085,2583,979,3562,27.48
172,Nashik,da931d01-2519-4d80-89ae-9d74dbb71918,2684,1011,3695,27.36
127,Kolkata,17532e16-28d2-4271-bbac-c48b9b3f8dd1,2662,974,3636,26.79
96,Hyderabad,43b12c97-dc99-431a-9ba3-e3cde9c716bb,2702,987,3689,26.76
197,S.A.S Nagar,2bf9f3ff-7b68-4ac5-a814-1059b71840cf,2535,920,3455,26.63
146,Mumbai,5116a0c5-42bc-487c-ac82-37af432606b0,2238,808,3046,26.53
155,Mumbai,95d6c1a2-b071-4cf3-a322-30b5754d7cb6,723,261,984,26.52
185,Pune,60252717-a8c5-4891-9b23-3db778b14477,391,141,532,26.50
54,Bangalore,e044093d-2a02-4fd7-a1e9-5542edbe746a,2223,797,3020,26.39
95,Hyderabad,33a1d02e-1bb7-44cc-8d38-9697bcc23dba,897,316,1213,26.05
188,Pune,7fe0f5bc-d9c2-4883-b9c2-35fc8f36e1c1,2610,912,3522,25.89
138,Mumbai,1cf40b2e-95cd-4581-9ab9-bca81d4932ab,987,342,1329,25.73
1,Ahmedabad,1105d3fb-0556-4f7e-bd83-416274e9924a,2715,938,3653,25.68
190,Pune,a6aaf608-0a95-47fd-a981-a52d1a5e5e2a,2540,868,3408,25.47
186,Pune,74dfeece-0ec5-4b41-a83b-576add66078e,2412,816,3228,25.28
92,Hyderabad,26ec9b6b-b566-4f36-b5dd-eb6fb92a0caf,2489,836,3325,25.14
148,Mumbai,5f267ad5-446b-4a8b-86f0-df174ad545dd,2378,798,3176,25.13
184,Pune,4cc5f8ae-6495-44d0-9212-b63fe11a3af5,2710,906,3616,25.06
124,Kochi,1dfb0f79-3c66-45e8-8b24-9d79ab1b2477,2791,928,3719,24.95
110,Hyderabad,b32bcacd-f047-47c1-a3b8-c1ccacf364a8,2756,906,3662,24.74
48,Bangalore,c48dd700-4314-4cc1-bffa-e1344e0298dc,2371,774,3145,24.61
157,Mumbai,b54c01f1-4f46-47d6-a3e7-bd040d3e8548,2414,774,3188,24.28
107,Hyderabad,ab5ca9c7-151c-45c6-97df-5a4844e981ea,2534,803,3337,24.06
65,Chennai,1e32417a-1c1c-4f1c-972e-9852a27904d0,2355,715,3070,23.29
34,Bangalore,76cae5a0-b75d-456b-9aab-df0b0b7559c2,1210,365,1575,23.17
100,Hyderabad,67ec5278-78c4-4654-b67d-c0433f5406c7,2428,731,3159,23.14
9,Bangalore,0cde9637-ca43-45b6-a89c-08c1e32bae57,1659,491,2150,22.84
104,Hyderabad,83e33858-a13f-4c67-a016-07de0cce8043,2548,747,3295,22.67
139,Mumbai,2175898f-b70e-46d9-8def-aba7f0745662,826,241,1067,22.59
30,Bangalore,6b1d82f8-b2ea-4e43-ae70-6f6bca1ec77a,1122,325,1447,22.46
52,Bangalore,cf384ecd-5e1f-47e9-9194-8e9dc940e8c3,2502,710,3212,22.10
160,Mumbai,d431e3b5-0ba8-4823-8c4b-c4ea0909dbde,2504,710,3214,22.09
88,Greater Noida,fc05177a-ca9e-4c93-9811-dbb101b0c8f7,742,210,952,22.06
94,Hyderabad,314533d4-8bd7-4985-8ca5-9b737431149b,2878,814,3692,22.05
171,Nashik,bc299560-8f6b-43ba-b146-879f3594ea7e,2928,825,3753,21.98
23,Bangalore,4e507e91-6be7-4f3c-8dfe-aaa051a6d0c8,2234,628,2862,21.94
187,Pune,7a75116f-d14e-49b3-bfde-a6c2a4d180a7,1013,284,1297,21.90
194,Pune,e9da3e70-081c-4c4d-abad-5d88303ced92,2375,658,3033,21.69
177,Pune,231186c7-f3b9-4b6e-9e17-f29a217c4de8,2511,689,3200,21.53
147,Mumbai,52278321-e20a-4a88-b24c-613fafa720e0,2586,708,3294,21.49
42,Bangalore,a09f04ca-3c1d-4523-8606-386ce213a7ae,2514,669,3183,21.02
135,Madurai,b91aec1b-7f2b-45a0-b047-bf7750d4d193,2808,747,3555,21.01
130,Kolkata,9cc80a80-f39d-4da4-9ce6-14fad42e470e,2914,774,3688,20.99
41,Bangalore,9fb087cf-076d-40a0-b974-8d26eaa69f44,2521,669,3190,20.97
63,Chennai,0f63c763-901b-4a64-8c53-da415735616b,2825,749,3574,20.96
82,Coimbatore,4942530d-03e3-44f5-ba28-30c05c238e24,2955,770,3725,20.67
36,Bangalore,7de4838b-ae7c-44d0-bf24-fb2040666654,2542,659,3201,20.59
37,Bangalore,843e630a-7896-462d-b7cf-712140483ed3,1146,297,1443,20.58
202,Surat,d2020a3b-0420-4886-8c55-3128f6a3f592,2879,742,3621,20.49
181,Pune,3a15115a-c99e-4421-bfcc-5b97a2716da5,2585,659,3244,20.31
203,Surat,e7cfb807-6977-42cb-90de-2a3a2527d6c3,2732,693,3425,20.23
182,Pune,3c8e6f2e-5b5d-4654-8e41-a1e0109e3972,2593,656,3249,20.19
47,Bangalore,b4dc8d65-ed2e-4142-81b6-373982b13500,2420,612,3032,20.18
141,Mumbai,291264cf-55b8-4ae3-93b2-cb23fd795054,2598,656,3254,20.16
18,Bangalore,376dd638-f05e-4171-b4e1-b97650b79fe7,341,85,426,19.95
20,Bangalore,40382f4d-61eb-4e99-9a0f-201fd9926f40,2566,634,3200,19.81
14,Bangalore,1c9e155e-83a8-457a-a687-01eabb1e7a36,1159,286,1445,19.79
178,Pune,252ed3f4-d99b-4793-951e-ae673cb9ebbf,2524,621,3145,19.75
8,Bangalore,07a6d7c0-aea9-434c-846e-9308e495db6a,1144,274,1418,19.32
24,Bangalore,4f54ea62-0269-4b93-87cd-ef7ed796c6b1,2544,609,3153,19.31
132,Kolkata,da5b2eac-c339-43fa-a59b-b153f2603b9c,2998,715,3713,19.26
40,Bangalore,992bee8f-8936-4b04-9d17-546cd0ba1b76,1149,274,1423,19.26
22,Bangalore,49879539-9538-42ca-b59e-952cdd73b506,1210,288,1498,19.23
97,Hyderabad,477d50e9-2c13-435c-8db4-dd0077b4ab2e,920,218,1138,19.16
204,Udaipur,ddd350df-f43c-408e-9d70-03fbf4417600,3025,707,3732,18.94
193,Pune,cb822812-1d29-440c-8759-b33d31f78248,2176,508,2684,18.93
144,Mumbai,38ac846f-6255-4a51-8bad-bf50f3c23827,2678,624,3302,18.90
199,Surat,2918790f-421a-493e-84a3-e9a2d8f0b60d,400,93,493,18.86
140,Mumbai,21db1e24-d6a7-484a-b5aa-b43e1aafb8fc,943,216,1159,18.64
98,Hyderabad,4c93e224-40da-4c86-a5ff-c9c2cfee1168,938,214,1152,18.58
90,Hubballi,913e4d9c-179c-43fc-b130-b0c9c39d3800,3020,685,3705,18.49
131,Kolkata,ad4637de-2e3e-4276-a524-0546f33fa0d9,2919,661,3580,18.46
91,Hyderabad,1712e422-5717-4540-88ff-b22ef46f4963,2751,622,3373,18.44
44,Bangalore,a7860f3d-39d4-4275-811d-904d4c2438f4,1109,250,1359,18.40
111,Hyderabad,bb713aac-cd12-4b4d-9026-704e3deaaac3,2707,603,3310,18.22
195,Pune,f931724a-0140-4c06-b832-027e03fc320a,1002,223,1225,18.20
201,Surat,8377168d-5d92-4937-943c-75dff1ed8575,2963,657,3620,18.15
83,Coimbatore,c0217c50-c66f-4c95-bc01-185979f9e33a,3058,677,3735,18.13
99,Hyderabad,56d50978-df14-48ba-aec8-79644b36fd6a,990,219,1209,18.11
128,Kolkata,56b34f56-7705-43b0-8fee-64125becba91,2982,655,3637,18.01
53,Bangalore,d4205b92-165a-4ad5-89c1-f857521a047f,1122,246,1368,17.98
119,Indore,a02cc832-e25e-4851-b7bd-3330a61c2158,2954,647,3601,17.97
15,Bangalore,1d852498-590f-4ffa-babf-aae026e3584d,2613,571,3184,17.93
5,Bangalore,0059ff6a-7eb0-477a-a7f5-69256f2c444b,1154,248,1402,17.69
3,Ahmedabad,a1b25791-8117-4059-bb44-cb57a42bd7be,2833,607,3440,17.65
125,Kochi,ea99ba63-8772-44b9-8a98-1c2b78fe3759,3060,652,3712,17.56
85,Faridabad,eedda2b5-04e2-466c-968e-3ba537af0eec,2695,572,3267,17.51
121,Indore,dbd8cb1b-0dd8-476d-8c3c-0b2be12536b2,2855,605,3460,17.49
114,Hyderabad,e052e083-dbfe-4156-a86e-e2fd848f8c3e,962,202,1164,17.35
200,Surat,5c849951-0ba3-4878-9b29-eb2d3ef252eb,2886,604,3490,17.31
69,Chennai,5a9291a1-3743-44ad-9c10-9d458d5b6325,2472,514,2986,17.21
191,Pune,aa27f94a-ddda-47a5-91c4-8677ef56052a,1105,229,1334,17.17
46,Bangalore,abd85a95-f3f3-42fd-aeb0-71b9127335f5,1143,233,1376,16.93
7,Bangalore,071461ac-2354-4e5e-b5f5-04ef935f591c,3149,628,3777,16.63
179,Pune,281082b4-7a69-4373-a3c3-385b02d134b1,1049,207,1256,16.48
93,Hyderabad,29f978f1-5bc3-4358-a811-4b817ebebfcb,2752,542,3294,16.45
58,Bangalore,eeea2403-3a6e-49b7-874b-3d8743ef3cd8,2697,530,3227,16.42
180,Pune,2c5f4d5e-e4b5-40d2-9230-d35756cfd601,2526,492,3018,16.30
59,Bangalore,f5ee88f8-c372-4160-ac4e-bb22d8b0158e,793,153,946,16.17
108,Hyderabad,adec0623-e83c-46cc-9eef-d33b4486d054,2642,509,3151,16.15
109,Hyderabad,b0a2db37-733d-46d1-808b-7af068fc7f8a,920,177,1097,16.13
189,Pune,8c4a9155-85ec-409f-a9d8-84b193ec06ad,1032,198,1230,16.10
162,Mumbai,e5319547-8bba-4fee-862c-7d9ab6dc97c8,949,182,1131,16.09
129,Kolkata,627273fe-a446-443c-b412-1f09a9131a72,3003,575,3578,16.07
105,Hyderabad,8c84e7ae-6e94-48f2-b4c8-af6c199aef1b,2909,555,3464,16.02
168,Nagpur,5bbd5e39-81de-4d1a-9706-25cbe2cb58af,3133,594,3727,15.94
117,Hyderabad,fc88e94a-f4b7-4eab-8ce0-fdecf2e29d5f,984,184,1168,15.75
101,Hyderabad,6893b298-d63b-4c4f-b155-2e4a0ca502d5,2811,525,3336,15.74
35,Bangalore,774a725c-2c4b-4dc2-94d1-72b737f7e1f6,1156,216,1372,15.74
183,Pune,3f82b919-5cc7-42a9-8e0a-147da44f9114,2609,487,3096,15.73
29,Bangalore,6abd3309-1e45-4411-943a-81f5c32fef41,2672,497,3169,15.68
106,Hyderabad,8d94ae95-db29-44f7-b705-d533f7c66176,1002,185,1187,15.59
115,Hyderabad,e4cb21ce-7d08-43cf-af28-bf84bac6e094,2583,477,3060,15.59
118,Indore,61064aad-9e86-41f1-a52c-03f0fd5ae970,3039,559,3598,15.54
103,Hyderabad,778b5c2b-0468-4f1e-8fa0-241cc91608a2,924,170,1094,15.54
45,Bangalore,a7c548c8-f8e5-41c6-9462-1b4d7e8de41e,1151,211,1362,15.49
165,Mysuru,31903708-6be4-4223-9730-aa1b43564b75,3268,596,3864,15.42
152,Mumbai,803931bb-511e-48bc-8611-4b9910682bb4,924,168,1092,15.38
32,Bangalore,7000d78e-6700-49e6-94ac-b4caa221a0f1,1892,342,2234,15.31
39,Bangalore,94528e28-a7cb-4b41-8127-6a5625f4516f,2714,482,3196,15.08
43,Bangalore,a559802e-0aed-4cc4-9e51-8f49be9d968e,865,152,1017,14.95
174,Patiala,309c7b5f-7840-442d-adc1-908c393f760e,3136,551,3687,14.94
74,Chennai,7cd6cb01-f62f-4c1a-8b2c-21c20b17526a,2476,432,2908,14.86
158,Mumbai,b7e326da-7679-428a-82b4-6cc1d91518ac,1012,175,1187,14.74
11,Bangalore,0f5f31f2-f764-498a-9cc5-606cf82f4f2e,2723,465,3188,14.59
169,Nagpur,f2c5a570-9b33-4094-9b3b-614319c81f8e,3291,562,3853,14.59
61,Bareilly,0be324c2-79de-426d-8d78-24b4d50cd9b4,3055,518,3573,14.50
120,Indore,be1ccc2b-a9dd-4372-82da-e831188bcb55,2975,495,3470,14.27
50,Bangalore,cc2189ac-d6e4-4b5c-9c3f-1f98470e9b1b,1913,314,2227,14.10
16,Bangalore,2614cabb-fff2-4ef6-aa5b-e94c2b875880,1145,187,1332,14.04
38,Bangalore,93e0e2c3-23a6-471f-9025-8dd79ef87d60,1143,186,1329,14.00
10,Bangalore,0f2d3f82-cf97-45e8-bd80-759fe5dfbf6c,2720,439,3159,13.90
156,Mumbai,a9588bc2-3d75-410c-88c3-ec029bf4593a,967,155,1122,13.81
192,Pune,ac91c141-986b-4bb1-9bb8-5b0be08b65de,1064,170,1234,13.78
173,Panipat,317f08d2-bf42-40ce-b4b9-2a1dd60dcbfe,3137,498,3635,13.70
55,Bangalore,e0e12ce6-3431-4ed8-a74b-b0de26426220,1942,306,2248,13.61
51,Bangalore,ccc9dc9b-9c6f-421e-bedc-f2e7463a75e9,2762,433,3195,13.55
25,Bangalore,542cf806-1216-4d13-b888-c3da22c20db0,1184,185,1369,13.51
19,Bangalore,38caa147-31a6-4fae-a5b6-1c21d1bbfa1d,1188,185,1373,13.47
123,Karnal,51e91140-ab27-4854-959e-b8e0b9b50b3b,3246,500,3746,13.35
166,Mysuru,411fefdc-6597-4e1e-ad2c-1cd7cdeadb5a,3051,470,3521,13.35
57,Bangalore,eacc5aad-4e93-4266-8cde-bee3b70926a8,1164,178,1342,13.26
73,Chennai,7732ead5-8482-4815-9559-7f4cb2a72f3e,1140,167,1307,12.78
56,Bangalore,e749e734-9e20-4090-b5c3-a66ed53b5e23,2827,408,3235,12.61
13,Bangalore,1ad29aa7-34e9-4268-9238-5a3a3fcd1bd2,812,116,928,12.50
122,Jalandhar,bfbe7463-5e2b-4358-9899-2dd0f8a631dd,2868,405,3273,12.37
175,Prayagraj,1abad930-6541-4216-afbe-fa376cf5bc72,3056,429,3485,12.31
170,Nagpur,fe47f2f1-6d89-4c25-949e-1427ba5d5620,2943,412,3355,12.28
6,Bangalore,055af6e1-5726-4e98-84fa-2ce7da4d382d,1220,169,1389,12.17
4,Bangalore,0053a04d-aeb4-46b5-99fe-d740491e3843,2835,390,3225,12.09
26,Bangalore,5ec071fd-78df-41f6-b3ae-7298d9f96a3d,2618,357,2975,12.00
161,Mumbai,de3fdf29-3177-4fb9-99f7-43b940f38175,1026,138,1164,11.86
198,Sonipat,2b25b1fd-8ab2-4065-9f8b-caef224c087c,3572,479,4051,11.82
167,Mysuru,56fa4f30-c992-4e19-9e84-c5ce28862207,3403,452,3855,11.73
102,Hyderabad,700d1509-0a10-4ca8-87b9-f8c3e612fb5c,2921,383,3304,11.59
49,Bangalore,c9d7d275-70b0-4f96-a48f-2a49801fdee8,2859,373,3232,11.54
68,Chennai,53e7b8c8-68fb-4ff9-85ea-018b5acd6367,1180,154,1334,11.54
31,Bangalore,6e4a3fce-7d2e-4cf2-8dad-3ef5e9922bfb,2593,334,2927,11.41
80,Chennai,b812518e-9cc3-45e3-8fef-a1dd3311194c,1253,155,1408,11.01
134,Kota,b359ba27-8fe9-4c95-85f0-0939de00f5a4,2907,355,3262,10.88
84,Dehradun,67b7452f-7def-49a9-8284-5c86df2068ac,2998,360,3358,10.72
21,Bangalore,425e2ef0-02bc-4c87-b423-cfbc6e56984a,894,105,999,10.51
62,Bhiwadi,44cd48b8-13b4-47a2-b689-11128d52c932,3262,383,3645,10.51
12,Bangalore,137b1539-52bc-4840-8bfe-4d71dceb8bb6,2642,304,2946,10.32
17,Bangalore,3123bc8b-6f8b-4eab-828e-5715162320e5,2682,304,2986,10.18
28,Bangalore,6252e437-b1f6-4ea7-9062-d90fba216c6f,1261,134,1395,9.61
89,Haridwar,9e330266-5ce4-4408-af82-5614f2b3b001,3543,365,3908,9.34
60,Barasat,1cfc00b2-b716-46b5-84ce-6fb13aefff1e,2758,182,2940,6.19
0,Agra,eec54adb-de2b-4387-a86e-44e5fa3de74c,3087,108,3195,3.38

In [5]:
import re

# Normalize brand names
df["productname_norm"] = (
    df["product_name"]
    .fillna("")
    .str.lower()
    .str.replace(r"[^a-z0-9]", "", regex=True)   # remove spaces, ', -, &, etc.
)

# Find brands that become the same after normalization
name_issue = (
    df.groupby("productname_norm")
    .agg(
        variant_count=("product_name", "nunique"),
        name_variants=("product_name", lambda x: sorted(set(x)))
    )
    .reset_index()
)

name_issue = name_issue[name_issue["variant_count"] > 1]

name_issue

,productname_norm,variant_count,name_variants
39,4700bccheesepopcornjumbosizezeropalmoil,2,"[4700BC Cheese Popcorn | Jumbo Size | Zero Palm Oil, 4700BC Cheese Popcorn | Jumbo Size,Zero Palm Oil]"
347,altcooatmilknzs1,2,"[Alt Co. Oat Milk nzs 1, Alt Co. Oat MilkN Z S 1]"
571,amulshaktifreshmilkpouch,2,"[Amul Shakti Fresh Milk (Pouch), Amul Shakti Fresh Milk | Pouch]"
647,andaahnaturalwhiteeggs,2,"[Andaah Natural White Eggs, Andaah Natural+ White Eggs]"
953,babysebamedgentlewashph55babybodywashsoapfreetearfree,2,"[Baby Sebamed Gentle Wash | pH 5.5 | Baby Body Wash | Soap Free | Tear Free, Baby Sebamed Gentle Wash | pH 5.5 | Baby Body Wash | Soap Free| Tear Free]"
999,bakersloafzeropreservativesmultigrainbread,2,"[Baker's Loaf Zero Preservatives Multigrain Bread, Baker's Loaf- Zero Preservatives Multigrain Bread]"
1000,bakersloafzeropreservativeswholewheatbread,2,"[Baker's Loaf - Zero Preservatives Whole Wheat Bread, Baker's Loaf Zero Preservatives Whole Wheat Bread]"
1164,beautyofjoseonreliefsunriceprobioticsspf50pa,2,"[Beauty Of Joseon Relief Sun | Rice + Probiotics SPF 50+ PA++++, Beauty of Joseon Relief Sun Rice + Probiotics SPF 50+ PA++++]"
1251,beyondsnackkeralabananachipsperiperi,2,"[Beyond Snack Kerala Banana Chips | Peri Peri, Beyond Snack Kerala Banana chips | Peri Peri]"
1392,bisleripackageddrinkingwater,2,"[Bisleri Packaged Drinking Water, Bisleri Packaged Drinking Water.]"
1559,bombayshavingcompanypostshavebalm,2,"[Bombay Shaving Company Post Shave Balm, Bombay Shaving Company Post-Shave Balm]"
1628,braunsilkepilatorse3031forlonglastinghairremovalfromrootswhitepink,2,"[Braun Silk Epilator Se 3031 For Long-Lasting Hair Removal From Roots,White & Pink, Braun Silk Epilator Se 3031 For Long-Lasting Hair Removal From Roots,White & Pink.]"
1735,britanniatreatrichcremeorangeflavouredwafers,2,"[Britannia Treat Rich Creme Orange Flavoured Wafers, Britannia Treat Rich Creme Orange Flavoured Wafers ..]"
1743,britanniavitarichsandwichpremiumwhitebread,2,"[Britannia Vita Rich Sandwich Premium White Bread, Britannia Vitarich Sandwich Premium White Bread]"
1844,cadburychoclayeredcakeminionpack,2,"[Cadbury Choc Layered Cake Minion Pack, Cadbury Choc Layered Cake Minion pack]"
1908,carmesidisposableperiodpantiesallnightprotectionxlxxl,2,"[Carmesi Disposable Period Panties | All Night Protection | XL-XXL, Carmesi Disposable Period Panties | All-Night Protection | XL-XXL]"
1972,cetaphilbabywashshampoowithorganiccalendula,2,"[Cetaphil Baby Wash & Shampoo With Organic Calendula, Cetaphil Baby Wash & Shampoo with Organic Calendula]"
1983,cetaphildamdailyadvanceultrahydratinglotion,2,"[Cetaphil DAM Daily Advance Ultra Hydrating Lotion, Cetaphil Dam Daily Advance Ultra Hydrating Lotion]"
2229,cleananddryintimatewash,2,"[Clean And Dry Intimate Wash, Clean and Dry Intimate Wash]"
2232,cleanclearfoamingfacewash,2,"[Clean & Clear Foaming Face Wash, Clean & Clear Foaming Facewash]"
2285,colgatekids2yearsextrasofttoothbrush,2,"[Colgate Kid's 2+ Years Extra Soft Toothbrush, Colgate Kids 2+ Years Extra Soft Toothbrush]"
2299,colgatemaxfreshplaxmouthwashfreshmint,2,"[Colgate Max Fresh Plax Mouthwash - Fresh Mint, Colgate Max Fresh Plax Mouthwash Freshmint]"
2704,dailygoodalmondbadamcalifornia,2,"[Daily Good Almond - Badam | California, Daily Good Almond / Badam | California]"
2705,dailygoodambemohargovindobhogjeerarice,2,"[Daily Good Ambemohar-Govindobhog-Jeera Rice, Daily Good Ambemohar/Govindobhog/Jeera Rice]"
2714,dailygoodblackpepperkalimirch,2,"[Daily Good Black Pepper - Kali Mirch, Daily Good Black Pepper / Kali Mirch]"
2751,dailygoodidlyanddosabatter,2,"[Daily Good - Idly And Dosa Batter, Daily Good Idly And Dosa Batter]"
2824,dailygoodsaunffennel,2,"[Daily Good Saunf - Fennel, Daily Good Saunf / Fennel]"
2855,dailygoodunpolishedtoorturarhardal,2,"[Daily Good Unpolished Toor - Tur - Arhar Dal, Daily Good Unpolished Toor / Tur / Arhar Dal]"
3025,delmontepineappleslices,2,"[Del Monte Pineapple - Slices, Del Monte Pineapple Slices]"
3474,eggoneggsgradeaeggs,2,"[Egg On Eggs Grade A Eggs, Egg On Eggs Grade-A Eggs]"
3655,epigamiagreekyogurtnaturalcombo,2,"[Epigamia Greek Yogurt- Natural Combo, Epigamia Greek Yogurt- Natural | Combo]"
3889,facescanadastrobecreamrosegoldprimerhighlightermoisturizer,2,"[FACES CANADA Strobe Cream - Rose Gold | Primer + Highlighter + Moisturizer, Faces Canada Strobe Cream | Rose Gold, Primer + Highlighter + Moisturizer]"
3893,facescanadaultimeprohdintensemattelipsprimerperfection01,2,"[Faces Canada Ultime Pro HD Intense Matte Lips + Primer - Perfection 01, Faces Canada Ultime Pro Hd Intense Matte Lips + Primer - Perfection 01]"
4027,fitnestclassicwhiteeggs,2,"[FitNest Classic White Eggs, Fitnest Classic White Eggs]"
4088,fortunekachighanimustardoilbottle,2,"[Fortune Kachi Ghani Mustard Oil Bottle, Fortune Kachi Ghani Mustard Oil | Bottle]"
4229,frubonrabrimalaikulfiicecreamstickcombo,2,"[FruBon Rabri Malai Kulfi Ice Cream Stick Combo, Frubon Rabri Malai Kulfi Ice Cream Stick Combo]"
4237,fruitchillicepopsfrozenjuicebarsmultipackmangostrawberryorangenimboogrape,2,"[Fruitchill Ice Pops/ Frozen Juice Bars Multipack- Mango, Strawberry, Orange, Nimboo, Grape, Fruitchill Ice Pops/Frozen Juice Bars Multipack- Mango, Strawberry, Orange, Nimboo, Grape]"
4241,fullbodytrimmerwith5in1magneticattachmentsformultigroomingsolutions,2,"[Full Body Trimmer With 5-in-1 Magnetic Attachments For Multi-Grooming Solutions, Full Body Trimmer With 5-in-1 Magnetic Attachments For Multi-Grooming Solutions.]"
4526,godrejjerseyspicybuttermilkpouch,2,"[Godrej Jersey Spicy Butter Milk Pouch, Godrej Jersey Spicy Buttermilk Pouch]"
4637,gozeroraspberryduetlowcalorieguiltfreeicecreamstick,2,"[Go Zero Raspberry Duet Low Calorie Guilt Free Ice Cream Stick ., Go Zero Raspberry Duet Low Calorie Guilt Free Ice Cream Stick ..]"
4728,gubbtonguecleanertassorted,2,"[GUBB Tongue Cleaner T | Assorted, GUBB Tongue Cleaner T+ | Assorted]"
4818,haldiramschipsclassicsaltedcrispysalty,2,"[Haldiram's Chips Classic Salted | Crispy & Salty, Haldiram's Chips | Classic Salted | Crispy & Salty]"
5041,havells1000wvolumizerhairdryerprestylingbrushcurlersrollerbrushblackhc4085,2,"[Havells 1000W Volumizer Hair Dryer|Pre-Styling Brush, Curlers, Roller Brush|Black|Hc4085, Havells 1000W Volumizer Hair Dryer|Pre-Styling Brush, Curlers, Roller Brush|Black|Hc4085.]"
5042,havellsbrushhairstraightener50whs4201,2,"[Havells Brush Hair Straightener (50 W, HS4201), Havells Brush Hair Straightener (50 W, HS4201).]"
5072,hbbakerschoicealmondcakerusk,2,"[HB BAKERS CHOICE Almond Cake Rusk, HB Bakers Choice Almond Cake Rusk]"
5075,hbbakerschoicemawacakerusk,2,"[HB Bakers Choice Mawa Cake Rusk, hb bakers choice mawa cake rusk]"
5159,heritagefullcreamfreshmilkpouch,2,"[Heritage Full Cream Fresh Milk (Pouch), Heritage Full Cream Fresh Milk | Pouch]"
5261,himalayagentlebabysoapwith100naturalalmondoliveoilnopostbathdryness,2,"[Himalaya Gentle Baby Soap with 100% Natural Almond & Olive Oil -| No Post Bath Dryness, Himalaya Gentle Baby Soap with 100% Natural Almond & Olive Oil| No Post Bath Dryness]"
5600,indulekhabringhashampooproprietaryayurvedicmedicineforhairfall,2,"[Indulekha Bringha Shampoo | Proprietary Ayurvedic Medicine For Hair Fall, Indulekha Bringha Shampoo|| Proprietary Ayurvedic Medicine For Hair Fall]"
5604,indusvalleygelhaircolourforwomenmendamageammoniappdfreehaircolordarkbrown,2,"[Indus Valley Gel Hair Colour for Women & Men Damage, Ammonia & PPD Free Hair Color | Dark Brown, Indus Valley Gel Hair Colour for Women & Men Damage, Ammonia&PPD Free Hair Color | Dark Brown]"
5628,insightcosmeticslongwearcolorrichlipglossfrost,2,"[Insight Cosmetics Long Wear Color Rich Lip Gloss - Frost, Insight Cosmetics Long Wear Color Rich Lip Gloss | Frost]"
5634,insightcosmeticsnontransferliquidlipstickcoffeecommandcrueltyfree,2,"[Insight Cosmetics Non Transfer Liquid Lipstick - Coffee Command | Cruelty Free, Insight Cosmetics Non Transfer Liquid Lipstick | Coffee Command | Cruelty Free]"
5635,insightcosmeticsnontransferliquidlipstickmoltenpinkcrueltyfree,2,"[Insight Cosmetics Non Transfer Liquid Lipstick - Molten Pink | Cruelty Free, Insight Cosmetics Non Transfer Liquid Lipstick | Molten Pink | Cruelty Free]"
5725,jhalmuri,2,"[Jhal Muri, Jhalmuri]"
6504,lalbabaricesuperiorbanskathirice,2,"[LALBABA Rice Superior Banskathi Rice, Lalbaba Rice Superior Banskathi Rice]"
6974,lovebeautyplanetonionblackseedpatchoulihairfallcontrolconditioner,2,"[Love Beauty & Planet Onion Blackseed & Patchouli Hairfall Control Conditioner, Love Beauty & Planet Onion, Blackseed & Patchouli Hairfall Control Conditioner]"
7109,maggirichtomatoketchup,2,"[MAGGI Rich Tomato Ketchup, Maggi Rich Tomato Ketchup]"
7114,maggivegattanoodlesmadewithonlyattaflour,2,"[Maggi Veg Atta Noodles Made with Only Atta Flour, Maggi Veg Atta Noodles Made with Only Atta flour]"
7183,mamaearthonionhairoilforhairfallcontrolwithonionredensyl,2,"[Mamaearth Onion Hair Oil For Hair Fall Control With Onion & Redensyl, Mamaearth Onion Hair Oil for Hair Fall Control with Onion & Redensyl]"
7767,minimalist35maleicbondrepairshampoofordamageddryfrizzyhair,2,"[Minimalist 3.5% Maleic Bond Repair Shampoo For Damaged, Dry & Frizzy Hair, Minimalist 3.5% Maleic Bond Repair Shampoo for Damaged, Dry & Frizzy Hair]"
8327,nandinigoodlifetoneduhtmilkfinopouch,2,"[Nandini Good Life Toned UHT Milk (Fino Pouch), Nandini Goodlife Toned UHT Milk (Fino Pouch)]"
8328,nandinigoodlifetoneduhtmilkfinopouchcombo,2,"[Nandini Good Life Toned UHT Milk (Fino Pouch) Combo, Nandini Goodlife Toned UHT Milk (Fino Pouch) Combo]"
8335,nandiniprocessedcheeseslices,2,"[Nandini Processed Cheese Slices, Nandini Processed Cheese- Slices]"
8534,nicalphonsomangoicecreamcupcombopreservativefreenoartificialflavors,2,"[NIC Alphonso Mango Ice Cream Cup Combo | Preservative Free | No Artificial Flavors, NIC Alphonso Mango Ice Cream Cup Combo| Preservative Free | No Artificial Flavors]"
8536,nicalphonsomangoicecreamcuppreservativefreenoartificialflavors,2,"[NIC Alphonso Mango Ice Cream Cup | Preservative Free | No Artificial Flavors, NIC Alphonso Mango Ice Cream Cup| Preservative Free | No Artificial Flavors]"
8631,niveasoftdailyuvlightmoisturisingcreamwithspf15,2,"[NIVEA Soft Daily UV Light Moisturising Cream with SPF-15, Nivea Soft Daily UV Light Moisturising Cream With SPF-15]"
8745,nutrajcaliforniaalmondbadam,2,"[Nutraj California Almond | Badam, Nutraj California Almond/Badam]"
8753,nutrajclassickalimirchblackpepperpouch,2,"[Nutraj Classic Kali Mirch (Black Pepper) - Pouch, Nutraj Classic Kali Mirch | Black Pepper - Pouch]"
8961,oralbprohealthgumcaretoothbrushmedium,2,"[Oral B Pro Health Gum Care Toothbrush Medium, Oral-B Pro Health Gum Care Toothbrush Medium]"
9050,orionoricecrackerbakedkoreansnack,2,"[Orion O'Rice Cracker - Baked Korean Snack, Orion O'rice Cracker - Baked Korean Snack]"
9180,pantenehairsciencehairfallcontrolshampoolesserhairfallwithvitaminb,2,"[Pantene Hairscience Hairfall Control Shampoo Lesser Hairfall,With Vitaminb, Pantene Hairscience Hairfall Control Shampoo, Lesser Hair Fall With Vitamin B]"
9225,parachuteadvansedbhringrajhibiscusenrichedcoconuthairoil,2,"[Parachute Advansed Bhringraj & Hibiscus Enriched Coconut Hair Oil, Parachute Advansed Bhringraj & Hibiscus-Enriched Coconut Hair Oil]"
9247,parachuteadvansedrosemaryessentialoil100pureforthickvoluminoushair,2,"[Parachute Advansed Rosemary Essential Oil | 100% Pure | For Thick & Voluminous Hair, Parachute Advansed Rosemary Essential Oil | 100% Pure | for Thick & Voluminous Hair]"
9278,parasnandancowgheetetrapack,2,"[Paras Nandan Cow Ghee Tetra Pack, Paras Nandan Cow Ghee Tetrapack]"
9402,patanjalidantkantinaturaltoothpasteherbaloralcarefightscavitiesandgerms,3,"[Patanjali Dant Kanti Natural Toothpaste - Herbal Oral Care ,Fights Cavities and Germs, Patanjali Dant Kanti Natural Toothpaste - Herbal Oral Care, Fights Cavities and Germs, Patanjali Dant Kanti Natural Toothpaste - Herbal Oral Care,Fights Cavities and Germs]"
9460,peesafecomfortperiodpantylxl,2,"[Pee Safe Comfort Period Panty (L-XL), Pee Safe Comfort Period Panty L-XL]"
9701,pintolaallnaturalpeanutbuttercrunchy,2,"[Pintola All Natural Peanut Butter - Crunchy, Pintola All Natural Peanut Butter Crunchy]"
10832,skin1004madagascarcentellatonebrighteningcapsuleampoule,2,"[SKIN1004 Madagascar Centella Tone Brightening Capsule Ampoule, Skin1004 Madagascar Centella Tone Brightening Capsule Ampoule]"
11315,sundroppeanutbuttercrunchywith26proteinpremiumroastedpeanutsnopreservatives,2,"[Sundrop Peanut Butter | Crunchy | With 26% Protein | Premium Roasted Peanuts | No Preservatives, Sundrop Peanut Butter | Crunchy | With 26% Protein |Premium Roasted Peanuts | No Preservatives]"
11391,superbottomsnewborngiftset0to3months,2,"[Super Bottoms Newborn Gift Set | 0 to 3 Months, SuperBottoms Newborn Gift Set | 0 to 3 Months]"
11570,tatasampannpremiumkalmidatesrichinfibrenaturallysweetnaturallylowfatfood,2,"[Tata Sampann Premium Kalmi Dates Rich In Fibre Naturally Sweet Naturally Low-Fat Food, Tata Sampann Premium Kalmi Dates | Rich In Fibre | Naturally Sweet | Naturally Low-Fat Food]"
11587,tatasampannunpolishedtoordalarhardal,2,"[Tata Sampann Unpolished Toor Dal | Arhar Dal, Tata Sampann Unpolished Toor Dal/Arhar Dal]"
11645,tenalidoublehorseuraddalsplit,2,"[Tenali Double Horse Urad Dal - Split, Tenali Double Horse Urad Dal Split]"
11770,thedermaco1hyaluronicsunscreenspf50paaquagelfornormaltooilyskin,2,"[The Derma Co 1% Hyaluronic Sunscreen SPF 50 PA++++ Aqua Gel For Normal To Oily Skin, The Derma Co 1% Hyaluronic Sunscreen Spf 50 Pa+++ Aqua Gel For Normal To Oily Skin]"
11897,theobromazeromaidawholewheatbreadnopreservativesnopalmoil,2,"[Theobroma Zero Maida Whole Wheat Bread | No Preservatives | No Palm Oil, Theobroma Zero Maida Whole wheat bread | No Preservatives | No Palm Oil]"
12439,udhaiyamdhallmoong,2,"[Udhaiyam Dhall - Moong, Udhaiyam Dhall Moong]"
12589,vaselinecocoaglowseruminlotion100purecocoasheabutterforglowingsoftskin,2,"[Vaseline Cocoa Glow Serum In Lotion, 100% Pure Cocoa & Shea Butter for Glowing & Soft Skin, Vaseline Cocoa Glow Serum In Lotion100% Pure Cocoa & Shea Butter For Glowing & Soft Skin]"
12591,vaselinedeepmoisturebodylotionwithceramidehyaluron10xmoremoisturefordryskin,2,"[Vaseline Deep Moisture Body Lotion With Ceramide Hyaluron | 10X More Moisture | For Dry Skin, Vaseline Deep Moisture Body Lotion With Ceramide Hyaluron | 10X More Moisture| For Dry Skin]"
12640,veetpurehairremovalcreamnormalskin,2,"[Veet Pure Hair Removal Cream - Normal Skin, Veet Pure Hair Removal Cream Normal Skin]"
12641,veetpurehairremovalcreamsensitiveskin,2,"[Veet Pure Hair Removal Cream - Sensitive Skin, Veet Pure Hair Removal Cream Sensitive Skin]"
12683,vegasoftbristlebathbrushwithergonomichandleplasticcolormayvary,2,"[VEGA Soft Bristle Bath Brush With Ergonomic Handle | Plastic | Color May Vary, Vega Soft Bristle Bath Brush With Ergonomic Handle | Plastic | Color May Vary]"
12692,vegavhdh25goprohairdryerwithcoolshotbuttonrosegold2100w,2,"[VEGA Vhdh-25 Go Pro Hair Dryer With Cool Shot Button (Rose Gold, 2100 W), VEGA Vhdh-25 Go Pro Hair Dryer With Cool Shot Button (Rose Gold, 2100 W).]"
12826,vlccsandalcleansingmilk,2,"[VLCC Sandal Cleansing Milk, Vlcc Sandal Cleansing Milk]"
12974,whisperultraskinlovesoftsanitarypadsforwomenxl15napkins,2,"[Whisper Ultra Skin Love Soft Sanitary Pads for Women, XL 15 Napkins, Whisper Ultra Skin Love Soft Sanitary Pads for Women, XL+ 15 Napkins]"
12975,whisperultraskinlovesoftsanitarypadsforwomenxl30napkins,2,"[Whisper Ultra Skin Love Soft Sanitary Pads for Women, XL 30 Napkins, Whisper Ultra Skin Love Soft Sanitary Pads for Women, XL+ 30 Napkins]"
12977,whisperultrauptonogapnoleakssanitarypads15xlpadsbasedonpgtechnicaldata,2,"[Whisper Ultra Upto No Gap No Leaks Sanitary Pads, 15 XL Pads (Based on P&G Technical Data), Whisper Ultra Upto No Gap No Leaks Sanitary Pads, 15 XL+ Pads (Based on P&G Technical Data)]"
13051,wishcareceramidetintedlipbalmwithspf50pa5gwishcareceramidelipbalmwithspf50paforliplightening5gnatural25gcombo,2,"[Wishcare Ceramide Tinted Lip Balm With Spf50 Pa++ (5g) & Wishcare Ceramide Lip Balm With Spf50 Pa++ For Lip Lightening 5G Natural 2 (5g) Combo, Wishcare Ceramide Tinted Lip Balm With Spf50 Pa+++ (5g) & Wishcare Ceramide Lip Balm With Spf50 Pa+++ For Lip Lightening - 5G - Natural 2\ (5g) Combo]"
13055,wishcarehairgrowthserumconcentrateresdensylanagaincaffeinebiotinkeratinricewater,2,"[WishCare Hair Growth Serum Concentrate Resdensyl, Anagain, Caffeine, Biotin, Keratin, Rice Water, WishCare Hair Growth Serum Concentrate-Resdensyl,Anagain,Caffeine,Biotin, Keratin & Rice Water]"

In [9]:
df[df.product_name == "VLCC Sandal Cleansing Milk"]

,crawl_date_and_time,platform_name,store_id,store_name_location,city,pin_code,unique_id,product_id_upc_ean,department,category,sub_category,product_type,brand_name,product_name,product_description,product_grammage,package_type,net_quantity,variants,item_mrp,item_selling_price,out_of_stock_flag,discount_flag,product_price,unit_price,promo_offer_description,promo_offer_price,discount_in_percent,stock_count,product_url,product_image_urls,productname_norm
46326,2026-07-15 00:38:34,zepto,49879539-9538-42ca-b59e-952cdd73b506,"Dlpluxury PG For Ladies, 10th 'A' Mian Rd, 3rd Cross, Near Metro Station Indira Nagar, Stage 1, IndiraNagar, Bengaluru, Karnataka, 560038, India",Bangalore,560038,5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,ea872077-330c-4343-ade6-ff5c5ac28a7f,Personal Care,Skincare,Face Wash & Scrubs,NaN,VLCC,VLCC Sandal Cleansing Milk,NaN,500 ml,NaN,1 pc (500 ml),"['500 ml', '100 ml']",549.0,458.0,No,Yes,458.0,NaN,₹91 OFF,458.0,16,2,https://www.zepto.com/pn/vlcc-sandal-cleansing-milk/pvid/5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,NaN,vlccsandalcleansingmilk
48580,2026-07-15 00:39:56,zepto,843e630a-7896-462d-b7cf-712140483ed3,"Tara Cafe, 72, 80 Feet Rd, Koramangala 7 Block, 7th Block, Koramangala, Bengaluru, Karnataka, 560095, India",Bangalore,560095,5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,ea872077-330c-4343-ade6-ff5c5ac28a7f,Personal Care,Skincare,Face Wash & Scrubs,NaN,VLCC,VLCC Sandal Cleansing Milk,NaN,500 ml,NaN,1 pc (500 ml),"['500 ml', '100 ml']",549.0,435.0,No,Yes,435.0,NaN,₹114 OFF,435.0,20,2,https://www.zepto.com/pn/vlcc-sandal-cleansing-milk/pvid/5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,NaN,vlccsandalcleansingmilk
53564,2026-07-15 00:44:12,zepto,e052e083-dbfe-4156-a86e-e2fd848f8c3e,"Herz Kitchen, Taj Residency, Ashok Vihar Colony, Upperpally, Pillar No 195, Near Sai Baba Temple, Ashok Vihar Colony, Fort View Colony, Janachaitanya Colony, Hyderabad, Telangana, 500030, India",Hyderabad,500030,5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,ea872077-330c-4343-ade6-ff5c5ac28a7f,Personal Care,Skincare,Face Wash & Scrubs,NaN,VLCC,VLCC Sandal Cleansing Milk,NaN,500 ml,NaN,1 pc (500 ml),"['500 ml', '100 ml']",549.0,406.0,No,Yes,406.0,NaN,₹143 OFF,406.0,26,1,https://www.zepto.com/pn/vlcc-sandal-cleansing-milk/pvid/5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,NaN,vlccsandalcleansingmilk
58830,2026-07-15 00:48:39,zepto,1c9e155e-83a8-457a-a687-01eabb1e7a36,"CoLive Medford PG In Marathahalli Bengaluru, Bldg No 3, Sai Baba Temple Rd, Near Bombay Kulfi, Green Garden Layout, Munekolala, Marathahalli, Bengaluru, Karnataka, 560037, India",Bangalore,560037,5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,ea872077-330c-4343-ade6-ff5c5ac28a7f,Personal Care,Skincare,Face Wash & Scrubs,NaN,VLCC,VLCC Sandal Cleansing Milk,NaN,500 ml,NaN,1 pc (500 ml),"['500 ml', '100 ml']",549.0,458.0,No,Yes,458.0,NaN,₹91 OFF,458.0,16,2,https://www.zepto.com/pn/vlcc-sandal-cleansing-milk/pvid/5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,NaN,vlccsandalcleansingmilk
59429,2026-07-15 00:49:08,zepto,803931bb-511e-48bc-8611-4b9910682bb4,"F Salon By FTV Andheri, Mohit Tower, 4, K D Gaikwad Road, Bhudargarh Colony, K/w Ward, Zone 3, Mumbai Suburban, Maharashtra, 400053, India",Mumbai,400053,5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,ea872077-330c-4343-ade6-ff5c5ac28a7f,Personal Care,Skincare,Face Wash & Scrubs,NaN,VLCC,VLCC Sandal Cleansing Milk,NaN,500 ml,NaN,1 pc (500 ml),"['500 ml', '100 ml']",549.0,505.0,No,Yes,505.0,NaN,₹44 OFF,505.0,8,2,https://www.zepto.com/pn/vlcc-sandal-cleansing-milk/pvid/5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,NaN,vlccsandalcleansingmilk
61098,2026-07-15 00:50:21,zepto,2175898f-b70e-46d9-8def-aba7f0745662,"C.B. Chajed & Company, Old Prabhadevi Rd, Dadar West, Century Bazaar, Prabhadevi, Mumbai, Maharashtra, 400025, India",Mumbai,400025,5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,ea872077-330c-4343-ade6-ff5c5ac28a7f,Personal Care,Skincare,Face Wash & Scrubs,NaN,VLCC,VLCC Sandal Cleansing Milk,NaN,500 ml,NaN,1 pc (500 ml),"['500 ml', '100 ml']",549.0,442.0,Yes,Yes,442.0,NaN,₹107 OFF,442.0,19,0,https://www.zepto.com/pn/vlcc-sandal-cleansing-milk/pvid/5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,NaN,vlccsandalcleansingmilk
61518,2026-07-15 00:50:41,zepto,b0a2db37-733d-46d1-808b-7af068fc7f8a,"Kavitha Ladies Tailor, Medchal Mandal, MedchalÃ£Â¢Ã¢ÂÃ¢Âmalkajgiri, Telangana, 500100, India",Hyderabad,500100,5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,ea872077-330c-4343-ade6-ff5c5ac28a7f,Personal Care,Skincare,Face Wash & Scrubs,NaN,VLCC,VLCC Sandal Cleansing Milk,NaN,500 ml,NaN,1 pc (500 ml),"['500 ml', '100 ml']",549.0,522.0,No,Yes,522.0,NaN,₹27 OFF,522.0,4,2,https://www.zepto.com/pn/vlcc-sandal-cleansing-milk/pvid/5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,NaN,vlccsandalcleansingmilk
62120,2026-07-15 00:51:05,zepto,1cf40b2e-95cd-4581-9ab9-bca81d4932ab,"Agra Road Industrial Premises Co-Operative Society Limited, Shop No, 82, Amrut Nagar Rd, Near Ghatkopar, Agra Industrial Estate, Ghatkopar West, Mumbai, Maharashtra, 400076, India",Mumbai,400076,5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,ea872077-330c-4343-ade6-ff5c5ac28a7f,Personal Care,Skincare,Face Wash & Scrubs,NaN,VLCC,VLCC Sandal Cleansing Milk,NaN,500 ml,NaN,1 pc (500 ml),"['500 ml', '100 ml']",549.0,505.0,Yes,Yes,505.0,NaN,₹44 OFF,505.0,8,0,https://www.zepto.com/pn/vlcc-sandal-cleansing-milk/pvid/5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,NaN,vlccsandalcleansingmilk
82460,2026-07-15 01:09:38,zepto,33a1d02e-1bb7-44cc-8d38-9697bcc23dba,"AISECT Office & Education Centre Hyderabad, Gayathri's Sri Sai Enclave, 3Floor, Musheerabad Main Rd, Musheerabad, Dayara, Hyderabad, Telangana, 500020, India",Hyderabad,500020,5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,ea872077-330c-4343-ade6-ff5c5ac28a7f,Personal Care,Skincare,Face Wash & Scrubs,NaN,VLCC,VLCC Sandal Cleansing Milk,NaN,500 ml,NaN,1 pc (500 ml),"['500 ml', '100 ml']",549.0,522.0,Yes,Yes,522.0,NaN,₹27 OFF,522.0,4,0,https://www.zepto.com/pn/vlcc-sandal-cleansing-milk/pvid/5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,NaN,vlccsandalcleansingmilk
117896,2026-07-15 01:42:21,zepto,76cae5a0-b75d-456b-9aab-df0b0b7559c2,"Nd Laurel, Apartment, N D Laurel, State Highway 35, Vinayaka Nagar, Gunjur Village, SH 35, Vinayaka Nagar, Gunjur Village, Bengaluru, Karnataka, 560087, India",Bangalore,560087,5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,ea872077-330c-4343-ade6-ff5c5ac28a7f,Personal Care,Skincare,Face Wash & Scrubs,NaN,VLCC,VLCC Sandal Cleansing Milk,NaN,500 ml,NaN,1 pc (500 ml),"['500 ml', '100 ml']",549.0,458.0,No,Yes,458.0,NaN,₹91 OFF,458.0,16,2,https://www.zepto.com/pn/vlcc-sandal-cleansing-milk/pvid/5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,NaN,vlccsandalcleansingmilk
136281,2026-07-15 02:12:15,zepto,fc05177a-ca9e-4c93-9811-dbb101b0c8f7,"Gagan Gift Collection, Bisrakh Rd, Sector 1, Greater Noida, Uttar Pradesh, 203207, India",Greater Noida,203207,5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,ea872077-330c-4343-ade6-ff5c5ac28a7f,Personal Care,Skincare,Face Wash & Scrubs,NaN,VLCC,VLCC Sandal Cleansing Milk,NaN,500 ml,NaN,1 pc (500 ml),"['500 ml', '100 ml']",549.0,505.0,No,Yes,505.0,NaN,₹44 OFF,505.0,8,3,https://www.zepto.com/pn/vlcc-sandal-cleansing-milk/pvid/5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,NaN,vlccsandalcleansingmilk
138026,2026-07-15 02:17:21,zepto,8a278c72-1366-4926-b81e-ecc6e64df2a7,"Changes Advertising, D-2, Rameshwar S V Road, Santacruz West, Railway Colony, Santacruz West, Mumbai, Maharashtra, 400054, India",Mumbai,400054,5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,ea872077-330c-4343-ade6-ff5c5ac28a7f,Personal Care,Skincare,Face Wash & Scrubs,NaN,VLCC,VLCC Sandal Cleansing Milk,NaN,500 ml,NaN,1 pc (500 ml),"['500 ml', '100 ml']",549.0,505.0,Yes,Yes,505.0,NaN,₹44 OFF,505.0,8,0,https://www.zepto.com/pn/vlcc-sandal-cleansing-milk/pvid/5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,NaN,vlccsandalcleansingmilk
138030,2026-07-15 02:17:23,zepto,d4205b92-165a-4ad5-89c1-f857521a047f,"DRR Foundation, 530, Akshaya Tower, 3rd Floor 5th Cross, HMT Layout, Opp. RT Nagar, Police Station, Bilappa Garden, R.T Nagar, Bengaluru, Karnataka, 560032, India",Bangalore,560032,5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,ea872077-330c-4343-ade6-ff5c5ac28a7f,Personal Care,Skincare,Face Wash & Scrubs,NaN,VLCC,VLCC Sandal Cleansing Milk,NaN,500 ml,NaN,1 pc (500 ml),"['500 ml', '100 ml']",549.0,458.0,No,Yes,458.0,NaN,₹91 OFF,458.0,16,2,https://www.zepto.com/pn/vlcc-sandal-cleansing-milk/pvid/5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,NaN,vlccsandalcleansingmilk
160008,2026-07-15 02:42:27,zepto,6252e437-b1f6-4ea7-9062-d90fba216c6f,"Blinkit Kannamangla Main Road, Unit-7, WayCool Foods Bangalore DC, Kannamangala Main Rd, Ardendale, Kannamangala, Karnataka, 560115, India",Bangalore,560115,5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,ea872077-330c-4343-ade6-ff5c5ac28a7f,Personal Care,Skincare,Face Wash & Scrubs,NaN,VLCC,VLCC Sandal Cleansing Milk,NaN,500 ml,NaN,1 pc (500 ml),"['500 ml', '100 ml']",499.0,438.0,No,Yes,438.0,NaN,₹61 OFF,438.0,12,2,https://www.zepto.com/pn/vlcc-sandal-cleansing-milk/pvid/5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,NaN,vlccsandalcleansingmilk
166278,2026-07-15 02:45:04,zepto,477d50e9-2c13-435c-8db4-dd0077b4ab2e,"Biswas Curry Point- Odia Hotel, Srinivasa Nagar, Ameerpet, Hyderabad, Telangana, 500038, India",Hyderabad,500038,5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,ea872077-330c-4343-ade6-ff5c5ac28a7f,Personal Care,Skincare,Face Wash & Scrubs,NaN,VLCC,VLCC Sandal Cleansing Milk,NaN,500 ml,NaN,1 pc (500 ml),"['500 ml', '100 ml']",549.0,522.0,No,Yes,522.0,NaN,₹27 OFF,522.0,4,1,https://www.zepto.com/pn/vlcc-sandal-cleansing-milk/pvid/5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,NaN,vlccsandalcleansingmilk
198351,2026-07-15 02:57:23,zepto,778b5c2b-0468-4f1e-8fa0-241cc91608a2,"Zepto Tarnaka, Nacharam - Mallapur Rd, Industrial Development Area, Nacharam, Secunderabad, Telangana, 500076, India",Hyderabad,500076,5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,ea872077-330c-4343-ade6-ff5c5ac28a7f,Personal Care,Skincare,Face Wash & Scrubs,NaN,VLCC,VLCC Sandal Cleansing Milk,NaN,500 ml,NaN,1 pc (500 ml),"['500 ml', '100 ml']",549.0,446.0,No,Yes,446.0,NaN,₹103 OFF,446.0,18,2,https://www.zepto.com/pn/vlcc-sandal-cleansing-milk/pvid/5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,NaN,vlccsandalcleansingmilk
200086,2026-07-15 02:57:59,zepto,4c93e224-40da-4c86-a5ff-c9c2cfee1168,"Sree Amrutha Junior College, Friends Colony Rd, Opposite Nayara Petrol Pump, Gayatri Nagar, Allapur, Borabanda, Hyderabad, Telangana, 500018, India",Hyderabad,500018,5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,ea872077-330c-4343-ade6-ff5c5ac28a7f,Personal Care,Skincare,Face Wash & Scrubs,NaN,VLCC,VLCC Sandal Cleansing Milk,NaN,500 ml,NaN,1 pc (500 ml),"['500 ml', '100 ml']",549.0,522.0,Yes,Yes,522.0,NaN,₹27 OFF,522.0,4,0,https://www.zepto.com/pn/vlcc-sandal-cleansing-milk/pvid/5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,NaN,vlccsandalcleansingmilk
200496,2026-07-15 02:58:08,zepto,0059ff6a-7eb0-477a-a7f5-69256f2c444b,"Raymondz EnterPrises, Nagondanahalli, Bengaluru, Karnataka, 560066, India",Bangalore,560066,5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,ea872077-330c-4343-ade6-ff5c5ac28a7f,Personal Care,Skincare,Face Wash & Scrubs,NaN,VLCC,VLCC Sandal Cleansing Milk,NaN,500 ml,NaN,1 pc (500 ml),"['500 ml', '100 ml']",549.0,458.0,No,Yes,458.0,NaN,₹91 OFF,458.0,16,2,https://www.zepto.com/pn/vlcc-sandal-cleansing-milk/pvid/5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,NaN,vlccsandalcleansingmilk
208186,2026-07-15 03:01:34,zepto,38caa147-31a6-4fae-a5b6-1c21d1bbfa1d,"Villa-1, Vishwam Inside Out Villas, Doddakannelli, Bengaluru, Karnataka, 560035, India",Bangalore,560035,5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,ea872077-330c-4343-ade6-ff5c5ac28a7f,Personal Care,Skincare,Face Wash & Scrubs,NaN,VLCC,VLCC Sandal Cleansing Milk,NaN,500 ml,NaN,1 pc (500 ml),"['500 ml', '100 ml']",549.0,458.0,No,Yes,458.0,NaN,₹91 OFF,458.0,16,2,https://www.zepto.com/pn/vlcc-sandal-cleansing-milk/pvid/5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,NaN,vlccsandalcleansingmilk
210145,2026-07-15 03:02:30,zepto,e879c6cf-e4bd-4b11-a605-4e9b2ee2365d,"Pride Plaza Hotel Kolkata, Service Rd, Opposite To Novotel, BG Block(newtown), Action Area I, NewTown, New Town, West Bengal, 700156, India",Kolkata,700156,5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,ea872077-330c-4343-ade6-ff5c5ac28a7f,Personal Care,Skincare,Face Wash & Scrubs,NaN,VLCC,VLCC Sandal Cleansing Milk,NaN,500 ml,NaN,1 pc (500 ml),"['500 ml', '100 ml']",549.0,442.0,Yes,Yes,442.0,NaN,₹107 OFF,442.0,19,0,https://www.zepto.com/pn/vlcc-sandal-cleansing-milk/pvid/5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,NaN,vlccsandalcleansingmilk
210589,2026-07-15 03:02:39,zepto,b7e326da-7679-428a-82b4-6cc1d91518ac,"Marathon Monte Carlo, Opposite P&t Colony, Near Samriddhi Banquet Hall, Off LBS Rd, Madan Mohan Malviya Road, Asha Nagar, Mulund West, Mumbai, Maharashtra, 400080, India",Mumbai,400080,5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,ea872077-330c-4343-ade6-ff5c5ac28a7f,Personal Care,Skincare,Face Wash & Scrubs,NaN,VLCC,VLCC Sandal Cleansing Milk,NaN,500 ml,NaN,1 pc (500 ml),"['500 ml', '100 ml']",549.0,505.0,No,Yes,505.0,NaN,₹44 OFF,505.0,8,1,https://www.zepto.com/pn/vlcc-sandal-cleansing-milk/pvid/5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,NaN,vlccsandalcleansingmilk
211691,2026-07-15 03:03:15,zepto,a7c548c8-f8e5-41c6-9462-1b4d7e8de41e,"Cut & Style Salon - Haralur Road, Bengaluru, 42 Haralur Road, 2nd Ave, Opposite HP Petrol Pump, Ambalipura, Bengaluru, Haralur, Karnataka, 560103, India",Bangalore,560103,5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,ea872077-330c-4343-ade6-ff5c5ac28a7f,Personal Care,Skincare,Face Wash & Scrubs,NaN,VLCC,VLCC Sandal Cleansing Milk,NaN,500 ml,NaN,1 pc (500 ml),"['500 ml', '100 ml']",549.0,458.0,No,Yes,458.0,NaN,₹91 OFF,458.0,16,2,https://www.zepto.com/pn/vlcc-sandal-cleansing-milk/pvid/5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,NaN,vlccsandalcleansingmilk
222250,2026-07-15 03:07:47,zepto,2614cabb-fff2-4ef6-aa5b-e94c2b875880,"Kamakshi Foods, No 15/1, 10th Main Rd, Revenue Extension, Kadarenahalli, Padmanabhanagar, Bengaluru, Karnataka, 560070, India",Bangalore,560070,5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,ea872077-330c-4343-ade6-ff5c5ac28a7f,Personal Care,Skincare,Face Wash & Scrubs,NaN,VLCC,VLCC Sandal Cleansing Milk,NaN,500 ml,NaN,1 pc (500 ml),"['500 ml', '100 ml']",549.0,458.0,No,Yes,458.0,NaN,₹91 OFF,458.0,16,2,https://www.zepto.com/pn/vlcc-sandal-cleansing-milk/pvid/5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,NaN,vlccsandalcleansingmilk
228833,2026-07-15 03:10:41,zepto,b812518e-9cc3-45e3-8fef-a1dd3311194c,"Green Fitness Club(camp Road), No 2, Sri Ram Nagar 4th Street, Seliyur, Post, Nazeeb Avenue, Tambaram, Chennai, Tamil Nadu, 600064, India",Chennai,600064,5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,ea872077-330c-4343-ade6-ff5c5ac28a7f,Personal Care,Skincare,Face Wash & Scrubs,NaN,VLCC,VLCC Sandal Cleansing Milk,NaN,500 ml,NaN,1 pc (500 ml),"['500 ml', '100 ml']",549.0,440.0,No,Yes,440.0,NaN,₹109 OFF,440.0,19,1,https://www.zepto.com/pn/vlcc-sandal-cleansing-milk/pvid/5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,NaN,vlccsandalcleansingmilk
277656,2026-07-15 03:33:02,zepto,abd85a95-f3f3-42fd-aeb0-71b9127335f5,"GFC Gowdru Biriyani, 20, Teachers Colony, Chikkabidarakallu, Bengaluru, Karnataka, 560073, India",Bangalore,560073,5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,ea872077-330c-4343-ade6-ff5c5ac28a7f,Personal Care,Skincare,Face Wash & Scrubs,NaN,VLCC,VLCC Sandal Cleansing Milk,NaN,500 ml,NaN,1 pc (500 ml),"['500 ml', '100 ml']",549.0,458.0,No,Yes,458.0,NaN,₹91 OFF,458.0,16,2,https://www.zepto.com/pn/vlcc-sandal-cleansing-milk/pvid/5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,NaN,vlccsandalcleansingmilk
286924,2026-07-15 03:37:34,zepto,95d6c1a2-b071-4cf3-a322-30b5754d7cb6,"Zepto Store, Phatak Rd, Bhayandar, Vikas Industrial Estate, Bhayandar East, Mira Bhayandar, Maharashtra 401105, India",Mumbai,401105,5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,ea872077-330c-4343-ade6-ff5c5ac28a7f,Personal Care,Skincare,Face Wash & Scrubs,NaN,VLCC,VLCC Sandal Cleansing Milk,NaN,500 ml,NaN,1 pc (500 ml),"['500 ml', '100 ml']",549.0,442.0,Yes,Yes,442.0,NaN,₹107 OFF,442.0,19,0,https://www.zepto.com/pn/vlcc-sandal-cleansing-milk/pvid/5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,NaN,vlccsandalcleansingmilk
300415,2026-07-15 03:43:57,zepto,8d94ae95-db29-44f7-b705-d533f7c66176,"9 Star Family Restaurant & Bakers, Bachupally, Hyderabad, Telangana, 500090, India",Hyderabad,500090,5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,ea872077-330c-4343-ade6-ff5c5ac28a7f,Personal Care,Skincare,Face Wash & Scrubs,NaN,VLCC,VLCC Sandal Cleansing Milk,NaN,500 ml,NaN,1 pc (500 ml),"['500 ml', '100 ml']",549.0,446.0,No,Yes,446.0,NaN,₹103 OFF,446.0,18,2,https://www.zepto.com/pn/vlcc-sandal-cleansing-milk/pvid/5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,NaN,vlccsandalcleansingmilk
313671,2026-07-15 03:49:44,zepto,de95e00b-0ebf-4f65-8f27-df66fd91dc13,"Narsinigi Methodist Church, Narsingi - Puppalaguda Main Rd, Narsingi, Hyderabad, Telangana, 500089, India",Hyderabad,500089,5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,ea872077-330c-4343-ade6-ff5c5ac28a7f,Personal Care,Skincare,Face Wash & Scrubs,NaN,VLCC,VLCC Sandal Cleansing Milk,NaN,500 ml,NaN,1 pc (500 ml),"['500 ml', '100 ml']",549.0,522.0,Yes,Yes,522.0,NaN,₹27 OFF,522.0,4,0,https://www.zepto.com/pn/vlcc-sandal-cleansing-milk/pvid/5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,NaN,vlccsandalcleansingmilk
323370,2026-07-15 03:54:08,zepto,774a725c-2c4b-4dc2-94d1-72b737f7e1f6,"Ramanuja Credit Co Op Soc Limited, No 22, Seshadri Rd, Lakshmanpuri, Gandhi Nagar, Bengaluru, Karnataka, 560009, India",Bangalore,560009,5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,ea872077-330c-4343-ade6-ff5c5ac28a7f,Personal Care,Skincare,Face Wash & Scrubs,NaN,VLCC,VLCC Sandal Cleansing Milk,NaN,500 ml,NaN,1 pc (500 ml),"['500 ml', '100 ml']",549.0,458.0,No,Yes,458.0,NaN,₹91 OFF,458.0,16,2,https://www.zepto.com/pn/vlcc-sandal-cleansing-milk/pvid/5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,NaN,vlccsandalcleansingmilk
331410,2026-07-15 03:57:00,zepto,eacc5aad-4e93-4266-8cde-bee3b70926a8,"Semitonic Studios, 15, Behind The Big Market, Hennur Main Road, Post, Kothanur, Bengaluru, Karnataka, 560077, India",Bangalore,560077,5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,ea872077-330c-4343-ade6-ff5c5ac28a7f,Personal Care,Skincare,Face Wash & Scrubs,NaN,VLCC,VLCC Sandal Cleansing Milk,NaN,500 ml,NaN,1 pc (500 ml),"['500 ml', '100 ml']",549.0,458.0,No,Yes,458.0,NaN,₹91 OFF,458.0,16,2,https://www.zepto.com/pn/vlcc-sandal-cleansing-milk/pvid/5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,NaN,vlccsandalcleansingmilk
354453,2026-07-15 04:07:14,zepto,a9588bc2-3d75-410c-88c3-ec029bf4593a,"Asha Turf, Press Bazar, Ulhasnagar, Maharashtra, 421002, India",Mumbai,421002,5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,ea872077-330c-4343-ade6-ff5c5ac28a7f,Personal Care,Skincare,Face Wash & Scrubs,NaN,VLCC,VLCC Sandal Cleansing Milk,NaN,500 ml,NaN,1 pc (500 ml),"['500 ml', '100 ml']",549.0,442.0,Yes,Yes,442.0,NaN,₹107 OFF,442.0,19,0,https://www.zepto.com/pn/vlcc-sandal-cleansing-milk/pvid/5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,NaN,vlccsandalcleansingmilk
360962,2026-07-15 04:10:31,zepto,a7860f3d-39d4-4275-811d-904d4c2438f4,"Alackrity Consols Private Limited, Venkateshwara Temple, 447/B, 9th Cross Rd, Near Lakshmi, 2nd Phase, J. P. Nagar, Bengaluru, Karnataka 560078, India",Bangalore,560078,5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,ea872077-330c-4343-ade6-ff5c5ac28a7f,Personal Care,Skincare,Face Wash & Scrubs,NaN,VLCC,VLCC Sandal Cleansing Milk,NaN,500 ml,NaN,1 pc (500 ml),"['500 ml', '100 ml']",549.0,458.0,No,Yes,458.0,NaN,₹91 OFF,458.0,16,2,https://www.zepto.com/pn/vlcc-sandal-cleansing-milk/pvid/5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,NaN,vlccsandalcleansingmilk
361019,2026-07-15 04:10:35,zepto,21db1e24-d6a7-484a-b5aa-b43e1aafb8fc,"Divine Banquets, C, 616, RDP 10, Chikoowadi, Borivali West, Mumbai, Maharashtra, 400091, India",Mumbai,400091,5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,ea872077-330c-4343-ade6-ff5c5ac28a7f,Personal Care,Skincare,Face Wash & Scrubs,NaN,VLCC,VLCC Sandal Cleansing Milk,NaN,500 ml,NaN,1 pc (500 ml),"['500 ml', '100 ml']",549.0,505.0,No,Yes,505.0,NaN,₹44 OFF,505.0,8,2,https://www.zepto.com/pn/vlcc-sandal-cleansing-milk/pvid/5ca51392-f225-4b37-bd1f-1c3b1ba5bad9,NaN,vlccsandalcleansingmilk

In [15]:
df[df.unique_id == "02ff8196-ec66-43e4-8a45-7d56ec8a3e0b"]

,crawl_date_and_time,platform_name,store_id,store_name_location,city,pin_code,unique_id,product_id_upc_ean,department,category,sub_category,product_type,brand_name,product_name,product_description,product_grammage,package_type,net_quantity,variants,item_mrp,item_selling_price,out_of_stock_flag,discount_flag,product_price,unit_price,promo_offer_description,promo_offer_price,discount_in_percent,stock_count,product_url,product_image_urls,productname_norm,brand_norm
5145,2026-07-15 00:07:42,zepto,471b6b1b-6289-47bf-ac72-a61684f86181,"Treebo Trend Savera Grand, 26-6-11, Babu Rajendra Prasad Rd, Papaiah Veedhi, Gandhi Nagar, Vijayawada, Andhra Pradesh, 520003, India",Vijayawada,520003,02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,e6db6618-386e-4a0b-8805-0501571c48eb,Bakery & Biscuits,Biscuits,Crackers,NaN,Malkist,Malkist Cheese Flavoured Crunchy Crackers | Trans Fat-free Combo,NaN,NaN,NaN,144 g X 2,NaN,120.0,114.0,No,Yes,114.0,NaN,₹6 OFF,114.0,5,1,https://www.zepto.com/pn/malkist-cheese-flavoured-crunchy-crackers-trans-fat-free-combo/pvid/02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,NaN,malkistcheeseflavouredcrunchycrackerstransfatfreecombo,malkist
6073,2026-07-15 00:08:08,zepto,7de4838b-ae7c-44d0-bf24-fb2040666654,"Dlpluxury PG For Ladies, 10th 'A' Mian Rd, 3rd Cross, Near Metro Station Indira Nagar, Stage 1, IndiraNagar, Bengaluru, Karnataka, 560038, India",Bangalore,560038,02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,e6db6618-386e-4a0b-8805-0501571c48eb,Bakery & Biscuits,Biscuits,Crackers,NaN,Malkist,Malkist Cheese Flavoured Crunchy Crackers | Trans Fat-free Combo,NaN,NaN,NaN,144 g X 2,NaN,120.0,114.0,No,Yes,114.0,NaN,₹6 OFF,114.0,5,6,https://www.zepto.com/pn/malkist-cheese-flavoured-crunchy-crackers-trans-fat-free-combo/pvid/02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,NaN,malkistcheeseflavouredcrunchycrackerstransfatfreecombo,malkist
7651,2026-07-15 00:09:20,zepto,75946a5e-942e-4db1-9e7c-5fe2eb85088b,"552, Outer Ring Rd, Opposite More Mega Store, Mahadevapura, Bengaluru, Karnataka, 560016, India",Bangalore,560016,02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,e6db6618-386e-4a0b-8805-0501571c48eb,Bakery & Biscuits,Biscuits,Crackers,NaN,Malkist,Malkist Cheese Flavoured Crunchy Crackers | Trans Fat-free Combo,NaN,NaN,NaN,144 g X 2,NaN,120.0,114.0,No,Yes,114.0,NaN,₹6 OFF,114.0,5,6,https://www.zepto.com/pn/malkist-cheese-flavoured-crunchy-crackers-trans-fat-free-combo/pvid/02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,NaN,malkistcheeseflavouredcrunchycrackerstransfatfreecombo,malkist
13231,2026-07-15 00:12:43,zepto,913e4d9c-179c-43fc-b130-b0c9c39d3800,"Divya Jyoti Eye Hospital, Lingarajnagar North, Hubli, Karnataka, 580031, India",Hubballi,580031,02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,e6db6618-386e-4a0b-8805-0501571c48eb,Bakery & Biscuits,Biscuits,Crackers,NaN,Malkist,Malkist Cheese Flavoured Crunchy Crackers | Trans Fat-free Combo,NaN,NaN,NaN,144 g X 2,NaN,120.0,114.0,No,Yes,114.0,NaN,₹6 OFF,114.0,5,6,https://www.zepto.com/pn/malkist-cheese-flavoured-crunchy-crackers-trans-fat-free-combo/pvid/02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,NaN,malkistcheeseflavouredcrunchycrackerstransfatfreecombo,malkist
16107,2026-07-15 00:15:33,zepto,425e2ef0-02bc-4c87-b423-cfbc6e56984a,"CoLive Medford PG In Marathahalli Bengaluru, Bldg No 3, Sai Baba Temple Rd, Near Bombay Kulfi, Green Garden Layout, Munekolala, Marathahalli, Bengaluru, Karnataka, 560037, India",Bangalore,560037,02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,e6db6618-386e-4a0b-8805-0501571c48eb,Bakery & Biscuits,Biscuits,Crackers,NaN,Malkist,Malkist Cheese Flavoured Crunchy Crackers | Trans Fat-free Combo,NaN,NaN,NaN,144 g X 2,NaN,120.0,114.0,No,Yes,114.0,NaN,₹6 OFF,114.0,5,6,https://www.zepto.com/pn/malkist-cheese-flavoured-crunchy-crackers-trans-fat-free-combo/pvid/02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,NaN,malkistcheeseflavouredcrunchycrackerstransfatfreecombo,malkist
20042,2026-07-15 00:19:07,zepto,8be2198a-76dd-42c7-a351-d1c2b80d459e,"F Salon By FTV Andheri, Mohit Tower, 4, K D Gaikwad Road, Bhudargarh Colony, K/w Ward, Zone 3, Mumbai Suburban, Maharashtra, 400053, India",Mumbai,400053,02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,e6db6618-386e-4a0b-8805-0501571c48eb,Bakery & Biscuits,Biscuits,Crackers,NaN,Malkist,Malkist Cheese Flavoured Crunchy Crackers | Trans Fat-free Combo,NaN,NaN,NaN,144 g X 2,NaN,120.0,114.0,No,Yes,114.0,NaN,₹6 OFF,114.0,5,6,https://www.zepto.com/pn/malkist-cheese-flavoured-crunchy-crackers-trans-fat-free-combo/pvid/02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,NaN,malkistcheeseflavouredcrunchycrackerstransfatfreecombo,malkist
22416,2026-07-15 00:21:15,zepto,72655f9e-d9be-4b01-b2ac-62e61d2efd47,"C.B. Chajed & Company, Old Prabhadevi Rd, Dadar West, Century Bazaar, Prabhadevi, Mumbai, Maharashtra, 400025, India",Mumbai,400025,02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,e6db6618-386e-4a0b-8805-0501571c48eb,Bakery & Biscuits,Biscuits,Crackers,NaN,Malkist,Malkist Cheese Flavoured Crunchy Crackers | Trans Fat-free Combo,NaN,NaN,NaN,144 g X 2,NaN,120.0,114.0,No,Yes,114.0,NaN,₹6 OFF,114.0,5,6,https://www.zepto.com/pn/malkist-cheese-flavoured-crunchy-crackers-trans-fat-free-combo/pvid/02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,NaN,malkistcheeseflavouredcrunchycrackerstransfatfreecombo,malkist
36298,2026-07-15 00:30:43,zepto,4942530d-03e3-44f5-ba28-30c05c238e24,"Ash Grill, 11/1, Kamarajar Road, SaiBaba Colony, Coimbatore, 641043, India",Coimbatore,641043,02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,e6db6618-386e-4a0b-8805-0501571c48eb,Bakery & Biscuits,Biscuits,Crackers,NaN,Malkist,Malkist Cheese Flavoured Crunchy Crackers | Trans Fat-free Combo,NaN,NaN,NaN,144 g X 2,NaN,120.0,114.0,No,Yes,114.0,NaN,₹6 OFF,114.0,5,4,https://www.zepto.com/pn/malkist-cheese-flavoured-crunchy-crackers-trans-fat-free-combo/pvid/02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,NaN,malkistcheeseflavouredcrunchycrackerstransfatfreecombo,malkist
44116,2026-07-15 00:36:36,zepto,51e91140-ab27-4854-959e-b8e0b9b50b3b,"Sheela Industries, Karnal, Haryana, 132001, India",Karnal,132001,02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,e6db6618-386e-4a0b-8805-0501571c48eb,Bakery & Biscuits,Biscuits,Crackers,NaN,Malkist,Malkist Cheese Flavoured Crunchy Crackers | Trans Fat-free Combo,NaN,NaN,NaN,144 g X 2,NaN,120.0,114.0,No,Yes,114.0,NaN,₹6 OFF,114.0,5,3,https://www.zepto.com/pn/malkist-cheese-flavoured-crunchy-crackers-trans-fat-free-combo/pvid/02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,NaN,malkistcheeseflavouredcrunchycrackerstransfatfreecombo,malkist
78571,2026-07-15 01:06:37,zepto,5c849951-0ba3-4878-9b29-eb2d3ef252eb,"88, Vesu Canal Rd, Ambanagar, Surat, Gujarat, 395001, India",Surat,395001,02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,e6db6618-386e-4a0b-8805-0501571c48eb,Bakery & Biscuits,Biscuits,Crackers,NaN,Malkist,Malkist Cheese Flavoured Crunchy Crackers | Trans Fat-free Combo,NaN,NaN,NaN,144 g X 2,NaN,120.0,114.0,No,Yes,114.0,NaN,₹6 OFF,114.0,5,1,https://www.zepto.com/pn/malkist-cheese-flavoured-crunchy-crackers-trans-fat-free-combo/pvid/02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,NaN,malkistcheeseflavouredcrunchycrackerstransfatfreecombo,malkist
81246,2026-07-15 01:08:48,zepto,4e507e91-6be7-4f3c-8dfe-aaa051a6d0c8,"Sri Udupi Park Party Hall, 7/1, ITPL Main Rd, BEML Layout, Brookefield, Bengaluru, Karnataka, 560066, India",Bangalore,560066,02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,e6db6618-386e-4a0b-8805-0501571c48eb,Bakery & Biscuits,Biscuits,Crackers,NaN,Malkist,Malkist Cheese Flavoured Crunchy Crackers | Trans Fat-free Combo,NaN,NaN,NaN,144 g X 2,NaN,120.0,114.0,No,Yes,114.0,NaN,₹6 OFF,114.0,5,2,https://www.zepto.com/pn/malkist-cheese-flavoured-crunchy-crackers-trans-fat-free-combo/pvid/02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,NaN,malkistcheeseflavouredcrunchycrackerstransfatfreecombo,malkist
84229,2026-07-15 01:11:21,zepto,ad4637de-2e3e-4276-a524-0546f33fa0d9,"Rohit Refrigeration Liluah, 42/1 Avoy Howrah 711107, Guha Rd, Vivekananda Colony, Liluah, Kolkata, West Bengal",Kolkata,711107,02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,e6db6618-386e-4a0b-8805-0501571c48eb,Bakery & Biscuits,Biscuits,Crackers,NaN,Malkist,Malkist Cheese Flavoured Crunchy Crackers | Trans Fat-free Combo,NaN,NaN,NaN,144 g X 2,NaN,120.0,114.0,No,Yes,114.0,NaN,₹6 OFF,114.0,5,6,https://www.zepto.com/pn/malkist-cheese-flavoured-crunchy-crackers-trans-fat-free-combo/pvid/02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,NaN,malkistcheeseflavouredcrunchycrackerstransfatfreecombo,malkist
97468,2026-07-15 01:21:27,zepto,cc72f206-e146-43c5-a01b-56ddc8d11464,"Changes Advertising, D-2, Rameshwar S V Road, Santacruz West, Railway Colony, Santacruz West, Mumbai, Maharashtra, 400054, India",Mumbai,400054,02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,e6db6618-386e-4a0b-8805-0501571c48eb,Bakery & Biscuits,Biscuits,Crackers,NaN,Malkist,Malkist Cheese Flavoured Crunchy Crackers | Trans Fat-free Combo,NaN,NaN,NaN,144 g X 2,NaN,120.0,114.0,No,Yes,114.0,NaN,₹6 OFF,114.0,5,5,https://www.zepto.com/pn/malkist-cheese-flavoured-crunchy-crackers-trans-fat-free-combo/pvid/02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,NaN,malkistcheeseflavouredcrunchycrackerstransfatfreecombo,malkist
97501,2026-07-15 01:21:29,zepto,7000d78e-6700-49e6-94ac-b4caa221a0f1,"Sri Gururagavendra Juice & Condiments, Volagalahalli, Stage II, Kengeri Satellite Town, Bengaluru, Karnataka 560060",Bangalore,560060,02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,e6db6618-386e-4a0b-8805-0501571c48eb,Bakery & Biscuits,Biscuits,Crackers,NaN,Malkist,Malkist Cheese Flavoured Crunchy Crackers | Trans Fat-free Combo,NaN,NaN,NaN,144 g X 2,NaN,120.0,114.0,No,Yes,114.0,NaN,₹6 OFF,114.0,5,2,https://www.zepto.com/pn/malkist-cheese-flavoured-crunchy-crackers-trans-fat-free-combo/pvid/02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,NaN,malkistcheeseflavouredcrunchycrackerstransfatfreecombo,malkist
98375,2026-07-15 01:22:02,zepto,c48dd700-4314-4cc1-bffa-e1344e0298dc,"DRR Foundation, 530, Akshaya Tower, 3rd Floor 5th Cross, HMT Layout, Opp. RT Nagar, Police Station, Bilappa Garden, R.T Nagar, Bengaluru, Karnataka, 560032, India",Bangalore,560032,02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,e6db6618-386e-4a0b-8805-0501571c48eb,Bakery & Biscuits,Biscuits,Crackers,NaN,Malkist,Malkist Cheese Flavoured Crunchy Crackers | Trans Fat-free Combo,NaN,NaN,NaN,144 g X 2,NaN,120.0,114.0,No,Yes,114.0,NaN,₹6 OFF,114.0,5,6,https://www.zepto.com/pn/malkist-cheese-flavoured-crunchy-crackers-trans-fat-free-combo/pvid/02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,NaN,malkistcheeseflavouredcrunchycrackerstransfatfreecombo,malkist
111233,2026-07-15 01:33:27,zepto,2699f532-61f3-431f-aab3-db586ec14085,"IndiGo Motor Works, No:88, Maduravoyal Service Road, Indira Gandhi St, Ayanambakkam, Kil Ayanambakkam, Chennai, Tamil Nadu, 600037, India",Chennai,600037,02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,e6db6618-386e-4a0b-8805-0501571c48eb,Bakery & Biscuits,Biscuits,Crackers,NaN,Malkist,Malkist Cheese Flavoured Crunchy Crackers | Trans Fat-free Combo,NaN,NaN,NaN,144 g X 2,NaN,120.0,114.0,No,Yes,114.0,NaN,₹6 OFF,114.0,5,6,https://www.zepto.com/pn/malkist-cheese-flavoured-crunchy-crackers-trans-fat-free-combo/pvid/02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,NaN,malkistcheeseflavouredcrunchycrackerstransfatfreecombo,malkist
114889,2026-07-15 01:38:44,zepto,b91aec1b-7f2b-45a0-b047-bf7750d4d193,"RadhaKrishnan Cross Street, RadhaKrishnan Cross St, Villapuram, Tamil Nadu, 625012, India",Madurai,625012,02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,e6db6618-386e-4a0b-8805-0501571c48eb,Bakery & Biscuits,Biscuits,Crackers,NaN,Malkist,Malkist Cheese Flavoured Crunchy Crackers | Trans Fat-free Combo,NaN,NaN,NaN,144 g X 2,NaN,120.0,114.0,No,Yes,114.0,NaN,₹6 OFF,114.0,5,6,https://www.zepto.com/pn/malkist-cheese-flavoured-crunchy-crackers-trans-fat-free-combo/pvid/02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,NaN,malkistcheeseflavouredcrunchycrackerstransfatfreecombo,malkist
118137,2026-07-15 01:42:31,zepto,86ec9fc6-ed4b-4674-8175-68c88c75c16f,"Celebrity Fashions Limited, Velachery - Tambaram Main Rd, Narayanapuram, Pallikaranai, Chennai, Tamil Nadu, 600129, India",Chennai,600129,02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,e6db6618-386e-4a0b-8805-0501571c48eb,Bakery & Biscuits,Biscuits,Crackers,NaN,Malkist,Malkist Cheese Flavoured Crunchy Crackers | Trans Fat-free Combo,NaN,NaN,NaN,144 g X 2,NaN,120.0,114.0,No,Yes,114.0,NaN,₹6 OFF,114.0,5,3,https://www.zepto.com/pn/malkist-cheese-flavoured-crunchy-crackers-trans-fat-free-combo/pvid/02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,NaN,malkistcheeseflavouredcrunchycrackerstransfatfreecombo,malkist
127237,2026-07-15 01:52:13,zepto,1ad29aa7-34e9-4268-9238-5a3a3fcd1bd2,"Blinkit Kannamangla Main Road, Unit-7, WayCool Foods Bangalore DC, Kannamangala Main Rd, Ardendale, Kannamangala, Karnataka, 560115, India",Bangalore,560115,02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,e6db6618-386e-4a0b-8805-0501571c48eb,Bakery & Biscuits,Biscuits,Crackers,NaN,Malkist,Malkist Cheese Flavoured Crunchy Crackers | Trans Fat-free Combo,NaN,NaN,NaN,144 g X 2,NaN,120.0,114.0,No,Yes,114.0,NaN,₹6 OFF,114.0,5,6,https://www.zepto.com/pn/malkist-cheese-flavoured-crunchy-crackers-trans-fat-free-combo/pvid/02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,NaN,malkistcheeseflavouredcrunchycrackerstransfatfreecombo,malkist
161632,2026-07-15 02:43:20,zepto,17532e16-28d2-4271-bbac-c48b9b3f8dd1,"Jha Marketing, 5, Matri Pally, Adarsha Pally, Belghoria, Kolkata, West Bengal, 700057, India",Kolkata,700057,02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,e6db6618-386e-4a0b-8805-0501571c48eb,Bakery & Biscuits,Biscuits,Crackers,NaN,Malkist,Malkist Cheese Flavoured Crunchy Crackers | Trans Fat-free Combo,NaN,NaN,NaN,144 g X 2,NaN,120.0,114.0,No,Yes,114.0,NaN,₹6 OFF,114.0,5,6,https://www.zepto.com/pn/malkist-cheese-flavoured-crunchy-crackers-trans-fat-free-combo/pvid/02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,NaN,malkistcheeseflavouredcrunchycrackerstransfatfreecombo,malkist
165897,2026-07-15 02:44:54,zepto,0f5f31f2-f764-498a-9cc5-606cf82f4f2e,"Villa-1, Vishwam Inside Out Villas, Doddakannelli, Bengaluru, Karnataka, 560035, India",Bangalore,560035,02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,e6db6618-386e-4a0b-8805-0501571c48eb,Bakery & Biscuits,Biscuits,Crackers,NaN,Malkist,Malkist Cheese Flavoured Crunchy Crackers | Trans Fat-free Combo,NaN,NaN,NaN,144 g X 2,NaN,120.0,114.0,No,Yes,114.0,NaN,₹6 OFF,114.0,5,6,https://www.zepto.com/pn/malkist-cheese-flavoured-crunchy-crackers-trans-fat-free-combo/pvid/02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,NaN,malkistcheeseflavouredcrunchycrackerstransfatfreecombo,malkist
170274,2026-07-15 02:46:39,zepto,0af692ee-167f-4903-bf7c-959643e47899,"Pride Plaza Hotel Kolkata, Service Rd, Opposite To Novotel, BG Block(newtown), Action Area I, NewTown, New Town, West Bengal, 700156, India",Kolkata,700156,02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,e6db6618-386e-4a0b-8805-0501571c48eb,Bakery & Biscuits,Biscuits,Crackers,NaN,Malkist,Malkist Cheese Flavoured Crunchy Crackers | Trans Fat-free Combo,NaN,NaN,NaN,144 g X 2,NaN,120.0,114.0,No,Yes,114.0,NaN,₹6 OFF,114.0,5,6,https://www.zepto.com/pn/malkist-cheese-flavoured-crunchy-crackers-trans-fat-free-combo/pvid/02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,NaN,malkistcheeseflavouredcrunchycrackerstransfatfreecombo,malkist
170640,2026-07-15 02:46:49,zepto,2e7ec440-fd1b-441e-90ee-9c8611648bb6,"Marathon Monte Carlo, Opposite P&t Colony, Near Samriddhi Banquet Hall, Off LBS Rd, Madan Mohan Malviya Road, Asha Nagar, Mulund West, Mumbai, Maharashtra, 400080, India",Mumbai,400080,02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,e6db6618-386e-4a0b-8805-0501571c48eb,Bakery & Biscuits,Biscuits,Crackers,NaN,Malkist,Malkist Cheese Flavoured Crunchy Crackers | Trans Fat-free Combo,NaN,NaN,NaN,144 g X 2,NaN,120.0,114.0,Yes,Yes,114.0,NaN,₹6 OFF,114.0,5,0,https://www.zepto.com/pn/malkist-cheese-flavoured-crunchy-crackers-trans-fat-free-combo/pvid/02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,NaN,malkistcheeseflavouredcrunchycrackerstransfatfreecombo,malkist
173439,2026-07-15 02:48:04,zepto,0f2d3f82-cf97-45e8-bd80-759fe5dfbf6c,"Cut & Style Salon - Haralur Road, Bengaluru, 42 Haralur Road, 2nd Ave, Opposite HP Petrol Pump, Ambalipura, Bengaluru, Haralur, Karnataka, 560103, India",Bangalore,560103,02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,e6db6618-386e-4a0b-8805-0501571c48eb,Bakery & Biscuits,Biscuits,Crackers,NaN,Malkist,Malkist Cheese Flavoured Crunchy Crackers | Trans Fat-free Combo,NaN,NaN,NaN,144 g X 2,NaN,120.0,114.0,No,Yes,114.0,NaN,₹6 OFF,114.0,5,6,https://www.zepto.com/pn/malkist-cheese-flavoured-crunchy-crackers-trans-fat-free-combo/pvid/02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,NaN,malkistcheeseflavouredcrunchycrackerstransfatfreecombo,malkist
176718,2026-07-15 02:49:27,zepto,da931d01-2519-4d80-89ae-9d74dbb71918,"Navshakti Chowk, Mumbai Naka, Dr.Homi Bhabha Nagar, Nashik, Maharashtra, 422011, India",Nashik,422011,02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,e6db6618-386e-4a0b-8805-0501571c48eb,Bakery & Biscuits,Biscuits,Crackers,NaN,Malkist,Malkist Cheese Flavoured Crunchy Crackers | Trans Fat-free Combo,NaN,NaN,NaN,144 g X 2,NaN,120.0,114.0,No,Yes,114.0,NaN,₹6 OFF,114.0,5,6,https://www.zepto.com/pn/malkist-cheese-flavoured-crunchy-crackers-trans-fat-free-combo/pvid/02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,NaN,malkistcheeseflavouredcrunchycrackerstransfatfreecombo,malkist
189516,2026-07-15 02:54:09,zepto,ccc9dc9b-9c6f-421e-bedc-f2e7463a75e9,"Kamakshi Foods, No 15/1, 10th Main Rd, Revenue Extension, Kadarenahalli, Padmanabhanagar, Bengaluru, Karnataka, 560070, India",Bangalore,560070,02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,e6db6618-386e-4a0b-8805-0501571c48eb,Bakery & Biscuits,Biscuits,Crackers,NaN,Malkist,Malkist Cheese Flavoured Crunchy Crackers | Trans Fat-free Combo,NaN,NaN,NaN,144 g X 2,NaN,120.0,114.0,No,Yes,114.0,NaN,₹6 OFF,114.0,5,6,https://www.zepto.com/pn/malkist-cheese-flavoured-crunchy-crackers-trans-fat-free-combo/pvid/02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,NaN,malkistcheeseflavouredcrunchycrackerstransfatfreecombo,malkist
198806,2026-07-15 02:57:33,zepto,b4d53703-4b49-4a38-85ca-7e321d1d5222,"Green Fitness Club(camp Road), No 2, Sri Ram Nagar 4th Street, Seliyur, Post, Nazeeb Avenue, Tambaram, Chennai, Tamil Nadu, 600064, India",Chennai,600064,02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,e6db6618-386e-4a0b-8805-0501571c48eb,Bakery & Biscuits,Biscuits,Crackers,NaN,Malkist,Malkist Cheese Flavoured Crunchy Crackers | Trans Fat-free Combo,NaN,NaN,NaN,144 g X 2,NaN,120.0,114.0,No,Yes,114.0,NaN,₹6 OFF,114.0,5,6,https://www.zepto.com/pn/malkist-cheese-flavoured-crunchy-crackers-trans-fat-free-combo/pvid/02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,NaN,malkistcheeseflavouredcrunchycrackerstransfatfreecombo,malkist
205371,2026-07-15 03:00:23,zepto,aa16c37d-46a9-4e32-84b3-0e2401bd196f,"Sri RB Chekku Oil, No.926, 563, Poonamallee High Rd, Arumbakkam, Chennai, Tamil Nadu, 600106, India",Chennai,600106,02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,e6db6618-386e-4a0b-8805-0501571c48eb,Bakery & Biscuits,Biscuits,Crackers,NaN,Malkist,Malkist Cheese Flavoured Crunchy Crackers | Trans Fat-free Combo,NaN,NaN,NaN,144 g X 2,NaN,120.0,114.0,No,Yes,114.0,NaN,₹6 OFF,114.0,5,6,https://www.zepto.com/pn/malkist-cheese-flavoured-crunchy-crackers-trans-fat-free-combo/pvid/02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,NaN,malkistcheeseflavouredcrunchycrackerstransfatfreecombo,malkist
209700,2026-07-15 03:02:15,zepto,da5b2eac-c339-43fa-a59b-b153f2603b9c,"Canal Bank Rd, Patharghata, NewTown, Kolkata, West Bengal, 700160, India",Kolkata,700160,02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,e6db6618-386e-4a0b-8805-0501571c48eb,Bakery & Biscuits,Biscuits,Crackers,NaN,Malkist,Malkist Cheese Flavoured Crunchy Crackers | Trans Fat-free Combo,NaN,NaN,NaN,2 x 144 g,NaN,120.0,114.0,Yes,Yes,114.0,NaN,₹6 OFF,114.0,5,0,https://www.zepto.com/pn/malkist-cheese-flavoured-crunchy-crackers-trans-fat-free-combo/pvid/02ff8196-ec66-43e4-8a45-7d56ec8a3e0b,NaN,malkistcheeseflavouredcrunchycrackerstransfatfreecombo,malkist

In [10]:
import re

# Normalize brand names
df["brand_norm"] = (
    df["brand_name"]
    .fillna("")
    .str.lower()
    .str.replace(r"[^a-z0-9]", "", regex=True)   # remove spaces, ', -, &, etc.
)

# Find brands that become the same after normalization
brand_issue = (
    df.groupby("brand_norm")
    .agg(
        variant_count=("brand_name", "nunique"),
        brand_variants=("brand_name", lambda x: sorted(set(x)))
    )
    .reset_index()
)

brand_issue = brand_issue[brand_issue["variant_count"] > 1]

brand_issue

,brand_norm,variant_count,brand_variants
207,bombayshavingcompany,2,"[Bombay Shaving Company, Bombay shaving Company]"
208,bonn,2,"[Bonn, bonn]"
212,borges,2,"[BORGES, Borges]"
371,delichic,2,"[Deli Chic, Delichic]"
758,kharifoods,2,"[KHARI FOODS, Khari Foods]"
1023,noto,2,"[NOTO, Noto]"
1096,paperboat,2,"[PAPER BOAT, Paper Boat]"
1109,patanjali,2,"[PATANJALI, Patanjali]"
1141,plixtheplantfix,2,"[Plix -The Plant Fix, Plix The Plant Fix]"
1338,star,2,"[STAR, Star]"
1370,sunscoop,2,"[SunScoop, Sunscoop]"
1533,vijay,2,"[VIJAY, Vijay]"

In [11]:
df.columns

Index(['crawl_date_and_time', 'platform_name', 'store_id',
       'store_name_location', 'city', 'pin_code', 'unique_id',
       'product_id_upc_ean', 'department', 'category', 'sub_category',
       'product_type', 'brand_name', 'product_name', 'product_description',
       'product_grammage', 'package_type', 'net_quantity', 'variants',
       'item_mrp', 'item_selling_price', 'out_of_stock_flag', 'discount_flag',
       'product_price', 'unit_price', 'promo_offer_description',
       'promo_offer_price', 'discount_in_percent', 'stock_count',
       'product_url', 'product_image_urls', 'productname_norm', 'brand_norm'],
      dtype='object')

In [12]:
# 1. Group by identity columns to isolate the exact same physical product
product_identity_issues = (
    df.groupby(["unique_id", "product_grammage", "net_quantity"])
    .agg(
        # Count how many different spelling/name variations exist for this product
        name_variant_count=("product_name", "nunique"),
        # Create an alphabetised list of those unique name variations
        name_variants=("product_name", lambda x: sorted(set(x))),
        # Optional: capture variations in brand name for the same product
        brand_variants=("brand_name", lambda x: sorted(set(x.dropna()))),
    )
    .reset_index()
)

# 2. Filter for rows where the same product has more than 1 name variation
name_issues_by_id = product_identity_issues[
    product_identity_issues["name_variant_count"] > 1
]

# 3. View the final flagged discrepancies
print(name_issues_by_id)

                                 unique_id product_grammage      net_quantity  \
67    01731957-be4c-4796-b99e-b9a3ca5dba52          151.2 g  1 pack (151.2 g)
651   0e2db924-61fa-4ed0-a156-0a1cf73b455a              1 L        1 pc (1 L)
1241  1b1b90cc-ad0a-4f14-81a4-14f22b8b64ac              1 L        1 pc (1 L)
9291  d3c9ab02-e7f7-44ae-8ae7-a973494b436a            150 g    1 pack (150 g)
9921  e226e3a0-e81f-444f-a023-1fd8f045c3c3            150 g    1 pack (150 g)

      name_variant_count  \
67                     2
651                    2
1241                   2
9291                   2
9921                   2

                                                                                                                       name_variants  \
67                                            [Orion O'Rice Cracker - Baked Korean Snack, Orion O'rice Cracker - Baked Korean Snack]
651   [RAW Pressary Almond Bevarage Cacao Chocolate Flavoured Almond Drink Lactose Free Vegan Drink, Raw Pressery Cocoa Almond Milk]
1241                           [RAW Pressary Almond Bevarage Plain (Unsweetened) Lactose Free Vegan Drink, Raw Pressery Almond Milk]
9291                         [Modern Kitchen Butter Murukku | Crunchy & Buttery, Modern Kitchens Butter Murukku | Crunchy & Buttery]
9921                               [Modern Kitchen Spicy Murukku | Crunchy & Spicy, Modern Kitchens Spicy Murukku | Crunchy & Spicy]

        brand_variants
67             [Orion]
651     [Raw Pressery]
1241    [Raw Pressery]
9291  [Modern Kitchen]
9921  [Modern Kitchen]

In [13]:
# 1. Group by unique_id to see if physical attributes split
id_integrity_check = (
    df.groupby("unique_id")
    .agg(
        grammage_count=("product_grammage", "nunique"),
        grammage_variants=("product_grammage", lambda x: list(set(x.dropna()))),
        quantity_count=("net_quantity", "nunique"),
        quantity_variants=("net_quantity", lambda x: list(set(x.dropna()))),
        category_count=("category", "nunique"),
        category_variants=("category", lambda x: list(set(x.dropna()))),
    )
    .reset_index()
)

# 2. Filter for rows where an ID maps to MORE THAN ONE physical variation
corrupted_ids = id_integrity_check[
    (id_integrity_check["grammage_count"] > 1) | 
    (id_integrity_check["quantity_count"] > 1)
]

# 3. Display the errors
print(f"Found {len(corrupted_ids)} unique_ids tied to different products.")
print(corrupted_ids)

Found 6 unique_ids tied to different products.
                                  unique_id  grammage_count  \
186    02ff8196-ec66-43e4-8a45-7d56ec8a3e0b               0
3062   350537ae-9114-4fe3-9fdc-5784019dd29c               2
8654   9468f7c9-2bce-4304-b3f1-1f3e831d9f82               0
10899  bb10e167-207f-4cc1-a82e-bdcbbb04dfdd               0
11405  c3d074ee-4498-42d9-b484-6f68fd77305b               0
14194  f27d19d1-67eb-4725-9cdb-0b52331c67cc               0

            grammage_variants  quantity_count  \
186                        []               2
3062   [210 g, 210 g or 200g]               2
8654                       []               2
10899                      []               2
11405                      []               2
14194                      []               2

                              quantity_variants  category_count  \
186                      [2 x 144 g, 144 g X 2]               1
3062   [1 pack (210 g), 1 pack (210 g or 200g)]               1
8654                       [2 x 48 g, 48 g X 2]               1
10899                      [48 g X 3, 3 x 48 g]               1
11405                      [2 x 75 g, 75 g X 2]               1
14194                    [2 x 144 g, 144 g X 2]               1

      category_variants
186          [Biscuits]
3062         [Munchies]
8654         [Biscuits]
10899        [Biscuits]
11405        [Biscuits]
14194        [Biscuits]

In [ ]:
in_stock_urls = (
    df.loc[df["out_of_stock_flag"] == "No",
             ["unique_id", "product_name", "city", "store_id", "product_url"]]
    .drop_duplicates()
)

print("Products to verify (In Stock):", len(in_stock_urls))
in_stock_urls.head()

Products to verify (In Stock): 116433

,unique_id,product_name,city,store_id,product_url
22,01a9083f-de42-4b6a-8169-692cbc0698f8,Rajdhani Premium Sooji,Kota,b359ba27-8fe9-4c95-85f0-0939de00f5a4,https://www.zepto.com/pn/rajdhani-premium-sooji/pvid/01a9083f-de42-4b6a-8169-692cbc0698f8
24,bb0b3235-925d-422c-a63b-034dbe0f0378,Daily Good Besan / Gram Flour / Chana Besan,Kota,b359ba27-8fe9-4c95-85f0-0939de00f5a4,https://www.zepto.com/pn/daily-good-besan-gram-flour-chana-besan/pvid/bb0b3235-925d-422c-a63b-034dbe0f0378
25,7ec4149a-d673-4485-bcf4-cb9aec6184dd,Rajdhani Besan,Kota,b359ba27-8fe9-4c95-85f0-0939de00f5a4,https://www.zepto.com/pn/rajdhani-besan/pvid/7ec4149a-d673-4485-bcf4-cb9aec6184dd
26,226523cf-f83b-4c63-9257-6711b5c1233d,Organic Tattva Organic Suji,Kota,b359ba27-8fe9-4c95-85f0-0939de00f5a4,https://www.zepto.com/pn/organic-tattva-organic-suji/pvid/226523cf-f83b-4c63-9257-6711b5c1233d
27,a6350d17-699f-4178-a3dc-846e11cad1f9,Gangaur Sooji,Kota,b359ba27-8fe9-4c95-85f0-0939de00f5a4,https://www.zepto.com/pn/gangaur-sooji/pvid/a6350d17-699f-4178-a3dc-846e11cad1f9

In [18]:
out_of_stock_urls = (
    df.loc[df["out_of_stock_flag"] == "Yes",
             ["unique_id", "product_name", "city", "store_id", "product_url"]]
    .drop_duplicates()
)

print("Products to verify (Out of Stock):", len(out_of_stock_urls))
out_of_stock_urls.head()

Products to verify (Out of Stock): 116433

,unique_id,product_name,city,store_id,product_url
22,01a9083f-de42-4b6a-8169-692cbc0698f8,Rajdhani Premium Sooji,Kota,b359ba27-8fe9-4c95-85f0-0939de00f5a4,https://www.zepto.com/pn/rajdhani-premium-sooji/pvid/01a9083f-de42-4b6a-8169-692cbc0698f8
24,bb0b3235-925d-422c-a63b-034dbe0f0378,Daily Good Besan / Gram Flour / Chana Besan,Kota,b359ba27-8fe9-4c95-85f0-0939de00f5a4,https://www.zepto.com/pn/daily-good-besan-gram-flour-chana-besan/pvid/bb0b3235-925d-422c-a63b-034dbe0f0378
25,7ec4149a-d673-4485-bcf4-cb9aec6184dd,Rajdhani Besan,Kota,b359ba27-8fe9-4c95-85f0-0939de00f5a4,https://www.zepto.com/pn/rajdhani-besan/pvid/7ec4149a-d673-4485-bcf4-cb9aec6184dd
26,226523cf-f83b-4c63-9257-6711b5c1233d,Organic Tattva Organic Suji,Kota,b359ba27-8fe9-4c95-85f0-0939de00f5a4,https://www.zepto.com/pn/organic-tattva-organic-suji/pvid/226523cf-f83b-4c63-9257-6711b5c1233d
27,a6350d17-699f-4178-a3dc-846e11cad1f9,Gangaur Sooji,Kota,b359ba27-8fe9-4c95-85f0-0939de00f5a4,https://www.zepto.com/pn/gangaur-sooji/pvid/a6350d17-699f-4178-a3dc-846e11cad1f9