In [12]:
import pandas as pd

### Data Loading

In [13]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [14]:
data = pd.read_csv(r"/home/user/Documents/zepto_2026_07_04.csv",low_memory=False)
data.head()

,crawl_date_and_time,platform_name,store_id,store_name_location,city,pin_code,unique_id,product_id_upc_ean,department,category,sub_category,product_type,brand_name,product_name,product_description,product_grammage,package_type,net_quantity,variants,item_mrp,item_selling_price,out_of_stock_flag,discount_flag,product_price,unit_price,promo_offer_description,promo_offer_price,discount_in_percent,stock_count,product_url,product_image_urls
0,2026-07-04 00:11:06,zepto,553c9cfa-5a00-4b98-a1d5-152c813e12d2,"Soft Touch Ladies Beauty Parlour & Spa, Bc126,...",Kolkata,700102,01e50ab8-aff1-456f-8d9e-fc4e352e737a,faeeda15-4ff5-4bcc-9bc1-d0a6dbf82393,"Atta, Rice & Dal","Atta, Rice, Oil & Dals",Millets & Other Flours,NaN,Ganesh,Ganesh Chawal Atta,NaN,500 g,NaN,1 pack (500 g),NaN,54.0,53.0,No,Yes,53.0,NaN,₹1 OFF,53.0,1,6,https://www.zepto.com/pn/ganesh-chawal-atta/pv...,NaN
1,2026-07-04 00:11:06,zepto,553c9cfa-5a00-4b98-a1d5-152c813e12d2,"Soft Touch Ladies Beauty Parlour & Spa, Bc126,...",Kolkata,700102,31ad3e8b-e689-48c1-956c-ca36d9fcac2c,e036add7-94c1-4287-b83b-ffd2794806cf,"Atta, Rice & Dal","Atta, Rice, Oil & Dals",Millets & Other Flours,NaN,Daily Good,Daily Good Corn Flour/Starch,NaN,500 g,NaN,1 pack (500 g),NaN,70.0,45.0,No,Yes,45.0,NaN,₹25 OFF,45.0,35,6,https://www.zepto.com/pn/daily-good-corn-flour...,NaN
2,2026-07-04 00:11:06,zepto,553c9cfa-5a00-4b98-a1d5-152c813e12d2,"Soft Touch Ladies Beauty Parlour & Spa, Bc126,...",Kolkata,700102,f2620ea4-725f-4b47-8c1c-85c893762db7,16773c77-d384-4a11-94d6-0d3ee8d32e62,"Atta, Rice & Dal","Atta, Rice, Oil & Dals",Millets & Other Flours,NaN,Ganesh,Ganesh Finger Millet (Ragi Atta),NaN,500 g,NaN,1 pack (500 g),NaN,73.0,63.0,No,Yes,63.0,NaN,₹10 OFF,63.0,13,6,https://www.zepto.com/pn/ganesh-finger-millet-...,NaN
3,2026-07-04 00:11:06,zepto,553c9cfa-5a00-4b98-a1d5-152c813e12d2,"Soft Touch Ladies Beauty Parlour & Spa, Bc126,...",Kolkata,700102,c0781799-72e5-4bb2-8b82-d96ffe9aab6f,dc4e1c46-1225-4fa6-94c3-01aadef9d8c8,"Atta, Rice & Dal","Atta, Rice, Oil & Dals",Millets & Other Flours,NaN,Organic Tattva,Organic Tattva Ragi Atta,NaN,500 g,NaN,1 pack (500 g),NaN,95.0,89.0,No,Yes,89.0,NaN,₹6 OFF,89.0,6,6,https://www.zepto.com/pn/organic-tattva-ragi-a...,NaN
4,2026-07-04 00:11:06,zepto,553c9cfa-5a00-4b98-a1d5-152c813e12d2,"Soft Touch Ladies Beauty Parlour & Spa, Bc126,...",Kolkata,700102,763dbe3b-38b6-4c72-a3cb-040ab964a239,bb519257-fec9-4df4-baa3-0f228ff83634,"Atta, Rice & Dal","Atta, Rice, Oil & Dals",Millets & Other Flours,NaN,Daily Good,Daily Good Rice Flour,NaN,500 g,NaN,1 pack (500 g),NaN,65.0,29.0,No,Yes,29.0,NaN,₹36 OFF,29.0,55,6,https://www.zepto.com/pn/daily-good-rice-flour...,NaN

### Data Exploration

In [15]:
#to get no.og rows and columns
data.shape

(1037455, 31)

In [16]:
#to get column names
data.columns

Index(['crawl_date_and_time', 'platform_name', 'store_id',
       'store_name_location', 'city', 'pin_code', 'unique_id',
       'product_id_upc_ean', 'department', 'category', 'sub_category',
       'product_type', 'brand_name', 'product_name', 'product_description',
       'product_grammage', 'package_type', 'net_quantity', 'variants',
       'item_mrp', 'item_selling_price', 'out_of_stock_flag', 'discount_flag',
       'product_price', 'unit_price', 'promo_offer_description',
       'promo_offer_price', 'discount_in_percent', 'stock_count',
       'product_url', 'product_image_urls'],
      dtype='object')

In [17]:
# to know data types
data.dtypes

crawl_date_and_time         object
platform_name               object
store_id                    object
store_name_location         object
city                        object
pin_code                     int64
unique_id                   object
product_id_upc_ean          object
department                  object
category                    object
sub_category                object
product_type               float64
brand_name                  object
product_name                object
product_description        float64
product_grammage            object
package_type               float64
net_quantity                object
variants                    object
item_mrp                   float64
item_selling_price         float64
out_of_stock_flag           object
discount_flag               object
product_price              float64
unit_price                 float64
promo_offer_description     object
promo_offer_price          float64
discount_in_percent          int64
stock_count                  int64
product_url                 object
product_image_urls         float64
dtype: object

In [18]:

data.describe()

,pin_code,product_type,product_description,package_type,item_mrp,item_selling_price,product_price,unit_price,promo_offer_price,discount_in_percent,stock_count,product_image_urls
count,1.037455e+06,0.0,0.0,0.0,1.037454e+06,1.037455e+06,1.037455e+06,0.0,1.037455e+06,1.037455e+06,1.037455e+06,0.0
mean,3.991030e+05,NaN,NaN,NaN,3.720981e+02,2.703402e+02,2.703402e+02,NaN,2.703402e+02,1.890673e+01,3.336163e+00,NaN
std,1.829157e+05,NaN,NaN,NaN,6.259922e+02,4.450633e+02,4.450633e+02,NaN,4.450633e+02,1.728904e+01,5.135736e+00,NaN
min,1.100030e+05,NaN,NaN,NaN,2.160000e+00,0.000000e+00,0.000000e+00,NaN,0.000000e+00,0.000000e+00,0.000000e+00,NaN
25%,2.013100e+05,NaN,NaN,NaN,9.000000e+01,7.500000e+01,7.500000e+01,NaN,7.500000e+01,5.000000e+00,1.000000e+00,NaN
50%,4.110440e+05,NaN,NaN,NaN,2.000000e+02,1.590000e+02,1.590000e+02,NaN,1.590000e+02,1.500000e+01,2.000000e+00,NaN
75%,5.600570e+05,NaN,NaN,NaN,4.250000e+02,3.110000e+02,3.110000e+02,NaN,3.110000e+02,2.800000e+01,4.000000e+00,NaN
max,7.111040e+05,NaN,NaN,NaN,4.990000e+04,4.590000e+04,4.590000e+04,NaN,4.590000e+04,9.500000e+01,6.000000e+01,NaN

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1037455 entries, 0 to 1037454
Data columns (total 31 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   crawl_date_and_time      1037455 non-null  object
 1   platform_name            1037455 non-null  object
 2   store_id                 1037455 non-null  object
 3   store_name_location      1037455 non-null  object
 4   city                     1037455 non-null  object
 5   pin_code                 1037455 non-null  int64
 6   unique_id                1037455 non-null  object
 7   product_id_upc_ean       1037455 non-null  object
 8   department               1037455 non-null  object
 9   category                 1037455 non-null  object
 10  sub_category             1037455 non-null  object
 11  product_type             0 non-null        float64
 12  brand_name               1037455 non-null  object
 13  product_name             1037455 non-null  object
 14  product_description      0 non-null        float64
 15  product_grammage         844382 non-null   object
 16  package_type             0 non-null        float64
 17  net_quantity             1037453 non-null  object
 18  variants                 26527 non-null    object
 19  item_mrp                 1037454 non-null  float64
 20  item_selling_price       1037455 non-null  float64
 21  out_of_stock_flag        1037455 non-null  object
 22  discount_flag            1037455 non-null  object
 23  product_price            1037455 non-null  float64
 24  unit_price               0 non-null        float64
 25  promo_offer_description  1037455 non-null  object
 26  promo_offer_price        1037455 non-null  float64
 27  discount_in_percent      1037455 non-null  int64
 28  stock_count              1037455 non-null  int64
 29  product_url              1037455 non-null  object
 30  product_image_urls       0 non-null        float64
dtypes: float64(9), int64(3), object(19)
memory usage: 245.4+ MB

In [21]:
data.duplicated().sum()

np.int64(0)

In [23]:
print(data.isnull().sum()== 1037455)

crawl_date_and_time        False
platform_name              False
store_id                   False
store_name_location        False
city                       False
pin_code                   False
unique_id                  False
product_id_upc_ean         False
department                 False
category                   False
sub_category               False
product_type                True
brand_name                 False
product_name               False
product_description         True
product_grammage           False
package_type                True
net_quantity               False
variants                   False
item_mrp                   False
item_selling_price         False
out_of_stock_flag          False
discount_flag              False
product_price              False
unit_price                  True
promo_offer_description    False
promo_offer_price          False
discount_in_percent        False
stock_count                False
product_url                False
product_image_urls          True
dtype: bool

In [27]:
duplicate_count = data['unique_id'].duplicated().sum()
print("Number of duplicate unique_id values:", duplicate_count)

Number of duplicate unique_id values: 1020106

In [28]:
data.nunique()

crawl_date_and_time        23330
platform_name                  1
store_id                     381
store_name_location          292
city                          54
pin_code                     248
unique_id                  17349
product_id_upc_ean         16866
department                    10
category                      28
sub_category                 161
brand_name                  1766
product_name               15545
product_grammage            1060
net_quantity                2101
variants                     227
item_mrp                    1199
item_selling_price          2136
out_of_stock_flag              2
discount_flag                  2
product_price               2136
promo_offer_description     1522
promo_offer_price           2136
discount_in_percent           93
stock_count                   57
product_url                17351
dtype: int64

In [32]:
data.city.unique()

array(['Kolkata', 'Bangalore', 'Chennai', 'Kochi', 'Pune', 'Jaipur',
       'Mumbai', 'Hyderabad', 'Lucknow', 'Indore', 'Davanagere', 'Nagpur',
       'Amritsar', 'Gurgaon', 'Noida', 'Dehradun', 'Ahmedabad', 'Kanpur',
       'Ghaziabad', 'Vijayawada', 'Coimbatore', 'Madurai', 'Delhi',
       'Sonipat', 'Navi Mumbai', 'Udaipur', 'Ludhiana', 'Belagavi',
       'Haridwar', 'Chandigarh', 'Puducherry', 'Vadodara',
       'Kalyan-Dombivli', 'Valsad', 'Phagwara', 'Surat', 'Faridabad',
       'Warangal', 'Bareilly', 'Panipat', 'Rajkot', 'Nashik', 'Varanasi',
       'Panchkula', 'Gorakhpur', 'Kalamassery', 'Rewari', 'Hubballi',
       'Prayagraj', 'Meerut', 'Mysuru', 'S.A.S Nagar',
       'Chhatrapati Sambhajinagar', 'Ambala'], dtype=object)

In [34]:
data.duplicated(
    subset=["unique_id", "store_id", "crawl_date_and_time"]
).sum()

np.int64(0)

In [35]:
data.groupby("unique_id")["store_id"].nunique().sort_values(ascending=False).head()

unique_id
cf720a00-485a-4c0d-9a09-bcd5628e5846    278
c3b939d1-e0cf-4af1-92b0-c6a7223034ce    276
14152635-b4e1-414a-a205-451f0cab7a2c    276
577d14c0-f2fe-4d7a-9cff-4085bf1455a0    275
34b9a8c1-6956-4e9c-aa2b-bf4a480fabc4    275
Name: store_id, dtype: int64

### Data cleaning

In [24]:
# Removing the rows which are completely empty(product_type,product_description ,package_type,unit_price,product_image_urls

# Remove columns that are completely empty
data = data.dropna(axis=1, how='all')

In [25]:
data.shape

(1037455, 26)

#### store_id check

In [39]:
store_location_check = (
    data.groupby("store_name_location")["store_id"]
        .nunique()
        .sort_values(ascending=False)
)

# Locations with more than one store_id
anomalies = store_location_check[store_location_check > 1]

print(anomalies)

store_name_location
Anika Redwood Square, Nagarabhavi Main Rd, 2nd Block, Coconut Garden, Chalukya Nagar, Bhyraveshwara Nagar, Bengaluru, Karnataka, 560072, India                                                                       3
Anju Boutique Cosmetic, 920, Jaina Market, Nathuram Market, DLF Phase 4, Nathuram Market, Chakkarpur, Sector 28, Gurugram, Haryana, 122002, India                                                                    3
King Mens Wear, Shop No 5 Jijamata Nagar, Kamgar Hospital Rd, Ramachandra Nagar, Waghle Estate, Thane West, Thane, Maharashtra, 400604, India                                                                        3
Village Side Cafe, Nr. Pixcy Kennel, Village Side Cafe, Kutchi Sarvoday Trust Ground, Yogi Nagar Marg, Yogi Nagar, Borivali West, Mumbai, Maharashtra, 400092, India                                                 3
NSM RoadWays, 14, A Block, GKRB Rd, Old Madiwala, Jay Bheema Nagar, 1st Stage, BTM Layout, Bengaluru, Karnataka, 560068, India                                                                                       3
Ceramic Pro Whitefeild - Bangalore (Route 66 Detailing) Best Detailing Studio In The Neighbourhood, 443, Varthur Main Rd, Phase 1, Siddapura, Whitefield, Bengaluru, Karnataka, 560066, India                        3
Goel Traders, 1539, GuruDwara Rd, South Extension, Kotla Mubarakpur, Kotla, New Delhi, Delhi, 110003, India                                                                                                          3
Spunky Homes, Preston Prime Mall, Lumbini Avenue, Gachibowli, Hyderabad, Telangana, 500081, India                                                                                                                    3
Sripathi Solutions, Devi Padmasree Convention Backside, Balaji Hills Rd, Nagaarjun Colony, Mallikarjuna Nagar, Boduppal, Hyderabad, Telangana, 500092, India                                                         3
Ramanuja Credit Co Op Soc Limited, No 22, Seshadri Rd, Lakshmanpuri, Gandhi Nagar, Bengaluru, Karnataka, 560009, India                                                                                               3
Zonah Mars, Sri Sai Apartment Block-B, Sri Sai Apartment, Plot 108, Vittal Rao Nagar, Hitec City, Hyderabad, Telangana, 500081, India                                                                                2
1, Dattani Park Rd, Thakur, Dattani Park, Thakur Village, Kandivali East, Mumbai, Maharashtra, 400066, India                                                                                                         2
Zepto Store Warehouse, Major Bhupinder Singh Nagar, Keshopur, Tilak Nagar, Delhi, 110018, India                                                                                                                      2
The MidTown, Virar - Nallasopara Link Rd, Sriprastha, Nalasopara West, Palghar, Nala Sopara, Maharashtra, 401203, India                                                                                              2
Temple Stone Residency, Templestone Residency, Rd Number 10, Madhavapuri Hills, PJR Enclave, PJR Layout, Chanda Nagar, Hyderabad, Miyapur, Telangana, 502032, India                                                  2
Time Steel Traders, Irandankattalai, Tamil Nadu, 600132, India                                                                                                                                                       2
Thehrav Homestay(caramel Homes), Rz10b/13, Kailashpuri Main, Kailash Puri, Palam, New Delhi, Delhi, 110045, India                                                                                                    2
AZB & Partners, A-8, Amaltash Marg, Block A, Sector 4, Noida, Uttar Pradesh, 201301, India                                                                                                                           2
Aakruthi Sunshine Apartment, Aakruthi Sunshine, Panathur Main Rd, Kaverappa Layout, Kadubeesanahalli, Bengaluru, Karnataka, 560103, India                                                                            2
AKJ Green Floors, Ansal API, Sushant Aquapolis, B-110, Crossings Republik, Ghaziabad, Uttar Pradesh, 201009, India                                                                                                   2
AISECT Office & Education Centre Hyderabad, Gayathri's Sri Sai Enclave, 3Floor, Musheerabad Main Rd, Musheerabad, Dayara, Hyderabad, Telangana, 500020, India                                                        2
BLS ACLS Pals ITLS Courses At Nashik | Charles Institute, Near Guruji Rugnalaya, Rameshwar Nagar, Balawant Nagar, Savarkar Nagar, Nashik, Maharashtra, 422013, India                                                 2
Aurinko Academy - IGCSE Cambridge Alternative Progressive School, 91, Opposite To Hosa Road, Parappana Agrahara, Bengaluru, Karnataka, 560035, India                                                                 2
8/225, Sector, 8, Malviya Nagar, Jaipur, Rajasthan, 302017, India                                                                                                                                                    2
BM Lal Brothers, 34, Opposite Sathyam Theatre Car Parking, Whites Road, Royapettah, Express Estate, Royapettah, Chennai, Tamil Nadu, 600002, India                                                                   2
Ahilya Marg, Block C, Chander Nagar, Surya Nagar, Ghaziabad, Uttar Pradesh, 201011, India                                                                                                                            2
Agarwal Furniture - Best Furniture Showroom In Manesar - Best Furniture Showroom In New Gurgaon, Shop No. 1, Near Rampura FlyOver, NH-8, Manesar, Gurugram, Haryana, 122004, India                                   2
Aeromarine Private Limited, 20, Jawahar Industrial Estate, Opposite To Mcdonald, Near J.K. Industries, Jawahar Co-Op Ind, Kamothe, Panvel, Navi Mumbai, Maharashtra, 410209, India                                   2
Abhishek Gas Agencies, No. 923, GF, VR Arcade, 1st Cross Rd, Near Corporation Bank, Remco Bhel Layout, Javarandoddi, RajaRajeshwari Nagar, Bengaluru, Karnataka, 560039, India                                       2
Abakash Apartment Nagerbazar, Nagendra Nath Rd, Nagerbazar, Kamardanga, Kolkata, West Bengal, 700028, India                                                                                                          2
Aama Tattoo Inn, Balkum Road, Kolshet Industrial Area, Thane West, Thane, Maharashtra, 400608, India                                                                                                                 2
Targhar B S N L, Central Bank Of India Staff Training College, Faizabad Road, Mahanagar Colony, Lucknow, Uttar Pradesh, 226006, India                                                                                2
Tara Cafe, 72, 80 Feet Rd, Koramangala 7 Block, 7th Block, Koramangala, Bengaluru, Karnataka, 560095, India                                                                                                          2
Surya Mytri, Rd Number 3, Hanuman Nagar, Jubilee Gardens, Kothaguda, Telangana, 500084, India                                                                                                                        2
Anil Beauty Cosmetics, Bin Trif Nagar, Raziya Complex, Banu Nagar, Madannapet Colony, Hyderabad, Telangana, 500059, India                                                                                            2
Apoorvam (B Desai Group), B/h, Vandemataram Icon, Opposite Prathna Elegance, Near By Aaryan City, Gota, Ahmedabad, Gujarat, 382481, India                                                                            2
Apollo MultiSpeciality Hospitals, Kolkata, 58, Canal Circular Rd, Kadapara, Phool Bagan, Kankurgachi, Kolkata, West Bengal 700054                                                                                    2
Aryans Dance Factory, SCO 11, Top Floor, Gillco Complex, Sector 127, Sector 4, Main Bazar, Kharar, Sahibzada Ajit Singh Nagar, Punjab, 140301, India                                                                 2
Ashok Leyland Dost LCV Asco Motors Delhi, Plot No 1 GuruNanak Auto Market, Libaspur, Delhi, 110042, India                                                                                                            2
Attiguppe Metro Station, Chord Road, PF Layout, Hampi Nagar, Bengaluru, Bangalore North, Bengaluru Urban, Karnataka, 560040, India                                                                                   2
Asif Tea Stall, 500, Chilla Sarda Bangar, Chilla Sarda Bangar Village, Trilokpuri, New Delhi, Delhi, 110091, India                                                                                                   2
Sportivo Sports Arena, Kushaiguda Rd, Opposite Mahindra Show Room And Bar Station, ECIL, Shiva Sai Nagar, Kushaiguda, Hyderabad, Secunderabad, Telangana, 500103, India                                              2
Southindia Properties SIP Ikon, Kelambakkam, Chennai, Kelambakkam, Chennai, 603103, India                                                                                                                            2
C.B. Chajed & Company, Old Prabhadevi Rd, Dadar West, Century Bazaar, Prabhadevi, Mumbai, Maharashtra, 400025, India                                                                                                 2
Blinkit Kannamangla Main Road, Unit-7, WayCool Foods Bangalore DC, Kannamangala Main Rd, Ardendale, Kannamangala, Karnataka, 560115, India                                                                           2
State Bank Of India, Karolan Ka Barh, Jaipur, Rajasthan, 302025, India                                                                                                                                               2
Sri Venkateshwara Public High School, 10th Cross, APR Kalyana Mantapa, Road, Maruthi Layout, Hongasandra, Bengaluru, Karnataka, 560068, India                                                                        2
State Bank Of India, SBI, Satnam Park, Block C, Krishna Nagar, Delhi, 110051, India                                                                                                                                  2
Surajilal Choud MahaLakshmi Collection, Hosapalaya, Muneshwara Nagar, Bengaluru, Karnataka, 560068, India                                                                                                            2
Bagara Biryani Cafe, R. Narayanapura, Whitefield, Gandhipura, Bengaluru, Bangalore East, Bengaluru Urban, Karnataka, 560066, India                                                                                   2
Southern Express Packers & Movers, Plot No. 89, Sector Number 23, Shree Vihar, Transport Nagar, Nigdi, Pune, Pimpri-Chinchwad, Maharashtra, 411044, India                                                            2
Soft Touch Ladies Beauty Parlour & Spa, Bc126, Samarpally, Baishnodevi Abasankrishnapur, Kestopur, Kolkata, West Bengal, 700102, India                                                                               2
Shree Sai EnterPrises, Dombala, Panvel, Navi Mumbai, Maharashtra, 410206, India                                                                                                                                      2
Shree Nakoda Distributors, Gala No-107, Shiv Sagar Industrial Estate Near Umiya Mata Mandir, Kotkar Compound, Vishveshwar Nagar Rd, Yashodham, Goregaon, Mumbai, Maharashtra, 400063, India                          2
Shefali Apartment, Bhatti Rd, Basai, Sector 70, Noida, Uttar Pradesh, 201307, India                                                                                                                                  2
Shanthi Dental Clinic, Tea Kadai, Bus Stop, Senthil Nagar, Urapakkam, Chengalpet, Tamil Nadu, 603210, India                                                                                                          2
Sham Sweets, 4, Express Way, 227, Gurgaon - Delhi Expy, Near Balaji Mandir, Shivaji Nagar, Sector 11, Gurugram, Haryana, 122001, India                                                                               2
Selvi Sweets And Bakery, East Coast Road, No:53, 23, Avvai Nagar Rd, Vasudeva Nagar Extension, Thiruvanmiyur, Chennai, Tamil Nadu, 600041, India                                                                     2
Sector 87 Shop No 4 Chandi Wala Bagh Near Shhardhha Mandir School Faridabad, Bharat Colony, Sector 87, Neharpar Faridabad, Faridabad, Haryana, 121014, India                                                         2
Sector 61 Ullwas Gaon, Sector 62, Gurugram, Haryana, 122102, India                                                                                                                                                   2
Devika Towers, Gf66, Block 1, P & T Colony, Raj Nagar, Ghaziabad, Uttar Pradesh, 201002, India                                                                                                                       2
Blinkit Dark Store Bhoomkar Chouk, Shankar Kalat Nagar, Wakad, Pimpri-Chinchwad, Maharashtra, 411057, India                                                                                                          2
Bikelele, Barat Ghar Rd, Tugalpur, Greater Noida, Uttar Pradesh, 201310, India                                                                                                                                       2
Sri Padmavathi School, Sai Ram Enclave, Naredra Nagar Rd, Ameenpur Village, Ameenpur, Miyapur, Telangana, 502032, India                                                                                              2
Sri Lakshmi Narasimha Nilayam, 42, 1st Main Rd, Balaji Layout, Green Woods Layout, Varanasi, Bengaluru, Karnataka, 560049, India                                                                                     2
Chicken Basket, H.No, 2-56, Khajaguda - Nanakramguda Rd, Near Ghanashyam Super Market, Janmabhoomi Colony, Chaitanya Enclave, Hyderabad, Telangana, 500075, India                                                    2
D Mart, 283/A, Rd Number 36, Behind D-Mart, Kavuri Hills, Madhapur, Telangana, 500033, India                                                                                                                         2
Carmasters, A-184, A Block, Sector 63, Noida, Uttar Pradesh, 201307, India                                                                                                                                           2
Charvi Bridal Jewelery, Vidya Nagar, T. Dasarahalli, Bengaluru, Karnataka, 560057, India                                                                                                                             2
Fitlane, Opposite Paras Tierea, Sector 137, Noida, Uttar Pradesh, 201305, India                                                                                                                                      2
F Salon By FTV Andheri, Mohit Tower, 4, K D Gaikwad Road, Bhudargarh Colony, K/w Ward, Zone 3, Mumbai Suburban, Maharashtra, 400053, India                                                                           2
Dua Old Age Home | Old Age Home | Senior Citizen Care | Assisted Living | Nursing Home | Dementia & Alzheimer & ICU Care, H-58, Sector 116, Noida, Uttar Pradesh, 201304, India                                      2
Car Kia Service Center Raidurg - Gachibowli | Kia Authorized Service Center Hyderabad, Survey No 224, Wipro Circle Rd, Near Lemon Tree Hotel, Financial District, Gachibowli, Hyderabad, Telangana, 500111, India    2
Dr Kartik Chadha, 375, Mukherjee Nagar, Near Sadgurudham Mandir, Munshi Ram Colony, Mukherjee Nagar, Delhi, 110009, India                                                                                            2
Satisloh AG India Branch Office, Shop No.10, Jaferbhoy Industrial Building, Makwana Rd, Gamdevi, Marol, Andheri East, Mumbai, Maharashtra, 400059, India                                                             2
SatGuru Complex, C.P 40, Kanpur Rd, Sector B, Bargawan, LDA Colony, Lucknow, Uttar Pradesh, 226012, India                                                                                                            2
Saraswati Tower Greater Noida West, Behind Ace City, Ace City Noida Extension, Sector 1, Greater Noida, Bisrakh Jalalpur, Uttar Pradesh, 203207, India                                                               2
Sangme Digital Production, Sri Venkateshvar Lauout Abbigere Shettihalli Ward Number 12, Kereguddadahalli, Chikkabanavara, Bengaluru, Karnataka, 560090, India                                                        2
Sahyadri Luxury Homes, Sri Ram Layout, Varthur, Karnataka, 560087, India                                                                                                                                             2
Saggi Solutions, House No. 76, M.G Layout, Mullur Rd, Bengaluru, Karnataka, 560035, India                                                                                                                            2
Dr. Florence Vasantha Prabha, 1B Malaragam, VGP Saraswathy Nagar Road, Madambakkam, Rajakilpakkam, Tamil Nadu, 600073, India                                                                                         2
Sage Hospital, Ground Floor, Aditya Heritage Industrial Premises Co. Operative Society Elanza Avenue, Mind Space, Next To Rustomjee Elanza, Malad, Towers, Malad West, Mumbai, Maharashtra, 400095, India            2
Saai Eye Hospital And Eye Plasty Center, AECS Layout D Block AECS Layout Bangalore East Bengaluru Urban Karnataka 560037 India                                                                                       2
SK.Khan Car Service Point, Agrahara Layout, Yelahanka Taluku, Bengaluru Urban, Karnataka, 560064, India                                                                                                              2
SRS Cinemas, Reach 2, Block-S, Block S, Sector 49, Gurugram, Haryana, 122018, India                                                                                                                                  2
Herz Kitchen, Taj Residency, Ashok Vihar Colony, Upperpally, Pillar No 195, Near Sai Baba Temple, Ashok Vihar Colony, Fort View Colony, Janachaitanya Colony, Hyderabad, Telangana, 500030, India                    2
HPL Engineering Services, 6, Amrut Angan, Phase I, West, Opp. Reliance Market, Parsik Nagar, Kalwa, Thane, Maharashtra, 400605, India                                                                                2
Gyan Sagar RWA Lane, Gyan Sagar RWA LN, Gyan Khand 1, Indirapuram, Ghaziabad, Uttar Pradesh, 201014, India                                                                                                           2
SG Energy Infra, Gopi Talav, Kot Safil Road, Salabatpura, Surat, Gujarat, 395002, India                                                                                                                              2
Gurukul's Sports, 176/1, Varthur Main Rd, Thubarahalli, Whitefield, Bengaluru, Karnataka, 560066, India                                                                                                              2
Gulshan Fish And Chicken Corner, 39, KC Rd, Block 1, New Industrial Twp 4, New Industrial Township, Faridabad, Haryana, 121001, India                                                                                2
Golden Tobacco Limited, Tobacco House, S.V. Road, Vile Parle (West), Navpada, Vile Parle West, Mumbai, Maharashtra, 400049, India                                                                                    2

In [40]:
data[data['store_name_location'] == 'Anika Redwood Square, Nagarabhavi Main Rd, 2nd Block, Coconut Garden, Chalukya Nagar, Bhyraveshwara Nagar, Bengaluru, Karnataka, 560072, India'][['store_id', 'store_name_location', 'city', 'pin_code']].drop_duplicates()

,store_id,store_name_location,city,pin_code
281070,4778fa3d-0494-484a-b488-e2b40088ddd7,"Anika Redwood Square, Nagarabhavi Main Rd, 2nd Block, Coconut Garden, Chalukya Nagar, Bhyraveshwara Nagar, Bengaluru, Karnataka, 560072, India",Bangalore,560072
284412,658cf319-0b10-4dbe-809e-ea5c913974cb,"Anika Redwood Square, Nagarabhavi Main Rd, 2nd Block, Coconut Garden, Chalukya Nagar, Bhyraveshwara Nagar, Bengaluru, Karnataka, 560072, India",Bangalore,560072
311024,5400933d-3c5d-4015-a767-daed27781a0d,"Anika Redwood Square, Nagarabhavi Main Rd, 2nd Block, Coconut Garden, Chalukya Nagar, Bhyraveshwara Nagar, Bengaluru, Karnataka, 560072, India",Bangalore,560072

In [42]:
pin_check = (
    data.groupby("store_name_location")["pin_code"]
        .nunique()
        .sort_values(ascending=False)
)

pin_check[pin_check > 1]

Series([], Name: pin_code, dtype: int64)

In [44]:
check = (
    data.groupby("store_name_location")
    .agg(
        store_ids=("store_id", "nunique"),
        cities=("city", "nunique"),
        pincodes=("pin_code", "nunique")
    )
)

check[check["store_ids"] > 1]

,store_ids,cities,pincodes
store_name_location,,,
"1, Dattani Park Rd, Thakur, Dattani Park, Thakur Village, Kandivali East, Mumbai, Maharashtra, 400066, India",2,1,1
"114, Regent Rd, Tilak Nagar, Regent Park, Kolkata, West Bengal, 700040, India",2,1,1
"12, Mhalunge - Nande Rd, Mahalunge, Pune, Maharashtra, 411045, India",2,1,1
"126, MM Road, Pulikeshi Nagar, Bengaluru, Karnataka, 560005, India",2,1,1
"164-132, Hill Rd, Bandra West, Mumbai, Maharashtra, 400050, India",2,1,1
"2, Mumbai Cantral Rd, Dadal Estate, Bane Compound, Tardeo, Mumbai, Maharashtra, 400034, India",2,1,1
"2/51, Bhosari Sambhaji Nagar, Gaikwad Nagar, Dighi, Pimpri Chinchwad, Pimpri-Chinchwad, Maharashtra, 411015, India",2,1,1
"45, Kodigehalli Main Rd, Amco Colony, Devinagar, Bengaluru, Karnataka, 560092, India",2,1,1
"49, Jhowtala Rd, Park Circus, Ballygunge, Kolkata, West Bengal, 700019, India",2,1,1
"5, Kanakapura Rd, Jayanagar, Bengaluru, Karnataka, 560070, India",2,1,1
"7 Classes Hiranandani (Heera Panna Shopping Centre, ), Shop No.1049, First Floor, Heera Panna Shopping Centre, Mhada Colony 19, Powai, Mumbai, Maharashtra, 400076, India",2,1,1
"8/225, Sector, 8, Malviya Nagar, Jaipur, Rajasthan, 302017, India",2,1,1
"AISECT Office & Education Centre Hyderabad, Gayathri's Sri Sai Enclave, 3Floor, Musheerabad Main Rd, Musheerabad, Dayara, Hyderabad, Telangana, 500020, India",2,1,1
"AKJ Green Floors, Ansal API, Sushant Aquapolis, B-110, Crossings Republik, Ghaziabad, Uttar Pradesh, 201009, India",2,1,1
"AZB & Partners, A-8, Amaltash Marg, Block A, Sector 4, Noida, Uttar Pradesh, 201301, India",2,1,1
"Aakruthi Sunshine Apartment, Aakruthi Sunshine, Panathur Main Rd, Kaverappa Layout, Kadubeesanahalli, Bengaluru, Karnataka, 560103, India",2,1,1
"Aama Tattoo Inn, Balkum Road, Kolshet Industrial Area, Thane West, Thane, Maharashtra, 400608, India",2,1,1
"Abakash Apartment Nagerbazar, Nagendra Nath Rd, Nagerbazar, Kamardanga, Kolkata, West Bengal, 700028, India",2,1,1
"Abhishek Gas Agencies, No. 923, GF, VR Arcade, 1st Cross Rd, Near Corporation Bank, Remco Bhel Layout, Javarandoddi, RajaRajeshwari Nagar, Bengaluru, Karnataka, 560039, India",2,1,1
"Aeromarine Private Limited, 20, Jawahar Industrial Estate, Opposite To Mcdonald, Near J.K. Industries, Jawahar Co-Op Ind, Kamothe, Panvel, Navi Mumbai, Maharashtra, 410209, India",2,1,1
"Agarwal Furniture - Best Furniture Showroom In Manesar - Best Furniture Showroom In New Gurgaon, Shop No. 1, Near Rampura FlyOver, NH-8, Manesar, Gurugram, Haryana, 122004, India",2,1,1
"Ahilya Marg, Block C, Chander Nagar, Surya Nagar, Ghaziabad, Uttar Pradesh, 201011, India",2,1,1
"Anika Redwood Square, Nagarabhavi Main Rd, 2nd Block, Coconut Garden, Chalukya Nagar, Bhyraveshwara Nagar, Bengaluru, Karnataka, 560072, India",3,1,1
"Anil Beauty Cosmetics, Bin Trif Nagar, Raziya Complex, Banu Nagar, Madannapet Colony, Hyderabad, Telangana, 500059, India",2,1,1
"Anju Boutique Cosmetic, 920, Jaina Market, Nathuram Market, DLF Phase 4, Nathuram Market, Chakkarpur, Sector 28, Gurugram, Haryana, 122002, India",3,1,1
"Apollo MultiSpeciality Hospitals, Kolkata, 58, Canal Circular Rd, Kadapara, Phool Bagan, Kankurgachi, Kolkata, West Bengal 700054",2,1,1
"Apoorvam (B Desai Group), B/h, Vandemataram Icon, Opposite Prathna Elegance, Near By Aaryan City, Gota, Ahmedabad, Gujarat, 382481, India",2,1,1
"Aryans Dance Factory, SCO 11, Top Floor, Gillco Complex, Sector 127, Sector 4, Main Bazar, Kharar, Sahibzada Ajit Singh Nagar, Punjab, 140301, India",2,1,1
"Ashok Leyland Dost LCV Asco Motors Delhi, Plot No 1 GuruNanak Auto Market, Libaspur, Delhi, 110042, India",2,1,1
"Asif Tea Stall, 500, Chilla Sarda Bangar, Chilla Sarda Bangar Village, Trilokpuri, New Delhi, Delhi, 110091, India",2,1,1
"Attiguppe Metro Station, Chord Road, PF Layout, Hampi Nagar, Bengaluru, Bangalore North, Bengaluru Urban, Karnataka, 560040, India",2,1,1
"Aurinko Academy - IGCSE Cambridge Alternative Progressive School, 91, Opposite To Hosa Road, Parappana Agrahara, Bengaluru, Karnataka, 560035, India",2,1,1
"BLS ACLS Pals ITLS Courses At Nashik | Charles Institute, Near Guruji Rugnalaya, Rameshwar Nagar, Balawant Nagar, Savarkar Nagar, Nashik, Maharashtra, 422013, India",2,1,1
"BM Lal Brothers, 34, Opposite Sathyam Theatre Car Parking, Whites Road, Royapettah, Express Estate, Royapettah, Chennai, Tamil Nadu, 600002, India",2,1,1
"Bagara Biryani Cafe, R. Narayanapura, Whitefield, Gandhipura, Bengaluru, Bangalore East, Bengaluru Urban, Karnataka, 560066, India",2,1,1
"Banswadi, 100 Feet Rd, HRBR Layout 1st Block, HRBR Layout, Kalyan Nagar, Bengaluru, Karnataka, 560043, India",2,1,1
"Big Basket Warehouse Hafeezpet, Janapriya Nagar, Hafeezpet, Hyderabad, Telangana, 500049, India",2,1,1
"Bikelele, Barat Ghar Rd, Tugalpur, Greater Noida, Uttar Pradesh, 201310, India",2,1,1
"Blinkit Dark Store Bhoomkar Chouk, Shankar Kalat Nagar, Wakad, Pimpri-Chinchwad, Maharashtra, 411057, India",2,1,1
"Blinkit Kannamangla Main Road, Unit-7, WayCool Foods Bangalore DC, Kannamangala Main Rd, Ardendale, Kannamangala, Karnataka, 560115, India",2,1,1
"C.B. Chajed & Company, Old Prabhadevi Rd, Dadar West, Century Bazaar, Prabhadevi, Mumbai, Maharashtra, 400025, India",2,1,1
"Car Kia Service Center Raidurg - Gachibowli | Kia Authorized Service Center Hyderabad, Survey No 224, Wipro Circle Rd, Near Lemon Tree Hotel, Financial District, Gachibowli, Hyderabad, Telangana, 500111, India",2,1,1
"Carmasters, A-184, A Block, Sector 63, Noida, Uttar Pradesh, 201307, India",2,1,1
"Ceramic Pro Whitefeild - Bangalore (Route 66 Detailing) Best Detailing Studio In The Neighbourhood, 443, Varthur Main Rd, Phase 1, Siddapura, Whitefield, Bengaluru, Karnataka, 560066, India",3,1,1
"Charvi Bridal Jewelery, Vidya Nagar, T. Dasarahalli, Bengaluru, Karnataka, 560057, India",2,1,1
"Chicken Basket, H.No, 2-56, Khajaguda - Nanakramguda Rd, Near Ghanashyam Super Market, Janmabhoomi Colony, Chaitanya Enclave, Hyderabad, Telangana, 500075, India",2,1,1
"D Mart, 283/A, Rd Number 36, Behind D-Mart, Kavuri Hills, Madhapur, Telangana, 500033, India",2,1,1
"Dantoon Dental Clinic & Orthodontic Center, 1st Floor, Sai Mahal, Whitefield Main Rd, Pattandur Agrahara, Whitefield, Bengaluru, Karnataka, 560066, India",2,1,1
"Detailing Bull Gurugram, F7, Near Hong Kong Bazar, Block F, Sushant Lok 2, Sector 57, Gurugram, Haryana, 122011, India",2,1,1
"Devika Towers, Gf66, Block 1, P & T Colony, Raj Nagar, Ghaziabad, Uttar Pradesh, 201002, India",2,1,1
"Dr Kartik Chadha, 375, Mukherjee Nagar, Near Sadgurudham Mandir, Munshi Ram Colony, Mukherjee Nagar, Delhi, 110009, India",2,1,1
"Dr. Florence Vasantha Prabha, 1B Malaragam, VGP Saraswathy Nagar Road, Madambakkam, Rajakilpakkam, Tamil Nadu, 600073, India",2,1,1
"Dua Old Age Home | Old Age Home | Senior Citizen Care | Assisted Living | Nursing Home | Dementia & Alzheimer & ICU Care, H-58, Sector 116, Noida, Uttar Pradesh, 201304, India",2,1,1
"F Salon By FTV Andheri, Mohit Tower, 4, K D Gaikwad Road, Bhudargarh Colony, K/w Ward, Zone 3, Mumbai Suburban, Maharashtra, 400053, India",2,1,1
"Fitlane, Opposite Paras Tierea, Sector 137, Noida, Uttar Pradesh, 201305, India",2,1,1
"GRS Convention Hall, Govindaraja Nagar Ward, Krishnananda Nagar, Naagarabhaavi, Bengaluru, Karnataka, 560072, India",2,1,1
"Glori By Noshh, 3rd Floor, Mckenzie Tower, C-97, Mayapuri Industrial Area Phase I, Mayapuri, New Delhi, Delhi, 110064, India",2,1,1
"Goel Traders, 1539, GuruDwara Rd, South Extension, Kotla Mubarakpur, Kotla, New Delhi, Delhi, 110003, India",3,1,1
"Golden Glove Interiors, Plot 216, Near Anand Interiors, Industrial Area, Daulatabad, Gurugram, Haryana, 122006, India",2,1,1
"Golden Tobacco Limited, Tobacco House, S.V. Road, Vile Parle (West), Navpada, Vile Parle West, Mumbai, Maharashtra, 400049, India",2,1,1
"Goyal Store, 80, Vrindavan Garden, Brindavan Garden Extension, Sahibabad, Ghaziabad, Uttar Pradesh, 201005, India",2,1,1
"Gulshan Fish And Chicken Corner, 39, KC Rd, Block 1, New Industrial Twp 4, New Industrial Township, Faridabad, Haryana, 121001, India",2,1,1
"Gurukul's Sports, 176/1, Varthur Main Rd, Thubarahalli, Whitefield, Bengaluru, Karnataka, 560066, India",2,1,1
"Gyan Sagar RWA Lane, Gyan Sagar RWA LN, Gyan Khand 1, Indirapuram, Ghaziabad, Uttar Pradesh, 201014, India",2,1,1
"HPL Engineering Services, 6, Amrut Angan, Phase I, West, Opp. Reliance Market, Parsik Nagar, Kalwa, Thane, Maharashtra, 400605, India",2,1,1
"Herz Kitchen, Taj Residency, Ashok Vihar Colony, Upperpally, Pillar No 195, Near Sai Baba Temple, Ashok Vihar Colony, Fort View Colony, Janachaitanya Colony, Hyderabad, Telangana, 500030, India",2,1,1
"Hotel Sion Fort, Gala No - 109, Beside VVF Limited, Near Sion Fort, Sion East, Sion, Mumbai, Maharashtra, 400022, India",2,1,1
"Indian Bank, No. 2, 248, Poonamallee - Avadi High Rd, Senneer Kuppam, Poonamallee, Chennai, Tamil Nadu, 600056, India",2,1,1
"Infinity Tower, 15, Narayan Dabholkar Rd, Off Nepean Sea Road, Navshanti Nagar, Malabar Hill, Mumbai, Maharashtra, 400006, India",2,1,1
"Iqbal Bus Body Builder, Block B, Sector 43, Noida, Uttar Pradesh, 201303, India",2,1,1
"Jai Kishan Gupta, A 20 Gali No 1, Sanjay Nagar, Adarsh Nagar, Delhi, 110033, India",2,1,1
"Jai Kumar, 374, Sector 17/18 Dividing Rd, Electronic City, Phase IV, Udyog Vihar, Sector 18, Gurugram, Haryana, 122015, India",2,1,1
"Jupiter Computers, 45a/1, Central Rd, Bidhanpally, Jadavpur, Kolkata, West Bengal, 700032, India",2,1,1
"Kavitha Ladies Tailor, Medchal Mandal, MedchalÃ£Â¢Ã¢ÂÃ¢Âmalkajgiri, Telangana, 500100, India",2,1,1
"Keerthi Regency, Kaggadasapura, Bangalore, 560093, India",2,1,1
"Kesava Towers, SY. No. 78, 3, Hafeezpet Rd, Bikshapathi Nagar, Hafeezpet, Serilingampalle (M), Hyderabad, Telangana, 500085, India",2,1,1
"Kessa, Ground Floor, Door No. 8-2, KR Towers, 699/1/402, Road No. 12, Syed Nagar, Banjara Hills, Hyderabad, Telangana, 500034, India",2,1,1
"King Mens Wear, Shop No 5 Jijamata Nagar, Kamgar Hospital Rd, Ramachandra Nagar, Waghle Estate, Thane West, Thane, Maharashtra, 400604, India",3,1,1
"Kp'S Restaurant, 411036, Matruchhaya Building, Poonawalla Road, Sasane Colony, Keshav Nagar, Mundhwa, Pune, Maharashtra",2,1,1
"Kurinji Apartments, Plot No, 51, 2nd Cross St, Sachidananda Puram, Thazhambur, Chennai, Tamil Nadu, 600130, India",2,1,1
"Kurtosshhh - Hungarian Street Food (Kurtosh), Ground Floor W One Building Kuzhikattumoola Junction, Kusumagiri P.O Kakkanad, Kalappurakkal, Kusumagiri, Kochi, Kerala, 682039, India",2,1,1
"Lila Shah Exports - Vintage Wrap Sari Silk Skirt Garments Manufacturers Factory, P. No. 172, 173, Muhana Mandi Rd, Near Kesar International School, Kesar Nagar, Mansarovar, Jaipur, Rajasthan, 302029, India",2,1,1
"MTNL KP Block Office, First Floor, Near Aakash Institute, Pitampura, Adarsh Nagar, Block KP, Poorvi Pitampura, Pitampura, Delhi, 110088, India",2,1,1
"Magnate Icon, New Ranip, Ahmedabad, Gujarat, 382470, India",2,1,1
"Manasa Boutique, HMT, JNTU Police Station Road, Rd Number 9, Opposite Reliance Smart Point, Western Hills, Jal Vayu Vihar, Kukatpally, Hyderabad, Telangana, 500090, India",2,1,1
"Mangalam Motors, B-114, Nigo's Building, Cama Industrial Estate, Goregaon, Mumbai, Maharashtra, 400063, India",2,1,1
"Mithuna White Water Apartments, Mithuna White Waters, Amruthahalli Main Rd, Jakkuru, Bengaluru, Karnataka, 560064, India",2,1,1
"Mody Ford, No 52, Indraprastha Colony, Bandlaguda, Nagole, Hyderabad, Telangana, 500068, India",2,1,1
"Mohan Meaking Society, Sector-5, Sector 5, Indirapuram, Ghaziabad, Uttar Pradesh, 201012, India",2,1,1
"NSM RoadWays, 14, A Block, GKRB Rd, Old Madiwala, Jay Bheema Nagar, 1st Stage, BTM Layout, Bengaluru, Karnataka, 560068, India",3,1,1
"Nandesh Food Centre, TC Palya, Seegehalli, Bengaluru, Bangalore East, Bengaluru Urban, Karnataka, 560049, India",2,1,1
"Nano Hospitals, Uttarahalli, No. 47 12/1A Uttarahalli Main Rd Near Bharat Petrol Bunk Simhadri Layout Uttarahalli Hobli Bengaluru Karnataka 560061",2,1,1
"National Mart, 8-40/1 Narayanapuram Colony Dammaiguda Municipality, Medchal, Narayana Puri Colony, Sai Priya Colony, Malkajgiri, Hyderabad, Telangana, 500083, India",2,1,1
"Navi Mumbai Municipal Corporation- B Ward Office, Sector 14 Nerul Rd, Dharshana Society, Sector 14, Nerul, Navi Mumbai, Maharashtra 400706, India",2,1,1
"NeelKanth Lake View, Near NeelKanth Heights, Pokharan Rd Number 2, Devdaya Nagar, Shivai Nagar, Thane West, Thane, Maharashtra, 400606, India",2,1,1
"NewTown Square Mall, NewTown Square Sector 95A Gurgaon, Pataudi Rd, Sector 95A, Gurugram, Haryana, 122505, India",2,1,1
"Nine 2 Twelve Khana Ghar Jaisa, Marathahalli Village, Marathahalli, Bengaluru, Karnataka, 560037, India",2,1,1
"OYO 823320 JVP Hotels, Plot No. 53, SY. No. 11/19, 11/20, Kabadi Godown, 11/21, Survey Of 500081, India Colony, Chanda Naik Nagar, Madhapur, Hyderabad, Telangana",2,1,1
"Omi Tuition Classes/coaching Centre(otc), Near Sangam Sweet Shop, Near Chauma, Chauma Village, Sector 1, Mahzid, Gurugram, Haryana, 122017, India",2,1,1
"Pavithra Toolings, Jayachamarajendra Industrial Estate, Kumaraswamy Layout, Bengaluru, Karnataka, 560111, India",2,1,1
"Pawan Nivas, Near RamDev Medical, Lake View Residency, Adarsh Palm Retreat, Bellandur, Bengaluru, Karnataka, 560103, India",2,1,1
"Pepitos HQ, C-28, C Block, Sector 6, Noida, Uttar Pradesh, 201301, India",2,1,1
"Prime Gardens, Moti Nagar Phase III, Kalyan Nagar, Moti Nagar, Hyderabad, Telangana, 500018, India",2,1,1
"Q Connect Business Solutions Limited, Sai Nagar, Anand Nagar, Thane West, Mumbai, Maharashtra, 400615, India",2,1,1
"Ramanuja Credit Co Op Soc Limited, No 22, Seshadri Rd, Lakshmanpuri, Gandhi Nagar, Bengaluru, Karnataka, 560009, India",3,1,1
"Rattan Icon, 121, New Sector-50, Sector 50 East, Seawoods, Navi Mumbai, Maharashtra, 400706, India",2,1,1
"Rawat Painters, RZ 124, Sayed Gaon, Nangloi Saiyed Village, Paschim Vihar, Delhi, 110087, India",2,1,1
"Reebok Outlet, 71/4, Rama Rd, Moti Nagar, New, Najafgarh Road Industrial Area, Delhi, 110015, India",2,1,1
"Reliance Smart SuperStore, Indiraj Arcade, Near Jharsa Road, Kirti Nagar, Part 2, Sector 15, Gurugram, Haryana 122001, India",2,1,1
"Revv Self Drive Car Rental, SY.No. 50/1, Beside Mantri Espana, Kaveri Layout, Devarabisanahalli, Bellandur, Bengaluru, Karnataka, 560037, India",2,1,1
"Rohit Wadewale, Hinjewadi - Kasarsai Rd, Phase 1, Marunji, Marunji Village, Hinjawadi, Pimpri-Chinchwad, Maharashtra, 411057, India",2,1,1
"Rukmini Enclave Road, Rukmini Enclave Rd, Prem Nagar, Bolarum, Secunderabad, Telangana, 500010, India",2,1,1
"SG Energy Infra, Gopi Talav, Kot Safil Road, Salabatpura, Surat, Gujarat, 395002, India",2,1,1
"SK.Khan Car Service Point, Agrahara Layout, Yelahanka Taluku, Bengaluru Urban, Karnataka, 560064, India",2,1,1
"SRS Cinemas, Reach 2, Block-S, Block S, Sector 49, Gurugram, Haryana, 122018, India",2,1,1
"Saai Eye Hospital And Eye Plasty Center, AECS Layout D Block AECS Layout Bangalore East Bengaluru Urban Karnataka 560037 India",2,1,1
"Sage Hospital, Ground Floor, Aditya Heritage Industrial Premises Co. Operative Society Elanza Avenue, Mind Space, Next To Rustomjee Elanza, Malad, Towers, Malad West, Mumbai, Maharashtra, 400095, India",2,1,1
"Saggi Solutions, House No. 76, M.G Layout, Mullur Rd, Bengaluru, Karnataka, 560035, India",2,1,1
"Sahyadri Luxury Homes, Sri Ram Layout, Varthur, Karnataka, 560087, India",2,1,1
"Sangme Digital Production, Sri Venkateshvar Lauout Abbigere Shettihalli Ward Number 12, Kereguddadahalli, Chikkabanavara, Bengaluru, Karnataka, 560090, India",2,1,1
"Saraswati Tower Greater Noida West, Behind Ace City, Ace City Noida Extension, Sector 1, Greater Noida, Bisrakh Jalalpur, Uttar Pradesh, 203207, India",2,1,1
"SatGuru Complex, C.P 40, Kanpur Rd, Sector B, Bargawan, LDA Colony, Lucknow, Uttar Pradesh, 226012, India",2,1,1
"Satisloh AG India Branch Office, Shop No.10, Jaferbhoy Industrial Building, Makwana Rd, Gamdevi, Marol, Andheri East, Mumbai, Maharashtra, 400059, India",2,1,1
"Sector 61 Ullwas Gaon, Sector 62, Gurugram, Haryana, 122102, India",2,1,1
"Sector 87 Shop No 4 Chandi Wala Bagh Near Shhardhha Mandir School Faridabad, Bharat Colony, Sector 87, Neharpar Faridabad, Faridabad, Haryana, 121014, India",2,1,1
"Selvi Sweets And Bakery, East Coast Road, No:53, 23, Avvai Nagar Rd, Vasudeva Nagar Extension, Thiruvanmiyur, Chennai, Tamil Nadu, 600041, India",2,1,1
"Sham Sweets, 4, Express Way, 227, Gurgaon - Delhi Expy, Near Balaji Mandir, Shivaji Nagar, Sector 11, Gurugram, Haryana, 122001, India",2,1,1
"Shanthi Dental Clinic, Tea Kadai, Bus Stop, Senthil Nagar, Urapakkam, Chengalpet, Tamil Nadu, 603210, India",2,1,1
"Shefali Apartment, Bhatti Rd, Basai, Sector 70, Noida, Uttar Pradesh, 201307, India",2,1,1
"Shree Nakoda Distributors, Gala No-107, Shiv Sagar Industrial Estate Near Umiya Mata Mandir, Kotkar Compound, Vishveshwar Nagar Rd, Yashodham, Goregaon, Mumbai, Maharashtra, 400063, India",2,1,1
"Shree Sai EnterPrises, Dombala, Panvel, Navi Mumbai, Maharashtra, 410206, India",2,1,1
"Soft Touch Ladies Beauty Parlour & Spa, Bc126, Samarpally, Baishnodevi Abasankrishnapur, Kestopur, Kolkata, West Bengal, 700102, India",2,1,1
"Southern Express Packers & Movers, Plot No. 89, Sector Number 23, Shree Vihar, Transport Nagar, Nigdi, Pune, Pimpri-Chinchwad, Maharashtra, 411044, India",2,1,1
"Southindia Properties SIP Ikon, Kelambakkam, Chennai, Kelambakkam, Chennai, 603103, India",2,1,1
"Sportivo Sports Arena, Kushaiguda Rd, Opposite Mahindra Show Room And Bar Station, ECIL, Shiva Sai Nagar, Kushaiguda, Hyderabad, Secunderabad, Telangana, 500103, India",2,1,1
"Spunky Homes, Preston Prime Mall, Lumbini Avenue, Gachibowli, Hyderabad, Telangana, 500081, India",3,1,1
"Sri Lakshmi Narasimha Nilayam, 42, 1st Main Rd, Balaji Layout, Green Woods Layout, Varanasi, Bengaluru, Karnataka, 560049, India",2,1,1
"Sri Padmavathi School, Sai Ram Enclave, Naredra Nagar Rd, Ameenpur Village, Ameenpur, Miyapur, Telangana, 502032, India",2,1,1
"Sri Venkateshwara Public High School, 10th Cross, APR Kalyana Mantapa, Road, Maruthi Layout, Hongasandra, Bengaluru, Karnataka, 560068, India",2,1,1
"Sripathi Solutions, Devi Padmasree Convention Backside, Balaji Hills Rd, Nagaarjun Colony, Mallikarjuna Nagar, Boduppal, Hyderabad, Telangana, 500092, India",3,1,1
"State Bank Of India, Karolan Ka Barh, Jaipur, Rajasthan, 302025, India",2,1,1
"State Bank Of India, SBI, Satnam Park, Block C, Krishna Nagar, Delhi, 110051, India",2,1,1
"Surajilal Choud MahaLakshmi Collection, Hosapalaya, Muneshwara Nagar, Bengaluru, Karnataka, 560068, India",2,1,1
"Surya Mytri, Rd Number 3, Hanuman Nagar, Jubilee Gardens, Kothaguda, Telangana, 500084, India",2,1,1
"Tara Cafe, 72, 80 Feet Rd, Koramangala 7 Block, 7th Block, Koramangala, Bengaluru, Karnataka, 560095, India",2,1,1
"Targhar B S N L, Central Bank Of India Staff Training College, Faizabad Road, Mahanagar Colony, Lucknow, Uttar Pradesh, 226006, India",2,1,1
"Temple Stone Residency, Templestone Residency, Rd Number 10, Madhavapuri Hills, PJR Enclave, PJR Layout, Chanda Nagar, Hyderabad, Miyapur, Telangana, 502032, India",2,1,1
"The MidTown, Virar - Nallasopara Link Rd, Sriprastha, Nalasopara West, Palghar, Nala Sopara, Maharashtra, 401203, India",2,1,1
"Thehrav Homestay(caramel Homes), Rz10b/13, Kailashpuri Main, Kailash Puri, Palam, New Delhi, Delhi, 110045, India",2,1,1
"Time Steel Traders, Irandankattalai, Tamil Nadu, 600132, India",2,1,1
"VLCC Beauty Clinic (Sohna Road, Gurgaon), Shop No, 22, Badshahpur Sohna Rd Hwy, Vatika City, Block W, Market, Sector 49, Gurugram, Haryana, 122018, India",2,1,1
"Venkat S.V.B Bricks, Main Road, Saroornagar, Brindavan Colony, Vanasthalipuram, Hyderabad, Telangana, 500035, India",2,1,1
"Village Side Cafe, Nr. Pixcy Kennel, Village Side Cafe, Kutchi Sarvoday Trust Ground, Yogi Nagar Marg, Yogi Nagar, Borivali West, Mumbai, Maharashtra, 400092, India",3,1,1
"Wellington Terrace, 6b 13, Dr SC Fernandes Rd, Dhus Wadi, Sonapur, Marine Lines, Mumbai, Maharashtra, 400002, India",2,1,1

#### Unique_id check

In [46]:
product_name_check = (
    data.groupby("unique_id")["product_name"]
    .nunique()
)

product_name_check[product_name_check > 1]

unique_id
599eb2e4-a83d-4caa-9163-3137890dfa3f    2
af9daf8a-7c57-45a4-a33b-a94585c9ba5f    2
f1a1dd6f-5df5-4ae1-b8ce-29463ad8c218    2
Name: product_name, dtype: int64

In [54]:
# Find unique_ids with multiple product names
anomaly_ids = (
    data.groupby("unique_id")["product_name"]
    .nunique()
    .loc[lambda x: x > 1]
    .index
)

# Fetch rows for those unique_ids and remove duplicate product names
result = (
    data[data["unique_id"].isin(anomaly_ids)]
    .drop_duplicates(subset=["unique_id", "product_name"])
    .sort_values(["unique_id", "product_name"])
)

result

,crawl_date_and_time,platform_name,store_id,store_name_location,city,pin_code,unique_id,product_id_upc_ean,department,category,sub_category,brand_name,product_name,product_grammage,net_quantity,variants,item_mrp,item_selling_price,out_of_stock_flag,discount_flag,product_price,promo_offer_description,promo_offer_price,discount_in_percent,stock_count,product_url
1011976,2026-07-04 07:04:35,zepto,1db5fffc-4eca-4f44-8ba6-14c5c107e81f,"Shefali Apartment, Bhatti Rd, Basai, Sector 70, Noida, Uttar Pradesh, 201307, India",Noida,201307,599eb2e4-a83d-4caa-9163-3137890dfa3f,f6d19988-d0cb-47fd-a69f-b44a9ddac588,Bakery & Biscuits,"Dairy, Bread & Eggs",Breads & Buns,Theobroma,Theobroma Pure Whole Wheat Bread,350 g,1 pack (350 g),NaN,70.0,66.0,No,Yes,66.0,₹4 OFF,66.0,5,2,https://www.zepto.com/pn/theobroma-pure-whole-wheat-bread/pvid/599eb2e4-a83d-4caa-9163-3137890dfa3f
3297,2026-07-04 00:12:16,zepto,b4dc8d65-ed2e-4142-81b6-373982b13500,"Bagara Biryani Cafe, R. Narayanapura, Whitefield, Gandhipura, Bengaluru, Bangalore East, Bengaluru Urban, Karnataka, 560066, India",Bangalore,560066,599eb2e4-a83d-4caa-9163-3137890dfa3f,f6d19988-d0cb-47fd-a69f-b44a9ddac588,Bakery & Biscuits,"Dairy, Bread & Eggs",Breads & Buns,Theobroma,Theobroma Zero Maida Whole wheat bread | No Preservatives | No Palm Oil,350 g,1 pack (350 g),NaN,70.0,66.0,Yes,Yes,66.0,₹4 OFF,66.0,5,0,https://www.zepto.com/pn/theobroma-zero-maida-whole-wheat-bread-no-preservatives-no-palm-oil/pvid/599eb2e4-a83d-4caa-9163-3137890dfa3f
86086,2026-07-04 00:40:48,zepto,bf926ab8-f286-4011-8de2-2561674ec588,"Cotfab India, VishwaKarma Industrial Area, Jaipur, Rajasthan, 302039, India",Jaipur,302039,af9daf8a-7c57-45a4-a33b-a94585c9ba5f,6299c551-668f-4b9e-97d8-f938c1b21368,Sweet Tooth,Ice Creams & More,Cones,Giani's,Giani's Butter Scotch Ice Cream Cone,120 ml,1 pc (120 ml),NaN,60.0,54.0,No,Yes,54.0,₹6 OFF,54.0,10,4,https://www.zepto.com/pn/gianis-butter-scotch-ice-cream-cone/pvid/af9daf8a-7c57-45a4-a33b-a94585c9ba5f
1011885,2026-07-04 07:04:32,zepto,da5125c1-14c6-4407-b8a3-7e2749ecbc51,"Ashok Leyland Dost LCV Asco Motors Delhi, Plot No 1 GuruNanak Auto Market, Libaspur, Delhi, 110042, India",Delhi,110042,af9daf8a-7c57-45a4-a33b-a94585c9ba5f,6299c551-668f-4b9e-97d8-f938c1b21368,Sweet Tooth,Ice Creams & More,Cones,Giani's,Gianis Butter Scotch Ice Cream Cone,120 ml,1 pc (120 ml),NaN,60.0,57.0,No,Yes,57.0,₹3 OFF,57.0,5,2,https://www.zepto.com/pn/gianis-butter-scotch-ice-cream-cone/pvid/af9daf8a-7c57-45a4-a33b-a94585c9ba5f
15868,2026-07-04 00:16:50,zepto,ffb97d6d-e865-4bf7-a4e4-4b95ebc3b7d9,"CHN Zepto - KK Nagar Network-2, 13B, Near NPS, Mugambigai Nagar, Krishna Nagar, Nerkundram, Chennai, Tamil Nadu 600107, India",Chennai,600107,f1a1dd6f-5df5-4ae1-b8ce-29463ad8c218,420e262d-70e4-4f7e-ac65-3e2b5a1f46ba,Organic & Premium,"Atta, Rice, Oil & Dals",Ghee,Milky Mist,Milky Mist Cow Ghee | Pouch,1 L,1 pack (1 L),NaN,880.0,669.0,No,Yes,669.0,₹211 OFF,669.0,23,3,https://www.zepto.com/pn/milky-mist-cow-ghee-pouch/pvid/f1a1dd6f-5df5-4ae1-b8ce-29463ad8c218
1026417,2026-07-04 07:10:07,zepto,777e8f7a-733e-49cc-8632-619c6723f077,"Abhishek Gas Agencies, No. 923, GF, VR Arcade, 1st Cross Rd, Near Corporation Bank, Remco Bhel Layout, Javarandoddi, RajaRajeshwari Nagar, Bengaluru, Karnataka, 560039, India",Bangalore,560039,f1a1dd6f-5df5-4ae1-b8ce-29463ad8c218,420e262d-70e4-4f7e-ac65-3e2b5a1f46ba,Organic & Premium,"Atta, Rice, Oil & Dals",Ghee,Milky Mist,Milkymist Cow Ghee | Pouch,1 L,1 pack (1 L),NaN,880.0,739.0,No,Yes,739.0,₹141 OFF,739.0,16,5,https://www.zepto.com/pn/milkymist-cow-ghee-pouch/pvid/f1a1dd6f-5df5-4ae1-b8ce-29463ad8c218

In [55]:
store_locations = [
    "Anika Redwood Square, Nagarabhavi Main Rd, 2nd Block, Coconut Garden, Chalukya Nagar, Bhyraveshwara Nagar, Bengaluru, Karnataka, 560072, India",
    "Anju Boutique Cosmetic, 920, Jaina Market, Nathuram Market, DLF Phase 4, Nathuram Market, Chakkarpur, Sector 28, Gurugram, Haryana, 122002, India"
]

monitoring = (
    data[data["store_name_location"].isin(store_locations)]
    [["store_id", "store_name_location", "product_url"]]
    .drop_duplicates()
    .sort_values(["store_name_location", "store_id"])
)

monitoring

                                    store_id  \
281070  4778fa3d-0494-484a-b488-e2b40088ddd7
281071  4778fa3d-0494-484a-b488-e2b40088ddd7
281072  4778fa3d-0494-484a-b488-e2b40088ddd7
281074  4778fa3d-0494-484a-b488-e2b40088ddd7
281075  4778fa3d-0494-484a-b488-e2b40088ddd7
281076  4778fa3d-0494-484a-b488-e2b40088ddd7
281077  4778fa3d-0494-484a-b488-e2b40088ddd7
281078  4778fa3d-0494-484a-b488-e2b40088ddd7
281079  4778fa3d-0494-484a-b488-e2b40088ddd7
281080  4778fa3d-0494-484a-b488-e2b40088ddd7
281081  4778fa3d-0494-484a-b488-e2b40088ddd7
281082  4778fa3d-0494-484a-b488-e2b40088ddd7
281083  4778fa3d-0494-484a-b488-e2b40088ddd7
281084  4778fa3d-0494-484a-b488-e2b40088ddd7
281085  4778fa3d-0494-484a-b488-e2b40088ddd7
281086  4778fa3d-0494-484a-b488-e2b40088ddd7
281087  4778fa3d-0494-484a-b488-e2b40088ddd7
281088  4778fa3d-0494-484a-b488-e2b40088ddd7
281089  4778fa3d-0494-484a-b488-e2b40088ddd7
281090  4778fa3d-0494-484a-b488-e2b40088ddd7
281091  4778fa3d-0494-484a-b488-e2b40088ddd7
281092  4778fa3d-0494-484a-b488-e2b40088ddd7
281093  4778fa3d-0494-484a-b488-e2b40088ddd7
281094  4778fa3d-0494-484a-b488-e2b40088ddd7
281095  4778fa3d-0494-484a-b488-e2b40088ddd7
281096  4778fa3d-0494-484a-b488-e2b40088ddd7
281097  4778fa3d-0494-484a-b488-e2b40088ddd7
281098  4778fa3d-0494-484a-b488-e2b40088ddd7
281099  4778fa3d-0494-484a-b488-e2b40088ddd7
281101  4778fa3d-0494-484a-b488-e2b40088ddd7
281714  4778fa3d-0494-484a-b488-e2b40088ddd7
281715  4778fa3d-0494-484a-b488-e2b40088ddd7
281717  4778fa3d-0494-484a-b488-e2b40088ddd7
281718  4778fa3d-0494-484a-b488-e2b40088ddd7
281719  4778fa3d-0494-484a-b488-e2b40088ddd7
281720  4778fa3d-0494-484a-b488-e2b40088ddd7
281721  4778fa3d-0494-484a-b488-e2b40088ddd7
281722  4778fa3d-0494-484a-b488-e2b40088ddd7
281723  4778fa3d-0494-484a-b488-e2b40088ddd7
281724  4778fa3d-0494-484a-b488-e2b40088ddd7
281725  4778fa3d-0494-484a-b488-e2b40088ddd7
281726  4778fa3d-0494-484a-b488-e2b40088ddd7
281727  4778fa3d-0494-484a-b488-e2b40088ddd7
281728  4778fa3d-0494-484a-b488-e2b40088ddd7
281729  4778fa3d-0494-484a-b488-e2b40088ddd7
281730  4778fa3d-0494-484a-b488-e2b40088ddd7
281731  4778fa3d-0494-484a-b488-e2b40088ddd7
281732  4778fa3d-0494-484a-b488-e2b40088ddd7
281733  4778fa3d-0494-484a-b488-e2b40088ddd7
281734  4778fa3d-0494-484a-b488-e2b40088ddd7
281735  4778fa3d-0494-484a-b488-e2b40088ddd7
281736  4778fa3d-0494-484a-b488-e2b40088ddd7
281737  4778fa3d-0494-484a-b488-e2b40088ddd7
281738  4778fa3d-0494-484a-b488-e2b40088ddd7
281739  4778fa3d-0494-484a-b488-e2b40088ddd7
281740  4778fa3d-0494-484a-b488-e2b40088ddd7
281741  4778fa3d-0494-484a-b488-e2b40088ddd7
281742  4778fa3d-0494-484a-b488-e2b40088ddd7
281743  4778fa3d-0494-484a-b488-e2b40088ddd7
281744  4778fa3d-0494-484a-b488-e2b40088ddd7
281745  4778fa3d-0494-484a-b488-e2b40088ddd7
281759  4778fa3d-0494-484a-b488-e2b40088ddd7
282321  4778fa3d-0494-484a-b488-e2b40088ddd7
282325  4778fa3d-0494-484a-b488-e2b40088ddd7
282326  4778fa3d-0494-484a-b488-e2b40088ddd7
282327  4778fa3d-0494-484a-b488-e2b40088ddd7
282328  4778fa3d-0494-484a-b488-e2b40088ddd7
282329  4778fa3d-0494-484a-b488-e2b40088ddd7
282330  4778fa3d-0494-484a-b488-e2b40088ddd7
282331  4778fa3d-0494-484a-b488-e2b40088ddd7
282332  4778fa3d-0494-484a-b488-e2b40088ddd7
282333  4778fa3d-0494-484a-b488-e2b40088ddd7
282334  4778fa3d-0494-484a-b488-e2b40088ddd7
282335  4778fa3d-0494-484a-b488-e2b40088ddd7
282336  4778fa3d-0494-484a-b488-e2b40088ddd7
282337  4778fa3d-0494-484a-b488-e2b40088ddd7
282338  4778fa3d-0494-484a-b488-e2b40088ddd7
282339  4778fa3d-0494-484a-b488-e2b40088ddd7
282340  4778fa3d-0494-484a-b488-e2b40088ddd7
282341  4778fa3d-0494-484a-b488-e2b40088ddd7
282342  4778fa3d-0494-484a-b488-e2b40088ddd7
282343  4778fa3d-0494-484a-b488-e2b40088ddd7
282344  4778fa3d-0494-484a-b488-e2b40088ddd7
282345  4778fa3d-0494-484a-b488-e2b40088ddd7
282346  4778fa3d-0494-484a-b488-e2b40088ddd7
282347  4778fa3d-0494-484a-b488-e2b40088ddd7
282348  4778fa3d-0494-484a-b488-e2b40088ddd7
282349  4778fa3d-0494-484a-b488-e2b40088ddd7
282350  4778fa3d-0494-484a-b488-e2b40088ddd7
282351  4778fa3d-0494-484a-b488-e2b40088ddd7
282352  4778fa3d-0494-484a-b488-e2b40088ddd7
282353  4778fa3d-0494-484a-b488-e2b40088ddd7
282354  4778fa3d-0494-484a-b488-e2b40088ddd7
282391  4778fa3d-0494-484a-b488-e2b40088ddd7
282493  4778fa3d-0494-484a-b488-e2b40088ddd7
282494  4778fa3d-0494-484a-b488-e2b40088ddd7
282495  4778fa3d-0494-484a-b488-e2b40088ddd7
282496  4778fa3d-0494-484a-b488-e2b40088ddd7
282497  4778fa3d-0494-484a-b488-e2b40088ddd7
282499  4778fa3d-0494-484a-b488-e2b40088ddd7
282500  4778fa3d-0494-484a-b488-e2b40088ddd7
282501  4778fa3d-0494-484a-b488-e2b40088ddd7
282503  4778fa3d-0494-484a-b488-e2b40088ddd7
282504  4778fa3d-0494-484a-b488-e2b40088ddd7
282505  4778fa3d-0494-484a-b488-e2b40088ddd7
282506  4778fa3d-0494-484a-b488-e2b40088ddd7
282507  4778fa3d-0494-484a-b488-e2b40088ddd7
282508  4778fa3d-0494-484a-b488-e2b40088ddd7
282509  4778fa3d-0494-484a-b488-e2b40088ddd7
282510  4778fa3d-0494-484a-b488-e2b40088ddd7
282511  4778fa3d-0494-484a-b488-e2b40088ddd7
282512  4778fa3d-0494-484a-b488-e2b40088ddd7
282513  4778fa3d-0494-484a-b488-e2b40088ddd7
282514  4778fa3d-0494-484a-b488-e2b40088ddd7
282515  4778fa3d-0494-484a-b488-e2b40088ddd7
282516  4778fa3d-0494-484a-b488-e2b40088ddd7
282517  4778fa3d-0494-484a-b488-e2b40088ddd7
282518  4778fa3d-0494-484a-b488-e2b40088ddd7
282519  4778fa3d-0494-484a-b488-e2b40088ddd7
282520  4778fa3d-0494-484a-b488-e2b40088ddd7
282521  4778fa3d-0494-484a-b488-e2b40088ddd7
282522  4778fa3d-0494-484a-b488-e2b40088ddd7
282523  4778fa3d-0494-484a-b488-e2b40088ddd7
282524  4778fa3d-0494-484a-b488-e2b40088ddd7
282525  4778fa3d-0494-484a-b488-e2b40088ddd7
282526  4778fa3d-0494-484a-b488-e2b40088ddd7
282788  4778fa3d-0494-484a-b488-e2b40088ddd7
282789  4778fa3d-0494-484a-b488-e2b40088ddd7
282790  4778fa3d-0494-484a-b488-e2b40088ddd7
282791  4778fa3d-0494-484a-b488-e2b40088ddd7
282792  4778fa3d-0494-484a-b488-e2b40088ddd7
282793  4778fa3d-0494-484a-b488-e2b40088ddd7
282794  4778fa3d-0494-484a-b488-e2b40088ddd7
282795  4778fa3d-0494-484a-b488-e2b40088ddd7
282796  4778fa3d-0494-484a-b488-e2b40088ddd7
282797  4778fa3d-0494-484a-b488-e2b40088ddd7
282798  4778fa3d-0494-484a-b488-e2b40088ddd7
282799  4778fa3d-0494-484a-b488-e2b40088ddd7
282800  4778fa3d-0494-484a-b488-e2b40088ddd7
282801  4778fa3d-0494-484a-b488-e2b40088ddd7
282802  4778fa3d-0494-484a-b488-e2b40088ddd7
282803  4778fa3d-0494-484a-b488-e2b40088ddd7
282804  4778fa3d-0494-484a-b488-e2b40088ddd7
282805  4778fa3d-0494-484a-b488-e2b40088ddd7
282806  4778fa3d-0494-484a-b488-e2b40088ddd7
282807  4778fa3d-0494-484a-b488-e2b40088ddd7
282808  4778fa3d-0494-484a-b488-e2b40088ddd7
282809  4778fa3d-0494-484a-b488-e2b40088ddd7
282810  4778fa3d-0494-484a-b488-e2b40088ddd7
282811  4778fa3d-0494-484a-b488-e2b40088ddd7
282812  4778fa3d-0494-484a-b488-e2b40088ddd7
282813  4778fa3d-0494-484a-b488-e2b40088ddd7
282814  4778fa3d-0494-484a-b488-e2b40088ddd7
282815  4778fa3d-0494-484a-b488-e2b40088ddd7
282816  4778fa3d-0494-484a-b488-e2b40088ddd7
282817  4778fa3d-0494-484a-b488-e2b40088ddd7
282818  4778fa3d-0494-484a-b488-e2b40088ddd7
282826  4778fa3d-0494-484a-b488-e2b40088ddd7
284393  4778fa3d-0494-484a-b488-e2b40088ddd7
284394  4778fa3d-0494-484a-b488-e2b40088ddd7
284395  4778fa3d-0494-484a-b488-e2b40088ddd7
284396  4778fa3d-0494-484a-b488-e2b40088ddd7
284397  4778fa3d-0494-484a-b488-e2b40088ddd7
284398  4778fa3d-0494-484a-b488-e2b40088ddd7
284399  4778fa3d-0494-484a-b488-e2b40088ddd7
284400  4778fa3d-0494-484a-b488-e2b40088ddd7
284401  4778fa3d-0494-484a-b488-e2b40088ddd7
284402  4778fa3d-0494-484a-b488-e2b40088ddd7
284403  4778fa3d-0494-484a-b488-e2b40088ddd7
284404  4778fa3d-0494-484a-b488-e2b40088ddd7
284405  4778fa3d-0494-484a-b488-e2b40088ddd7
284406  4778fa3d-0494-484a-b488-e2b40088ddd7
284407  4778fa3d-0494-484a-b488-e2b40088ddd7
284408  4778fa3d-0494-484a-b488-e2b40088ddd7
284409  4778fa3d-0494-484a-b488-e2b40088ddd7
284410  4778fa3d-0494-484a-b488-e2b40088ddd7
284411  4778fa3d-0494-484a-b488-e2b40088ddd7
284413  4778fa3d-0494-484a-b488-e2b40088ddd7
284414  4778fa3d-0494-484a-b488-e2b40088ddd7
284416  4778fa3d-0494-484a-b488-e2b40088ddd7
284421  4778fa3d-0494-484a-b488-e2b40088ddd7
285060  4778fa3d-0494-484a-b488-e2b40088ddd7
285062  4778fa3d-0494-484a-b488-e2b40088ddd7
285063  4778fa3d-0494-484a-b488-e2b40088ddd7
285064  4778fa3d-0494-484a-b488-e2b40088ddd7
285065  4778fa3d-0494-484a-b488-e2b40088ddd7
286016  4778fa3d-0494-484a-b488-e2b40088ddd7
286017  4778fa3d-0494-484a-b488-e2b40088ddd7
286018  4778fa3d-0494-484a-b488-e2b40088ddd7
286573  4778fa3d-0494-484a-b488-e2b40088ddd7
286574  4778fa3d-0494-484a-b488-e2b40088ddd7
286575  4778fa3d-0494-484a-b488-e2b40088ddd7
286576  4778fa3d-0494-484a-b488-e2b40088ddd7
286577  4778fa3d-0494-484a-b488-e2b40088ddd7
286578  4778fa3d-0494-484a-b488-e2b40088ddd7
286579  4778fa3d-0494-484a-b488-e2b40088ddd7
286580  4778fa3d-0494-484a-b488-e2b40088ddd7
286581  4778fa3d-0494-484a-b488-e2b40088ddd7
286582  4778fa3d-0494-484a-b488-e2b40088ddd7
286583  4778fa3d-0494-484a-b488-e2b40088ddd7
286586  4778fa3d-0494-484a-b488-e2b40088ddd7
286588  4778fa3d-0494-484a-b488-e2b40088ddd7
286928  4778fa3d-0494-484a-b488-e2b40088ddd7
286929  4778fa3d-0494-484a-b488-e2b40088ddd7
286930  4778fa3d-0494-484a-b488-e2b40088ddd7
287337  4778fa3d-0494-484a-b488-e2b40088ddd7
287338  4778fa3d-0494-484a-b488-e2b40088ddd7
287339  4778fa3d-0494-484a-b488-e2b40088ddd7
287340  4778fa3d-0494-484a-b488-e2b40088ddd7
287341  4778fa3d-0494-484a-b488-e2b40088ddd7
287344  4778fa3d-0494-484a-b488-e2b40088ddd7
287993  4778fa3d-0494-484a-b488-e2b40088ddd7
287996  4778fa3d-0494-484a-b488-e2b40088ddd7
287997  4778fa3d-0494-484a-b488-e2b40088ddd7
287999  4778fa3d-0494-484a-b488-e2b40088ddd7
288001  4778fa3d-0494-484a-b488-e2b40088ddd7
288003  4778fa3d-0494-484a-b488-e2b40088ddd7
288007  4778fa3d-0494-484a-b488-e2b40088ddd7
288008  4778fa3d-0494-484a-b488-e2b40088ddd7
288010  4778fa3d-0494-484a-b488-e2b40088ddd7
288011  4778fa3d-0494-484a-b488-e2b40088ddd7
288012  4778fa3d-0494-484a-b488-e2b40088ddd7
288013  4778fa3d-0494-484a-b488-e2b40088ddd7
288014  4778fa3d-0494-484a-b488-e2b40088ddd7
288016  4778fa3d-0494-484a-b488-e2b40088ddd7
288218  4778fa3d-0494-484a-b488-e2b40088ddd7
288222  4778fa3d-0494-484a-b488-e2b40088ddd7
288223  4778fa3d-0494-484a-b488-e2b40088ddd7
289502  4778fa3d-0494-484a-b488-e2b40088ddd7
289505  4778fa3d-0494-484a-b488-e2b40088ddd7
289506  4778fa3d-0494-484a-b488-e2b40088ddd7
289507  4778fa3d-0494-484a-b488-e2b40088ddd7
290531  4778fa3d-0494-484a-b488-e2b40088ddd7
290533  4778fa3d-0494-484a-b488-e2b40088ddd7
290534  4778fa3d-0494-484a-b488-e2b40088ddd7
290535  4778fa3d-0494-484a-b488-e2b40088ddd7
291053  4778fa3d-0494-484a-b488-e2b40088ddd7
291055  4778fa3d-0494-484a-b488-e2b40088ddd7
291056  4778fa3d-0494-484a-b488-e2b40088ddd7
291058  4778fa3d-0494-484a-b488-e2b40088ddd7
291059  4778fa3d-0494-484a-b488-e2b40088ddd7
291061  4778fa3d-0494-484a-b488-e2b40088ddd7
291062  4778fa3d-0494-484a-b488-e2b40088ddd7
291065  4778fa3d-0494-484a-b488-e2b40088ddd7
291066  4778fa3d-0494-484a-b488-e2b40088ddd7
291068  4778fa3d-0494-484a-b488-e2b40088ddd7
291070  4778fa3d-0494-484a-b488-e2b40088ddd7
291071  4778fa3d-0494-484a-b488-e2b40088ddd7
291072  4778fa3d-0494-484a-b488-e2b40088ddd7
291073  4778fa3d-0494-484a-b488-e2b40088ddd7
291074  4778fa3d-0494-484a-b488-e2b40088ddd7
291075  4778fa3d-0494-484a-b488-e2b40088ddd7
291078  4778fa3d-0494-484a-b488-e2b40088ddd7
291538  4778fa3d-0494-484a-b488-e2b40088ddd7
291790  4778fa3d-0494-484a-b488-e2b40088ddd7
291795  4778fa3d-0494-484a-b488-e2b40088ddd7
291796  4778fa3d-0494-484a-b488-e2b40088ddd7
291797  4778fa3d-0494-484a-b488-e2b40088ddd7
291798  4778fa3d-0494-484a-b488-e2b40088ddd7
291799  4778fa3d-0494-484a-b488-e2b40088ddd7
291800  4778fa3d-0494-484a-b488-e2b40088ddd7
292113  4778fa3d-0494-484a-b488-e2b40088ddd7
292114  4778fa3d-0494-484a-b488-e2b40088ddd7
292115  4778fa3d-0494-484a-b488-e2b40088ddd7
292116  4778fa3d-0494-484a-b488-e2b40088ddd7
292117  4778fa3d-0494-484a-b488-e2b40088ddd7
292118  4778fa3d-0494-484a-b488-e2b40088ddd7
292119  4778fa3d-0494-484a-b488-e2b40088ddd7
292120  4778fa3d-0494-484a-b488-e2b40088ddd7
292122  4778fa3d-0494-484a-b488-e2b40088ddd7
292123  4778fa3d-0494-484a-b488-e2b40088ddd7
292124  4778fa3d-0494-484a-b488-e2b40088ddd7
292125  4778fa3d-0494-484a-b488-e2b40088ddd7
292126  4778fa3d-0494-484a-b488-e2b40088ddd7
292127  4778fa3d-0494-484a-b488-e2b40088ddd7
292128  4778fa3d-0494-484a-b488-e2b40088ddd7
292129  4778fa3d-0494-484a-b488-e2b40088ddd7
292131  4778fa3d-0494-484a-b488-e2b40088ddd7
292132  4778fa3d-0494-484a-b488-e2b40088ddd7
292133  4778fa3d-0494-484a-b488-e2b40088ddd7
292142  4778fa3d-0494-484a-b488-e2b40088ddd7
292558  4778fa3d-0494-484a-b488-e2b40088ddd7
292559  4778fa3d-0494-484a-b488-e2b40088ddd7
292560  4778fa3d-0494-484a-b488-e2b40088ddd7
292561  4778fa3d-0494-484a-b488-e2b40088ddd7
292563  4778fa3d-0494-484a-b488-e2b40088ddd7
292564  4778fa3d-0494-484a-b488-e2b40088ddd7
292565  4778fa3d-0494-484a-b488-e2b40088ddd7
292566  4778fa3d-0494-484a-b488-e2b40088ddd7
292567  4778fa3d-0494-484a-b488-e2b40088ddd7
292569  4778fa3d-0494-484a-b488-e2b40088ddd7
292570  4778fa3d-0494-484a-b488-e2b40088ddd7
292572  4778fa3d-0494-484a-b488-e2b40088ddd7
292573  4778fa3d-0494-484a-b488-e2b40088ddd7
292574  4778fa3d-0494-484a-b488-e2b40088ddd7
292575  4778fa3d-0494-484a-b488-e2b40088ddd7
292576  4778fa3d-0494-484a-b488-e2b40088ddd7
292577  4778fa3d-0494-484a-b488-e2b40088ddd7
292579  4778fa3d-0494-484a-b488-e2b40088ddd7
292584  4778fa3d-0494-484a-b488-e2b40088ddd7
292591  4778fa3d-0494-484a-b488-e2b40088ddd7
292938  4778fa3d-0494-484a-b488-e2b40088ddd7
292939  4778fa3d-0494-484a-b488-e2b40088ddd7
292940  4778fa3d-0494-484a-b488-e2b40088ddd7
292941  4778fa3d-0494-484a-b488-e2b40088ddd7
292942  4778fa3d-0494-484a-b488-e2b40088ddd7
292943  4778fa3d-0494-484a-b488-e2b40088ddd7
292944  4778fa3d-0494-484a-b488-e2b40088ddd7
292945  4778fa3d-0494-484a-b488-e2b40088ddd7
292946  4778fa3d-0494-484a-b488-e2b40088ddd7
292947  4778fa3d-0494-484a-b488-e2b40088ddd7
292948  4778fa3d-0494-484a-b488-e2b40088ddd7
292949  4778fa3d-0494-484a-b488-e2b40088ddd7
292950  4778fa3d-0494-484a-b488-e2b40088ddd7
292951  4778fa3d-0494-484a-b488-e2b40088ddd7
292952  4778fa3d-0494-484a-b488-e2b40088ddd7
292953  4778fa3d-0494-484a-b488-e2b40088ddd7
292954  4778fa3d-0494-484a-b488-e2b40088ddd7
292955  4778fa3d-0494-484a-b488-e2b40088ddd7
292956  4778fa3d-0494-484a-b488-e2b40088ddd7
292957  4778fa3d-0494-484a-b488-e2b40088ddd7
292958  4778fa3d-0494-484a-b488-e2b40088ddd7
292959  4778fa3d-0494-484a-b488-e2b40088ddd7
292960  4778fa3d-0494-484a-b488-e2b40088ddd7
292961  4778fa3d-0494-484a-b488-e2b40088ddd7
292962  4778fa3d-0494-484a-b488-e2b40088ddd7
292963  4778fa3d-0494-484a-b488-e2b40088ddd7
292965  4778fa3d-0494-484a-b488-e2b40088ddd7
293507  4778fa3d-0494-484a-b488-e2b40088ddd7
293508  4778fa3d-0494-484a-b488-e2b40088ddd7
293509  4778fa3d-0494-484a-b488-e2b40088ddd7
293512  4778fa3d-0494-484a-b488-e2b40088ddd7
293515  4778fa3d-0494-484a-b488-e2b40088ddd7
293516  4778fa3d-0494-484a-b488-e2b40088ddd7
293517  4778fa3d-0494-484a-b488-e2b40088ddd7
293518  4778fa3d-0494-484a-b488-e2b40088ddd7
293519  4778fa3d-0494-484a-b488-e2b40088ddd7
293907  4778fa3d-0494-484a-b488-e2b40088ddd7
293908  4778fa3d-0494-484a-b488-e2b40088ddd7
293909  4778fa3d-0494-484a-b488-e2b40088ddd7
293910  4778fa3d-0494-484a-b488-e2b40088ddd7
293911  4778fa3d-0494-484a-b488-e2b40088ddd7
293912  4778fa3d-0494-484a-b488-e2b40088ddd7
293914  4778fa3d-0494-484a-b488-e2b40088ddd7
293915  4778fa3d-0494-484a-b488-e2b40088ddd7
293916  4778fa3d-0494-484a-b488-e2b40088ddd7
293917  4778fa3d-0494-484a-b488-e2b40088ddd7
293918  4778fa3d-0494-484a-b488-e2b40088ddd7
293919  4778fa3d-0494-484a-b488-e2b40088ddd7
293920  4778fa3d-0494-484a-b488-e2b40088ddd7
293921  4778fa3d-0494-484a-b488-e2b40088ddd7
293922  4778fa3d-0494-484a-b488-e2b40088ddd7
294264  4778fa3d-0494-484a-b488-e2b40088ddd7
294434  4778fa3d-0494-484a-b488-e2b40088ddd7
294435  4778fa3d-0494-484a-b488-e2b40088ddd7
294436  4778fa3d-0494-484a-b488-e2b40088ddd7
294437  4778fa3d-0494-484a-b488-e2b40088ddd7
294438  4778fa3d-0494-484a-b488-e2b40088ddd7
294439  4778fa3d-0494-484a-b488-e2b40088ddd7
294440  4778fa3d-0494-484a-b488-e2b40088ddd7
294441  4778fa3d-0494-484a-b488-e2b40088ddd7
294442  4778fa3d-0494-484a-b488-e2b40088ddd7
294443  4778fa3d-0494-484a-b488-e2b40088ddd7
294444  4778fa3d-0494-484a-b488-e2b40088ddd7
294707  4778fa3d-0494-484a-b488-e2b40088ddd7
294708  4778fa3d-0494-484a-b488-e2b40088ddd7
294709  4778fa3d-0494-484a-b488-e2b40088ddd7
294710  4778fa3d-0494-484a-b488-e2b40088ddd7
294711  4778fa3d-0494-484a-b488-e2b40088ddd7
295305  4778fa3d-0494-484a-b488-e2b40088ddd7
295306  4778fa3d-0494-484a-b488-e2b40088ddd7
295307  4778fa3d-0494-484a-b488-e2b40088ddd7
295308  4778fa3d-0494-484a-b488-e2b40088ddd7
295310  4778fa3d-0494-484a-b488-e2b40088ddd7
295311  4778fa3d-0494-484a-b488-e2b40088ddd7
295312  4778fa3d-0494-484a-b488-e2b40088ddd7
295313  4778fa3d-0494-484a-b488-e2b40088ddd7
295314  4778fa3d-0494-484a-b488-e2b40088ddd7
295315  4778fa3d-0494-484a-b488-e2b40088ddd7
295316  4778fa3d-0494-484a-b488-e2b40088ddd7
295317  4778fa3d-0494-484a-b488-e2b40088ddd7
295318  4778fa3d-0494-484a-b488-e2b40088ddd7
295319  4778fa3d-0494-484a-b488-e2b40088ddd7
295320  4778fa3d-0494-484a-b488-e2b40088ddd7
295321  4778fa3d-0494-484a-b488-e2b40088ddd7
295322  4778fa3d-0494-484a-b488-e2b40088ddd7
295323  4778fa3d-0494-484a-b488-e2b40088ddd7
295324  4778fa3d-0494-484a-b488-e2b40088ddd7
295325  4778fa3d-0494-484a-b488-e2b40088ddd7
295327  4778fa3d-0494-484a-b488-e2b40088ddd7
295332  4778fa3d-0494-484a-b488-e2b40088ddd7
295769  4778fa3d-0494-484a-b488-e2b40088ddd7
295770  4778fa3d-0494-484a-b488-e2b40088ddd7
295771  4778fa3d-0494-484a-b488-e2b40088ddd7
295772  4778fa3d-0494-484a-b488-e2b40088ddd7
295773  4778fa3d-0494-484a-b488-e2b40088ddd7
295792  4778fa3d-0494-484a-b488-e2b40088ddd7
296625  4778fa3d-0494-484a-b488-e2b40088ddd7
296626  4778fa3d-0494-484a-b488-e2b40088ddd7
296627  4778fa3d-0494-484a-b488-e2b40088ddd7
296628  4778fa3d-0494-484a-b488-e2b40088ddd7
296629  4778fa3d-0494-484a-b488-e2b40088ddd7
296630  4778fa3d-0494-484a-b488-e2b40088ddd7
296631  4778fa3d-0494-484a-b488-e2b40088ddd7
296632  4778fa3d-0494-484a-b488-e2b40088ddd7
296633  4778fa3d-0494-484a-b488-e2b40088ddd7
296634  4778fa3d-0494-484a-b488-e2b40088ddd7
296635  4778fa3d-0494-484a-b488-e2b40088ddd7
296636  4778fa3d-0494-484a-b488-e2b40088ddd7
296637  4778fa3d-0494-484a-b488-e2b40088ddd7
296638  4778fa3d-0494-484a-b488-e2b40088ddd7
296639  4778fa3d-0494-484a-b488-e2b40088ddd7
296640  4778fa3d-0494-484a-b488-e2b40088ddd7
296641  4778fa3d-0494-484a-b488-e2b40088ddd7
296642  4778fa3d-0494-484a-b488-e2b40088ddd7
296643  4778fa3d-0494-484a-b488-e2b40088ddd7
296644  4778fa3d-0494-484a-b488-e2b40088ddd7
296645  4778fa3d-0494-484a-b488-e2b40088ddd7
296646  4778fa3d-0494-484a-b488-e2b40088ddd7
296647  4778fa3d-0494-484a-b488-e2b40088ddd7
296648  4778fa3d-0494-484a-b488-e2b40088ddd7
296649  4778fa3d-0494-484a-b488-e2b40088ddd7
296650  4778fa3d-0494-484a-b488-e2b40088ddd7
296651  4778fa3d-0494-484a-b488-e2b40088ddd7
296652  4778fa3d-0494-484a-b488-e2b40088ddd7
296653  4778fa3d-0494-484a-b488-e2b40088ddd7
296654  4778fa3d-0494-484a-b488-e2b40088ddd7
296658  4778fa3d-0494-484a-b488-e2b40088ddd7
296686  4778fa3d-0494-484a-b488-e2b40088ddd7
296687  4778fa3d-0494-484a-b488-e2b40088ddd7
296688  4778fa3d-0494-484a-b488-e2b40088ddd7
296689  4778fa3d-0494-484a-b488-e2b40088ddd7
296691  4778fa3d-0494-484a-b488-e2b40088ddd7
296692  4778fa3d-0494-484a-b488-e2b40088ddd7
296693  4778fa3d-0494-484a-b488-e2b40088ddd7
296694  4778fa3d-0494-484a-b488-e2b40088ddd7
296696  4778fa3d-0494-484a-b488-e2b40088ddd7
296697  4778fa3d-0494-484a-b488-e2b40088ddd7
296698  4778fa3d-0494-484a-b488-e2b40088ddd7
296699  4778fa3d-0494-484a-b488-e2b40088ddd7
296700  4778fa3d-0494-484a-b488-e2b40088ddd7
296701  4778fa3d-0494-484a-b488-e2b40088ddd7
296702  4778fa3d-0494-484a-b488-e2b40088ddd7

In [56]:
monitoring_table = (
    data.groupby("store_name_location")
    .agg(
        number_of_store_ids=("store_id", "nunique"),
        store_ids=("store_id", lambda x: ", ".join(sorted(x.unique())))
    )
    .reset_index()
)

# Keep only locations with more than one store_id
monitoring_table = monitoring_table[
    monitoring_table["number_of_store_ids"] > 1
]

monitoring_table

,store_name_location,number_of_store_ids,store_ids
0,"1, Dattani Park Rd, Thakur, Dattani Park, Thakur Village, Kandivali East, Mumbai, Maharashtra, 400066, India",2,"238a227d-697c-4fa9-a4f5-4fd064760098, 3b18ee5e-9d22-44cd-acff-646042e546bf"
3,"114, Regent Rd, Tilak Nagar, Regent Park, Kolkata, West Bengal, 700040, India",2,"5d94bdb2-32fe-42f1-bc68-732d1d7ccb11, cd098e80-d516-4508-b4fc-3d7f10461033"
4,"12, Mhalunge - Nande Rd, Mahalunge, Pune, Maharashtra, 411045, India",2,"60252717-a8c5-4891-9b23-3db778b14477, 8c4a9155-85ec-409f-a9d8-84b193ec06ad"
5,"126, MM Road, Pulikeshi Nagar, Bengaluru, Karnataka, 560005, India",2,"3fdf2ec3-0ac0-4e8d-a7f0-e184ef12fbe6, d4205b92-165a-4ad5-89c1-f857521a047f"
6,"164-132, Hill Rd, Bandra West, Mumbai, Maharashtra, 400050, India",2,"8a278c72-1366-4926-b81e-ecc6e64df2a7, 973a6df0-7634-4291-be0d-cd48a816516b"
8,"2, Mumbai Cantral Rd, Dadal Estate, Bane Compound, Tardeo, Mumbai, Maharashtra, 400034, India",2,"2175898f-b70e-46d9-8def-aba7f0745662, 88c4cd44-4d68-40af-af18-9fd8c8db3f39"
9,"2/51, Bhosari Sambhaji Nagar, Gaikwad Nagar, Dighi, Pimpri Chinchwad, Pimpri-Chinchwad, Maharashtra, 411015, India",2,"7644b7fa-98d0-4bdd-a093-965dac5a807b, 931f1ec1-e287-4412-9b52-df3f8ab9c95c"
14,"45, Kodigehalli Main Rd, Amco Colony, Devinagar, Bengaluru, Karnataka, 560092, India",2,"20b71590-dbe0-4666-b941-017436eae4d4, 266f0f16-dcf8-4ab0-bbfb-2860b57c3c9b"
15,"49, Jhowtala Rd, Park Circus, Ballygunge, Kolkata, West Bengal, 700019, India",2,"5d94bdb2-32fe-42f1-bc68-732d1d7ccb11, 74039f14-48e6-4a32-b70f-7ddda4c42900"
17,"5, Kanakapura Rd, Jayanagar, Bengaluru, Karnataka, 560070, India",2,"1ba2b8e0-aa82-4a78-b38b-477b97eac054, 843e630a-7896-462d-b7cf-712140483ed3"
18,"7 Classes Hiranandani (Heera Panna Shopping Centre, ), Shop No.1049, First Floor, Heera Panna Shopping Centre, Mhada Colony 19, Powai, Mumbai, Maharashtra, 400076, India",2,"1cf40b2e-95cd-4581-9ab9-bca81d4932ab, 751c003c-bbe4-453d-ae3d-404380528149"
19,"8/225, Sector, 8, Malviya Nagar, Jaipur, Rajasthan, 302017, India",2,"4db672ad-efd4-44f3-bd91-300233162d1c, 8ec659c9-2faa-4eba-ba2e-158ae485ebb4"
20,"AISECT Office & Education Centre Hyderabad, Gayathri's Sri Sai Enclave, 3Floor, Musheerabad Main Rd, Musheerabad, Dayara, Hyderabad, Telangana, 500020, India",2,"33a1d02e-1bb7-44cc-8d38-9697bcc23dba, e4cb21ce-7d08-43cf-af28-bf84bac6e094"
22,"AKJ Green Floors, Ansal API, Sushant Aquapolis, B-110, Crossings Republik, Ghaziabad, Uttar Pradesh, 201009, India",2,"4fd851db-0ec5-499e-9c7b-724a03966eb8, d000be21-9dc2-4554-9cb0-b2f5ffe340cc"
23,"AZB & Partners, A-8, Amaltash Marg, Block A, Sector 4, Noida, Uttar Pradesh, 201301, India",2,"207df3d7-87f9-4b65-b6be-8e7114d22512, 3ed41d5c-5bb0-4ea9-b041-4d40c2b1f963"
24,"Aakruthi Sunshine Apartment, Aakruthi Sunshine, Panathur Main Rd, Kaverappa Layout, Kadubeesanahalli, Bengaluru, Karnataka, 560103, India",2,"6cf381cd-d178-4bd1-8018-14218a4c0c0d, 9eebbbc9-3fb9-45c1-ab71-312606cf9852"
25,"Aama Tattoo Inn, Balkum Road, Kolshet Industrial Area, Thane West, Thane, Maharashtra, 400608, India",2,"5223893f-f150-4fb3-9f8b-2e86a7c15af1, f4877d26-05ba-4844-8609-1de598d206a5"
27,"Abakash Apartment Nagerbazar, Nagendra Nath Rd, Nagerbazar, Kamardanga, Kolkata, West Bengal, 700028, India",2,"ab3bee45-6ef0-4dbe-bf5f-253d0817ceb5, e879c6cf-e4bd-4b11-a605-4e9b2ee2365d"
28,"Abhishek Gas Agencies, No. 923, GF, VR Arcade, 1st Cross Rd, Near Corporation Bank, Remco Bhel Layout, Javarandoddi, RajaRajeshwari Nagar, Bengaluru, Karnataka, 560039, India",2,"777e8f7a-733e-49cc-8632-619c6723f077, a559802e-0aed-4cc4-9e51-8f49be9d968e"
31,"Aeromarine Private Limited, 20, Jawahar Industrial Estate, Opposite To Mcdonald, Near J.K. Industries, Jawahar Co-Op Ind, Kamothe, Panvel, Navi Mumbai, Maharashtra, 410209, India",2,"291264cf-55b8-4ae3-93b2-cb23fd795054, de3fdf29-3177-4fb9-99f7-43b940f38175"
32,"Agarwal Furniture - Best Furniture Showroom In Manesar - Best Furniture Showroom In New Gurgaon, Shop No. 1, Near Rampura FlyOver, NH-8, Manesar, Gurugram, Haryana, 122004, India",2,"0cdd4ac3-fbeb-4bfd-8960-ebf2192d29b4, b2daed2f-9d3a-495a-a005-a0b0bc04a445"
33,"Ahilya Marg, Block C, Chander Nagar, Surya Nagar, Ghaziabad, Uttar Pradesh, 201011, India",2,"57a0c2ae-1cf1-4c4a-99eb-eb2e19864075, cd3f5394-9700-484e-97d7-7d68e3a620af"
37,"Anika Redwood Square, Nagarabhavi Main Rd, 2nd Block, Coconut Garden, Chalukya Nagar, Bhyraveshwara Nagar, Bengaluru, Karnataka, 560072, India",3,"4778fa3d-0494-484a-b488-e2b40088ddd7, 5400933d-3c5d-4015-a767-daed27781a0d, 658cf319-0b10-4dbe-809e-ea5c913974cb"
38,"Anil Beauty Cosmetics, Bin Trif Nagar, Raziya Complex, Banu Nagar, Madannapet Colony, Hyderabad, Telangana, 500059, India",2,"55b244f4-1068-4dfc-be57-0aee061bc311, 56d50978-df14-48ba-aec8-79644b36fd6a"
39,"Anju Boutique Cosmetic, 920, Jaina Market, Nathuram Market, DLF Phase 4, Nathuram Market, Chakkarpur, Sector 28, Gurugram, Haryana, 122002, India",3,"1c31b7f9-1213-49ea-8346-4879856906a4, d890c3ec-bdf4-4253-b3b4-60742f691584, de5f724c-2832-47fb-b811-d0cdcc00157d"
40,"Apollo MultiSpeciality Hospitals, Kolkata, 58, Canal Circular Rd, Kadapara, Phool Bagan, Kankurgachi, Kolkata, West Bengal 700054",2,"a414c96e-6808-45f5-bdaf-1182485ac38c, e879c6cf-e4bd-4b11-a605-4e9b2ee2365d"
41,"Apoorvam (B Desai Group), B/h, Vandemataram Icon, Opposite Prathna Elegance, Near By Aaryan City, Gota, Ahmedabad, Gujarat, 382481, India",2,"46b54f69-c5ff-4595-934d-3d98fbf33ec0, e677968e-5901-4ff2-8613-ebd72359a67c"
44,"Aryans Dance Factory, SCO 11, Top Floor, Gillco Complex, Sector 127, Sector 4, Main Bazar, Kharar, Sahibzada Ajit Singh Nagar, Punjab, 140301, India",2,"6355d6a1-48e0-48fb-a1fd-9cba4fb43086, 856f5f52-8b1c-4089-b242-6c5dd371777e"
45,"Ashok Leyland Dost LCV Asco Motors Delhi, Plot No 1 GuruNanak Auto Market, Libaspur, Delhi, 110042, India",2,"2a655482-29d6-48fd-bb6c-6051fb5900ee, da5125c1-14c6-4407-b8a3-7e2749ecbc51"
46,"Asif Tea Stall, 500, Chilla Sarda Bangar, Chilla Sarda Bangar Village, Trilokpuri, New Delhi, Delhi, 110091, India",2,"0c865653-8eac-4a33-900c-d2ed7f3c0477, e0a0c84c-0819-482e-8b95-55d4b32592d8"
47,"Attiguppe Metro Station, Chord Road, PF Layout, Hampi Nagar, Bengaluru, Bangalore North, Bengaluru Urban, Karnataka, 560040, India",2,"5400933d-3c5d-4015-a767-daed27781a0d, 658cf319-0b10-4dbe-809e-ea5c913974cb"
48,"Aurinko Academy - IGCSE Cambridge Alternative Progressive School, 91, Opposite To Hosa Road, Parappana Agrahara, Bengaluru, Karnataka, 560035, India",2,"6ceb23b1-672d-4fd7-a89c-66163925a764, a7c548c8-f8e5-41c6-9462-1b4d7e8de41e"
49,"BLS ACLS Pals ITLS Courses At Nashik | Charles Institute, Near Guruji Rugnalaya, Rameshwar Nagar, Balawant Nagar, Savarkar Nagar, Nashik, Maharashtra, 422013, India",2,"1794eede-9e42-4a9c-b132-0be5b0e4e4a4, 703ffbf1-6ea7-4223-815c-82f39176f6e8"
50,"BM Lal Brothers, 34, Opposite Sathyam Theatre Car Parking, Whites Road, Royapettah, Express Estate, Royapettah, Chennai, Tamil Nadu, 600002, India",2,"22cd61da-18f7-490b-9394-24abc3780214, 59099ea0-3411-4169-9c90-206cb03ef12a"
53,"Bagara Biryani Cafe, R. Narayanapura, Whitefield, Gandhipura, Bengaluru, Bangalore East, Bengaluru Urban, Karnataka, 560066, India",2,"0059ff6a-7eb0-477a-a7f5-69256f2c444b, b4dc8d65-ed2e-4142-81b6-373982b13500"
54,"Banswadi, 100 Feet Rd, HRBR Layout 1st Block, HRBR Layout, Kalyan Nagar, Bengaluru, Karnataka, 560043, India",2,"5f97e876-bbea-4c00-8df2-2005db7db8dc, 6b1d82f8-b2ea-4e43-ae70-6f6bca1ec77a"
56,"Big Basket Warehouse Hafeezpet, Janapriya Nagar, Hafeezpet, Hyderabad, Telangana, 500049, India",2,"18073c2e-7d0d-4096-b0e0-c8b5f7454446, d71ff3ac-0dbd-43de-bf48-6a1b0ba17c12"
57,"Bikelele, Barat Ghar Rd, Tugalpur, Greater Noida, Uttar Pradesh, 201310, India",2,"581b1461-3a0b-4698-adb6-93a51207b2e1, 89f3ad21-ce3d-41d6-a3f5-54563135c339"
58,"Blinkit Dark Store Bhoomkar Chouk, Shankar Kalat Nagar, Wakad, Pimpri-Chinchwad, Maharashtra, 411057, India",2,"74dfeece-0ec5-4b41-a83b-576add66078e, f931724a-0140-4c06-b832-027e03fc320a"
59,"Blinkit Kannamangla Main Road, Unit-7, WayCool Foods Bangalore DC, Kannamangala Main Rd, Ardendale, Kannamangala, Karnataka, 560115, India",2,"1ad29aa7-34e9-4268-9238-5a3a3fcd1bd2, 6252e437-b1f6-4ea7-9062-d90fba216c6f"
65,"C.B. Chajed & Company, Old Prabhadevi Rd, Dadar West, Century Bazaar, Prabhadevi, Mumbai, Maharashtra, 400025, India",2,"2175898f-b70e-46d9-8def-aba7f0745662, 72655f9e-d9be-4b01-b2ac-62e61d2efd47"
68,"Car Kia Service Center Raidurg - Gachibowli | Kia Authorized Service Center Hyderabad, Survey No 224, Wipro Circle Rd, Near Lemon Tree Hotel, Financial District, Gachibowli, Hyderabad, Telangana, 500111, India",2,"da5149e0-007e-4134-bc25-497d6ea3c5b2, e531dd78-694e-4025-afdb-76adec0f6d48"
71,"Carmasters, A-184, A Block, Sector 63, Noida, Uttar Pradesh, 201307, India",2,"81d2371c-4e12-4122-9799-f8c21807947d, 9f128d50-def8-471b-bc47-b041d95b885a"
72,"Ceramic Pro Whitefeild - Bangalore (Route 66 Detailing) Best Detailing Studio In The Neighbourhood, 443, Varthur Main Rd, Phase 1, Siddapura, Whitefield, Bengaluru, Karnataka, 560066, India",3,"0cde9637-ca43-45b6-a89c-08c1e32bae57, 1c9e155e-83a8-457a-a687-01eabb1e7a36, 425e2ef0-02bc-4c87-b423-cfbc6e56984a"
73,"Charvi Bridal Jewelery, Vidya Nagar, T. Dasarahalli, Bengaluru, Karnataka, 560057, India",2,"abd85a95-f3f3-42fd-aeb0-71b9127335f5, e749e734-9e20-4090-b5c3-a66ed53b5e23"
74,"Chicken Basket, H.No, 2-56, Khajaguda - Nanakramguda Rd, Near Ghanashyam Super Market, Janmabhoomi Colony, Chaitanya Enclave, Hyderabad, Telangana, 500075, India",2,"8c84e7ae-6e94-48f2-b4c8-af6c199aef1b, de95e00b-0ebf-4f65-8f27-df66fd91dc13"
76,"D Mart, 283/A, Rd Number 36, Behind D-Mart, Kavuri Hills, Madhapur, Telangana, 500033, India",2,"8dcc9bd0-fb05-42e9-96c7-ef15a999c522, ebad4c79-770a-495f-88bf-6d99b2acc4e8"
78,"Dantoon Dental Clinic & Orthodontic Center, 1st Floor, Sai Mahal, Whitefield Main Rd, Pattandur Agrahara, Whitefield, Bengaluru, Karnataka, 560066, India",2,"0059ff6a-7eb0-477a-a7f5-69256f2c444b, 1a2ba310-07de-4a70-946c-b54f2a487646"
79,"Detailing Bull Gurugram, F7, Near Hong Kong Bazar, Block F, Sushant Lok 2, Sector 57, Gurugram, Haryana, 122011, India",2,"bcfaff62-217e-4fab-b8cd-a89d81ccfc4a, f4626c02-1bd4-4396-9a7c-e111d2fc0170"
82,"Devika Towers, Gf66, Block 1, P & T Colony, Raj Nagar, Ghaziabad, Uttar Pradesh, 201002, India",2,"2027ae67-e366-4f60-ab7d-64ffbebfeee0, 5c78735a-a78d-4d43-8cb1-9ba75215f8a7"
84,"Dr Kartik Chadha, 375, Mukherjee Nagar, Near Sadgurudham Mandir, Munshi Ram Colony, Mukherjee Nagar, Delhi, 110009, India",2,"433bb54d-7e04-4f91-ac03-bee784a3102c, c978abd4-1b79-40d2-ab47-ec19b7c29d41"
86,"Dr. Florence Vasantha Prabha, 1B Malaragam, VGP Saraswathy Nagar Road, Madambakkam, Rajakilpakkam, Tamil Nadu, 600073, India",2,"b4d53703-4b49-4a38-85ca-7e321d1d5222, b812518e-9cc3-45e3-8fef-a1dd3311194c"
88,"Dua Old Age Home | Old Age Home | Senior Citizen Care | Assisted Living | Nursing Home | Dementia & Alzheimer & ICU Care, H-58, Sector 116, Noida, Uttar Pradesh, 201304, India",2,"3cd244d7-9f76-467e-b4ab-0d7123ebd606, 3eced897-a793-4b9d-bc3b-1772a883d8af"
96,"F Salon By FTV Andheri, Mohit Tower, 4, K D Gaikwad Road, Bhudargarh Colony, K/w Ward, Zone 3, Mumbai Suburban, Maharashtra, 400053, India",2,"37b900f0-25c0-448b-825a-74d62c8ceb41, 803931bb-511e-48bc-8611-4b9910682bb4"
97,"Fitlane, Opposite Paras Tierea, Sector 137, Noida, Uttar Pradesh, 201305, India",2,"3d914942-fcf7-4222-8029-aff9d8ee3743, 415a53bb-ae7f-4d84-b58f-e36e425769e5"
99,"GRS Convention Hall, Govindaraja Nagar Ward, Krishnananda Nagar, Naagarabhaavi, Bengaluru, Karnataka, 560072, India",2,"658cf319-0b10-4dbe-809e-ea5c913974cb, a16e98dd-a208-4aa2-9627-69eef07e8d69"
104,"Glori By Noshh, 3rd Floor, Mckenzie Tower, C-97, Mayapuri Industrial Area Phase I, Mayapuri, New Delhi, Delhi, 110064, India",2,"42d58798-26cc-429a-aea6-92dbbecae776, 8dde3f32-eae6-42e2-a9cc-ada2f0a9d22f"
105,"Goel Traders, 1539, GuruDwara Rd, South Extension, Kotla Mubarakpur, Kotla, New Delhi, Delhi, 110003, India",3,"32ac84e0-0a29-4c1f-865a-c33780173389, 73b0c599-728d-4642-a0e3-1e5b68836327, 94f50df3-fb2e-4c36-ad6f-8a00bfd1c6af"
106,"Golden Glove Interiors, Plot 216, Near Anand Interiors, Industrial Area, Daulatabad, Gurugram, Haryana, 122006, India",2,"005dcc9a-d50c-442f-ae5e-f89f35d1a01a, e03f540b-f6e2-4749-93fc-5c777cb31628"
107,"Golden Tobacco Limited, Tobacco House, S.V. Road, Vile Parle (West), Navpada, Vile Parle West, Mumbai, Maharashtra, 400049, India",2,"0e8c4509-c9cd-4235-9da5-18fbede8ce72, 769200e9-30cc-47a2-81d4-58904ed953cc"
108,"Goyal Store, 80, Vrindavan Garden, Brindavan Garden Extension, Sahibabad, Ghaziabad, Uttar Pradesh, 201005, India",2,"57a0c2ae-1cf1-4c4a-99eb-eb2e19864075, 8a93c269-b281-4e2d-98b8-cce217827cd0"
109,"Gulshan Fish And Chicken Corner, 39, KC Rd, Block 1, New Industrial Twp 4, New Industrial Township, Faridabad, Haryana, 121001, India",2,"a95989f3-34a1-4288-b318-a01c946b6919, b463b5a9-6661-4ee9-b58b-03b285ac536e"
110,"Gurukul's Sports, 176/1, Varthur Main Rd, Thubarahalli, Whitefield, Bengaluru, Karnataka, 560066, India",2,"0cde9637-ca43-45b6-a89c-08c1e32bae57, 1c9e155e-83a8-457a-a687-01eabb1e7a36"
111,"Gyan Sagar RWA Lane, Gyan Sagar RWA LN, Gyan Khand 1, Indirapuram, Ghaziabad, Uttar Pradesh, 201014, India",2,"5bc98314-fe7f-490b-a41c-cb478ab34dd9, 94a98275-e83a-4a25-ba73-690cbfaa1d55"
112,"HPL Engineering Services, 6, Amrut Angan, Phase I, West, Opp. Reliance Market, Parsik Nagar, Kalwa, Thane, Maharashtra, 400605, India",2,"5223893f-f150-4fb3-9f8b-2e86a7c15af1, b7c3c400-9275-4d75-afa3-62e0a6abfaac"
113,"Herz Kitchen, Taj Residency, Ashok Vihar Colony, Upperpally, Pillar No 195, Near Sai Baba Temple, Ashok Vihar Colony, Fort View Colony, Janachaitanya Colony, Hyderabad, Telangana, 500030, India",2,"83e33858-a13f-4c67-a016-07de0cce8043, e052e083-dbfe-4156-a86e-e2fd848f8c3e"
118,"Hotel Sion Fort, Gala No - 109, Beside VVF Limited, Near Sion Fort, Sion East, Sion, Mumbai, Maharashtra, 400022, India",2,"684a75ae-c944-480c-a64f-76a1a9cfa393, eb92685d-4aad-4424-b38f-f876e41640a8"
119,"Indian Bank, No. 2, 248, Poonamallee - Avadi High Rd, Senneer Kuppam, Poonamallee, Chennai, Tamil Nadu, 600056, India",2,"44e000f6-7a95-4723-ac5d-af4b508056c1, efe487f5-0138-496c-9360-ba76a80cd46f"
122,"Infinity Tower, 15, Narayan Dabholkar Rd, Off Nepean Sea Road, Navshanti Nagar, Malabar Hill, Mumbai, Maharashtra, 400006, India",2,"2175898f-b70e-46d9-8def-aba7f0745662, 81822dd8-20a3-4da0-b460-671c9d1f6d27"
123,"Iqbal Bus Body Builder, Block B, Sector 43, Noida, Uttar Pradesh, 201303, India",2,"3422fce9-9587-44a5-8cff-8ee60c65617d, 554896ba-1bc3-493a-84c2-8a0ce07c2611"
125,"Jai Kishan Gupta, A 20 Gali No 1, Sanjay Nagar, Adarsh Nagar, Delhi, 110033, India",2,"c978abd4-1b79-40d2-ab47-ec19b7c29d41, f36075d2-40c9-4e63-a9d0-4fe36b2ca31f"
126,"Jai Kumar, 374, Sector 17/18 Dividing Rd, Electronic City, Phase IV, Udyog Vihar, Sector 18, Gurugram, Haryana, 122015, India",2,"baa090fc-be13-4b34-87c5-2aea256fd4c4, d38c9d04-5703-4156-8431-c27aebbf3dc1"
128,"Jupiter Computers, 45a/1, Central Rd, Bidhanpally, Jadavpur, Kolkata, West Bengal, 700032, India",2,"5d94bdb2-32fe-42f1-bc68-732d1d7ccb11, a935152c-9baa-46c1-b2ac-37701a227a19"
133,"Kavitha Ladies Tailor, Medchal Mandal, MedchalÃ£Â¢Ã¢ÂÃ¢Âmalkajgiri, Telangana, 500100, India",2,"700d1509-0a10-4ca8-87b9-f8c3e612fb5c, b0a2db37-733d-46d1-808b-7af068fc7f8a"
134,"Keerthi Regency, Kaggadasapura, Bangalore, 560093, India",2,"49879539-9538-42ca-b59e-952cdd73b506, cd653888-0a9a-4251-8d70-7df4c8c2f22a"
137,"Kesava Towers, SY. No. 78, 3, Hafeezpet Rd, Bikshapathi Nagar, Hafeezpet, Serilingampalle (M), Hyderabad, Telangana, 500085, India",2,"18073c2e-7d0d-4096-b0e0-c8b5f7454446, 9ea894e0-db78-45f7-beb1-10b6a52c3fb8"
138,"Kessa, Ground Floor, Door No. 8-2, KR Towers, 699/1/402, Road No. 12, Syed Nagar, Banjara Hills, Hyderabad, Telangana, 500034, India",2,"bb713aac-cd12-4b4d-9026-704e3deaaac3, e052e083-dbfe-4156-a86e-e2fd848f8c3e"
142,"King Mens Wear, Shop No 5 Jijamata Nagar, Kamgar Hospital Rd, Ramachandra Nagar, Waghle Estate, Thane West, Thane, Maharashtra, 400604, India",3,"01185b5e-b794-4cfb-99c9-625397e548ac, 5223893f-f150-4fb3-9f8b-2e86a7c15af1, 7333c09a-d46f-4c45-845d-360e2ed38c8e"
145,"Kp'S Restaurant, 411036, Matruchhaya Building, Poonawalla Road, Sasane Colony, Keshav Nagar, Mundhwa, Pune, Maharashtra",2,"281082b4-7a69-4373-a3c3-385b02d134b1, d5350a6a-f6d4-454f-9c53-205dfefec328"
146,"Kurinji Apartments, Plot No, 51, 2nd Cross St, Sachidananda Puram, Thazhambur, Chennai, Tamil Nadu, 600130, India",2,"7732ead5-8482-4815-9559-7f4cb2a72f3e, 905a8ac5-fea2-4e5c-bf26-13d0bdac9478"
147,"Kurtosshhh - Hungarian Street Food (Kurtosh), Ground Floor W One Building Kuzhikattumoola Junction, Kusumagiri P.O Kakkanad, Kalappurakkal, Kusumagiri, Kochi, Kerala, 682039, India",2,"6d1f09eb-28f1-48b4-86c8-bcfa246c70fa, 8a71c5dd-fc7e-42e0-b56d-7d3b7df30187"
151,"Lila Shah Exports - Vintage Wrap Sari Silk Skirt Garments Manufacturers Factory, P. No. 172, 173, Muhana Mandi Rd, Near Kesar International School, Kesar Nagar, Mansarovar, Jaipur, Rajasthan, 302029, India",2,"8ec659c9-2faa-4eba-ba2e-158ae485ebb4, c56338b2-6871-4193-b594-445cdb7706b3"
153,"MTNL KP Block Office, First Floor, Near Aakash Institute, Pitampura, Adarsh Nagar, Block KP, Poorvi Pitampura, Pitampura, Delhi, 110088, India",2,"2522b064-b9af-4967-9c41-2bfffe8786d3, f2818431-48b5-4b57-9ec5-02e8eef7bc92"
154,"Magnate Icon, New Ranip, Ahmedabad, Gujarat, 382470, India",2,"5c720bb8-ef8e-45c7-a249-be01de180a15, e677968e-5901-4ff2-8613-ebd72359a67c"
157,"Manasa Boutique, HMT, JNTU Police Station Road, Rd Number 9, Opposite Reliance Smart Point, Western Hills, Jal Vayu Vihar, Kukatpally, Hyderabad, Telangana, 500090, India",2,"43b12c97-dc99-431a-9ba3-e3cde9c716bb, fc88e94a-f4b7-4eab-8ce0-fdecf2e29d5f"
158,"Mangalam Motors, B-114, Nigo's Building, Cama Industrial Estate, Goregaon, Mumbai, Maharashtra, 400063, India",2,"803931bb-511e-48bc-8611-4b9910682bb4, c688da38-967b-4e15-862f-458ce8ea6821"
161,"Mithuna White Water Apartments, Mithuna White Waters, Amruthahalli Main Rd, Jakkuru, Bengaluru, Karnataka, 560064, India",2,"0053a04d-aeb4-46b5-99fe-d740491e3843, 07a6d7c0-aea9-434c-846e-9308e495db6a"
163,"Mody Ford, No 52, Indraprastha Colony, Bandlaguda, Nagole, Hyderabad, Telangana, 500068, India",2,"7aad3d3f-1dcc-4bad-baeb-d0640bf7ab86, b9641f44-b385-4cbd-816e-6dceeff911b0"
164,"Mohan Meaking Society, Sector-5, Sector 5, Indirapuram, Ghaziabad, Uttar Pradesh, 201012, India",2,"94a98275-e83a-4a25-ba73-690cbfaa1d55, aa4c6307-c5ae-46c8-8c4d-9750b2bf193f"
168,"NSM RoadWays, 14, A Block, GKRB Rd, Old Madiwala, Jay Bheema Nagar, 1st Stage, BTM Layout, Bengaluru, Karnataka, 560068, India",3,"3bf7d17f-4fa3-481d-b14d-66ca5c4f14da, 5d427762-35fa-45f0-92b2-560b135fcba3, 796c71f3-568e-4d6d-8767-87285ad4f23a"
169,"Nandesh Food Centre, TC Palya, Seegehalli, Bengaluru, Bangalore East, Bengaluru Urban, Karnataka, 560049, India",2,"542cf806-1216-4d13-b888-c3da22c20db0, 9fb087cf-076d-40a0-b974-8d26eaa69f44"
170,"Nano Hospitals, Uttarahalli, No. 47 12/1A Uttarahalli Main Rd Near Bharat Petrol Bunk Simhadri Layout Uttarahalli Hobli Bengaluru Karnataka 560061",2,"2614cabb-fff2-4ef6-aa5b-e94c2b875880, ccc9dc9b-9c6f-421e-bedc-f2e7463a75e9"
171,"National Mart, 8-40/1 Narayanapuram Colony Dammaiguda Municipality, Medchal, Narayana Puri Colony, Sai Priya Colony, Malkajgiri, Hyderabad, Telangana, 500083, India",2,"c96055f6-ed06-46e5-93af-58fa1a374792, e096acfe-3139-4927-b2c8-f36e3587fcf8"
172,"Navi Mumbai Municipal Corporation- B Ward Office, Sector 14 Nerul Rd, Dharshana Society, Sector 14, Nerul, Navi Mumbai, Maharashtra 400706, India",2,"52917883-e475-4632-9fa3-9c99ba0f4b78, badfd8b4-f39a-41ec-8f0a-4f86184f0953"
173,"NeelKanth Lake View, Near NeelKanth Heights, Pokharan Rd Number 2, Devdaya Nagar, Shivai Nagar, Thane West, Thane, Maharashtra, 400606, India",2,"01185b5e-b794-4cfb-99c9-625397e548ac, 5223893f-f150-4fb3-9f8b-2e86a7c15af1"