In [1]:
import pandas as pd
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option("display.max_colwidth", None)

In [2]:
with open(r"/home/user/Downloads/bahrainfinder_2026_07_04.json", "r", encoding="utf-8") as f:
    for i in range(5):
        print(f.readline())

{"reference_number": "1252", "url": "https://bahrainfinder.bh/en/property/villa-for-sale-in-jid-al-haj-11585.html", "broker_display_name": "LAKUM Real Estates", "broker": "LAKUM REAL ESTATES", "category": "sale", "category_url": "https://bahrainfinder.bh/en/for-sale/", "title": "Residential Villa For Sale", "description": "Residential Villa for Sale in Jid Al HajArea: 254.5 sqmBuilt-up size: 230 sqmBathrooms: 2Halls: 1Floors: 2Furnishing: FurnishedCondition: NewParking spaces: 2Price: 129,000 BHDRoads: 1Features & Amenities: Garden, Closed Kitchen, Swimming PoolFor more information, do not hesitate to contact me now | Manaf Tareef – LAKUM Real Estates", "location": "Jid Al Haj", "price": "129,000", "currency": "BHD", "price_per": "", "bedrooms": "", "bathrooms": "2", "furnished": "Furnished", "rera_permit_number": "", "dtcm_licence": "", "scraped_ts": "2026-07-27", "amenities": "Garden, Closed Kitchen, Swimming Pool", "details": "254.5 m²230 m²", "agent_name": "Manaf Tareef", "number_of_photos": "5", "phone_number": "+97333446001", "user_id": "", "date": "2026-07-27", "iteration_number": "2026_07_04", "sub_category_1": "Residential", "sub_category_2": "", "property_type": "Villa", "depth": "", "last_update": "2026-07-26", "published_at": "2026-07-26", "id": "b4ef94c3f0077322a15b1a1f639c94d3"}

{"reference_number": "11037", "url": "https://bahrainfinder.bh/en/property/villa-for-sale-in-hamalah-11037.html", "broker_display_name": "Fajar Alkhalij", "broker": "FAJAR ALKHALIJ", "category": "sale", "category_url": "https://bahrainfinder.bh/en/for-sale/", "title": "Residential Villa For Sale", "description": "Residential Villa for Sale in HamalahClassification: Residential Attached Zones (A)Area: 167.4 sqmBuilt-up size: 210 sqmBedrooms: 4Bathrooms: 4Halls: 2Floors: 2Condition: NewParking spaces: 2Price: 105,000 BHDRoads: 1For more information, do not hesitate to contact me now | Taher Marhoon – Fajar Alkhalij", "location": "Hamalah", "price": "105,000", "currency": "BHD", "price_per": "", "bedrooms": "4", "bathrooms": "4", "furnished": "", "rera_permit_number": "", "dtcm_licence": "", "scraped_ts": "2026-07-27", "amenities": "Open Kitchen, Mejlas, Store, Shared Bathrooms, Laundry, BBQ, Cinema, Home Appliances, Car Parking", "details": "167.4 m²210 m²", "agent_name": "Taher Marhoon", "number_of_photos": "5", "phone_number": "+97338100177", "user_id": "", "date": "2026-07-27", "iteration_number": "2026_07_04", "sub_category_1": "Residential", "sub_category_2": "", "property_type": "Villa", "depth": "", "last_update": "2026-07-26", "published_at": "2026-06-20", "id": "1e36de27c498c1779e98056c2fe62c61"}

{"reference_number": "", "url": "https://bahrainfinder.bh/en/property/villa-for-sale-in-sar-3525.html", "broker_display_name": "Fajar Alkhalij", "broker": "FAJAR ALKHALIJ", "category": "sale", "category_url": "https://bahrainfinder.bh/en/for-sale/", "title": "Residential Villa For Sale", "description": "لبيع فيلا في سار سنترالالمساحة 301.1البناء414,5غرف5حمامات 7صالة2غرفة طعام1غرفة غسيلمصعد حديقةالسعر 222الف", "location": "Sar", "price": "222,000", "currency": "BHD", "price_per": "", "bedrooms": "5", "bathrooms": "7", "furnished": "", "rera_permit_number": "", "dtcm_licence": "", "scraped_ts": "2026-07-27", "amenities": "Mejlas, Store, Maid Room, Meetings Room, Security System, Laundry, Home Appliances", "details": "301.1 m²414.5 m²", "agent_name": "Taher Marhoon", "number_of_photos": "5", "phone_number": "+97338100177", "user_id": "", "date": "2026-07-27", "iteration_number": "2026_07_04", "sub_category_1": "Residential", "sub_category_2": "", "property_type": "Villa", "depth": "", "last_update": "2026-07-26", "published_at": "2025-02-03", "id": "adf96a07f8933da62147bddb0506ea88"}

{"reference_number": "", "url": "https://bahrainfinder.bh/en/property/villa-for-sale-in-lawzi-3825.html", "broker_display_name": "Fajar Alkhalij", "broker": "FAJAR ALKHALIJ", "category": "sale", "category_url": "https://bahrainfinder.bh/en/for-sale/", "title": "Residential Villa For Sale", "description": "لبيع فلل فاخرة - اللوزي(موقع راقي)بناء درجة أولى وبتصميم عصري ..!مساحة الارض 275مساحة البناء 2713 غرف نوم ماستر كبيرة مع غرف التبديلثلاث صالات مفتوحهمطبخ داخليمطبخ خارجيمجلس للضيوف مع الخدماتكراج سيارتينملحق غسيل .غرفة خادمةحديقة اماميةحديقة خلفيهالسعر ١٤٥ الف", "location": "Lawzi", "price": "145,000", "currency": "BHD", "price_per": "", "bedrooms": "5", "bathrooms": "4", "furnished": "Furnished", "rera_permit_number": "", "dtcm_licence": "", "scraped_ts": "2026-07-27", "amenities": "Mejlas, Meetings Room, Garden, Swimming Pool, Shared Bathrooms, Security System, Laundry, Car Parking, Guard Room", "details": "275 m²290 m²", "agent_name": "Taher Marhoon", "number_of_photos": "5", "phone_number": "+97338100177", "user_id": "", "date": "2026-07-27", "iteration_number": "2026_07_04", "sub_category_1": "Residential", "sub_category_2": "", "property_type": "Villa", "depth": "", "last_update": "2026-07-26", "published_at": "2025-03-02", "id": "05a4a30472e2575e022bea782c6ee395"}

{"reference_number": "", "url": "https://bahrainfinder.bh/en/property/villa-for-sale-in-sar-3148.html", "broker_display_name": "Fajar Alkhalij", "broker": "FAJAR ALKHALIJ", "category": "sale", "category_url": "https://bahrainfinder.bh/en/for-sale/", "title": "Residential Villa For Sale", "description": "لبيع فيلا في سارالمساحة314البناء400غرف 5حمامات5كراج سيارتينالسعر 230الف", "location": "Sar", "price": "230,000", "currency": "BHD", "price_per": "", "bedrooms": "5", "bathrooms": "5", "furnished": "Unfurnished", "rera_permit_number": "", "dtcm_licence": "", "scraped_ts": "2026-07-27", "amenities": "Mejlas, Store, Maid Room, Garden, Swimming Pool, Shared Bathrooms, Laundry, Car Parking, Closed Kitchen", "details": "314 m²400 m²", "agent_name": "Taher Marhoon", "number_of_photos": "5", "phone_number": "+97338100177", "user_id": "", "date": "2026-07-27", "iteration_number": "2026_07_04", "sub_category_1": "Residential", "sub_category_2": "", "property_type": "Villa", "depth": "", "last_update": "2026-07-26", "published_at": "2024-12-23", "id": "d78bdec272423f6be70ed488b2d30dc9"}

In [4]:
import pandas as pd
import json

# ============================================================
# 1. FILE CONFIGURATION
# ============================================================

file_path = "/home/user/Downloads/bayut_uae_2026_10_15.json"
chunk_size = 10_000

# ============================================================
# 2. EXPECTED FIELDS
# ============================================================

expected_fields = [
    "reference_number", "id", "url", "broker_display_name", "broker",
    "category", "category_url", "title", "description", "location",
    "price", "currency", "price_per", "bedrooms", "bathrooms",
    "furnished", "rera_permit_number", "dtcm_licence", "scraped_ts",
    "amenities", "details", "agent_name", "number_of_photos",
    "user_id", "phone_number", "date", "iteration_number",
    "rera_registration_number", "ded_license_number", "rera_length",
    "latitude", "longitude", "listing_id", "package_type", "locality",
    "object_id", "completion_status", "ad_type", "verified",
    "sub_category_1", "sub_category_2", "property_type", "depth",
    "published_at", "listing_availability", "brn_registration_number",
    "orn_number", "bln_number", "adm_number", "3d_live", "3d_image",
    "2d_image", "ded_number_2", "ded_number_3", "ded_number_4",
    "trucheck_on", "email", "trubroker", "rating", "no_of_reviews",
    "property_of_the_week", "quality_lister", "trakheesi_url",
    "floorplan_type_identifier", "floorplans_total", "floorplan_id",
    "floorplan_raw"
]

expected_set = set(expected_fields)

# ============================================================
# 3. INITIALIZE TRACKING VARIABLES
# ============================================================

actual_fields = set()
total_records = 0

# Count records where each expected field is absent
missing_count = {field: 0 for field in expected_fields}

# Store sample record numbers for missing fields
missing_samples = {field: [] for field in expected_fields}
max_samples = 5

# ============================================================
# 4. PROCESS JSON FILE IN CHUNKS
# ============================================================

for chunk_no, chunk in enumerate(
    pd.read_json(file_path, lines=True, chunksize=chunk_size),
    start=1
):
    print(f"Processing chunk {chunk_no}: {chunk.shape}")

    total_records += len(chunk)

    # Track every field found in the file
    actual_fields.update(chunk.columns)

    # Check which expected fields are absent from each record
    for field in expected_fields:

        if field not in chunk.columns:
            # The field is absent from every record in this chunk
            missing_count[field] += len(chunk)

            for idx in range(min(max_samples, len(chunk))):
                if len(missing_samples[field]) < max_samples:
                    missing_samples[field].append(
                        total_records - len(chunk) + idx + 1
                    )

        else:
            # A column exists, but individual JSON records may omit it.
            # pandas represents those absent values as NaN.
            absent_mask = chunk[field].isna()
            absent_rows = absent_mask[absent_mask].index

            missing_count[field] += len(absent_rows)

            for idx in absent_rows:
                if len(missing_samples[field]) < max_samples:
                    missing_samples[field].append(
                        total_records - len(chunk)
                        + chunk.index.get_loc(idx) + 1
                    )

    print(f"Total records processed: {total_records:,}")

# ============================================================
# 5. COMPARE EXPECTED AND ACTUAL FIELDS
# ============================================================

missing_fields = sorted(expected_set - actual_fields)
extra_fields = sorted(actual_fields - expected_set)

# ============================================================
# 6. PRINT FIELD VALIDATION REPORT
# ============================================================

print("\n" + "=" * 60)
print("             JSON FIELD VALIDATION REPORT")
print("=" * 60)

print(f"File: {file_path}")
print(f"Total records: {total_records:,}")
print(f"Expected fields: {len(expected_fields)}")
print(f"Actual distinct fields: {len(actual_fields)}")

print("\n--- MISSING FIELDS (Absent from the entire file) ---")
print(f"Count: {len(missing_fields)}")

if missing_fields:
    for field in missing_fields:
        print(f"❌ {field}")
else:
    print("No missing fields.")

print("\n--- EXTRA FIELDS ---")
print(f"Count: {len(extra_fields)}")

if extra_fields:
    for field in extra_fields:
        print(f"⚠️ {field}")
else:
    print("No extra fields.")

print("\n--- RECORD-LEVEL FIELD ABSENCE ---")
print("Field | Records Missing Field | Sample Record Numbers")

for field in expected_fields:
    if missing_count[field] > 0:
        print(
            f"{field} | {missing_count[field]:,} | "
            f"{missing_samples[field]}"
        )

print("\n--- FINAL STATUS ---")

if not missing_fields and not extra_fields:
    print("PASS: Expected and actual field names match.")
else:
    print("FAIL: Missing or extra field names detected.")

if any(count > 0 for count in missing_count.values()):
    print("WARNING: Some records have absent or null field values.")
else:
    print("All expected fields have non-null values in every record.")

Processing chunk 1: (10000, 67)
Total records processed: 10,000
Processing chunk 2: (10000, 67)
Total records processed: 20,000
Processing chunk 3: (10000, 67)
Total records processed: 30,000
Processing chunk 4: (10000, 67)
Total records processed: 40,000
Processing chunk 5: (10000, 67)
Total records processed: 50,000
Processing chunk 6: (10000, 67)
Total records processed: 60,000
Processing chunk 7: (10000, 67)
Total records processed: 70,000
Processing chunk 8: (10000, 67)
Total records processed: 80,000
Processing chunk 9: (10000, 67)
Total records processed: 90,000
Processing chunk 10: (10000, 67)
Total records processed: 100,000
Processing chunk 11: (10000, 67)
Total records processed: 110,000
Processing chunk 12: (10000, 67)
Total records processed: 120,000
Processing chunk 13: (10000, 67)
Total records processed: 130,000
Processing chunk 14: (10000, 67)
Total records processed: 140,000
Processing chunk 15: (10000, 67)
Total records processed: 150,000
Processing chunk 16: (10000, 67)
Total records processed: 160,000
Processing chunk 17: (10000, 67)
Total records processed: 170,000
Processing chunk 18: (10000, 67)
Total records processed: 180,000
Processing chunk 19: (10000, 67)
Total records processed: 190,000
Processing chunk 20: (10000, 67)
Total records processed: 200,000
Processing chunk 21: (10000, 67)
Total records processed: 210,000
Processing chunk 22: (10000, 67)
Total records processed: 220,000
Processing chunk 23: (10000, 67)
Total records processed: 230,000
Processing chunk 24: (10000, 67)
Total records processed: 240,000
Processing chunk 25: (10000, 67)
Total records processed: 250,000
Processing chunk 26: (10000, 67)
Total records processed: 260,000
Processing chunk 27: (10000, 67)
Total records processed: 270,000
Processing chunk 28: (10000, 67)
Total records processed: 280,000
Processing chunk 29: (10000, 67)
Total records processed: 290,000
Processing chunk 30: (10000, 67)
Total records processed: 300,000
Processing chunk 31: (10000, 67)
Total records processed: 310,000
Processing chunk 32: (10000, 67)
Total records processed: 320,000
Processing chunk 33: (10000, 67)
Total records processed: 330,000
Processing chunk 34: (10000, 67)
Total records processed: 340,000
Processing chunk 35: (10000, 67)
Total records processed: 350,000
Processing chunk 36: (10000, 67)
Total records processed: 360,000
Processing chunk 37: (10000, 67)
Total records processed: 370,000
Processing chunk 38: (10000, 67)
Total records processed: 380,000
Processing chunk 39: (10000, 67)
Total records processed: 390,000
Processing chunk 40: (10000, 67)
Total records processed: 400,000
Processing chunk 41: (10000, 67)
Total records processed: 410,000
Processing chunk 42: (10000, 67)
Total records processed: 420,000
Processing chunk 43: (10000, 67)
Total records processed: 430,000
Processing chunk 44: (10000, 67)
Total records processed: 440,000
Processing chunk 45: (10000, 67)
Total records processed: 450,000
Processing chunk 46: (10000, 67)
Total records processed: 460,000
Processing chunk 47: (10000, 67)
Total records processed: 470,000
Processing chunk 48: (10000, 67)
Total records processed: 480,000
Processing chunk 49: (10000, 67)
Total records processed: 490,000
Processing chunk 50: (10000, 67)
Total records processed: 500,000
Processing chunk 51: (10000, 67)
Total records processed: 510,000
Processing chunk 52: (10000, 67)
Total records processed: 520,000
Processing chunk 53: (10000, 67)
Total records processed: 530,000
Processing chunk 54: (10000, 67)
Total records processed: 540,000
Processing chunk 55: (10000, 67)
Total records processed: 550,000
Processing chunk 56: (10000, 67)
Total records processed: 560,000
Processing chunk 57: (10000, 67)
Total records processed: 570,000
Processing chunk 58: (10000, 67)
Total records processed: 580,000
Processing chunk 59: (10000, 67)
Total records processed: 590,000
Processing chunk 60: (8469, 67)
Total records processed: 598,469

============================================================
             JSON FIELD VALIDATION REPORT
============================================================
File: /home/user/Downloads/bayut_uae_2026_10_15.json
Total records: 598,469
Expected fields: 67
Actual distinct fields: 67

--- MISSING FIELDS (Absent from the entire file) ---
Count: 0
No missing fields.

--- EXTRA FIELDS ---
Count: 0
No extra fields.

--- RECORD-LEVEL FIELD ABSENCE ---
Field | Records Missing Field | Sample Record Numbers

--- FINAL STATUS ---
PASS: Expected and actual field names match.
All expected fields have non-null values in every record.

In [6]:
import pandas as pd
import os

# ============================================================
# 1. FILE CONFIGURATION
# ============================================================

file_path = "/home/user/Downloads/bayut_uae_2026_10_15.json"
chunk_size = 10_000
output_dir = "/home/user/Downloads/bayut_qa_report"

os.makedirs(output_dir, exist_ok=True)

# Fields for value counts
value_count_fields = [
    "scraped_ts",
    "date",
    "iteration_number",
    "price_per",
    "furnished",
    "category",
    "sub_category_1",
    "completion_status",
    "package_type",
    "currency"
]

# ============================================================
# 2. INITIALIZE TRACKING
# ============================================================

total_records = 0
field_counts = {field: {} for field in value_count_fields}

# Exact duplicate detection across all columns:
# Store each unique full-record hash and its occurrence count.
record_hash_counts = {}

# ============================================================
# 3. PROCESS FILE IN CHUNKS
# ============================================================

for chunk_no, chunk in enumerate(
    pd.read_json(file_path, lines=True, chunksize=chunk_size),
    start=1
):
    print(f"Processing chunk {chunk_no}: {chunk.shape}")

    total_records += len(chunk)

    # --------------------------------------------------------
    # A. VALUE COUNTS
    # --------------------------------------------------------

    for field in value_count_fields:
        if field not in chunk.columns:
            continue

        counts = chunk[field].value_counts(dropna=False)

        for value, count in counts.items():
            # Convert values into dictionary-safe keys
            key = repr(value)
            field_counts[field][key] = (
                field_counts[field].get(key, 0) + int(count)
            )

    # --------------------------------------------------------
    # B. FULL-RECORD DUPLICATE CHECK
    # --------------------------------------------------------

    # Hash complete rows, including all columns in this chunk.
    # JSON serialization handles list/dict values consistently.
    normalized = chunk.copy()

    for col in normalized.columns:
        normalized[col] = normalized[col].map(
            lambda x: str(x) if isinstance(x, (dict, list)) else x
        )

    row_hashes = pd.util.hash_pandas_object(
        normalized, index=False
    )

    for h, count in row_hashes.value_counts().items():
        key = int(h)
        record_hash_counts[key] = (
            record_hash_counts.get(key, 0) + int(count)
        )

# ============================================================
# 4. DUPLICATE SUMMARY
# ============================================================

duplicate_groups = sum(
    1 for count in record_hash_counts.values() if count > 1
)

duplicate_records = sum(
    count - 1
    for count in record_hash_counts.values()
    if count > 1
)

print("\n" + "=" * 60)
print("ENTIRE DATASET UNIQUENESS")
print("=" * 60)
print(f"Total records: {total_records:,}")
print(f"Unique record-hash groups: {len(record_hash_counts):,}")
print(f"Duplicate groups: {duplicate_groups:,}")
print(f"Duplicate records beyond first occurrence: {duplicate_records:,}")

if duplicate_records == 0:
    print("Result: No duplicate records detected.")
else:
    print("Result: Duplicate records detected.")

# ============================================================
# 5. SAVE VALUE COUNTS
# ============================================================

for field, counts in field_counts.items():
    report = pd.DataFrame(
        [
            {"value": value, "count": count}
            for value, count in counts.items()
        ]
    )

    if not report.empty:
        report = report.sort_values("count", ascending=False)

    output_path = os.path.join(
        output_dir, f"{field}_value_counts.csv"
    )
    report.to_csv(output_path, index=False)

    print(f"Saved: {output_path}")

print("\nAll checks completed.")

Processing chunk 1: (10000, 67)
Processing chunk 2: (10000, 67)
Processing chunk 3: (10000, 67)
Processing chunk 4: (10000, 67)
Processing chunk 5: (10000, 67)
Processing chunk 6: (10000, 67)
Processing chunk 7: (10000, 67)
Processing chunk 8: (10000, 67)
Processing chunk 9: (10000, 67)
Processing chunk 10: (10000, 67)
Processing chunk 11: (10000, 67)
Processing chunk 12: (10000, 67)
Processing chunk 13: (10000, 67)
Processing chunk 14: (10000, 67)
Processing chunk 15: (10000, 67)
Processing chunk 16: (10000, 67)
Processing chunk 17: (10000, 67)
Processing chunk 18: (10000, 67)
Processing chunk 19: (10000, 67)
Processing chunk 20: (10000, 67)
Processing chunk 21: (10000, 67)
Processing chunk 22: (10000, 67)
Processing chunk 23: (10000, 67)
Processing chunk 24: (10000, 67)
Processing chunk 25: (10000, 67)
Processing chunk 26: (10000, 67)
Processing chunk 27: (10000, 67)
Processing chunk 28: (10000, 67)
Processing chunk 29: (10000, 67)
Processing chunk 30: (10000, 67)
Processing chunk 31: (10000, 67)
Processing chunk 32: (10000, 67)
Processing chunk 33: (10000, 67)
Processing chunk 34: (10000, 67)
Processing chunk 35: (10000, 67)
Processing chunk 36: (10000, 67)
Processing chunk 37: (10000, 67)
Processing chunk 38: (10000, 67)
Processing chunk 39: (10000, 67)
Processing chunk 40: (10000, 67)
Processing chunk 41: (10000, 67)
Processing chunk 42: (10000, 67)
Processing chunk 43: (10000, 67)
Processing chunk 44: (10000, 67)
Processing chunk 45: (10000, 67)
Processing chunk 46: (10000, 67)
Processing chunk 47: (10000, 67)
Processing chunk 48: (10000, 67)
Processing chunk 49: (10000, 67)
Processing chunk 50: (10000, 67)
Processing chunk 51: (10000, 67)
Processing chunk 52: (10000, 67)
Processing chunk 53: (10000, 67)
Processing chunk 54: (10000, 67)
Processing chunk 55: (10000, 67)
Processing chunk 56: (10000, 67)
Processing chunk 57: (10000, 67)
Processing chunk 58: (10000, 67)
Processing chunk 59: (10000, 67)
Processing chunk 60: (8469, 67)

============================================================
ENTIRE DATASET UNIQUENESS
============================================================
Total records: 598,469
Unique record-hash groups: 598,469
Duplicate groups: 0
Duplicate records beyond first occurrence: 0
Result: No duplicate records detected.
Saved: /home/user/Downloads/bayut_qa_report/scraped_ts_value_counts.csv
Saved: /home/user/Downloads/bayut_qa_report/date_value_counts.csv
Saved: /home/user/Downloads/bayut_qa_report/iteration_number_value_counts.csv
Saved: /home/user/Downloads/bayut_qa_report/price_per_value_counts.csv
Saved: /home/user/Downloads/bayut_qa_report/furnished_value_counts.csv
Saved: /home/user/Downloads/bayut_qa_report/category_value_counts.csv
Saved: /home/user/Downloads/bayut_qa_report/sub_category_1_value_counts.csv
Saved: /home/user/Downloads/bayut_qa_report/completion_status_value_counts.csv
Saved: /home/user/Downloads/bayut_qa_report/package_type_value_counts.csv
Saved: /home/user/Downloads/bayut_qa_report/currency_value_counts.csv

All checks completed.

In [7]:
import pandas as pd

file_path = "/home/user/Downloads/bayut_uae_2026_10_15.json"
chunk_size = 10_000

total_records = 0
empty_counts = {}
all_fields = set()

for chunk_no, chunk in enumerate(
    pd.read_json(file_path, lines=True, chunksize=chunk_size),
    start=1
):
    total_records += len(chunk)
    all_fields.update(chunk.columns)

    for col in chunk.columns:
        # Count nulls, empty strings, and whitespace-only strings
        empty_mask = (
            chunk[col].isna()
            | chunk[col].map(
                lambda x: isinstance(x, str) and x.strip() == ""
            )
        )

        empty_counts[col] = (
            empty_counts.get(col, 0) + int(empty_mask.sum())
        )

    print(f"Processed chunk {chunk_no}")

print("\n========== COMPLETELY EMPTY FIELDS ==========")
print(f"Total records: {total_records:,}")

completely_empty = [
    field for field in sorted(all_fields)
    if empty_counts.get(field, 0) == total_records
]

if completely_empty:
    for field in completely_empty:
        print(f"❌ {field}")
    print(f"\nTotal completely empty fields: {len(completely_empty)}")
else:
    print("No completely empty fields found.")

Processed chunk 1
Processed chunk 2
Processed chunk 3
Processed chunk 4
Processed chunk 5
Processed chunk 6
Processed chunk 7
Processed chunk 8
Processed chunk 9
Processed chunk 10
Processed chunk 11
Processed chunk 12
Processed chunk 13
Processed chunk 14
Processed chunk 15
Processed chunk 16
Processed chunk 17
Processed chunk 18
Processed chunk 19
Processed chunk 20
Processed chunk 21
Processed chunk 22
Processed chunk 23
Processed chunk 24
Processed chunk 25
Processed chunk 26
Processed chunk 27
Processed chunk 28
Processed chunk 29
Processed chunk 30
Processed chunk 31
Processed chunk 32
Processed chunk 33
Processed chunk 34
Processed chunk 35
Processed chunk 36
Processed chunk 37
Processed chunk 38
Processed chunk 39
Processed chunk 40
Processed chunk 41
Processed chunk 42
Processed chunk 43
Processed chunk 44
Processed chunk 45
Processed chunk 46
Processed chunk 47
Processed chunk 48
Processed chunk 49
Processed chunk 50
Processed chunk 51
Processed chunk 52
Processed chunk 53
Processed chunk 54
Processed chunk 55
Processed chunk 56
Processed chunk 57
Processed chunk 58
Processed chunk 59
Processed chunk 60

========== COMPLETELY EMPTY FIELDS ==========
Total records: 598,469
❌ ad_type
❌ bln_number
❌ ded_license_number
❌ ded_number_2
❌ ded_number_3
❌ ded_number_4
❌ depth
❌ dtcm_licence
❌ email
❌ no_of_reviews
❌ quality_lister
❌ rating
❌ sub_category_2

Total completely empty fields: 13

In [8]:
import pandas as pd

# File configuration
file_path = "/home/user/Downloads/bayut_uae_2026_10_15.json"
chunk_size = 10_000

total_records = 0
same_values = 0
different_values = 0
missing_values = 0
broker_not_capital = 0

different_samples = []
capital_samples = []
max_samples = 10

for chunk_no, chunk in enumerate(
    pd.read_json(file_path, lines=True, chunksize=chunk_size),
    start=1
):
    print(f"Processing chunk {chunk_no}: {chunk.shape}")
    total_records += len(chunk)

    # Check required columns
    required = ["broker", "broker_display_name"]
    if not all(col in chunk.columns for col in required):
        raise ValueError(f"Missing required columns: {required}")

    broker = chunk["broker"]
    display = chunk["broker_display_name"]

    # Check missing values
    missing_mask = broker.isna() | display.isna()
    missing_values += int(missing_mask.sum())

    # Compare values, ignoring leading/trailing spaces
    broker_clean = broker.astype("string").str.strip()
    display_clean = display.astype("string").str.strip()

    same_mask = (
        broker_clean.eq(display_clean).fillna(False)
        & ~missing_mask
    )
    different_mask = ~same_mask & ~missing_mask

    same_values += int(same_mask.sum())
    different_values += int(different_mask.sum())

    # Capture examples where values differ
    if len(different_samples) < max_samples:
        sample = chunk.loc[
            different_mask, ["broker", "broker_display_name"]
        ].head(max_samples - len(different_samples))

        different_samples.extend(sample.to_dict("records"))

    # Check whether broker is uppercase
    # Ignore nulls and non-string values
    string_mask = broker.map(lambda x: isinstance(x, str))
    uppercase_mask = broker.map(
        lambda x: isinstance(x, str) and x == x.upper()
    )

    not_capital_mask = string_mask & ~uppercase_mask
    broker_not_capital += int(not_capital_mask.sum())

    # Capture examples where broker is not uppercase
    if len(capital_samples) < max_samples:
        sample = chunk.loc[
            not_capital_mask, ["broker", "broker_display_name"]
        ].head(max_samples - len(capital_samples))

        capital_samples.extend(sample.to_dict("records"))

# Final report
print("\n" + "=" * 60)
print("BROKER FIELD QA REPORT")
print("=" * 60)

print(f"Total records: {total_records:,}")

print("\n1. broker vs broker_display_name")
print(f"Same values: {same_values:,}")
print(f"Different values: {different_values:,}")
print(f"Records with missing values: {missing_values:,}")

if different_samples:
    print("\nSample mismatched values:")
    print(pd.DataFrame(different_samples).to_string(index=False))

print("\n2. broker uppercase validation")
print(f"Non-uppercase string values: {broker_not_capital:,}")

if capital_samples:
    print("\nSample non-uppercase values:")
    print(pd.DataFrame(capital_samples).to_string(index=False))

print("\nFINAL STATUS")
if different_values == 0 and missing_values == 0 and broker_not_capital == 0:
    print("PASS: Both fields match and broker is uppercase.")
else:
    print("FAIL: Differences, missing values, or non-uppercase values found.")

Processing chunk 1: (10000, 67)
Processing chunk 2: (10000, 67)
Processing chunk 3: (10000, 67)
Processing chunk 4: (10000, 67)
Processing chunk 5: (10000, 67)
Processing chunk 6: (10000, 67)
Processing chunk 7: (10000, 67)
Processing chunk 8: (10000, 67)
Processing chunk 9: (10000, 67)
Processing chunk 10: (10000, 67)
Processing chunk 11: (10000, 67)
Processing chunk 12: (10000, 67)
Processing chunk 13: (10000, 67)
Processing chunk 14: (10000, 67)
Processing chunk 15: (10000, 67)
Processing chunk 16: (10000, 67)
Processing chunk 17: (10000, 67)
Processing chunk 18: (10000, 67)
Processing chunk 19: (10000, 67)
Processing chunk 20: (10000, 67)
Processing chunk 21: (10000, 67)
Processing chunk 22: (10000, 67)
Processing chunk 23: (10000, 67)
Processing chunk 24: (10000, 67)
Processing chunk 25: (10000, 67)
Processing chunk 26: (10000, 67)
Processing chunk 27: (10000, 67)
Processing chunk 28: (10000, 67)
Processing chunk 29: (10000, 67)
Processing chunk 30: (10000, 67)
Processing chunk 31: (10000, 67)
Processing chunk 32: (10000, 67)
Processing chunk 33: (10000, 67)
Processing chunk 34: (10000, 67)
Processing chunk 35: (10000, 67)
Processing chunk 36: (10000, 67)
Processing chunk 37: (10000, 67)
Processing chunk 38: (10000, 67)
Processing chunk 39: (10000, 67)
Processing chunk 40: (10000, 67)
Processing chunk 41: (10000, 67)
Processing chunk 42: (10000, 67)
Processing chunk 43: (10000, 67)
Processing chunk 44: (10000, 67)
Processing chunk 45: (10000, 67)
Processing chunk 46: (10000, 67)
Processing chunk 47: (10000, 67)
Processing chunk 48: (10000, 67)
Processing chunk 49: (10000, 67)
Processing chunk 50: (10000, 67)
Processing chunk 51: (10000, 67)
Processing chunk 52: (10000, 67)
Processing chunk 53: (10000, 67)
Processing chunk 54: (10000, 67)
Processing chunk 55: (10000, 67)
Processing chunk 56: (10000, 67)
Processing chunk 57: (10000, 67)
Processing chunk 58: (10000, 67)
Processing chunk 59: (10000, 67)
Processing chunk 60: (8469, 67)

============================================================
BROKER FIELD QA REPORT
============================================================
Total records: 598,469

1. broker vs broker_display_name
Same values: 2,346
Different values: 596,123
Records with missing values: 0

Sample mismatched values:
                       broker           broker_display_name
             DARNA PROPERTIES              Darna Properties
  PRESTIGE LUXURY REAL ESTATE   Prestige Luxury Real Estate
  PRESTIGE LUXURY REAL ESTATE   Prestige Luxury Real Estate
       BLUE CROWN REAL ESTATE        Blue Crown Real Estate
          MUSAFRI REAL ESTATE           Musafri Real Estate
     KHAN CAPTAIN REAL ESTATE      Khan Captain Real Estate
         THE BOROS COLLECTION          The Boros Collection
        CITY EDGE REAL ESTATE         City Edge Real Estate
          SORENTO REAL ESTATE           Sorento Real Estate
ALLSOPP & ALLSOPP REAL ESTATE Allsopp & Allsopp Real Estate

2. broker uppercase validation
Non-uppercase string values: 0

FINAL STATUS
FAIL: Differences, missing values, or non-uppercase values found.

In [11]:
import pandas as pd

file_path = "/home/user/Downloads/bayut_uae_2026_10_15.json"
chunk_size = 10_000

issue_examples = {}

for chunk_no, chunk in enumerate(
    pd.read_json(file_path, lines=True, chunksize=chunk_size),
    start=1
):
    print(f"Processing chunk {chunk_no}")

    for col in chunk.columns:

        # Keep only the first issue per field
        if col in issue_examples:
            continue

        string_mask = chunk[col].map(lambda x: isinstance(x, str))
        values = chunk.loc[string_mask, col].astype("string")

        if values.empty:
            continue

        checks = [
            ("Leading whitespace", values.str.match(r"^\s+")),
            ("Trailing whitespace", values.str.match(r"\s+$")),
            (
                "Multiple consecutive spaces",
                values.str.contains(r" {2,}", regex=True, na=False)
            ),
            (
                "Tabs or newlines",
                values.str.contains(r"[\t\r\n]", regex=True, na=False)
            )
        ]

        for issue_type, mask in checks:
            if mask.any():
                idx = values.index[mask][0]

                record_no = (
                    (chunk_no - 1) * chunk_size
                    + chunk.index.get_loc(idx) + 1
                )

                issue_examples[col] = {
                    "record_no": record_no,
                    "url": chunk.loc[idx, "url"]
                          if "url" in chunk.columns else None,
                    "issue": issue_type
                }
                break

print("\n========== WHITESPACE QA REPORT ==========")

if issue_examples:
    report = pd.DataFrame([
        {"field": field, **details}
        for field, details in issue_examples.items()
    ])

    print(report.to_string(index=False))
    print(f"\nTotal fields with whitespace issues: {len(report)}")
else:
    print("No whitespace issues found.")

Processing chunk 1
Processing chunk 2
Processing chunk 3
Processing chunk 4
Processing chunk 5
Processing chunk 6
Processing chunk 7
Processing chunk 8
Processing chunk 9
Processing chunk 10
Processing chunk 11
Processing chunk 12
Processing chunk 13
Processing chunk 14
Processing chunk 15
Processing chunk 16
Processing chunk 17
Processing chunk 18
Processing chunk 19
Processing chunk 20
Processing chunk 21
Processing chunk 22
Processing chunk 23
Processing chunk 24
Processing chunk 25
Processing chunk 26
Processing chunk 27
Processing chunk 28
Processing chunk 29
Processing chunk 30
Processing chunk 31
Processing chunk 32
Processing chunk 33
Processing chunk 34
Processing chunk 35
Processing chunk 36
Processing chunk 37
Processing chunk 38
Processing chunk 39
Processing chunk 40
Processing chunk 41
Processing chunk 42
Processing chunk 43
Processing chunk 44
Processing chunk 45
Processing chunk 46
Processing chunk 47
Processing chunk 48
Processing chunk 49
Processing chunk 50
Processing chunk 51
Processing chunk 52
Processing chunk 53
Processing chunk 54
Processing chunk 55
Processing chunk 56
Processing chunk 57
Processing chunk 58
Processing chunk 59
Processing chunk 60

========== WHITESPACE QA REPORT ==========
                    field  record_no                                                  url                       issue
      broker_display_name       1405 https://www.bayut.com/property/details-16850141.html Multiple consecutive spaces
                   broker       1405 https://www.bayut.com/property/details-16850141.html Multiple consecutive spaces
              description         11 https://www.bayut.com/property/details-16833656.html Multiple consecutive spaces
floorplan_type_identifier        431 https://www.bayut.com/property/details-16854160.html Multiple consecutive spaces
               agent_name      60340 https://www.bayut.com/property/details-16698671.html Multiple consecutive spaces
                 location      72667  https://www.bayut.com/property/details-9049781.html Multiple consecutive spaces
                    title     102321  https://www.bayut.com/property/details-9121717.html Multiple consecutive spaces
         reference_number     285357  https://www.bayut.com/property/details-7647106.html Multiple consecutive spaces

Total fields with whitespace issues: 8

In [2]:
import pandas as pd
import json

file_path = "/home/user/Downloads/bayut_uae_2026_10_15.json"
chunk_size = 10_000

for chunk_no, chunk in enumerate(
    pd.read_json(file_path, lines=True, chunksize=chunk_size),
    start=1
):
    print(f"Chunk {chunk_no}: {chunk.shape}")

    # Convert list/dict columns only when needed for QA
    for col in chunk.columns:
        if chunk[col].map(lambda x: isinstance(x, (list, dict))).any():
            chunk[col] = chunk[col].map(
                lambda x: json.dumps(x, sort_keys=True, ensure_ascii=False)
                if isinstance(x, (list, dict))
                else x
            )

    # Perform your QA checks on this chunk here

Chunk 1: (10000, 67)
Chunk 2: (10000, 67)
Chunk 3: (10000, 67)
Chunk 4: (10000, 67)
Chunk 5: (10000, 67)
Chunk 6: (10000, 67)
Chunk 7: (10000, 67)
Chunk 8: (10000, 67)
Chunk 9: (10000, 67)
Chunk 10: (10000, 67)
Chunk 11: (10000, 67)
Chunk 12: (10000, 67)
Chunk 13: (10000, 67)
Chunk 14: (10000, 67)
Chunk 15: (10000, 67)
Chunk 16: (10000, 67)
Chunk 17: (10000, 67)
Chunk 18: (10000, 67)
Chunk 19: (10000, 67)
Chunk 20: (10000, 67)
Chunk 21: (10000, 67)
Chunk 22: (10000, 67)
Chunk 23: (10000, 67)
Chunk 24: (10000, 67)
Chunk 25: (10000, 67)
Chunk 26: (10000, 67)
Chunk 27: (10000, 67)
Chunk 28: (10000, 67)
Chunk 29: (10000, 67)
Chunk 30: (10000, 67)
Chunk 31: (10000, 67)
Chunk 32: (10000, 67)
Chunk 33: (10000, 67)
Chunk 34: (10000, 67)
Chunk 35: (10000, 67)
Chunk 36: (10000, 67)
Chunk 37: (10000, 67)
Chunk 38: (10000, 67)
Chunk 39: (10000, 67)
Chunk 40: (10000, 67)
Chunk 41: (10000, 67)
Chunk 42: (10000, 67)
Chunk 43: (10000, 67)
Chunk 44: (10000, 67)
Chunk 45: (10000, 67)
Chunk 46: (10000, 67)
Chunk 47: (10000, 67)
Chunk 48: (10000, 67)
Chunk 49: (10000, 67)
Chunk 50: (10000, 67)
Chunk 51: (10000, 67)
Chunk 52: (10000, 67)
Chunk 53: (10000, 67)
Chunk 54: (10000, 67)
Chunk 55: (10000, 67)
Chunk 56: (10000, 67)
Chunk 57: (10000, 67)
Chunk 58: (10000, 67)
Chunk 59: (10000, 67)
Chunk 60: (8469, 67)

In [3]:
import pandas as pd
import json
import os
import re
import random
from datetime import datetime

# ============================================================
# 1. CONFIGURATION
# ============================================================

file_path = "/home/user/Downloads/dubizzle_uae_2026_10_02.json"

expected_fields = """
reference_number
id
url
broker_display_name
broker
category
category_url
title
description
location
price
currency
price_per
bedrooms
bathrooms
furnished
rera_permit_number
dtcm_licence
scraped_ts
amenities
details
agent_name
number_of_photos
user_id
phone_number
date
iteration_number
rera_registration_number
ded_license_number
rera_length
latitude
longitude
listing_id
package_type
locality
object_id
completion_status
ad_type
verified
sub_category_1
sub_category_2
property_type
depth
published_at
listing_availability
brn_registration_number
orn_number
bln_number
adm_number
3d_live
3d_image
2d_image
ded_number_2
ded_number_3
ded_number_4
trucheck_on
email
trubroker
rating
no_of_reviews
property_of_the_week
quality_lister
trakheesi_url
floorplan_type_identifier
floorplans_total
floorplan_id
floorplan_raw
""".strip().splitlines()

expected_empty_fields = [
    "dtcm_licence",
    "user_id",
    "listed_by",
    "ded_license_number"
]

allowed_values = {
    "price_per": {
        "", "Bi-Yearly", "Monthly", "Quarterly",
        "Yearly", "Daily", "سنويا"
    },
    "currency": {"AED"},
    "furnished": {"", "Yes"},
    "category": {"rent", "sale"},
    "package_type": {"standard", "featured", "premium"},
    "sub_category_1": {"commercial", "residential"},
    "completion_status": {"", "Ready", "Off-plan"},
    "verified": {"", "Checked", "TruCheckTM"}
}

date_fields = [
    "scraped_ts", "date", "published_at", "last_update"
]

# Update this to the expected run ID for the specific dataset.
expected_run_id = "propertyfinder-weekly:dubizzle_uae:2026junw3:qa"

# The provided iteration_number example is 2026_06_03.
iteration_pattern = re.compile(r"^\d{4}_\d{2}_\d{2}$")

chunk_size = 10_000
random_check_count = 10

output_path = file_path.replace(".json", "_qa_report.txt")

# ============================================================
# 2. HELPERS
# ============================================================

def is_empty(value):
    if value is None:
        return True
    if isinstance(value, str):
        return value.strip() == ""
    return pd.isna(value)


def is_valid_date(value):
    if is_empty(value):
        return True  # Missing values handled separately if required.

    try:
        datetime.strptime(str(value).strip(), "%Y-%m-%d")
        return True
    except ValueError:
        return False


def add_issue(issues, row_no, field, value, message):
    issues.append({
        "row_no": row_no,
        "field": field,
        "value": str(value)[:300],
        "issue": message
    })


# ============================================================
# 3. FILE NAME AND FORMAT CHECKS
# ============================================================

issues = []
summary = []

file_name = os.path.basename(file_path)

summary.append("DUBIZZLE UAE QA REPORT")
summary.append("=" * 60)
summary.append(f"File name: {file_name}")

if not file_name.endswith(".json"):
    summary.append("FAIL: File format should be JSON.")
else:
    summary.append("PASS: File extension is JSON.")

# Accepts names such as dubizzle_uae_2026_10_02.json
file_name_pattern = r"^dubizzle_uae_\d{4}_\d{2}_\d{2}\.json$"

if re.match(file_name_pattern, file_name):
    summary.append("PASS: File name follows the accepted naming pattern.")
else:
    summary.append(
        "FAIL: File name does not follow dubizzle_uae_YYYY_MM_DD.json."
    )

if "_uae_" in file_name:
    summary.append("PASS: Country suffix '_uae_' is present.")
else:
    summary.append("FAIL: Country suffix '_uae_' is missing.")

# ============================================================
# 4. CHUNK-BASED DATA QA
# ============================================================

total_rows = 0
seen_ids = set()
random_records = []
columns_found = None
chunk_count = 0

# Reservoir sampling selects 10 random records across the whole file.
rng = random.Random(42)

try:
    reader = pd.read_json(
        file_path,
        lines=True,
        chunksize=chunk_size
    )

    for chunk_no, chunk in enumerate(reader, start=1):
        chunk_count += 1
        chunk_start = total_rows
        chunk = chunk.reset_index(drop=True)

        if columns_found is None:
            columns_found = list(chunk.columns)

        total_rows += len(chunk)

        print(f"Processing chunk {chunk_no}: {len(chunk):,} rows")

        # ----------------------------------------------------
        # A. RANDOM SAMPLE OF 10 RECORDS
        # ----------------------------------------------------

        for idx, record in chunk.iterrows():
            record_no = chunk_start + idx + 2
            item = {
                "row_no": record_no,
                "record": record.to_dict()
            }

            if len(random_records) < random_check_count:
                random_records.append(item)
            else:
                position = rng.randint(0, record_no - 2)
                if position < random_check_count:
                    random_records[position] = item

        # ----------------------------------------------------
        # B. EMPTY EXPECTED FIELDS
        # ----------------------------------------------------

        for field in expected_empty_fields:
            if field not in chunk.columns:
                continue

            mask = ~chunk[field].map(is_empty)

            for idx in chunk.index[mask]:
                add_issue(
                    issues,
                    chunk_start + idx + 2,
                    field,
                    chunk.at[idx, field],
                    "Expected empty field but value is populated"
                )

        # ----------------------------------------------------
        # C. ALLOWED VALUES
        # ----------------------------------------------------

        for field, allowed in allowed_values.items():
            if field not in chunk.columns:
                continue

            for idx, value in chunk[field].items():
                if is_empty(value):
                    normalized = ""
                else:
                    normalized = str(value).strip()

                if normalized not in allowed:
                    add_issue(
                        issues,
                        chunk_start + idx + 2,
                        field,
                        value,
                        f"Unexpected value; allowed values: {sorted(allowed)}"
                    )

        # ----------------------------------------------------
        # D. BROKER AND BROKER_DISPLAY_NAME COMPARISON
        # ----------------------------------------------------

        if {"broker", "broker_display_name"}.issubset(chunk.columns):
            for idx, row in chunk.iterrows():
                broker = row["broker"]
                display = row["broker_display_name"]

                if not is_empty(broker) and not is_empty(display):
                    if str(broker).strip() != str(display).strip():
                        add_issue(
                            issues,
                            chunk_start + idx + 2,
                            "broker",
                            broker,
                            "broker and broker_display_name do not match"
                        )

                if isinstance(broker, str) and broker != broker.upper():
                    add_issue(
                        issues,
                        chunk_start + idx + 2,
                        "broker",
                        broker,
                        "broker value is not in uppercase"
                    )

        # ----------------------------------------------------
        # E. DATE FORMATS
        # ----------------------------------------------------

        for field in date_fields:
            if field not in chunk.columns:
                continue

            for idx, value in chunk[field].items():
                if not is_valid_date(value):
                    add_issue(
                        issues,
                        chunk_start + idx + 2,
                        field,
                        value,
                        "Invalid date format; expected YYYY-MM-DD"
                    )

        # ----------------------------------------------------
        # F. ITERATION NUMBER
        # ----------------------------------------------------

        if "iteration_number" in chunk.columns:
            for idx, value in chunk["iteration_number"].items():
                if not is_empty(value) and not iteration_pattern.match(
                    str(value).strip()
                ):
                    add_issue(
                        issues,
                        chunk_start + idx + 2,
                        "iteration_number",
                        value,
                        "Invalid format; expected YYYY_MM_week, e.g. 2026_06_03"
                    )

        # ----------------------------------------------------
        # G. DUPLICATE DATASET CHECK
        # ----------------------------------------------------

        if "id" in chunk.columns:
            for idx, value in chunk["id"].items():
                if is_empty(value):
                    continue

                key = str(value).strip()

                if key in seen_ids:
                    add_issue(
                        issues,
                        chunk_start + idx + 2,
                        "id",
                        value,
                        "Duplicate ID"
                    )
                else:
                    seen_ids.add(key)

        # ----------------------------------------------------
        # H. CURRENCY CHECK: AED
        # ----------------------------------------------------

        # Already covered by allowed_values.
        # Add more requirements here if needed.

# ============================================================
# 5. FINAL VALIDATION
# ============================================================

    summary.append("")
    summary.append(f"Total records: {total_rows:,}")
    summary.append(f"Total chunks processed: {chunk_count}")

    if 170_000 <= total_rows <= 190_000:
        summary.append("PASS: Record count is within the standard range.")
    elif total_rows >= 495_900:
        summary.append("INFO: Record count is within the latest dataset scale.")
    else:
        summary.append("CHECK: Record count is outside the specified ranges.")

    # --------------------------------------------------------
    # REQUIRED FIELDS AND FIELD NAME CASE
    # --------------------------------------------------------

    if columns_found is not None:
        missing_fields = sorted(set(expected_fields) - set(columns_found))
        unexpected_fields = sorted(set(columns_found) - set(expected_fields))

        if not missing_fields:
            summary.append("PASS: All expected fields are present.")
        else:
            summary.append(f"FAIL: Missing fields: {missing_fields}")

        if unexpected_fields:
            summary.append(f"CHECK: Unexpected fields: {unexpected_fields}")

        wrong_case = [
            col for col in columns_found
            if col != col.lower()
        ]

        if wrong_case:
            summary.append(f"FAIL: Field names not lowercase: {wrong_case}")
        else:
            summary.append("PASS: All field names are lowercase.")

        duplicate_column_names = (
            pd.Index(columns_found)[pd.Index(columns_found).duplicated()]
            .tolist()
        )

        if duplicate_column_names:
            summary.append(
                f"FAIL: Duplicate column names: {duplicate_column_names}"
            )

    # --------------------------------------------------------
    # UNIQUE DATASET CHECK
    # --------------------------------------------------------

    if "id" in (columns_found or []):
        if total_rows == len(seen_ids):
            summary.append("PASS: Dataset IDs are unique.")
        else:
            summary.append(
                f"FAIL: Duplicate or missing IDs detected. "
                f"Rows: {total_rows:,}; unique IDs: {len(seen_ids):,}"
            )

    # --------------------------------------------------------
    # RANDOM RECORD OUTPUT
    # --------------------------------------------------------

    summary.append("")
    summary.append("RANDOM DATA CHECK (10 RECORDS)")
    summary.append("-" * 60)

    for sample in sorted(random_records, key=lambda x: x["row_no"]):
        summary.append(f"Row {sample['row_no']}:")
        summary.append(
            json.dumps(
                sample["record"],
                ensure_ascii=False,
                default=str
            )
        )

    # --------------------------------------------------------
    # ISSUE REPORT
    # --------------------------------------------------------

    summary.append("")
    summary.append(f"Total QA issues found: {len(issues):,}")
    summary.append("")

    if issues:
        issue_df = pd.DataFrame(issues)
        issue_df.to_csv(
            file_path.replace(".json", "_qa_issues.csv"),
            index=False
        )
        summary.append(
            "Detailed issues saved to: "
            + file_path.replace(".json", "_qa_issues.csv")
        )
    else:
        summary.append("No issues found by the configured checks.")

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(summary))

    print("\n".join(summary[:15]))
    print(f"\nQA summary saved to: {output_path}")

except Exception as e:
    print(f"QA failed: {type(e).__name__}: {e}")

QA failed: FileNotFoundError: File /home/user/Downloads/dubizzle_uae_2026_10_02.json does not exist

In [4]:
#===================================================================================

In [ ]:
import pandas as pd
import json

file_path = "/home/user/Downloads/bahrainfinder_bah_2026_10_03.json"

try:
    df = pd.read_json(file_path, lines=True)
except ValueError:
    try:
        df = pd.read_json(file_path, lines=False)
    except ValueError:
        with open(file_path, "r", encoding="utf-8-sig") as f:
            data = json.load(f)

        df = pd.DataFrame(data)

print(df.shape)
display(df.head())

(157, 36)

,category,bayut_property_type_id,transaction_hash_id,date_transaction_nk,builtup_area_sqm,plot_area_sqm,transaction_amount,bayut_leaf_location_name_en,bayut_leaf_location_name_ar,transaction_category_l1_name,...,bayut_location_l6_name_ar,bayut_leaf_location_id,property_completion_status_sk,transaction_per_sqm_amount,sale_market_name,date_previous_sale_transaction_nk,balcony_area_sqm,contract_monthly_amount,occupancy_status_name,has_kpi_value
0,Commercial,6,651e5d0027837ea3,2026-10-07 00:00:00,101.00,,5305750.00,Breez by Danube,بريز من دانوب,Sales,...,,22488,off-plan,52532.18,Primary First Sale,1970-01-01,32.00,,Unknown,False
1,Commercial,5,a72c6b724c15481,2026-10-09 00:00:00,65.91,,1200000.00,The Citadel,ذا سيتاديل,Sales,...,,5134,ready,18206.65,Secondary Resale,2025-01-14,0.00,,Vacant,True
2,Commercial,6,42f29b4658e83e0c,2026-10-06 00:00:00,162.12,,2294734.00,One Beverly,وان بيفرلي,Sales,...,,20465,off-plan,14154.54,Primary First Sale,1970-01-01,52.63,,Unknown,False
3,Commercial,5,56b865ef2252022d,2026-10-07 00:00:00,494.62,,36392940.00,Lumena by Omniyat,لومينا من أمنيات,Sales,...,,22046,off-plan,73577.57,Primary First Sale,1970-01-01,58.89,,Unknown,False
4,Commercial,5,5789d9629d608568,2026-10-12 00:00:00,101.52,,1049427.08,Jumeirah Bay X2,خور الجميرا X2,Sales,...,,5179,ready,10337.15,Secondary Resale,2026-02-24,0.00,,Vacant,True

In [29]:
df.shape

(157, 36)

In [30]:
df.duplicated().sum()

np.int64(0)

In [31]:
df.columns

Index(['category', 'bayut_property_type_id', 'transaction_hash_id',
       'date_transaction_nk', 'builtup_area_sqm', 'plot_area_sqm',
       'transaction_amount', 'bayut_leaf_location_name_en',
       'bayut_leaf_location_name_ar', 'transaction_category_l1_name', 'beds',
       'latitude', 'longitude', 'bayut_latitude', 'bayut_longitude', 'floor',
       'rent_contract_duration_months', 'rent_contract_renewal_status_name',
       'date_start_nk', 'bayut_location_l3_name_en',
       'bayut_location_l3_name_ar', 'bayut_location_l4_name_en',
       'bayut_location_l4_name_ar', 'bayut_location_l5_name_en',
       'bayut_location_l5_name_ar', 'bayut_location_l6_name_en',
       'bayut_location_l6_name_ar', 'bayut_leaf_location_id',
       'property_completion_status_sk', 'transaction_per_sqm_amount',
       'sale_market_name', 'date_previous_sale_transaction_nk',
       'balcony_area_sqm', 'contract_monthly_amount', 'occupancy_status_name',
       'has_kpi_value'],
      dtype='object')

In [32]:
df.category.value_counts()

category
Commercial    157
Name: count, dtype: int64

In [33]:
df.date_transaction_nk.duplicated().sum()

np.int64(145)

In [34]:
import pandas as pd

df["date_transaction_nk"] = pd.to_datetime(
    df["date_transaction_nk"], errors="coerce"
)

start_date = "2026-10-07"
end_date = "2026-10-14"

issues = df[
    ~df["date_transaction_nk"].between(start_date, end_date)
    & df["date_transaction_nk"].notna()
]

print(
    issues[["date_transaction_nk", "transaction_hash_id"]]
    .sort_values("date_transaction_nk", ascending=False)
    .to_string(index=False)
)

date_transaction_nk transaction_hash_id
         2026-10-06    42f29b4658e83e0c
         2026-10-06    5884435733de9ef0
         2026-10-06    4ca48290f8b3f12e
         2026-10-06    4478d3080bceee99
         2026-10-06    1076228fe2580891
         2026-10-06    4df6b700d9597b52
         2026-10-06    6d5de1092c126a8d
         2026-10-06    6ab781beee77f247
         2026-10-06    59762f6d38745b03
         2026-10-06    731827561918ce20
         2026-10-06    68810f538802cdd5
         2026-10-06    10923cd4daae3eaf
         2026-10-06    70284b7bc327c5f1
         2026-10-06    6b502468fb5a47a2
         2026-10-06    64164d94ca26387f
         2026-10-06    4874c1832a911696
         2026-10-06     ff9254cec2a3c94
         2026-10-06    6ba038d1e6846d95
         2026-10-06    7cbec3be03b1d5fc
         2026-10-06    572840e59bc354c3
         2026-10-06    555e9216d154e8a2
         2026-10-06    5cea74c58c6e3cab
         2026-10-06    4e91ad8a66fd0c4b
         2026-10-06     ec36721525a64fe
         2026-10-06    692b2c6493cb2f09
         2026-10-06    40f70684b2ebedcc
         2026-10-06    63a687529f98bcfe
         2026-10-06    4df8dfaefef042a9
         2026-10-06    1e9009b3fdc49b42
         2026-10-06     86dd6608391bcfe
         2026-10-05    13d912b361d7169a
         2026-08-31     fa9955b95c71874
         2026-05-22    6a7db125a605901a
         2026-02-24    3463d17d970866aa
         2026-02-05     88baf0df5ea2a5e
         2026-01-14    351b2e80ff178458

In [36]:
import pandas as pd

# Count actual null/NaN values
null_count = df.isna().sum()

# Count empty strings and strings containing only whitespace
empty_count = df.apply(
    lambda col: col.map(
        lambda x: isinstance(x, str) and x.strip() == ""
    ).sum()
)

# Combine counts
result = pd.DataFrame({
    "null_count": null_count,
    "empty_string_count": empty_count,
    "total_empty_or_null": null_count + empty_count
})


# Show fields containing empty or null values
result = result[result["total_empty_or_null"] > 0]
result = result.sort_values("total_empty_or_null", ascending=False)

print(result.to_string())

                               null_count  empty_string_count  total_empty_or_null
beds                                    0                 157                  157
rent_contract_duration_months           0                 157                  157
contract_monthly_amount                 0                 157                  157
bayut_location_l6_name_en               0                 152                  152
bayut_location_l6_name_ar               0                 152                  152
plot_area_sqm                           0                 130                  130
bayut_location_l5_name_en               0                  78                   78
bayut_location_l5_name_ar               0                  78                   78
floor                                   0                  27                   27
builtup_area_sqm                        0                  27                   27
bayut_location_l4_name_ar               0                   8                    8
bayut_location_l4_name_en               0                   8                    8
longitude                               0                   5                    5
latitude                                0                   5                    5

In [26]:
# Find duplicate transaction_hash_id values
duplicates = df[df.duplicated(subset=["transaction_hash_id"], keep=False)]

print("Total duplicate records:", len(duplicates))
print("Duplicate transaction_hash_id count:",
      duplicates["transaction_hash_id"].nunique())

display(
    duplicates[["transaction_hash_id", "date_transaction_nk"]]
    .sort_values("transaction_hash_id")
)

Total duplicate records: 0
Duplicate transaction_hash_id count: 0

Empty DataFrame
Columns: [transaction_hash_id, date_transaction_nk]
Index: []

In [5]:
#=========================================================================================================

In [1]:
import pandas as pd
import json

df = pd.read_json(
    r"/home/user/Downloads/bayut_transactions_sold_residential_2026_10_14.json",
    lines=True
)

# Convert list/dict columns into strings
df = df.apply(
    lambda col: col.map(
        lambda x: json.dumps(x, sort_keys=True)
        if isinstance(x, (list, dict))
        else x
    )
)

ValueError: Expected object or value

In [8]:
import pandas as pd

# Count null + empty string values in each column
empty_counts = {}

for col in df.columns:
    # Null values
    null_count = df[col].isna().sum()

    # Empty strings / whitespace-only strings
    empty_string_count = (
        df[col]
        .fillna('')
        .astype(str)
        .str.strip()
        .eq('')
        .sum()
    )

    # Total missing/empty
    total = null_count + empty_string_count

    empty_counts[col] = {
        'null_count': null_count,
        'empty_string_count': empty_string_count,
        'total_null_or_empty': total
    }

result = pd.DataFrame(empty_counts).T

print(result.to_string())

                      null_count  empty_string_count  total_null_or_empty
reference_number               0                3053                 3053
id                             0                   0                    0
url                            0                   0                    0
broker_display_name            0                   3                    3
broker                         0                   3                    3
category                       0                   0                    0
category_url                   0                   0                    0
title                          0                   0                    0
description                    0                   0                    0
location                       0                   0                    0
price                          0                   6                    6
currency                       0                   6                    6
price_per                      0                3053                 3053
bedrooms                       0                1866                 1866
bathrooms                      0                1866                 1866
furnished                      0                   0                    0
rera_permit_number             0                3053                 3053
dtcm_licence                   0                3053                 3053
scraped_ts                     0                   0                    0
amenities                      0                 373                  373
details                        0                   0                    0
agent_name                     0                3053                 3053
number_of_photos               0                  14                   14
user_id                        0                3053                 3053
phone_number                   0                 155                  155
date                           0                   0                    0
iteration_number               0                   0                    0
depth                          0                3050                 3050
sub_category_1                 0                   0                    0
property_type                  0                   0                    0
sub_category_2                 0                3053                 3053
published_at                   0                   0                    0
listing_availability           0                   0                    0

In [9]:
df.furnished.value_counts()

furnished
Yes    2338
No      715
Name: count, dtype: int64

In [10]:
df.shape

(3053, 33)

In [11]:
import json

duplicate_count = (
    df.applymap(
        lambda x: json.dumps(x, sort_keys=True)
        if isinstance(x, (list, dict))
        else x
    )
    .duplicated()
    .sum()
)

print("Duplicate rows:", duplicate_count)

Duplicate rows: 0

/tmp/ipykernel_48619/600954025.py:4: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
empty_cols = df.columns[df.isna().all()].tolist()
empty_cols

[]

In [14]:
df.isnull().sum()

reference_number        0
id                      0
url                     0
broker_display_name     0
broker                  0
category                0
category_url            0
title                   0
description             0
location                0
price                   0
currency                0
price_per               0
bedrooms                0
bathrooms               0
furnished               0
rera_permit_number      0
dtcm_licence            0
scraped_ts              0
amenities               0
details                 0
agent_name              0
number_of_photos        0
user_id                 0
phone_number            0
date                    0
iteration_number        0
depth                   0
sub_category_1          0
property_type           0
sub_category_2          0
published_at            0
listing_availability    0
dtype: int64

In [15]:
df.columns

Index(['reference_number', 'id', 'url', 'broker_display_name', 'broker',
       'category', 'category_url', 'title', 'description', 'location', 'price',
       'currency', 'price_per', 'bedrooms', 'bathrooms', 'furnished',
       'rera_permit_number', 'dtcm_licence', 'scraped_ts', 'amenities',
       'details', 'agent_name', 'number_of_photos', 'user_id', 'phone_number',
       'date', 'iteration_number', 'depth', 'sub_category_1', 'property_type',
       'sub_category_2', 'published_at', 'listing_availability'],
      dtype='object')

In [16]:
req_cols = """reference_number,
id,
url,
broker_display_name,
broker,
category,
category_url,
title,
property_type,
sub_category_1,
sub_category_2,
depth,
description,
location,
price,
currency,
price_per,
bedrooms,
bathrooms,
furnished,
rera_permit_number,
dtcm_licence,
scraped_ts,
amenities,
details,
agent_name,
number_of_photos,
user_id,
phone_number,
date,
iteration_number,
published_at,
listing_availability"""
req_cols = [c.strip() for c in req_cols.split(",") if c.strip()]

missing = [c for c in req_cols if c not in df.columns]
extra = [c for c in df.columns if c not in req_cols]

print("Requirement columns:", len(req_cols))
print("File columns:", len(df.columns))
print("Missing:", missing)
print("Extra:", extra)
print("Order matches:", req_cols == list(df.columns))

Requirement columns: 33
File columns: 33
Missing: []
Extra: []
Order matches: False

In [17]:
print(df.columns.tolist())

['reference_number', 'id', 'url', 'broker_display_name', 'broker', 'category', 'category_url', 'title', 'description', 'location', 'price', 'currency', 'price_per', 'bedrooms', 'bathrooms', 'furnished', 'rera_permit_number', 'dtcm_licence', 'scraped_ts', 'amenities', 'details', 'agent_name', 'number_of_photos', 'user_id', 'phone_number', 'date', 'iteration_number', 'depth', 'sub_category_1', 'property_type', 'sub_category_2', 'published_at', 'listing_availability']

In [18]:
broker = df["broker"].fillna("").astype(str).str.strip()
display_name = df["broker_display_name"].fillna("").astype(str).str.strip()

# Find invalid rows
invalid = df[
    broker != display_name.str.upper()
][["id", "url", "broker", "broker_display_name"]]

print(f"Invalid rows: {len(invalid)}")
display(invalid)

Invalid rows: 0

Empty DataFrame
Columns: [id, url, broker, broker_display_name]
Index: []

In [19]:
df.published_at.value_counts()

published_at
2026-09-28    738
2026-09-21    658
2026-09-14    631
2026-10-05    409
2026-10-08    141
2026-10-11    126
2026-10-07    113
2026-10-10    110
2026-10-06     89
2026-10-09     24
2025-10-12      6
2026-09-12      4
2026-10-12      2
2026-08-12      1
2025-12-12      1
Name: count, dtype: int64

In [20]:
duplicates = df[df.duplicated(subset="url", keep=False)]

print(f"Duplicate URLs: {len(duplicates)}")
display(duplicates.sort_values("url"))

Duplicate URLs: 0

Empty DataFrame
Columns: [reference_number, id, url, broker_display_name, broker, category, category_url, title, description, location, price, currency, price_per, bedrooms, bathrooms, furnished, rera_permit_number, dtcm_licence, scraped_ts, amenities, details, agent_name, number_of_photos, user_id, phone_number, date, iteration_number, depth, sub_category_1, property_type, sub_category_2, published_at, listing_availability]
Index: []

In [21]:
df1 = df.copy()

for col in df1.columns:
    if df1[col].apply(lambda x: isinstance(x, list)).any():
        df1[col] = df1[col].astype(str)

duplicates = df1[df1.duplicated(keep=False)]

print(f"Duplicate rows: {len(duplicates)}")
display(duplicates)

Duplicate rows: 0

Empty DataFrame
Columns: [reference_number, id, url, broker_display_name, broker, category, category_url, title, description, location, price, currency, price_per, bedrooms, bathrooms, furnished, rera_permit_number, dtcm_licence, scraped_ts, amenities, details, agent_name, number_of_photos, user_id, phone_number, date, iteration_number, depth, sub_category_1, property_type, sub_category_2, published_at, listing_availability]
Index: []

In [22]:
import pandas as pd

df1 = df.replace(r'^\s*$', pd.NA, regex=True)

empty_columns = df1.columns[df1.isna().all()]

print("Completely empty columns:")
print(list(empty_columns))

Completely empty columns:
['reference_number', 'price_per', 'rera_permit_number', 'dtcm_licence', 'agent_name', 'user_id', 'sub_category_2']

In [23]:
import re

url_pattern = re.compile(
    r'^(https?://)'
    
    r'([a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}'
    r'(/[^\s]*)?$'
)

invalid_url = df[
    ~df["url"].fillna("").astype(str).str.match(url_pattern)
]

print(f"Invalid URLs: {len(invalid_url)}")
display(invalid_url[[ "url"]])

Invalid URLs: 0

Empty DataFrame
Columns: [url]
Index: []

In [24]:
df.listing_availability.value_counts()

listing_availability
True     3051
False       2
Name: count, dtype: int64

In [25]:
df.dtypes

reference_number                object
id                               int64
url                             object
broker_display_name             object
broker                          object
category                        object
category_url                    object
title                           object
description                     object
location                        object
price                           object
currency                        object
price_per                       object
bedrooms                        object
bathrooms                       object
furnished                       object
rera_permit_number              object
dtcm_licence                    object
scraped_ts                      object
amenities                       object
details                         object
agent_name                      object
number_of_photos                object
user_id                         object
phone_number                    object
date                    datetime64[ns]
iteration_number                 int64
depth                           object
sub_category_1                  object
property_type                   object
sub_category_2                  object
published_at            datetime64[ns]
listing_availability              bool
dtype: object

In [26]:
phone_pattern = re.compile(r'^\+?\d+$')

invalid_phone = df[
    ~df["phone_number"].fillna("").astype(str).str.match(phone_pattern)
]

display(invalid_phone[["id", "phone_number"]])

             id phone_number
45    105731646
60    105757668
61    105756071
70    105767298
80    105766749
81    105766738
98    105711788
100   105635856
129   105756170
130   500134673
131   500134414
133   500134145
134   500133939
135   500133924
136   500133655
137   500133319
142   104713338
161   105711905
165   105761352
175   105756204
191   105760234
198   105271524
203   105762083
204   105761269
207   105728125
216   105729629
219   105704317
237   105763087
241   105762078
258   105670266
259   105662208
260   105659731
261   105655784
262   105734466
263   105731715
264   105731714
265   105712272
266   105653027
269   105642487
280   105237881
283   105731643
309   105750556
322   105765714
358   105733153
396   105710619
401   105763871
412   105689315
421   105746133
518   104819786
531   105760236
538   105714070
539   105714068
558   105369873
571   105759652
619   105597820
622   104973326
625   105689757
627   104713055
633   105280668
635   105756773
647   105759395
648   104652454
657   105758589
672   104486602
680   104827806
686   105735460
690   105755804
761   105672667
769   105755337
772   105610987
773   105044708
780   105734332
789   105754822
791   105754740
799   105754452
803   105754268
813   104742567
814   104713301
815   104713294
816   104900784
817   104900752
852   104284812
868   105753282
889   105025680
944   104713335
1120  105764957
1556  105710627
1557  104819811
2200  105694471
2359  105280691
2360  104742481
2501  104907424
2593  105730587
2594  105610962
2600  105764863
2622  105689372
2627  105763034
2631  105721796
2637  105762470
2638  105349445
2643  105762370
2650  105762133
2658  105709681
2681  105522669
2688  105760227
2694  105759700
2725  105757941
2738  105706985
2754  105532135
2777  105598621
2790  105381169
2792  105258543
2801  105766091
2802  105766025
2818  105765186
2819  105389191
2820  105764542
2823  105763459
2888  105761303
2891  105761299
2893  105760586
2897  105738606
2901  105757921
2902  105758445
2906  105756415
2907  105756412
2911  105734354
2915  105754824
2916  105754699
2918  105661403
2928  105710632
2932  105696646
2933  105710631
2935  105280648
2936  104819805
2937  104819790
2941  105147100
2953  105727555
2965  104406355
2966  104713049
2969  105280695
2974  105600978
2975  105710142
2982  105754138
2983  104713305
2985  104713316
2986  104900762
2987  104742499
2988  104900769
2992  105752400
2999  104742561
3015  105753915
3025  105685554
3036  105741271
3042  105754780

In [27]:
df.sub_category_1.value_counts()

sub_category_1
Commercial     1866
Residential    1187
Name: count, dtype: int64

In [28]:
import pandas as pd

details = df["details"].fillna("").astype(str).str.strip()

# Must end with: number + space + M²
mask = details.ne("") & ~details.str.fullmatch(r"\d+(?:\.\d+)? M²", na=False)

result = df.loc[mask, ["url", "details"]].copy()
result["record_no"] = result.index + 2

print("Invalid details:", len(result))
print(result[["record_no", "url", "details"]].to_string(index=False))

Invalid details: 3053
 record_no                                                                                                                                                                                                                                                                                                                                                                                                                             url      details
         2                                                                                                                                                                                           https://www.dubizzle.com.bh/en/ad/%D9%84%D9%84%D8%A7%D9%8A%D8%AC%D8%A7%D8%B1-%D8%B3%D8%AA%D8%AF%D9%8A%D9%88-%D9%85%D9%81%D8%B1%D9%88%D8%B4-%D9%81%D9%8A-%D8%AC%D8%AF%D8%B9%D9%84%D9%8A-for-rent-f-f-studio-in-jidali-ID105767254.html        20 m²
         3                                                                                                                                                                                                                         https://www.dubizzle.com.bh/en/ad/%D8%B4%D9%82%D9%87-%D9%86%D8%B8%D9%8A%D9%81%D9%87-%D9%84%D9%84%D8%A7%D9%8A%D8%AC%D8%A7%D8%B1-%D9%81%D9%8A-%D8%A7%D9%84%D8%AD%D8%AC%D9%8A%D8%A7%D8%AA-ID105765882.html       120 m²
         4                                                                                                                                                                                            https://www.dubizzle.com.bh/en/ad/ff-studio-for-rent-in-jidali-%D9%84%D9%84%D8%A7%D9%8A%D8%AC%D8%A7%D8%B1-%D8%B3%D8%AA%D8%AF%D9%8A%D9%88-%D9%85%D9%81%D8%B1%D9%88%D8%B4-%D9%81%D9%8A-%D8%AC%D8%AF%D8%B9%D9%84%D9%8A-ID105766884.html        30 m²
         5                                                                                                                                                                                                                                                                                                                                                     https://www.dubizzle.com.bh/en/ad/studio-flat-in-banijamra-ID105767346.html        70 m²
         6                                                                                                                                                                                                                                                                                                                   https://www.dubizzle.com.bh/en/ad/limited-offer-fully-furnished-1bhk-bd-380-pool-gym-jacuzzi-ID105765225.html        65 m²
         7                                                                                                                                                                                                                                                                                                                                   https://www.dubizzle.com.bh/en/ad/fully-furnished-2bhk-apartment-only-bd-580-ID105765214.html        90 m²
         8                                                                                                                                                                                                                                                                                                                           https://www.dubizzle.com.bh/en/ad/for-rent-1-bedroom-in-arard-all-inclusive-no-limit-ID105764783.html        45 m²
         9                                                                                                                                                                 https://www.dubizzle.com.bh/en/ad/for-rent-ff-studio-in-isa-town-%D9%84%D9%84%D8%A7%D9%8A%D8%AC%D8%A7%D8%B1-%D8%B3%D8%AA%D8%AF%D9%8A%D9%88-%D9%85%D9%81%D8%B1%D9%88%D8%B4-%D9%81%D9%8A-%D9%85%D8%AF%D9%8A%D9%86%D8%A9-%D8%B9%D9%8A%D8%B3%D9%89-ID105764639.html        20 m²
        10                                                                                                                                                                                                                                                                                                                         https://www.dubizzle.com.bh/en/ad/house-for-rent-in-sehla-with-car-garage-outdoor-area-ID105763048.html       180 m²
        11                                                                                                                                                                                                                                                                                                                                                 https://www.dubizzle.com.bh/en/ad/studio-flat-for-rent-budayia-ID105762273.html        70 m²
        12                                                                                                                                                                                                                                                                                                                            https://www.dubizzle.com.bh/en/ad/2bhk-apartment-in-diah-area-near-al-razi-pharmacy-ID105763663.html        80 m²
        13                                                                                                                                                                                                                                                                                                                                         https://www.dubizzle.com.bh/en/ad/town-house-for-rent-in-budayia-h-way-ID105762214.html       120 m²
        14                                                                                                                                                                                                                                                                                                                                                     https://www.dubizzle.com.bh/en/ad/spacious-studio-for-rent-ID105761657.html        65 m²
        15                                                                                                                                                                                                                                                                                                               https://www.dubizzle.com.bh/en/ad/spacious-2bhk-flat-available-for-rent-in-prime-location-galali-ID105761729.html        85 m²
        16                                                                                                                                                                                                                                                                                                                                       https://www.dubizzle.com.bh/en/ad/for-rent-2-bedrooms-aparment-in-jidali-ID105761477.html        85 m²
        17                                                                                                                                                                                                                                                                                                                         https://www.dubizzle.com.bh/en/ad/2-bedroom-apartment-for-rent-hamad-town-roundabout-2-ID105761128.html        95 m²
        18                                                                                                                                                                                                                   https://www.dubizzle.com.bh/en/ad/%D9%81%D9%8A%D9%84%D8%A7-%D8%B1%D8%A7%D9%82%D9%8A%D9%87-%D9%84%D9%84%D8%A7%D9%8A%D8%AC%D8%A7%D8%B1-%D9%81%D9%8A-%D8%A8%D9%88%D9%83%D9%88%D8%A7%D8%B1%D9%87-ID105760338.html       220 m²
        19                                                                                                                                                                                                                                                                                                                                https://www.dubizzle.com.bh/en/ad/3bhk-apartment-in-jidhafs-first-floor-with-ac-ID105760040.html       125 m²
        20                                                                                                                                                                              https://www.dubizzle.com.bh/en/ad/ff-1-bhk-in-sanad-%D9%84%D8%A7%D9%8A%D8%AC%D8%A7%D8%B1-%D8%B4%D9%82%D8%A9-%D9%85%D9%81%D8%B1%D9%88%D8%B4%D8%A9-%D8%A8%D8%A7%D9%84%D9%83%D8%A7%D9%85%D9%84-%D9%85%D9%86-%D8%BA%D8%B1%D9%81%D8%A9-ID105756882.html        50 m²
        21                                                                                                                                                                                                             https://www.dubizzle.com.bh/en/ad/%D8%BA%D8%B1%D9%81%D9%87-%D9%88%D8%AD%D9%85%D8%A7%D9%85-%D9%88%D8%B5%D8%A7%D9%84%D9%87-%D9%88%D9%85%D8%B7%D8%A8%D8%AE-%D9%84%D9%84%D8%A7%D9%8A%D8%AC%D8%A7%D8%B1-ID105757807.html        60 m²
        22                                                                                                                                              https://www.dubizzle.com.bh/en/ad/%D8%B4%D9%82%D9%87-%D9%85%D8%B1%D8%AA%D8%A8%D9%87-%D9%81%D9%8A-%D8%A7%D9%84%D8%AD%D8%AC%D9%8A%D8%A7%D8%AA-%D8%AB%D9%84%D8%A7%D8%AB-%D8%BA%D8%B1%D9%81-%D8%B4%D8%A7%D9%85%D9%84-%D8%A7%D9%84%D9%83%D9%87%D8%B1%D8%A8%D8%A7%D8%A1-ID105758157.html       140 m²
        23                                                                                                                                                                                           https://www.dubizzle.com.bh/en/ad/%D9%84%D9%84%D8%A7%D9%8A%D8%AC%D8%A7%D8%B1-%D8%B4%D9%82%D8%A9-%D9%85%D9%86-%D8%BA%D8%B1%D9%81%D8%AA%D9%8A%D9%86-%D8%A8%D8%AC%D8%AF%D8%B9%D9%84%D9%8A-for-rent-2-bhk-flat-in-jidali-ID105756875.html       100 m²
        24                                                                                                                                                                                                                                                                                                                                      https://www.dubizzle.com.bh/en/ad/workshop-warehouse-for-rent-in-salmabad-ID105765679.html       550 m²
        25                                                                                                                                                                                                                                                                                                                 https://www.dubizzle.com.bh/en/ad/workshop-warehouse-in-salmabad-with-2-entrance-high-power505-ID105761771.html       505 m²
        26                                                                                                                                                                                                                                                                                                                                     https://www.dubizzle.com.bh/en/ad/spacious-large-commercial-shop-in-galali-ID105761746.html        18 m²
        27                                                                                                                                                                                                                                                                                                                     https://www.dubizzle.com.bh/en/ad/warehouse-workshop-with-ready-showroom-for-rent-in-tubli-ID105757214.html       350 m²
        28                                                                                                                                                     https://www.dubizzle.com.bh/en/ad/%D8%B4%D9%82%D9%82-%D9%81%D8%A7%D8%AE%D8%B1%D9%87-%D9%85%D9%83%D8%AA%D8%A8%D9%8A%D9%87-%D9%81%D9%8A-%D8%A7%D9%84%D8%B1%D9%81%D8%A7%D8%B9-%D8%A7%D9%84%D8%B4%D8%B1%D9%82%D9%8A-%D8%A7%D9%84%D8%AD%D8%AC%D9%8A%D8%A7%D8%AA-ID105680754.html       140 m²
        29                                                                                                                                                                                                                                                                                                                                           https://www.dubizzle.com.bh/en/ad/office-for-rent-in-diplomatic-area-ID105573482.html       120 m²
        30                                                                                                                                                                                                                                                                                                                                     https://www.dubizzle.com.bh/en/ad/office-for-rent-in-tubli-bright-spacious-ID105752505.html        90 m²
        31                                                                                                                                                                                                                                                                                                                                     https://www.dubizzle.com.bh/en/ad/commercial-storage-space-available-sanad-ID105729764.html        30 m²
        32                                                                                                                                                                                                                                                                                                                                                  https://www.dubizzle.com.bh/en/ad/shop-in-east-riffa-for-rent-ID105425101.html        18 m²
        33                                                                                                                                                                                                                                                                                                                    https://www.dubizzle.com.bh/en/ad/today-commercial-address-available-call-now-monthly-bd-99-ID104797070.html        10 m²
        34                                                                                                                                                                                                                                                                                                                    https://www.dubizzle.com.bh/en/ad/best-place-for-commercial-address-at-fakhro-tower-get-now-ID104797066.html        10 m²
        35                                                                                                                                                                                                                                                                                                                     https://www.dubizzle.com.bh/en/ad/call-now-bhd-100-per-month-for-commercial-office-address-ID105102468.html        10 m²
        36                                                                                                                                                                                                                                                                                                               https://www.dubizzle.com.bh/en/ad/good-offer-for-commercial-office-address-99-bd-monthly-get-now-ID104924348.html        10 m²
        37                                                                                                                                                                                                                                                                                                                         https://www.dubizzle.com.bh/en/ad/contact-us-commercial-address-for-rent-66-bd-monthly-ID104924343.html        10 m²
        38                                                                                                                                                                                                                                                                                                                 https://www.dubizzle.com.bh/en/ad/reasonable-price-for-99-bd-commercial-office-address-at-seef-ID104932819.html        10 m²
        39                                                                                                                                                                                                                                                                                                           https://www.dubizzle.com.bh/en/ad/limited-offer-99-bdmonthlyfor-commercial-office-at-seef-park-place-ID104932812.html        10 m²
        40                                                                                                                                                                                                                                                                                                                    https://www.dubizzle.com.bh/en/ad/special-offer-for-commercial-officeaddress-100-bd-monthly-ID104864948.html        10 m²
        41                                                                                                                                                                                                                                                                                                             https://www.dubizzle.com.bh/en/ad/commercial-address-available-for-rentat-gulf-hotel-bd-99-monthly-ID104864945.html        10 m²
        42                                                                                                                                                                                                                                                                                                                          https://www.dubizzle.com.bh/en/ad/commercial-address-available-call-now-monthly-bd-66-ID104933002.html        10 m²
        43                                                                                                                                                                                                                                                                                                                   https://www.dubizzle.com.bh/en/ad/fully-furnished-commercial-address-available-66-bd-monthly-ID104933000.html        10 m²
        44                                                                                                                                                                                                                                                                                                              https://www.dubizzle.com.bh/en/ad/commercial-address-with-best-services-get-nowfor-bd-100-monthly-ID104867315.html        10 m²
        45                                                                                                                                                                                                                                                                                                          https://www.dubizzle.com.bh/en/ad/contact-us-commercial-address-available-for-rent-at-seef-park-place-ID104866312.html        10 m²

In [29]:
import re

email_pattern = re.compile(
    r'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'
)

invalid_emails = df[
    df["email"].notna() &
    (df["email"].astype(str).str.strip() != "") &
    ~df["email"].astype(str).str.strip().str.match(email_pattern)
]

print(f"Invalid emails: {len(invalid_emails)}")
display(invalid_emails[["email"]])

KeyError: 'email'

In [30]:
duplicates = df[df.duplicated("id", keep=False)]

print(f"Duplicate IDs: {duplicates.shape[0]}")
display(duplicates[["id"]])

Duplicate IDs: 0

Empty DataFrame
Columns: [id]
Index: []

In [31]:
duplicates = (
    df[df["id"].duplicated(keep=False)]
    .sort_values("id")
)

print(f"Duplicate rows: {len(duplicates)}")
display(duplicates)

Duplicate rows: 0

Empty DataFrame
Columns: [reference_number, id, url, broker_display_name, broker, category, category_url, title, description, location, price, currency, price_per, bedrooms, bathrooms, furnished, rera_permit_number, dtcm_licence, scraped_ts, amenities, details, agent_name, number_of_photos, user_id, phone_number, date, iteration_number, depth, sub_category_1, property_type, sub_category_2, published_at, listing_availability]
Index: []

In [32]:
allowed = [
    "Apartments",
    "Rooms",
    "Villas",
    "Commercial",
    "Multiple-units",
    "Buildings",
    "Garage",
    "Chalet",
    "land",
    "Rentals-wanted"
]

invalid = df[~df["property_type"].isin(allowed)]

display(invalid[["id", "property_type"]])

             id property_type
118   500133900          Land
119   105758935          Land
120   104795861          Land
176   500133962          Land
177   105168575          Land
178   500133899          Land
179   105462629          Land
180   105766897          Land
181   105766742          Land
182   105751021          Land
183   105627092          Land
184   105764952          Land
185   105725707          Land
186   105675699          Land
187   105762676          Land
188   105762235          Land
189   105744997          Land
190   104855788          Land
191   105760234          Land
192   105738515          Land
193   105542677          Land
194   105612062          Land
195   105612067          Land
196   105735623          Land
197   105759068          Land
198   105271524          Land
3006  105758161          Land
3007  105757761          Land
3008  105757227          Land
3009  105722788          Land
3010  105700007          Land
3011  105634663          Land
3012  105611239          Land
3013  105116316          Land
3014  105754723          Land
3015  105753915          Land
3016  104063448          Land
3017  105753359          Land
3018  105125441          Land

In [33]:
date_regex = r"^\d{4}-\d{2}-\d{2}$"

for col in ["scraped_ts", "date"]:
    invalid = df[
        ~df[col].fillna("").astype(str).str.match(date_regex)
    ]
    print(col, len(invalid))

scraped_ts 0
date 0

In [34]:
df.date.value_counts()

date
2026-10-12    3053
Name: count, dtype: int64

In [35]:
broker = df["broker"].fillna("").astype(str).str.strip()
display_name = df["broker_display_name"].fillna("").astype(str).str.strip()

invalid = df[
    broker != display_name.str.upper()
]

display(invalid[["id", "broker", "broker_display_name"]])

Empty DataFrame
Columns: [id, broker, broker_display_name]
Index: []

In [36]:
df.type.value_counts()

AttributeError: 'DataFrame' object has no attribute 'type'

In [37]:
import pandas as pd

invalid = df[
   
     df["developer_start_price"].replace(r'^\s*$', pd.NA, regex=True).isna() 
]

print(f"Rows where both prices are missing: {len(invalid)}")
display(invalid)

KeyError: 'developer_start_price'

In [38]:
df.currency.value_counts()

currency
BHD    3047
          6
Name: count, dtype: int64

In [25]:
import pandas as pd

text_cols = df.select_dtypes(include="object").columns

issues = []

for col in text_cols:
    s = df[col].fillna("").astype(str)

    mask = (
        s.str.match(r"^\s") |                  # Leading whitespace
        s.str.match(r".*\s$") |                # Trailing whitespace
        s.str.contains(r" {2,}", regex=True) | # Multiple consecutive spaces
        s.str.contains(r"[\t\r\n]", regex=True) |  # Tabs/newlines
        s.str.contains("\u00A0", regex=False)      # Non-breaking space
    )

    if mask.any():
        temp = df.loc[mask, [col]].copy()
        temp["column"] = col
        temp["row_index"] = temp.index
        issues.append(temp)

if issues:
    whitespace_issues = pd.concat(issues, ignore_index=True)
    print(f"Total issues found: {len(whitespace_issues)}")
    display(whitespace_issues[["row_index", "column"] + [c for c in whitespace_issues.columns if c not in ["row_index","column"]]])
else:
    print("✅ No unwanted whitespace found.")

Total issues found: 121423

KeyboardInterrupt:

In [30]:
# 2. Define the columns
columns_to_analyze = [
    "category", "title", "location", "price", "currency", "price_per",
    "bedrooms", "bathrooms", "furnished", "rera_permit_number",
    "dtcm_licence", "scraped_ts", "amenities", "details", "agent_name",
    "number_of_photos", "user_id", "phone_number", "date", "iteration_number",
    "depth", "sub_category_1", "property_type", "sub_category_2",
    "published_at", "listing_availability", "ownership", "verified_business"
]

# 3. Print the number of unique entries and their breakdown
for col in columns_to_analyze:
    if col in df.columns:
        unique_count = df[col].nunique()
        print(f"==================================================")
        print(f"COLUMN: {col}")
        print(f"Total Unique Values: {unique_count}")
        print(f"==================================================")
        print(df[col].value_counts())
        print("\n")

==================================================
COLUMN: category
Total Unique Values: 2
==================================================
category
sale    3990
rent     627
Name: count, dtype: int64


==================================================
COLUMN: title
Total Unique Values: 28
==================================================
title
أرض سكنية للبيع                          2543
فيلا سكنية للبيع                          727
شقة سكنية للإيجار                         447
شقة سكنية للبيع                           288
أرض تجارية للبيع                          236
مبنى تجاري للبيع                           77
فيلا سكنية للإيجار                         59
شقة استوديو سكنية للإيجار                  55
شقة استوديو سكنية للبيع                    20
Residential Villa For Rent                 16
Residential Land For Sale                  16
Residential Villa For Sale                 16
Commercial Office For Rent                 16
Commercial Land For Sale                   16
Commercial Building For Sale               16
Residential Apartment For Sale             14
Residential Apartment For Rent             14
مكتب تجاري للإيجار                          8
Residential Penthouse For Sale              8
Commercial Villa For Sale                   7
Commercial Office For Sale                  4
Residential Penthouse For Rent              3
Commercial Building For Rent                3
Residential Studio Apartment For Sale       2
Commercial Villa For Rent                   2
Residential Studio Apartment For Rent       2
Residential Land For Rent                   1
Commercial Land For Rent                    1
Name: count, dtype: int64


==================================================
COLUMN: location
Total Unique Values: 179
==================================================
location
الهملة                 442
ضاحية السيف            241
الجفير                 185
عالي                   156
الجنبية                144
المالكية               143
سار                    135
ديار المحرق            124
دمستان                 124
توبلي                  119
بوقوة                  101
جزر امواج              100
صدد                    100
الحد                    98
باربار                  95
البسيتين                93
القرية                  93
كرزكان                  89
النويدرات               88
سند                     78
سترة                    74
مقابة                   70
عراد                    68
الرملي                  68
شهركان                  65
مدينة حمد               63
دلمونيا                 51
سلماباد                 50
البديع                  46
الرفاع                  43
قلالي                   43
السنابس                 41
العكر                   38
جد علي                  36
دار كليب                34
بوري                    33
جبلة حبشي               33
راس حيان                32
مراسي البحرين           32
سرايا 2                 28
عسكر                    28
المحرق                  28
جزيرة الريف             27
سماهيج                  27
المنامة                 27
الزنج                   23
اللوزي                  22
الشاخورة                22
المقشع                  22
الدراز                  21
جدحفص                   20
جد الحاج                20
جرداب                   19
بني جمرة                19
البحير                  19
السهلة الشمالية         19
مدينة عيسى              18
خليج البحرين            18
كرانة                   17
درة المحرق              16
Seef District           16
الحجر                   16
المرخ                   15
الدير                   13
الديه                   12
المعامير                12
الخميس                  12
سرايا 1                 12
الرفاع الشرقي           12
Hidd                    11
الساية                  11
جنوسان                  11
جو                      10
ام الحصم                10
البرهامة                 9
هورة عالي                9
مدينة خليفة              9
القدم                    9
عذاري                    8
العدلية                  8
الماحوز                  8
Juffair                  8
راس زويد                 7
درة البحرين              7
المصلى                   7
Manama                   7
هورة سند                 7
Sar                      7
ابو صيبع                 7
البلاد القديم            6
Aali                     5
حلة العبد الصالح         5
بو كوارة                 5
Janabiyah                5
Diyar Al Muharraq        5
Hamalah                  5
النبيه صالح              5
الرفاع الشمالي           5
Damistan                 4
Budaiya                  4
الزلاق                   4
القضيبية                 4
السلمانية                4
السهلة الجنوبية          4
القفول                   4
سترة الصناعية            4
Amwaj Island             4
بحرين هاربور             4
Tubli                    4
الحورة                   3
Um Al Hasam              3
Mahooz                   3
Eker                     3
Busaiteen                3
Bu Asheera               3
جري الشيخ                3
الرفاع فيوز              3
Muharraq                 3
Adliya                   2
Adhari                   2
السقية                   2
Burhama                  2
نورانا                   2
بو عشيرة                 2
Reef Island              2
مدينة سلمان              2
القلعة                   2
الرفاع الغربي            2
مدينة زايد               2
الصالحية                 2
راس رمان                 2
Jid Ali                  2
Sanad                    2
Hamad Town               2
Isa Town                 2
Marassi Al Bahrain       2
Barbar                   2
Qurayyah                 2
Durrat Al Bahrain        2
Daih                     1
Hajiyat                  1
Khalifa Town             1
Saraya 2                 1
Malkiya                  1
Dair                     1
Jid Al Haj               1
Jidhafs                  1
Sayah                    1
Lawzi                    1
Sanabis                  1
Durrat Al Muharraq       1
Karbabad                 1
Salman Town              1
Diraz                    1
Maqaba                   1
Shakhura                 1
كرباباد                  1
الجسرة                   1
Dilmunia                 1
Salmabad                 1
Karzakkan                1
East Riffa               1
Ramli                    1
Qudaibiya                1
الغريفة                  1
النعيم                   1
دانة البحرين             1
Bu Kowarah               1
Jannusan                 1
Sugaya                   1
Hoora                    1
المنطقة الدبلوماسية      1
Ras Zuwaid               1
Riffa Views              1
Bahrain Bay              1
العرين                   1
الحنينية                 1
بو غزال                  1
الحالة                   1
Name: count, dtype: int64


==================================================
COLUMN: price
Total Unique Values: 2221
==================================================
price
120,000      49
140,000      45
500          45
400          44
300          41
130,000      39
350          35
125,000      34
55,000       31
110,000      31
95,000       30
115,000      30
145,000      30
75,000       30
550          30
450          28
80,000       28
85,000       27
155,000      24
150,000      24
90,000       24
100,000      23
65,000       22
60,000       21
105,000      21
135,000      20
160,000      20
70,000       20
96,134       20
380          20
58,000       19
180,000      19
128,000      19
50,000       19
600          18
250          16
200,000      16
190,000      16
650          16
320,000      16
165,000      16
700          15
142,000      15
200          15
250,000      14
68,000       14
129,000      14
170,000      13
118,000      13
750          13
220,000      13
800          13
260,000      12
98,000       12
126,000      12
290,000      12
52,000       12
350,000      12
112,000      11
280,000      11
175,000      11
1,000        11
255,000      11
62,000       11
48,000       11
320          10
420          10
103,000      10
280          10
230,000      10
330,000      10
93,000       10
370          10
40,000       10
72,000       10
51,000       10
230          10
139,000      10
92,000       10
37,000        9
49,000        9
56,000        9
82,000        9
185,000       9
900           9
84,000        9
240,000       9
96,167        9
1,200         9
38,000        9
850           8
235,000       8
300,000       8
210,000       8
122,000       8
61,000        8
109,000       8
88,000        8
54,000        8
45,000        8
77,000        8
101,000       7
107,000       7
87,000        7
195,000       7
67,000        7
400,000       7
73,000        7
270,000       7
47,000        7
360           7
220           7
330           7
108,000       7
177,000       7
225,000       7
63,000        7
42,000        7
450,000       6
147,000       6
260           6
99,423        6
270           6
265,000       6
475           6
102,941       6
148,000       6
78,000        6
240           6
160           6
178,000       6
89,000        6
79,000        6
137,000       6
117,000       6
300,819       6
133,990       5
123,000       5
1,500         5
67,028        5
156,000       5
285,000       5
53,000        5
74,999        5
81,000        5
116,509       5
96,000        5
113,000       5
46,500        5
78,999        5
86,000        5
89,332        5
425           5
410           5
96,201        5
173,000       5
64,000        5
275,000       4
104,000       4
59,000        4
390           4
73,304        4
115,001       4
580           4
480           4
215,000       4
325,000       4
78,892        4
140           4
116,630       4
530           4
43,000        4
114,000       4
116,000       4
98,813        4
108,313       4
63,999        4
98,167        4
121,983       4
170           4
116,315       4
119,000       4
133,311       4
102,150       4
680           4
116,423       4
85,586        4
98,894        4
198,000       4
96,972        4
111,601       4
430           4
66,992        4
128,845       4
143,000       4
199,000       3
1,300         3
103,783       3
229,000       3
132,000       3
145,206       3
600,000       3
66,069        3
154,614       3
465,000       3
1,200,000     3
84,999        3
79,999        3
105,001       3
1,800         3
83,000        3
99,410        3
127,000       3
141,051       3
79,900        3
146,382       3
190           3
110,186       3
375           3
800,000       3
28,000        3
117,835       3
290           3
49,500        3
115,303       3
70,578        3
33,000        3
850,000       3
295,000       3
370,000       3
380,000       3
77,500        3
3,000         3
119,351       3
74,998        3
97,000        3
98,377        3
210           3
206,301       3
98,791        3
81,999        3
90,417        3
108,614       3
249,000       3
265           3
89,998        3
375,000       3
69,440        3
126,162       3
115,282       3
85,154        3
98,555        3
68,499        3
129,400       3
226,044       3
184,000       3
287,867       3
250,002       3
103,479       3
102,000       3
360,000       3
470           3
179,000       3
69,000        3
162,000       3
55,154        3
159,845       3
105,497       3
89,039        3
132,666       2
135,023       2
75,604        2
126,304       2
104,884       2
68,500        2
108,247       2
96,525        2
101,719       2
67,500        2
112,608       2
51,760        2
54,638        2
340           2
150           2
68,994        2
96,314        2
106,001       2
106,149       2
134,644       2
85,801        2
133,000       2
120,556       2
72,191        2
105,053       2
101,865       2
88,001        2
51,538        2
110,331       2
127,488       2
101,332       2
111,999       2
2,200         2
112,500       2
112,725       2
95,153        2
105,271       2
109,243       2
97,476        2
48,915        2
142,182       2
94,198        2
131,234       2
190,509       2
248,000       2
101,702       2
103,334       2
106,951       2
111,165       2
69,673        2
59,999        2
114,442       2
60,935        2
39,999        2
144,000       2
44,000        2
315,000       2
123,860       2
132,635       2
93,065        2
233,503       2
121,685       2
134,851       2
111,609       2
96,876        2
74,271        2
291,919       2
45,500        2
83,001        2
121,712       2
99,598        2
124,800       2
115,337       2
222,000       2
121,366       2
101,585       2
1,250         2
98,008        2
94,848        2
136,069       2
80,682        2
516,650       2
130,836       2
106,068       2
94,034        2
126,806       2
119,092       2
103,754       2
156,898       2
103,957       2
102,242       2
2,000         2
59,500        2
159,000       2
163,000       2
950           2
117,661       2
108,347       2
102,908       2
102,974       2
822           2
97,414        2
121,159       2
119,999       2
100,359       2
330,080       2
203,148       2
94,000        2
104,509       2
111,945       2
160,733       2
317,207       2
111,213       2
146,067       2
97,999        2
130,730       2
52,151        2
103,592       2
100,815       2
105,220       2
101,965       2
105,999       2
110,223       2
129,108       2
211,101       2
98,500        2
39,000        2
470,000       2
126,494       2
197,562       2
64,368        2
58,061        2
98,713        2
119,803       2
132,201       2
138,000       2
106,292       2
144,926       2
188,000       2
119,325       2
111,515       2
223,029       2
95,820        2
127,004       2
310,000       2
71,494        2
77,452        2
576,347       2
127,518       2
64,999        2
90,934        2
124,001       2
141,884       2
75,348        2
88,428        2
106,450       2
129,168       2
2,700         2
480,000       2
99,911        2
112,897       2
181,359       2
200,285       2
94,690        2
97,392        2
109,878       2
346,303       2
123,637       2
65,891        2
146,000       2
48,999        2
166,187       2
48,400        2
152,392       2
91,515        2
103,818       2
475,000       2
258,000       2
172,000       2
69,994        2
47,805        2
93,646        2
154,355       2
118,753       2
72,463        2
163,104       2
35,000        2
115,841       2
116,005       2
120,002       2
75,078        2
200,001       2
155,819       2
540           2
160,504       2
168,000       2
97,500        2
390,000       2
157,000       2
140,015       2
150,818       2
100,644       2
67,779        2
200,823       2
129,417       2
840           2
66,000        2
111,000       2
650,000       2
120           2
99,000        2
520           2
397,428       2
190,668       2
102,204       2
440           2
310           2
169,000       2
490,915       2
420,000       2
49,999        2
134,334       2
106,578       2
102,541       2
91,000        2
525           2
71,000        2
41,000        2
96,549        2
96,393        2
80,001        2
121,000       2
236,683       2
75,650        2
189,000       2
207,062       2
50,999        2
51,845        2
133,554       2
157,003       2
158,668       2
180           2
108,398       2
151,707       2
94,998        2
391,852       2
140,524       2
48,674        2
118,567       2
54,999        2
88,799        2
245,000       2
101,612       2
269,000       2
119,998       2
128,513       1
199,220       1
89,629        1
129,518       1
95,755        1
105,146       1
201,586       1
124,708       1
424,407       1
126,799       1
131,683       1
120,741       1
151,234       1
133,134       1
99,869        1
140,999       1
96,799        1
51,598        1
79,567        1
106,093       1
174,798       1
89,418        1
90,149        1
91,999        1
92,322        1
76,509        1
81,019        1
92,999        1
233,168       1
92,641        1
195,931       1
104,679       1
174,861       1
196,000       1
243,000       1
139,604       1
162,775       1
219,000       1
98,764        1
116,746       1
97,602        1
143,500       1
124,900       1
199,822       1
126,682       1
180,243       1
60,528        1
274,266       1
119,389       1
502,446       1
316,892       1
190,641       1
218,000       1
172,074       1
101,362       1
143,789       1
106,009       1
109,889       1
189,446       1
294,848       1
288,370       1
583,219       1
269,073       1
204,500       1
445,909       1
280,474       1
113,926       1
192,331       1
205,000       1
180,702       1
102,473       1
106,641       1
148,134       1
140,002       1
780,000       1
329,998       1
132,122       1
345,048       1
545,121       1
152,676       1
416,269       1
489,573       1
168,564       1
212,226       1
150,047       1
430,872       1
123,252       1
118,987       1
144,600       1
339,066       1
306,655       1
87,188        1
267,087       1
123,400       1
236,784       1
335,007       1
172,891       1
162,805       1
160,704       1
83,728        1
240,898       1
88,060        1
330,088       1
69,999        1
220,610       1
193,144       1
94,173        1
181,112       1
168,429       1
63,733        1
191,300       1
232,147       1
622,772       1
700,000       1
381,540       1
218,213       1
244,709       1
204,556       1
175,119       1
60,642        1
136,501       1
236,950       1
208,864       1
85,133        1
460,285       1
324,480       1
610,000       1
95,722        1
199,997       1
88,426        1
215,069       1
119,730       1
174,505       1
73,044        1
139,811       1
55,122        1
170,017       1
110,185       1
294,599       1
371,729       1
124,986       1
71,200        1
85,999        1
675           1
150,771       1
182,697       1
132,073       1
120,901       1
178,671       1
109,024       1
630           1
285           1
328,000       1
1,250,000     1
340,000       1
636,023       1
514,626       1
219,161       1
543,901       1
65,229        1
92,032        1
71,113        1
128,441       1
175,086       1
88,100        1
244,708       1
149,000       1
123,457       1
113,662       1
91,998        1
187,327       1
113,108       1
475,338       1
307,850       1
191,523       1
239,390       1
410,000       1
147,929       1
302,253       1
75,257        1
135,626       1
157,132       1
144,991       1
158,800       1
109,993       1
48,765        1
124,330       1
152,632       1
173,749       1
520,000       1
145,400       1
93,243        1
750,000       1
90,899        1
92,346        1
82,900        1
284,998       1
137,659       1
111,891       1
263,700       1
152,741       1
49,247        1
170,001       1
184,714       1
385           1
163,943       1
207,282       1
101,246       1
229,998       1
305,598       1
92,316        1
89,012        1
108,694       1
216,087       1
99,981        1
96,998        1
102,783       1
339,819       1
67,638        1
124,998       1
128,500       1
89,571        1
217,583       1
106,563       1
117,882       1
191,857       1
1,409,815     1
202,000       1
71,881        1
91,627        1
1,141,522     1
27,216        1
399,000       1
154,997       1
26,000        1
162,797       1
629,048       1
526,682       1
132,577       1
147,868       1
280,017       1
185,635       1
124,022       1
123,516       1
200,118       1
100,107       1
106,892       1
315,402       1
91,039        1
187,622       1
576,000       1
206,754       1
105,452       1
115,088       1
71,785        1
98,103        1
110,570       1
92,591        1
620,000       1
119,867       1
80,076        1
107,998       1
92,800        1
57,999        1
93,001        1
150,965       1
145,798       1
108,124       1
86,623        1
155,324       1
653,980       1
70,072        1
125,852       1
7,000         1
1,440         1
790           1
830           1
712,154       1
277,657       1
159,500       1
51,779        1
126,557       1
109,870       1
191,685       1
293,194       1
200,371       1
134,743       1
303,848       1
103,076       1
133,831       1
103,065       1
52,991        1
125,379       1
417,427       1
138,160       1
230,564       1
329,679       1
114,798       1
463,390       1

In [40]:
df.bathrooms.value_counts()

bathrooms
       2980
2       465
5       278
4       216
3       208
6       192
1       132
7        85
8        32
9        10
10        9
12        5
11        2
375       1
17        1
14        1
Name: count, dtype: int64

In [36]:
df.nunique()

reference_number       3857
url                    4617
broker_display_name      29
broker                   29
category                  2
category_url              2
title                    28
description            4107
location                179
price                  2221
currency                  1
price_per                 1
bedrooms                  8
bathrooms                16
furnished                 7
rera_permit_number        1
dtcm_licence              1
scraped_ts                1
amenities              1464
details                1915
agent_name               95
number_of_photos          3
phone_number             53
user_id                   1
date                      1
iteration_number          1
sub_category_1            4
sub_category_2            1
property_type            13
depth                     3
last_update             124
published_at            651
id                     4617
dtype: int64

In [59]:
import pandas as pd

date_cols = [
    "scraped_ts",
    "license_start_date",
    "license_end_date",
    "date"
]

for col in date_cols:
    # Convert to datetime using the expected format
    parsed = pd.to_datetime(df[col], format="%Y-%m-%d", errors="coerce")

    invalid = df[parsed.isna() & df[col].notna() & (df[col].astype(str).str.strip() != "")]

    print(f"\n{col}")
    print(f"Invalid date format count: {len(invalid)}")

    if len(invalid) > 0:
        display(invalid[[col]])

scraped_ts
Invalid date format count: 0

KeyError: 'license_start_date'

In [60]:
df.isnull().sum()

reference_number       0
id                     0
url                    0
broker_display_name    0
broker                 0
category               0
category_url           0
title                  0
description            0
location               0
price                  0
currency               0
price_per              0
bedrooms               0
bathrooms              0
furnished              0
rera_permit_number     0
dtcm_licence           0
scraped_ts             0
amenities              0
details                0
agent_name             0
number_of_photos       0
user_id                0
phone_number           0
date                   0
iteration_number       0
depth                  0
sub_category_1         0
property_type          0
sub_category_2         0
published_at           0
dtype: int64

In [61]:
null_counts = df.isna().sum()

print(null_counts)

reference_number       0
id                     0
url                    0
broker_display_name    0
broker                 0
category               0
category_url           0
title                  0
description            0
location               0
price                  0
currency               0
price_per              0
bedrooms               0
bathrooms              0
furnished              0
rera_permit_number     0
dtcm_licence           0
scraped_ts             0
amenities              0
details                0
agent_name             0
number_of_photos       0
user_id                0
phone_number           0
date                   0
iteration_number       0
depth                  0
sub_category_1         0
property_type          0
sub_category_2         0
published_at           0
dtype: int64

In [62]:
empty_counts = (
    df.astype(str)
      .apply(lambda col: (col.str.strip() == "").sum())
)

print(empty_counts)

reference_number       2974
id                        0
url                       0
broker_display_name       0
broker                    0
category                  0
category_url              0
title                     0
description               0
location                  0
price                     5
currency                  5
price_per              2974
bedrooms                728
bathrooms               728
furnished                 0
rera_permit_number     2974
dtcm_licence           2974
scraped_ts                0
amenities               808
details                   0
agent_name             2974
number_of_photos          5
user_id                2974
phone_number            260
date                      0
iteration_number          0
depth                  2961
sub_category_1            0
property_type             0
sub_category_2         2974
published_at              0
dtype: int64

In [63]:
df[df["phone_number_1"].astype(str).str.strip() == ""]

KeyError: 'phone_number_1'

In [64]:
import json

file_path = r"/home/user/Downloads/dari_ae_2025_07_04.json"

with open(file_path, "r", encoding="utf-8") as f:
    for i, line in enumerate(f, 1):
        try:
            json.loads(line)
        except Exception as e:
            print(f"Error at line {i}")
            print(e)
            print(line[:500])   # show the beginning of the problematic line
            break
    else:
        print("✅ No JSON syntax errors found.")

✅ No JSON syntax errors found.

In [65]:
import json

file_path = r"/home/user/Downloads/dari_ae_2025_07_04.json"

with open(file_path, "r", encoding="utf-8") as f:
    try:
        data = json.load(f)
        print("✅ Valid JSON")
    except Exception as e:
        print(e)

Extra data: line 2 column 1 (char 498)

In [39]:
cols = ["phone_number_1", "phone_number_2"]

df[cols] = df[cols].fillna("").astype(str).apply(lambda x: x.str.strip())

same_phone = df[
    (df["phone_number_1"] != "") &
    (df["phone_number_1"] == df["phone_number_2"])
]

print("Records with same phone_number_1 and phone_number_2:", len(same_phone))

display(same_phone[["url", "name", "phone_number_1", "phone_number_2"]])

KeyError: "None of [Index(['phone_number_1', 'phone_number_2'], dtype='object')] are in the [columns]"

In [67]:
df.scraped_ts.value_counts()

scraped_ts
2026-07-20    2607
2026-07-27     367
Name: count, dtype: int64

In [68]:
df.date.value_counts()

date
2026-07-20    2607
2026-07-27     367
Name: count, dtype: int64

In [69]:
df.iteration_number.value_counts()

iteration_number
20260703    2607
20260704     367
Name: count, dtype: int64

In [72]:
df.category.value_counts()

category
rent    2935
sale      39
Name: count, dtype: int64

In [30]:
df[df.currency == "AED"]

,reference_number,url,broker_display_name,broker,category,category_url,title,description,location,price,currency,price_per,bedrooms,bathrooms,furnished,rera_permit_number,dtcm_licence,scraped_ts,amenities,details,agent_name,number_of_photos,phone_number,user_id,date,iteration_number,sub_category_1,sub_category_2,property_type,depth,last_update,published_at,id
4123,,https://bahrainfinder.bh/ar/property/أرض-للبيع-في-كرانة-3519.html,فجر الخليج العقارية,فجر الخليج العقارية,sale,https://bahrainfinder.bh/en/for-sale/,أرض سكنية للبيع,"أرض سكنية للبيع في كرانهبتصنيف RB (مناطق السكن الخاص (ب))تقع على شارع واحدمساحة أرض 312.9 متر مربعبسعر 31.77د.ب لكل قدم مربعالسعر الإجمالي 107,003.266د.ب قابل للتفاوض",كرانة,"107,003",AED,,,,,,,2026-07-27,,312.9 م²,حسين الخياط,1,+97338100114,,2026-07-27,20260704,سكنية,,أرض,,2026-06-14,2025-02-02,18d0227a284a4dd1f27715facce65b1f

In [4]:
df.furnished.value_counts()

furnished
No     191168
Yes     43079
Name: count, dtype: int64

In [ ]:
import pandas as pd

for col in df.columns:
    print("\n" + "="*80)
    print(f"Column: {col}")
    print("="*80)

    value_counts = (
        df[col]
        .fillna("<NULL>")        # Show nulls explicitly
        .astype(str)
        .value_counts(dropna=False)
    )

    print(value_counts)

In [ ]:
df.scraped_ts.value_counts()

scraped_ts
2026-07-27    109714
2026-07-26     91308
2026-07-25     33225
Name: count, dtype: int64

:

In [3]:
df.date.value_counts()

date
2026-07-27    109714
2026-07-26     91308
2026-07-25     33225
Name: count, dtype: int64

In [ ]:
df.published_at.value_counts()

published_at
2026-07-13    26445
2026-07-06    26319
2026-06-29    23844
2026-07-12    22644
2026-07-05    15626
2026-07-20    15087
2026-07-19    14886
2026-06-28    13025
2026-07-22    10499
2026-07-21     9790
2026-07-23     7126
2026-07-11     6593
2026-07-25     5823
2026-06-27     5436
2026-07-18     4937
2026-07-04     3813
2026-07-24     3797
2026-07-27     3394
2026-07-26     3246
2026-06-26     2961
2026-04-27     2030
2026-05-27     1787
2026-04-26     1250
2026-05-26      985
2026-03-27      663
2026-06-25      454
2026-03-26      349
2026-04-25      329
2026-05-25      327
2024-07-27      113
2025-12-27       74
2024-07-26       66
2025-07-27       60
2025-07-26       55
2026-02-27       50
2025-08-26       44
2026-03-25       42
2026-02-26       33
2025-12-26       32
2025-10-27       30
2025-08-27       29
2025-09-26       25
2025-07-25       21
2026-01-26       16
2025-11-26       15
2025-09-27       12
2025-10-26       10
2026-01-27        9
2025-12-25        9
2024-07-25        8
2026-02-25        8
2025-11-27        6
2025-09-25        5
2026-01-25        3
2023-07-26        3
2025-11-25        2
2023-07-25        1
2023-07-27        1
Name: count, dtype: int64

:

In [37]:
df.depth.value_counts()

depth
            4576
Featured      40
مميّز          1
Name: count, dtype: int64

In [38]:
df.dtypes

reference_number               object
url                            object
broker_display_name            object
broker                         object
category                       object
category_url                   object
title                          object
description                    object
location                       object
price                          object
currency                       object
price_per                      object
bedrooms                       object
bathrooms                      object
furnished                      object
rera_permit_number             object
dtcm_licence                   object
scraped_ts                     object
amenities                      object
details                        object
agent_name                     object
number_of_photos                int64
phone_number                   object
user_id                        object
date                   datetime64[ns]
iteration_number                int64
sub_category_1                 object
sub_category_2                 object
property_type                  object
depth                          object
last_update                    object
published_at           datetime64[ns]
id                             object
dtype: object

In [21]:
import re
import pandas as pd

issues = []

for col in df.columns:

    s = df[col].fillna("").astype(str)

    # Check leading, trailing, multiple spaces, tab, newline
    mask = (
        s.str.contains(r"^\s", regex=True) |
        s.str.contains(r"\s$", regex=True) |
        s.str.contains(r" {2,}", regex=True) |
        s.str.contains(r"\t", regex=True) |
        s.str.contains(r"\n", regex=True) |
        s.str.contains(r"\r", regex=True)
    )

    # Only the first issue from each field
    if mask.any():
        idx = df.index[mask][0]

        issues.append({
            "record_no": idx + 1,
            "url": df.loc[idx, "url"],
            "issue_field": col
        })

result = pd.DataFrame(issues)

print("Fields with whitespace issues:", len(result))
print(result.to_string(index=False))

Fields with whitespace issues: 4
 record_no                                                                                                                                                                                                                                                                                url         issue_field
       425                                                                                                                              https://www.dubizzle.com.bh/en/ad/%D8%B4%D9%82%D9%87-%D9%85%D9%81%D8%B1%D9%88%D8%B4%D8%A9-%D9%84%D9%84%D8%A7%D9%8A%D8%AC%D8%A7%D8%B1-ID105759706.html broker_display_name
       425                                                                                                                              https://www.dubizzle.com.bh/en/ad/%D8%B4%D9%82%D9%87-%D9%85%D9%81%D8%B1%D9%88%D8%B4%D8%A9-%D9%84%D9%84%D8%A7%D9%8A%D8%AC%D8%A7%D8%B1-ID105759706.html              broker
        11 https://www.dubizzle.com.bh/en/ad/%D8%B4%D9%82%D9%87-%D9%85%D8%B1%D8%AA%D8%A8%D9%87-%D9%81%D9%8A-%D8%A7%D9%84%D8%AD%D8%AC%D9%8A%D8%A7%D8%AA-%D8%AB%D9%84%D8%A7%D8%AB-%D8%BA%D8%B1%D9%81-%D8%B4%D8%A7%D9%85%D9%84-%D8%A7%D9%84%D9%83%D9%87%D8%B1%D8%A8%D8%A7%D8%A1-ID105758157.html               title
         5                                                                                                                                                                  https://www.dubizzle.com.bh/en/ad/spacious-2bhk-flat-available-for-rent-in-prime-location-galali-ID105761729.html         description

In [30]:
df.number_of_photos.value_counts()

number_of_photos
3      55096
1      34356
4      31487
5      26858
6      22493
2      19325
7      16996
8      13950
9      12050
10     11748
11      7083
12      6947
13      3203
14      2881
15      2180
16      1676
        1278
18      1235
17      1094
20       991
19       622
24       569
21       480
22       364
23       326
25       284
36       281
30       265
28       222
27       203
26       201
40       155
32       131
29       117
33        99
35        97
37        85
31        82
38        62
34        60
48        50
39        45
42        45
50        37
45        35
44        30
49        27
41        25
54        21
46        19
47        14
60        14
55        14
70        13
43        13
52        12
65        12
72        12
56        11
57        10
63         9
90         9
80         8
51         8
53         8
64         8
67         7
58         6
59         5
84         5
100        5
81         5
66         5
68         4
135        4
61         4
77         4
75         4
98         3
96         3
112        3
140        3
91         3
99         3
102        2
234        2
85         2
71         2
105        2
104        2
88         2
171        2
69         2
95         1
146        1
97         1
644        1
150        1
136        1
156        1
351        1
89         1
82         1
410        1
242        1
264        1
288        1
121        1
200        1
128        1
187        1
125        1
117        1
132        1
191        1
494        1
256        1
101        1
160        1
62         1
153        1
130        1
181        1
120        1
76         1
126        1
110        1
138        1
Name: count, dtype: int64

In [29]:
df[df.bathrooms== "2.5"].url

81219    https://aqarmap.com.eg/en/listing/7155474-for-sale-cairo-dokki-mydn-lmsh-almosekar-ali-ismail-st/
Name: url, dtype: object