In [1]:
import pandas as pd
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option("display.max_colwidth", None)

In [2]:
df= pd.read_csv(r'/home/user/Documents/blinkit_2026_07_31.csv',  low_memory=False)

In [3]:
df.shape

(1627680, 31)

In [4]:
df.head()

,crawl_date_and_time,platform_name,store_id,store_name_location,city,pin_code,unique_id,product_id_upc_ean,department,category,sub_category,product_type,brand_name,product_name,product_description,product_grammage,package_type,net_quantity,variants,item_mrp,item_selling_price,out_of_stock_flag,discount_flag,product_price,unit_price,promo_offer_description,promo_offer_price,discount_in_percent,stock_count,product_url,product_image_urls
0,2026-07-31 00:05:01,Blinkit,33317,NaN,Chennai,600100,717442,717442,"Atta, Rice & Dal","Atta, Rice & Dal",Fresh Atta,NaN,MillD,Milld High Protein Atta,NaN,1 kg,NaN,NaN,NaN,299,249,Yes,No,249,NaN,No offer,249,0,0,https://blinkit.com/prn/milld-high-protein-atta/prid/717442,NaN
1,2026-07-31 00:05:01,Blinkit,39054,NaN,Guwahati,781036,15481,15481,"Atta, Rice & Dal","Atta, Rice & Dal",Atta,NaN,Aashirvaad,"Aashirvaad Shudh Chakki Atta (100% Atta, 0% Maida)",NaN,1 kg,NaN,NaN,"['10 kg', '1 kg']",60,60,No,No,60,NaN,No offer,60,0,50,https://blinkit.com/prn/aashirvaad-shudh-chakki-atta-100%25-atta%2C-0%25-maida/prid/15481,NaN
2,2026-07-31 00:05:01,Blinkit,33317,NaN,Chennai,600100,734829,734829,"Atta, Rice & Dal","Atta, Rice & Dal",Fresh Atta,NaN,Nutroactive,Nutroactive Daily Keto Low Carb Atta,NaN,1 kg,NaN,NaN,NaN,399,395,No,No,395,NaN,No offer,395,0,2,https://blinkit.com/prn/nutroactive-daily-keto-low-carb-atta/prid/734829,NaN
3,2026-07-31 00:05:01,Blinkit,39054,NaN,Guwahati,781036,32147,32147,"Atta, Rice & Dal","Atta, Rice & Dal",Atta,NaN,Aashirvaad,Aashirvaad High Fibre Atta with Multigrains - 1 kg (Guti Xoisor Bohubidh),NaN,1 kg,NaN,NaN,"['5 kg', '1 kg']",80,76,No,Yes,76,NaN,5% OFF,76,5,50,https://blinkit.com/prn/aashirvaad-high-fibre-atta-with-multigrains---1-kg-guti-xoisor-bohubidh/prid/32147,NaN
4,2026-07-31 00:05:01,Blinkit,39054,NaN,Guwahati,781036,674714,674714,"Atta, Rice & Dal","Atta, Rice & Dal",Atta,NaN,Aashirvaad,Aashirvaad Boga Atta,NaN,1 kg,NaN,NaN,NaN,50,50,No,No,50,NaN,No offer,50,0,50,https://blinkit.com/prn/aashirvaad-boga-atta/prid/674714,NaN

In [9]:
df.isnull().sum()

crawl_date_and_time              0
platform_name                    0
store_id                         0
store_name_location        1627680
city                             0
pin_code                         0
unique_id                        0
product_id_upc_ean               0
department                       0
category                         0
sub_category                     0
product_type               1627680
brand_name                    2430
product_name                     0
product_description        1627680
product_grammage                 0
package_type               1627680
net_quantity               1627680
variants                   1432177
item_mrp                         0
item_selling_price               0
out_of_stock_flag                0
discount_flag                    0
product_price                    0
unit_price                 1627680
promo_offer_description          0
promo_offer_price                0
discount_in_percent              0
stock_count                      0
product_url                      0
product_image_urls         1627680
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.nunique()

crawl_date_and_time        16141
platform_name                  1
store_id                     219
store_name_location            0
city                          52
pin_code                      97
unique_id                  35159
product_id_upc_ean         35159
department                    10
category                      10
sub_category                 128
product_type                   0
brand_name                  4279
product_name               35300
product_description            0
product_grammage            2113
package_type                   0
net_quantity                   0
variants                    5881
item_mrp                    1426
item_selling_price          2255
out_of_stock_flag              2
discount_flag                  2
product_price               2255
unit_price                     0
promo_offer_description       88
promo_offer_price           2255
discount_in_percent           88
stock_count                   51
product_url                37936
product_image_urls             0
dtype: int64

In [12]:
df.city.value_counts()

city
Bangalore        266902
Delhi            101390
Pune              95458
Gurgaon           90594
Chennai           82706
Kolkata           74712
Hyderabad         72578
Visakhapatnam     52219
Ahmedabad         45477
Noida             40752
Indore            40002
Agra              35443
Jaipur            30581
Vadodara          29842
Guwahati          29013
Coimbatore        22935
Faridabad         21992
Mumbai            19170
Ghaziabad         19135
Howrah            17795
Mysuru            17357
Amritsar          16595
Burdwan           16544
Lucknow           16050
Jind              15577
Moradabad         15434
Jalandhar         15139
Dehradun          15071
Prayagraj         14700
Bhopal            14438
Kota              14362
Nizamabad         14336
Vijayawada        14258
Asansol           14187
Pinjore           13999
Rampur            13843
Jalgaon           13763
Ranchi            13752
Jabalpur          13675
Hubballi          13269
Bharatpur         13031
Gaya              12741
Mohali            12580
Vapi              12357
Siliguri          12257
Palanpur          11993
Roorkee           11976
Gandhidham        11543
Jaunpur           11240
Rajkot            11195
Trivandrum        11167
Bettiah           10555
Name: count, dtype: int64

In [13]:
import pandas as pd

# Missing product_grammage
grammage_missing = (
    df["product_grammage"].isna() |
    (df["product_grammage"].astype(str).str.strip() == "")
)

# net_quantity contains a measurement inside parentheses
pattern = r"\(\s*[\d.,]+\s*(g|kg|mg|ml|l)\s*(?:or\s*[\d.,]+\s*(g|kg|mg|ml|l))?(?:\s*\+\s*[\d.,]+\s*(g|kg|mg|ml|l))*\s*\)"

mask = df["net_quantity"].fillna("").str.contains(
    pattern,
    case=False,
    regex=True,
    na=False
)

issues = df[grammage_missing & mask]

print("Rows found:", len(issues))

issues[[
    "unique_id",
    "product_name",
    "net_quantity",
    "product_grammage"
]]

/tmp/ipykernel_19911/5463894.py:12: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  mask = df["net_quantity"].fillna("").str.contains(

Rows found: 0

Empty DataFrame
Columns: [unique_id, product_name, net_quantity, product_grammage]
Index: []

In [14]:
city_department = pd.crosstab(df["city"], df["department"])

city_department

department,"Atta, Rice & Dal",Baby Care,Bakery & Biscuits,Beauty & Cosmetics,Cold Drinks & Juices,Dairy & Breakfast,Munchies,Organic & Premium,Personal Care,Sweet Tooth
city,,,,,,,,,,
Agra,1579,2411,2124,8926,2486,2224,3314,1673,7454,3252
Ahmedabad,1787,2759,2589,12128,3185,2950,4497,1963,9474,4145
Amritsar,733,1020,1071,3820,1242,1131,1603,777,3611,1587
Asansol,575,567,927,3691,1051,820,1366,726,3004,1460
Bangalore,12107,15911,17128,64048,19825,19467,26368,13956,51092,27000
Bettiah,455,437,775,2289,823,743,1180,470,2338,1045
Bharatpur,640,519,923,2940,1016,918,1405,697,2555,1418
Bhopal,593,815,861,3827,993,910,1452,614,3100,1273
Burdwan,670,799,1094,4355,1131,1063,1578,859,3396,1599
Chennai,3113,5140,4977,21469,5946,5485,7873,3721,16933,8049
Coimbatore,972,811,1567,5226,1872,1544,2543,1074,4844,2482
Dehradun,641,904,893,3970,1096,950,1421,705,3184,1307
Delhi,4751,6518,6612,23898,7664,7673,9559,5149,19461,10105
Faridabad,1006,1504,1523,4815,1687,1685,2005,1166,4421,2180
Gandhidham,545,409,749,2543,926,757,1377,543,2494,1200
Gaya,482,598,824,3147,917,787,1314,537,2900,1235
Ghaziabad,850,1305,1263,4252,1472,1483,1760,935,3756,2059
Gurgaon,4231,5816,5756,21643,6766,6706,8347,4690,17644,8995
Guwahati,1124,1752,1703,7915,1922,1667,2710,1340,6491,2389
Howrah,705,1084,1106,4861,1140,1169,1607,866,3659,1598
Hubballi,517,794,803,3174,999,842,1405,673,2920,1142
Hyderabad,2962,3984,4527,18993,5260,5097,6995,3407,14149,7204
Indore,1631,2229,2472,10231,2771,2523,4084,1754,8591,3716
Jabalpur,558,822,796,3589,943,800,1422,602,2970,1173
Jaipur,1171,1673,1783,8222,2179,2036,2780,1277,6436,3024
Jalandhar,673,806,955,3970,1097,1029,1451,669,3149,1340
Jalgaon,627,588,894,3270,1108,841,1592,687,2809,1347
Jaunpur,514,481,725,2668,839,732,1197,521,2451,1112
Jind,743,636,1129,3493,1255,1222,1570,839,3015,1675
Kolkata,2888,4198,4830,19312,5066,4968,6745,3763,15599,7343
Kota,546,816,856,3855,1012,853,1364,610,3135,1315
Lucknow,678,993,969,4304,1120,1063,1455,712,3358,1398
Mohali,651,463,933,2687,1001,984,1403,610,2573,1275
Moradabad,689,645,926,4202,1169,952,1524,746,2961,1620
Mumbai,857,1101,1194,5012,1429,1370,1911,957,3578,1761
Mysuru,586,1000,900,4278,1292,1254,1774,909,3622,1742
Nizamabad,677,636,998,3241,1134,993,1533,761,2868,1495
Noida,1876,2432,2519,10351,2946,3021,3771,2022,7947,3867
Palanpur,562,527,727,2892,939,790,1356,562,2445,1193
Pinjore,668,618,1003,3068,1098,1023,1468,676,2929,1448
Prayagraj,637,883,831,4006,967,890,1406,658,3178,1244
Pune,4053,6057,5519,24990,7133,6473,9322,4445,18687,8779
Rajkot,510,397,727,2366,925,752,1374,486,2468,1190
Rampur,601,580,927,3441,1125,872,1453,631,2649,1564
Ranchi,489,725,815,3915,935,777,1301,575,2976,1244
Roorkee,568,398,845,2611,946,820,1360,597,2485,1346
Siliguri,562,543,883,2801,958,794,1336,650,2649,1081
Trivandrum,506,497,766,2379,892,758,1265,520,2469,1115
Vadodara,1179,1723,1759,7978,2084,1952,3057,1226,6211,2673
Vapi,521,563,826,2783,987,771,1433,611,2628,1234
Vijayawada,564,777,861,3819,1018,853,1418,651,3069,1228
Visakhapatnam,2162,2685,3354,12747,3848,3378,5456,2475,11056,5058

In [15]:
### city wise category distribution
city_category = pd.crosstab(df["city"], df["category"])

# Cities where any category is missing
missing_categories = city_category[city_category.eq(0).any(axis=1)]

missing_categories

Empty DataFrame
Columns: [Atta, Rice & Dal, Baby Care, Bakery & Biscuits, Beauty & Cosmetics, Cold Drinks & Juices, Dairy & Breakfast, Munchies, Organic & Premium, Personal Care, Sweet Tooth]
Index: []

In [16]:
dept_category = (
    df.groupby("department")["category"]
    .apply(lambda x: sorted(x.unique()))
    .reset_index()
)

dept_category

             department                category
0      Atta, Rice & Dal      [Atta, Rice & Dal]
1             Baby Care             [Baby Care]
2     Bakery & Biscuits     [Bakery & Biscuits]
3    Beauty & Cosmetics    [Beauty & Cosmetics]
4  Cold Drinks & Juices  [Cold Drinks & Juices]
5     Dairy & Breakfast     [Dairy & Breakfast]
6              Munchies              [Munchies]
7     Organic & Premium     [Organic & Premium]
8         Personal Care         [Personal Care]
9           Sweet Tooth           [Sweet Tooth]

In [3]:
master = df[["department", "category"]].drop_duplicates()
city_stock = (
    df.groupby("city")["out_of_stock_flag"]
    .value_counts()
    .unstack(fill_value=0)
)

city_stock["Total"] = city_stock.sum(axis=1)
city_stock["Out_of_stock_%"] = (
    city_stock["Yes"] / city_stock["Total"] * 100
).round(2)

city_stock.sort_values("Out_of_stock_%", ascending=False)

out_of_stock_flag      No    Yes   Total  Out_of_stock_%
city
Moradabad            7903   7531   15434           48.79
Asansol              9943   4244   14187           29.91
Vadodara            21090   8752   29842           29.33
Burdwan             11794   4750   16544           28.71
Pinjore             10018   3981   13999           28.44
Coimbatore          16554   6381   22935           27.82
Amritsar            12128   4467   16595           26.92
Vijayawada          10458   3800   14258           26.65
Vapi                 9074   3283   12357           26.57
Ahmedabad           33573  11904   45477           26.18
Hyderabad           53601  18977   72578           26.15
Jaipur              22717   7864   30581           25.72
Gaya                 9563   3178   12741           24.94
Kolkata             56156  18556   74712           24.84
Ranchi              10367   3385   13752           24.61
Gandhidham           8925   2618   11543           22.68
Faridabad           17023   4969   21992           22.59
Guwahati            22508   6505   29013           22.42
Jaunpur              8735   2505   11240           22.29
Gurgaon             70412  20182   90594           22.28
Rajkot               8736   2459   11195           21.97
Jalandhar           11827   3312   15139           21.88
Delhi               80042  21348  101390           21.06
Mysuru              13765   3592   17357           20.69
Mumbai              15301   3869   19170           20.18
Nizamabad           11446   2890   14336           20.16
Noida               32612   8140   40752           19.97
Chennai             66213  16493   82706           19.94
Jind                12558   3019   15577           19.38
Indore              32400   7602   40002           19.00
Siliguri             9942   2315   12257           18.89
Kota                11652   2710   14362           18.87
Mohali              10213   2367   12580           18.82
Pune                77851  17607   95458           18.44
Jabalpur            11172   2503   13675           18.30
Jalgaon             11258   2505   13763           18.20
Bangalore          218467  48435  266902           18.15
Visakhapatnam       42768   9451   52219           18.10
Lucknow             13160   2890   16050           18.01
Rampur              11425   2418   13843           17.47
Prayagraj           12177   2523   14700           17.16
Palanpur             9945   2048   11993           17.08
Bhopal              12109   2329   14438           16.13
Trivandrum           9439   1728   11167           15.47
Howrah              15080   2715   17795           15.26
Hubballi            11367   1902   13269           14.33
Dehradun            13015   2056   15071           13.64
Roorkee             10416   1560   11976           13.03
Bettiah              9189   1366   10555           12.94
Agra                31163   4280   35443           12.08
Ghaziabad           16896   2239   19135           11.70
Bharatpur           11963   1068   13031            8.20

In [4]:
dept_stock = (
    df.groupby("department")["out_of_stock_flag"]
    .value_counts()
    .unstack(fill_value=0)
)

dept_stock["Total"] = dept_stock.sum(axis=1)
dept_stock["Out_of_stock_%"] = (
    dept_stock["Yes"] / dept_stock["Total"] * 100
).round(2)

dept_stock.sort_values("Out_of_stock_%", ascending=False)

out_of_stock_flag         No    Yes   Total  Out_of_stock_%
department
Baby Care              69839  22510   92349           24.37
Bakery & Biscuits      78035  24482  102517           23.88
Dairy & Breakfast      86389  25226  111615           22.60
Sweet Tooth           122826  35498  158324           22.42
Beauty & Cosmetics    316976  87435  404411           21.62
Cold Drinks & Juices   94606  25029  119635           20.92
Munchies              129284  30976  160260           19.33
Organic & Premium      63812  14931   78743           18.96
Atta, Rice & Dal       56958  13027   69985           18.61
Personal Care         269384  60457  329841           18.33

In [19]:

cat_stock = (
    df.groupby("category")["out_of_stock_flag"]
    .value_counts()
    .unstack(fill_value=0)
)

cat_stock["Total"] = cat_stock.sum(axis=1)
cat_stock["Out_of_stock_%"] = (
    cat_stock["Yes"] / cat_stock["Total"] * 100
).round(2)

cat_stock.sort_values("Out_of_stock_%", ascending=False)

out_of_stock_flag         No    Yes   Total  Out_of_stock_%
category
Baby Care              69839  22510   92349           24.37
Bakery & Biscuits      78035  24482  102517           23.88
Dairy & Breakfast      86389  25226  111615           22.60
Sweet Tooth           122826  35498  158324           22.42
Beauty & Cosmetics    316976  87435  404411           21.62
Cold Drinks & Juices   94606  25029  119635           20.92
Munchies              129284  30976  160260           19.33
Organic & Premium      63812  14931   78743           18.96
Atta, Rice & Dal       56958  13027   69985           18.61
Personal Care         269384  60457  329841           18.33

In [5]:
df.columns

Index(['crawl_date_and_time', 'platform_name', 'store_id',
       'store_name_location', 'city', 'pin_code', 'unique_id',
       'product_id_upc_ean', 'department', 'category', 'sub_category',
       'product_type', 'brand_name', 'product_name', 'product_description',
       'product_grammage', 'package_type', 'net_quantity', 'variants',
       'item_mrp', 'item_selling_price', 'out_of_stock_flag', 'discount_flag',
       'product_price', 'unit_price', 'promo_offer_description',
       'promo_offer_price', 'discount_in_percent', 'stock_count',
       'product_url', 'product_image_urls'],
      dtype='object')

In [20]:
df["brand_name"].value_counts()

brand_name
The Baker's Dozen                     22576
Edel                                  19618
Amul                                  18823
RiteBite                              18536
GUBB                                  17884
Whole Farm                            13437
MARS Cosmetics                        13179
Swiss Beauty                          11727
RENEE                                 10856
Vega                                  10189
Organic Tattva                         9683
Faces Canada                           9307
Let's Try                              9226
Mogu Mogu                              8747
Yoga Bar                               8638
Sanfe                                  8608
Mamaearth                              8599
Himalaya                               8550
Lakme                                  8362
L'Oreal Paris                          8131
24 Mantra Organic                      7610
Dove                                   7575
Open Secret                            7272
Colgate                                6850
The Select Aisle                       6665
Dot & Key                              6654
Britannia                              6637
Paper Boat                             6631
Cetaphil                               6559
Nivea                                  6536
4700BC                                 6451
Sweet Karam Coffee                     6236
LuvLap                                 5807
The Whole Truth                        5760
Tata Sampann                           5746
Insight Cosmetics                      5741
Dettol                                 5646
MCaffeine                              5630
Kimirica                               5433
Minimalist                             5249
Sugar Pop                              5245
Epigamia                               5244
Haldiram's                             5131
Raw Pressery                           5046
Parachute Advansed                     4962
Biotique                               4889
Gleva                                  4807
SuperYou                               4790
Karachi Bakery                         4604
Loacker                                4567
GO DESi                                4538
Chheda's                               4514
Unibic                                 4492
Plum                                   4465
Maybelline New York                    4436
Phab                                   4409
Farmley                                4393
The Body Shop                          4385
Dabur                                  4342
Puramate                               4337
Ajmal                                  4333
Plum BodyLovin'                        4322
Natureland Organics                    4316
Slurrp Farm                            4300
Fiama                                  4288
True Elements                          4193
Carlton London                         4189
Too Yumm                               4146
Hershey's                              4144
Elle 18                                4139
KLOY                                   4112
Miss Nails                             4064
Vaseline                               4050
Crax                                   4011
The Derma Co                           3977
Foxtale                                3939
Kellogg's                              3911
Pilgrim                                3891
Vembley                                3882
Engage                                 3862
Skinn by Titan                         3835
Sebamed                                3834
Mother Dairy                           3813
Jimmy's                                3719
Hyphen                                 3614
Just Herbs                             3526
Lay's                                  3524
WishCare                               3517
Awsum                                  3493
Bronson Professional                   3418
Bikano                                 3408
The Face Shop                          3394
Bauli                                  3365
Patanjali                              3338
Mother Sparsh                          3290
Beauté Secrets                         3283
Nua                                    3236
Kettle Studio                          3234
Indus Valley                           3231
Winkies                                3229
Gillette                               3210
Parle                                  3208
Whole Farm Grocery                     3200
Safe Harvest                           3163
Coca-Cola                              3154
Park Avenue                            3148
Jabsons                                3102
Tiffany                                3085
Bare Anatomy                           3082
Pond's                                 3070
Soulflower                             3062
Oyo Baby                               3024
Bikaji                                 3023
Lo Foods                               3006
O3+                                    2983
Haus & Kinder                          2975
Saffola                                2931
Whisper                                2914
Blue Heaven                            2902
Fanta                                  2883
Bombay Shaving Company                 2874
Dobra                                  2803
Lux                                    2792
Mee Mee                                2788
Protein Chef                           2772
Fortune                                2741
Pee Safe                               2724
Bella Vita Organic                     2708
Tata Soulfull                          2708
Veet                                   2694
Cadbury Dairy Milk Silk                2690
Daawat                                 2663
L'Oréal Professionnel                  2661
Philips                                2641
Sunfeast Dark Fantasy                  2638
Beardo                                 2630
Moxie Beauty                           2614
Cerrito                                2613
Plush                                  2604
MomsHome                               2577
Cornitos                               2570
Johnson's                              2568
Bla Bli Blu                            2566
Oreo                                   2554
Be Bodywise                            2528
Kidology                               2504
Multibrite                             2499
Tresemme                               2499
Revlon                                 2480
Pintola                                2470
Haldiram's Nagpur                      2464
Philips Avent                          2461
India Gate                             2443
Paradyes                               2440
Mr. Makhana                            2436
Pepsi                                  2431
La French                              2431
Oral-B                                 2422
Pears                                  2400
Plix                                   2396
Lotus Herbals                          2390
Lal                                    2374
Bella Vita                             2368
Pep Nails                              2364
Earth Rhythm                           2354
Monster                                2346
Lacto Calamine                         2346
Pampers                                2333
Guess                                  2331
English Oven                           2309
Daadi's                                2298
Rajdhani                               2293
Chemist At Play                        2278
Cookieman                              2267
Chicco                                 2264
Palmolive                              2264
Joy                                    2245
CeraVe                                 2238
Bath & Body Works                      2234
Cinthol                                2214
BBlunt                                 2187
Khadi Natural                          2178
Nivea Men                              2178
Lotte                                  2156
Nat Habit                              2144
Impact                                 2144
Act II                                 2140
Bingo                                  2134
Santoor                                2134
Yu                                     2134
Eat Better Co                          2126
Sugar                                  2126
Pro Nature                             2106
Aashirvaad                             2097
Coolberg                               2085
Victoria's Secret                      2082
Sapphire                               2058
Streax                                 2039
Perfora                                2016
Denver                                 2012
Arata                                  1986
Coco Crush                             1985
Real                                   1983
MTR                                    1981
Fastrack                               1978
Theobroma                              1970
Milky Mist                             1959
Staze                                  1948
Sirona                                 1916
Bagrry's                               1915
Aqualogica                             1915
Nestle Cerelac                         1915
Conscious Food                         1903
Lakme 9To5                             1901
Huggies                                1898
Urban Platter                          1896
Jovees Herbal                          1895
Chandan                                1892
Head & Shoulders                       1872
Cream Bell                             1854
Nuluv                                  1852
The Cinnamon Kitchen                   1848
Medimix                                1847
Happilo                                1846
Beyond Snack                           1841
Wild Stone                             1840
Sensodyne                              1831
Amul Kool                              1829
MamyPoko Pants                         1818
D'lecta                                1817
Jaguar                                 1814
Everyuth                               1813
Amul Gold                              1805
Baskin Robbins                         1804
Havmor                                 1802
Cavin's                                1801
Garnier                                1797
Red Bull                               1787
Conscious Chemist                      1783
Britannia Treat                        1782
ENN                                    1771
Shanya                                 1755
Trident                                1751
Mirada                                 1750
MOM                                    1744
O.P.I                                  1742
Sepoy & Co.                            1741
Abbie's                                1738
Carmesi                                1727
The Health Factory                     1725
Tong Garden                            1709
Stayfree                               1705
VLCC                                   1700
Kab's Jackpot                          1694
Anveshan                               1691
Two Brothers                           1686
Beanly                                 1682
Lindt Lindor                           1680
Kwality Wall's                         1673
Yardley                                1668
Orion                                  1666
iD                                     1663
MyFitness                              1645
St. D'Vence                            1642
Azah                                   1641
Go Zero                                1613
American Garden                        1601
Mila Beauté                            1598
Aveeno                                 1587
Cadbury Dairy Milk                     1581
PHC                                    1564
Stroom                                 1556
McVitie's                              1549
Pocky                                  1549
Nautica                                1538
A TATA Product - Organic India         1535
Avolt                                  1524
The Wellness Shop                      1520
Real Activ                             1516
Bombae                                 1514
Praakritik                             1506
LoveChild Masaba                       1489
Elite                                  1488
Nescafe                                1486
Nova Nova                              1476
Re' Equil                              1474
Sofy                                   1459
Amul Tru                               1454
The Man Company                        1453
Babique                                1450
Adidas                                 1437
Delfi                                  1435
Dukes Waffy                            1429
Laneige                                1429
Taali                                  1428
O'cean                                 1424
Hair Drama Co.                         1424
Charliee                               1421
Namyaa                                 1421
Modern Kitchens                        1421
Modern                                 1419
Vadilal                                1417
True Story                             1412
Whimsy                                 1401
Kwality                                1394
Pringles                               1391
Britannia NutriChoice                  1386
Schweppes                              1378
Hershey's Kisses                       1375
Yellow Diamond                         1371
Sprite                                 1364
Quench                                 1363
Sleepy Owl                             1356
Axe                                    1353
Sunfeast Baked Creations               1353
Gillette Venus                         1349
Fix My Curls                           1334
Bumtum                                 1333
Harveys                                1331
Fogg                                   1328
Gush Beauty                            1328
FURR                                   1321
Forest Essentials                      1312
Tuco Kids                              1312
Alpenliebe                             1309
Real Thai                              1307
Neutrogena                             1298
Weikfield                              1293
Wazdorf                                1292
Bioderma                               1292
Schwarzkopf                            1291
Doritos                                1290
Bartisans                              1284
Mancode                                1282
Little's                               1282
FAE Beauty                             1278
B Natural                              1277
Davidoff                               1263
R for Rabbit                           1258
Dermatouch                             1245
Balaji                                 1236
Kapiva                                 1226
Mothercare                             1225
Ramji                                  1219
Hocco                                  1217
Deconstruct                            1214
French Essence                         1213
Mother's Recipe                        1208
Troovy                                 1196
Godrej No.1                            1181
Mimo                                   1162
Noor Skincare                          1160
Gits                                   1155
Typsy Beauty                           1154
Fast&Up                                1150
Dr. Sheth's                            1146
StarAndDaisy                           1146
Fixderma                               1143
Makeup Revolution                      1142
Amul Kool Cafe                         1140
Prolume                                1137
Wonderland Foods                       1132
Glucon-D                               1129
SkinSide                               1129
7UP                                    1125
Pansari                                1124
Wild Oak                               1124
KitKat Delights                        1122
Nature Vit                             1122
Hide & Seek                            1121
Schwarzkopf Professional               1119
Snickers                               1118
Pigeon Baby                            1106
Cheetos                                1105
Moi Soi                                1100
Fabelle                                1092
Aroma Magic                            1092
Wella Professionals                    1088
Zeyu                                   1087
Ritebite Max Protein Roots             1081
Majestique                             1076
NIC                                    1074
Urban Yog                              1073
Toyshine                               1070
Niine                                  1070
BabyPro                                1067
Sattviko                               1063
Chupa Chups                            1063
Rexona                                 1060
Anand                                  1059
Get-A-Way                              1058
Nutella                                1057
Snackible                              1056
Sunsilk                                1054
Nestle KitKat                          1048
Garnier Skin Naturals                  1045
Skippi                                 1041
Moody                                  1038
Mannlich                               1038
Smoodh                                 1037
Pluckk                                 1034
Livon                                  1032
Dimpy Stuff                            1031
Bisleri                                1030
Tipsy Tiger                            1026
Poko Loko                              1023
Ustraa                                 1021
Venusia                                1020
Doctor's Choice                        1020
Bombay Banta                           1018
Britannia Good Day                     1000
Navratna                                995
Organic Box                             994
Little Joys                             989
Wow Skin Science                        988
Raw Alchemy                             981
Dairy Day                               977
Love Beauty & Planet                    976
Dermicool                               976
Fine Touch                              976
Tang                                    974
Sundrop                                 974
Mangat Ram                              972
United Colors Of Benetton               970
Twinings                                970
Sotrue                                  969
Nongshim                                962
Manna                                   956
Nutty Gritties                          944
Naturali                                944
Imfresh                                 941
UrbanGabru                              940
Colorbar                                939
Supply6                                 939
EAT Anytime                             937
Sunfeast Farmlite                       931
Pantene                                 927
Listerine                               927
FruBon                                  920
Mentos                                  918
Daily life FOREVER52                    916
Tattvalogy                              916
Prasuma                                 911
Arun                                    911
Giggles                                 910
SuperBottoms                            908
Ferrero Rocher                          907
Unibic Swaadesi                         906
Derm Ease                               898
Villain                                 897
ETUDE                                   896
Mysore Sandal                           891
Cadbury Celebrations                    890
Matrix                                  889

In [21]:
brand_summary = (
    df.groupby("brand_name", dropna=False)
      .agg(
          total_rows=("brand_name", "size"),
          unique_products=("unique_id", "nunique"),
          unique_urls=("product_url", "nunique"),
          unique_product_names=("product_name", "nunique"),
          unique_categories=("category", "nunique"),
          unique_departments=("department", "nunique"),
          unique_cities=("city", "nunique"),
          urls=("product_url", lambda x: sorted(set(x.dropna()))),
          product_names=("product_name", lambda x: sorted(set(x.dropna()))),
          categories=("category", lambda x: sorted(set(x.dropna()))),
          departments=("department", lambda x: sorted(set(x.dropna())))
      )
      .reset_index()
      .sort_values("total_rows", ascending=False)
)

brand_summary.head()

             brand_name  total_rows  unique_products  unique_urls  \
3739  The Baker's Dozen       22576              118          118
1117               Edel       19618              172          172
168                Amul       18823              268          269
3214           RiteBite       18536               95           95
1371               GUBB       17884              204          204

      unique_product_names  unique_categories  unique_departments  \
3739                   115                  5                   5
1117                   167                  1                   1
168                    217                  6                   6
3214                    95                  5                   5
1371                   201                  3                   3

      unique_cities  \
3739             52
1117             52
168              52
3214             52
1371             52

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     urls  \

In [28]:
import re

url_pattern = re.compile(
    r"^https?://[^\s/$.?#].[^\s]*$",
    re.IGNORECASE
)

invalid_urls = df[
    df["product_url"].isna() |
    ~df["product_url"].astype(str).str.match(url_pattern)
]

print(f"Invalid URLs: {len(invalid_urls)}")
print(invalid_urls[["unique_id", "product_url"]])

Invalid URLs: 0
Empty DataFrame
Columns: [unique_id, product_url]
Index: []

In [23]:
store_oos = (
    df.pivot_table(
        index=["city", "store_id"],
        columns="out_of_stock_flag",
        aggfunc="size",
        fill_value=0
    )
    .reset_index()
)

# Ensure both columns exist
for col in ["Yes", "No"]:
    if col not in store_oos.columns:
        store_oos[col] = 0

store_oos["Total"] = store_oos["Yes"] + store_oos["No"]
store_oos["Out_of_stock_%"] = (
    store_oos["Yes"] / store_oos["Total"] * 100
).round(2)

store_oos = store_oos.sort_values(
    "Out_of_stock_%",
    ascending=False
)

store_oos

out_of_stock_flag           city  store_id     No   Yes  Total  Out_of_stock_%
28                     Bangalore     34752      0     1      1          100.00
177                        Noida     44662      0     1      1          100.00
137                       Jaipur     37028      0     4      4          100.00
25                     Bangalore     34348      1     6      7           85.71
198                         Pune     45923      1     4      5           80.00
115                    Hyderabad     30741   1324  3350   4674           71.67
213                   Vijayawada     35684    813  1744   2557           68.20
139                       Jaipur     39338   1168  1664   2832           58.76
168                       Mysuru     37128    929  1318   2247           58.66
163                    Moradabad     37334   1076  1394   2470           56.44
15                     Bangalore     30248      6     7     13           53.85
208                     Vadodara     36084   1769  1829   3598           50.83
94                       Gurgaon     31719   5657  5101  10758           47.42
164                    Moradabad     41105   6827  6137  12964           47.34
159                      Lucknow     39461    279   237    516           45.93
0                           Agra     33920     50    30     80           37.50
142                       Jaipur     49251   2368  1387   3755           36.94
7                      Ahmedabad     35032    488   270    758           35.62
71                         Delhi     30693  11276  6022  17298           34.81
10                     Ahmedabad     42042   2273  1211   3484           34.76
38                     Bangalore     41917   3719  1964   5683           34.56
149                      Kolkata     35122  10278  5353  15631           34.25
175                        Noida     42102   3685  1881   5566           33.79
66                    Coimbatore     35956   7176  3652  10828           33.73
178                        Noida     47300   4202  2128   6330           33.62
20                     Bangalore     30832      2     1      3           33.33
141                       Jaipur     42813      2     1      3           33.33
13                      Amritsar     43639   2410  1203   3613           33.30
118                    Hyderabad     37626   8887  4281  13168           32.51
209                     Vadodara     36676   2603  1224   3827           31.98
121                    Hyderabad     40244   3705  1697   5402           31.41
156                         Kota     46673   2132   972   3104           31.31
165                       Mumbai     35030   3910  1767   5677           31.13
119                    Hyderabad     38474   3679  1626   5305           30.65
103                      Gurgaon     43483    130    57    187           30.48
8                      Ahmedabad     35848   8000  3451  11451           30.14
14                       Asansol     38876   9943  4244  14187           29.91
48                     Bangalore     45758    657   280    937           29.88
110                     Guwahati     46019   2149   900   3049           29.52
90                     Ghaziabad     37288     12     5     17           29.41
195                         Pune     41533   4575  1896   6471           29.30
24                     Bangalore     33509   3790  1540   5330           28.89
56                       Burdwan     37862  11794  4750  16544           28.71
105                     Guwahati     37914     15     6     21           28.57
125                    Hyderabad     46079     30    12     42           28.57
26                     Bangalore     34540     15     6     21           28.57
9                      Ahmedabad     39336   1536   612   2148           28.49
181                      Pinjore     37738  10018  3981  13999           28.44
37                     Bangalore     41096     13     5     18           27.78
147                      Kolkata     32504   4279  1645   5924           27.77
148                      Kolkata     33976  10304  3918  14222           27.55
83                     Faridabad     33682   4896  1846   6742           27.38
16                     Bangalore     30632   4641  1747   6388           27.35
64                       Chennai     45929   4402  1641   6043           27.16
210                     Vadodara     41655   8207  3044  11251           27.06
205                      Roorkee     49141     11     4     15           26.67
130                       Indore     43497   2553   927   3480           26.64
212                         Vapi     45268   9074  3283  12357           26.57
44                     Bangalore     43815   5041  1758   6799           25.86
78                         Delhi     45791   5544  1929   7473           25.81
35                     Bangalore     38212   5788  2006   7794           25.74
113                     Hubballi     38324   2098   724   2822           25.66
6                      Ahmedabad     34112   9218  3146  12364           25.44
12                      Amritsar     32889   9718  3264  12982           25.14
82                         Delhi     46897   5154  1728   6882           25.11
109                     Guwahati     45799   2642   884   3526           25.07
152                      Kolkata     37636      9     3     12           25.00
88                          Gaya     39042   9563  3178  12741           24.94
184                    Prayagraj     47398   3059  1011   4070           24.84
51                     Bangalore     47062   5356  1756   7112           24.69
197                         Pune     45646   4923  1609   6532           24.63
203                       Ranchi     35938  10367  3385  13752           24.61
62                       Chennai     45682   3971  1277   5248           24.33
138                       Jaipur     38880   8766  2799  11565           24.20
39                     Bangalore     42124   5292  1680   6972           24.10
129                       Indore     43487   2706   856   3562           24.03
128                       Indore     40000   9266  2914  12180           23.92
211                     Vadodara     42316   8511  2655  11166           23.78
217                Visakhapatnam     36592  10223  3094  13317           23.23
150                      Kolkata     35886   4089  1237   5326           23.23
61                       Chennai     36371   8732  2626  11358           23.12
87                    Gandhidham     39334   8925  2618  11543           22.68
98                       Gurgaon     34032  11931  3497  15428           22.67
133                     Jabalpur     46677   2225   650   2875           22.61
67                    Coimbatore     36692   9378  2729  12107           22.54
55                        Bhopal     44119   2696   774   3470           22.31
145                      Jaunpur     40963   8735  2505  11240           22.29
43                     Bangalore     43721   9945  2846  12791           22.25
60                       Chennai     35672     14     4     18           22.22
36                     Bangalore     40523     14     4     18           22.22
84                     Faridabad     34836   7764  2212   9976           22.17
106                     Guwahati     39054   8902  2530  11432           22.13
42                     Bangalore     42814   4979  1413   6392           22.11
201                       Rajkot     37804   8736  2459  11195           21.97
143                    Jalandhar     43651  11827  3312  15139           21.88
80                         Delhi     46623   5656  1528   7184           21.27
69                      Dehradun     47041   1885   507   2392           21.20
81                         Delhi     46783   4469  1200   5669           21.17
116                    Hyderabad     30765   5703  1527   7230           21.12
11                     Ahmedabad     43762  12058  3214  15272           21.05
46                     Bangalore     44864     15     4     19           21.05
179                        Noida     47302     15     4     19           21.05
58                       Chennai     31861   9297  2473  11770           21.01
57                       Chennai     31669  10019  2631  12650           20.80
101                      Gurgaon     42460   5935  1538   7473           20.58
122                    Hyderabad     41987   9432  2407  11839           20.33
171                    Nizamabad     42983  11446  2890  14336           20.16
200                         Pune     46683   3338   840   4178           20.11
96                       Gurgaon     33027      4     1      5           20.00
108                     Guwahati     41729   8762  2177  10939           19.90
102                      Gurgaon     42989   6011  1491   7502           19.87
187                         Pune     31214   2304   571   2875           19.86
153                      Kolkata     40767  10434  2554  12988           19.66
112                       Howrah     45476   4434  1081   5515           19.60
191                         Pune     35532   7722  1866   9588           19.46
146                         Jind     39464  12558  3019  15577           19.38
95                       Gurgaon     31967  11919  2785  14704           18.94
206                     Siliguri     45795   9942  2315  12257           18.89
151                      Kolkata     36036  12400  2878  15278           18.84
162                       Mohali     41869  10213  2367  12580           18.82
194                         Pune     41099   2888   661   3549           18.62
32                     Bangalore     36375  11538  2631  14169           18.57
161                      Lucknow     49387   3034   686   3720           18.44
144                      Jalgaon     41517  11258  2505  13763           18.20
154                      Kolkata     46909   4363   968   5331           18.16
185                         Pune     30667  10515  2287  12802           17.86
218                Visakhapatnam     43057  12899  2800  15699           17.84
190                         Pune     33507   9970  2160  12130           17.81
170                       Mysuru     48232   3536   764   4300           17.77
73                         Delhi     38364  11586  2473  14059           17.59
214                   Vijayawada     35686   9645  2056  11701           17.57
193                         Pune     36906   9162  1947  11109           17.53
99                       Gurgaon     34732  11407  2423  13830           17.52
50                     Bangalore     46907  15968  3385  19353           17.49
202                       Rampur     39212  11425  2418  13843           17.47
91                     Ghaziabad     42302    104    22    126           17.46
76                         Delhi     43995  11969  2529  14498           17.44
107                     Guwahati     41165     38     8     46           17.39
30                     Bangalore     35388   6319  1325   7644           17.33
85                     Faridabad     42859   4239   887   5126           17.30
18                     Bangalore     30771  11669  2419  14088           17.17
132                     Jabalpur     41535   8947  1853  10800           17.16
120                    Hyderabad     38646   9266  1917  11183           17.14
180                     Palanpur     45020   9945  2048  11993           17.08
41                     Bangalore     42458  17227  3530  20757           17.01
124                    Hyderabad     42933     15     3     18           16.67
63                       Chennai     45684     60    12     72           16.67
158                      Lucknow     39292   9830  1965  11795           16.66
65                       Chennai     46475  14495  2887  17382           16.61
34                     Bangalore     37424  12268  2402  14670           16.37
134                       Jaipur     31588  10375  2008  12383           16.22
86                     Faridabad     45266    124    24    148           16.22
59                       Chennai     33317  15223  2942  18165           16.20
172                        Noida     35320  12144  2338  14482           16.14
126                       Indore     33205   7422  1423   8845           16.09
100                      Gurgaon     35334  11663  2231  13894           16.06
92                     Ghaziabad     45847   2938   561   3499           16.03
189                         Pune     31486   1233   235   1468           16.01
117                    Hyderabad     31012  10834  2051  12885           15.92
215                Visakhapatnam     36228  10333  1943  12276           15.83
40                     Bangalore     42172     16     3     19           15.79
19                     Bangalore     30788  11774  2194  13968           15.71
33                     Bangalore     36475  11966  2216  14182           15.63
166                       Mumbai     41219  11371  2102  13473           15.60
27                     Bangalore     34734  11366  2099  13465           15.59
199                         Pune     46411   4969   914   5883           15.54
104                      Gurgaon     46421   5752  1058   6810           15.54
207                   Trivandrum     47402   9439  1728  11167           15.47
155                         Kota     35942   9520  1738  11258           15.44
21                     Bangalore     31025  11904  2162  14066           15.37
77                         Delhi     45642    166    30    196           15.31
1                           Agra     34412   5609   991   6600           15.02
3                           Agra     44125   1075   190   1265           15.02
17                     Bangalore     30638  11780  2055  13835           14.85
192                         Pune     35902  10289  1784  12073           14.78
216                Visakhapatnam     36351   9313  1614  10927           14.77
72                         Delhi     36426  12001  2037  14038           14.51
183                    Prayagraj     41551   9097  1512  10609           14.25
54                        Bhopal     35688   9413  1555  10968           14.18
70                      Dehradun     48461   1369   225   1594           14.12
169                       Mysuru     37470   9300  1510  10810           13.97
5                           Agra     49609   4030   644   4674           13.78
31                     Bangalore     35578  11835  1840  13675           13.46
23                     Bangalore     31250  11414  1766  13180           13.40
74                         Delhi     42812  12063  1857  13920           13.34
111                       Howrah     37910  10646  1634  12280           13.31
127                       Indore     36056   9237  1406  10643           13.21
204                      Roorkee     41543  10405  1556  11961           13.01
52                       Bettiah     46187   9189  1366  10555           12.94
45                     Bangalore     44500     27     4     31           12.90
4                           Agra     44371   5423   798   6221           12.83
123                    Hyderabad     42030    726   106    832           12.74
173                        Noida     37812   3987   575   4562           12.60
157                      Lucknow     33676      7     1      8           12.50
174                        Noida     39611   8563  1211   9774           12.39
188                         Pune     31364   5938   833   6771           12.30
68                      Dehradun     35314   9761  1324  11085           11.94
114                     Hubballi     45746   9269  1178  10447           11.28
176                        Noida     44257     16     2     18           11.11
140                       Jaipur     42750      8     1      9           11.11
89                     Ghaziabad     32750  13842  1651  15493           10.66
47                     Bangalore     45342  12073  1379  13452           10.25
2                           Agra     43895  14976  1627  16603            9.80
79                         Delhi     45855    145    15    160            9.38
160                      Lucknow     42815     10     1     11            9.09
53                     Bharatpur     45859  11963  1068  13031            8.20
131                       Indore     49093   1216    76   1292            5.88
22                     Bangalore     31033     33     1     34            2.94
75                         Delhi     43365     13     0     13            0.00
29                     Bangalore     34835      7     0      7            0.00
49                     Bangalore     46427      9     0      9            0.00
136                       Jaipur     36353     20     0     20            0.00
135                       Jaipur     36253     10     0     10            0.00
93                       Gurgaon     31552      1     0      1            0.00
97                       Gurgaon     33541      2     0      2            0.00
186                         Pune     30821     21     0     21            0.00
182                    Prayagraj     41451     21     0     21            0.00
167                       Mumbai     47776     20     0     20            0.00
196                         Pune     45270      3     0      3            0.00

In [24]:
import pandas as pd

# Ensure stock_count is numeric
df["stock_count"] = pd.to_numeric(df["stock_count"], errors="coerce")

# Normalize out_of_stock_flag
flag = df["out_of_stock_flag"].astype(str).str.strip().str.lower()

# 1. out_of_stock_flag = Yes, but stock_count > 0
yes_stock_gt0 = df[
    (flag == "yes") &
    (df["stock_count"] > 0)
]

print(f"Rows with out_of_stock_flag='Yes' but stock_count > 0: {len(yes_stock_gt0)}")
print(yes_stock_gt0[["unique_id", "product_name", "store_id", "stock_count", "out_of_stock_flag"]])

# 2. out_of_stock_flag = No, but stock_count = 0
no_stock_0 = df[
    (flag == "no") &
    (df["stock_count"] == 0)
]

print(f"\nRows with out_of_stock_flag='No' but stock_count = 0: {len(no_stock_0)}")
print(no_stock_0[["unique_id", "product_name", "store_id", "stock_count", "out_of_stock_flag"]])

Rows with out_of_stock_flag='Yes' but stock_count > 0: 60
         unique_id  \
35776       764575
40164       721481
46990       721481
234800      710120
242337      498797
290988      635320
294317      762142
295636      742881
295934      548763
297457      610223
297508      735423
297909      709409
298501      806683
299192      769992
299201      791912
299516      973094
299705      791909
300322      788642
300553      791916
306592      569813
308118      717556
324218      512438
328733      642704
329956       21530
407383      677054
517175      541713
542847      541713
603637      241069
610673      745150
666001     1367494
666452      592027
666507     1366121
666509     1361493
726874      542484
909515      668138
909672      548955
912222      544729
912389      745595
912610      668138
912888      605807
914006      539946
935769      548118
948334      793742
950917      506910
953458      501321
1033115     579075
1043841     525100
1045107      74414
1052315      58005
1054901     525100
1055367      74414
1155465     506032
1155488      45655
1214412     759765
1333568      86620
1333772     785519
1540322     731826
1588476     605807
1588745     540182
1591783     540182

                                                                                      product_name  \
35776                                             Pilgrim 25% AHA, 2% BHA, 5% PHA Peeling Solution
40164                                                 Tekcool Derma Roller For Hair & Skin (Black)
46990                                                 Tekcool Derma Roller For Hair & Skin (Black)
234800                                                    Kulsum’s Kaya Kalp Party Glow Facial Kit
242337                                                           Little's Baby Plush Ball (Medium)
290988                                                   Noor Skincare 100% Organic Mulethi Powder
294317                                     Faces Canada Ultime Pro Strobe Makeup Fixer (Rose Gold)
295636                                                   Swiss Beauty Dew It Up Blush (Dusty Pink)
295934                                                Lakme Facelift Foundation Stick (Cool Ivory)
297457                                                     La French Euphoria Unisex Eau de Parfum
297508                                    Bath & Body Works Travel Size Body Mist (Into The Night)
297909   L'Oreal Paris That's So Worth It Lipstick Kit (635 Worth It Medium, 570 Worth It Intense)
298501                                          Kenaz Oud Ameer Eau de Parfum (Saffron, Oud, Rose)
299192                        The Man Company Fragrance Collective Perfume Gift Set (Hope & Black)
299201                                       Skinn by Titan 24Seven Eau de Parfum for Her (Floral)
299516                                                            Axe Eau de Parfum (Midnight Oak)
299705                                                Skinn by Titan 24Seven Eau de Parfum (Woody)
300322                                       Adidas Dynamic Pulse Eau de Toilette (Clean Aromatic)
300553                                           Fastrack Girl Boss Eau de Parfum for Her (Floral)
306592                          Faces Canada Ultime Pro Splash Mini Nail Paint Kit (True Neutrals)
308118                                      Swiss Beauty Satin Comfort Lipstick (03 Roasted Brown)
324218                                                 RENEE Kajal Pen with Sharpener (Hard Black)
328733                                                    Everyuth Naturals Golden Glow Sheet Mask
329956                                                       Pond's BB+ Cream (Ivory, SPF 30 PA++)
407383                                                           Voylla Boho Tribe Anklet (Silver)
517175          MARS Cosmetics Artist's Arsenal Professional Small Blending Eyeshadow Makeup Brush
542847          MARS Cosmetics Artist's Arsenal Professional Small Blending Eyeshadow Makeup Brush
603637                                    Set Wet Cool Avatar Body Spray Perfume & Men's Deodorant
610673                                    Swiss Beauty Moist Heist Tinted Lip Gloss (02 Pink Plan)
666001                                                       Nubilous Bio Collagen Face Sheet Mask
666452                                                 ToyTales Ostrich Hug Plush Stuffed Soft Toy
666507                                           Nubilous 5-in-1 Mini Makeup Brush Set with Mirror
666509                                                                   Nubilous Makeup Brush Set
726874                                     Toyshine Friction Powered Rock Crawler Mini Toy Vehicle
909515                                                                   GUBB Embossed Cotton Pads
909672                                               Quench Matcha Better Bubble Korean Sheet Mask
912222                       MARS Cosmetics Trend Setting Loose Face Powder (01-Matte Translucent)
912389                                           Swiss Beauty Glow Up Strobe Cream (Pink Twilight)
912610                                                                   GUBB Embossed Cotton Pads
912888                                       Staze HD BlendPro Beauty Blender Sponge (01 Teardrop)
914006                                          Swiss Beauty Cheek It Up Blush (Mood Lifter Coral)
935769                                                              Toyshine Baby Squeeze Bath Toy
948334                                           Tanqueray Tonic water Tanqueray Peach Tonic Water
950917                                                 Swiss Beauty Pure Matte Lipstick (Hot Nude)
953458                                                                 Colorbar Nail Paint Remover
1033115                                                              King Krab Spiderman Play Tent
1043841                                                      Vega Compact Pocket Hair Comb (Black)
1045107                                              Vega Round Hair Brush, Hair Volumizer (Black)
1052315                                                                     Woodward's Gripe Water
1054901                                                      Vega Compact Pocket Hair Comb (Black)
1055367                                              Vega Round Hair Brush, Hair Volumizer (Black)
1155465                                                                    Prolyte Nimbu Paani ORS
1155488                                                         Red Bull Energy Drink (4 x 250 ml)
1214412                                                             Vaseline Cherry Blush Lip Balm
1333568                                     L'Oreal Paris New Excellence Hair Colour Creme (Black)
1333772                                                Hell Energy Classic Zero Sugar Energy Drink
1540322                                                 Bare Necessities Luxury Gentleman Gift Set
1588476                                      Staze HD BlendPro Beauty Blender Sponge (01 Teardrop)
1588745                                                           KLOY Hair Scalp Massager (Black)
1591783                                                           KLOY Hair Scalp Massager (Black)

         store_id  stock_count out_of_stock_flag
35776       35334            1               Yes
40164       38212            1               Yes
46990       38212            1               Yes
234800      39338            4               Yes
242337      46907            1               Yes
290988      46907            1               Yes
294317      46907            1               Yes
295636      46907            1               Yes
295934      46907            1               Yes
297457      46907            1               Yes
297508      46907            1               Yes
297909      46907            1               Yes
298501      46907            1               Yes
299192      46907            1               Yes
299201      46907            1               Yes
299516      46907            1               Yes
299705      46907            1               Yes
300322      46907            1               Yes
300553      46907            1               Yes
306592      39042            1               Yes
308118      46907            1               Yes
324218      32889            1               Yes
328733      32889            1               Yes
329956      32889            1               Yes
407383      40244            1               Yes
517175      36692            1               Yes
542847      36692            1               Yes
603637      41987            2               Yes
610673      35314            1               Yes
666001      41533            1               Yes
666452      42812            1               Yes
666507      41533            1               Yes
666509      41533            1               Yes
726874      36056            8               Yes
909515      41105            1               Yes
909672      41105            2               Yes
912222      41105            1               Yes
912389      41105            1               Yes
912610      41105            1               Yes
912888      41105            1               Yes
914006      41105            1               Yes
935769      36228            1               Yes
948334      33682            2               Yes
950917      41105            1               Yes
953458      41105            1               Yes
1033115     45642            1               Yes
1043841     36228            5               Yes
1045107     36228            4               Yes
1052315     43995            1               Yes
1054901     36228            5               Yes
1055367     36228            4               Yes
1155465     30693           50               Yes
1155488     30693            6               Yes
1214412     35578            1               Yes
1333568     37910            1               Yes
1333772     31967            5               Yes
1540322     42460            1               Yes
1588476     41105            1               Yes
1588745     41105            1               Yes
1591783     41105            1               Yes

Rows with out_of_stock_flag='No' but stock_count = 0: 0
Empty DataFrame
Columns: [unique_id, product_name, store_id, stock_count, out_of_stock_flag]
Index: []

In [30]:
df[
    
    (df["store_id"] == 30693) &
    (df["stock_count"] == 50) &
    (df["out_of_stock_flag"] == "Yes")
]

,crawl_date_and_time,platform_name,store_id,store_name_location,city,pin_code,unique_id,product_id_upc_ean,department,category,sub_category,product_type,brand_name,product_name,product_description,product_grammage,package_type,net_quantity,variants,item_mrp,item_selling_price,out_of_stock_flag,discount_flag,product_price,unit_price,promo_offer_description,promo_offer_price,discount_in_percent,stock_count,product_url,product_image_urls
1155465,2026-07-31 03:33:43,Blinkit,30693,NaN,Delhi,110087,506032,506032,Cold Drinks & Juices,Cold Drinks & Juices,Energy Drinks,NaN,Prolyte,Prolyte Nimbu Paani ORS,NaN,200 ml,NaN,NaN,"['3 x 200 ml', '200 ml', '6 x 200 ml', '10 x 200 ml']",32,32,Yes,No,32,NaN,No offer,32,0,50,https://blinkit.com/prn/prolyte-nimbu-paani-ors/prid/506032,NaN

In [31]:
import pandas as pd

# Convert price columns to numeric
price_cols = [
    "item_mrp",
    "item_selling_price",
    "discount_in_percent"
]

for col in price_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

# Normalize discount flag
flag = df["discount_flag"].astype(str).str.strip().str.lower()

# 1. Selling Price > MRP
selling_gt_mrp = df[df["item_selling_price"] > df["item_mrp"]]

print(f"1. Selling Price > MRP : {len(selling_gt_mrp)} rows")
print(selling_gt_mrp[[
    "unique_id",
    "product_name",
    "item_mrp",
    "item_selling_price"
]])

# 2. Discount Flag = Yes but MRP == Selling Price
discount_no_difference = df[
    (flag == "yes") &
    (df["item_mrp"] == df["item_selling_price"])
]

print(f"\n2. Discount Flag = Yes but MRP == Selling Price : {len(discount_no_difference)} rows")
print(discount_no_difference[[
    "unique_id",
    "product_name",
    "item_mrp",
    "item_selling_price",
    "discount_flag"
]])

# 3. Discount % > 100
discount_gt_100 = df[df["discount_in_percent"] > 100]

print(f"\n3. Discount % > 100 : {len(discount_gt_100)} rows")
print(discount_gt_100[[
    "unique_id",
    "product_name",
    "item_mrp",
    "item_selling_price",
    "discount_in_percent"
]])

1. Selling Price > MRP : 0 rows
Empty DataFrame
Columns: [unique_id, product_name, item_mrp, item_selling_price]
Index: []

2. Discount Flag = Yes but MRP == Selling Price : 0 rows
Empty DataFrame
Columns: [unique_id, product_name, item_mrp, item_selling_price, discount_flag]
Index: []

3. Discount % > 100 : 0 rows
Empty DataFrame
Columns: [unique_id, product_name, item_mrp, item_selling_price, discount_in_percent]
Index: []

In [32]:
url_name_issues = (
    df.groupby("product_id_upc_ean")
      .agg(
          product_count=("product_name", "nunique"),
          product_names=("product_name", lambda x: sorted(set(x)))
      )
      .reset_index()
)

url_name_issues = url_name_issues[url_name_issues["product_count"] > 1]

print("URLs with different product names:", len(url_name_issues))
url_name_issues.head()

URLs with different product names: 985

,product_id_upc_ean,product_count,product_names
0,1,3,"[Nutrela Soya Mini Chunks, Nutrela Soya Mini Chunks (Meal Maker), Nutrela Soya Mini Chunks (Xoru Soyabin)]"
1,2,4,"[Nutrela Soya Chunks, Nutrela Soya Chunks (Meal Maker), Nutrela Soya Chunks (Soya Katta), Nutrela Soya Chunks (Soyabean De Tukre)]"
2,3,2,"[Nutrela Soya Granules, Nutrela Soya Granules (Soya Tharikal)]"
3,4,4,"[Fortune Soya Chunks, Fortune Soya Chunks (Meal Maker), Fortune Soya Chunks (Soya Katta), Fortune Soya Chunks (Soyabean De Tukre)]"
4,7,3,"[Aashirvaad Select 100% MP Sharbati Atta, Aashirvaad Select 100% MP Sharbati Atta (Sharbati Godhuma Pindi), Aashirvaad Select 100% MP Sharbati Atta (Sharbati Lott)]"

In [33]:
result = (
    df.groupby("product_url")
      .agg(
          product_count=("product_name", "nunique"),
          product_names=("product_name", lambda x: sorted(set(x))),
          unique_ids=("unique_id", lambda x: sorted(set(x))),
          product_ids=("product_id_upc_ean", lambda x: sorted(set(x)))
      )
      .reset_index()
)

# Keep only URLs mapped to multiple product names
result = result[result["product_count"] > 1]

print(f"Found {len(result)} URLs with different product names.")
result

Found 0 URLs with different product names.

Empty DataFrame
Columns: [product_url, product_count, product_names, unique_ids, product_ids]
Index: []

In [1]:
top10_longest = (
    df.drop_duplicates(subset="product_name")
      .assign(name_length=lambda x: x["product_name"].fillna("").str.len())
      .sort_values("name_length", ascending=False)
      [["unique_id", "name_length", "product_name", "product_url"]]
      .head(10)
)

print(top10_longest)

NameError: name 'df' is not defined

In [12]:
# 1. Group by identity columns to isolate the exact same physical product
product_identity_issues = (
    df.groupby(["unique_id", "product_grammage", "net_quantity"])
    .agg(
        # Count how many different spelling/name variations exist for this product
        name_variant_count=("product_name", "nunique"),
        # Create an alphabetised list of those unique name variations
        name_variants=("product_name", lambda x: sorted(set(x))),
        # Optional: capture variations in brand name for the same product
        brand_variants=("brand_name", lambda x: sorted(set(x.dropna()))),
    )
    .reset_index()
)

# 2. Filter for rows where the same product has more than 1 name variation
name_issues_by_id = product_identity_issues[
    product_identity_issues["name_variant_count"] > 1
]

# 3. View the final flagged discrepancies
print(name_issues_by_id)

Empty DataFrame
Columns: [unique_id, product_grammage, net_quantity, name_variant_count, name_variants, brand_variants]
Index: []

In [13]:
product_identity_issues = (
    df.groupby(["unique_id", "product_grammage", "net_quantity"])
    .agg(
        name_variant_count=("product_name", "nunique"),
        name_variants=("product_name", lambda x: sorted(set(x))),
        brand_variants=("brand_name", lambda x: sorted(set(x.dropna()))),
        url_count=("product_url", "nunique"),
        product_urls=("product_url", lambda x: sorted(set(x.dropna())))
    )
    .reset_index()
)

name_issues_by_id = product_identity_issues[
    product_identity_issues["name_variant_count"] > 1
]

name_issues_by_id

Empty DataFrame
Columns: [unique_id, product_grammage, net_quantity, name_variant_count, name_variants, brand_variants, url_count, product_urls]
Index: []

In [34]:
subcat_dist = (
    df["sub_category"]
    .value_counts(dropna=False)
    .rename_axis("sub_category")
    .reset_index(name="product_count")
)

subcat_dist

                    sub_category  product_count
0            Tools & Accessories          76047
1       Hair Styling & Treatment          68230
2                      Face Care          55126
3                 Chips & Crisps          48706
4                      Hair Care          44165
5                    Energy Bars          41795
6                 Nail Cosmetics          35699
7                      Fragrance          34788
8                        Bathing          33266
9                    Gift & Kits          31840
10    Ice Cream & Frozen Dessert          31343
11                Face Cosmetics          31220
12                 Cakes & Rolls          30947
13                 Feminine Care          28689
14                Namkeen Snacks          27366
15                    Chocolates          25098
16                 Lip Cosmetics          24766
17                   Bread & Pav          24735
18                Makhana & More          23400
19                 Indian Sweets          23354
20          Lassi, Shakes & More          23324
21      Face & Body Moisturizers          23271
22                       Cookies          22541
23              Deodorant & Talc          22440
24                     Oral Care          21616
25           Bath & Beauty Gifts          20926
26                   Soft Drinks          20911
27                 Face Cleaning          20836
28                    Eye Makeup          20313
29                Rusks & Wafers          20289
30              Skin & Hair Care          19336
31                 Candies & Gum          19335
32                 Soda & Mixers          19216
33                   Fruit Juice          17928
34   Poha, Daliya & Other Grains          17905
35                          Rice          17775
36             Bhujia & Mixtures          16334
37       Shower Gels & Body Wash          15959
38           Baby Gifting & Toys          15579
39                Men's Grooming          15461
40                 Energy Drinks          15344
41                 Bathing Soaps          14589
42                     Face Wash          14415
43                Lip & Eye Care          14282
44                     Sunscreen          13839
45             Face Moisturisers          12516
46              Body & Skin Care          12100
47    Baby Accessories & Apparel          11927
48              Women's Grooming          11795
49                Diapers & More          11309
50            Feeding Essentials          11136
51            Baking Ingredients          11088
52         Millet & Other Flours           9780
53         Cold Coffee & Ice Tea           9729
54                Cream Biscuits           9645
55              Mouth Fresheners           9643
56            Toor, Urad & Chana           9627
57               Chocolate Packs           9425
58        Rajma, Chhole & Others           8255
59                          Oats           8202
60                     Baby Food           8022
61             Snacks & Munchies           7494
62           Chocolate Gift Pack           7065
63              Pulses & Millets           7064
64                 Curd & Yogurt           6961
65           Healthy & Digestive           6942
66      Dry Fruits, Nuts & Seeds           6682
67              Cookies & Wafers           6452
68                      Handwash           6401
69                 Bathing Needs           6287
70              Muesli & Granola           6283
71          Honey & Chyawanprash           6229
72             Baking Essentials           6145
73                Gourmet Bakery           6140
74          Breakfast Essentials           6060
75                        Cheese           5988
76                Papad & Fryums           5936
77                       Popcorn           5891
78                Moong & Masoor           5839
79            Imported Beverages           5761
80                    Oil & Ghee           5711
81                          Atta           5648
82                     Beverages           5517
83                 Peanut Butter           5215
84                       Nursing           5012
85   Organic Salt, Sugar & Honey           4885
86                         Flour           4844
87         Flakes & Kids Cereals           4842
88                 Sweet & Salty           4764
89         Concentrates & Syrups           4719
90                        Nachos           4665
91               Health & Safety           4432
92      Premium Sauces & Spreads           4390
93          Besan, Sooji & Maida           4003
94                 Instant Foods           3930
95                       Hygiene           3554
96                  Tea & Coffee           3362
97             Water & Ice Cubes           3238
98                    Baby Wipes           3218
99                 Coconut Water           3191
100              Breakfast Mixes           3109
101                         Eggs           3033
102                         Milk           2970
103                Herbal Drinks           2938
104         Rice & Rice Products           2793
105        Sausage, Salami & Ham           2749
106                 Mango Drinks           2562
107              Imported Snacks           2509
108                Paneer & Tofu           2477
109            Flavoured Yogurts           2426
110                       Batter           2144
111                  Pure Juices           2141
112              Glucose & Marie           2132
113         Chocolates & Candies           1922
114               Mom Care Needs           1432
115                   Vermicelli           1417
116                Butter & More           1268
117             Spices & Vinegar           1257
118                       Syrups           1246
119            Biscuit Gift Pack           1241
120             Cream & Whitener           1040
121                      Granola            918
122                    Baby Gear            762
123               Condensed Milk            741
124          Munchies Gift Packs            478
125         Beverages Gift Packs            291
126             Plant Based Meat            235
127                   Fresh Atta            146

In [35]:
subcat_by_category = (
    pd.crosstab(
        df["category"],
        df["sub_category"]
    )
)

subcat_by_category

sub_category,Atta,Baby Accessories & Apparel,Baby Food,Baby Gear,Baby Gifting & Toys,Baby Wipes,Baking Essentials,Baking Ingredients,Bath & Beauty Gifts,Bathing,Bathing Needs,Bathing Soaps,Batter,"Besan, Sooji & Maida",Beverages,Beverages Gift Packs,Bhujia & Mixtures,Biscuit Gift Pack,Body & Skin Care,Bread & Pav,Breakfast Essentials,Breakfast Mixes,Butter & More,Cakes & Rolls,Candies & Gum,Cheese,Chips & Crisps,Chocolate Gift Pack,Chocolate Packs,Chocolates,Chocolates & Candies,Coconut Water,Cold Coffee & Ice Tea,Concentrates & Syrups,Condensed Milk,Cookies,Cookies & Wafers,Cream & Whitener,Cream Biscuits,Curd & Yogurt,Deodorant & Talc,Diapers & More,"Dry Fruits, Nuts & Seeds",Eggs,Energy Bars,Energy Drinks,Eye Makeup,Face & Body Moisturizers,Face Care,Face Cleaning,Face Cosmetics,Face Moisturisers,Face Wash,Feeding Essentials,Feminine Care,Flakes & Kids Cereals,Flavoured Yogurts,Flour,Fragrance,Fresh Atta,Fruit Juice,Gift & Kits,Glucose & Marie,Gourmet Bakery,Granola,Hair Care,Hair Styling & Treatment,Handwash,Health & Safety,Healthy & Digestive,Herbal Drinks,Honey & Chyawanprash,Hygiene,Ice Cream & Frozen Dessert,Imported Beverages,Imported Snacks,Indian Sweets,Instant Foods,"Lassi, Shakes & More",Lip & Eye Care,Lip Cosmetics,Makhana & More,Mango Drinks,Men's Grooming,Milk,Millet & Other Flours,Mom Care Needs,Moong & Masoor,Mouth Fresheners,Muesli & Granola,Munchies Gift Packs,Nachos,Nail Cosmetics,Namkeen Snacks,Nursing,Oats,Oil & Ghee,Oral Care,"Organic Salt, Sugar & Honey",Paneer & Tofu,Papad & Fryums,Peanut Butter,Plant Based Meat,"Poha, Daliya & Other Grains",Popcorn,Premium Sauces & Spreads,Pulses & Millets,Pure Juices,"Rajma, Chhole & Others",Rice,Rice & Rice Products,Rusks & Wafers,"Sausage, Salami & Ham",Shower Gels & Body Wash,Skin & Hair Care,Snacks & Munchies,Soda & Mixers,Soft Drinks,Spices & Vinegar,Sunscreen,Sweet & Salty,Syrups,Tea & Coffee,Tools & Accessories,"Toor, Urad & Chana",Vermicelli,Water & Ice Cubes,Women's Grooming
category,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
"Atta, Rice & Dal",5648,0,0,0,0,0,0,0,0,0,0,0,0,4003,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,146,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,9780,0,5839,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8912,0,0,0,0,8255,17775,0,0,0,0,0,0,0,0,0,0,0,0,0,0,9627,0,0,0
Baby Care,0,11927,8022,762,15579,3218,0,0,0,0,6287,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,11309,0,0,0,0,0,0,0,0,0,0,0,11136,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4432,0,0,0,3554,0,0,0,0,0,0,0,0,0,0,0,0,0,1432,0,0,0,0,0,0,0,5012,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,9679,0,0,0,0,0,0,0,0,0,0,0,0,0
Bakery & Biscuits,0,0,0,0,0,0,0,11088,0,0,0,0,0,0,0,0,0,1241,0,12363,0,0,0,15465,0,0,0,0,0,0,0,0,0,0,0,22541,0,0,9645,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2132,6140,0,0,0,0,0,6942,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,10196,0,0,0,0,0,0,0,0,4764,0,0,0,0,0,0,0
Beauty & Cosmetics,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,12100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,20313,0,55126,0,31220,0,0,0,0,0,0,0,34788,0,0,31840,0,0,0,0,68230,0,0,0,0,0,0,0,0,0,0,0,0,14282,24766,0,0,0,0,0,0,0,0,0,0,0,35699,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,76047,0,0,0,0
Cold Drinks & Juices,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,291,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3191,9729,4719,0,0,0,0,0,0,0,0,0,0,0,15344,0,0,0,0,0,0,0,0,0,0,0,0,0,0,17928,0,0,0,0,0,0,0,0,0,2938,0,0,0,5761,0,0,0,11666,0,0,0,2562,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2141,0,0,0,0,0,0,0,0,19216,20911,0,0,0,0,0,0,0,0,3238,0
Dairy & Breakfast,0,0,0,0,0,0,0,0,0,0,0,0,2144,0,0,0,0,0,0,12372,0,3109,1268,0,0,5988,0,0,0,0,0,0,0,0,741,0,0,1040,0,6961,0,0,0,3033,13924,0,0,0,0,0,0,0,0,0,0,4842,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6229,0,0,0,0,0,0,11658,0,0,0,0,0,2970,0,0,0,0,6283,0,0,0,0,0,8202,0,0,0,2477,0,5215,0,8993,0,0,0,0,0,0,0,0,2749,0,0,0,0,0,0,0,0,0,0,0,0,1417,0,0
Munchies,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,16334,0,0,0,0,0,0,0,0,0,48706,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,13964,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,918,0,0,0,0,0,0,0,0,0,0,2509,0,0,0,0,0,23400,0,0,0,0,0,0,0,0,478,4665,0,27366,0,0,0,0,0,0,5936,0,0,0,5891,0,0,0,0,0,0,10093,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Organic & Premium,0,0,0,0,0,0,6145,0,0,0,0,0,0,0,5517,0,0,0,0,0,6060,0,0,0,0,0,0,0,0,0,1922,0,0,0,0,0,6452,0,0,0,0,0,6682,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4844,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3930,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5711,0,4885,0,0,0,235,0,0,4390,7064,0,0,0,2793,0,0,0,0,7494,0,0,1257,0,0,0,3362,0,0,0,0,0
Personal Care,0,0,0,0,0,0,0,0,20926,33266,0,14589,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22440,0,0,0,0,0,0,23271,0,20836,0,12516,14415,0,28689,0,0,0,0,0,0,0,0,0,0,44165,0,6401,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,15461,0,0,0,0,0,0,0,0,0,0,0,0,0,21616,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,15959,9657,0,0,0,0,13839,0,0,0,0,0,0,0,11795
Sweet Tooth,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,15482,19335,0,0,7065,9425,25098,0,0,0,0,0,0,0,0,0,0,0,0,0,0,13907,0,0,0,0,0,0,0,0,0,0,0,2426,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,31343,0,0,23354,0,0,0,0,0,0,0,0,0,0,0,9643,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1246,0,0,0,0,0,0

In [36]:
subcat_by_department = (
    pd.crosstab(
        df["department"],
        df["sub_category"]
    )
)

subcat_by_department

sub_category,Atta,Baby Accessories & Apparel,Baby Food,Baby Gear,Baby Gifting & Toys,Baby Wipes,Baking Essentials,Baking Ingredients,Bath & Beauty Gifts,Bathing,Bathing Needs,Bathing Soaps,Batter,"Besan, Sooji & Maida",Beverages,Beverages Gift Packs,Bhujia & Mixtures,Biscuit Gift Pack,Body & Skin Care,Bread & Pav,Breakfast Essentials,Breakfast Mixes,Butter & More,Cakes & Rolls,Candies & Gum,Cheese,Chips & Crisps,Chocolate Gift Pack,Chocolate Packs,Chocolates,Chocolates & Candies,Coconut Water,Cold Coffee & Ice Tea,Concentrates & Syrups,Condensed Milk,Cookies,Cookies & Wafers,Cream & Whitener,Cream Biscuits,Curd & Yogurt,Deodorant & Talc,Diapers & More,"Dry Fruits, Nuts & Seeds",Eggs,Energy Bars,Energy Drinks,Eye Makeup,Face & Body Moisturizers,Face Care,Face Cleaning,Face Cosmetics,Face Moisturisers,Face Wash,Feeding Essentials,Feminine Care,Flakes & Kids Cereals,Flavoured Yogurts,Flour,Fragrance,Fresh Atta,Fruit Juice,Gift & Kits,Glucose & Marie,Gourmet Bakery,Granola,Hair Care,Hair Styling & Treatment,Handwash,Health & Safety,Healthy & Digestive,Herbal Drinks,Honey & Chyawanprash,Hygiene,Ice Cream & Frozen Dessert,Imported Beverages,Imported Snacks,Indian Sweets,Instant Foods,"Lassi, Shakes & More",Lip & Eye Care,Lip Cosmetics,Makhana & More,Mango Drinks,Men's Grooming,Milk,Millet & Other Flours,Mom Care Needs,Moong & Masoor,Mouth Fresheners,Muesli & Granola,Munchies Gift Packs,Nachos,Nail Cosmetics,Namkeen Snacks,Nursing,Oats,Oil & Ghee,Oral Care,"Organic Salt, Sugar & Honey",Paneer & Tofu,Papad & Fryums,Peanut Butter,Plant Based Meat,"Poha, Daliya & Other Grains",Popcorn,Premium Sauces & Spreads,Pulses & Millets,Pure Juices,"Rajma, Chhole & Others",Rice,Rice & Rice Products,Rusks & Wafers,"Sausage, Salami & Ham",Shower Gels & Body Wash,Skin & Hair Care,Snacks & Munchies,Soda & Mixers,Soft Drinks,Spices & Vinegar,Sunscreen,Sweet & Salty,Syrups,Tea & Coffee,Tools & Accessories,"Toor, Urad & Chana",Vermicelli,Water & Ice Cubes,Women's Grooming
department,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
"Atta, Rice & Dal",5648,0,0,0,0,0,0,0,0,0,0,0,0,4003,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,146,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,9780,0,5839,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8912,0,0,0,0,8255,17775,0,0,0,0,0,0,0,0,0,0,0,0,0,0,9627,0,0,0
Baby Care,0,11927,8022,762,15579,3218,0,0,0,0,6287,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,11309,0,0,0,0,0,0,0,0,0,0,0,11136,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4432,0,0,0,3554,0,0,0,0,0,0,0,0,0,0,0,0,0,1432,0,0,0,0,0,0,0,5012,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,9679,0,0,0,0,0,0,0,0,0,0,0,0,0
Bakery & Biscuits,0,0,0,0,0,0,0,11088,0,0,0,0,0,0,0,0,0,1241,0,12363,0,0,0,15465,0,0,0,0,0,0,0,0,0,0,0,22541,0,0,9645,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2132,6140,0,0,0,0,0,6942,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,10196,0,0,0,0,0,0,0,0,4764,0,0,0,0,0,0,0
Beauty & Cosmetics,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,12100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,20313,0,55126,0,31220,0,0,0,0,0,0,0,34788,0,0,31840,0,0,0,0,68230,0,0,0,0,0,0,0,0,0,0,0,0,14282,24766,0,0,0,0,0,0,0,0,0,0,0,35699,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,76047,0,0,0,0
Cold Drinks & Juices,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,291,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3191,9729,4719,0,0,0,0,0,0,0,0,0,0,0,15344,0,0,0,0,0,0,0,0,0,0,0,0,0,0,17928,0,0,0,0,0,0,0,0,0,2938,0,0,0,5761,0,0,0,11666,0,0,0,2562,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2141,0,0,0,0,0,0,0,0,19216,20911,0,0,0,0,0,0,0,0,3238,0
Dairy & Breakfast,0,0,0,0,0,0,0,0,0,0,0,0,2144,0,0,0,0,0,0,12372,0,3109,1268,0,0,5988,0,0,0,0,0,0,0,0,741,0,0,1040,0,6961,0,0,0,3033,13924,0,0,0,0,0,0,0,0,0,0,4842,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6229,0,0,0,0,0,0,11658,0,0,0,0,0,2970,0,0,0,0,6283,0,0,0,0,0,8202,0,0,0,2477,0,5215,0,8993,0,0,0,0,0,0,0,0,2749,0,0,0,0,0,0,0,0,0,0,0,0,1417,0,0
Munchies,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,16334,0,0,0,0,0,0,0,0,0,48706,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,13964,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,918,0,0,0,0,0,0,0,0,0,0,2509,0,0,0,0,0,23400,0,0,0,0,0,0,0,0,478,4665,0,27366,0,0,0,0,0,0,5936,0,0,0,5891,0,0,0,0,0,0,10093,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Organic & Premium,0,0,0,0,0,0,6145,0,0,0,0,0,0,0,5517,0,0,0,0,0,6060,0,0,0,0,0,0,0,0,0,1922,0,0,0,0,0,6452,0,0,0,0,0,6682,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4844,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3930,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5711,0,4885,0,0,0,235,0,0,4390,7064,0,0,0,2793,0,0,0,0,7494,0,0,1257,0,0,0,3362,0,0,0,0,0
Personal Care,0,0,0,0,0,0,0,0,20926,33266,0,14589,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22440,0,0,0,0,0,0,23271,0,20836,0,12516,14415,0,28689,0,0,0,0,0,0,0,0,0,0,44165,0,6401,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,15461,0,0,0,0,0,0,0,0,0,0,0,0,0,21616,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,15959,9657,0,0,0,0,13839,0,0,0,0,0,0,0,11795
Sweet Tooth,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,15482,19335,0,0,7065,9425,25098,0,0,0,0,0,0,0,0,0,0,0,0,0,0,13907,0,0,0,0,0,0,0,0,0,0,0,2426,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,31343,0,0,23354,0,0,0,0,0,0,0,0,0,0,0,9643,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1246,0,0,0,0,0,0

In [37]:
summary = (
    df.groupby(["category", "sub_category"])
      .size()
      .reset_index(name="product_count")
      .sort_values(["category", "product_count"], ascending=[True, False])
)

summary

                 category                 sub_category  product_count
7        Atta, Rice & Dal                         Rice          17775
3        Atta, Rice & Dal        Millet & Other Flours           9780
8        Atta, Rice & Dal           Toor, Urad & Chana           9627
5        Atta, Rice & Dal  Poha, Daliya & Other Grains           8912
6        Atta, Rice & Dal       Rajma, Chhole & Others           8255
4        Atta, Rice & Dal               Moong & Masoor           5839
0        Atta, Rice & Dal                         Atta           5648
1        Atta, Rice & Dal         Besan, Sooji & Maida           4003
2        Atta, Rice & Dal                   Fresh Atta            146
12              Baby Care          Baby Gifting & Toys          15579
9               Baby Care   Baby Accessories & Apparel          11927
15              Baby Care               Diapers & More          11309
16              Baby Care           Feeding Essentials          11136
21              Baby Care             Skin & Hair Care           9679
10              Baby Care                    Baby Food           8022
14              Baby Care                Bathing Needs           6287
20              Baby Care                      Nursing           5012
17              Baby Care              Health & Safety           4432
18              Baby Care                      Hygiene           3554
13              Baby Care                   Baby Wipes           3218
19              Baby Care               Mom Care Needs           1432
11              Baby Care                    Baby Gear            762
26      Bakery & Biscuits                      Cookies          22541
25      Bakery & Biscuits                Cakes & Rolls          15465
24      Bakery & Biscuits                  Bread & Pav          12363
22      Bakery & Biscuits           Baking Ingredients          11088
31      Bakery & Biscuits               Rusks & Wafers          10196
27      Bakery & Biscuits               Cream Biscuits           9645
30      Bakery & Biscuits          Healthy & Digestive           6942
29      Bakery & Biscuits               Gourmet Bakery           6140
32      Bakery & Biscuits                Sweet & Salty           4764
28      Bakery & Biscuits              Glucose & Marie           2132
23      Bakery & Biscuits            Biscuit Gift Pack           1241
43     Beauty & Cosmetics          Tools & Accessories          76047
39     Beauty & Cosmetics     Hair Styling & Treatment          68230
35     Beauty & Cosmetics                    Face Care          55126
42     Beauty & Cosmetics               Nail Cosmetics          35699
37     Beauty & Cosmetics                    Fragrance          34788
38     Beauty & Cosmetics                  Gift & Kits          31840
36     Beauty & Cosmetics               Face Cosmetics          31220
41     Beauty & Cosmetics                Lip Cosmetics          24766
34     Beauty & Cosmetics                   Eye Makeup          20313
40     Beauty & Cosmetics               Lip & Eye Care          14282
33     Beauty & Cosmetics             Body & Skin Care          12100
56   Cold Drinks & Juices                  Soft Drinks          20911
55   Cold Drinks & Juices                Soda & Mixers          19216
49   Cold Drinks & Juices                  Fruit Juice          17928
48   Cold Drinks & Juices                Energy Drinks          15344
52   Cold Drinks & Juices         Lassi, Shakes & More          11666
46   Cold Drinks & Juices        Cold Coffee & Ice Tea           9729
51   Cold Drinks & Juices           Imported Beverages           5761
47   Cold Drinks & Juices        Concentrates & Syrups           4719
57   Cold Drinks & Juices            Water & Ice Cubes           3238
45   Cold Drinks & Juices                Coconut Water           3191
50   Cold Drinks & Juices                Herbal Drinks           2938
53   Cold Drinks & Juices                 Mango Drinks           2562
54   Cold Drinks & Juices                  Pure Juices           2141
44   Cold Drinks & Juices         Beverages Gift Packs            291
67      Dairy & Breakfast                  Energy Bars          13924
59      Dairy & Breakfast                  Bread & Pav          12372
70      Dairy & Breakfast         Lassi, Shakes & More          11658
76      Dairy & Breakfast  Poha, Daliya & Other Grains           8993
73      Dairy & Breakfast                         Oats           8202
65      Dairy & Breakfast                Curd & Yogurt           6961
72      Dairy & Breakfast             Muesli & Granola           6283
69      Dairy & Breakfast         Honey & Chyawanprash           6229
62      Dairy & Breakfast                       Cheese           5988
75      Dairy & Breakfast                Peanut Butter           5215
68      Dairy & Breakfast        Flakes & Kids Cereals           4842
60      Dairy & Breakfast              Breakfast Mixes           3109
66      Dairy & Breakfast                         Eggs           3033
71      Dairy & Breakfast                         Milk           2970
77      Dairy & Breakfast        Sausage, Salami & Ham           2749
74      Dairy & Breakfast                Paneer & Tofu           2477
58      Dairy & Breakfast                       Batter           2144
78      Dairy & Breakfast                   Vermicelli           1417
61      Dairy & Breakfast                Butter & More           1268
64      Dairy & Breakfast             Cream & Whitener           1040
63      Dairy & Breakfast               Condensed Milk            741
80               Munchies               Chips & Crisps          48706
87               Munchies               Namkeen Snacks          27366
84               Munchies               Makhana & More          23400
79               Munchies            Bhujia & Mixtures          16334
81               Munchies                  Energy Bars          13964
90               Munchies               Rusks & Wafers          10093
88               Munchies               Papad & Fryums           5936
89               Munchies                      Popcorn           5891
86               Munchies                       Nachos           4665
83               Munchies              Imported Snacks           2509
82               Munchies                      Granola            918
85               Munchies          Munchies Gift Packs            478
105     Organic & Premium            Snacks & Munchies           7494
103     Organic & Premium             Pulses & Millets           7064
96      Organic & Premium     Dry Fruits, Nuts & Seeds           6682
95      Organic & Premium             Cookies & Wafers           6452
91      Organic & Premium            Baking Essentials           6145
93      Organic & Premium         Breakfast Essentials           6060
99      Organic & Premium                   Oil & Ghee           5711
92      Organic & Premium                    Beverages           5517
100     Organic & Premium  Organic Salt, Sugar & Honey           4885
97      Organic & Premium                        Flour           4844
102     Organic & Premium     Premium Sauces & Spreads           4390
98      Organic & Premium                Instant Foods           3930
107     Organic & Premium                 Tea & Coffee           3362
104     Organic & Premium         Rice & Rice Products           2793
94      Organic & Premium         Chocolates & Candies           1922
106     Organic & Premium             Spices & Vinegar           1257
101     Organic & Premium             Plant Based Meat            235
117         Personal Care                    Hair Care          44165
109         Personal Care                      Bathing          33266
116         Personal Care                Feminine Care          28689
112         Personal Care     Face & Body Moisturizers          23271
111         Personal Care             Deodorant & Talc          22440
120         Personal Care                    Oral Care          21616
108         Personal Care          Bath & Beauty Gifts          20926
113         Personal Care                Face Cleaning          20836
121         Personal Care      Shower Gels & Body Wash          15959
119         Personal Care               Men's Grooming          15461
110         Personal Care                Bathing Soaps          14589
115         Personal Care                    Face Wash          14415
123         Personal Care                    Sunscreen          13839
114         Personal Care            Face Moisturisers          12516
124         Personal Care             Women's Grooming          11795
122         Personal Care             Skin & Hair Care           9657
118         Personal Care                     Handwash           6401
132           Sweet Tooth   Ice Cream & Frozen Dessert          31343
129           Sweet Tooth                   Chocolates          25098
133           Sweet Tooth                Indian Sweets          23354
126           Sweet Tooth                Candies & Gum          19335
125           Sweet Tooth                Cakes & Rolls          15482
130           Sweet Tooth                  Energy Bars          13907
134           Sweet Tooth             Mouth Fresheners           9643
128           Sweet Tooth              Chocolate Packs           9425
127           Sweet Tooth          Chocolate Gift Pack           7065
131           Sweet Tooth            Flavoured Yogurts           2426
135           Sweet Tooth                       Syrups           1246

In [38]:
subcat_mapping = (
    df.groupby("sub_category")["category"]
      .agg(lambda x: sorted(set(x)))
      .reset_index(name="categories")
)

subcat_mapping["category_count"] = subcat_mapping["categories"].str.len()

issues = subcat_mapping[subcat_mapping["category_count"] > 1]

issues

,sub_category,categories,category_count
19,Bread & Pav,"[Bakery & Biscuits, Dairy & Breakfast]",2
23,Cakes & Rolls,"[Bakery & Biscuits, Sweet Tooth]",2
44,Energy Bars,"[Dairy & Breakfast, Munchies, Sweet Tooth]",3
78,"Lassi, Shakes & More","[Cold Drinks & Juices, Dairy & Breakfast]",2
103,"Poha, Daliya & Other Grains","[Atta, Rice & Dal, Dairy & Breakfast]",2
111,Rusks & Wafers,"[Bakery & Biscuits, Munchies]",2
114,Skin & Hair Care,"[Baby Care, Personal Care]",2

In [39]:
summary = (
    df.groupby(["category", "sub_category"])
      .size()
      .reset_index(name="product_count")
      .sort_values("product_count", ascending=True)
)

summary

                 category                 sub_category  product_count
2        Atta, Rice & Dal                   Fresh Atta            146
101     Organic & Premium             Plant Based Meat            235
44   Cold Drinks & Juices         Beverages Gift Packs            291
85               Munchies          Munchies Gift Packs            478
63      Dairy & Breakfast               Condensed Milk            741
11              Baby Care                    Baby Gear            762
82               Munchies                      Granola            918
64      Dairy & Breakfast             Cream & Whitener           1040
23      Bakery & Biscuits            Biscuit Gift Pack           1241
135           Sweet Tooth                       Syrups           1246
106     Organic & Premium             Spices & Vinegar           1257
61      Dairy & Breakfast                Butter & More           1268
78      Dairy & Breakfast                   Vermicelli           1417
19              Baby Care               Mom Care Needs           1432
94      Organic & Premium         Chocolates & Candies           1922
28      Bakery & Biscuits              Glucose & Marie           2132
54   Cold Drinks & Juices                  Pure Juices           2141
58      Dairy & Breakfast                       Batter           2144
131           Sweet Tooth            Flavoured Yogurts           2426
74      Dairy & Breakfast                Paneer & Tofu           2477
83               Munchies              Imported Snacks           2509
53   Cold Drinks & Juices                 Mango Drinks           2562
77      Dairy & Breakfast        Sausage, Salami & Ham           2749
104     Organic & Premium         Rice & Rice Products           2793
50   Cold Drinks & Juices                Herbal Drinks           2938
71      Dairy & Breakfast                         Milk           2970
66      Dairy & Breakfast                         Eggs           3033
60      Dairy & Breakfast              Breakfast Mixes           3109
45   Cold Drinks & Juices                Coconut Water           3191
13              Baby Care                   Baby Wipes           3218
57   Cold Drinks & Juices            Water & Ice Cubes           3238
107     Organic & Premium                 Tea & Coffee           3362
18              Baby Care                      Hygiene           3554
98      Organic & Premium                Instant Foods           3930
1        Atta, Rice & Dal         Besan, Sooji & Maida           4003
102     Organic & Premium     Premium Sauces & Spreads           4390
17              Baby Care              Health & Safety           4432
86               Munchies                       Nachos           4665
47   Cold Drinks & Juices        Concentrates & Syrups           4719
32      Bakery & Biscuits                Sweet & Salty           4764
68      Dairy & Breakfast        Flakes & Kids Cereals           4842
97      Organic & Premium                        Flour           4844
100     Organic & Premium  Organic Salt, Sugar & Honey           4885
20              Baby Care                      Nursing           5012
75      Dairy & Breakfast                Peanut Butter           5215
92      Organic & Premium                    Beverages           5517
0        Atta, Rice & Dal                         Atta           5648
99      Organic & Premium                   Oil & Ghee           5711
51   Cold Drinks & Juices           Imported Beverages           5761
4        Atta, Rice & Dal               Moong & Masoor           5839
89               Munchies                      Popcorn           5891
88               Munchies               Papad & Fryums           5936
62      Dairy & Breakfast                       Cheese           5988
93      Organic & Premium         Breakfast Essentials           6060
29      Bakery & Biscuits               Gourmet Bakery           6140
91      Organic & Premium            Baking Essentials           6145
69      Dairy & Breakfast         Honey & Chyawanprash           6229
72      Dairy & Breakfast             Muesli & Granola           6283
14              Baby Care                Bathing Needs           6287
118         Personal Care                     Handwash           6401
95      Organic & Premium             Cookies & Wafers           6452
96      Organic & Premium     Dry Fruits, Nuts & Seeds           6682
30      Bakery & Biscuits          Healthy & Digestive           6942
65      Dairy & Breakfast                Curd & Yogurt           6961
103     Organic & Premium             Pulses & Millets           7064
127           Sweet Tooth          Chocolate Gift Pack           7065
105     Organic & Premium            Snacks & Munchies           7494
10              Baby Care                    Baby Food           8022
73      Dairy & Breakfast                         Oats           8202
6        Atta, Rice & Dal       Rajma, Chhole & Others           8255
5        Atta, Rice & Dal  Poha, Daliya & Other Grains           8912
76      Dairy & Breakfast  Poha, Daliya & Other Grains           8993
128           Sweet Tooth              Chocolate Packs           9425
8        Atta, Rice & Dal           Toor, Urad & Chana           9627
134           Sweet Tooth             Mouth Fresheners           9643
27      Bakery & Biscuits               Cream Biscuits           9645
122         Personal Care             Skin & Hair Care           9657
21              Baby Care             Skin & Hair Care           9679
46   Cold Drinks & Juices        Cold Coffee & Ice Tea           9729
3        Atta, Rice & Dal        Millet & Other Flours           9780
90               Munchies               Rusks & Wafers          10093
31      Bakery & Biscuits               Rusks & Wafers          10196
22      Bakery & Biscuits           Baking Ingredients          11088
16              Baby Care           Feeding Essentials          11136
15              Baby Care               Diapers & More          11309
70      Dairy & Breakfast         Lassi, Shakes & More          11658
52   Cold Drinks & Juices         Lassi, Shakes & More          11666
124         Personal Care             Women's Grooming          11795
9               Baby Care   Baby Accessories & Apparel          11927
33     Beauty & Cosmetics             Body & Skin Care          12100
24      Bakery & Biscuits                  Bread & Pav          12363
59      Dairy & Breakfast                  Bread & Pav          12372
114         Personal Care            Face Moisturisers          12516
123         Personal Care                    Sunscreen          13839
130           Sweet Tooth                  Energy Bars          13907
67      Dairy & Breakfast                  Energy Bars          13924
81               Munchies                  Energy Bars          13964
40     Beauty & Cosmetics               Lip & Eye Care          14282
115         Personal Care                    Face Wash          14415
110         Personal Care                Bathing Soaps          14589
48   Cold Drinks & Juices                Energy Drinks          15344
119         Personal Care               Men's Grooming          15461
25      Bakery & Biscuits                Cakes & Rolls          15465
125           Sweet Tooth                Cakes & Rolls          15482
12              Baby Care          Baby Gifting & Toys          15579
121         Personal Care      Shower Gels & Body Wash          15959
79               Munchies            Bhujia & Mixtures          16334
7        Atta, Rice & Dal                         Rice          17775
49   Cold Drinks & Juices                  Fruit Juice          17928
55   Cold Drinks & Juices                Soda & Mixers          19216
126           Sweet Tooth                Candies & Gum          19335
34     Beauty & Cosmetics                   Eye Makeup          20313
113         Personal Care                Face Cleaning          20836
56   Cold Drinks & Juices                  Soft Drinks          20911
108         Personal Care          Bath & Beauty Gifts          20926
120         Personal Care                    Oral Care          21616
111         Personal Care             Deodorant & Talc          22440
26      Bakery & Biscuits                      Cookies          22541
112         Personal Care     Face & Body Moisturizers          23271
133           Sweet Tooth                Indian Sweets          23354
84               Munchies               Makhana & More          23400
41     Beauty & Cosmetics                Lip Cosmetics          24766
129           Sweet Tooth                   Chocolates          25098
87               Munchies               Namkeen Snacks          27366
116         Personal Care                Feminine Care          28689
36     Beauty & Cosmetics               Face Cosmetics          31220
132           Sweet Tooth   Ice Cream & Frozen Dessert          31343
38     Beauty & Cosmetics                  Gift & Kits          31840
109         Personal Care                      Bathing          33266
37     Beauty & Cosmetics                    Fragrance          34788
42     Beauty & Cosmetics               Nail Cosmetics          35699
117         Personal Care                    Hair Care          44165
80               Munchies               Chips & Crisps          48706
35     Beauty & Cosmetics                    Face Care          55126
39     Beauty & Cosmetics     Hair Styling & Treatment          68230
43     Beauty & Cosmetics          Tools & Accessories          76047

In [40]:
price_cols = [
    "item_mrp",
    "item_selling_price",
    "product_price",
    "promo_offer_price"
]

zero_price_rows = df[(df[price_cols] == 0).any(axis=1)]

zero_price_rows

,crawl_date_and_time,platform_name,store_id,store_name_location,city,pin_code,unique_id,product_id_upc_ean,department,category,sub_category,product_type,brand_name,product_name,product_description,product_grammage,package_type,net_quantity,variants,item_mrp,item_selling_price,out_of_stock_flag,discount_flag,product_price,unit_price,promo_offer_description,promo_offer_price,discount_in_percent,stock_count,product_url,product_image_urls
332458,2026-07-31 01:01:40,Blinkit,41219,NaN,Mumbai,400059,1373229,1373229,Beauty & Cosmetics,Beauty & Cosmetics,Hair Styling & Treatment,NaN,Nexxus,Nexxus Promend Oil Resurrection Hair Serum,NaN,3.5 ml,NaN,NaN,NaN,1,0,No,No,0,NaN,No offer,0,0,1,https://blinkit.com/prn/nexxus-promend-oil-resurrection-hair-serum/prid/1373229,NaN
788316,2026-07-31 02:26:11,Blinkit,45268,NaN,Vapi,396191,1373229,1373229,Beauty & Cosmetics,Beauty & Cosmetics,Hair Styling & Treatment,NaN,Nexxus,Nexxus Promend Oil Resurrection Hair Serum,NaN,3.5 ml,NaN,NaN,NaN,1,0,No,No,0,NaN,No offer,0,0,1,https://blinkit.com/prn/nexxus-promend-oil-resurrection-hair-serum/prid/1373229,NaN

In [ ]:
df.unique_id.duplicated().sum()

np.int64(1592521)

:

In [ ]:
store_counts = (
    df.groupby(["city", "store_id",])
      .size()
      .reset_index(name="product_count")
)

store_counts[store_counts["product_count"] < 10]

          city  store_id  product_count
20   Bangalore     30832              3
25   Bangalore     34348              7
28   Bangalore     34752              1
29   Bangalore     34835              7
49   Bangalore     46427              9
93     Gurgaon     31552              1
96     Gurgaon     33027              5
97     Gurgaon     33541              2
137     Jaipur     37028              4
140     Jaipur     42750              9
141     Jaipur     42813              3
157    Lucknow     33676              8
177      Noida     44662              1
196       Pune     45270              3
198       Pune     45923              5