In [1]:
import pandas as pd
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option("display.max_colwidth", None)

In [2]:
df= pd.read_csv(r'/home/user/Documents/zepto_2026_07_23.csv',  low_memory=False)

In [4]:
df.shape

(165326, 31)

In [5]:
df.head()

,crawl_date_and_time,platform_name,store_id,store_name_location,city,pin_code,unique_id,product_id_upc_ean,department,category,sub_category,product_type,brand_name,product_name,product_description,product_grammage,package_type,net_quantity,variants,item_mrp,item_selling_price,out_of_stock_flag,discount_flag,product_price,unit_price,promo_offer_description,promo_offer_price,discount_in_percent,stock_count,product_url,product_image_urls
0,2026-07-23 01:15:38,zepto,aa443b4b-bf3b-499c-a846-bf5196d444ae,"Vikaspuri Road, Vikaspuri Rd, Manohar Nagar, Vikaspuri, Delhi, 110018, India",Delhi,110018,31ad3e8b-e689-48c1-956c-ca36d9fcac2c,e036add7-94c1-4287-b83b-ffd2794806cf,"Atta, Rice & Dal","Atta, Rice, Oil & Dals",Millets & Other Flours,NaN,Daily Good,Daily Good Corn Flour/Starch,NaN,500 g,NaN,1 pack (500 g),NaN,70.0,62.0,No,Yes,62.0,NaN,₹8 OFF,62.0,11,6,https://www.zepto.com/pn/daily-good-corn-flourstarch/pvid/31ad3e8b-e689-48c1-956c-ca36d9fcac2c,NaN
1,2026-07-23 01:15:38,zepto,aa443b4b-bf3b-499c-a846-bf5196d444ae,"Vikaspuri Road, Vikaspuri Rd, Manohar Nagar, Vikaspuri, Delhi, 110018, India",Delhi,110018,4321e603-486d-4de8-a146-48d353992e19,c34b6a8d-009b-449a-bdc1-260f53ae51d3,"Atta, Rice & Dal","Atta, Rice, Oil & Dals",Millets & Other Flours,NaN,Tata Sampann,Tata Sampann Easy Cook Ragi Atta,NaN,500 g,NaN,1 pack (500 g),NaN,90.0,75.0,No,Yes,75.0,NaN,₹15 OFF,75.0,16,5,https://www.zepto.com/pn/tata-sampann-easy-cook-ragi-atta/pvid/4321e603-486d-4de8-a146-48d353992e19,NaN
2,2026-07-23 01:15:38,zepto,aa443b4b-bf3b-499c-a846-bf5196d444ae,"Vikaspuri Road, Vikaspuri Rd, Manohar Nagar, Vikaspuri, Delhi, 110018, India",Delhi,110018,7ff95977-a477-4d2a-acec-61fc8d1bcea2,d24fcfb1-fb69-4c91-8a76-a348a5f90a7b,"Atta, Rice & Dal","Atta, Rice, Oil & Dals",Millets & Other Flours,NaN,Weikfield,Weikfield Corn Starch Powder| Gluten-Free Cornflour for Baking| Perfect Thickening,NaN,500 g,NaN,1 pack (500 g),NaN,89.0,84.0,No,Yes,84.0,NaN,₹5 OFF,84.0,5,1,https://www.zepto.com/pn/weikfield-corn-starch-powder-gluten-free-cornflour-for-baking-perfect-thickening/pvid/7ff95977-a477-4d2a-acec-61fc8d1bcea2,NaN
3,2026-07-23 01:15:38,zepto,aa443b4b-bf3b-499c-a846-bf5196d444ae,"Vikaspuri Road, Vikaspuri Rd, Manohar Nagar, Vikaspuri, Delhi, 110018, India",Delhi,110018,c0781799-72e5-4bb2-8b82-d96ffe9aab6f,dc4e1c46-1225-4fa6-94c3-01aadef9d8c8,"Atta, Rice & Dal","Atta, Rice, Oil & Dals",Millets & Other Flours,NaN,Organic Tattva,Organic Tattva Ragi Atta,NaN,500 g,NaN,1 pack (500 g),NaN,95.0,89.0,No,Yes,89.0,NaN,₹6 OFF,89.0,6,1,https://www.zepto.com/pn/organic-tattva-ragi-atta/pvid/c0781799-72e5-4bb2-8b82-d96ffe9aab6f,NaN
4,2026-07-23 01:15:38,zepto,aa443b4b-bf3b-499c-a846-bf5196d444ae,"Vikaspuri Road, Vikaspuri Rd, Manohar Nagar, Vikaspuri, Delhi, 110018, India",Delhi,110018,295dca45-3a22-4ce7-a3ca-5345c2549eb0,58974140-c679-466b-9971-2114f9b3a753,"Atta, Rice & Dal","Atta, Rice, Oil & Dals",Millets & Other Flours,NaN,Daily Good,Daily Good Jowar Flour / Sorghum Millet,NaN,500 g,NaN,1 pack (500 g),NaN,75.0,46.0,No,Yes,46.0,NaN,₹29 OFF,46.0,38,6,https://www.zepto.com/pn/daily-good-jowar-flour-sorghum-millet/pvid/295dca45-3a22-4ce7-a3ca-5345c2549eb0,NaN

In [6]:
df.isnull().sum()

crawl_date_and_time             0
platform_name                   0
store_id                        0
store_name_location             0
city                            0
pin_code                        0
unique_id                       0
product_id_upc_ean              0
department                      0
category                        0
sub_category                    0
product_type               165326
brand_name                      0
product_name                    0
product_description        165326
product_grammage            28257
package_type               165326
net_quantity                    0
variants                   162457
item_mrp                        0
item_selling_price              0
out_of_stock_flag               0
discount_flag                   0
product_price                   0
unit_price                 165326
promo_offer_description         0
promo_offer_price               0
discount_in_percent             0
stock_count                     0
product_url                     0
product_image_urls         165326
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.nunique()

crawl_date_and_time        5131
platform_name                 1
store_id                     63
store_name_location          60
city                          1
pin_code                     39
unique_id                  5508
product_id_upc_ean         5375
department                   10
category                     24
sub_category                150
product_type                  0
brand_name                  939
product_name               5124
product_description           0
product_grammage            566
package_type                  0
net_quantity                916
variants                     89
item_mrp                    784
item_selling_price         1340
out_of_stock_flag             2
discount_flag                 2
product_price              1340
unit_price                    0
promo_offer_description     836
promo_offer_price          1340
discount_in_percent          88
stock_count                  51
product_url                5508
product_image_urls            0
dtype: int64

In [9]:
df.city.value_counts()

city
Delhi    165326
Name: count, dtype: int64

In [10]:
import pandas as pd

# Missing product_grammage
grammage_missing = (
    df["product_grammage"].isna() |
    (df["product_grammage"].astype(str).str.strip() == "")
)

# net_quantity contains a measurement inside parentheses
pattern = r"\(\s*[\d.,]+\s*(g|kg|mg|ml|l)\s*(?:or\s*[\d.,]+\s*(g|kg|mg|ml|l))?(?:\s*\+\s*[\d.,]+\s*(g|kg|mg|ml|l))*\s*\)"

mask = df["net_quantity"].fillna("").str.contains(
    pattern,
    case=False,
    regex=True,
    na=False
)

issues = df[grammage_missing & mask]

print("Rows found:", len(issues))

issues[[
    "unique_id",
    "product_name",
    "net_quantity",
    "product_grammage"
]]

Rows found: 0

/tmp/ipykernel_12970/5463894.py:12: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  mask = df["net_quantity"].fillna("").str.contains(

Empty DataFrame
Columns: [unique_id, product_name, net_quantity, product_grammage]
Index: []

In [11]:
city_department = pd.crosstab(df["city"], df["department"])

city_department

department,"Atta, Rice & Dal",Baby Care,Bakery & Biscuits,Beauty & Cosmetics,Cold Drinks & Juices,Dairy & Breakfast,Munchies,Organic & Premium,Personal Care,Sweet Tooth
city,,,,,,,,,,
Delhi,7307,21181,14035,25600,16345,20084,8513,18444,23169,10648

In [12]:
### city wise category distribution
city_category = pd.crosstab(df["city"], df["category"])

# Cities where any category is missing
missing_categories = city_category[city_category.eq(0).any(axis=1)]

missing_categories

Empty DataFrame
Columns: [Atta, Rice, Oil & Dals, Baby Care, Bath & Body, Biscuits, Breakfast & Sauces, Cold Drinks & Juices, Dairy, Bread & Eggs, Electronics & Appliances, Feminine Hygiene, Fragrances & Grooming, Frozen Food, Hair Care, Ice Creams & More, Makeup & Beauty, Masala, Dry Fruits & More, Munchies, Packaged Food, Pharma & Wellness, Skincare, Stationery & Books, Sweet Cravings, Tea, Coffee & More, Toys & Sports, Zepto Cafe]
Index: []

In [13]:
dept_category = (
    df.groupby("department")["category"]
    .apply(lambda x: sorted(x.unique()))
    .reset_index()
)

dept_category

,department,category
0,"Atta, Rice & Dal","[Atta, Rice, Oil & Dals]"
1,Baby Care,"[Baby Care, Packaged Food, Pharma & Wellness, Stationery & Books, Toys & Sports]"
2,Bakery & Biscuits,"[Biscuits, Dairy, Bread & Eggs, Packaged Food, Sweet Cravings]"
3,Beauty & Cosmetics,"[Fragrances & Grooming, Hair Care, Makeup & Beauty, Skincare]"
4,Cold Drinks & Juices,"[Cold Drinks & Juices, Dairy, Bread & Eggs, Ice Creams & More, Packaged Food, Pharma & Wellness, Tea, Coffee & More, Zepto Cafe]"
5,Dairy & Breakfast,"[Breakfast & Sauces, Dairy, Bread & Eggs, Frozen Food, Munchies, Packaged Food]"
6,Munchies,"[Biscuits, Masala, Dry Fruits & More, Munchies, Packaged Food]"
7,Organic & Premium,"[Atta, Rice, Oil & Dals, Biscuits, Breakfast & Sauces, Masala, Dry Fruits & More, Munchies, Packaged Food, Sweet Cravings, Tea, Coffee & More, Zepto Cafe]"
8,Personal Care,"[Baby Care, Bath & Body, Electronics & Appliances, Feminine Hygiene, Fragrances & Grooming, Skincare]"
9,Sweet Tooth,"[Bath & Body, Biscuits, Dairy, Bread & Eggs, Frozen Food, Ice Creams & More, Munchies, Sweet Cravings]"

In [14]:
master = df[["department", "category"]].drop_duplicates()
city_stock = (
    df.groupby("city")["out_of_stock_flag"]
    .value_counts()
    .unstack(fill_value=0)
)

city_stock["Total"] = city_stock.sum(axis=1)
city_stock["Out_of_stock_%"] = (
    city_stock["Yes"] / city_stock["Total"] * 100
).round(2)

city_stock.sort_values("Out_of_stock_%", ascending=False)

out_of_stock_flag      No    Yes   Total  Out_of_stock_%
city
Delhi              123699  41627  165326           25.18

In [15]:
dept_stock = (
    df.groupby("department")["out_of_stock_flag"]
    .value_counts()
    .unstack(fill_value=0)
)

dept_stock["Total"] = dept_stock.sum(axis=1)
dept_stock["Out_of_stock_%"] = (
    dept_stock["Yes"] / dept_stock["Total"] * 100
).round(2)

dept_stock.sort_values("Out_of_stock_%", ascending=False)

out_of_stock_flag        No   Yes  Total  Out_of_stock_%
department
Baby Care             14366  6815  21181           32.18
Personal Care         16570  6599  23169           28.48
Beauty & Cosmetics    18677  6923  25600           27.04
Dairy & Breakfast     14773  5311  20084           26.44
Sweet Tooth            7839  2809  10648           26.38
Cold Drinks & Juices  12157  4188  16345           25.62
Bakery & Biscuits     10856  3179  14035           22.65
Organic & Premium     15147  3297  18444           17.88
Atta, Rice & Dal       6056  1251   7307           17.12
Munchies               7258  1255   8513           14.74

In [16]:

cat_stock = (
    df.groupby("category")["out_of_stock_flag"]
    .value_counts()
    .unstack(fill_value=0)
)

cat_stock["Total"] = cat_stock.sum(axis=1)
cat_stock["Out_of_stock_%"] = (
    cat_stock["Yes"] / cat_stock["Total"] * 100
).round(2)

cat_stock.sort_values("Out_of_stock_%", ascending=False)

out_of_stock_flag             No   Yes  Total  Out_of_stock_%
category
Zepto Cafe                    87   597    684           87.28
Pharma & Wellness             83    63    146           43.15
Electronics & Appliances     361   227    588           38.61
Baby Care                   7304  4000  11304           35.39
Makeup & Beauty             3754  1986   5740           34.60
Dairy, Bread & Eggs         8469  4415  12884           34.27
Fragrances & Grooming       2746  1378   4124           33.41
Toys & Sports               6491  2486   8977           27.69
Skincare                   11467  4311  15778           27.32
Ice Creams & More           6176  2293   8469           27.08
Feminine Hygiene            4255  1493   5748           25.97
Bath & Body                 7481  2357   9838           23.96
Hair Care                   5074  1587   6661           23.83
Biscuits                    7377  2130   9507           22.40
Cold Drinks & Juices        8285  2367  10652           22.22
Sweet Cravings              5562  1525   7087           21.52
Atta, Rice, Oil & Dals      9011  2195  11206           19.59
Munchies                    7797  1855   9652           19.22
Packaged Food               5649  1341   6990           19.18
Tea, Coffee & More          4348   972   5320           18.27
Masala, Dry Fruits & More   4729   899   5628           15.97
Breakfast & Sauces          6006   989   6995           14.14
Frozen Food                 1174   160   1334           11.99
Stationery & Books            13     1     14            7.14

In [17]:
df.columns

Index(['crawl_date_and_time', 'platform_name', 'store_id',
       'store_name_location', 'city', 'pin_code', 'unique_id',
       'product_id_upc_ean', 'department', 'category', 'sub_category',
       'product_type', 'brand_name', 'product_name', 'product_description',
       'product_grammage', 'package_type', 'net_quantity', 'variants',
       'item_mrp', 'item_selling_price', 'out_of_stock_flag', 'discount_flag',
       'product_price', 'unit_price', 'promo_offer_description',
       'promo_offer_price', 'discount_in_percent', 'stock_count',
       'product_url', 'product_image_urls'],
      dtype='object')

In [3]:
df["brand_name"].value_counts()

brand_name
Amul                         4276
Britannia                    2298
Daily Good                   2281
Toyshine                     1855
Haldiram's                   1817
Mother Dairy                 1702
Colgate                      1631
Fablue                       1577
Parle                        1437
Kellogg's                    1286
Tata Sampann                 1164
Nivea                        1129
Himalaya Baby Care           1032
Cetaphil                     1031
Fortune                      1012
Frubon                        991
4700BC                        988
L'Oreal                       973
Sebamed                       971
Whisper                       970
LuvLap                        955
Mee Mee                       925
Minimalist                    890
Pee Safe                      876
Dot & Key                     831
MTR                           789
Nua                           767
Mamaearth                     765
Real                          764
Sunfeast                      762
Vaseline                      749
Go Zero                       748
Nescafe                       748
Organic Tattva                742
Puramate                      721
Parachute                     717
Unibic                        712
Oral-B                        694
Zepto Cafe                    684
Plum                          680
Mother Sparsh                 664
Rajdhani                      660
BUNDLE                        658
Cadbury                       658
Philips Baby Care             645
Nutraj                        635
Pintola                       631
Bisleri                       629
Gubb                          629
Milky Mist                    625
Yoga Bar                      619
Johnson's Baby                619
Chicco                        615
Farmley                       615
The Body Shop                 602
Pilgrim                       598
Se7en                         584
Let's try                     584
Epigamia                      579
TMI COLMAN                    577
Cream Bell                    574
Maggi                         574
Act II                        573
The Derma Co                  571
Hershey's                     570
Vadilal                       564
Lakme                         564
Garnier                       561
The Baker's Dozen             560
Aashirvaad                    558
Sirona                        549
Dove                          547
Country Delight               538
Cornitos                      531
Glucon D                      527
Prasuma                       517
Vega BCA                      511
Dukes                         507
Pansari                       502
24 Mantra                     500
Maybelline                    491
mCaffeine                     490
Kissan                        489
Nutralite                     485
Mars Cosmetics                485
Sensodyne                     481
The Health Factory            480
Kadence                       480
Harvest Gold                  479
Blue Heaven                   478
Wild Stone                    477
Pampers                       474
Himalaya BPC                  464
Bella Vita Organic            464
Sleepy Owl                    462
Grameen                       461
Foxtale                       454
Veeba                         449
MyFitness                     446
Deepak                        432
India Gate                    432
McVitie's                     427
O3+                           421
Listerine                     419
iD Fresh                      419
Pond's                        414
Super Bottoms                 410
Doritos                       404
Daawat                        402
Havmor                        399
MOM                           398
Beardo                        396
Godrej Yummiez                395
Organic India                 395
Hasbro                        384
PATANJALI                     380
Davidoff                      378
Renee                         376
Perfora                       373
Phab                          368
Streax                        368
Oreo                          367
Sofit                         367
Cavin's                       366
Tetley                        361
Get-A-Way                     360
Max Protein                   360
MasterChow                    357
Superyou                      350
Stayfree                      349
So Good                       348
Park Avenue                   338
Monster-S                     337
Weikfield                     337
Swiss Beauty                  333
O'cean Beverages              328
Lindt                         328
Slurrp Farm                   328
Hocco Ice Creams              328
Sofy                          326
CeraVe                        325
Dr. Oetker Fun Foods          320
Slovic                        320
Littles Expert Baby Care      319
Be Bodywise                   316
Mamypoko                      316
Wonderland Foods              313
Ching's Secret                312
Disano                        312
Bingo!                        311
The Whole Truth               307
Sanfe                         304
Samyang                       304
Open Secret PF                298
Neutrogena                    295
Dabur Oral Care               294
Lipton                        294
Giani's                       294
Hot Wheels                    293
SUGAR POP                     292
English Oven                  289
Britannia Breads              288
MINUS THIRTY                  288
Kwality Wall's                283
Nestle Nutrition              282
L'Oreal Professional          282
NOTO                          282
Kimirica                      281
Dlecta                        272
Desi Farms                    271
DearJoy                       271
Bombay Shaving Company        271
Hilary Rhoda                  271
Tedibar Family                270
Sugar Free                    270
Khetika                       269
EGGOZ                         268
Kloy                          267
Perrier Imported              264
Insight Cosmetics             264
Coloressence                  262
Pears                         260
Patanjali                     260
Denver                        257
Cinthol                       255
Nycil                         255
Fiama                         254
Happa                         253
Bioderma                      252
Everyuth                      251
Deconstruct                   248
Awenest                       246
Saffola Foods                 245
Natureland Organics           243
Bonn                          240
Boldfit                       238
R For Rabbit                  236
Carmesi                       235
Rajdhani FM                   235
Coca-Cola US                  233
Azah                          232
Nestle                        231
Paper Boat                    230
TRESemme                      229
Raw Pressery                  228
Mattel Games                  227
WishCare                      227
Dehaat Honest Farms           227
Pepsi                         226
BestValue                     225
Crax                          224
Hellmann's                    224
Ferrero Rocher                224
Wingreens                     223
The Theatre Project           222
Evereve                       221
Wagh Bakri                    221
Orbit                         220
Malkist                       219
Tata Tea Premium              219
Troovy                        219
Tang                          219
Bikaji                        218
Alpino                        216
Eat Better Co                 216
FURR                          215
Baskin Robbins                215
Dettol                        215
Ananda                        214
Cream Pot                     213
Mimo                          212
Rasna                         212
Red Bull                      212
Lacto Calamine                211
Faces Canada                  210
MOOZ Formaggio                209
Bronson Professional          209
Midazzle                      207
Schwarzkopf                   206
Moxie Beauty                  205
Lifelong                      200
The Face Shop                 196
Candid                        194
Bumtum                        193
Bagrry's                      193
Plush                         190
Pillsbury                     189
Baker's Loaf                  188
Dabur Skin Care               188
Yardley London                187
Kwality Wall's Magnum         186
Ajmal                         186
Old Spice                     184
Catch Drinks                  184
Orion                         184
Lotus Dairy                   183
Mother's Recipe               182
Joy                           182
Fixderma                      182
Smoodh                        182
Livon                         182
Plix -The Plant Fix           181
Lay's                         181
Bru                           181
Nutella 2024                  180
the little farm co.           180
Go Cheese                     179
Lal Sweets                    179
Agapi                         179
Heritage                      179
Kwality Wall's Cornetto       178
Wembley                       178
Gowardhan                     177
Gillette                      177
Chupa Chups                   177
Uttam Sugar                   177
Catch                         177
Alpenliebe                    176
Dhampur Green                 176
Lijjat                        176
Dhampure                      176
Tops                          175
Snapin                        173
Carnivore                     173
Paradyes                      172
Lux                           171
HELL Energy Drink             170
Bournville                    170
Dabur OTC                     170
Uapan                         169
Safe Harvest                  168
Bombae                        166
Moms Home                     165
Enn Beauty                    163
Plix The Plant Fix            162
Pigeon Baby Care              161
Del Monte                     161
Gits                          160
Toblerone                     159
Venusia                       157
The Ordinary                  156
Philips                       156
OM Sweets                     155
Salt                          155
Awestuffs                     150
Hira Fragrances               149
Parksons                      147
The Select Aisle              145
Lavian Exotique               145
Morde                         144
Teddyy                        144
Storio                        143
The Belgian Waffle Co         142
Mangat Ram                    142
Anugrah                       141
Shakti Bhog                   141
Lotte                         141
VIKRAM MILLS                  141
Lotus Biscoff                 141
Engage                        141
Skippi Icepops                140
Oxyglow Herbals               140
Soulflower                    139
Alt Co.                       138
Tata Coffee Grand             138
Cremeitalia                   137
Abhi Eggs                     136
Tropicana Delight             135
Galaxy                        135
Thums Up                      135
Sundrop                       135
Babique                       135
Coca Cola                     135
Frooti                        135
Cremica                       135
Urban Eggs                    135
Quaker                        134
Doodhvale Farms               134
DR.hen                        134
Britannia Dairy               134
MuscleBlaze                   134
Bloody Bubbly                 134
Mawana                        132
Tata Tea Gold                 132
Boomer                        132
Happydent                     132
Snackible                     132
Clean & Clear                 132
Figaro                        132
Anmol                         132
Red Label                     132
Navratna                      132
Meatzza                       131
Jivo                          131
Taj Mahal                     131
Juarez                        130
Saffola                       130
Mr Makhana                    130
Red Label Natural Care        130
Dermi Cool                    129
Zyro                          129
Dabur Hommade                 128
Ghar Soaps                    128
Godrej No.1                   127
Arora Eggs                    127
Nutrisum                      126
Only Earth                    126
Happilo                       126
Warner Bro.Action Figures     126
Aptamil                       125
Quench Botanics               123
Bare Anatomy                  123
inde wild                     123
Burrf                         120
Closeup                       120
Re'Equil                      120
Choki Choki                   120
OYO Baby                      118
Dexolac                       118
Beautiliss                    118
Instant Ice Cubes             117
Kit-Kat                       117
The Cinnamon Kitchen          117
Heinz                         117
Namyaa                        114
Chokola                       113
TGL Co.                       112
Loacker                       110
Munch                         108
GO Desi                       108
VLCC                          106
Justherbs                     106
Fix My Curls                  105
Matrix                        104
LetsShave                     103
Huber & Holly                 103
Jovees Herbal                 103
Galact                        102
Daadi's                       102
Moccona                       101
Striders                      101
Palekar                        99
Webby                          98
CLASSIC                        98
Dermatouch                     98
Jimmy's                        97
Jaguar                         97
Ustraa                         96
UV Doux                        96
921                            95
Hamleys                        95
Aravalli                       95
Twinings                       94
Yonex                          94
Biotique                       94
SUGAR Cosmetics                93
Cravova                        93
Set Wet                        93
Pepsi Imported                 93
Schweppes                      92
Bajaj Consumer Care            92
B Natural                      92
Head & Shoulders               92
WhiteTone                      92
Panda's Box                    92
Wickedgud                      91
Beyond Snack                   91
Amma's                         91
Uncle Chipps                   91
Andaah                         91
Natural Food                   91
Dalda                          91
Tulips                         91
Kurkure                        91
Fast&up                        91
Coke Zero                      91
Yu Foods                       91
Rishta                         91
OPI                            91
Glow & Lovely                  90
Conscious Food                 90
Sting                          90
Dairy Craft                    90
Modern Kitchen                 90
Keya                           90
Praakritik                     90
Limca                          90
Simmply                        90
Sprite                         90
Dabur Honey                    90
Yellow Diamond                 89
Stroom                         89
Too Yumm!                      89
Moi Soi                        89
Ice Craft                      89
Annkoot                        89
Pro Plant                      89
Pulse                          89
ZOFF                           89
Knorr                          88
Aruba                          88
Aditi Toys                     88
Dhara                          88
Wai Wai                        88
Tata Tea Agni                  88
9Am                            88
Candyman                       88
Bikano                         88
Taaza                          88
Ammamma's                      88
Z-Eggss Organic                88
Humpy Farms                    88
Blue Tea                       87
Smart One                      87
Himalayan Natives              87
Bevzilla                       87
Winkies                        87
Unifit                         86
Chemist at Play                86
Emami Healthy and Tasty        86
Fogg                           86
BLA BLI BLU                    85
Rexona                         85
Mysore Sandal                  85
Nongshim                       85
Imagimake                      84
Aqualogica                     84
Funskool                       84
The Man Company                84
Fruitchill                     84
Backbay                        83
Episoft                        82
Chyll                          82
VWash                          82
Hyphen                         81
Bigen                          81
Fabelle                        81
Pepsodent                      80
Cosrx                          79
STIM                           79
Habbits                        79
Khari Foods                    79
UPF                            79
Love Beauty & Planet           79
BabyPro                        78
Indimix                        78
Laneige                        78
Winkin Cow                     77
Love Earth                     77
Forest Essentials              76
Similac                        76
Loyka                          75
Kenaz                          74
Arata                          74
Clean & Dry                    74
Smart And Handsome             74
NIC                            73
Baby Forest                    73
Kidology                       73
Milkybar                       72
Nuttoz                         72
ICE CUBEs                      72
Kinder                         72
ITOYS                          72
NIINE                          71
The Natural Wash               71
Bburago                        69
Aveeno Baby                    68
Arun Ice Creams                67
Wella Professionals            66
LuxaDerme                      66
Bio Oil                        64
Wowzers                        64
La Shield                      64
TIRTIR                         63
Ahaglow                        63
Polka Tots                     63
Olay                           62
Skillmatics                    62
Thank You Farmer               57
Zuari                          57
Mirada                         57
Hamdard OTC                    57
Chigy Wooh                     56
Creativity for Kids            56
Little Joys                    56
Kidsmate                       56
Axe                            54
Bontress Pro                   54
Dapr.                          53
Veet                           53
Nexxus                         52
Oracura                        52
Innisfree                      52
Patch Up                       52
My Orl-Care                    52
Skin1004                       52
Nature Fresh                   50
Simple                         49
Indulekha                      49
Cuddles                        49
Huggies                        48
Farmlite                       48
Right Shift                    48
Devaaya                        48
Protein Chef                   48
Kohinoor                       48
Awsum                          48
Mayor                          48
Pantene                        48
Faber-Castell                  48
Cadbury CHOCOBAKES             48
Zeeba                          48
Raaga                          48
bonn                           48
Americana                      47
Bauli                          47
Dabur Baby                     47
Naturbaked                     47
Jabsons                        47
Clinic Plus                    47
Sunder                         47
Sunsilk                        47
Creambell Milkshake            47
Red Bull - US                  47
Adrenaline Rush                47
Dabur Hair Care                47

In [4]:
brand_summary = (
    df.groupby("brand_name", dropna=False)
      .agg(
          total_rows=("brand_name", "size"),
          unique_products=("unique_id", "nunique"),
          unique_urls=("product_url", "nunique"),
          unique_product_names=("product_name", "nunique"),
          unique_categories=("category", "nunique"),
          unique_departments=("department", "nunique"),
          unique_cities=("city", "nunique"),
          urls=("product_url", lambda x: sorted(set(x.dropna()))),
          product_names=("product_name", lambda x: sorted(set(x.dropna()))),
          categories=("category", lambda x: sorted(set(x.dropna()))),
          departments=("department", lambda x: sorted(set(x.dropna())))
      )
      .reset_index()
      .sort_values("total_rows", ascending=False)
)

brand_summary.head()

     brand_name  total_rows  unique_products  unique_urls  \
28         Amul        4276              123          123
122   Britannia        2298               56           56
211  Daily Good        2281               65           65
850    Toyshine        1855               68           68
348  Haldiram's        1817               50           50

     unique_product_names  unique_categories  unique_departments  \
28                    109                  7                   6
122                    38                  2                   1
211                    53                  3                   4
850                    68                  3                   1
348                    49                  4                   4

     unique_cities  \
28               1
122              1
211              1
850              1
348              1

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     urls  \

In [5]:
import re

url_pattern = re.compile(
    r"^https?://[^\s/$.?#].[^\s]*$",
    re.IGNORECASE
)

invalid_urls = df[
    df["product_url"].isna() |
    ~df["product_url"].astype(str).str.match(url_pattern)
]

print(f"Invalid URLs: {len(invalid_urls)}")
print(invalid_urls[["unique_id", "product_url"]])

Invalid URLs: 0
Empty DataFrame
Columns: [unique_id, product_url]
Index: []

In [6]:
store_oos = (
    df.pivot_table(
        index=["city", "store_id"],
        columns="out_of_stock_flag",
        aggfunc="size",
        fill_value=0
    )
    .reset_index()
)

# Ensure both columns exist
for col in ["Yes", "No"]:
    if col not in store_oos.columns:
        store_oos[col] = 0

store_oos["Total"] = store_oos["Yes"] + store_oos["No"]
store_oos["Out_of_stock_%"] = (
    store_oos["Yes"] / store_oos["Total"] * 100
).round(2)

store_oos = store_oos.sort_values(
    "Out_of_stock_%",
    ascending=False
)

store_oos

out_of_stock_flag,city,store_id,No,Yes,Total,Out_of_stock_%
4,Delhi,1585f304-7c1d-404d-b925-84bd48e90433,1836,1531,3367,45.47
15,Delhi,31a8b99d-0d1a-4f32-a367-e6cf62bb8603,2034,1591,3625,43.89
35,Delhi,7e586f3d-8e30-4859-8851-4476b8a965f4,2014,1548,3562,43.46
1,Delhi,05c5bd1a-d9b2-4ea3-848c-d8ae96b1d04a,434,298,732,40.71
57,Delhi,f02ef084-eab2-4651-8168-a4814b97ca06,2007,1305,3312,39.40
10,Delhi,261b9c45-eb5b-4398-be1c-909ccde6f629,1925,1249,3174,39.35
54,Delhi,ead42923-cfd0-4a7d-bb71-b879631773f1,1203,764,1967,38.84
34,Delhi,73952e1c-38a1-40a3-b71f-a4150849ee52,2159,1315,3474,37.85
23,Delhi,49d9df40-6b3b-4f3e-ad7d-bda18f57d419,1921,1160,3081,37.65
60,Delhi,f2e8316d-0937-4104-bae3-a24d608bb09c,2270,1334,3604,37.01
27,Delhi,57fbfbc2-6ec0-4465-aff3-81e771faf303,2042,1111,3153,35.24
59,Delhi,f2818431-48b5-4b57-9ec5-02e8eef7bc92,944,509,1453,35.03
0,Delhi,01e98a7e-46d7-48f1-bbcd-8e864116e992,1351,721,2072,34.80
50,Delhi,c951a741-faf1-4189-be8c-e441b6985190,783,408,1191,34.26
6,Delhi,1edbc6f5-f8dd-4dd0-9555-a8a5d90dd2d7,2124,1098,3222,34.08
12,Delhi,2baf335a-045a-4401-8761-a53b44b5cdcd,1951,832,2783,29.90
45,Delhi,b8aed0f4-59e0-4387-825d-406800150b71,2562,1076,3638,29.58
32,Delhi,6118ee4c-ee70-4b20-b071-f8e5e39fb7be,1728,725,2453,29.56
16,Delhi,321b0b48-7137-4832-ab17-f131421bdb78,2189,891,3080,28.93
41,Delhi,a5ff49ab-36f4-4aa6-b66e-de385f5d147b,1061,427,1488,28.70
29,Delhi,5d8ec059-9f5f-4867-8520-b232a1ebde3d,2123,843,2966,28.42
13,Delhi,2fa35ecf-4334-4ec6-b6de-5bae11a3dbf7,2672,1000,3672,27.23
25,Delhi,55bbe2f9-33f4-4ce0-a864-9730284b2a7c,2602,908,3510,25.87
19,Delhi,3d03e7a7-4ded-458a-9349-2978cd333ef0,2656,872,3528,24.72
9,Delhi,2522b064-b9af-4967-9c41-2bfffe8786d3,2132,698,2830,24.66
53,Delhi,e1befcff-e3d0-4fce-929c-50b9b6ae296f,2430,761,3191,23.85
46,Delhi,b8d61fbc-eb4a-4836-b785-e3b63aa3fa62,2135,667,2802,23.80
5,Delhi,1c3ca061-43e6-4119-85c3-76e51106a606,2538,786,3324,23.65
39,Delhi,96a968d7-aca7-4b78-9302-ef72fbb1cc57,2648,799,3447,23.18
14,Delhi,3072e208-7b9a-4821-a000-e121ba8a43fa,2802,787,3589,21.93
42,Delhi,aa443b4b-bf3b-499c-a846-bf5196d444ae,2383,653,3036,21.51
55,Delhi,ebc222f1-119b-457b-a137-3a4cfa10c571,2653,726,3379,21.49
40,Delhi,9bb503dd-63be-4b26-b2ba-8fe51192d2bd,1281,346,1627,21.27
3,Delhi,10655b62-1ead-42a2-a02c-d7a749951d48,2436,643,3079,20.88
26,Delhi,57a0c2ae-1cf1-4c4a-99eb-eb2e19864075,1233,323,1556,20.76
61,Delhi,f36075d2-40c9-4e63-a9d0-4fe36b2ca31f,2502,630,3132,20.11
43,Delhi,ad2daf79-44db-459d-9a45-d7807b5b37a2,2865,713,3578,19.93
30,Delhi,5dbd7e40-75db-452c-bd76-7dac3d7c0c0b,1149,279,1428,19.54
51,Delhi,c978abd4-1b79-40d2-ab47-ec19b7c29d41,1203,287,1490,19.26
48,Delhi,c73b0824-ac1e-43eb-98e4-ed5b849a651b,2871,676,3547,19.06
8,Delhi,23e18cbf-7e46-49ec-a559-d5a6cdb09d3b,2147,497,2644,18.80
28,Delhi,5cad640b-fe79-43bb-aac2-849733defb55,2105,477,2582,18.47
56,Delhi,efaa6e99-a68b-4c31-a50a-1bc5712533d7,1180,259,1439,18.00
38,Delhi,94f50df3-fb2e-4c36-ad6f-8a00bfd1c6af,1290,277,1567,17.68
22,Delhi,444a442d-982b-437d-a8eb-9ca9385eaed5,2403,509,2912,17.48
33,Delhi,681003a8-bce8-4481-980d-8253746471e6,1280,271,1551,17.47
7,Delhi,207df3d7-87f9-4b65-b6be-8e7114d22512,525,111,636,17.45
24,Delhi,4ba5f414-34e0-442c-938e-ef76fc9804bf,2621,549,3170,17.32
2,Delhi,0c865653-8eac-4a33-900c-d2ed7f3c0477,2615,540,3155,17.12
37,Delhi,8dde3f32-eae6-42e2-a9cc-ada2f0a9d22f,1325,271,1596,16.98
47,Delhi,c620a3ce-ee2e-493f-a83d-5555531fd861,1175,233,1408,16.55
31,Delhi,5ebdb9c0-59e0-436c-9e67-5594e00a45af,2545,504,3049,16.53
21,Delhi,4332c938-8582-4628-95d9-2844086daf78,2480,480,2960,16.22
36,Delhi,852818aa-dfa5-4943-b2b5-1cd51c26bdd5,2677,494,3171,15.58
58,Delhi,f090d50a-60ed-4b98-9493-3f0d9751a3f3,2197,397,2594,15.30
18,Delhi,3a9d3627-e56b-4584-ab9f-ed78e1903ed4,2546,458,3004,15.25
52,Delhi,e0a0c84c-0819-482e-8b95-55d4b32592d8,1242,214,1456,14.70
17,Delhi,34420157-825b-4822-acc8-9f20ae822fe3,2705,458,3163,14.48
44,Delhi,b5c0eebd-0709-4d34-9530-d4540f4db62f,2359,397,2756,14.40
49,Delhi,c8e077b9-6eec-4317-8254-6fd9eca59bed,2506,400,2906,13.76
62,Delhi,f88dd0bb-dc4a-400c-badc-d8fc18aeaeb7,1311,209,1520,13.75
20,Delhi,3f23fe21-69e5-4b46-9e90-809b609a3131,1287,178,1465,12.15
11,Delhi,2a655482-29d6-48fd-bb6c-6051fb5900ee,1326,154,1480,10.41

In [7]:
import pandas as pd

# Ensure stock_count is numeric
df["stock_count"] = pd.to_numeric(df["stock_count"], errors="coerce")

# Normalize out_of_stock_flag
flag = df["out_of_stock_flag"].astype(str).str.strip().str.lower()

# 1. out_of_stock_flag = Yes, but stock_count > 0
yes_stock_gt0 = df[
    (flag == "yes") &
    (df["stock_count"] > 0)
]

print(f"Rows with out_of_stock_flag='Yes' but stock_count > 0: {len(yes_stock_gt0)}")
print(yes_stock_gt0[["unique_id", "product_name", "store_id", "stock_count", "out_of_stock_flag"]])

# 2. out_of_stock_flag = No, but stock_count = 0
no_stock_0 = df[
    (flag == "no") &
    (df["stock_count"] == 0)
]

print(f"\nRows with out_of_stock_flag='No' but stock_count = 0: {len(no_stock_0)}")
print(no_stock_0[["unique_id", "product_name", "store_id", "stock_count", "out_of_stock_flag"]])

Rows with out_of_stock_flag='Yes' but stock_count > 0: 0
Empty DataFrame
Columns: [unique_id, product_name, store_id, stock_count, out_of_stock_flag]
Index: []

Rows with out_of_stock_flag='No' but stock_count = 0: 0
Empty DataFrame
Columns: [unique_id, product_name, store_id, stock_count, out_of_stock_flag]
Index: []

In [8]:
import pandas as pd

# Convert price columns to numeric
price_cols = [
    "item_mrp",
    "item_selling_price",
    "discount_in_percent"
]

for col in price_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

# Normalize discount flag
flag = df["discount_flag"].astype(str).str.strip().str.lower()

# 1. Selling Price > MRP
selling_gt_mrp = df[df["item_selling_price"] > df["item_mrp"]]

print(f"1. Selling Price > MRP : {len(selling_gt_mrp)} rows")
print(selling_gt_mrp[[
    "unique_id",
    "product_name",
    "item_mrp",
    "item_selling_price"
]])

# 2. Discount Flag = Yes but MRP == Selling Price
discount_no_difference = df[
    (flag == "yes") &
    (df["item_mrp"] == df["item_selling_price"])
]

print(f"\n2. Discount Flag = Yes but MRP == Selling Price : {len(discount_no_difference)} rows")
print(discount_no_difference[[
    "unique_id",
    "product_name",
    "item_mrp",
    "item_selling_price",
    "discount_flag"
]])

# 3. Discount % > 100
discount_gt_100 = df[df["discount_in_percent"] > 100]

print(f"\n3. Discount % > 100 : {len(discount_gt_100)} rows")
print(discount_gt_100[[
    "unique_id",
    "product_name",
    "item_mrp",
    "item_selling_price",
    "discount_in_percent"
]])

1. Selling Price > MRP : 0 rows
Empty DataFrame
Columns: [unique_id, product_name, item_mrp, item_selling_price]
Index: []

2. Discount Flag = Yes but MRP == Selling Price : 0 rows
Empty DataFrame
Columns: [unique_id, product_name, item_mrp, item_selling_price, discount_flag]
Index: []

3. Discount % > 100 : 0 rows
Empty DataFrame
Columns: [unique_id, product_name, item_mrp, item_selling_price, discount_in_percent]
Index: []

In [9]:
url_name_issues = (
    df.groupby("product_id_upc_ean")
      .agg(
          product_count=("product_name", "nunique"),
          product_names=("product_name", lambda x: sorted(set(x)))
      )
      .reset_index()
)

url_name_issues = url_name_issues[url_name_issues["product_count"] > 1]

print("URLs with different product names:", len(url_name_issues))
url_name_issues.head()

URLs with different product names: 0

Empty DataFrame
Columns: [product_id_upc_ean, product_count, product_names]
Index: []

In [10]:
result = (
    df.groupby("product_url")
      .agg(
          product_count=("product_name", "nunique"),
          product_names=("product_name", lambda x: sorted(set(x))),
          unique_ids=("unique_id", lambda x: sorted(set(x))),
          product_ids=("product_id_upc_ean", lambda x: sorted(set(x)))
      )
      .reset_index()
)

# Keep only URLs mapped to multiple product names
result = result[result["product_count"] > 1]

print(f"Found {len(result)} URLs with different product names.")
result

Found 0 URLs with different product names.

Empty DataFrame
Columns: [product_url, product_count, product_names, unique_ids, product_ids]
Index: []

In [11]:
top10_longest = (
    df.drop_duplicates(subset="product_name")
      .assign(name_length=lambda x: x["product_name"].fillna("").str.len())
      .sort_values("name_length", ascending=False)
      [["unique_id", "name_length", "product_name", "product_url"]]
      .head(10)
)

print(top10_longest)

                                  unique_id  name_length  \
30741  7e1c699f-d191-4be4-9314-3506b1a75b97          389
30734  edd24376-4a56-4c30-bc25-17740efa5f75          206
71861  58caf284-73d7-4a9e-ab54-eb51f6b197f5          204
29766  7cfc3765-fcc7-41e0-8a86-f39bd0c19271          186
10198  05099171-d97f-4169-99d8-2f6fc01a0c22          170
1289   4907f3af-c281-4005-aff6-a9aa3b2d76d9          169
1286   f7b9124f-022b-4896-a7a6-8c546d89a996          169
9704   4b45a46c-7559-4707-bc8a-a013171cfed1          158
4254   f6271978-512b-4f18-9786-db39a78754ac          154
10780  be7e109b-ec7a-4aa4-b147-51c48a5a1d5b          139

                                                                                                                                                                                                                                                                                                                                                                                                product_name  \
30741  Deconstruct Brightening Lip Balm Spf 50 | Vitamin C & Resorcinol | Moisturizes & Brightens (4g) & Deconstruct Gel Sunscreen Spf 55+ Pa+++ | In Vivo Tested | Matte, Lightweight & Airy, Non-Greasy (50g) & Deconstruct Oil-Free Moisturizer | Lightweight, Non-Sticky, Non-Comedogenic | For Oily Skin (50g) & Deconstruct 10% Vitamin C Serum For Oily Skin | Clinically Tested | 30 Ml (30ml) Combo
30734                                                                                                                                                                                         Deconstruct Brightening Lip Balm Spf 50 | Vitamin C & Resorcinol | Moisturizes & Brightens (4g) & Deconstruct Gel Sunscreen Spf 55+ Pa+++ | In Vivo Tested | Matte, Lightweight & Airy, Non-Greasy (50g) Combo
71861                                                                                                                                                                                           Sirona Heavy Flow Tampons | Organic Cotton Core | Ultra-High Absorbency And Leak-Proof Protection (20pc) & Sirona Herbal Period Pain Relief Patches| Relief From Menstrual Cramps | Cool Patches (5pc) Combo
29766                                                                                                                                                                                                             Hyphen 7% Ceramides-Nmf Face Toner Essence | 5% Glass Skin Blend With Rice Water (100ml) & Hyphen 18% Brightening + 20% Collagen Double Serum | 5% Niacinamide For Dark Spots (50ml) Combo
10198                                                                                                                                                                                                                             Plum Green Tea Pore Cleansing Face Wash Fights Pimples & Removes Excess Oil Enriched With Green Tea & Glycolic Acid Best Suits Oily Acne-Prone Combination Skin 100% Vegan
1289                                                                                                                                                                                                                               Colgate Batman Toothbrush For Kids, Battery Powered Electric Toothbrush, Age 3+, Kids Toothbrush With Extra Soft Bristles And Slim Handle, Includes Replaceable Batteries
1286                                                                                                                                                                                                                               Colgate Barbie Toothbrush For Kids, Battery Powered Electric Toothbrush, Age 3+, Kids Toothbrush With Extra Soft Bristles And Slim Handle, Includes Replaceable Batteries
9704                                                                                                                                                                                                                                          Spinz BB Brightening & Beauty Face Talc for Instant Brightness that Lasts 2X Longer Covers Dark Spots and Blemishes Gives Soft and Smooth Skin (Natural Beige)
4254                                                                                                                                                                                                                                              Fast&Up Reload Berry Instant Energy Drink 5 Essential Electrolytes(20pc) & Fast&Up Reload Orange Instant Energy Drink 5 Essential Electrolytes(20pc) Combo
10780                                                                                                                                                                                                                                                            Carmesi Body Razor for Women's Hair Removal With Travel Case 5-Blade Precision Smooth & Hassle-Free Shaving on the Go Aloe Vera & Vitamin E

                                                                                                                                                                                                                                                                                                                                                                                                                       product_url
30741  https://www.zepto.com/pn/deconstruct-brightening-lip-balm-spf-50-vitamin-c-resorcinol-moisturizes-brightens-4g-deconstruct-gel-sunscreen-spf-55-pa-in-vivo-tested-matte-lightweight-airy-non-greasy-50g-deconstruct-oil-free-moisturizer-lightweight-non-sticky-non-comedogenic-for-oily-skin-50g-deconstruct-10-vitamin-c-serum-for-oily-skin-clinically-tested-30-ml-30ml-combo/pvid/7e1c699f-d191-4be4-9314-3506b1a75b97
30734                                                                                                                                                                      https://www.zepto.com/pn/deconstruct-brightening-lip-balm-spf-50-vitamin-c-resorcinol-moisturizes-brightens-4g-deconstruct-gel-sunscreen-spf-55-pa-in-vivo-tested-matte-lightweight-airy-non-greasy-50g-combo/pvid/edd24376-4a56-4c30-bc25-17740efa5f75
71861                                                                                                                                                           https://www.zepto.com/pn/sirona-heavy-flow-tampons-organic-cotton-core-ultra-high-absorbency-and-leak-proof-protection-20pc-sirona-herbal-period-pain-relief-patches-relief-from-menstrual-cramps-cool-patches-5pc-combo/pvid/58caf284-73d7-4a9e-ab54-eb51f6b197f5
29766                                                                                                                                                                                 https://www.zepto.com/pn/hyphen-7-ceramides-nmf-face-toner-essence-5-glass-skin-blend-with-rice-water-100ml-hyphen-18-brightening-20-collagen-double-serum-5-niacinamide-for-dark-spots-50ml-combo/pvid/7cfc3765-fcc7-41e0-8a86-f39bd0c19271
10198                                                                                                                                                                                     https://www.zepto.com/pn/plum-green-tea-pore-cleansing-face-wash-fights-pimples-removes-excess-oil-enriched-with-green-tea-glycolic-acid-best-suits-oily-acne-prone-combination-skin-100-vegan/pvid/05099171-d97f-4169-99d8-2f6fc01a0c22
1289                                                                                                                                                                                       https://www.zepto.com/pn/colgate-batman-toothbrush-for-kids-battery-powered-electric-toothbrush-age-3-kids-toothbrush-with-extra-soft-bristles-and-slim-handle-includes-replaceable-batteries/pvid/4907f3af-c281-4005-aff6-a9aa3b2d76d9
1286                                                                                                                                                                                       https://www.zepto.com/pn/colgate-barbie-toothbrush-for-kids-battery-powered-electric-toothbrush-age-3-kids-toothbrush-with-extra-soft-bristles-and-slim-handle-includes-replaceable-batteries/pvid/f7b9124f-022b-4896-a7a6-8c546d89a996
9704                                                                                                                                                                                                 https://www.zepto.com/pn/spinz-bb-brightening-beauty-face-talc-for-instant-brightness-that-lasts-2x-longer-covers-dark-spots-and-blemishes-gives-soft-and-smooth-skin-natural-beige/pvid/4b45a46c-7559-4707-bc8a-a013171cfed1
4254                                                                                                                                                                                                         https://www.zepto.com/pn/fastup-reload-berry-instant-energy-drink-5-essential-electrolytes20pc-fastup-reload-orange-instant-energy-drink-5-essential-electrolytes20pc-combo/pvid/f6271978-512b-4f18-9786-db39a78754ac
10780                                                                                                                                                                                                                    https://www.zepto.com/pn/carmesi-body-razor-for-womens-hair-removal-with-travel-case-5-blade-precision-smooth-hassle-free-shaving-on-the-go-aloe-vera-vitamin-e/pvid/be7e109b-ec7a-4aa4-b147-51c48a5a1d5b

In [12]:
# 1. Group by identity columns to isolate the exact same physical product
product_identity_issues = (
    df.groupby(["unique_id", "product_grammage", "net_quantity"])
    .agg(
        # Count how many different spelling/name variations exist for this product
        name_variant_count=("product_name", "nunique"),
        # Create an alphabetised list of those unique name variations
        name_variants=("product_name", lambda x: sorted(set(x))),
        # Optional: capture variations in brand name for the same product
        brand_variants=("brand_name", lambda x: sorted(set(x.dropna()))),
    )
    .reset_index()
)

# 2. Filter for rows where the same product has more than 1 name variation
name_issues_by_id = product_identity_issues[
    product_identity_issues["name_variant_count"] > 1
]

# 3. View the final flagged discrepancies
print(name_issues_by_id)

Empty DataFrame
Columns: [unique_id, product_grammage, net_quantity, name_variant_count, name_variants, brand_variants]
Index: []

In [13]:
product_identity_issues = (
    df.groupby(["unique_id", "product_grammage", "net_quantity"])
    .agg(
        name_variant_count=("product_name", "nunique"),
        name_variants=("product_name", lambda x: sorted(set(x))),
        brand_variants=("brand_name", lambda x: sorted(set(x.dropna()))),
        url_count=("product_url", "nunique"),
        product_urls=("product_url", lambda x: sorted(set(x.dropna())))
    )
    .reset_index()
)

name_issues_by_id = product_identity_issues[
    product_identity_issues["name_variant_count"] > 1
]

name_issues_by_id

Empty DataFrame
Columns: [unique_id, product_grammage, net_quantity, name_variant_count, name_variants, brand_variants, url_count, product_urls]
Index: []

In [14]:
subcat_dist = (
    df["sub_category"]
    .value_counts(dropna=False)
    .rename_axis("sub_category")
    .reset_index(name="product_count")
)

subcat_dist

                   sub_category  product_count
0            Face Wash & Scrubs           4250
1                   Rice & More           2746
2            Face Creams & Gels           2356
3                Chips & Crisps           2274
4     Body Lotion & Moisturizer           2265
5             Toothbrush & More           2195
6                      Perfumes           1835
7                    Chocolates           1764
8                     Baby Bath           1608
9                       Cookies           1558
10   Baking Mixes & Ingredients           1536
11                Breads & Buns           1531
12             Pastries & Cakes           1525
13   Dry Fruits & Nuts Munchies           1524
14                     Namkeens           1522
15                Dals & Pulses           1511
16                  Energy Bars           1476
17         Besan, Sooji & Maida           1466
18               Baby Diapering           1464
19                      Gifting           1463
20           Yogurt & Shrikhand           1463
21                  Milk Drinks           1456
22                       Sticks           1447
23                Soda & Mixers           1445
24            Dry Fruits & Nuts           1440
25           Beauty Accessories           1439
26                         Atta           1438
27              Honey & Spreads           1436
28    Papads, Pickles & Chutney           1436
29                       Nachos           1431
30                      Popcorn           1425
31                         Milk           1425
32                Peanut Butter           1425
33                    Face Care           1423
34                         Tubs           1416
35               Paneer & Cream           1415
36    Whole Spices & Seasonings           1412
37                  Soft Drinks           1412
38       Cold Coffee & Iced Tea           1408
39             Ketchup & Sauces           1408
40                          Oil           1397
41                     Crackers           1395
42                       Butter           1393
43        Salt, Sugar & Jaggery           1393
44              Glucose & Marie           1392
45           Premium Chocolates           1387
46            Breakfast Cereals           1386
47                Dates & Seeds           1383
48        Candies, Gums & Mints           1382
49                         Eggs           1382
50                       Cheese           1381
51                   Creamfills           1378
52                        Soaps           1369
53       Millets & Other Flours           1365
54         Noodles & Vermicelli           1364
55           Green & Herbal Tea           1363
56        Fruit Juices & Drinks           1362
57                          Tea           1345
58                Muesli & Oats           1340
59                   Hair Color           1329
60                 Rusk & Khari           1324
61                   Digestives           1301
62       Sausages, Salami & Ham           1298
63         Ice Cubes & Ice Pops           1286
64               Baby Oral Care           1284
65                         Ghee           1283
66              Deos & Roll Ons           1275
67        Baby Skin & Hair Care           1271
68                 Vegan Drinks           1264
69                Sanitary Pads           1263
70          Instant Drink Mixes           1259
71                 Energy Drink           1258
72                Talcum Powder           1254
73                        Cones           1249
74                      Shampoo           1242
75                Ready To Cook           1241
76                   Toothpaste           1227
77             Serums & Essence           1223
78               Eye & Lip Care           1218
79                    Mouthwash           1206
80                       Coffee           1204
81                        Water           1196
82                       Wafers           1159
83               Period Panties           1149
84     Cakes, Sandwiches & More           1137
85    Educational Toys & Sports           1091
86          Conditioner & Masks           1085
87                        Kulfi           1073
88                  Shower Gels           1071
89       Hair Removal For Women           1060
90             Sports & Fitness           1045
91          Hair Serum & Polish           1038
92                Indian Mithai           1029
93              Batters & Mixes           1028
94               Men's Grooming           1014
95                   Eye Makeup           1002
96                 Baby Hygiene            988
97                   Baby Wipes            983
98                     Hair Oil            974
99                  Lips Makeup            968
100                Hair Styling            961
101           Milk Based Drinks            951
102                 Baby Health            913
103      Curd & Probiotic Drink            892
104          Card & Board Games            880
105                 Infant Food            876
106                        Cups            861
107                Baby Feeding            859
108                    Sun Care            855
109              Toners & Mists            821
110                 Face Makeup            821
111                   Soft Toys            814
112                       Nails            812
113            Bath Accessories            751
114          Baby & Mom Gifting            730
115   Activities & Outdoor Toys            724
116                   Body Care            689
117            Hand & Feet Care            678
118             Doll & Play Set            675
119                 Art & Craft            651
120                     Tampons            609
121                    Grooming            588
122               Intimate Care            581
123                     Toddler            573
124                Panty Liners            569
125   Electronic Toys & Vehicle            568
126            Blocks & Puzzles            549
127              Action Figures            546
128                    Mom Care            506
129         Musical Instruments            449
130              Cold Beverages            446
131         Musical Accessories            412
132         Baby & Toddler Food            397
133             Infant Clothing            277
134              Toilet Hygiene            274
135                   Baby Gear            223
136          Period Pain Relief            202
137                Tea & Coffee            199
138                 Baby Safety            198
139                Ready To Eat            140
140                    Ayurveda             60
141  Rehydration & Electrolytes             44
142         Vitamin Supplements             42
143             Personal Safety             41
144                  Veg Snacks             36
145    Hair Tools & Accessories             32
146                     Healthy             25
147               Indian Breads             23
148              Crafts & Hobby             14
149                      Snacks             14

In [15]:
subcat_by_category = (
    pd.crosstab(
        df["category"],
        df["sub_category"]
    )
)

subcat_by_category

sub_category,Action Figures,Activities & Outdoor Toys,Art & Craft,Atta,Ayurveda,Baby & Mom Gifting,Baby & Toddler Food,Baby Bath,Baby Diapering,Baby Feeding,Baby Gear,Baby Health,Baby Hygiene,Baby Oral Care,Baby Safety,Baby Skin & Hair Care,Baby Wipes,Baking Mixes & Ingredients,Bath Accessories,Batters & Mixes,Beauty Accessories,"Besan, Sooji & Maida",Blocks & Puzzles,Body Care,Body Lotion & Moisturizer,Breads & Buns,Breakfast Cereals,Butter,"Cakes, Sandwiches & More","Candies, Gums & Mints",Card & Board Games,Cheese,Chips & Crisps,Chocolates,Coffee,Cold Beverages,Cold Coffee & Iced Tea,Conditioner & Masks,Cones,Cookies,Crackers,Crafts & Hobby,Creamfills,Cups,Curd & Probiotic Drink,Dals & Pulses,Dates & Seeds,Deos & Roll Ons,Digestives,Doll & Play Set,Dry Fruits & Nuts,Dry Fruits & Nuts Munchies,Educational Toys & Sports,Eggs,Electronic Toys & Vehicle,Energy Bars,Energy Drink,Eye & Lip Care,Eye Makeup,Face Care,Face Creams & Gels,Face Makeup,Face Wash & Scrubs,Fruit Juices & Drinks,Ghee,Gifting,Glucose & Marie,Green & Herbal Tea,Grooming,Hair Color,Hair Oil,Hair Removal For Women,Hair Serum & Polish,Hair Styling,Hair Tools & Accessories,Hand & Feet Care,Healthy,Honey & Spreads,Ice Cubes & Ice Pops,Indian Breads,Indian Mithai,Infant Clothing,Infant Food,Instant Drink Mixes,Intimate Care,Ketchup & Sauces,Kulfi,Lips Makeup,Men's Grooming,Milk,Milk Based Drinks,Milk Drinks,Millets & Other Flours,Mom Care,Mouthwash,Muesli & Oats,Musical Accessories,Musical Instruments,Nachos,Nails,Namkeens,Noodles & Vermicelli,Oil,Paneer & Cream,Panty Liners,"Papads, Pickles & Chutney",Pastries & Cakes,Peanut Butter,Perfumes,Period Pain Relief,Period Panties,Personal Safety,Popcorn,Premium Chocolates,Ready To Cook,Ready To Eat,Rehydration & Electrolytes,Rice & More,Rusk & Khari,"Salt, Sugar & Jaggery",Sanitary Pads,"Sausages, Salami & Ham",Serums & Essence,Shampoo,Shower Gels,Snacks,Soaps,Soda & Mixers,Soft Drinks,Soft Toys,Sports & Fitness,Sticks,Sun Care,Talcum Powder,Tampons,Tea,Tea & Coffee,Toddler,Toilet Hygiene,Toners & Mists,Toothbrush & More,Toothpaste,Tubs,Veg Snacks,Vegan Drinks,Vitamin Supplements,Wafers,Water,Whole Spices & Seasonings,Yogurt & Shrikhand
category,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
"Atta, Rice, Oil & Dals",0,0,0,1438,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1466,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1511,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1283,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1365,0,0,0,0,0,0,0,0,0,1397,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2746,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Baby Care,0,0,0,0,0,730,0,1608,1464,859,223,913,988,1284,198,1271,983,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,277,0,0,0,0,0,0,0,0,0,0,0,506,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Bath & Body,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,751,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,765,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1206,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1071,0,1369,0,0,0,0,0,0,1254,0,0,0,0,0,0,2195,1227,0,0,0,0,0,0,0,0
Biscuits,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1558,1395,0,1378,0,0,0,0,0,1301,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1392,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1324,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1159,0,0,0
Breakfast & Sauces,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1386,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1436,0,0,0,0,0,0,0,1408,0,0,0,0,0,0,0,0,0,1340,0,0,0,0,0,0,0,0,0,0,0,1425,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Cold Drinks & Juices,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1258,0,0,0,0,0,0,1362,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1259,0,0,0,0,0,0,0,1456,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1445,1412,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1264,0,0,1196,0,0
"Dairy, Bread & Eggs",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1028,0,0,0,0,0,1531,0,1393,0,0,0,1381,0,0,0,0,0,0,0,0,0,0,0,0,892,0,0,0,0,0,0,0,0,1382,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,23,0,0,0,0,0,0,0,0,0,1425,951,0,0,0,0,0,0,0,0,0,0,0,0,1415,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1463
Electronics & Appliances,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,588,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Feminine Hygiene,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1060,0,0,0,0,0,0,0,0,0,0,0,0,581,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,569,0,0,0,0,202,1149,41,0,0,0,0,0,0,0,0,1263,0,0,0,0,0,0,0,0,0,0,0,0,0,609,0,0,0,274,0,0,0,0,0,0,0,0,0,0,0
Fragrances & Grooming,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1275,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1014,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1835,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Frozen Food,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1298,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,36,0,0,0,0,0,0
Hair Care,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1085,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1329,974,0,1038,961,32,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1242,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Ice Creams & More,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1137,0,0,0,0,0,0,0,0,0,1249,0,0,0,0,861,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1286,0,0,0,0,0,0,0,1073,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1447,0,0,0,0,0,0,0,0,0,0,1416,0,0,0,0,0,0,0
Makeup & Beauty,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1439,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1002,0,0,821,0,0,0,698,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,968,0,0,0,0,0,0,0,0,0,0,0,812,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
"Masala, Dry Fruits & More",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1383,0,0,0,1440,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1393,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1412,0
Munchies,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2274,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1524,0,0,0,1476,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1431,0,1522,0,0,0,0,0,0,0,0,0,0,0,1425,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Packaged Food,0,0,0,0,0,0,397,0,0,0,0,0,0,0,0,0,0,1536,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,876,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1364,0,0,0,1436,0,0,0,0,0,0,0,0,1241,140,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Pharma & Wellness,0,0,0,0,60,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,44,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,42,0,0,0,0
Skincare,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,689,2265,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1218,0,1423,2356,0,4250,0,0,0,0,0,0,0,0,0,0,0,0,678,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1223,0,0,0,0,0,0,0,0,0,855,0,0,0,0,0,0,821,0,0,0,0,0,0,0,0,0,0
Stationery & Books,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,14,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Sweet Cravings,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1382,0,0,0,1764,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1029,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1525,0,0,0,0,0,0,1387,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
"Tea, Coffee & More",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1204,0,1408,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1363,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1345,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Toys & Sports,546,724,651,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,549,0,0,0,0,0,0,0,880,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,675,0,0,1091,0,568,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,412,449,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,814,1045,0,0,0,0,0,0,573,0,0,0,0,0,0,0,0,0,0,0,0
Zepto Cafe,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,446,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,25,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,14,0,0,0,0,0,0,0,0,0,0,199,0,0,0,0,0,0,0,0,0,0,0,0,0

In [16]:
subcat_by_department = (
    pd.crosstab(
        df["department"],
        df["sub_category"]
    )
)

subcat_by_department

sub_category,Action Figures,Activities & Outdoor Toys,Art & Craft,Atta,Ayurveda,Baby & Mom Gifting,Baby & Toddler Food,Baby Bath,Baby Diapering,Baby Feeding,Baby Gear,Baby Health,Baby Hygiene,Baby Oral Care,Baby Safety,Baby Skin & Hair Care,Baby Wipes,Baking Mixes & Ingredients,Bath Accessories,Batters & Mixes,Beauty Accessories,"Besan, Sooji & Maida",Blocks & Puzzles,Body Care,Body Lotion & Moisturizer,Breads & Buns,Breakfast Cereals,Butter,"Cakes, Sandwiches & More","Candies, Gums & Mints",Card & Board Games,Cheese,Chips & Crisps,Chocolates,Coffee,Cold Beverages,Cold Coffee & Iced Tea,Conditioner & Masks,Cones,Cookies,Crackers,Crafts & Hobby,Creamfills,Cups,Curd & Probiotic Drink,Dals & Pulses,Dates & Seeds,Deos & Roll Ons,Digestives,Doll & Play Set,Dry Fruits & Nuts,Dry Fruits & Nuts Munchies,Educational Toys & Sports,Eggs,Electronic Toys & Vehicle,Energy Bars,Energy Drink,Eye & Lip Care,Eye Makeup,Face Care,Face Creams & Gels,Face Makeup,Face Wash & Scrubs,Fruit Juices & Drinks,Ghee,Gifting,Glucose & Marie,Green & Herbal Tea,Grooming,Hair Color,Hair Oil,Hair Removal For Women,Hair Serum & Polish,Hair Styling,Hair Tools & Accessories,Hand & Feet Care,Healthy,Honey & Spreads,Ice Cubes & Ice Pops,Indian Breads,Indian Mithai,Infant Clothing,Infant Food,Instant Drink Mixes,Intimate Care,Ketchup & Sauces,Kulfi,Lips Makeup,Men's Grooming,Milk,Milk Based Drinks,Milk Drinks,Millets & Other Flours,Mom Care,Mouthwash,Muesli & Oats,Musical Accessories,Musical Instruments,Nachos,Nails,Namkeens,Noodles & Vermicelli,Oil,Paneer & Cream,Panty Liners,"Papads, Pickles & Chutney",Pastries & Cakes,Peanut Butter,Perfumes,Period Pain Relief,Period Panties,Personal Safety,Popcorn,Premium Chocolates,Ready To Cook,Ready To Eat,Rehydration & Electrolytes,Rice & More,Rusk & Khari,"Salt, Sugar & Jaggery",Sanitary Pads,"Sausages, Salami & Ham",Serums & Essence,Shampoo,Shower Gels,Snacks,Soaps,Soda & Mixers,Soft Drinks,Soft Toys,Sports & Fitness,Sticks,Sun Care,Talcum Powder,Tampons,Tea,Tea & Coffee,Toddler,Toilet Hygiene,Toners & Mists,Toothbrush & More,Toothpaste,Tubs,Veg Snacks,Vegan Drinks,Vitamin Supplements,Wafers,Water,Whole Spices & Seasonings,Yogurt & Shrikhand
department,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
"Atta, Rice & Dal",0,0,0,1438,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1466,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1511,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1365,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1527,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Baby Care,546,724,651,0,60,730,397,1165,1464,859,223,913,988,1284,198,1271,983,0,0,0,0,0,549,0,0,0,0,0,0,0,880,0,0,0,0,0,0,0,0,0,0,14,0,0,0,0,0,0,0,675,0,0,1091,0,568,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,277,876,0,0,0,0,0,0,0,0,0,0,460,0,0,412,449,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,814,1045,0,0,0,0,0,0,573,0,0,0,0,0,0,0,42,0,0,0,0
Bakery & Biscuits,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1536,0,0,0,0,0,0,0,1531,0,0,0,0,0,0,0,0,0,0,0,0,0,1506,1395,0,1378,0,0,0,0,0,1301,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1392,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1525,0,0,0,0,0,0,0,0,0,0,0,1322,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1149,0,0,0
Beauty & Cosmetics,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1439,0,0,689,1343,0,0,0,0,0,0,0,0,0,0,0,0,1085,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1218,1002,1423,1437,821,1677,0,0,698,0,0,0,1329,974,0,1038,961,32,678,0,0,0,0,0,0,0,0,0,0,0,968,0,0,0,0,0,0,0,0,0,0,0,812,0,0,0,0,0,0,0,0,1835,0,0,0,0,0,0,0,0,0,0,0,0,0,1223,1242,0,0,0,0,0,0,0,0,855,0,0,0,0,0,0,821,0,0,0,0,0,0,0,0,0,0
Cold Drinks & Juices,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,446,1408,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1258,0,0,0,0,0,0,1362,0,0,0,1363,0,0,0,0,0,0,0,0,25,0,1117,0,0,0,0,1259,0,0,0,0,0,0,951,1456,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,140,44,0,0,0,0,0,0,0,0,0,0,1445,1412,0,0,0,0,0,0,0,199,0,0,0,0,0,0,0,1264,0,0,1196,0,0
Dairy & Breakfast,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1028,0,0,0,0,0,0,1386,1393,0,0,0,1381,0,0,0,0,0,0,0,0,0,0,0,0,892,0,0,0,0,0,0,0,0,1382,0,1390,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1436,0,0,0,0,0,0,0,0,0,0,0,1425,0,0,0,0,0,1340,0,0,0,0,0,1364,0,1415,0,0,0,1425,0,0,0,0,0,0,66,0,0,0,0,0,0,1298,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1463
Munchies,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1349,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1440,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1431,0,1430,0,0,0,0,1436,0,0,0,0,0,0,1425,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Organic & Premium,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1382,0,0,925,900,1204,0,0,0,0,42,0,0,0,0,0,0,1383,0,0,0,0,1524,0,0,0,0,0,0,0,0,0,0,0,0,1283,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1408,0,0,0,0,0,0,0,0,0,0,0,0,0,0,92,0,1397,0,0,0,0,0,0,0,0,0,0,346,1175,0,0,1219,0,1393,0,0,0,0,0,14,0,0,0,0,0,0,0,0,0,1345,0,0,0,0,0,0,0,0,0,0,0,0,1412,0
Personal Care,0,0,0,0,0,0,0,443,0,0,0,0,0,0,0,0,0,0,751,0,0,0,0,0,922,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1275,0,0,0,0,0,0,0,0,0,0,0,0,919,0,2573,0,0,765,0,0,588,0,0,1060,0,0,0,0,0,0,0,0,0,0,0,0,581,0,0,0,1014,0,0,0,0,46,1009,0,0,0,0,0,0,0,0,0,569,0,0,0,0,202,1149,41,0,0,0,0,0,0,0,0,1263,0,0,0,1071,0,1369,0,0,0,0,0,0,1254,609,0,0,0,274,0,2195,1227,0,0,0,0,0,0,0,0
Sweet Tooth,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1137,0,0,0,0,864,0,0,0,0,1249,10,0,0,0,861,0,0,0,0,0,0,0,0,0,0,0,86,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,169,23,1029,0,0,0,0,0,1073,0,0,0,0,0,0,0,197,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1041,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1447,0,0,0,0,0,0,0,0,0,0,1416,36,0,0,10,0,0,0

In [17]:
summary = (
    df.groupby(["category", "sub_category"])
      .size()
      .reset_index(name="product_count")
      .sort_values(["category", "product_count"], ascending=[True, False])
)

summary

                      category                sub_category  product_count
6       Atta, Rice, Oil & Dals                 Rice & More           2746
2       Atta, Rice, Oil & Dals               Dals & Pulses           1511
1       Atta, Rice, Oil & Dals        Besan, Sooji & Maida           1466
0       Atta, Rice, Oil & Dals                        Atta           1438
5       Atta, Rice, Oil & Dals                         Oil           1397
4       Atta, Rice, Oil & Dals      Millets & Other Flours           1365
3       Atta, Rice, Oil & Dals                        Ghee           1283
8                    Baby Care                   Baby Bath           1608
9                    Baby Care              Baby Diapering           1464
14                   Baby Care              Baby Oral Care           1284
16                   Baby Care       Baby Skin & Hair Care           1271
13                   Baby Care                Baby Hygiene            988
17                   Baby Care                  Baby Wipes            983
12                   Baby Care                 Baby Health            913
10                   Baby Care                Baby Feeding            859
7                    Baby Care          Baby & Mom Gifting            730
19                   Baby Care                    Mom Care            506
18                   Baby Care             Infant Clothing            277
11                   Baby Care                   Baby Gear            223
15                   Baby Care                 Baby Safety            198
26                 Bath & Body           Toothbrush & More           2195
24                 Bath & Body                       Soaps           1369
25                 Bath & Body               Talcum Powder           1254
27                 Bath & Body                  Toothpaste           1227
22                 Bath & Body                   Mouthwash           1206
23                 Bath & Body                 Shower Gels           1071
21                 Bath & Body                     Gifting            765
20                 Bath & Body            Bath Accessories            751
28                    Biscuits                     Cookies           1558
29                    Biscuits                    Crackers           1395
32                    Biscuits             Glucose & Marie           1392
30                    Biscuits                  Creamfills           1378
33                    Biscuits                Rusk & Khari           1324
31                    Biscuits                  Digestives           1301
34                    Biscuits                      Wafers           1159
36          Breakfast & Sauces             Honey & Spreads           1436
39          Breakfast & Sauces               Peanut Butter           1425
37          Breakfast & Sauces            Ketchup & Sauces           1408
35          Breakfast & Sauces           Breakfast Cereals           1386
38          Breakfast & Sauces               Muesli & Oats           1340
43        Cold Drinks & Juices                 Milk Drinks           1456
44        Cold Drinks & Juices               Soda & Mixers           1445
45        Cold Drinks & Juices                 Soft Drinks           1412
41        Cold Drinks & Juices       Fruit Juices & Drinks           1362
46        Cold Drinks & Juices                Vegan Drinks           1264
42        Cold Drinks & Juices         Instant Drink Mixes           1259
40        Cold Drinks & Juices                Energy Drink           1258
47        Cold Drinks & Juices                       Water           1196
49         Dairy, Bread & Eggs               Breads & Buns           1531
58         Dairy, Bread & Eggs          Yogurt & Shrikhand           1463
55         Dairy, Bread & Eggs                        Milk           1425
57         Dairy, Bread & Eggs              Paneer & Cream           1415
50         Dairy, Bread & Eggs                      Butter           1393
53         Dairy, Bread & Eggs                        Eggs           1382
51         Dairy, Bread & Eggs                      Cheese           1381
48         Dairy, Bread & Eggs             Batters & Mixes           1028
56         Dairy, Bread & Eggs           Milk Based Drinks            951
52         Dairy, Bread & Eggs      Curd & Probiotic Drink            892
54         Dairy, Bread & Eggs               Indian Breads             23
59    Electronics & Appliances                    Grooming            588
66            Feminine Hygiene               Sanitary Pads           1263
64            Feminine Hygiene              Period Panties           1149
60            Feminine Hygiene      Hair Removal For Women           1060
67            Feminine Hygiene                     Tampons            609
61            Feminine Hygiene               Intimate Care            581
62            Feminine Hygiene                Panty Liners            569
68            Feminine Hygiene              Toilet Hygiene            274
63            Feminine Hygiene          Period Pain Relief            202
65            Feminine Hygiene             Personal Safety             41
71       Fragrances & Grooming                    Perfumes           1835
69       Fragrances & Grooming             Deos & Roll Ons           1275
70       Fragrances & Grooming              Men's Grooming           1014
72                 Frozen Food      Sausages, Salami & Ham           1298
73                 Frozen Food                  Veg Snacks             36
75                   Hair Care                  Hair Color           1329
80                   Hair Care                     Shampoo           1242
74                   Hair Care         Conditioner & Masks           1085
77                   Hair Care         Hair Serum & Polish           1038
76                   Hair Care                    Hair Oil            974
78                   Hair Care                Hair Styling            961
79                   Hair Care    Hair Tools & Accessories             32
86           Ice Creams & More                      Sticks           1447
87           Ice Creams & More                        Tubs           1416
84           Ice Creams & More        Ice Cubes & Ice Pops           1286
82           Ice Creams & More                       Cones           1249
81           Ice Creams & More    Cakes, Sandwiches & More           1137
85           Ice Creams & More                       Kulfi           1073
83           Ice Creams & More                        Cups            861
88             Makeup & Beauty          Beauty Accessories           1439
89             Makeup & Beauty                  Eye Makeup           1002
92             Makeup & Beauty                 Lips Makeup            968
90             Makeup & Beauty                 Face Makeup            821
93             Makeup & Beauty                       Nails            812
91             Makeup & Beauty                     Gifting            698
95   Masala, Dry Fruits & More           Dry Fruits & Nuts           1440
97   Masala, Dry Fruits & More   Whole Spices & Seasonings           1412
96   Masala, Dry Fruits & More       Salt, Sugar & Jaggery           1393
94   Masala, Dry Fruits & More               Dates & Seeds           1383
98                    Munchies              Chips & Crisps           2274
99                    Munchies  Dry Fruits & Nuts Munchies           1524
102                   Munchies                    Namkeens           1522
100                   Munchies                 Energy Bars           1476
101                   Munchies                      Nachos           1431
103                   Munchies                     Popcorn           1425
105              Packaged Food  Baking Mixes & Ingredients           1536
108              Packaged Food   Papads, Pickles & Chutney           1436
107              Packaged Food        Noodles & Vermicelli           1364
109              Packaged Food               Ready To Cook           1241
106              Packaged Food                 Infant Food            876
104              Packaged Food         Baby & Toddler Food            397
110              Packaged Food                Ready To Eat            140
111          Pharma & Wellness                    Ayurveda             60
112          Pharma & Wellness  Rehydration & Electrolytes             44
113          Pharma & Wellness         Vitamin Supplements             42
119                   Skincare          Face Wash & Scrubs           4250
118                   Skincare          Face Creams & Gels           2356
115                   Skincare   Body Lotion & Moisturizer           2265
117                   Skincare                   Face Care           1423
121                   Skincare            Serums & Essence           1223
116                   Skincare              Eye & Lip Care           1218
122                   Skincare                    Sun Care            855
123                   Skincare              Toners & Mists            821
114                   Skincare                   Body Care            689
120                   Skincare            Hand & Feet Care            678
124         Stationery & Books              Crafts & Hobby             14
126             Sweet Cravings                  Chocolates           1764
128             Sweet Cravings            Pastries & Cakes           1525
129             Sweet Cravings          Premium Chocolates           1387
125             Sweet Cravings       Candies, Gums & Mints           1382
127             Sweet Cravings               Indian Mithai           1029
131         Tea, Coffee & More      Cold Coffee & Iced Tea           1408
132         Tea, Coffee & More          Green & Herbal Tea           1363
133         Tea, Coffee & More                         Tea           1345
130         Tea, Coffee & More                      Coffee           1204
140              Toys & Sports   Educational Toys & Sports           1091
145              Toys & Sports            Sports & Fitness           1045
138              Toys & Sports          Card & Board Games            880
144              Toys & Sports                   Soft Toys            814
135              Toys & Sports   Activities & Outdoor Toys            724
139              Toys & Sports             Doll & Play Set            675
136              Toys & Sports                 Art & Craft            651
146              Toys & Sports                     Toddler            573
141              Toys & Sports   Electronic Toys & Vehicle            568
137              Toys & Sports            Blocks & Puzzles            549
134              Toys & Sports              Action Figures            546
143              Toys & Sports         Musical Instruments            449
142              Toys & Sports         Musical Accessories            412
147                 Zepto Cafe              Cold Beverages            446
150                 Zepto Cafe                Tea & Coffee            199
148                 Zepto Cafe                     Healthy             25
149                 Zepto Cafe                      Snacks             14

In [18]:
subcat_mapping = (
    df.groupby("sub_category")["category"]
      .agg(lambda x: sorted(set(x)))
      .reset_index(name="categories")
)

subcat_mapping["category_count"] = subcat_mapping["categories"].str.len()

issues = subcat_mapping[subcat_mapping["category_count"] > 1]

issues

   sub_category                      categories  category_count
65      Gifting  [Bath & Body, Makeup & Beauty]               2

In [20]:
summary = (
    df.groupby(["category", "sub_category"])
      .size()
      .reset_index(name="product_count")
      .sort_values("product_count", ascending=True)
)

summary

                      category                sub_category  product_count
124         Stationery & Books              Crafts & Hobby             14
149                 Zepto Cafe                      Snacks             14
54         Dairy, Bread & Eggs               Indian Breads             23
148                 Zepto Cafe                     Healthy             25
79                   Hair Care    Hair Tools & Accessories             32
73                 Frozen Food                  Veg Snacks             36
65            Feminine Hygiene             Personal Safety             41
113          Pharma & Wellness         Vitamin Supplements             42
112          Pharma & Wellness  Rehydration & Electrolytes             44
111          Pharma & Wellness                    Ayurveda             60
110              Packaged Food                Ready To Eat            140
15                   Baby Care                 Baby Safety            198
150                 Zepto Cafe                Tea & Coffee            199
63            Feminine Hygiene          Period Pain Relief            202
11                   Baby Care                   Baby Gear            223
68            Feminine Hygiene              Toilet Hygiene            274
18                   Baby Care             Infant Clothing            277
104              Packaged Food         Baby & Toddler Food            397
142              Toys & Sports         Musical Accessories            412
147                 Zepto Cafe              Cold Beverages            446
143              Toys & Sports         Musical Instruments            449
19                   Baby Care                    Mom Care            506
134              Toys & Sports              Action Figures            546
137              Toys & Sports            Blocks & Puzzles            549
141              Toys & Sports   Electronic Toys & Vehicle            568
62            Feminine Hygiene                Panty Liners            569
146              Toys & Sports                     Toddler            573
61            Feminine Hygiene               Intimate Care            581
59    Electronics & Appliances                    Grooming            588
67            Feminine Hygiene                     Tampons            609
136              Toys & Sports                 Art & Craft            651
139              Toys & Sports             Doll & Play Set            675
120                   Skincare            Hand & Feet Care            678
114                   Skincare                   Body Care            689
91             Makeup & Beauty                     Gifting            698
135              Toys & Sports   Activities & Outdoor Toys            724
7                    Baby Care          Baby & Mom Gifting            730
20                 Bath & Body            Bath Accessories            751
21                 Bath & Body                     Gifting            765
93             Makeup & Beauty                       Nails            812
144              Toys & Sports                   Soft Toys            814
90             Makeup & Beauty                 Face Makeup            821
123                   Skincare              Toners & Mists            821
122                   Skincare                    Sun Care            855
10                   Baby Care                Baby Feeding            859
83           Ice Creams & More                        Cups            861
106              Packaged Food                 Infant Food            876
138              Toys & Sports          Card & Board Games            880
52         Dairy, Bread & Eggs      Curd & Probiotic Drink            892
12                   Baby Care                 Baby Health            913
56         Dairy, Bread & Eggs           Milk Based Drinks            951
78                   Hair Care                Hair Styling            961
92             Makeup & Beauty                 Lips Makeup            968
76                   Hair Care                    Hair Oil            974
17                   Baby Care                  Baby Wipes            983
13                   Baby Care                Baby Hygiene            988
89             Makeup & Beauty                  Eye Makeup           1002
70       Fragrances & Grooming              Men's Grooming           1014
48         Dairy, Bread & Eggs             Batters & Mixes           1028
127             Sweet Cravings               Indian Mithai           1029
77                   Hair Care         Hair Serum & Polish           1038
145              Toys & Sports            Sports & Fitness           1045
60            Feminine Hygiene      Hair Removal For Women           1060
23                 Bath & Body                 Shower Gels           1071
85           Ice Creams & More                       Kulfi           1073
74                   Hair Care         Conditioner & Masks           1085
140              Toys & Sports   Educational Toys & Sports           1091
81           Ice Creams & More    Cakes, Sandwiches & More           1137
64            Feminine Hygiene              Period Panties           1149
34                    Biscuits                      Wafers           1159
47        Cold Drinks & Juices                       Water           1196
130         Tea, Coffee & More                      Coffee           1204
22                 Bath & Body                   Mouthwash           1206
116                   Skincare              Eye & Lip Care           1218
121                   Skincare            Serums & Essence           1223
27                 Bath & Body                  Toothpaste           1227
109              Packaged Food               Ready To Cook           1241
80                   Hair Care                     Shampoo           1242
82           Ice Creams & More                       Cones           1249
25                 Bath & Body               Talcum Powder           1254
40        Cold Drinks & Juices                Energy Drink           1258
42        Cold Drinks & Juices         Instant Drink Mixes           1259
66            Feminine Hygiene               Sanitary Pads           1263
46        Cold Drinks & Juices                Vegan Drinks           1264
16                   Baby Care       Baby Skin & Hair Care           1271
69       Fragrances & Grooming             Deos & Roll Ons           1275
3       Atta, Rice, Oil & Dals                        Ghee           1283
14                   Baby Care              Baby Oral Care           1284
84           Ice Creams & More        Ice Cubes & Ice Pops           1286
72                 Frozen Food      Sausages, Salami & Ham           1298
31                    Biscuits                  Digestives           1301
33                    Biscuits                Rusk & Khari           1324
75                   Hair Care                  Hair Color           1329
38          Breakfast & Sauces               Muesli & Oats           1340
133         Tea, Coffee & More                         Tea           1345
41        Cold Drinks & Juices       Fruit Juices & Drinks           1362
132         Tea, Coffee & More          Green & Herbal Tea           1363
107              Packaged Food        Noodles & Vermicelli           1364
4       Atta, Rice, Oil & Dals      Millets & Other Flours           1365
24                 Bath & Body                       Soaps           1369
30                    Biscuits                  Creamfills           1378
51         Dairy, Bread & Eggs                      Cheese           1381
125             Sweet Cravings       Candies, Gums & Mints           1382
53         Dairy, Bread & Eggs                        Eggs           1382
94   Masala, Dry Fruits & More               Dates & Seeds           1383
35          Breakfast & Sauces           Breakfast Cereals           1386
129             Sweet Cravings          Premium Chocolates           1387
32                    Biscuits             Glucose & Marie           1392
96   Masala, Dry Fruits & More       Salt, Sugar & Jaggery           1393
50         Dairy, Bread & Eggs                      Butter           1393
29                    Biscuits                    Crackers           1395
5       Atta, Rice, Oil & Dals                         Oil           1397
131         Tea, Coffee & More      Cold Coffee & Iced Tea           1408
37          Breakfast & Sauces            Ketchup & Sauces           1408
45        Cold Drinks & Juices                 Soft Drinks           1412
97   Masala, Dry Fruits & More   Whole Spices & Seasonings           1412
57         Dairy, Bread & Eggs              Paneer & Cream           1415
87           Ice Creams & More                        Tubs           1416
117                   Skincare                   Face Care           1423
103                   Munchies                     Popcorn           1425
55         Dairy, Bread & Eggs                        Milk           1425
39          Breakfast & Sauces               Peanut Butter           1425
101                   Munchies                      Nachos           1431
36          Breakfast & Sauces             Honey & Spreads           1436
108              Packaged Food   Papads, Pickles & Chutney           1436
0       Atta, Rice, Oil & Dals                        Atta           1438
88             Makeup & Beauty          Beauty Accessories           1439
95   Masala, Dry Fruits & More           Dry Fruits & Nuts           1440
44        Cold Drinks & Juices               Soda & Mixers           1445
86           Ice Creams & More                      Sticks           1447
43        Cold Drinks & Juices                 Milk Drinks           1456
58         Dairy, Bread & Eggs          Yogurt & Shrikhand           1463
9                    Baby Care              Baby Diapering           1464
1       Atta, Rice, Oil & Dals        Besan, Sooji & Maida           1466
100                   Munchies                 Energy Bars           1476
2       Atta, Rice, Oil & Dals               Dals & Pulses           1511
102                   Munchies                    Namkeens           1522
99                    Munchies  Dry Fruits & Nuts Munchies           1524
128             Sweet Cravings            Pastries & Cakes           1525
49         Dairy, Bread & Eggs               Breads & Buns           1531
105              Packaged Food  Baking Mixes & Ingredients           1536
28                    Biscuits                     Cookies           1558
8                    Baby Care                   Baby Bath           1608
126             Sweet Cravings                  Chocolates           1764
71       Fragrances & Grooming                    Perfumes           1835
26                 Bath & Body           Toothbrush & More           2195
115                   Skincare   Body Lotion & Moisturizer           2265
98                    Munchies              Chips & Crisps           2274
118                   Skincare          Face Creams & Gels           2356
6       Atta, Rice, Oil & Dals                 Rice & More           2746
119                   Skincare          Face Wash & Scrubs           4250